### ISSUE TITLE
Leer la documentación relacionada con el proyecto de planeación

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#1]
Se debe realizar la lectura de la documentación levantada hasta el momento para la apropiación del sistema, los documentos son 

- Formato formulación Plan de Acción, la cual corresponde a la plantilla empleada para la formulación del Plan de Acción 2022 de las Unidades, incluye dos componentes (actividades y presupuesto). [Link](https://drive.google.com/file/d/1L1ZdvxE1u8ynjXqQRS3CjBIPfuKIPsmQ/view?ts=60eed6ef)
- Lineamiento, Metas, Estrategias PED, contiene la estructura del PED actual. [Link](https://drive.google.com/file/d/11ltM_ByRifVPwvSQE6FNGixzil5-7Y0o/view?ts=60eed6ef)
- Instrumento de seguimiento al PED y el PI, el cual consolida el seguimiento al Plan Estratégico y el Plan Indicativo. [Link](https://drive.google.com/file/d/1zuZ5KOG0pov1GQ2FIu9jln55OI_ztb72/view?ts=60eed6ef)
- [Acta de reunión N°100 A_2021 - Planeación - Segunda mesa de trabajo Desarrollo para el Subsistema de Planeación, Gestión y Seguimiento de los Procesos (1)_signed.pdf](https://github.com/udistrital/planeacion_cliente/files/6844811/Acta.de.reunion.N.100.A_2021.-.Planeacion.-.Segunda.mesa.de.trabajo.Desarrollo.para.el.Subsistema.de.Planeacion.Gestion.y.Seguimiento.de.los.Procesos.1._signed.pdf)

**Comment by ndmc98** [comment]
Tarea realizada. Se efectuaron las lecturas de la documentación levantada hasta el momento para la apropiación del sistema.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
