### ISSUE TITLE
Implementar de la funcionalidad CRUD para la identificación de recursos y contratistas en el cliente 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#100]
Se debe implementar la funcionalidad CRUD desarrollada en la issue #90  en el cliente, se debe configurar el flujo para distinguir si es una creación del registro o una actualización del registro, eso se debe hacer realizando una petición get para saber si existe información y activar o no la bandera para la consulta o la creación, la issue debe cumplir con los siiguientes requerimientos:

- [x] Implementar el flujo con los requerimientos explicados

**Comment by ndmc98** [comment]
Se dio inicio a la issue el 03/11/2021

**Comment by ndmc98** [comment]
Se implementan los flujos para guardar y consultar la identificación de contratistas y recursos. Se cumple con la especificación de saber si existe o no la tabla para realizar operación PUT o POST según sea el caso. Se consumen las funciones de MID para guardar y consultar los registros de las tablas de identificación.

**Comment by ndmc98** [comment]
Se genera Pull Request para dar cierre a la issue.

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
