### ISSUE TITLE
Bug - Fallo en lectura de fechas habilitadas en seguimiento (toma las fechas del primer plan de acción asociado a la unidad y vigencia, y no las fechas del plan seleccionado)

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1004]
Se requiere realizar la corrección del consumo de fechas en el módulo de seguimiento al seleccionar un plan de acción en particular..

**Especificaciones técnicas**
- En el seguimiento de un plan de acción se debe ajustar el consumo de fechas acorde al plan seleccionado (actualmente se queda pegado a las fechas del primer plan de acción).
- La funcionalidad de seguimiento se encuentra próxima a despliegue a producción y entrega a usuario/cliente.

**Sub Tareas**

- [x] Se debe revisar el comportamiento de la petición que revisa las fechas parametrizadas para realizar el seguimiento de un plan de acción, dado que actualmente se quedan pegadas al primer plan de acción del desplegable.
- [x] Una vez identificado el error se debe documentar el issue con la causa y posible solución.
- [x] Se debe desarrollar la solución.
- [x] Se deben realizar pruebas funcionales evidenciando la corrección.

**Criterios de aceptación**

- [x] Se documenta el issue.
- [x] Se corrige el incidente.
- [x] Se realizan las respectivas pruebas de funcionamiento.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by ccmendezt** [comment]
## Evidencias - Avance Fallo en lectura de fechas habilitadas en seguimiento
### 01/05/2024 - 20:30

- Se agregó el parámetro _nueva_estructura_ al schema **periodo-seguimiento** para poder filtrar los registros y diferenciarlos de los nuevos registros:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/fb0ba059-b26e-4790-b8a2-f9d2d953300e)

- Se creó un nuevo caso en **planes_crud** para encontrar registros cuyo parámetro _nueva_estructura_ sea nulo, ya que no se puede hacer desde los query params. El cambio se puede apreciar en este commit: https://github.com/udistrital/planes_crud/commit/473a6c07f493580d803c0e77591c21eec81d12c3

- Se modificó **planeacion_mid** para que busque los registros de periodo-seguimiento antiguos usando el caso mencionado anteriormente. Los cambios se pueden apreciar en este commit: https://github.com/udistrital/planeacion_mid/commit/8dbcd26837f0844fbf65224e703fca1f78fb96e5

- Se modificó **planeacion_cliente** para que al endpoint que contiene el caso creado para obtener los registros. El cambio se puede apreciar en este commit: https://github.com/udistrital/planeacion_cliente/commit/885d1e74dea568cd94ed581ae9a24f843363eebc

## Notas importantes:
  **i.** Se debe crear un script que permita: crear un nuevo registro de periodo-seguimiento por cada trimestre de la vigencia con el parámetro nueva_estructura. Dicho registro contendrá en el campo unidades_interes a TODAS las unidades, el campo planes_interes tendrá el _id y nombre del plan de acción en formulado(s) en producción. De esa manera, cuando se quieran formular fechas de seguimiento para el plan, se podrá editar ese registro y crear nuevos.

**Comment by ccmendezt** [comment]
## Pull Request Asociados a Issue
### 02/05/2024 - 16:00 pm

- **planeacion_cliente:** https://github.com/udistrital/planeacion_cliente/pull/1030
- **planeacion_mid:** https://github.com/udistrital/planeacion_mid/pull/519
- **planes_crud:** https://github.com/udistrital/planes_crud/pull/102
