### ISSUE TITLE
Refactorización cliente planeacion_formulacion_mf

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1005]
Se requiere refactorizar el MF **PLANEACION_FORMULACION_MF** con base en el API **PLANEACION_CLIENTE**, de forma tal que se culmine con la migración de componentes y se presente el cliente en su forma final.

**Especificaciones técnicas**

1. El repositorio para **PLANEACION_FORMULACION_MF** es: https://github.com/udistrital/planeacion_formulacion_mf
2. Se requiere migrar los **nuevos desarrollos** (en caso de ser requerido) asociados a Formulación, del cliente **PLANEACION_CLIENTE** al MF **PLANEACION_FORMULACION_MF**. Tener en cuenta todos los ajustes, como por ejemplo: #982 , #983 , #997 , #1004 , entre otras.
3. El Cliente debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevos Clientes definidos por la OATI.
4. Los componentes y servicios que son globales a todos los MF deben ser Ubicados en la carpeta **UTILIDADES**.
5. Se debe optimizar el código migrado, eliminando malas practicas de desarrollo.
6. El MF debe quedar optimizado en estilos y con pruebas funcionales en su totalidad.
7. El MF debe consumir los endpoints asociados a los MicroMids desarrollados para SISGPLAN, en lugar de planeacion_mid.

**Sub Tareas**

- [x] Refactorización del cliente **PLANEACION_FORMULACION_MF**
- [x] Migración de nuevas funcionalidades.
- [x] Optimización de código.

**Criterios de aceptación**

- [x] El MF se encuentra refactorizado.
- [x] El MF cuenta con todas sus componentes y funcionalidades migrados.
- [x] El código del MF se encuentra optimizado.

**Requerimientos**

- [x] #939 .
- [x] #961 .

**Dependencias**

- planeacion_cliente
- planeacion_mid
- planeacion_formulacion_mid
- planeacion_formulacion_mf
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by felimarod** [comment]
Se necesitan permisos para subir cambios en el repositorio [planeacion_formulacion_mf](https://github.com/udistrital/planeacion_formulacion_mf)

![Image](https://github.com/udistrital/planeacion_cliente/assets/85894335/e32bc835-0e93-44e1-9b42-85af72ea2ef3)

Se agregaron las múltiples vinculaciones

![Image](https://github.com/udistrital/planeacion_cliente/assets/85894335/75d9cdd4-7966-4a7f-b820-5c785ddeefdc)

Se quito la opción de que se seleccione la unidad al traerla desde OIKOS_SERVICE

**Comment by felimarod** [comment]
Se agrego el desarrollo de #983 , en el MF
Se nota que la parte del MID no se encuentra en la API de pruebas de PLANES_MID

**Comment by a52290451** [comment]
@felimarod se conceden permisos en [planeacion_formulacion_mf](https://github.com/udistrital/planeacion_formulacion_mf) para subir los cambios correspondientes.

**Comment by felimarod** [comment]
Teniendo en cuenta las especificaciones tecnicas:
- Se han migrado los nuevos desarrollos a excepción del de la issue #997 
- Se utiliza la carpeta de utils, optimizando el código de la autenticación
- Se ha estado optimizando código conforme se ha estado editando, sin embargo falta avanzar en este mismo punto
- La configuración de los estilos sigue pendiente en los MF en general
- Se cambio el consumo de PLANEACION_MID a PLANEACION_ARBOL_MID y PLANEACION_FORMULACION_MID
    - Queda pendiente cambiar el endpoint de avalar plan desde PLANEACION_MID, este solo se encuentra ahí

**Comment by a52290451** [comment]
S

**Comment by a52290451** [comment]
Queda pendiente desplegar infraestructura.
