### ISSUE TITLE
Refactorización cliente planeacion_seguimiento_mf - PT 1

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1007]
Se requiere refactorizar el MF **PLANEACION_SEGUIMIENTO_MF** con base en el API **PLANEACION_CLIENTE**, de forma tal que se culmine con la migración de componentes y se presente el cliente en su forma final.

**Especificaciones técnicas**

1. El repositorio para **PLANEACION_SEGUIMIENTO_MF** es: https://github.com/udistrital/planeacion_seguimiento_mf
2. Se requiere migrar los **nuevos desarrollos** (en caso de ser requerido) asociados a Reportes, del cliente **PLANEACION_CLIENTE** al MF **PLANEACION_SEGUIMIENTO_MF**. Tener en cuenta todos los ajustes, como por ejemplo: #982 , #983 , #997 , #1004 , entre otras.
3. El Cliente debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevos Clientes definidos por la OATI.
4. Los componentes y servicios que son globales a todos los MF deben ser migrados al cliente **CORE** o de **UTILIDADES**.
5. Se debe optimizar el código migrado, eliminando malas practicas de desarrollo.
6. El MF debe quedar optimizado en estilos y con pruebas funcionales en su totalidad.
7. El MF debe consumir los endpoints asociados a los MicroMids desarrollados para SISGPLAN, en lugar de planeacion_mid.

**Sub Tareas**

- [x] Refactorización del cliente **PLANEACION_SEGUIMIENTO_MF**
- [x] Migración de nuevas funcionalidades.
- [x] Optimización de código.

**Criterios de aceptación**

- [x] El MF se encuentra refactorizado.
- [x] El MF cuenta con todas sus componentes y funcionalidades migrados.
- [x] El código del MF se encuentra optimizado.

**Requerimientos**

- [x] #943 , #952  .
- [x] #973 .

**Dependencias**

- planeacion_cliente
- planeacion_mid
- planeacion_reportes_mid
- planeacion_reportes_mf
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by C0C045** [comment]
# Avance refactorización cliente planeacion_seguimiento_mf
Avance asociado al siguiente commit: [4377f8b](https://github.com/udistrital/planeacion_seguimiento_mf/commit/4377f8bcd9d8728b6bd8f0be37d78f82aaf7c134)

1. En el desarrollo #983 no fue necesario implementar ningún cambio en seguimiento, por ende, no se tuvo en cuenta.
2. La implementación de #982 fue exitosa y actualmente ya se encuentra funcional en el microfrontend de seguimiento.
![982](https://github.com/udistrital/planeacion_cliente/assets/55455142/2258a765-8c02-476b-8500-c5c4bb572a15)

3. La solución de #1004 ya se encuentra implementada en el microfrontend de seguimiento y es funcional.
![1004](https://github.com/udistrital/planeacion_cliente/assets/55455142/3a7afa40-9d93-4da2-88fe-b39b7d1c290a)

4. Por último, queda pendiente la implementación de #997 , ya que su desarrollo aún no se encuentra culminado.

**Comment by C0C045** [comment]
# Observaciones refactorización planeacion_seguimiento_mf
1. Se implementó el cambio al endpoint de 'vinculación terceros' mostrado en #982 y se encuentra en el siguiente pull request: https://github.com/udistrital/planeacion_formulacion_mid/pull/5
2. Debido a que el micromid de seguimiento (#972 ) tiene algunas inconsistencias respecto a lo planteado en #948 es laborioso implementar los nuevos cambios en el microfrontend de seguimiento, ya que es necesario verificar internamente en el código para comprobar cual es la ruta actual de cada endpoint. Por ejemplo:
      - **Esperado:** estado_trimestre/:plan_id/:trimestre/estado - **Actual:** estado_trimestre/:plan_id/:trimestre
      - **Esperado:** /:seguimiento_id/actividades - **Actual:** /actividades/:seguimiento_id

     Como es evidente los cambios en las rutas son mínimos, sin embargo, la cuestión es a qué issue debería ser fiel en cuanto a la implementación de endpoints en el microfrontend de seguimiento.
3. Por último, se implementaron tanto el micromid de formulación como el de seguimiento en la siguientes variables de entorno del microfrontend de seguimiento:
`FORMULACION_MID: [Pruebas API Formulación]`
`SEGUIMIENTO_MID: [Pruebas API Seguimiento]`

**Comment by felimarod** [comment]
> @a52290451 y @felimarod por favor revisar en concreto el punto dos del comentario [#1007 (comment)](https://github.com/udistrital/planeacion_cliente/issues/1007#issuecomment-2080285323), dado que los endpoints no quedaron nombrados correctamente en el api de seguimiento_mid. La idea es abordar esta tarea lo antes posible dado el alistamiento de integración de mf y micro mids.
> 
> Gracias por su colaboración,

Quedo listo el renombramiento de los endpoints en seguimiento_mid, se pueden consultar algunas rutas en https://github.com/udistrital/planeacion_cliente/issues/972#issuecomment-2083846680
