### ISSUE TITLE
Ajuste del flujo de armonización para la facilidad del usuario 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#101]
Se debe ajustar el flujo de la armonización de las actividades, para esto se debe cambiar de posición para que el componente de armonización se ubique entre la tabla resumen y el formulario dinámico, también se debe incluir la alerta informado que se debe armonizar la actividad antes de crear la actividad, la issue debe cumplir con los siguientes requerimiento: 

- [x] Ajustar la visualización de la armonización para un mejor entendimiento 
- [x] Implementar la alerta mencionada con anterioridad.

**Comment by brayaned** [comment]
Se da inicio a la issue.

**Comment by brayaned** [comment]
Se realizaron los ajustes pertinentes para que el usuario tenga facilidad de visualización para la armonización. No se presento ningún problema mayor y se da por finalizado el desarrollo de la issue.

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
