### ISSUE TITLE
Ajustes integración de microfrontends Utilidades y root

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1011]
Se requiere integrar en ambiente de pruebas los microclientes base del sistema SISGPLAN.

**Especificaciones técnicas**

1. El micro cliente orquestador **root** del sistema para pruebas se encuentra en: https://github.com/udistrital/planeacion_root_mf/tree/release/0.0.1
2. El micro cliente de la OATI tipo **core** para pruebas se encuentra en: https://github.com/udistrital/core_mf_cliente/tree/release/0.0.1
3. El micro cliente de SISGPLAN con su visual base para pruebas se encuentra en: https://github.com/udistrital/planeacion_utilidades_mf/tree/release/0.0.1
4. Se realizaron las respectivas peticiones para desplegar los microclientes utilidades y root de SISGPLAN en ambiente de pruebas, dando como URI de estos:

- core_mf_cliente: https://pruebassgamicroclientes.portaloas.udistrital.edu.co
- planeacion_root_mf: pruebaspsisgplanmf.portaloas.udistrital.edu.co
- planeacion_utilidades_mf: pruebaspsisgplanutilidadesmf.portaloas.udistrital.edu.co

**Subtareas**

- [x] Ajustar todos los archivos relacionados a los MF para que el despliegue sea correcto.
- [x] Ajuste de los archivos de rutas a partir de las URIs asignadas
- [x] Revisión de los endpoints y métodos lógicos empleados en el core por parte del equipo de Fabian Barreto.
- [x] Ajustar el consumo de utilidades desde el root (revisar la ruta).
- [x] Estabilización de las ramas develop y release/0.0.1.

**Criterios de aceptación**

- [x] Se ajustan los archivos en los micro clientes para que funcione en ambiente de pruebas en la uri: pruebaspsisgplanmf.portaloas.udistrital.edu.co.
- [x] Las ramas se encuentran estabilizadas.
- [x] El consumo de utilidades se corrige.

**Requerimientos**

- [x] Despliegue de los microclientes por parte del equipo de infraestructura.

**Dependencias**

- core_mf_cliente
- planeacion_root_mf
- planeacion_utilidades_mf

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
- Se realiza el desarrollo para que se consuma diferentes archivos de entorno según sea local, pruebas y producción.

![Image](https://github.com/udistrital/planeacion_cliente/assets/73924638/f205f875-0553-4d73-80f5-f76dd9c197bb)

- Se corrige en utilidades, el tema de la creación del proyecto dentro de otra carpeta con el mismo nombre:

![Image](https://github.com/udistrital/planeacion_cliente/assets/73924638/117fd43b-8102-436e-b19f-f57ddb6ddb83)

**Comment by Mechaz123** [comment]
Teniendo en cuenta que el CORE funcionaba el pasado 26/04/2024 se da por terminada la tarea, ya que este es un problema de CORS y así mismo, ya se encuentra corregida la ruta de planeacion_utilidades_mf.
