### ISSUE TITLE
Refactorización cliente planeacion_seguimiento_mf - PT 2

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1013]
Se requiere refactorizar el MF **PLANEACION_SEGUIMIENTO_MF** con base en el API **PLANEACION_CLIENTE**, de forma tal que se culmine con la migración de componentes y se presente el cliente en su forma final.

**Especificaciones técnicas**

1. El desarrollo de la **parte 1** de esta tarea corresponde a lo documentado en el issue #1007 .
2. El repositorio para **PLANEACION_SEGUIMIENTO_MF** es: https://github.com/udistrital/planeacion_seguimiento_mf
3. Se requiere migrar los **nuevos desarrollos** (en caso de ser requerido) asociados a Reportes, del cliente **PLANEACION_CLIENTE** al MF **PLANEACION_SEGUIMIENTO_MF**. Tener en cuenta todos los ajustes, como por ejemplo: #982 , #983 , #997 , #1004 , #1017 entre otras.

5. El Cliente debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevos Clientes definidos por la OATI.
6. Los componentes y servicios que son globales a todos los MF deben ser migrados al cliente **CORE** o de **UTILIDADES**.
7. Se debe optimizar el código migrado, eliminando malas practicas de desarrollo.
8. El MF debe quedar optimizado en estilos y con pruebas funcionales en su totalidad.
9. El MF debe consumir los endpoints asociados a los MicroMids desarrollados para SISGPLAN, en lugar de planeacion_mid.
10. Generar el archivo drone.yml con base en lo encontrado en planeacion_utilidades_mf: pruebaspsisgplanutilidadesmf.portaloas.udistrital.edu.co
11. De igual manera tener en cuenta los clientes ya desplegados en pruebas:
- core_mf_cliente: https://pruebassgamicroclientes.portaloas.udistrital.edu.co/
- planeacion_root_mf: pruebaspsisgplanmf.portaloas.udistrital.edu.co
12. Actualizar el Readme.md.

**Sub Tareas**

- [x] Refactorización del cliente **PLANEACION_SEGUIMIENTO_MF**
- [x] Migración de nuevas funcionalidades.
- [x] Cambio de consumo de endpoints, en especial los del api de planeacion_seguimiento_mid.
- [x] Optimización de código.
- [x] Ajuste de readme y drone.

**Criterios de aceptación**

- [x] El MF se encuentra refactorizado.
- [x] El MF cuenta con todas sus componentes y funcionalidades migrados.
- [x] El código del MF se encuentra optimizado.

**Requerimientos**

- [x] #943 , #952  .
- [x] #973 .
- [x] #1007 .
- [x] Ajuste de nombramiento de endpoints en planeacion_seguimiento_mid.

**Dependencias**

- planeacion_cliente
- planeacion_mid
- planeacion_seguimiento_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by C0C045** [comment]
# Refactorización cliente planeacion_seguimiento_mf - PT 2
1. Se ajustaron todas rutas qué apuntaban a 'PLANES_MID' para que usarán los micromid's de 'FORMULACION' y 'SEGUIMIENTO', además de ajustar la respuestas de los datos, ya que antes se esperaba un 'Data' y ahora 'data'; tal que así:
**Caso 'FORMULACION_MID':**
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/058ef589-4416-4876-9269-67af774c8220)
**Caso 'SEGUIMIENTO_MID':**
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/541a4216-2020-441c-9db2-0a80130ede5a)
**Prueba Funcional:**
![Pruebas Mids](https://github.com/udistrital/planeacion_cliente/assets/55455142/8feb4081-dbc9-4103-8093-66b29fb7fdb9)
**Nota:** Como podemos ver en la última parte de la prueba funcional cuando queremos ver el detalle de una actividad en especifico, la consulta retorna un 500 indicando que la consulta: 'SEGUIMIENTO_MID/seguimiento/65bf03d30c1fc945b06aee5b/1/635b1fff5073f2675157dc83' esta fallando, por ende, es necesario indagar en el posible error y solucionarlo.
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/97fc48cd-10e6-415f-b63e-f30af739fa5a)

2. Por otro lado tanto el drone.yml y el README.md quedaron actualizados según lo solicitado.
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/e14b41d9-f3d0-41cb-bfcd-faf90c32ef68)

3. Por último, se ajustó el package.json según lo planteado en https://github.com/udistrital/planeacion_utilidades_mf/commit/b2cb27067eaf37ed81aa798cbb323ee14f610c15
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/6d9a860d-ef01-42dc-8baa-b8a0cb06b004)

**Comment by C0C045** [comment]
# PR
seguimiento_mf: https://github.com/udistrital/planeacion_seguimiento_mf/pull/6

**Comment by C0C045** [comment]
# PR VARIABLES DE ENTORNO
seguimiento_mf: https://github.com/udistrital/planeacion_seguimiento_mf/pull/7
