### ISSUE TITLE
Propuesta de diferenciación de estilos y componentes lógicos en el cliente core_mf_cliente

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1014]
Se requiere realizar una propuesta técnica y abstracta sobre como organizar los estilos y componentes lógicos en el micro cliente del core.

**Especificaciones técnicas**

1. El micro cliente de la OATI tipo core para pruebas se encuentra en: https://github.com/udistrital/core_mf_cliente/tree/release/0.0.1.
2. En el desarrollo del issue #1007 se identificó que el método de armado de peticiones HTTP empleado en el core funciona diferente al comunmente utilizado en SISGPLAN.
3. Actualmente el mf core se encuentra orientado a los estilos y funcionalidades del sistema SGA.
4. Idealmente es parametrizar los estilos y funciones lógicas empleadas en el core con base en el sistema que haga uso de este.
5. Como material de apoyo revisar la [reunión sobre el tema](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/blsierraf_udistrital_edu_co/EbJxOuFFsztIkAhgbYsM6OwBR0FV2XJUYUemixqqf0c8wg?referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view).
6. El Cliente debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevos Clientes definidos por la OATI.

**Subtareas**

- [x] Revisión de como se encuentra implementado el consumo de estilos, assets y componentes lógicos por parte del core actualmente.
- [x] Realizar una propuesta de diferenciación de assets, estilos y componentes lógicos dependiente al sistema que este consumiendo el core.
- [x] Implementar la propuesta posterior a la aprobación del líder téncino/SM.
- [x] Probar funcionalmente la propuesta a partir de su consumo desde SISGPLAN.

**Criterios de aceptación**

- [x] Se documenta el issue con la propuesta de parametrización
- [x] El MF se encuentra refactorizado para ser parametrizable.
- [x] Se comprueba la funcionalidad de parametrización de estilos en el core_mf, a partir de su consumo desde por lo menos un mf de SISGPLAN.

**Requerimientos**

- [x] Inducción al manejo de estilos en el core.

**Dependencias**

- Todos los MF de SISGPLAN.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by C0C045** [comment]
# Avance Propuesta de diferenciación de estilos

Dado la que la implementación de estilos se importa desde el CORE en el archivo 'styles.scss' fue complicado llegar a proponer alguna solución que se implemente en el mismo CORE, ya que de ser así la opción más viable era crear un 'styles.scss' para cada sistema. Por ende, se propuso implementar estos estilos desde el ROOT, ya que este es independiente por cada sistema.

Para lograrlo se importa los colores desde el ROOT en el archivo `src/index.ejs`, ya que de esta manera cada sistema puede implementar el suyo.
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/0ed492a7-5c21-49f3-8891-c89f793246b6)

**RESULTADO:**
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/b50979b1-ad83-4da5-a329-538b4460d72a)
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/4cebfd24-393b-4525-8175-9a2412db1c0d)

**Comment by C0C045** [comment]
# Propuesta de implementación de colores 'mat-material' en 'styles-gaia'
Para diferenciar lo colores de 'mat-material' por cada sistema se propone agregar los nuevos colores en el asset de 'styles-gaia' y de esta forma se garantiza que cada sistema use sus propios colores de 'mat-material'. Por ejemplo:
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/78d67e8a-4111-41fc-9565-cf00ebc4db6e)

Una vez implementados los nuevos colores en 'styles-gaia' los importamos en el `src/index.ejs` del root y los usamos en el `theme.scss` del CORE. Tal que así:
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/90df03d5-241b-4b74-bf63-acec6d38a68f)

**Comment by C0C045** [comment]
# Rama de la propuesta
ROOT: https://github.com/udistrital/planeacion_root_mf/tree/feature/estilos_planeacion
