### ISSUE TITLE
Cambio de cargo_id en vinculación al asignar un permiso

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1015]
Se requiere continuar con el desarrollo relacionado al módulo de **gestión de usuarios** para realizar toda la operación correcta de la asignación de roles que se realiza desde la OATI una vez se solicita esto desde la Oficina de Planeación.

**Especificaciones técnicas**
- Actualmente la asignación de roles se encuentra funcional en el módulo de pruebas.
- Los roles gestionados por WSO2, son aquellos relacionados con los menús a los que debe tener acceso el usuario loggeado traídos desde el api de configuración.
- El sistema actualmente filtra en los modúlos relacionados a planes de acción (formulación y seguimiento), por los cargos que tenga relacionados un usuario de la tabla de vinculacion del esquemta de terceros. Lo anterior se valida para el proceso de formulación en el mid (planeacion_mid): https://github.com/udistrital/planeacion_mid/blob/727c99257a2cc7c3e0976433d1ba0c6d40b6ffbd/controllers/formulacion.go#L1648
- Solo se deben modificar las vinculaciones activas relacionadas con la dependencia de la cual la oficina de planeación le va a dar permiso.

**Sub Tareas**

- [x] Ocultar del módulo de **"Gestión de usuarios"** la búsqueda por rol (queda pendiente de implementar funcionalidad en autenticacion_mid).
- [x] Revisar los valores en el **api de parametros** que corresponden los ids 319, 312 y 320. Además, verificar cual es el cargo_id (id en parámetros) que corresponde a **no registra o nombre similar**, que tiene la mayoría de usuarios en la tabla de vinculaciones de terceros.
- [x] Crear un desplegable (Select) que muestre las vinculaciones activas para el usuario sobre el cual se realiza la búsqueda en el menú de "Gestión de usuarios", esto para que la oficina de planeación pueda seleccionar sobre cual vinvulación se le va a cambiar el cargo_id.
- [x] Aplicar la actualización del campo cargo_id de la tabla vinculaciones del esquema de terceros para que tenga el id correspondiente a **"Asistente dependencia"** una ves se ejecute la acción de vincular a un usuario dicho rol.
- [x] Por otra parte, cuando se desvincule de un usuario el rol "Asistente dependencia", se debe ejecutar la acción de actualización de vinculación para que quede aquel id correspondiente a **no registra o nombre similar**.

**Criterios de aceptación**

- [x] Se documenta el issue.
- [x] Se oculta el componente de búsqueda de usuarios por rol.
- [x] Se actualizan las vinculaciones del usuario sobre el cual se añade o quita el rol "ASISTENTE_DEPENDENCIA".

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by ccmendezt** [comment]
## Evidencias - Cambio de cargo_id en vinculación al asignar un permiso
### 20/05/2024 - 15:30

Los valores en el api de parametros que corresponden los ids 312, 319 y 320 corresponden a:
**- Base de datos de desarrollo:**
```json
{
      "Id": 312,
      "Nombre": "JEFE OFICINA",
      "Descripcion": "JEFE OFICINA",
      "CodigoAbreviacion": "JO",
      "Activo": true,
      "NumeroOrden": 1,
      "FechaCreacion": "2021-01-28 15:23:00 +0000 +0000",
      "FechaModificacion": "2023-07-27 12:00:36.147643 +0000 +0000",
      "TipoParametroId": {
        "Id": 15,
        "Nombre": "Cargos",
        "Descripcion": "Cargos",
        "CodigoAbreviacion": "C",
        "Activo": true,
        "NumeroOrden": 15,
        "FechaCreacion": "2021-01-28 15:23:00 +0000 +0000",
        "FechaModificacion": "2021-01-28 15:23:00 +0000 +0000",
        "AreaTipoId": {
          "Id": 5,
          "Nombre": "Contratación",
          "Descripcion": "Contratación",
          "CodigoAbreviacion": "C",
          "Activo": true,
          "NumeroOrden": 0,
          "FechaCreacion": "2021-01-08 19:42:00 +0000 +0000",
          "FechaModificacion": "2021-01-08 19:42:00 +0000 +0000"
        }
      },
      "ParametroPadreId": null
    }
```

```json
{
      "Id": 319,
      "Nombre": "VICERECTOR ACADÉMICO",
      "Descripcion": "VICERECTOR ACADÉMICO",
      "CodigoAbreviacion": "VA",
      "Activo": true,
      "NumeroOrden": 1,
      "FechaCreacion": "2021-02-16 17:27:14.082122 +0000 +0000",
      "FechaModificacion": "2021-02-16 17:27:14.082232 +0000 +0000",
      "TipoParametroId": {
        "Id": 15,
        "Nombre": "Cargos",
        "Descripcion": "Cargos",
        "CodigoAbreviacion": "C",
        "Activo": true,
        "NumeroOrden": 15,
        "FechaCreacion": "2021-01-28 15:23:00 +0000 +0000",
        "FechaModificacion": "2021-01-28 15:23:00 +0000 +0000",
        "AreaTipoId": {
          "Id": 5,
          "Nombre": "Contratación",
          "Descripcion": "Contratación",
          "CodigoAbreviacion": "C",
          "Activo": true,
          "NumeroOrden": 0,
          "FechaCreacion": "2021-01-08 19:42:00 +0000 +0000",
          "FechaModificacion": "2021-01-08 19:42:00 +0000 +0000"
        }
      },
      "ParametroPadreId": null
    }
```

```json
{
      "Id": 320,
      "Nombre": "Asistente Dependencia",
      "Descripcion": "Cargo de Asistente de dependencia",
      "CodigoAbreviacion": "AS_D",
      "Activo": true,
      "NumeroOrden": 320,
      "FechaCreacion": "2022-08-02 14:37:20.659752 +0000 +0000",
      "FechaModificacion": "2024-04-10 14:50:24.397723 +0000 +0000",
      "TipoParametroId": {
        "Id": 15,
        "Nombre": "Cargos",
        "Descripcion": "Cargos",
        "CodigoAbreviacion": "C",
        "Activo": true,
        "NumeroOrden": 15,
        "FechaCreacion": "2021-01-28 15:23:00 +0000 +0000",
        "FechaModificacion": "2021-01-28 15:23:00 +0000 +0000",
        "AreaTipoId": {
          "Id": 5,
          "Nombre": "Contratación",
          "Descripcion": "Contratación",
          "CodigoAbreviacion": "C",
          "Activo": true,
          "NumeroOrden": 0,
          "FechaCreacion": "2021-01-08 19:42:00 +0000 +0000",
          "FechaModificacion": "2021-01-08 19:42:00 +0000 +0000"
        }
      },
      "ParametroPadreId": null
    }
```

#### Id Parámetro NO REGISTRA - BD Desarrollo

```json
{
      "Id": 5957,
      "Nombre": "NO REGISTRA",
      "Descripcion": "NO REGISTRA",
      "CodigoAbreviacion": "NR",
      "Activo": true,
      "NumeroOrden": 2,
      "FechaCreacion": "2024-04-10 14:56:44.023043 +0000 +0000",
      "FechaModificacion": "2024-04-10 14:56:44.023125 +0000 +0000",
      "TipoParametroId": {
        "Id": 15,
        "Nombre": "Cargos",
        "Descripcion": "Cargos",
        "CodigoAbreviacion": "C",
        "Activo": true,
        "NumeroOrden": 15,
        "FechaCreacion": "2021-01-28 15:23:00 +0000 +0000",
        "FechaModificacion": "2021-01-28 15:23:00 +0000 +0000",
        "AreaTipoId": {
          "Id": 5,
          "Nombre": "Contratación",
          "Descripcion": "Contratación",
          "CodigoAbreviacion": "C",
          "Activo": true,
          "NumeroOrden": 0,
          "FechaCreacion": "2021-01-08 19:42:00 +0000 +0000",
          "FechaModificacion": "2021-01-08 19:42:00 +0000 +0000"
        }
      },
      "ParametroPadreId": null
    }
```

**- Base de datos de producción:**
```json
{
      "Id": 312,
      "Nombre": "JEFE OFICINA",
      "Descripcion": "JEFE OFICINA",
      "CodigoAbreviacion": "JO",
      "Activo": true,
      "NumeroOrden": 1,
      "FechaCreacion": "2021-01-28 15:23:00 +0000 +0000",
      "FechaModificacion": "2023-07-27 12:00:25.477152 +0000 +0000",
      "TipoParametroId": {
        "Id": 15,
        "Nombre": "Cargos",
        "Descripcion": "Cargos",
        "CodigoAbreviacion": "C",
        "Activo": true,
        "NumeroOrden": 14,
        "FechaCreacion": "2021-01-28 15:23:00 +0000 +0000",
        "FechaModificacion": "2021-01-28 15:23:00 +0000 +0000",
        "AreaTipoId": {
          "Id": 5,
          "Nombre": "Contratación",
          "Descripcion": "Contratación",
          "CodigoAbreviacion": "C",
          "Activo": true,
          "NumeroOrden": 0,
          "FechaCreacion": "2021-01-08 19:42:00 +0000 +0000",
          "FechaModificacion": "2021-01-08 19:42:00 +0000 +0000"
        }
      },
      "ParametroPadreId": null
    }
```

```json
{
      "Id": 320,
      "Nombre": "Asistente Dependencia",
      "Descripcion": "Cargo de Asistente de dependencia",
      "CodigoAbreviacion": "",
      "Activo": false,
      "NumeroOrden": 320,
      "FechaCreacion": "2022-08-02 14:37:59.626655 +0000 +0000",
      "FechaModificacion": "2023-03-22 00:37:30.903583 +0000 +0000",
      "TipoParametroId": {
        "Id": 15,
        "Nombre": "Cargos",
        "Descripcion": "Cargos",
        "CodigoAbreviacion": "C",
        "Activo": true,
        "NumeroOrden": 14,
        "FechaCreacion": "2021-01-28 15:23:00 +0000 +0000",
        "FechaModificacion": "2021-01-28 15:23:00 +0000 +0000",
        "AreaTipoId": {
          "Id": 5,
          "Nombre": "Contratación",
          "Descripcion": "Contratación",
          "CodigoAbreviacion": "C",
          "Activo": true,
          "NumeroOrden": 0,
          "FechaCreacion": "2021-01-08 19:42:00 +0000 +0000",
          "FechaModificacion": "2021-01-08 19:42:00 +0000 +0000"
        }
      },
      "ParametroPadreId": null
    }
```

#### Id Parámetro NO REGISTRA - BD Producción

```json
{
      "Id": 313,
      "Nombre": "NO REGISTRA",
      "Descripcion": "NO REGISTRA",
      "CodigoAbreviacion": "NR",
      "Activo": true,
      "NumeroOrden": 2,
      "FechaCreacion": "2021-02-10 09:17:00 +0000 +0000",
      "FechaModificacion": "2021-02-10 09:17:00 +0000 +0000",
      "TipoParametroId": {
        "Id": 15,
        "Nombre": "Cargos",
        "Descripcion": "Cargos",
        "CodigoAbreviacion": "C",
        "Activo": true,
        "NumeroOrden": 14,
        "FechaCreacion": "2021-01-28 15:23:00 +0000 +0000",
        "FechaModificacion": "2021-01-28 15:23:00 +0000 +0000",
        "AreaTipoId": {
          "Id": 5,
          "Nombre": "Contratación",
          "Descripcion": "Contratación",
          "CodigoAbreviacion": "C",
          "Activo": true,
          "NumeroOrden": 0,
          "FechaCreacion": "2021-01-08 19:42:00 +0000 +0000",
          "FechaModificacion": "2021-01-08 19:42:00 +0000 +0000"
        }
      },
      "ParametroPadreId": null
    }
```

Para realizar pruebas resultó necesario agregar vinculaciones al usuario _ccmendezt@udistrital.edu.co_ para la vigencia 2024:

```json
[
  {
    "Id": 65,
    "TerceroPrincipalId": {
      "Id": 59869,
      "NombreCompleto": "Cristian Camilo Mendez Trujillo",
      "PrimerNombre": "Cristian",
      "SegundoNombre": "Camilo",
      "PrimerApellido": "Mendez",
      "SegundoApellido": "Trujillo",
      "LugarOrigen": 0,
      "FechaNacimiento": "2002-03-19T00:00:00Z",
      "Activo": true,
      "TipoContribuyenteId": {
        "Id": 1,
        "Nombre": "PERSONA NATURAL",
        "Descripcion": "",
        "CodigoAbreviacion": "P_NATURAL",
        "Activo": true,
        "FechaCreacion": "2019-11-25 20:39:54.419232 +0000 +0000",
        "FechaModificacion": "2019-11-25 20:39:54.419232 +0000 +0000"
      },
      "FechaCreacion": "2024-05-17 10:49:52.997219 +0000 +0000",
      "FechaModificacion": "2024-05-17 10:49:52.999549 +0000 +0000",
      "UsuarioWSO2": "ccmendezt@udistrital.edu.co"
    },
    "TerceroRelacionadoId": null,
    "TipoVinculacionId": 307,
    "CargoId": 320,
    "DependenciaId": 14,
    "Soporte": 0,
    "PeriodoId": 39,
    "FechaInicioVinculacion": "2024-01-17T00:00:00Z",
    "FechaFinVinculacion": "2024-12-30T00:00:00Z",
    "Activo": true,
    "FechaCreacion": "2024-05-17 11:06:16 +0000 +0000",
    "FechaModificacion": "2024-05-20 13:04:59 +0000 +0000",
    "Alternancia": false
  },
  {
    "Id": 64,
    "TerceroPrincipalId": {
      "Id": 59869,
      "NombreCompleto": "Cristian Camilo Mendez Trujillo",
      "PrimerNombre": "Cristian",
      "SegundoNombre": "Camilo",
      "PrimerApellido": "Mendez",
      "SegundoApellido": "Trujillo",
      "LugarOrigen": 0,
      "FechaNacimiento": "2002-03-19T00:00:00Z",
      "Activo": true,
      "TipoContribuyenteId": {
        "Id": 1,
        "Nombre": "PERSONA NATURAL",
        "Descripcion": "",
        "CodigoAbreviacion": "P_NATURAL",
        "Activo": true,
        "FechaCreacion": "2019-11-25 20:39:54.419232 +0000 +0000",
        "FechaModificacion": "2019-11-25 20:39:54.419232 +0000 +0000"
      },
      "FechaCreacion": "2024-05-17 10:49:52.997219 +0000 +0000",
      "FechaModificacion": "2024-05-17 10:49:52.999549 +0000 +0000",
      "UsuarioWSO2": "ccmendezt@udistrital.edu.co"
    },
    "TerceroRelacionadoId": null,
    "TipoVinculacionId": 307,
    "CargoId": 5957,
    "DependenciaId": 8,
    "Soporte": 0,
    "PeriodoId": 39,
    "FechaInicioVinculacion": "2024-01-17T00:00:00Z",
    "FechaFinVinculacion": "2024-12-30T00:00:00Z",
    "Activo": true,
    "FechaCreacion": "2024-05-17 00:00:00 +0000 +0000",
    "FechaModificacion": "2024-05-20 14:33:38 +0000 +0000",
    "Alternancia": false
  }
]
```

- Se ocultó la opción de _búsqueda por rol_.
- El select mostrado para las vinculaciones del usuario es el siguiente:
![vinculaciones-usuario](https://github.com/udistrital/planeacion_cliente/assets/82072560/864664dc-8fcb-4896-93d8-eb86941f3206)
Como se aprecia en el video, para cada vinculación se muestra la vinculación en formato: **Vigencia - Dependencia**, de los datos obtenidos de la vigencia en el método creado en _planeacion_mid_ llamado **VinculacionTerceroByEmail()**.

- **Vinculación de rol:** Cuando se elige una vinculación y se vincula el rol al usuario, se cambia el CargoId de vinculación de _No registra_ --> _Asistente de dependencia_:
![vincular-rol](https://github.com/udistrital/planeacion_cliente/assets/82072560/3cc6627c-1367-45b4-a936-dba4c1ffce9b)

- **Desvinculación de rol:** Cuando se elige una vinculación y se vincula el rol al usuario, se cambia el CargoId de vinculación de _Asistente de dependencia_ --> _No registra_:
![desvincular-rol](https://github.com/udistrital/planeacion_cliente/assets/82072560/8b34f8c2-68af-4a02-a7b8-3273fa0298da)

## Pull Request asociados a Issue
- planeacion_mid: https://github.com/udistrital/planeacion_mid/pull/528
- planeacion_cliente: https://github.com/udistrital/planeacion_cliente/pull/1071

## Notas importantes:
  **i.** El mensaje mostrado al momento de querer vincular/desvincular un rol a un usuario: "_¿Está seguro de vincular el rol al usuario?, si el usuario tiene otra vinculación se verá afectada con el cambio de rol_" se muestra ya que cuando se desea agregar o eliminar un rol de un usuario, esto se hace en una tabla de rompimiento que contiene el usuario y rol, pero el cambio de CargoId se hace en el crud de terceros, así que si alguien tiene más de una vinculación, por ejemplo, alguien es ASISTENTE_DEPENDENCIA de Facultad de Ingenieria pero también de Vicerrectoría Académica, y se quiere quitar el rol de _Asistente de Dependencia_ únicamente de la Vicerrectoría Académica, el cambio de CargoId de esa vinculación se puede realizar sin ningún problema, pero también se quitaría el rol del usuario de WSO2, aunque tenga la vinculación de la Facultad de Ingeniería activa.
