### ISSUE TITLE
Ajuste de Hotfix en planeacion ambiente de pruebas (monolito)

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1016]
Se requiere revisar el bug abordado en el hotfix del issue #983: _"Se presenta un error cuando un plan de acción en fase de Formulación pasa a estado Avalado. En este punto el sistema debe generar la plantilla del plan de acción para realizar su seguimiento y este mismo debe quedar en el estado inicial de seguimiento. Sin embargo, esto no ocurre actualmente."_, en el cliente y mid de planeación.

**Especificaciones técnicas**

- El error se trató en el issue #983 .
- Se requiere controlar el error asociado a la realización de peticiones diferenciadas a la hora de avalar un plan.
- Se requiere controlar avalar un plan si no se encuentran los periodos para la vigencia del plan a avalar en parámetros.

**Sub Tareas**

- [x] Identificar si se requiere realizar la gestión de los errores mencionados en la sección de **Especificaciones técnicas**.
- [x] Realizar el ajuste requerido en el api mid y el cliente de SISGPLAN.
- [x] Probar el funcionamiento y realizar la actualización del código en develop posteriormente en release/0.0.1.

**Criterios de aceptación**

- [x] Corrección de comportamiento esperado en la fase de avalar un plan.
- [x] Documentación del issue con las respectivas pruebas de funcionamiento.

**Dependencias**

- No presenta.

**Requerimientos**

- planeacion_mid
- planeacion_cliente
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by ccmendezt** [comment]
## Evidencias - Ajuste de Hotfix en planeación ambiente de pruebas (monolito)
### 30/04/2024 - 9:10

### Se evidencia el funcionamiento de avalar el plan desde el rol planeación, evitando la doble petición:

![avalar-plan-ajuste-hotfix](https://github.com/udistrital/planeacion_cliente/assets/82072560/01fac430-b1d1-4b03-8116-6b161725cac7)

_Código asociado a prueba funcional:_

- **Cliente:**
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/e55e00e4-1bd9-48a9-9221-2117e534b0be)

- **API MID:**
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/35bd8955-375a-4f6d-969f-fa61a9280dc5)

### Se evidencia el funcionamiento del flujo cuando no hay trimestres establecidos para avalar un plan

![avalar-plan-error-ajuste-hotfix](https://github.com/udistrital/planeacion_cliente/assets/82072560/d9e2832a-f893-444e-823c-0cde474ea87d)

### Se evidencia los mensajes de diálogo cuando no hay trimestres para la vigencia seleccionada en el módulo de construcción:
![sin-trimestres-ajuste-hotfix](https://github.com/udistrital/planeacion_cliente/assets/82072560/856d8cd3-54d4-4ea6-b14b-248a487e4140)

_Código asociado a prueba funcional:_ Desde el servicio habilitar-reporte.service se apunta al nuevo endpoint creado en la API MID.

- **Cliente:**
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/d3f079d4-fbbd-4396-99bc-809b316a5f99)

**Comment by ccmendezt** [comment]
## Pull Request Asociados a Issue
### 30/04/2024 - 9:40

- **planeacion_cliente:** https://github.com/udistrital/planeacion_cliente/pull/1021
- **planeacion_mid:** https://github.com/udistrital/planeacion_mid/pull/513
