### ISSUE TITLE
Estandarización de Roles en SISGPLAN PT2

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1017]
Se requiere continuar con el ajuste de los roles del sistema y su respectiva configuración de accesos a los diferentes módulos y estados.

**Especificaciones técnicas**
- Con base en las falencias identificadas en #997 realizar los ajustes para que el sistema cumpla con el control de accesos por rol deseado.
- El desarrollo del sistema actual se encuentra en entorno de pruebas (release/0.0.1) para el cliente, api mid y api crud.
- El [Diagrama de estados/acciones y flujo](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EeNjPFNBwsRBjDqSepON5WABPt4F9mmyAGakA_vQnhXwRg?e=IDSZ9R)
- Actualmente los roles del sistema son: PLANEACION, ASISTENTE_DEPENDENCIA, JEFE_DEPENDENCIA, JEFE_UNIDAD_PLANEACION.
- Se debe crear el rol ASISTENTE_PLANEACION.

**Sub Tareas**

- [x] En el aplicativo de configuración en entorno de pruebas se debe añadir y relacionar el rolde ASISTENTE_PLANEACION.
- [x] Asignar a un usuario el rol de ASITENTE_PLANEACION, para poder relaizar las respectivas pruebas.
- [x] En el sistema de SISGPLAN adicionar el rol de ASISTENTE_PLANEACION en las fases que debería ir.
- [x] Revisar nuevamente que el flujo se realice de la manera correcta con los permisos asignados a cada estado.
- [x] Documentar el issue con las posibles insidencias o bugs
- [x] Se debe desarrollar la solución.
- [x] Se deben realizar pruebas funcionales evidenciando la corrección. Además, se deben realizar pruebas funcionales del correcto flujo con los ajustes solicitados.

**Criterios de aceptación**

- [x] Se documenta el issue.
- [x] Se corrige el incidente.
- [x] Se ajustan los roles.
- [x] Se realizan las respectivas pruebas de funcionamiento.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by ccmendezt** [comment]
## Evidencias - Estandarización de Roles en SISGPLAN.
### 07/05/2024 - 18:30

### Proceso de Seguimiento:

- **Estado A (Habilitado)**: Ambos roles, tanto _ASISTENTE_DEPENDENCIA_ como _JEFE_DEPENDENCIA_ pueden acceder a este estado del proceso:

     - **ASISTENTE_DEPENDENCIA**: 
     
     ![estado-a-habilitado-asistente-dependencia](https://github.com/udistrital/planeacion_cliente/assets/82072560/b7ca1502-8c7d-480c-87a8-830e8f48d88b)

     - **JEFE_DEPENDENCIA**: 
     
     ![estado-a-habilitado-jefe-dependencia](https://github.com/udistrital/planeacion_cliente/assets/82072560/51795498-ccc2-4c99-84f8-892bc5041e4f)
     
- **Estado B (En reporte)**: Ambos roles, tanto _ASISTENTE_DEPENDENCIA_ como _JEFE_DEPENDENCIA_ pueden acceder a este estado del proceso, aunque normalmente lo realiza el ASISTENTE_DEPENDENCIA y las acciones permitidas para este estado son: _Consulta del plan, Seguimiento de planes, Evaluación cuantitativa y cualitativa, Editar evaluación cuantitativa y cualitativa_

     - **ASISTENTE_DEPENDENCIA**:
     
     ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/36a043bb-c24c-45d5-9ca4-5403fe504346)

     - **Componente cualitativo**:
        
     ![componente-cualitativo](https://github.com/udistrital/planeacion_cliente/assets/82072560/0edb89b3-f8dc-4fc9-82b6-da3be255801f)

     - **Componente cuantitativo**:
        
     ![componente-cuantitativo](https://github.com/udistrital/planeacion_cliente/assets/82072560/8fdfc80f-f873-451c-b90f-da42652b2b6f)

     En este estado, se permite tanto al ASISTENTE_DEPENDENCIA como al JEFE_DEPENDENCIA realizar el envío del reporte:

     - **ASISTENTE_DEPENDENCIA**: 
     
     ![generar-reporte-asistente](https://github.com/udistrital/planeacion_cliente/assets/82072560/56e9946a-4542-445a-8da0-5f10372063c0)

     - **JEFE_DEPENDENCIA**: 
     
     ![generar-reporte-jefe](https://github.com/udistrital/planeacion_cliente/assets/82072560/ff7dd2c8-1776-414c-b9db-b32eb167a32d)

- **Estado C (Enviado a revisión)**: En este estado se habilita un botón _Enviar Reporte_ en la visualización del trimestre tanto para JEFE_DEPENDENCIA como para ASISTENTE_DEPENDENCIA (normalmente lo hace este rol según el flujo) cuando el estado del seguimiento es _En reporte_, anteriormente se mostraba cuando estaba el estado _Habilitado_. Ya se corrigió:

     - **ASISTENTE_DEPENDENCIA**: 
     
     ![enviar-reporte-asistente](https://github.com/udistrital/planeacion_cliente/assets/82072560/efd77a48-60a8-4e48-976e-d87ab9b9ead6)

     - **JEFE_DEPENDENCIA**:

     ![enviar-reporte-jefe](https://github.com/udistrital/planeacion_cliente/assets/82072560/435b695e-48f4-4388-939a-000d74d24662)

En este punto, según el flujo, cuando el ASISTENTE_DEPENDENCIA envía el reporte de seguimiento a revisión, es el JEFE_DEPENDENCIA quien revisa ese reporte de seguimiento, en el estado D, y en caso de haber observaciones, las hace y devuelve el estado del reporte a B pero dicho flujo no está implementado.

![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/60d92459-87e3-428a-b285-690a0b1affbb)


Lo que está implementado ahora mismo es que cuando se envía el reporte, se habilitan las opciones de iniciar revisión desde el rol PLANEACION, es decir, el estado E:

- **Estado E (En revisión OAP)**: Ambos roles, tanto _ASISTENTE_PLANEACION_(actualmente NO implementado) como _PLANEACION_ pueden acceder a este estado del proceso, para verificar el seguimiento y en dado caso realizar observación o avalar el reporte.

![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/6aad344b-42e5-4828-aeec-c7d52f7d9ee4)

Luego, al darle al botón iniciar revisión:

![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/d8fc189a-4f9c-410f-8e82-13c4d846e854)

**Iniciar revisión - PLANEACION:**

![observaciones-planeacion](https://github.com/udistrital/planeacion_cliente/assets/82072560/9085af16-5fed-40bf-9311-72ec16c228e9)

**Finalización de revisión - PLANEACION:**

![finalizar-observaciones-planeacion](https://github.com/udistrital/planeacion_cliente/assets/82072560/48d03c03-badb-4f53-be72-c95a2ecfbfad)

- **Estado F (Con observaciones)**: Ambos roles, tanto _ASISTENTE_DEPENDENCIA_ como _JEFE_DEPENDENCIA_ pueden acceder a este estado del proceso, para para realizar las observaciones dadas por planeación:

     - **ASISTENTE_DEPENDENCIA**: 
     
     ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/01fdf897-c504-407c-816f-a3ed5497f9ff)

     - **JEFE_DEPENDENCIA**:
     
     ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/45ae38eb-6b32-492f-8362-a7d7cd69af2d)
     
En este estado ocurre que aparece desde el rol JEFE_DEPENDENCIA el botón **Enviar Corrección** pero debería tenerlo también el rol ASISTENTE_DEPENDENCIA, así que se corrigió:

![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/e2edca8b-1c0d-4386-8761-22b03a72cd53)

Este botón aparece incluso aún cuando no se han realizado las modificaciones de las observaciones, pero dicho botón tiene una validación que impide enviar el reporte sin que se haya realizado alguna modificación al reporte en cuestión:

![validacion-observaciones](https://github.com/udistrital/planeacion_cliente/assets/82072560/735f5ce2-411e-4e56-bfdd-b200c9b918cd)

Es por eso que se debe entrar al reporte de la actividad y luego realizar la modificación, dicho flujo funciona como se espera:

![realizar-modificacion-observaciones](https://github.com/udistrital/planeacion_cliente/assets/82072560/c0d3f2ea-8a65-4e5e-b210-2fa31a0aa5ea)

Luego, se vuelve al **Estado E** para que **PLANEACION** revise nuevamente la actividad, en este flujo es cuando dicho rol quita las observaciones y avala la actividad:

- **PLANEACION**:

![revisar-actividad](https://github.com/udistrital/planeacion_cliente/assets/82072560/33ae3b7d-73c7-4c6e-8677-7b41a8f93824)
     
En la parte inferior de la revisión de la actividad, hay un botón llamado **Retornar a revisión**, dicho botón permite a PLANEACION cambiar el estado de la actividad de _Actividad Avalada_ a _Actividad Reportada_ permitiendo colocar nuevamente observaciones a dicha actividad:

![retornar-a-revision](https://github.com/udistrital/planeacion_cliente/assets/82072560/5f7ff02e-0aa7-4dfb-94e3-c17afac60f11)

- **Estado G (Reporte Avalado)**: Únicamente el rol PLANEACION puede acceder a este estado en el que finaliza la revisión y finalmente avala el reporte, este apartado funciona como se espera:

![finalizar-revision-avalar-reporte](https://github.com/udistrital/planeacion_cliente/assets/82072560/588f7d01-352c-4f4c-8d7e-42d6c466f23c)


### Commits asociados a Issue:

- **planeacion_cliente:** https://github.com/udistrital/planeacion_cliente/commit/66479c2e0a7e88bc40b704827ec7ffe8f9677046

### Notas Importantes
  **i.** Falta implementar el flujo dado de C a D, dicho flujo se implementará en el Sprint actual.

**Comment by ccmendezt** [comment]
## Evidencias - Estandarización de Roles en SISGPLAN.
### 08/05/2024 - 17:15

- Se creó el rol **ASISTENTE_PLANEACION** en el _aplicativo de configuración_ en entorno de pruebas.
- Se asignó el rol **ASISTENTE_PLANEACION** al usuario _pruebasoas1_
- Se insertó el rol **ASISTENTE_PLANEACION** en el flujo de _formulación_ de planes de acción.
- Se insertó el rol **ASISTENTE_PLANEACION** en el flujo de _seguimiento_ de planes de acción.

## Commits Asociados a Issue

- **planeacion_cliente:** https://github.com/udistrital/planeacion_cliente/commit/340429a6615b55f846f19e84cb88a88a129eea1f

## Notas importantes:
  **i.** Aún se está validando que el rol **ASISTENTE_PLANEACION** cumpla el flujo establecido en el diagrama, para ello se están realizando pruebas.

**Comment by ccmendezt** [comment]
## Evidencias - Estandarización de Roles en SISGPLAN.
### 09/05/2024 - 16:20

- Se modificó el archivo de **Estados/acciones y flujo** dados los requerimientos del SM para corregir y complementar la documentación con la información y terminología correcta y existente usada en los procesos de formulación y seguimiento para el sistema SISGPLAN: [Estados acciones y flujo.xlsx](https://github.com/udistrital/planeacion_cliente/files/15267767/Estados.acciones.y.flujo.xlsx)

- Se inicia la implementación del flujo D del proceso de Seguimiento que concretamente permitirá al rol JEFE_DEPENDENCIA realizar:
    1. Consulta del seguimiento,
    2. Realizar observaciones
    3. Devolver seguimiento
    4. Finalizar revisión

**Comment by ccmendezt** [comment]
## Evidencias - Estandarización de Roles en SISGPLAN.
### 15/05/2024 - 13:36

- Se modificó el archivo de **Estados/acciones y flujo** dados los requerimientos del SM para corregir y complementar la documentación con la información y terminología correcta y existente usada en los procesos de formulación y seguimiento para el sistema SISGPLAN: [Estados acciones y flujo.xlsx](https://github.com/udistrital/planeacion_cliente/files/15325627/Estados.acciones.y.flujo.xlsx)


### Flujo Seguimiento:
- **Estado B y C (En reporte y Enviado a Revisión):** En estos estados normalmente el ASISTENTE_DEPENDENCIA reporta los seguimientos a las actividades realizadas para cada trimestre y envía a revisión dicho reporte para que el JEFE_DEPENDENCIA lo revise: 

![estado-b-en-reporte-asistente-unidad](https://github.com/udistrital/planeacion_cliente/assets/82072560/b7936554-3602-424b-8848-8d9fca2759b6)

- **Estado D y E (En revisión JU y Revisión Verificada con Observaciones):** En este estado el JEFE_DEPENDENCIA inicia la revisión del seguimiento y en caso de que hayan observaciones, las realizará y finalizará la revisión del reporte de seguimiento:

![estado-d-en-revision-ju](https://github.com/udistrital/planeacion_cliente/assets/82072560/90a6f5ef-79e5-47fb-acdf-80b94b1715ef)

En este caso, se devuelve el flujo para que el ASISTENTE_DEPENDENCIA revise las observaciones y reporte nuevamente el seguimiento para el periodo:

![estado-e-observaciones-ju](https://github.com/udistrital/planeacion_cliente/assets/82072560/9682e810-8bd2-45d3-ab15-5ce15e474223)

- **Estado F (Revisión Verificada):** En este caso, entonces el JEFE_DEPENDENCIA revisa nuevamente el reporte de seguimiento y quita las observaciones para _Verificar la actividad_ y posteriormente asignarle el estado de _Revisión Verificada_ al reporte de seguimiento:

![estado-f-revision-verificada](https://github.com/udistrital/planeacion_cliente/assets/82072560/f7fa15f7-4f3d-48d4-9b41-5b2b66cf8fe5)

- **Estado G y H (En revisión OAPC y Con Observaciones):** En este estado normalmente el ASISTENTE_PLANEACION (aunque también PLANEACION) inicia la revisión del reporte de seguimiento, puede realizar observaciones:

![estado-g-h-revision-oapc](https://github.com/udistrital/planeacion_cliente/assets/82072560/a5d124b5-75a5-41ac-b166-f3a3961cedec)

En dado caso que se realicen las observaciones por parte de la OAPC, se retornará al estado En Reporte, donde se tendrá que realizar todo el flujo desde el estado B hasta aquí, pasando por las verificaciones de JEFE_DEPENDENCIA y ASISTENTE_PLANEACION.

- **Estado I (Reporte Avalado):** Una vez se realizan las correcciones, se vuelve al estado G y se revisa el reporte, si no tiene observaciones, se avala:

![estado-i-avalar](https://github.com/udistrital/planeacion_cliente/assets/82072560/57054af2-ba18-44f2-a770-a05908345bad)

**Comment by norbeydanilo** [comment]
@milo19980525 Subir documento de actualización de estados y flujo en la carpeta del proyecto en OneDrive y dejar enlace en la issue.
