### ISSUE TITLE
Refactorización cliente planeacion_formulacion_mf (PARTE 2)

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1019]
Se requiere completar la refactorización del MF **PLANEACION_FORMULACION_MF** con base en el API **PLANEACION_CLIENTE** y todos los cambios realizados a la fecha, de forma tal que se culmine con la migración de componentes y se presente el cliente en su forma final.

**Especificaciones técnicas**

1. El repositorio para **PLANEACION_FORMULACION_MF** es: https://github.com/udistrital/planeacion_formulacion_mf
2. Se requiere migrar los **nuevos desarrollos** (en caso de ser requerido) asociados a Formulación, del cliente **PLANEACION_CLIENTE** al MF **PLANEACION_FORMULACION_MF**. Tener en cuenta todos los ajustes, como por ejemplo: #982 , #983 , #997 , #1004 , entre otras.
3. El Cliente debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevos Clientes definidos por la OATI.
4. Los componentes y servicios que son globales a todos los MF deben ser Ubicados en la carpeta **UTILIDADES**.
5. Se debe optimizar el código migrado, eliminando malas practicas de desarrollo.
6. El MF debe quedar optimizado en estilos y con pruebas funcionales en su totalidad.
7. El MF debe consumir los endpoints asociados a los MicroMids desarrollados para SISGPLAN, en lugar de planeacion_mid.

**Sub Tareas**

- [x] Refactorización del cliente **PLANEACION_FORMULACION_MF**
- [x] Migración de nuevas funcionalidades.
- [x] Optimización de código.
- [ ] Ajuste de estilos.

**Criterios de aceptación**

- [x] El MF se encuentra refactorizado.
- [x] El MF cuenta con todas sus componentes y funcionalidades migrados.
- [x] El código del MF se encuentra optimizado.
- [ ] Los estilos del MF son los correspondientes a SISGPLAN.

**Requerimientos**

- [x] #939 .
- [x] #961 .
- [x] #1005 .

**Dependencias**

- planeacion_cliente
- planeacion_mid
- planeacion_formulacion_mid
- planeacion_formulacion_mf
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
@felimarod cargar material asociado a la finalización de la refactorización de planeacion_formulacion_mf (PARTE 2).

Subir evidencia de pruebas realizadas.

**Comment by a52290451** [comment]
Queda faltando:

- [ ] Pruebas funcionales.
- [ ] Comentario final del issue.
- [ ] Deuda técnica.

**Comment by felimarod** [comment]
### Pruebas funcionales
[Pruebas funcionales refactorización Formulación MF](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EfNmJbXwf6JDgXgi6234gyIBsYf9NPBaVqhSYoS_H7T1Mw?e=9u2STq)
### Desarrollos realizados
- Tipado en la página principal
- Tipado en algunos componentes
- Se quitan los códigos quemados
- Se quita código muerto
- Se optimiza código quitando procesos innecesarios y/o redundantes
### Deuda tecnica
- Agregar el desarrollo de: https://github.com/udistrital/planeacion_cliente/issues/997
- Estilos

**Comment by a52290451** [comment]
Se validan pruebas funcionales realizadas.

Queda pendiente la **corrección de bugs encontrados en la formulación de un plan a través de sus múltiples fáses, tanto en el cliente de planeacion con en planeacion_formulacion_mf.** Esto se debe implementar en una nueva tarea.

Queda pendiente despliegue en ambiente de pruebas y producción.
