### ISSUE TITLE
Funcionalidad para consulta y calculo de valor unitario en la identificación de contratistas 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#102]
Se debe realizar la funcionalidad para la consulta de los valores de cada perfil profesional y el calculo de los valores unitarios y totales dependiendo de los meses y dias ingresados con anterioridad en la tabla, la issue debe cumplir con los siguientes requerimientos:

- [x] Realizar los insert en el api de parámetro para el registro del valor de los diferentes perfiles profesionales para el periodo 2021
- [x] Realizar la funcionalidad  del calculo para los valores unitarios y  valores totales, teniendo en cuenta la guia del exel aportado

**Comment by brayaned** [comment]
Se da inicio a la issue.

**Comment by brayaned** [comment]
Se realizaron los inserts en la api de parametros_crud de los correspondientes salarios mensuales y se realizó la funcionalidad para el calculo del valor total de los servicios prestados teniendo en cuenta los meses trabajados y la cantidad de contratistas ingresados. No se presento ningún problema mayor en el desarrollo de la issue.

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
