### ISSUE TITLE
Pruebas Funcionales - Sprints 9, 10, NP-1 y NP-2

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1020]
Tomando como referencia lo realizado en #963 , se requieren llevar a cabo pruebas funcionales en ambiente de pruebas, asociadas a los desarrollos realizados en SISGPLAN en los Sprints 9 y 10 asociados al antiguo tablero, y los Sprints 1 y 2 asociados al nuevo tablero.

**Especificaciones técnicas**

1. Las pruebas funcionales deben cubrir todos los desarrollos cargados en develop en los Sprints 9 y 10 asociados al antiguo tablero, y los Sprints 1 y 2 asociados al nuevo tablero.
2. Se deben tomar como guía las pruebas realizadas por los desarrolladores en local en cada implementación.
3. El documento de pruebas debe especificar el estado en el que se encuentra el desarrollo, si se valida o no su funcionamiento y las observaciones correspondientes.
4. Los desarrollos a probar se encuentran en:
- [Sprint 9](https://github.com/udistrital/planeacion_cliente/milestone/87)
- [Sprint 10](https://github.com/udistrital/planeacion_cliente/milestone/88)
- [Sprint NP-1](https://github.com/orgs/udistrital/projects/54/views/1?filterQuery=sprint%3A%22Sprint+1%22)
- [Sprint NP-2](https://github.com/orgs/udistrital/projects/54/views/1?filterQuery=sprint%3A%22Sprint+2%22)
5. Se deben probar solamente los desarrollos, las tareas de análisis o documentación no se tienen en cuenta.
6. Se trata de hacer un compendio de todas las pruebas realizadas hasta la fecha en un documento y validar su funcionamiento.
7. Adicional al documento que se debe presentar con las pruebas, se requiere realizar una anotación y seguimiento en forma de comentarios en este issue, de tal forma que se evidencien las pruebas realizadas en cada desarrollo y si aprueban o no. Tomar como guía: https://github.com/udistrital/sga_documentacion/issues/42

**Sub Tareas**

- [x] Desarrollo de pruebas funcionales en ambiente de pruebas - SISGPLAN.
- [x] Seguimiento de pruebas funcionales en el issue.

**Criterios de aceptación**

- [x] Se presenta un documento con pruebas de los desarrollos implementados en los Sprints 9 y 10 asociados al antiguo tablero, y los Sprints 1 y 2 asociados al nuevo tablero.
- [x] Se presenta el seguimiento de las pruebas realizadas en el issue, asociadas a cada desarrollo.

**Requerimientos**

- No presenta.

**Dependencias**

- planeacion_cliente.
- planeacion_mid.
- planes_crud.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Pruebas locales (funcionales).
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Oscarjaimes1710** [comment]
Link de archivo de pruebas funcionales realizadas: https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7B663fd1a9-f7d8-4e28-9393-18852844573a%7D&action=editnew

Sprinte 9 -----> 

2-8 --> https://github.com/udistrital/planeacion_cliente/issues/951 -->  Ok
HU2 - 2 Edición de roles usuario PT2 --> https://github.com/udistrital/planeacion_cliente/issues/956 --> No esta funcionando. por falta de data en teoria, por esta razón no se pueden culminar todas las pruebas. 

 2-7 Creación de microfrontend "pendientes_mf" PT2 #957  -->https://github.com/udistrital/planeacion_cliente/issues/957 --> Todo Ok

 HU1 - 4 Consulta de Fechas Asignadas por Otros Usuarios #820  --> https://github.com/udistrital/planeacion_cliente/issues/820 --> Pendiente por culminar pruebas por falta de data

 2 - 4 Desarrollo de componente de notificaciones en cliente de planeación #862 -->https://github.com/udistrital/planeacion_cliente/issues/862 --> Prueba pendiente por culminar por falta de permisos 


SPRINT 10 ---->

**Comment by a52290451** [comment]
Queda pendiente validación de pruebas realizadas.

**Comment by Oscarjaimes1710** [comment]
Se realizan pruebas de las consultas que general error directamente en las apis de consumo, se cargan evidencias al final de este documento : https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7B663fd1a9-f7d8-4e28-9393-18852844573a%7D&action=editnew

Allí podrán encontrar pruebas realizadas para crear un plan desde 0 , donde se encontraron errores y funcionalidades rotas.

**Comment by a52290451** [comment]
De acuerdo a las pruebas realizadas, se obtienen los siguientes resultados:

Realizadas: **54**
No aplican: **2**
Aprobadas (BLANCO): **16**
Requieren corrección (**AMARILLO**): 25
Pendientes (**AZUL**): 4
Fallidas - Bugs (**ROJO**): 8

@Oscarjaimes1710 Por favor revisar y completar pruebas que **Requieren corrección**.

Queda pendiente evaluar pruebas fallidas y crear tareas de corrección relacionadas.

**Comment by Oscarjaimes1710** [comment]
> De acuerdo a las pruebas realizadas, se obtienen los siguientes resultados:
> 
> Realizadas: **54** No aplican: **2** Aprobadas (BLANCO): **16** Requieren corrección (**AMARILLO**): 25 Pendientes (**AZUL**): 4 Fallidas - Bugs (**ROJO**): 8
> 
> @Oscarjaimes1710 Por favor revisar y completar pruebas que **Requieren corrección**.
> 
> Queda pendiente evaluar pruebas fallidas y crear tareas de corrección relacionadas.



Se Realizan todos las pruebas solicitadas por el líder @a52290451 Teniendo en cuenta que hubo algunas pruebas que aparecen con respuesta 404 por falta de data, Se realizar las pruebas pendientes tener en cuenta que se hizo lo que se pudo puesto que hay muchos vacíos de data pero en términos generales el 65% de las pruebas de autenticación funcionaron bien. Queda pendiente por mi parte corregir las pruebas ubicadas en la linea 14 y 15 puesto que no entiendo cual es la corrección que se solicita.

**Comment by a52290451** [comment]
@Oscarjaimes1710 Revisar nuevamente el documento de pruebas y verificar las que se encuentran en amarillo. Se debe completar el ajuste solicitado.
