### ISSUE TITLE
Creación del componente IDENTIFICACIÓN DE RECURSO DOCENTE con funcionalidad de sumas 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#103]
Se debe construir el componente estático para ingresar la identificación de recursos docente, según el Excel entregado para el análisis, se deben implementar la funcionalidad  de las sumas definidas en el excel, la issue debe cumplir con los siguientes requerimientos:

- [x] Construir el componente para el registro de la identificación de recurso docente 
- [x] Crear la funcionalidad para sumas definidas en el excel

**Comment by ndmc98** [comment]
Se da inicio a la issue el 05/11/2021

**Comment by ndmc98** [comment]
- Se crea el componente que simula la tabla de identificación de recursos docente. 
- Se ajusta el esquema de la tabla para la facilidad de la manipulación en el cliente.
- Se configuran las operaciones de suma tanto de las subtablas como el total.

**Comment by ndmc98** [comment]
Se genera el Pull Request con los requerimientos implementados.

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
