### ISSUE TITLE
Propuesta de diferenciación de estilos y componentes lógicos en el cliente core_mf_cliente PT2

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1031]
Se requiere implementar los estilos particulares de SISGPLAN en todos los microfrontends con base en la propuesta realizada en #1014 .

**Especificaciones técnicas**

1. Los microfrontend's de [root](https://github.com/udistrital/planeacion_root_mf), [utilidades ](https://github.com/udistrital/planeacion_utilidades_mf) y PENDIENTE, se encuentran desplegados en entorno de pruebas.
2. Los estilos particulares para SISGPLAN quedaron en el root.
3. Actualmente los mf cuentan con un estilo base y orientado a SGA.
4. En SPA existen módulos que pueden emplearse para los estilos.

**Subtareas**

- [x] Revisar los módulos de SPA, realizar una prueba de concepto y comparar cuál de las 2 propuestas es más viable.
- [x] Para cada uno de los microclientes se deben ajustar los estilos a como se presentaa actualmente el c[liente de planeación](https://github.com/udistrital/planeacion_cliente), comenzando en el siguiente orden:

1. [Utilidades](https://github.com/udistrital/planeacion_utilidades_mf)(Revisar como mostrar la imagen base de SISGPLAN).
2. [Formulacion](https://github.com/udistrital/planeacion_formulacion_mf) 
3. [Seguimiento](https://github.com/udistrital/planeacion_seguimiento_mf)
5. [Evaluacion](https://github.com/udistrital/planeacion_evaluacion_mf)
6. [Macroplanes](https://github.com/udistrital/planeacion_macroplanes_mf)
7. [Pendientes](https://github.com/udistrital/planeacion_macroplanes_mf)
8. [Construccion](https://github.com/udistrital/planeacion_macroplanes_mf)

- [x] Cada uno de los MF deben quedar con el archivo Drone.yml (Tomar como base el de planeacion_utilidades_mf).
- [x] Cada uno de los MF deben quedar con el Readme.md completo.
- [x] Añadir en el package.json lo realizado en: https://github.com/udistrital/planeacion_utilidades_mf/commit/b2cb27067eaf37ed81aa798cbb323ee14f610c15
- [x] Revisar los archivos de variables de entorno y dejar solo en developement aquellas direcciones relacionadas al consumo de APIs por VPN.
- [x] Implementar la propuesta posterior a la aprobación del líder téncino/SM.
- [x] Probar funcionalmente la propuesta a partir de su consumo desde SISGPLAN.

**Criterios de aceptación**

- [x] Se documenta el issue correctamente con los avances realizados de manera progresiva.
- [x] El cliente de SISGPLAN (compuesto por el root y demás mf's) presenta los estilos de manera correcta.
- [x] Todos los MF cuentan con la estructura base y presentan todas las características para ser desplegados en pruebas.

**Requerimientos**

- [x] Refactor de todos los mf 

**Dependencias**

- Todos los MF de SISGPLAN.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by C0C045** [comment]
# Investigación Módulo de estilos single-spa
Según la documentación de [single-spa](https://single-spa.js.org/docs/module-types) el tipo de microfrontend que nos permite generar un módulo con propiedades compartidas en común entre los demás MF's es el de utilidades, sin embargo, este solo es usado para compartir lógica en común (TS), componentes (Header, Navbar, etc.) o generar algún servicio.
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/daca4039-d2fa-4090-98d4-bd64e0f406c3)
Por ende, para compartir solamente hojas de estilos no es funcional, ya que lo más cercano sería trasladar los componentes ya generados en el CORE al nuevo módulo, pero esto sería replicar el CORE y no tendría sentido cuando la única diferencia entre sistemas son colores y fuentes.

En conclusión, como podemos evidenciar la diferenciación entre los sistema es la paleta de colores usada por cada uno, por ende, la opción óptima es mantener la primera propuesta, ya que de por sí los '[assets](https://github.com/udistrital/assets)' actuales ya nos brinda las hojas de estilos necesarias para tener estilos base en cada sistema y si se llega a dar el caso de implementar nuevos estilos; entonces, bastaría con agregarlos a los '[assets](https://github.com/udistrital/assets)' y redesplegar el servicio.

**Comment by C0C045** [comment]
# Refactor SEGUIMIENTO-MF
Se estilizó y refactorizó el microfrontend de seguimiento de forma efectiva; en dónde todos los estilos se ajustaron según lo visto en [cliente de planeación](https://github.com/udistrital/planeacion_cliente). Además, se ajustaron tanto el Drone.yml, Readme.md, Package.json y Variables de Entorno según lo evidenciado en [utilidades-mf](https://github.com/udistrital/planeacion_utilidades_mf).

**Pruebas Funcionales:**
![seguimiento1](https://github.com/udistrital/planeacion_cliente/assets/55455142/4c55f264-18b5-4bf6-bf7b-b76793065ccc)
![seguimiento2](https://github.com/udistrital/planeacion_cliente/assets/55455142/ddc91de8-9879-467e-a4fe-552c6cfb40df)
![seguimiento3](https://github.com/udistrital/planeacion_cliente/assets/55455142/3e99c482-428e-4ecf-8a3b-8ada11740a39)

**Comment by C0C045** [comment]
# Refactor UTILIDADES-MF
Se estilizó y refactorizó el microfrontend de utilidades de forma efectiva; en dónde todos los estilos se ajustaron según lo visto en [cliente de planeación](https://github.com/udistrital/planeacion_cliente). Además, se ajustaron tanto el Drone.yml, Readme.md, Package.json y Variables de Entorno según lo evidenciado en [utilidades-mf](https://github.com/udistrital/planeacion_utilidades_mf).
Por último, se logró presentar el aplicativo en la ruta raíz de la página; esto se hizo agregando en el layout del root la siguiente propiedad en la etiqueta `<route></route>`:

```html
<route default>
  <application name="@udistrital/planeacion-utilidades-mf"></application>
</route>
```

**Cambios realizados en:** PENDIENTE

**Pruebas Funcionales:**
![utilidades](https://github.com/udistrital/planeacion_cliente/assets/55455142/2fddaaa0-83cb-4877-801d-041de8bc0fd0)

**Comment by C0C045** [comment]
# PR's asociados para la implementación de estilos de cada sistema.
assets: https://github.com/udistrital/assets/pull/21
CORE: https://github.com/udistrital/core_mf_cliente/pull/24
ROOT: https://github.com/udistrital/planeacion_root_mf/pull/14

**Comment by C0C045** [comment]
# Refactor FORMULACION-MF
Se estilizó y refactorizó el microfrontend de formulación de forma efectiva; en dónde todos los estilos se ajustaron según lo visto en [cliente de planeación](https://github.com/udistrital/planeacion_cliente). Además, se ajustaron tanto el Drone.yml, Readme.md, Package.json y Variables de Entorno según lo evidenciado en [utilidades-mf](https://github.com/udistrital/planeacion_utilidades_mf).

**Cambios realizados en:** https://github.com/udistrital/planeacion_formulacion_mf/compare/develop...feature/mf_estilizado

**Pruebas Funcionales:**
![formulacion](https://github.com/udistrital/planeacion_cliente/assets/55455142/773b8196-dd89-4740-9480-b465ce37f7e8)
![formulacion2](https://github.com/udistrital/planeacion_cliente/assets/55455142/1f71a209-e3a5-4705-b9e2-bdbeceac9515)

**Comment by C0C045** [comment]
# Refactor EVALUACION-MF
Se estilizó y refactorizó el microfrontend de evaluación de forma efectiva; en dónde todos los estilos se ajustaron según lo visto en [cliente de planeación](https://github.com/udistrital/planeacion_cliente). Además, se ajustaron tanto el Drone.yml, Readme.md, Package.json y Variables de Entorno según lo evidenciado en [utilidades-mf](https://github.com/udistrital/planeacion_utilidades_mf).

**Cambios realizados en:** https://github.com/udistrital/planeacion_evaluacion_mf/compare/develop...feature/mf_estilizado

**Pruebas Funcionales:**
![evaluacion](https://github.com/udistrital/planeacion_cliente/assets/55455142/b48a8ec9-5cc0-475b-9870-ea482eabbacf)

### NOTA
Cómo se evidencia en las pruebas funcionales, el microfrontend quedo estilizado hasta dónde fue posible, ya que las peticiones del mismo están rotas o el microfrontend en sí esta desactualizado respecto a [cliente de planeación](https://github.com/udistrital/planeacion_cliente).

**Comment by C0C045** [comment]
# Refactor MACROPLANES-MF

Se estilizó y refactorizó el microfrontend de macroplanes de forma efectiva; en dónde todos los estilos se ajustaron según lo visto en [cliente de planeación](https://github.com/udistrital/planeacion_cliente). Además, se ajustaron tanto el Drone.yml, Readme.md, Package.json y Variables de Entorno según lo evidenciado en [utilidades-mf](https://github.com/udistrital/planeacion_utilidades_mf).

**Cambios realizados en:** https://github.com/udistrital/planeacion_macroplanes_mf/compare/develop...feature/mf_estilizado

**Pruebas Funcionales:**
![macroplanes](https://github.com/udistrital/planeacion_cliente/assets/55455142/88f589e5-3fa0-4357-b330-8835cddb7270)

**Comment by C0C045** [comment]
# Refactor PENDIENTES-MF

Se estilizó y refactorizó el microfrontend de pendientes de forma efectiva hasta dónde fue posible; en dónde todos los estilos se ajustaron según lo visto en [cliente de planeación](https://github.com/udistrital/planeacion_cliente). Además, se ajustaron tanto el Drone.yml, Readme.md, Package.json y Variables de Entorno según lo evidenciado en [utilidades-mf](https://github.com/udistrital/planeacion_utilidades_mf).

**Cambios realizados en:** https://github.com/udistrital/planeacion_pendientes_mf/compare/develop...feature/mf_estilizado

**Pruebas Funcionales:**
![pendientes](https://github.com/udistrital/planeacion_cliente/assets/55455142/4c82e5f5-e7af-4b71-8ccb-815f030b2734)

### NOTA
Cómo se evidencia en las pruebas funcionales, el microfrontend quedo estilizado hasta dónde fue posible, ya que la petición para obtener el documento falla.
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/dd6586d9-8d0a-4b17-963d-19169bb1e680)
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/b0c71fb3-1509-4828-995c-68a3489ae716)

**Comment by C0C045** [comment]
# PR's
Seguimiento MF: https://github.com/udistrital/planeacion_seguimiento_mf/pull/8
Utilidades MF: https://github.com/udistrital/planeacion_utilidades_mf/pull/3
Formulación MF: https://github.com/udistrital/planeacion_formulacion_mf/pull/6
Evaluación MF: https://github.com/udistrital/planeacion_evaluacion_mf/pull/1
Macroplanes MF: https://github.com/udistrital/planeacion_macroplanes_mf/pull/4
Pendientes MF: https://github.com/udistrital/planeacion_pendientes_mf/pull/7
