### ISSUE TITLE
Bug: Corrección de fallos en la formulación de un plan de acción a través de sus múltiples fases.

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1037]
Se requiere corregir los bugs asociados al flujo de formulación de un plan a través de sus múltiples fases, tanto en el cliente de planeación con en planeacion_formulacion_mf.

**Especificaciones Técnicas**

- El flujo de formulación de un plan de acción presenta múltiples fallas que no permiten que un plan de acción pase de la fase de formulación. Se requiere identificar la causa de dichas fallas e implementar una posible solución en código a dichas fallas.

- Adicionalmente, posterior a la corrección del bug inicial, se debe garantizar que el módulo de formulación responda correctamente en cada una de sus funcionalidades.

-  Se debe documentar la issue, indicando los elementos y aspectos que se deben tener en cuenta para realizar una correcta formulación de un plan de acción, partiendo desde la creación de la plantilla del plan de acción en el módulo de construcción.

**Material de apoyo**

Pruebas funcionales planeacion_formulacion_mf: https://github.com/udistrital/planeacion_cliente/issues/1019#issuecomment-2097516562

Pruebas funcionales globales: 
https://github.com/udistrital/planeacion_cliente/issues/1020#issuecomment-2099326263

**Sub Tareas**

- [x] Corrección de bugs en submódulo de formulación en planes de acción.
- [x] Pruebas funcionales de todas las funcionalidades del submódulo de formulación en planes de acción.
- [x] Recomendaciones y pautas para la formulación de un plan de acción.

**Criterios de aceptación**

- [x] El submódulo de formulación en planes de acción se encuentra funcionando correctamente en cada uno de sus flujos permitidos.

**Requerimientos**

No aplica

**Dependencias**

- planeacion_mid.
- planes_crud.
- planeacion_cliente.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by felimarod** [comment]
Con el plan 

![Image](https://github.com/udistrital/planeacion_cliente/assets/85894335/7e4acb8a-7bd3-4c88-9e40-6241113b4a34)

Se hizo el seguimiento de por que no se podía culminar el plan, para pasarlo de estado "En formulación" a "Formulado".

Esto se debe a la estructura del plan. Revisando el endpoint en `planeacion_mid`: se encuentra un fragmento en el cual se verifica si el plan tiene el campo "PONDERACIÓN" en `controllers/formulacion.go:1289`.

```go
strings.Contains(strings.ToUpper(hijos[i]["nombre"].(string)), "PONDERACIÓN") && strings.Contains(strings.ToUpper(hijos[i]["nombre"].(string)), "ACTIVIDAD") || strings.Contains(strings.ToUpper(hijos[i]["nombre"].(string)), "PONDERACIÓN")
```

Dado que el campo no se encontraba, se salía de los condicionales sin devolver alguna respuesta.

**Comment by felimarod** [comment]
Tomando como guía la estructura de los planes "Fabian" y "Seguimiento PruebaSure" ya que son dos planes que se encuentran en estado avalado, se creo el formato: 
![Image](https://github.com/udistrital/planeacion_cliente/assets/85894335/525c6bcf-af0b-4dc6-b747-748da1e050c8)

Que consta de los campos Ponderación y Actividad General, donde Ponderación debe ser de tipo númerico
![Image](https://github.com/udistrital/planeacion_cliente/assets/85894335/55017b7a-54ab-416a-9df5-9fdb75c493b7)

Observaciones:
- El problema como tal se da al construir los planes desde el modulo de construcción, ya que desde ahí, se permite dejar la estructura sin el item necesario, que es el de "ponderación"

Idea de solución:
- Al construirse un plan se podría agregar automáticamente un campo o nivel de Ponderación el cual no se pueda inactivar o modificar el tipo de valor 'númerico' para así asegurar que todos los planes nuevos tengan este requisito

**Comment by felimarod** [comment]
Observación:
Al cargar los planes, se traen desde dos lugares:
1. Desde planes_crud: trayendo los que estan en estado activo y que pertenecen a la unidad y vigencia seleccionada. Luego,
2. También desde planes_crud: trae los planes de interes, que serían los planes que se encuentran habilitados para su formulación
Esto es lo que da paso a que se repitan los planes en el seleccionable de Plan

**Comment by felimarod** [comment]
Se nota que el paso del plan en estado "Pre Avalado" al estado "Ajuste Presupuestal" no se da, el plan pasa directamente al estado "En Formulación" 
Notese en la versión 2 y 3:
![image](https://github.com/udistrital/planeacion_cliente/assets/85894335/655e75eb-95db-4ff1-939e-2e990715ef41)

Se debe evaluar si el paso de "Pre Avalado" a "En Formulación" es un paso que cumple con lo esperado o se debe hacer algún ajuste.

Además, se nota que al ingresar al plan en su versión 2, se siguen mostrando las opciones de "Dar Aval" y "Remitir Ajuste Plan de Acción".
![image](https://github.com/udistrital/planeacion_cliente/assets/85894335/0116e1f4-b12d-4d51-ab0a-b2b3bbdc0e2a)

**Comment by a52290451** [comment]
@felimarod Se requiere cargar pruebas funcionales de todo el flujo de formulación (VIDEO).

**Comment by a52290451** [comment]
Se requiere dar consideraciones finales para que un plan sea formulado correctamente.

**Comment by felimarod** [comment]
[Vídeo de el flujo completo](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/computo_udistrital_edu_co/EezHxYc4MitIsorJ97OFgw0BLMtOUF5a_F2H66beuxunLw?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=gLiurm)

**Comment by felimarod** [comment]
### Observación
No se logró formular un plan con la vigencia 2023 ya que no se podían agregar los contratistas correctamente
**Contexto:**
Con el rol de unidad y con un plan en estado de formulación, se desea hacer la identificación de contratistas.
**Comportamiento esperado:**
Configuración de los contratistas y posterior guardado dentro de la actividad.
**Comportamiento actual:**
![Image](https://github.com/udistrital/planeacion_cliente/assets/85894335/26972b54-278f-4231-8ebf-24a30289d4cc)
**Observaciones:**
Se hace la petición a `https://autenticacion.portaloas.udistrital.edu.co/apioas/parametros/v1/parametro_periodo?query=ParametroId:485,PeriodoId:25` la cual retorna un objeto vacío `[{}]`

**Comment by felimarod** [comment]
Observación
-
**Contexto:**
Se están revisando las actividades de un plan en estado "Aval".
**Comportamiento esperado:**
Mensajes y botones congruentes con el estado actual de el plan.
**Comportamiento actual:**
Mientras se está visualizando una actividad:
![Image](https://github.com/udistrital/planeacion_cliente/assets/85894335/b5b903f3-d645-4761-80f5-56a56696e68d)
1. Al dar click en "Cancelar", sale el siguiente mensaje:
  ![Image](https://github.com/udistrital/planeacion_cliente/assets/85894335/98900ca7-540d-4f0f-ad13-39a906191b58)
  Se esperaría una pregunta como "¿Desea cerrar la actividad?"
2. Se tiene el botón "Guardar", a pesar de que no se pueden modificar los datos, este botón sigue estando habilitado para hacer la petición a los servicios pertinentes, comportamiento que no me parece el adecuado.
