### ISSUE TITLE
Revisión de variable de entorno ACADEMICA_JBPM_SERVICE

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1038]
Se requiere validar el uso de la variable ACADEMICA_JBPM_SERVICE para tomar la decisión si eliminarla o mantenerla.

**Especificaciones técnicas**

1. Actualmente se encuentran nuevos desarrollos para el sistema monolito (cliente y api's), se encuentran desplegados en entorno de pruebas.
2. Estas nuevas funcionalidades se encuentran en diferentes micromids y microclientes (nueva arquitectura).
3. Se está haciendo uso de la variable ACADEMICA_JBPM_SERVICE  en los clientes.

**Subtareas**

- [x] Revisar cuál es el uso de la variable ACADEMICA_JBPM_SERVICE y verificar si es necesaria para la lógica del negocio.
- [x] En dado caso de no requerirse el uso de la variable, eliminar la lógica relacionada a esta en el cliente del monolito.
- [x] En dado caso de no requerirse el uso de la variable, eliminar la lógica relacionada a esta en los mf que se vean afectados.

**Criterios de aceptación**

- [x] Se documenta el issue correctamente con los avances realizados de manera progresiva.
- [x] El cliente de SISGPLAN funciona de manera correcta posterior al cambio.
- [x] Todos los MF y el cliente (monolito) afectado por el cambio funcionan correctamente.

**Requerimientos**

- [x] Refactor de todos los mf 

**Dependencias**

- Todos los MF de SISGPLAN.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] PR a Release.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
- Se realiza revisión de la variable academica_jbpm, en el sistema de planeación, específicamente en el monolito, donde se evidencia que solo se hace un llamado en un componente en específico llamado "información-basica":

![Image](https://github.com/udistrital/planeacion_cliente/assets/73924638/a71cb604-943b-49ea-9134-73dd625a4009)

- Se revisó este componente y se encuentra que actualmente tiene toda la sección de HTML en comentario, por lo cual se entiende que no está en uso dicho componente:

![Image](https://github.com/udistrital/planeacion_cliente/assets/73924638/1231be88-c98f-429f-a50b-79250a7c86b9)

- Adicional a esto se verifica en donde se podría realizar algún tipo de llamado de este componente para ser usado en otro, las coincidencias reflejan que este componente solo se encuentra creado, pero no se usa en ninguna sección:

![Image](https://github.com/udistrital/planeacion_cliente/assets/73924638/6178b2f4-d53b-4317-8db4-9a8797333aa7)

### NOTA ###

Con base en la información anteriormente presentada se toma la decisión de eliminar la variable de las variables de entorno y colocar en comentario, donde se hace el llamado o uso de esta, en el componente "informacion-basica"

**Comment by Mechaz123** [comment]
## MICROFRONTENDS ##

**Comment by Mechaz123** [comment]
- PR de planeacion_cliente: https://github.com/udistrital/planeacion_cliente/pull/1070
- PR de planeacion_pendientes_mf: https://github.com/udistrital/planeacion_pendientes_mf/pull/9
- PR de planeacion_evaluacion_mf: https://github.com/udistrital/planeacion_evaluacion_mf/pull/2
- PR de planeacion_formulacion_mf: https://github.com/udistrital/planeacion_formulacion_mf/pull/8
- PR de planeacion_seguimiento_mf: https://github.com/udistrital/planeacion_seguimiento_mf/pull/10
- PR de planeacion_reportes_mf: https://github.com/udistrital/planeacion_reportes_mf/pull/1
