### ISSUE TITLE
Cambio de cargo en vinculación - quitar revisión de contratista

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1039]
Se requiere eliminar la validación de cargo id asociado a contratista en procesos de formulación y seguimiento en MF y en el monolito.

**Especificaciones técnicas**

1. Actualmente se encuentran nuevos desarrollos para el sistema monolito (cliente y api's), se encuentran desplegados en entorno de pruebas.
2. Estas nuevas funcionalidades se encuentran en diferentes micromids y microclientes (nueva arquitectura).
3. Se está haciendo uso de la validación cargo_id asociado a contratista en los clientes.
4. Los ids de los cargos que deben quedar son: 319, 312 y 320.

**Subtareas**

- [x] Eliminar la validación en ambos tipos de cliente.

**Criterios de aceptación**

- [x] Se documenta el issue correctamente con los avances realizados de manera progresiva.
- [x] El cliente de SISGPLAN funciona de manera correcta posterior al cambio.
- [x] Todos los MF y el cliente (monolito) afectado por el cambio funcionan correctamente.

**Requerimientos**

- [x] Refactor de todos los mf 

**Dependencias**

- Todos los MF de SISGPLAN.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
La funcionalidad asociada a la vinculación del usuario va desarrollada en el mid, ya que dentro de formulación_mid, existe una función llamada Vinculación tercero, el cual tiene los tipos de vinculaciones permitidas, para este caso se dejan solo las 3 vinculaciones iniciales:

![Image](https://github.com/udistrital/planeacion_cliente/assets/73924638/2ae28b2d-e969-4b18-a0b9-56d1b195ad80)
