### ISSUE TITLE
Modulo para agrupar componentes funcionales y cookies PT1

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1040]
Se requiere implementar un módulo lógico en single SPA que agrupe las funcionalidades compartidas en diferentes micro frontends.

**Especificaciones técnicas**

1. Los microfrontend's de [root](https://github.com/udistrital/planeacion_root_mf), [utilidades ](https://github.com/udistrital/planeacion_utilidades_mf), se encuentran desplegados en entorno de pruebas.
2. Los estilos particulares para SISGPLAN (generales) quedaron en el root.
3. Cada uno de los mf maneja sus propios estilos.

**Subtareas**

- [x] Identificar las funcionalidades lógicas compartidas en diferentes MF como el árbol manejado para armar los planes.
- [x] Una vez identificadas las funcionalidades, estas se deben agrupar en un componente de tipo módulo.
- [x] En cada uno de los MF dónde se dejó de utilizar la funcionalidad desde ellos mismos, deben cambiarse su consumo al utilizar el módulo creado.
- [x] Probar el funcionamiento correcto de las funcionalidades pasadas al módulo.

**Criterios de aceptación**

- [x] Se documenta el issue correctamente con los avances realizados de manera progresiva.
- [x] Se agrupan de manera correcta los componente lógicos compartidos en diferentes MF en un módulo de single SPA.
- [x] Se realizan las pruebas funcionales necesarias para garantizar el correcto cambio de consumo de lógica.

**Requerimientos**

- [x] Refactor de todos los mf 

**Dependencias**

- Todos los MF de SISGPLAN.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by C0C045** [comment]
# Primera implementación del módulo de utilidades

Para poder implementar un módulo de utilidades con [single-spa](https://single-spa.js.org/docs/getting-started-overview), es necesario tener en cuenta que principalmente este tipo de microfrontend se basa en compartir lógica común o generar servicios entre las diferentes aplicaciones microfrontend's. Por ende, usaremos este modulo precisamente para compartir toda lógica repetitiva entre los microfrontend's; tal es el caso del sistema de cookies que manejan algunos microfrontend's para comunicarse entre ellos.

Por otro lado, [single-spa](https://single-spa.js.org/docs/getting-started-overview) no soporta aún módulos de utilidades para el framework de Angular, tal cuál como vemos a continuación:
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/ed466d01-c020-43cb-9170-d9c82249ec71)
Por tanto, esta limitación impide compartir componentes enteros de Angular entre los diferentes microfrontend's.

Una vez teniendo todo lo anterior claro, se procedió a integrar el módulo de utilidades tal que así:
### 1. Configuración del Microfrontend de tipo utilidad
Se ejecuta el siguiente comando en consola `npx create-single-spa`, para después dar nombre a nuestro microfrontend y seleccionar el tipo de microfrontend que es, en este caso: **in-browser utility module (styleguide, api cache, etc)**; de resto solo se sigue la configuración normal sin seleccionar ningún framework.
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/3bc3c54d-8dfc-4d48-a80e-dc34287c93c4)

### 2. Importar el nuevo módulo de utilidad en el ROOT
Como siguiente paso es necesario importar el módulo de utilidad en el `index.ejs` de tal manera que quede debajo del import de single-spa, tal que así:
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/54c2c321-4095-47c4-939c-4f884f534e0b)

### 3. Adicionar microfrontend en Webpack config
Para este paso se agrega el microfrontend de utilidades en el `extra-webpack.config.js` del microfrontend que lo vaya a usar, en este caso 'planeacion-formulacion-mf'.
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/9650d0b9-5c46-4703-bd9a-df61ab3aff61)

### 4. Generamos una declaración para el microfrontend de utilidad
Creamos el archivo `decl.d.ts` en `src/app`; esto con el motivo de omitir el error posterior al importar los métodos del microfrontend de utilidad, tal que así:
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/6c9ea8d5-c145-45b2-9d8d-b99bfd725094)

### 5. Implementación de lógica común
En el microfrontend de utilidades declaramos cada uno de los métodos que deseamos exportar, en este caso el método de obtener las Cookies del navegador, tal que así:
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/339a8fff-809d-4c02-99e3-d80107647e22)

### 6. Importación de funcionalidades
Por último paso, ya nos quedaría importar cada uno de los métodos que vamos a usar del microfrontend de utilidades, en este caso usaremos `getCookie` para obtener las cookies del navegador y operar con estas, tal que así:
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/8fb872e0-8de8-47ca-ad1c-0b2c7d2f393a)
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/ea6c051b-9164-40c7-9b9d-0f446e889e63)

**Comment by C0C045** [comment]
# NOTA
@milo19980525 se solicita un repositorio específico para subir los avances del microfrontend de utilidades o módulo de utilidades.

**Comment by C0C045** [comment]
# Commit asociado a cada uno de los cambios
Enlace de acceso: https://github.com/udistrital/planeacion_utility_module/commit/7cc0e743f2515922ef3057d679d1a05700460229
