### ISSUE TITLE
Pruebas funcionales de monolito en pruebas

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1041]
Tomando como referencia lo realizado en #963 , se requieren llevar a cabo pruebas funcionales en ambiente de pruebas, asociadas a los desarrollos realizados en SISGPLAN en los Sprints 3, 4 y 5 asociados al nuevo tablero.

**Especificaciones técnicas**

1. Las pruebas funcionales deben cubrir todos los desarrollos cargados en release en los Sprints 3, 4 y 5 asociados al nuevo tablero.
2. Se deben tomar como guía las pruebas realizadas por los desarrolladores en local en cada implementación.
3. El documento de pruebas debe especificar el estado en el que se encuentra el desarrollo, si se valida o no su funcionamiento y las observaciones correspondientes.
4. Los desarrollos a probar se encuentran en:
- [Sprint NP-3](https://github.com/orgs/udistrital/projects/54/views/1?filterQuery=sprint%3A%22Sprint+3%22)
- [Sprint NP-4](https://github.com/orgs/udistrital/projects/54/views/1?filterQuery=sprint%3A%22Sprint+4%22)
- [Sprint NP-5](https://github.com/orgs/udistrital/projects/54/views/1?filterQuery=sprint%3A%22Sprint+5%22)
5. Se deben probar solamente los desarrollos, las tareas de análisis o documentación no se tienen en cuenta.
6. Se trata de hacer un compendio de todas las pruebas realizadas hasta la fecha en un documento y validar su funcionamiento.
7. Adicional al documento que se debe presentar con las pruebas, se requiere realizar una anotación y seguimiento en forma de comentarios en este issue, de tal forma que se evidencien las pruebas realizadas en cada desarrollo y si aprueban o no. Tomar como guía: https://github.com/udistrital/sga_documentacion/issues/42

8. Carpeta para pruebas funcionales: https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EvgM4KowvOBKjdXD3aFLGV0BGcATolW8LorkydQUQnYMuA?e=MZjaiw

**Sub Tareas**

- [x] Desarrollo de pruebas funcionales en ambiente de pruebas - SISGPLAN.
- [x] Seguimiento de pruebas funcionales en el issue.

**Criterios de aceptación**

- [x] Se presenta un documento con pruebas de los desarrollos implementados en los Sprints 3, 4 y 5 asociados al nuevo tablero.
- [x] Se presenta el seguimiento de las pruebas realizadas en el issue, asociadas a cada desarrollo.

**Requerimientos**

- No presenta.

**Dependencias**

- planeacion_cliente.
- planeacion_mid.
- planes_crud.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Pruebas locales (funcionales).
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
Las pruebas funcionales se han estado realizando para el módulo de construcción, donde se ha probado granularmente todo el sistema, realizando la documentación respectiva.

A continuación, se adjunta el link del Excel donde se están realizando las pruebas funcionales al sistema en ambiente de pruebas:
https://pruebasplaneacion.portaloas.udistrital.edu.co/#/pages/plan/habilitar-reporte
