### ISSUE TITLE
2 - 8 Documentación Técnica - Módulo de notificaciones internas.

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1042]
Se requiere construir un documento técnico en el cual se describa el desarrollo realizado con el módulo de notificaciones internas a nivel de sistema.

**Especificaciones técnicas**

1. El documento técnico debe contener los siguientes elementos:

- Portada
- Tabla de Contenido
- Objetivos
- Requerimientos
- Tecnologías implementadas
- Costos de utilización
- Conceptos básicos
- Aspectos técnicos
- Instrucciones de implementación
- Conclusiones
- Recomendaciones y Mejoras

Tomar como guía el siguiente ejemplo:

https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EW-h4D4dgZBGsfJwUCMuonsBtJpSbtY-gBtAP5rFXSaqtQ?e=g7Delw

Incluir tabla de versionado de documento tal como se muestra en el siguiente ejemplo de documento técnico:

https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EcZwcyp8jB5KsBUJs7dz4_cB8JegJ2vfUL4oX_rjN0oXkQ?e=92Dfiu

2. En la sección de aspectos técnicos se debe incluir el detalle de la implementación, tanto la que ya existía como lo nuevo que se realizo.

**Sub Tareas**

- [x] Creación de Manual Técnico: Notificaciones Internas.

**Criterios de aceptación**

- [x] Existe un Manual Técnico que me permite implementar el servicio de notificaciones internas en mi sistema.

**Requerimientos**

- [x] Completar issue #862 .
- [x] Completar issue #819 .
- [x] Completar issue #865 .
- [x] Completar issue #990 .
- [x] Completar issue #1002 .
- [x] Completar issue #1004 .
- [x] Completar issue #1003 .
- [x] Completar issue #1018 .
- [x] Completar issue #1035 . 

**Dependencias**

- planeacion_cliente.
- web-components.
- notificacion_mid.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Se solicita por favor la revisión del manual técnico, teniendo en cuenta que aún quedan pendientes algunos aspectos: 
[Link del manual ](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EdixQ978d0hFgJi-psItfw8B1HgCUT9vVDjo4hAqkWQ5qg?e=mIEGhW)

**Comment by a52290451** [comment]
Queda pendiente revisión final del documento.

**Comment by a52290451** [comment]
Correcciones requeridas:

1. en "Aspectos técnicos" se requiere incluir la implementación de notificaciones mediante web-component.
2. Se requiere completar sección de "Recomendaciones y mejoras".

**Comment by diegobauto** [comment]
Se añaden recomendaciones y mejores,  y la implementación de notificaciones (intercambio) en el aparte de instrucciones de implementación:
[Link del manual ](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EdixQ978d0hFgJi-psItfw8B1HgCUT9vVDjo4hAqkWQ5qg?e=mIEGhW)

**Comment by a52290451** [comment]
Se cierra issue con la revisión del manual técnico elaborado.

Se solicita a @norbeydanilo realizar una segunda revisión indicando las posibles mejoras al mismo.

Mis observaciones que pueden ser abordadas en una segunda versión son:

1. Agregar diagrama de componentes y de secuencia que ejemplifique a nivel de arquitectura el flujo de las notificaciones a nivel de sistema, tanto para su registro como para su consulta.
2. Incluir links en el documento que permitan al lector revisar el código señalado en cada caso.
3. Complementar aspectos técnicos e instrucciones de implementación con desarrollo sugerido en clientes.
