### ISSUE TITLE
Pruebas - Bug: estandarización de códigos de abreviación.

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1043]
Se requiere estandarizar la utilización de códigos de abreviación en planeación cliente y derivados, en vez de utilizar el ID registrado en la BD. Esto representa una mala práctica de desarrollo que puede causar problemas de compatibilidad, tanto en ambiente de pruebas como de producción.

**Especificaciones técnicas**

1. Se debe reemplazar cualquier ID quemado, tanto en planeacion_cliente, como en los MF derivados, de tal forma que se consuma en su lugar el código de abreviación del mismo para su búsqueda.
2. Para cada caso, se debe comprobar que el código de abreviación registrado en la BD de pruebas, sea el mismo que esté en la BD de producción.
3. Si no existe un código de abreviación que reemplace el ID quemado, se debe evaluar la posibilidad de registrarlo y utilizarlo.
4. En caso de no encontrar una alternativa para reemplazar el ID quemado, se debe dejar la observación en el issue, junto con las indicaciones necesarias para encontrar el ID en el código.

**Sub Tareas**

- [x] Pruebas funcionales de la estandarización de códigos de abreviación.

**Criterios de aceptación**

- [x] El código fuente de SISGPLAN se encuentra libre de IDs quemados para realizar consultas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by felimarod** [comment]
Issue anterior con el desarrollo:
- https://github.com/udistrital/planeacion_cliente/issues/1036

**Comment by felimarod** [comment]
[Pruebas funcionales(en desarrollo)](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EQqbrIQONFtOjRypdOwdJsYBRkWD2v9wViIbMCitMfgvGw?e=k19fJ3)

**Comment by felimarod** [comment]
Objeto en donde se cargarán los id's antes de ser consultados:
![image](https://github.com/udistrital/planeacion_cliente/assets/85894335/a35b72a8-a240-4f23-a3a7-029ac424dab0)
Objeto con los id's cargados:
![image](https://github.com/udistrital/planeacion_cliente/assets/85894335/e9f2708d-d67b-4c8f-941b-3b091f2202ff)

**Comment by a52290451** [comment]
Queda pendiente despliegue en pruebas.

**Comment by a52290451** [comment]
Se despliegan los ajustes realizados en ambiente de pruebas
