### ISSUE TITLE
Bug: Se repiten planes de acción al consultarlos y colocarlos en el select en formulación.

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1044]
Actualmente se presenta un Bug en la consulta de planes de acción en formulación, el cual produce que se muestre el mismo plan de acción mas de una vez en la opción de búsqueda de planes de acción.

El error se relaciona con la cantidad de versiones que tiene cada plan, tomando cada versión como una opción independiente en el buscador. Se debe limitar esto para que solamente aparezca una vez cada plan de acción disponible en el buscador.

Evidencia:

![Image](https://github.com/udistrital/planeacion_cliente/assets/36229498/5175fdad-3202-42e1-bff4-4367168cc20a)

**Especificaciones técnicas**

1. La búsqueda de planes de acción en la BD, trae todos los planes registrados, incluyendo cada una de sus versiones disponibles. Se debe aplicar una especie de filtro en la consulta para que solamente traiga una versión de cada plan de acción.
2. En caso de no lograr controlar el filtrado de planes de acción en la petición, se debe aplicar un filtro adicional al obtener la respuesta de la petición, de tal forma que no se repitan planes de acción en el buscador.

**Sub Tareas**

- [x] Eliminar planes de acción repetidos en las opciones disponibles en el buscador de formulación.

**Criterios de aceptación**

- [x] Cuando busco los planes de acción disponibles para una unidad y vigencia en particular, aparece solamente una opción por cada plan y no elementos repetidos.

**Requerimientos**

No aplica

**Dependencias**

- planeacion_cliente.
- planeacion_mid.
- planes_crud.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by felimarod** [comment]
Estando en el apartado de Formulación de Planes, con el rol "PLANEACION", se obtiene un total de 62 planes, donde no se repite ninguno, algunos casos particulares es "Plan de accion prueba redireccionamiento", ya que hay otro plan que tiene por nombre " Plan de accion prueba redireccionamiento ", los planes como tal se diferencian netamente por el nombre, entonces dado cualquier espacio(' ') lo tomará como otro plan

**Comment by felimarod** [comment]
Se agrega la evidencia de solución con el plan puesto de ejemplo en la issue

![Image](https://github.com/udistrital/planeacion_cliente/assets/85894335/196540a0-1b20-4bc7-892c-dabe527619b3)

**Comment by a52290451** [comment]
- [ ] Se requiere realizar esta misma implementación en planeacion_formulacion_mf.

**Comment by felimarod** [comment]
Desarrollo implementado en [planeacion_formulacion_mf(PR)](https://github.com/udistrital/planeacion_formulacion_mf/pull/9)
