### ISSUE TITLE
Revisión y levantamiento inicial para programación presupuestal funcionamiento -- inversión

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/planeacion_cliente#1046]
Se requiere realizar el análisis sobre la "programación presupuestal". Tener en cuenta a que se refiere cuando se habla en el contexto de funcionamiento y desde SISGPLAN como está o debería estar soportado. Por otra parte, realizar el ejercicio inicial para inversión, esto con el propósito de implementarlo según la necesidad de la OAP.

**Sub Tareas**

- [ ] Establecer comunicación con el usuario para aclarar el término de programación presupuestal y su abordaje en SISGPLAN.
- [ ] Aclarar para el ámbito de funcionamiento.
- [ ] Hacer levantamiento/propuesta para el ámbito de inversión.

**Criterios de aceptación**

- [ ] Flujo/diagrama/documento con las aclaraciones específicas para funcionamiento.
- [ ] Flujo/diagrama/documento con las aclaraciones específicas para inversión.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by norbeydanilo** [comment]
Documentar con información levantada y/o consultada.

Ubicar flujo o levantamiento que se va aterrizando y/o proponiendo de forma continua.

@BikerMetalHead

**Comment by BikerMetalHead** [comment]
Se realiza la primera reunión formal para el levantamiento de requerimientos de programación presupuestal desde sisgplan 
[Acta](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/Ea2PIXQSPPNNlMM5S034Rl4BgRH3FzFMbwT8Ou9WP2emcQ?e=mAerDR)

**Comment by BikerMetalHead** [comment]
Se realiza una hoja de ruta para el levantamiento de los requerimientos para el módulo de programación presupuestal, el cual se describe a continuación: 

1. Interfaz de Usuario (UI) Intuitiva
•	Dashboard Principal: Vista general con resúmenes y estadísticas clave, como el estado de los presupuestos, planes de acción en curso, y alertas importantes.
•	Navegación Sencilla: Menús claros y accesibles para facilitar la navegación entre diferentes secciones del módulo.
2. Gestión de Planes de Acción
•	Creación y Edición de Planes: Formularios para crear y modificar planes de acción con campos detallados para objetivos, actividades, responsables, plazos y métricas de éxito.
•	Visualización de Planes: Opciones para ver los planes de acción en formato de lista, calendario, o diagramas
•	Estado de los Planes: Indicadores de progreso y estado (pendiente, en progreso, completado).
3. Presupuestación
•	Asignación de Presupuestos: Funcionalidad para asignar presupuestos a cada plan de acción o actividad específica.
•	Categorías de Presupuesto: Posibilidad de definir y clasificar gastos en diferentes categorías (e.g., recursos humanos, infraestructura, materiales).
•	Ajustes y Reasignaciones: Herramientas para ajustar presupuestos y reasignar fondos según sea necesario.
4. Control y Seguimiento
•	Monitoreo de Ejecución: Herramientas para rastrear el progreso de las actividades y el uso del presupuesto en tiempo real.
•	Reportes y Análisis: Generación de informes detallados y gráficos sobre el avance de los planes y el estado del presupuesto.
•	Alertas y Notificaciones: Sistema de alertas para plazos próximos, desvíos presupuestales, y otros eventos importantes.
5. Colaboración y Comunicación
•	Asignación de Responsables: Posibilidad de asignar responsables a cada plan de acción y actividad.
•	Comentarios y Discusiones: Espacios para comentarios y discusiones dentro de cada plan o actividad para facilitar la comunicación entre los miembros del equipo.
•	Historial de Cambios: Registro de todas las modificaciones realizadas en los planes y presupuestos para mantener un historial detallado.
6. Integración con Otros Sistemas
•	Importación y Exportación de Datos: Capacidades para importar datos de otros sistemas (e.g., sistemas financieros, ERPs) y exportar información en formatos estándar (e.g., Excel, PDF).
•	APIs: Interfaces de programación de aplicaciones (APIs) para integrar con otros sistemas de gestión de la universidad.
7. Seguridad y Permisos
•	Control de Acceso: Gestión de usuarios y roles con permisos específicos para acceder y modificar diferentes partes del módulo.
•	Seguridad de Datos: Implementación de medidas de seguridad para proteger la información sensible, incluyendo cifrado y copias de seguridad regulares.
8. Evaluación y Mejora Continua
•	Feedback de Usuarios: Herramientas para recopilar feedback de los usuarios sobre la funcionalidad y usabilidad del módulo.
•	Actualizaciones y Mejoras: Planificación de actualizaciones regulares para mejorar el sistema basándose en el feedback recibido y en nuevas necesidades identificadas.

**Comment by BikerMetalHead** [comment]
se construye modelo de macro procesos del ciclo de vida de los proyectos de inversión, sus planes asociados y los sistemas que intervienen en cada punto.
[Modelo](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/EWsFWSSvW-hFrAGGA-MhU1UB2bRS7C4l9I5AlkotIYSQuA?e=ZYsIfm)

**Comment by BikerMetalHead** [comment]
Se realiza versión 1 de diagrama de arquitectura de la información
[Diagrama](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EQp3EiXPcp9Gt1PmNxlktaEBbpOzgZCDxQV2UIvKBbZ1Vg?e=NrWJ2A)

**Comment by BikerMetalHead** [comment]
Se realizan correcciones indicadas al diagrama de arquitectura de la información.
[Diagrama](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EQp3EiXPcp9Gt1PmNxlktaEBbpOzgZCDxQV2UIvKBbZ1Vg?e=NrWJ2A)

**Comment by BikerMetalHead** [comment]
Se realizan los diagramas de flujo de los procesos de SISGPLAN en bizagi. Desde el diagrama general hasta los diagramas detallados por proceso y módulos:
[General](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/EUfbh8oG3SpAiSM3LomdldYBUFV0RLY5fFiCdhIzQFmYBA?e=vVs6bC)
[Construcción](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/EYgEFYfiE9hOsjuMPfIUSwABuqc3sqY2-iir4Gdo17m4Tw?e=73tB6T)
[Formulación](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/Ea9fV3oCAa9Ih1-V4vo6-KQBpw5wvsJIW__i7OFwp1zmAQ?e=CWuCX7)
[seguimiento](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/Ee2Lui6GGtNHsdEumolV-gEBAbSBxE7UD1FHhX8cmNcazQ?e=Nrcp0E)
[reportes](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/Eeiyl4-6qRxEvnJjxQVYJtUBIpDcDc3IwenJa8c_xSPWSw?e=N6Lde7)
[Reformulación](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/Eb1x4G7DkhJKjbCxW4b4L9QBwMlD2CfAekMxR4oYUv8bUQ?e=eclzNm)

**Comment by norbeydanilo** [comment]
Ajustar diagramas según comentarios de la sesion del 25/06/24. Enlazar carpeta @BikerMetalHead

**Comment by norbeydanilo** [comment]
Se procede al cierre de esta tarea pues la issue #1156 continua con el análisis para inversión. Los ajustes y actualización de diagramas se hace sobre la issue #1155 @BikerMetalHead
