### ISSUE TITLE
Corrección de funcionamiento MF y micro Mids de Pendientes y Evaluacion

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1048]
Se requiere terminar con el funcionamiento relacionado al funcionamiento base correcto de la arquitectura orientada a microfrontends y microservicios.

**Especificaciones técnicas**

1. Se realiza el ajuste de estilos de todos los MF en la issue #1031 .
2. Algunos de los MF no se encuentran funcionales dados diferentes bugs en la migración de los mismos o en los servicios que consumen de las APIs.
3. Todos los clientes debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevos Clientes definidos por la OATI bajo la arquitectura de micro frontends.
4. Todos los MF deben quedar optimizados en estilos y con pruebas funcionales en su totalidad.
6. El MF debe consumir los endpoints asociados a los MicroMids desarrollados para SISGPLAN, en lugar de planeacion_mid.

**Sub Tareas**

- [x] Revisar los endpoints del api de [evaluacion_mid](https://github.com/udistrital/planeacion_evaluacion_mid) dado que muchos de estos se encuentran rotos o no están acorde a como se encuentran en el mid de planeacion (planeacion_mid).
- [x] Corregir el comportamiento lógico de los endpoints para que su consumo desde el MF de [planeacion_evaluacion_mf](https://github.com/udistrital/planeacion_evaluacion_mid), sea correcto y su funcionalidad se pueda evidenciar visualmente.
- [x] Revisar el comportamiento del endpopint estructuraPlanes y adecuarlo en el api de formulacion_mid.
- [x] Ajustar la funcionalidad en el MF de pendientes relacionada con la consulta de datos a terceros con base en la identificación traida del endpoint userRole de autenticacion_mid.
- [x] Ajustar el tipo de respuesta en todos los MF, con base en: https://github.com/udistrital/sga_documentacion/issues/194
- [x] Optimización de código.

**Criterios de aceptación**

- [x] El MF se encuentra refactorizado.
- [x] El MF cuenta con todas sus componentes y funcionalidades migrados.
- [x] El código del MF se encuentra optimizado.
- [x] Los estilos del MF son los correspondientes a SISGPLAN.

**Requerimientos**

- [x] #936 .
- [x] #950 .

**Dependencias**

- planeacion_cliente
- planeacion_mid
- planeacion_reportes_mid
- planeacion_reportes_mf
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by C0C045** [comment]
# Múltiples Vinculaciones para el MicroFrontend de Pendientes
**Desarrollo asociado al siguiente commit:** [eda89e6](https://github.com/udistrital/planeacion_pendientes_mf/commit/eda89e6ddcd00e0c6e8413ab39199650f7953878)

Se implementó el soporte para las múltiples vinculaciones que pueden estar asignadas a un solo JEFE_DEPENDENCIA, tal que así:
![multiples](https://github.com/udistrital/planeacion_cliente/assets/55455142/64047330-0383-4dae-8b2c-eb053a450b06)

**Comment by C0C045** [comment]
# MicroFrontend Pendientes para el rol PLANEACION

**Desarrollo asociado al siguiente commit:** [1bf0e76](https://github.com/udistrital/planeacion_pendientes_mf/commit/1bf0e76bd7b9de160fa50cd42faf414e8902492a)

Se implementó la disponibilidad del microfrontend de pendientes para el rol 'PLANEACION', tal que así:

![rolplaneacion](https://github.com/udistrital/planeacion_cliente/assets/55455142/c34d31fc-0f9c-4d9a-aaa1-e736bcd74c80)

**Comment by C0C045** [comment]
# Micronfrontend de pendientes estilizado

**Desarrollo asociado al siguiente commit:** [d2793eb](https://github.com/udistrital/planeacion_pendientes_mf/commit/d2793ebb6480e50a9d170818367d3900533e5704)

Podemos observar que el microfrontend de pendientes queda estilizado a su totalidad, tal que así:

![stylePendientes](https://github.com/udistrital/planeacion_cliente/assets/55455142/b3ad4102-4940-40c2-be94-a415a22e8226)

**Comment by C0C045** [comment]
# Microfrontend de Pendientes con nueva respuesta

Cómo se podrá evidenciar a continuación el microfrontend de pendientes se encuentra ajustado según el nuevo tipo de respuesta por petición que se establece en https://github.com/udistrital/sga_documentacion/issues/194

**Pruebas Funcionales:**
![Pendientes](https://github.com/udistrital/planeacion_cliente/assets/55455142/21ae5c6d-4ae5-4859-9b38-58ea4fc55d0e)

**Comment by C0C045** [comment]
# Microfrontend de Formulación con nueva respuesta

Cómo se podrá evidenciar a continuación el microfrontend de seguimiento se encuentra ajustado según el nuevo tipo de respuesta por petición que se establece en https://github.com/udistrital/sga_documentacion/issues/194

**Pruebas Funcionales:**
![formulacion](https://github.com/udistrital/planeacion_cliente/assets/55455142/b6c7dc0a-852b-4fb4-b305-70cd603b3860)

**Comment by C0C045** [comment]
# Microfrontend de Macroplanes con nueva respuesta

Cómo se podrá evidenciar a continuación el microfrontend de macroplanes se encuentra ajustado según el nuevo tipo de respuesta por petición que se establece en https://github.com/udistrital/sga_documentacion/issues/194

**Pruebas Funcionales:**
![macroplanes](https://github.com/udistrital/planeacion_cliente/assets/55455142/9479127d-3e06-41b8-95bd-8be137133422)

**Comment by C0C045** [comment]
# PR's nueva respuesta de peticiones
pendientes-mf: https://github.com/udistrital/planeacion_pendientes_mf/pull/8
seguimiento-mf: https://github.com/udistrital/planeacion_seguimiento_mf/pull/9
formulacion-mf: https://github.com/udistrital/planeacion_formulacion_mf/pull/7
macroplanes-mf: https://github.com/udistrital/planeacion_macroplanes_mf/pull/5

**Comment by C0C045** [comment]
> @C0C045 por favor probar nuevamente el consumo de planeacion_formato_mid por autenticación, ya se tiene el permiso requerido.

El consumo de planeacion_formato_mid ya funciona correctamente, gracias.
