### ISSUE TITLE
Bug: Levantamiento de flujo de Evaluación en planes de acción.

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1049]
Se requiere corregir los bugs asociados al flujo de evaluación en planes de acción, de tal forma que el sistema permita visualizar la evaluación de los planes de acción que se encuentran avalados en seguimiento.

**Especificaciones Técnicas**

- Actualmente el flujo de evaluación se encuentra con fallas ya que no permite consultar los planes de acción que se encuentran avalados en fase de seguimiento:

![image](https://github.com/udistrital/planeacion_cliente/assets/36229498/1a2a4919-cdb1-4bf6-a864-f7ccdbc4ddc3)
![image](https://github.com/udistrital/planeacion_cliente/assets/36229498/e558de75-b7e7-4da4-b7bd-f49ebd32652d)

Segun lo observado, la consulta interna que se realiza desde el submódulo de evaluación a planeacion_mid no encuentra datos relacionados. Sin embargo, a continuación se muestra que si existen planes que cumplen con las condiciones requeridas:

![image](https://github.com/udistrital/planeacion_cliente/assets/36229498/6e97a1bc-8746-45f4-a5a2-87d32acfd142)

- Adicionalmente, posterior a la corrección del bug inicial, se debe garantizar que el módulo de evaluación responde correctamente en cada una de sus funcionalidades.

**Sub Tareas**

- [x] Corrección de bugs en submódulo de evaluación en planes de acción.
- [ ] Pruebas funcionales de todas las funcionalidades del submódulo de evaluación en planes de acción.

**Criterios de aceptación**

- [ ] El submódulo de evaluación en planes de acción se encuentra funcionando correctamente en cada uno de sus flujos permitidos.

**Requerimientos**

No aplica

**Dependencias**

- planeacion_mid.
- planes_crud.
- planeacion_cliente.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Oscarjaimes1710** [comment]
<img width="1462" alt="Captura de pantalla 2024-05-15 a la(s) 10 39 07 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/1efe0447-31d2-4dab-bb95-434dcae33f3e">

Esta roto el Ep, se ingresa a analizar la funcion : GetPlanesParaEvaluar

**Comment by Oscarjaimes1710** [comment]
En compañía, asesoramiento y análisis de @a52290451 Se logra encontrar el porque no estaba trayendo los planes que estaban con las condiciones idóneas para estar en evaluación. 

En ese orden de idea se hace analisis de el script de la consulta a la base de datos -->
<img width="1512" alt="Captura de pantalla 2024-05-17 a la(s) 4 42 45 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/d065a0ce-a5b1-4373-85f4-69f1072fe620">

Se hacen las consultas por intranet a planes_crud 
<img width="1512" alt="Captura de pantalla 2024-05-17 a la(s) 4 43 24 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/1eb77040-37f3-456f-a207-bed6579efaae">

Las consultas estan generandose bien entonces se procede a investigar que esta guardando en las variables si las consultas estan bien ejecutadas se hacen unos ftm en consola, devuelve la data correctamente la consulta pero al imprimir planes que es la variable donde lo almacena no trae nada-->
<img width="1512" alt="Captura de pantalla 2024-05-17 a la(s) 4 45 23 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/8265f130-bc5e-4dd9-a9c2-16e0ca5b4cc5">
<img width="766" alt="Captura de pantalla 2024-05-17 a la(s) 4 45 43 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/ba932660-7e70-4ccd-b20f-73bc52ee8e9e">


A continuación se procede entonces a revisar los id de los planes que esta haciendo que se rompa la consulta 

Se encuentra que hay planes que no tienen data y es lo que esta generando que se rompa 
<img width="766" alt="Captura de pantalla 2024-05-17 a la(s) 4 48 20 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/52ef0576-4a94-4e48-9aed-a34cf5a6c88a">

Se identifican se procede a hacer su delete-->
<img width="1436" alt="Captura de pantalla 2024-05-17 a la(s) 4 49 06 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/c2a78175-673c-4220-a478-60d2d7c2b757">

Se encuentra entonces que a la consulta de seguimiento se le debe agregar una variable que verifique el estado de los planes como activo:true asi como la imagen.

<img width="1018" alt="Captura de pantalla 2024-05-17 a la(s) 4 50 25 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/8a6c91e2-fe31-459e-b150-d7683a4dacad">

y se hace nuevamente la consulta completa -->
<img width="758" alt="Captura de pantalla 2024-05-17 a la(s) 4 50 59 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/65805179-c114-4c79-bf18-f44eb8acca61">

ya aparecen los planes se procede a ejecutarlo en el cliente en local para verificar.

**Comment by Oscarjaimes1710** [comment]
Ya esta trayendo los planes con un pequeño ajuste de una letra en data.Data es data.data
<img width="1512" alt="Captura de pantalla 2024-05-17 a la(s) 5 45 28 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/9920534d-8af8-4367-952c-9e365c533653">

<img width="1512" alt="Captura de pantalla 2024-05-17 a la(s) 5 45 34 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/2b8942f1-fc68-443a-bd2c-085e7ddbbcc1">

Pero ahora se queda cargando para traer la unidad. 

Se procede a investigar por que.

**Comment by Oscarjaimes1710** [comment]
<img width="1509" alt="Captura de pantalla 2024-05-20 a la(s) 12 22 42 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/b8e28c91-b08e-4f55-901b-e87de2226b64">

Seleccionando el trimestre ya funciona el flujo correctamente, pero en todas las unidades aun no , se esta investigando la razón. 
<img width="1509" alt="Captura de pantalla 2024-05-20 a la(s) 12 25 46 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/f4c5ddba-79c0-48dd-a9c2-b37f3105085f">

**Comment by Oscarjaimes1710** [comment]
Flujo completo 
<img width="1509" alt="Captura de pantalla 2024-05-20 a la(s) 3 58 37 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/d9a2dcf1-bbd6-4dc0-a573-148a22fa7ca8">
<img width="1509" alt="Captura de pantalla 2024-05-20 a la(s) 3 58 39 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/34c62ba7-5b93-4c82-8e8c-9d0b0542cc48">

**Comment by a52290451** [comment]
Faltan las siguientes acciones:

1. Completar solución de Bugs de acuerdo a lo mencionado en Review.
2. Completar pruebas funcionales.
3. PR a develop de planeacion_mid.
4. PR a develop de planeacion_cliente.

**Comment by Oscarjaimes1710** [comment]
1. Se completa la solución de bugs de acuerdo a lo mencionado en review, se hace ajuste de consulta y esta completamente funcional 
<img width="1512" alt="Captura de pantalla 2024-05-21 a la(s) 6 32 11 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/87699ac3-90a3-48e1-bd9c-6efab3d7d02b">
<img width="1509" alt="Captura de pantalla 2024-05-21 a la(s) 6 49 35 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/18d1e346-f2de-4675-b39e-7fbf1369062d">
<img width="1509" alt="Captura de pantalla 2024-05-21 a la(s) 6 49 37 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/c23e6882-e5b2-471e-aed3-53fe402673ba">
<img width="1512" alt="Captura de pantalla 2024-05-21 a la(s) 6 55 52 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/c153ee50-c29d-4378-b282-628978e3f636">
<img width="1509" alt="Captura de pantalla 2024-05-21 a la(s) 6 56 02 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/f7154959-3c23-4eba-af82-23c8b71bb94e">
<img width="1509" alt="Captura de pantalla 2024-05-21 a la(s) 6 56 06 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/ceaa8113-0a72-4804-9c01-ace0527bb388">
<img width="1509" alt="Captura de pantalla 2024-05-21 a la(s) 7 02 09 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/9ae643bc-6ef2-4d7d-89d8-36988b62232d">
<img width="1509" alt="Captura de pantalla 2024-05-21 a la(s) 7 02 40 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/d6de35d0-78f5-4620-89b0-ec0750a12cf6">
<img width="1509" alt="Captura de pantalla 2024-05-21 a la(s) 7 03 00 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/b37c6857-43d6-45eb-91a9-6a42ce37e147">
<img width="1509" alt="Captura de pantalla 2024-05-21 a la(s) 7 03 06 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/8128a2e1-acd2-4e7d-bdeb-2efe8bf15288">

Se corrigen todos los fallos del bug para el flujo de evaluación. 

Se procede a hacer los commits correspondientes.

**Comment by Oscarjaimes1710** [comment]
Video del flujo completo

https://udistritaleduco-my.sharepoint.com/:v:/g/personal/computo_udistrital_edu_co/ERTLHCG4dyZEjwMLY66HQgMBsVd2BKXQKfFVrUyBBR0-Ag?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=KJ2SUg

**Comment by a52290451** [comment]
Completar solucion de fallos y subir video con el funcionamiento correcto en evaluación.

**Comment by Oscarjaimes1710** [comment]
<img width="1505" alt="Captura de pantalla 2024-05-31 a la(s) 8 20 19 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/b359cab6-7134-4437-8db7-edbc80b7d0f9">
<img width="1505" alt="Captura de pantalla 2024-05-31 a la(s) 8 20 24 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/c4be92e1-75c6-41e2-bf08-418c0274f895">
