### ISSUE TITLE
Revisión de construcción (Popup's, eliminar planes, reestructurarlos)

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1055]
Se requiere verificar cuales son las condiciones estructurales para que un plan de acción pueda formularse y realizar su respectivo seguimiento.

**Especificaciones técnicas**

1. El cliente y el mid se encuentran actualizados en pruebas (release/0.0.1)
2. Actualmente existen algunos planes que no cuentan con la estructura requerida para pasar a ser avalados.
3. La construcción de las plantillas de los planes de acción no muestran alguna advertencia sobre que ítems obligatorios faltantes tiene el plan de acción antes de almacenarlo.

**Subtareas**

- [x] Identificar las condiciones para que una estructura de un plan cumpla con las condiciones necesarias para ser formulado, aprobado y apto para hacerle seguimiento.
- [x] Al identificar las condiciones, se debe advertir gráficamente al usuario en la construcción de plantillas sobre que elementos son obligatorios y no permitir el almacenamiento de los planes hasta que no se cumpla con los requisitos básicos.
- [x] En un Popup señalar puntualmente cuales son los ítems faltantes.
- [x] Probar el funcionamiento correcto de las restricciones de almacenamiento.
- [x] Eliminar aquellos planes que tengan asociada una estructura que no cumpla con los requisitos o condiciones necesarias para formular, aprobar y hacer seguimiento.

**Criterios de aceptación**

- [x] Se documenta el issue correctamente con los avances realizados de manera progresiva.
- [x] Se controla el almacenamiento de planes incompletos y se generan las advertencias sobre cuales son los ítems faltantes por ajustar previo a su persistencia.
- [x] Se realizan las pruebas funcionales sobre el almacenamiento de planes en su contrucción.
- [x] Se eliminan aquellis planes que no cuentan con la estructura necesaria.

**Requerimientos**

- [x] Refactor de todos los mf 

**Dependencias**

- Todos los MF de SISGPLAN.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
Se ha realizado la creación desde 0 de un plan nuevo, en donde se ha realizado la identificación de que condiciones son necesarias, para la generación de plantillas y planes, teniendo en cuenta que actualmente se ha llegado hasta el proceso de formulación:

![Image](https://github.com/udistrital/planeacion_cliente/assets/73924638/0d8c3e56-e767-421a-93fe-3ea6ffb71f73)

Se ha podido apreciar que este error, con respecto a la generación de planes, pudo haber sido provocado por la eliminación de los planes, esto en vista que las plantillas se guardan en la tabla plan, por lo cual puede que muchos de los planes hayan quedado con errores debido a esta acción.

##NOTA##

A continuación, se presentan los campos y las notas recopiladas en el proceso de generación del plan de la imagen de arriba:

[Parametros para crear un plan.xlsx](https://github.com/udistrital/planeacion_cliente/files/15397681/Parametros.para.crear.un.plan.xlsx)

**Comment by Mechaz123** [comment]
Dentro de las restricciones encontradas, se identifica que el botón solo será habilitado una vez que todos los campos estén seleccionados o con la información necesaria, de manera que no quedarán campos nulos.

![Image](https://github.com/udistrital/planeacion_cliente/assets/73924638/8858340f-bff6-4054-8dac-c3a5475b9bcf)

Por otra parte, la única restricción a tener en consideración es la de la selección de plantillas, ya que, al darle no, el plan no aparecerá en el listado de planes.

![Image](https://github.com/udistrital/planeacion_cliente/assets/73924638/af410b02-dc23-4c03-8111-6080bbbc3326)

**Comment by Mechaz123** [comment]
Se presentaron inconvenientes al momento de formular el plan, por el tema que la plantilla creada no coincidía con el "plan de desarrollo" seleccionado y tampoco con el "Plan indicativo", se tuvo que modificar el plan varias veces para que coincidiera con estos dos planes, pero se pudo enviar el plan para la revisión.

![Image](https://github.com/udistrital/planeacion_cliente/assets/73924638/042424ca-9948-42b5-ac1f-0221633b7014)

**Comment by Mechaz123** [comment]
Una vez el plan ha sido avalado, se puede comenzar con el proceso de seguimiento al plan, como se puede apreciar en la imagen:

![Image](https://github.com/udistrital/planeacion_cliente/assets/73924638/e032787f-390d-45c9-b110-21312d544e92)

**Comment by Mechaz123** [comment]
- Realizando la revisión del sistema, al momento de modificar la plantilla por "pruebasplaneacion" e inactivar un nivel, este cambio no se está viendo reflejado en al momento de realizar la formulación, como se puede apreciar en la imagen:

![Image](https://github.com/udistrital/planeacion_cliente/assets/73924638/2c2dc369-9be7-42ad-bf38-adabfe2acd02)

- Por otra parte, se modificó el mensaje original del sistema, ya que muchas veces, cuando falla por la estructura, no se tiene un if en esos casos o algo que active un panic, de manera que se evaluó que la mayoría de errores que puede presentar en este apartado es por la estructura del formato del plan:

- Dentro de las validaciones implementadas, se notifica cuando el texto de algún nivel no tiene las palabras "Ponderación" y "Actividad", ya que este es un requisito dentro del Mid:

![Image](https://github.com/udistrital/planeacion_cliente/assets/73924638/14717231-9cf7-4d5f-bf00-089388f0f9ae)

**Comment by Mechaz123** [comment]
Teniendo en cuenta que muchos de los planes con plantillas, dependen de la estructura que se defina, no se consideraría que un plan sea funcional o no, ya que esto es muy relativo, si se cambió ciertos elementos dentro del código, como el hecho de permitir modificar la plantilla de planes inactivos, también manejos de alertas, dando así un mejor manejo a todo este tema de las plantillas en los planes.

**Comment by Mechaz123** [comment]
Pull Request relacionado a planeacion_mid: https://github.com/udistrital/planeacion_mid/pull/534
Pull Request relacionado a planeacion_cliente: https://github.com/udistrital/planeacion_cliente/pull/1105

**Comment by Mechaz123** [comment]
> > Revisar este pr: https://github.com/udistrital/planeacion_mid/pull/527/files/d58212eaa4e0a7f237cae0d52561ac0e3f946288..1a5338cf73aa7d969cefe7cb2b054f03c843ea49, al igual revisar el nombramiento de los commit y pr.
> 
> POr favor revisar estrategia para estabilizar develop con los cambios.

Este es un PR que poseía un cambio relacionado a un hotfix en donde se realizaba la eliminación en un filtro mediante los cargos, el cargo que se había quitado era el cargo 414, pero en vista de que esto en su momento fue un Hotfix, no se requería la sincronización con la rama develop o demás ramas, ya que este cambio solo se encuentra en Master aplicado.
