### ISSUE TITLE
Nuevas funcionalidades en nueva arquitectura

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1060]
Se requiere realizar el paso de los desarrollos y ajustes realizados en el monolito, en la nueva arquitectura, de forma tal que los se evidencie e comportamiento actual del sistema en los microfrontends y miromids.

**Especificaciones técnicas**

- Los repositorios de los MF son: 

1. [Root](https://github.com/udistrital/planeacion_root_mf)
2. [Utilidades](https://github.com/udistrital/planeacion_utilidades_mf)(Revisar como mostrar la imagen base de SISGPLAN).
3. [Formulacion](https://github.com/udistrital/planeacion_formulacion_mf) 
4. [Seguimiento](https://github.com/udistrital/planeacion_seguimiento_mf)5. [Evaluacion](https://github.com/udistrital/planeacion_evaluacion_mf)
6. [Macroplanes](https://github.com/udistrital/planeacion_macroplanes_mf)
7. [Pendientes](https://github.com/udistrital/planeacion_macroplanes_mf)
8. [Construccion](https://github.com/udistrital/planeacion_macroplanes_mf)

- Los repositorios de los mid son:

1. [planeacion_formulacion_mid](https://github.com/udistrital/planeacion_formulacion_mid)
2. [planeacion_seguimiento_mid](https://github.com/udistrital/planeacion_seguimiento_mid)
3. [planeacion_evaluacion_mid](https://github.com/udistrital/planeacion_evaluacion_mid)
4. [planeacion_reportes_mid](https://github.com/udistrital/planeacion_reportes_mid)
5. [planeacion_arbol_mid](https://github.com/udistrital/planeacion_arbol_mid)
6. [planeacion_formato_mid](https://github.com/udistrital/planeacion_formato_mid)

- Los desarrollos ajustados corresponden a los encontrados en: #997 , #988 , #983 , #1004 , #1016 , #1023 , #1017 , #1015 .

**Sub Tareas**

- [x] Identificar los ajustes a realizar.
- [x] Una vez identificados los ajustes a realizar, definir en que micromid y microftontend se va a aplicar cada uno de los cambios.
- [x] Realizar los ajustes en cada uno de los microfrontends y micromids definidos.
- [x] Realización de pruebas funcionales.

**Criterios de aceptación**

- [x] Los microfrontends y micromids se encuentran actualizados con las funcionalidades requeridas.
- [x] Se realizan las respectivas pruebas funcionales.

**Requerimientos**

- [x] Completar Issues #997 , #988 , #983 , #1004 , #1016 , #1023 , #1017 , #1015 .

**Dependencias**

- micromids de planeación.
- microfrontends de planeación.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by ccmendezt** [comment]
## Evidencias - Avance Nuevas funcionalidades en nueva arquitectura
### 22/05/2024 - 9:30 am

### Bug - Corrección de limpieza módulo de consulta

- Se agregó una validación adicional a planeacion_seguimiento_mf en la que si la respuesta obtenida al buscar un trimestre es vacía, arroja error. Anteriormente estaba de la siguiente manera:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/28e6878f-dbde-4fc8-95e7-c2bc4eb482a5)
Ahora se muestra así:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/cc57f915-12c4-433a-9005-bcb04c58f0d7)
Y eso hacía que si se pudiera elegir la Vigencia 2021 que no tiene trimestres asociados a dicha vigencia, ahora muestra el siguiente mensaje:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/6b4df749-58c6-45a9-b89b-1199eb1e05c2)

- Se complementó la funcionalidad asociada a **Bug - Corrección de limpieza módulo de consulta** en planeacion_construccion_mf: 
[bug-limpieza-modulo-consulta-mf.zip](https://github.com/udistrital/planeacion_cliente/files/15404403/bug-limpieza-modulo-consulta-mf.zip)

## Commits/Pull Request asociados a Issue
- **planeacion_seguimiento_mid:** https://github.com/udistrital/planeacion_seguimiento_mid/commit/5286a7a0c24359876e5ac419450948f2566f9f2d
- **planeacion_construccion_mf:** https://github.com/udistrital/planeacion_construccion_mf/commit/f4ab0c848e88d8fce1e811040d12134958d33f9f

**Comment by ccmendezt** [comment]
## Evidencias - Avance Nuevas funcionalidades en nueva arquitectura
### 23/05/2024 - 15:40

### Bug - Fallo en lectura de fechas habilitadas en seguimiento

- Fechas sin actualizar para un plan:
![fechas-antiguas](https://github.com/udistrital/planeacion_cliente/assets/82072560/7674d2b8-b04c-47c5-9a97-662e196a06ba)

- Actualización de fechas:
![actualizacion-fechas](https://github.com/udistrital/planeacion_cliente/assets/82072560/530311c3-34c7-49da-b57b-c97bbef49669)

- Visualización de fechas actualizadas:
![visualizacion-fechas](https://github.com/udistrital/planeacion_cliente/assets/82072560/d48aaf9f-adc0-4832-aaaa-bcbaa668c501)

- Visualizacion de fechas actualizadas desde el rol **UNIDAD** visualizando la _correcta lectura de fechas_ por parte del sistema:
![visualizacion-fechas2](https://github.com/udistrital/planeacion_cliente/assets/82072560/60398b95-9121-4b48-b750-730dcd6bdbaf)


## Commits/Pull Request asociados a Issue
- **planeacion_construccion_mf:** https://github.com/udistrital/planeacion_construccion_mf/commit/b566e465ed01f4ad166dcfd8bacf80c5f61d311e
- **planeacion_seguimiento_mf:** https://github.com/udistrital/planeacion_seguimiento_mf/commit/831c360c8d14102444c1f87c64b3b292cb2d190b
- **planeacion_formulacion_mid:** https://github.com/udistrital/planeacion_formulacion_mid/commit/1d52328669d03ef5713197798d92915ec50c76c6

**Comment by ccmendezt** [comment]
## Evidencias - Avance Nuevas funcionalidades en nueva arquitectura
### 27/05/2024 - 17:00

### Estandarización de Roles en SISGPLAN PT1 y Cambio de cargo_id en vinculación al asignar un permiso

- Se agregó la funcionalidad de **Cambio de cargo_id en vinculación al asignar un permiso**:

- Vinculación de rol y cambio de **CargoId** a _Asistente de Dependencia_:
![vinculacion](https://github.com/udistrital/planeacion_cliente/assets/82072560/4c9035dd-5d8f-4485-a5a8-0f25f257b562)

- Desvinculación de rol y cambio de **CargoId** a _No Registra_:
![desvinculacion](https://github.com/udistrital/planeacion_cliente/assets/82072560/8c834869-4ff0-436e-8909-9939603192e8)

- La Estandarización de Roles en SISGPLAN PT1 no se ha podido probar en su totalidad ya que el usuario con rol ASISTENTE_DEPENDENCIA tiene un tercero diferente al usual, lo que hace que no tenga vinculaciones activas y muestre el siguiente mensaje:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/3f804816-6658-485b-9bec-ef28010d198c)

Se realiza esta petición: 
_https://autenticacion.portaloas.udistrital.edu.co/apioas/terceros_crud/v1/datos_identificacion/?query=Numero:79777053_ pero al número al que se hacía la petición antes era: 7230282
```json
[
    {
        "Id": 4259,
        "TipoDocumentoId": {
            "Id": 7,
            "Nombre": "NIT",
            "Descripcion": "NIT",
            "CodigoAbreviacion": "NIT",
            "Activo": true,
            "NumeroOrden": 0,
            "FechaCreacion": "2019-11-07 20:38:40.930714 +0000 +0000",
            "FechaModificacion": "2019-11-07 20:38:40.930714 +0000 +0000"
        },
        "TerceroId": {
            "Id": 13169,
            "NombreCompleto": "ALEJANDRO PAOLO DAZA CORREDOR",
            "PrimerNombre": "",
            "SegundoNombre": "",
            "PrimerApellido": "",
            "SegundoApellido": "",
            "LugarOrigen": 0,
            "FechaNacimiento": null,
            "Activo": true,
            "TipoContribuyenteId": {
                "Id": 2,
                "Nombre": "PERSONA JURIDICA",
                "Descripcion": "",
                "CodigoAbreviacion": "P_JURIDICA",
                "Activo": true,
                "FechaCreacion": "2019-11-25 20:39:54.421872 +0000 +0000",
                "FechaModificacion": "2019-11-25 20:39:54.421872 +0000 +0000"
            },
            "FechaCreacion": "2022-06-02 10:01:47.336 +0000 +0000",
            "FechaModificacion": "2022-06-02 10:01:47.336 +0000 +0000",
            "UsuarioWSO2": ""
        },
        "Numero": "79777053",
        "DigitoVerificacion": 0,
        "CiudadExpedicion": 0,
        "FechaExpedicion": null,
        "Activo": true,
        "DocumentoSoporte": 0,
        "FechaCreacion": "2022-06-02 10:08:24.735 +0000 +0000",
        "FechaModificacion": "2022-06-02 10:08:24.735 +0000 +0000"
    }
]
```
Y al revisar las vinculaciones asociadas a dicho tercero, se encuentra que no hay, por lo que se muestra el mensaje que el usuario no tiene permisos requeridos para acceder a dicho módulo.

## Commits/Pull Request asociados a Issue
- **planeacion_construccion_mf:** https://github.com/udistrital/planeacion_construccion_mf/commit/3a07a34c61fd487d782cd271c35e194bc6848011
- **planeacion_formulacion_mf:** https://github.com/udistrital/planeacion_formulacion_mf/commit/c95b4a09457cafed926fdc530acb6c4f9d9a40f9
- **planeacion_seguimiento_mf:** https://github.com/udistrital/planeacion_seguimiento_mf/commit/bc656f393a593845aef2c1945e538db241797285
- **planeacion_pendientes_mf:** https://github.com/udistrital/planeacion_pendientes_mf/commit/6f686a62e3548ee7120a42039a4cfd666db2f323
- **planeacion_formulacion_mid:** https://github.com/udistrital/planeacion_formulacion_mid/commit/7391c6bcc16faa66f7c84aabf3a9258dfd914c70

## Notas importantes:
  **i.** Se continua el desarrollo en #1066 
  **ii.** En la parte dos de esta issue se realizarán las pruebas funcionales del flujo de _formulación_ y _seguimiento_ cuando el usuario con rol **ASISTENTE_DEPENDENCIA** no tenga problemas con su tercero y vinculaciones asociadas al mismo.

**Comment by ccmendezt** [comment]
## Pull Request Asociados a Issue
### 28/05/2024 - 7:00 am

- **planeacion_construccion_mf:** https://github.com/udistrital/planeacion_construccion_mf/pull/5
- **planeacion_formulacion_mf:** https://github.com/udistrital/planeacion_formulacion_mf/pull/12
- **planeacion_seguimiento_mf:** https://github.com/udistrital/planeacion_seguimiento_mf/pull/12
- **planeacion_pendientes_mf:** https://github.com/udistrital/planeacion_pendientes_mf/pull/11
- **planeacion_formulacion_mid:** https://github.com/udistrital/planeacion_formulacion_mid/pull/8
- **planeacion_seguimiento_mid:** https://github.com/udistrital/planeacion_seguimiento_mid/pull/12
