### ISSUE TITLE
Modulo para agrupar componentes funcionales y cookies PT2

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1061]
Se requiere terminar de implentar el módulo lógico (utility) en single SPA que agrupe las funcionalidades compartidas en diferentes micro frontends.

**Especificaciones técnicas**

1. Los microfrontend's de [root](https://github.com/udistrital/planeacion_root_mf), [utilidades ](https://github.com/udistrital/planeacion_utilidades_mf), se encuentran desplegados en entorno de pruebas.
2. Los estilos particulares para SISGPLAN (generales) quedaron en el root.
3. Cada uno de los mf maneja sus propios estilos.

**Subtareas**

- [x] Continuar con la agrupación de componente identificados en el componente de tipo módulo (utility).
- [x] En cada uno de los MF dónde se dejó de utilizar la funcionalidad desde ellos mismos, deben cambiarse su consumo al utilizar el módulo creado.
- [x] Probar el funcionamiento correcto de las funcionalidades pasadas al módulo.

**Criterios de aceptación**

- [x] Se documenta el issue correctamente con los avances realizados de manera progresiva.
- [x] Se agrupan de manera correcta los componente lógicos compartidos en diferentes MF en un módulo de single SPA.
- [x] Se realizan las pruebas funcionales necesarias para garantizar el correcto cambio de consumo de lógica.

**Requerimientos**

- [x] Refactor de todos los mf 

**Dependencias**

- Todos los MF de SISGPLAN.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by C0C045** [comment]
# Componentes Angular en Módulo de Utilidades

Como se mencionó en https://github.com/udistrital/planeacion_cliente/issues/1040#issuecomment-2121501971; single-spa no soporta aún módulos de utilidades para el framework de Angular, por ende, se propuso intentar manejar solo la parte lógica del componente 'árbol' en el módulo de utilidades, sin embargo, esto resulta inconveniente, ya que el mismo typescript del componente usa tipado y funciones de Angular, por ende, solo sería posible pasar cierta cantidad de lógica y el componente quedaría dividido entre su microfrontend y el módulo de utilidades; lo cuál no sería para nada practico. Así que se descarta la idea de intentar externalizar componentes de angular.

Por otro lado, se reestructuró el módulo de utilidades; se agregaron clases para manejar cada uno de los servicios y luego se exporta cada una de ella, tal que así:

**Estructura:**
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/605740c0-dd02-4ec0-815d-c0b295858ade)

**Nuevo Main:**
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/83ab75b0-9248-44de-bc80-a215abe54e50)

Dado lo anterior, es cuestión de ir agregando cada servicio e importarlo en el 'main' del módulo de utilidades.

**Comment by C0C045** [comment]
# Formulacion_mf consume ahora el módulo de utilidades
**Cambios realizados en el siguiente commit:** [889b2b7](https://github.com/udistrital/planeacion_formulacion_mf/commit/889b2b73dd2fba348151050dd6025d72c2069037)

El microfrontend de formulación se ajustó para consumir el nuevo módulo de utilidades el cuál contiene los servicios de 'ImplicitAutenticationService' y 'ServiceCookies' los cuales son usados por el microfrontend.

Una vez implementados estos servicios de forma efectiva, se procedió a eliminar los anterior servicios y modelos antes usados por el microfrontend de manera interna.

Estos archivos eliminados son:
- Modelo usuarios.ts usado por el servicio 'ImplicitAutenticationService'.
- Servicio ImplicitAutenticationService.
- Servicio verificarFormulario encargado de las cookies.

**Pruebas Funcionales:**
![formulacionUtilidades](https://github.com/udistrital/planeacion_cliente/assets/55455142/a4e7a6bc-385b-4c25-a3b5-a7fb40bf6d2c)

**Comment by C0C045** [comment]
# Seguimiento_mf consume ahora el módulo de utilidades
**Cambios realizados en el siguiente commit:** [edab64b](https://github.com/udistrital/planeacion_seguimiento_mf/commit/edab64b4027059a1fd8a96427049b4387583fd68)

El microfrontend de seguimiento se ajustó para consumir el nuevo módulo de utilidades el cuál contiene los servicios de 'ImplicitAutenticationService' y 'ServiceCookies' los cuales son usados por el microfrontend. Además los métodos `getUrlFile` y `fileToBase64` del servicio 'GestorDocumental' fueron trasladados al nuevo módulo de utilidades.

Una vez implementados estos servicios de forma efectiva, se procedió a eliminar los anteriores servicios antes usados por el microfrontend de manera interna.

Estos archivos eliminados son:
- Servicio ImplicitAutenticationService.
- Servicio verificarFormulario encargado de las cookies.

**Pruebas Funcionales:**
![seguimiento](https://github.com/udistrital/planeacion_cliente/assets/55455142/4ef8c97b-ffe0-48f8-b904-8dbc7d8457ad)

**Comment by C0C045** [comment]
# Pendientes_mf consume ahora el módulo de utilidades
**Cambios realizados en el siguiente commit:** [99160aa](https://github.com/udistrital/planeacion_pendientes_mf/commit/99160aa75f19d716bc95c2f774831b7f91935905)

El microfrontend de pendientes se ajustó para consumir el nuevo módulo de utilidades el cuál contiene los servicios de 'ImplicitAutenticationService' y 'ServiceCookies' los cuales son usados por el microfrontend.

Una vez implementados estos servicios de forma efectiva, se procedió a eliminar los anterior servicios y modelos antes usados por el microfrontend de manera interna.

Estos archivos eliminados son:
- Modelo usuarios.ts usado por el servicio 'ImplicitAutenticationService'.
- Servicio ImplicitAutenticationService.
- Servicio verificarFormulario encargado de las cookies.

**Pruebas Funcionales:**
![pendientes](https://github.com/udistrital/planeacion_cliente/assets/55455142/b5c26f4e-845c-4ba7-aed3-59f0293e9fae)

**Comment by C0C045** [comment]
# Evaluación_mf consume ahora el módulo de utilidades
**Cambios realizados en el siguiente commit:** [ba3c51f](https://github.com/udistrital/planeacion_evaluacion_mf/commit/ba3c51fab6f0978c5b76b72cc39b6ebebf73f440)

El microfrontend de evaluación se ajustó para consumir el nuevo módulo de utilidades el cuál contiene el servicio de 'ImplicitAutenticationService' el cual esta siendo usado por el microfrontend.

Una vez implementado este servicio de forma efectiva, se procedió a eliminar los anterior servicios y modelos antes usados por el microfrontend de manera interna.

Estos archivos eliminados son:
- Servicio ImplicitAutenticationService.
- Variable de entorno TOKEN usada por el servicio de 'ImplicitAutenticationService'

**Pruebas Funcionales:**
![evaluacion](https://github.com/udistrital/planeacion_cliente/assets/55455142/58b9f766-dc97-430c-bf4e-4929624d10ee)

**Comment by C0C045** [comment]
# Construcción_mf consume ahora el módulo de utilidades
**Cambios realizados en el siguiente commit:** [4b115b2](https://github.com/udistrital/planeacion_construccion_mf/commit/4b115b272db3adc87a7c12bf4fa5f89828cbb71c)

El microfrontend de construcción se ajustó para consumir el nuevo módulo de utilidades el cuál contiene los servicios de 'ImplicitAutenticationService' y 'ServiceCookies' los cuales son usados por el microfrontend.

Una vez implementados estos servicios de forma efectiva, se procedió a eliminar los anterior servicios y modelos antes usados por el microfrontend de manera interna.

Estos archivos eliminados son:
- Servicio ImplicitAutenticationService.
- Servicio verificarFormulario encargado de las cookies.
- Variable de entorno TOKEN usada por 'ImplicitAutenticationService'

**Pruebas Funcionales:**
![construccion](https://github.com/udistrital/planeacion_cliente/assets/55455142/152b5266-a5d3-4fbe-a006-deb6774d8017)

**Comment by C0C045** [comment]
# Macroplanes_mf consume ahora el módulo de utilidades
**Cambios realizados en el siguiente commit:** [2189c43](https://github.com/udistrital/planeacion_macroplanes_mf/commit/2189c43db089cf73bdd57451fa9f6cf1c75f8df2)

El microfrontend de Macroplanes se ajustó para consumir el nuevo módulo de utilidades el cuál contiene el servicio de 'ImplicitAutenticationService' el cual esta siendo usado por el microfrontend.

Una vez implementado este servicio de forma efectiva, se procedió a eliminar los anterior servicios y modelos antes usados por el microfrontend de manera interna.

Estos archivos eliminados son:
- Modelo usuarios.ts usado por el servicio 'ImplicitAutenticationService'.
- Servicio ImplicitAutenticationService.
- Variable de entorno TOKEN usada por 'ImplicitAutenticationService'

**Pruebas Funcionales:**
![macroplanes](https://github.com/udistrital/planeacion_cliente/assets/55455142/3d489ae2-307b-4d66-95e1-d39b4f17f4dd)

**Comment by C0C045** [comment]
# Limpieza y Solución de Bugs
### Solución de vista entre Pendientes y Formulación
Actualmente el sistema presenta un bug, en dónde, si deseamos visitar el detalle de un plan desde la tabla de pendientes de formulación; este se visualizará solo un par de segundos, tal que así:
![bugFormulacion](https://github.com/udistrital/planeacion_cliente/assets/55455142/4a47e6d3-71aa-4c04-a267-9ae44f578630)

Esto se debe a que la vista del plan se presenta antes de que culminen todas las peticiones del sistema y luego una vez finalizadas; los estados encargados de la visualización del componente cambian y ocultan el componente.
Por ende, el paso de cookies y su consulta fueron modificadas junto al método `onChangeV()`; el cuál se le agrego un argumento adicional que es un booleano el cuál se encarga de controlar si se esta haciendo la consulta desde el mismo componente de formulación o desde pendientes, entonces, de esta forma evitó la consulta del plan o no. Tal que así:
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/d50b10b9-9816-408c-a9f6-bed935a51b83)

**Prueba Funcional:**
![solutionBug](https://github.com/udistrital/planeacion_cliente/assets/55455142/77d343d8-b17b-4f51-a6b5-34e8d44c0a0a)

### Limpieza de imports y DataRequestMID
Cada uno de los microfrontend's tenían varios imports que no eran usados en ningún momento, por ende se eliminaron. Por otro lado, el tipo de dato creado a partir del anterior formato de cada uno de los micromid's fue eliminado (DataRequestMID).

**Comment by C0C045** [comment]
# PR's
root: 
root: 
root: 
root: 
root:
