### ISSUE TITLE
Investigación y documentación sobre go routines

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1062]
Se requiere investigar sobre las go rutines y realizar una ejemplificación correcta de estas en el Mid.

**Especificaciones técnicas**

1. El cliente y el mid se encuentran actualizados en pruebas (release/0.0.1)
2. Las rutinas de Go permiten a los desarrolladores realizar peticiones de manera paralela aprovechando los núcleos del procesador, reduciendo así los tiempos de respuesta sobre una lógica ejecutada.
3. Las rutinas de Go deben desarrollarse y verificarse dado que pueden ejecutarse de manera errónea.

**Subtareas**

- [x] Investigar acerca de las rutinas de Go y generar en lineamientos un archivo .md en el [apartado de creación de apis](https://github.com/udistrital/lineamientos_oas/tree/master/generacion_de_apis) que contenga: definición de las rutinas de go, cómo utilizarlas, en que ocaciones y aspectos a tener en cuenta (inicio, definición de trabajos (hilos) y cierre correcto).
- [x] Generar de manera correcta rutinas en una petición del mid, realizar 10 veces pruebas de peticiones al endpoint implementado con rutinas y evidenciar su resultado satisfactorio, 

**Criterios de aceptación**

- [x] Se documenta el issue correctamente con los avances realizados de manera progresiva.
- [x] Se genera en lineamientos la documentación de las rutinas de Go.
- [ ] El ejemplo realizado con las rutinas funciona correctamente.

**Requerimientos**

- [x] Refactor de todos los mf 

**Dependencias**

- Todos los MF de SISGPLAN.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by C0C045** [comment]
# PR
Se generó la respectiva documentación en [lineamientos_oas](https://github.com/udistrital/lineamientos_oas) en dónde se tomo como referencia lo visto en https://github.com/udistrital/sga_documentacion/issues/178

**Pull Request:** https://github.com/udistrital/lineamientos_oas/pull/54
