### ISSUE TITLE
Mostrar codificación de actividades al pasar a seguimiento

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1063]
Se requiere que todos los planes de acción cuando pasen al estado avalado (seguimiento), por cada actividad que estos tengan se muestre a su lado el id de estas.

**Especificaciones técnicas**

1. La HU asociada a esta issue es: https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7B257F0C12-B780-4AA8-A3A2-07459C7D99F0%7D&file=hu-%20codigo%20unico%20de%20actividades.xlsx&action=default&mobileredirect=true. De esta no se debe tener en cuenta aún los escenarios 2 y 3.
2. El cliente y el mid se encuentran actualizados en pruebas (release/0.0.1)
3. Actualmente existe un ERP contratado por la Universidad para llevar allí la parte contable y financiera de la institución, a través de este se gestionan todos los rubros, solicitud de necesidades, CRP y CDP.
4. Para poder relacionar los gastos relacionados con la institución y los planes de acción formulados por cada una de las unidades, se requiere mostrar a todos los usuarios un **id para cada actividad**, dado que cada necesidad solicitada a través del ERP se le relacione la actividad del plan de acción que corresponda.

**Subtareas**

- [ ] En el cliente cuando cargue cada una de las actividades en un plan de acción que se encuentre dentro del flujo de seguimiento debe mostrar su respectivo ID.
- En esta tabla se debe cambiar el título de la columna 1 a "#" y agregar una segunda columna con el nombre "ID" y en su contenido debe tener el **id de la actividad en BD**

![Image](https://github.com/udistrital/planeacion_cliente/assets/106636533/f1384aec-d2b7-44e3-a1df-c8141dec65b1)

- En esta tabla se debe cambiar el título de fila "Código" a "Número de actividad" y agregar una nueva fila con el el nombre "ID" y en su contenido debe tener el **id de la actividad en BD**

![Image](https://github.com/udistrital/planeacion_cliente/assets/106636533/e4b0b6aa-5418-47ff-89f6-749e6a576337)

- [ ] Realizar las pruebas funcionales respectivas en cada una de los menús que utilicen el consumo de planes en seguimiento como por ejemplo: pendientes, planes de acción->seguimiento.

**Criterios de aceptación**

- [ ] Se documenta el issue correctamente con los avances realizados de manera progresiva.
- [ ] Se muestra para cada una de las actividades de los planes de acción el respectivo ID cuando estos se encuentran en fase de seguimiento.
- [ ] Los cambios deben verse en la nueva arquitectura y en el monolito.

**Requerimientos**

- [x] Ninguna.

**Dependencias**

- Todos los MF de SISGPLAN.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Oscarjaimes1710** [comment]
![Captura de pantalla 2024-06-14 a la(s) 7 02 44 p  m](https://github.com/udistrital/planeacion_cliente/assets/145817817/3078008b-e8e1-4beb-aa1a-7d55188199ed)
![Captura de pantalla 2024-06-14 a la(s) 7 02 37 p  m](https://github.com/udistrital/planeacion_cliente/assets/145817817/d799421f-ded5-468c-8bd7-ca4f4d6895cd)

Como se evidencia se completo la issue pero se deja a consideración lo siguiente : 
Según lo hablado y acordado con @a52290451 Se deja la codificación y el index puesto que la actividad no tiene un id si no una posición por eso donde se supone solicitaban el id de la actividad quedo el código del plan con el que hace la consulta del trimestre y se le adiciona la posición de la actividad seleccionada.

**Comment by a52290451** [comment]
Se requiere ajuste en el ID de Actividad.

Estado actual "666cccf4252f5d94cdc174c9 - 1"
Estado esperado "666cccf4252f5d94cdc174c9-1"

**Comment by norbeydanilo** [comment]
Generar un identificador de plan más corto (por ejemplo de 4 o 5 carácteres) usando hash o la mejor estrategia que se pueda contemplar e implementar. Seguido el "-" y número de actividad.

**Comment by Oscarjaimes1710** [comment]
<img width="985" alt="Captura de pantalla 2024-06-20 a la(s) 11 34 36 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/ffcab91d-911b-4eb8-aa61-9f295d784d3b">
Aqui esta la prueba de que funciona correctamente la codificación. 

<img width="985" alt="Captura de pantalla 2024-06-20 a la(s) 11 35 34 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/54bef2ec-d271-4b22-bc56-5a34dc177aa6">


Pero Es importante recordar que si el planId original tiene más de 16 caracteres, la conversión a Base62 necesariamente generará un código más largo que 10 caracteres.

**Comment by Oscarjaimes1710** [comment]
Se hace el ajuste del Para que se consuma desde planeacion mid el id_actividad con el fin de que se pueda consumir en próximos desarrollos.
![Captura de pantalla 2024-06-21 a la(s) 5 45 32 p  m](https://github.com/udistrital/planeacion_cliente/assets/145817817/0e4825c4-f2bf-420e-b3bf-5a12fffadf36)

![Captura de pantalla 2024-06-21 a la(s) 5 45 28 p  m](https://github.com/udistrital/planeacion_cliente/assets/145817817/7b93fe89-7247-467b-a259-29b547cde30a)


![Captura de pantalla 2024-06-21 a la(s) 5 45 23 p  m](https://github.com/udistrital/planeacion_cliente/assets/145817817/f8a1a9dc-eb93-454f-837e-2ab9747686b0)

Se deja la evidencia del funcionamiento del encode y del decoded y la documentación debida comentada para su uso posterior.
