### ISSUE TITLE
Aplicación de Go routines en todos los Micromids

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1064]
A raíz de la investigación de las rutinas de GO, se requiere implementar en todas las funciones en dónde se puedan aplicar.

**Especificaciones técnicas**

- Los repositorios de los mid son:

1. [planeacion_formulacion_mid](https://github.com/udistrital/planeacion_formulacion_mid)
2. [planeacion_seguimiento_mid](https://github.com/udistrital/planeacion_seguimiento_mid)
3. [planeacion_evaluacion_mid](https://github.com/udistrital/planeacion_evaluacion_mid)
4. [planeacion_reportes_mid](https://github.com/udistrital/planeacion_reportes_mid)
5. [planeacion_arbol_mid](https://github.com/udistrital/planeacion_arbol_mid)
6. [planeacion_formato_mid](https://github.com/udistrital/planeacion_formato_mid)

- Las rutinas de Go permiten a los desarrolladores realizar peticiones de manera paralela aprovechando los núcleos del procesador, reduciendo así los tiempos de respuesta sobre una lógica ejecutada.
- Las rutinas de Go deben desarrollarse y verificarse dado que pueden ejecutarse de manera errónea.
- Se realizó una investigación e implementació inical en  #1062 .

**Subtareas**

- [x] Identificar cada uno de los servicios (services) y controladores, dónde se pueda emplear las rutinas de Go, tanto en los micromids como en el crud.
- [ ] En cada uno de los servicios y controladores  identificados aplicar las rutinas de Go. Se debe realizar un cuadro comparativo en tiempos de respuesta en cada uno de los servicios y controladores refactorizados.
- [ ] Se deben realizar pruebas funcionales sobre cada uno de los servicios o controladores modificados, evidenciándose en 10 iteraciones la respuesta correcta.

**Criterios de aceptación**

- [x] Se documenta el issue correctamente con los avances realizados de manera progresiva.
- [x] Se documentan los servicios y controladores a ser modificados.
- [x] Se evidencia el cuadro comparativo con tiempos de respuesta de los controladores y servicios modificados.
- [x] Se evidencian las pruebas funcionales por servicio o controlador cada una con 10 iteraciones.

**Requerimientos**

- [x] Refactor de todos los mf 

**Dependencias**

- Todos los MF de SISGPLAN.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by C0C045** [comment]
# Recorrido de Posibles Cambios
Principalmente se optó por primero identificar cada una de la peticiones tipo GET que se encuentran dentro de un ciclo 'for' en cada uno de los micromids, en donde se obtuvieron las siguientes lineas de código en dónde se encuentra una petición con esas características:

**SEGUIMIENTO = 24** 
 - Actividades => 70
 - Indicadores => 26
 - Periodos => 26
 - Reportes => 129, 202, 330, 550
 - Seguimiento => 443, 517, 534, 646, 662, 735, 738, 759, 873, 878, 887, 890, 932, 936, 943, 946
 - helpers/utilidades => 146
 
**FORMULACION = 47**
 - Formulacion => 126, 229, 263, 975, 1310
 - Inversion => 144, 191, 539, 572, 954, 987, 1071, 1104, 1168, 1201, 1364
 - helpers/formulacion => 93, 98, 167, 222, 232, 297, 365, 387, 452, 463, 535, 591, 596, 674, 740
 - helpers/inversion => 83, 139, 174, 223, 278, 288, 353, 420, 431, 495, 569, 579, 643, 665, 743, 748
 
**EVALUACION = 9**
 - Evaluacion => 62, 198, 225, 360, 435, 487, 820, 876, 963
 
**REPORTES = 17**
 - Reportes => 225, 231, 515, 968, 1060, 1362, 1404, 1607, 2017, 2037, 2141, 2148, 2177, 2606, 2611, 3020
 - helpers/reportes => 85
 
**ARBOL = 3**
 - Arbol => 72, 181, 213
 
**FORMATO = 3**
 - Formato => 74, 134, 142 

### TOTAL = 103 Posibles peticiones que pueden implementarse con GoRoutines

**Comment by C0C045** [comment]
# FORMATO_MID implementación de Go Routines
El micromid de Formato tenía 3 posibles peticiones en las cuales se podría aplicar Go Routines; en donde una se encontraba en el método de `ConstruirArbol()` y las otras dos en el método `ConsultarHijos()`. Dos métodos que se encuentran en `src/services/formato.go`.

En la única petición de `ContruirArbol()` se implementa con éxito las Go Routines, además, de obtener los datos ordenados:

**Original:**
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/abe69adb-16e2-40b9-9c2e-e9345fdd7ffe)

**Go Routines:**
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/31942727-0242-4d87-bfdf-ecda22150873)

Por otro lado, la dos peticiones de `ConsultarHijos()` lastimosamente no fueron posibles de ordenar, ya que esta función es recursiva y por tanto el ordenamiento es más que complejo. Además, al ser recursiva y con los datos ordenados aleatoriamente no es funcional, ya que asigna valores que no pertenecen al hijo correcto.

**Original:**
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/f4835198-b3f6-46a6-9229-88ba8aa300fb)

**Go Routines:**
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/c7162172-156c-4a4c-9e53-5a0406b51075)

**Comment by C0C045** [comment]
# ARBOL_MID implementación de Go Routines
Analizando más a fondo cada una de las peticiones mencionadas en https://github.com/udistrital/planeacion_cliente/issues/1064#issuecomment-2140751415, se tiene que la primera petición de la linea 72 hace parte de una función recursiva y cómo vimos con anterioridad en FORMATO_MID; aplicar Go Routines en este tipo de funciones altera el orden y hace complejo el ordenamiento del mismo.
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/09a0a376-417d-469b-955c-2720040c40a0)

Por otro lado, las peticiones de las lineas 181 y 213 tienen como limitación una petición PUT dentro de cada for y como se menciono en los [lineamientos](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/go_routines.md); este tipo de peticiones es mejor no aplicarles Go Routines, ya que son susceptibles a cambios delicados e inesperados en los datos, lo que puede provocar inconsistencias y problemas de concurrencia.

**Petición 181:**
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/4ffeb4bb-84bd-438c-b316-7a8577bc3698)

**Petición 213:**
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/5bde088b-77df-46e9-8ecf-ce86986833f0)

**Comment by C0C045** [comment]
# PR
formato_mid: https://github.com/udistrital/planeacion_formato_mid/pull/10
