### ISSUE TITLE
Reformulación de planes de acción PT1

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1065]
Se requiere implementar la primera parte para la reformulación de planes de acción una vez estos se encuentran en la fase de seguimiento.

**Especificaciones técnicas**

- Las HU que acompañan esta primera parte del desarrollo son: https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7B35B71E3E-8F62-4FE1-A27D-62D3C527BD47%7D&file=hu%20menu%20de%20acceso%20reformulacion%20(1).xlsx&action=default&mobileredirect=true
- Los mockups correspondientes a este issue son: 
1. https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/ETN2DmPjP_REiPxPJRI5uIIBED_YVPN4NeN6Ddf-Qz6Tgw?e=qgyNVa
2. https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EZT3UasU9C1Jjt4oxrAjmW0BqholdiIrNyzaQqdJAUVBsA?e=EiLvLd
3. https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EQQ3KsAtUtVCoRlVG1HwfRcBfexnDdZW7cgUMx7wouiolg?e=ovcNPi

- Los repositorios de los MF son: 

1. [Root](https://github.com/udistrital/planeacion_root_mf)
5. [Utilidades](https://github.com/udistrital/planeacion_utilidades_mf)(Revisar como mostrar la imagen base de SISGPLAN).
6. [Formulacion](https://github.com/udistrital/planeacion_formulacion_mf) 
7. [Seguimiento](https://github.com/udistrital/planeacion_seguimiento_mf)5. [Evaluacion](https://github.com/udistrital/planeacion_evaluacion_mf)
8. [Macroplanes](https://github.com/udistrital/planeacion_macroplanes_mf)
9. [Pendientes](https://github.com/udistrital/planeacion_macroplanes_mf)
10. [Construccion](https://github.com/udistrital/planeacion_macroplanes_mf)

- Los repositorios de los mid son:

1. [planeacion_formulacion_mid](https://github.com/udistrital/planeacion_formulacion_mid)
2. [planeacion_seguimiento_mid](https://github.com/udistrital/planeacion_seguimiento_mid)
3. [planeacion_evaluacion_mid](https://github.com/udistrital/planeacion_evaluacion_mid)
4. [planeacion_reportes_mid](https://github.com/udistrital/planeacion_reportes_mid)
6. [planeacion_arbol_mid](https://github.com/udistrital/planeacion_arbol_mid)
7. [planeacion_formato_mid](https://github.com/udistrital/planeacion_formato_mid)

- La reformulación a grandes rasgos debe cumplir con las siguientes condiciones:

1. Todo cambio a realizar debe estar debidamente sustentado y aprobado por la OAP
2. Los cambios realizados deben conservar la regla que las ponderaciones totales de indicadores sumen el 100% tanto a nivel general como particular.
3. Los cambios realizados a los recursos sean ops o recursos docentes no deben afectar el presupuesto asignado.
4. Al momento de realizar un cambio e implementarlo en el plan de acción se genera un punto de corte en donde: la parte correspondiente a lo ya medido (el pasado) se conserva igual, generando un cierre de esa parte del plan. Para la parte futura del plan, después del punto de corte, el plan se genera con una versión superior y una nota aclaratoria que indique la reformulación de alguno de sus componentes.
5. Se debe asegurar al momento de implementar los cambios; estos no involucren un mayor gasto del presupuesto asignado.
6. Si, al realizar los cambios en el plan se libera parte del presupuesto asignado, este movimiento debe ser informado a la OAP para su autorización y se debe conocer el nuevo destino de los recursos monetarios liberados.

**Sub Tareas**

- [x] Leer las HU y revisar los mockups para entender más el proceso requerido.
- [x] En el aplicativo de [configuración en entorno de pruebas](https://pruebasconfiguracion.portaloas.udistrital.edu.co/) adicionar en el menú de "Plan de Acción" el submenú "Solicitud de Reformulación" el cual debe quedar asociado a los cuatro roles de SISGPPLAN "ASISTENTE_DEPENDENCIA" y "JEFE_DEPENDENCIA".
- [x] Adicionar un componente visual en el MF de seguimiento relacionado a la reformulación y asociarlo al submenú "Solicitud de Reformulación".
- [x] El componente visual debe ofrecer las siguientes opciones de filtrado para encontrar un plan de acción en fase de seguimiento: "Unidad", "Vigencia", "Planes de acción", para esto se puede reutilizar la vista que se tiene en "Planes de acción->Planes de acción activos->Seguimiento", sin embargo se deben adicionar los filtros requeridos y se debe quitar el botón de descarga de excel. Finalmente, se debe cambiar el símbolo de la acción (uno que indique redirección) en cada uno de los registros de la tabla y la acción a la que debe estar asociado corresponde a la vista de solicitud formal de reformulación.
![image](https://github.com/udistrital/planeacion_cliente/assets/106636533/90ac1bb1-d01e-4c92-85cd-0f2b097bf506)
- [x] Crear un componente visual que este relacionado con la solicitud formal de reformulación de plan la cual mostrará información relacionada con el plan escogido por parte de la unidad: "Unidad,  estado del reporte", ID de plan de acción, vigencia, Nombre de plan de accción. Además, la vista tiene que contar con tres acciones:

1. Cargar archivo PDF con la solicitud formal de reformulación del plan de accción.
2. La visualización del archivo cargado.
3. Envío de la solicitud de reformulación.

Finalmente se debe habilitar un campo de observaciones limitado a 1000 caracteres con un contador que vaya indicando al usuario cuantos caracteres lleva diligenciado.

Deben quedar como campos obligatorios el cargue del archivo y las obsevaciones para enviar la solicitud.

- [x] Realización de pruebas funcionales.

**Criterios de aceptación**

- [x] Los relacionados a las HU.
- [x] Documentación del issue progresiva e informativa.
- [x] Se evidencia el menú, la asociación a la tabla de búsqueda, la redirección a la solicitud formal de un plan de acción con su cargue de documento y diligenciamiento de observaciones.
- [x] Se debe generar persistencia sobre los documentos, observaciones y planes con solicitud de reformulación.

**Requerimientos**

- [x] Ninguno.

**Dependencias**

- micromids de planeación.
- microfrontends de planeación.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by felimarod** [comment]
Al entrar a seguimiento en el modulo "Listar Plan de Acción" sale lo siguiente:
![Image](https://github.com/udistrital/planeacion_cliente/assets/85894335/8d432ec8-d4c3-48f3-a573-b2219b4a4c0a)

**Comment by felimarod** [comment]
Avance hasta el momento:

![Image](https://github.com/udistrital/planeacion_cliente/assets/85894335/3a2e2d38-f5a5-45d9-b2b1-0fc013b7ea20)


![Image](https://github.com/udistrital/planeacion_cliente/assets/85894335/bba398c3-1067-45c2-ac35-d5637f08192c)




Completado el [Hito 1 de la HU](https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7B35B71E3E-8F62-4FE1-A27D-62D3C527BD47%7D&file=hu%20menu%20de%20acceso%20reformulacion%20(1).xlsx&action=default&mobileredirect=true)

**Comment by felimarod** [comment]
Primer mockup finalizado en cuanto a diseño:
![image](https://github.com/udistrital/planeacion_cliente/assets/85894335/8ccb1375-fdad-4b9a-beaf-e0c125e13a3b)

**Comment by a52290451** [comment]
Para finalizar la actividad se requiere:

1. Realizar correcciones sugeridas en la revisión.
2. Video en el cual se evidencie el funcionamiento de la vista.
3. Commit con cambios realizados.

**Comment by felimarod** [comment]
- Se agregó la ruta en configuraciones
- Y se agregó el primer mockup con las respectivas verificaciones
[Avance.webm](https://github.com/udistrital/planeacion_cliente/assets/85894335/1cd9ed85-bb47-47e0-bf9a-ef3f287ecddf)
