### ISSUE TITLE
Nuevas funcionalidades en nueva arquitectura PT2

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1066]
Se requiere finalizar el paso de los desarrollos y ajustes realizados en el monolito, en la nueva arquitectura, de forma tal que los se evidencie e comportamiento actual del sistema en los microfrontends y miromids.

**Especificaciones técnicas**

- Los repositorios de los MF son: 

1. [Root](https://github.com/udistrital/planeacion_root_mf)
2. [Utilidades](https://github.com/udistrital/planeacion_utilidades_mf)(Revisar como mostrar la imagen base de SISGPLAN).
3. [Formulacion](https://github.com/udistrital/planeacion_formulacion_mf) 
4. [Seguimiento](https://github.com/udistrital/planeacion_seguimiento_mf)5. [Evaluacion](https://github.com/udistrital/planeacion_evaluacion_mf)
6. [Macroplanes](https://github.com/udistrital/planeacion_macroplanes_mf)
7. [Pendientes](https://github.com/udistrital/planeacion_macroplanes_mf)
8. [Construccion](https://github.com/udistrital/planeacion_macroplanes_mf)

- Los repositorios de los mid son:

1. [planeacion_formulacion_mid](https://github.com/udistrital/planeacion_formulacion_mid)
2. [planeacion_seguimiento_mid](https://github.com/udistrital/planeacion_seguimiento_mid)
3. [planeacion_evaluacion_mid](https://github.com/udistrital/planeacion_evaluacion_mid)
4. [planeacion_reportes_mid](https://github.com/udistrital/planeacion_reportes_mid)
5. [planeacion_arbol_mid](https://github.com/udistrital/planeacion_arbol_mid)
6. [planeacion_formato_mid](https://github.com/udistrital/planeacion_formato_mid)

- Los desarrollos ajustados corresponden a los encontrados en: #997 , #988 , #983 , #1004 , #1016 , #1023 , #1017 , #1015 .

**Sub Tareas**

- [x] Identificar los ajustes a realizar.
- [x] continuar con los ajustes pendientes a realizar, dediniendo en en que micromid y microftontend se va a aplicar cada uno de los cambios.
- [x] Realizar los ajustes en cada uno de los microfrontends y micromids definidos.
- [x] Realización de pruebas funcionales.

**Criterios de aceptación**

- [x] Los microfrontends y micromids se encuentran actualizados con las funcionalidades requeridas.
- [x] Se realizan las respectivas pruebas funcionales.

**Requerimientos**

- [x] Completar Issues #997 , #988 , #983 , #1004 , #1016 , #1023 , #1017 , #1015 .

**Dependencias**

- micromids de planeación.
- microfrontends de planeación.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by ccmendezt** [comment]
## Evidencias - Avance Nuevas funcionalidades en nueva arquitectura
### 31/05/2024 - 10:20

### Estandarización de Roles en SISGPLAN PT2

- Se ha migrado en un 95% la funcionalidad de estandarización de roles **SISGPLAN PT2**.
- Falta por migrar _plan-accion-seguimiento_ dentro de **planeacion_construccion_mf**.

## Commits asociados a Issue
- **planeacion_construccion_mf:** https://github.com/udistrital/planeacion_construccion_mf/commit/2a658790a9374551bc3696e787b7059f17e3c5f9
- **planeacion_formulacion_mf:** https://github.com/udistrital/planeacion_formulacion_mf/commit/1e9e26fef3aca640df61449fb7f704c6882309ca
- **planeacion_seguimiento_mf:** https://github.com/udistrital/planeacion_seguimiento_mf/commit/3db0605884aa81fbc27d5facba10ffb2878c06b8
- **planeacion_seguimiento_mid:** https://github.com/udistrital/planeacion_seguimiento_mid/commit/9b6ec6714d13ca075a2967453c00f0b4dc4aeb71

## Notas importantes:
  **i.** El flujo de formulación y seguimiento se migró en su totalidad y actualmente se están realizando pruebas de ambos flujos para realizar las correcciones necesarias.
  **ii.** Se espera documentar hoy mismo los avances de las pruebas funcionales para los flujos de formulación y seguimiento.
  **iii.** Una vez terminados los flujos de formulación y seguimiento y validar que funcionen como se espera, se continuará con la migración del componente _plan-accion-seguimiento_ dentro de **planeacion_construccion_mf**.

**Comment by ccmendezt** [comment]
## Evidencias - Nuevas funcionalidades en nueva arquitectura PT2
### 31/05/2024 - 16:22

## Estandarización de Roles en SISGPLAN

### Proceso de Formulación:

- **Estado A (En formulación)**: Ambos roles, tanto _ASISTENTE_DEPENDENCIA_ como _JEFE_DEPENDENCIA_ pueden formular un plan

     - **ASISTENTE_DEPENDENCIA**: Es el rol que normalmente formula el plan, añade, elimina, edita actividades y demás como lo indica el diagrama de flujo/acciones.
     
     ![crear_actividad_asistente](https://github.com/udistrital/planeacion_cliente/assets/82072560/7855d600-662d-4177-b0c0-f880a540f397)
     
     ![crear_actividad_asistente2](https://github.com/udistrital/planeacion_cliente/assets/82072560/9c63aae7-f993-4b77-bae1-f444b740c424)

     - **JEFE_DEPENDENCIA**: Aunque normalmente dentro del flujo establecido no lo hace, puede realizarlo.
     
     ![crear_actividad_jefe](https://github.com/udistrital/planeacion_cliente/assets/82072560/8d7f705c-d717-4abc-b850-e294b5549bad)


- **Estado B (Formulado)**: Ambos roles, tanto _ASISTENTE_DEPENDENCIA_ como _JEFE_DEPENDENCIA_ pueden consultar el plan y enviar plan a revision, normalmente lo realiza el ASISTENTE_DEPENDENCIA:

     - **ASISTENTE_DEPENDENCIA**: Es el rol que normalmente formula el plan, añade, elimina, edita actividades y demás como lo indica el diagrama de flujo/acciones.
     
     ![consultar_culminar_plan_asistente_dependencia](https://github.com/udistrital/planeacion_cliente/assets/82072560/a86e055f-12d6-4d52-8476-0d938d606e2f)
     
     - **JEFE_DEPENDENCIA**: Aunque normalmente dentro del flujo establecido no lo hace, puede realizarlo.
     
     ![consultar_culminar_plan_jefe_dependencia](https://github.com/udistrital/planeacion_cliente/assets/82072560/a196e8d4-a4bb-40d2-b643-35f9abc07753)

- **Estado C (En Revisión)**: Ambos roles, tanto _ASISTENTE_PLANEACION_ como _PLANEACION_ pueden consultar el plan, realizar la revisión del plan (observaciones), y enviarlo a estado REVISADO.

     - **ASISTENTE_PLANEACION**:
     
     - **Iniciar revisión**: 

     ![iniciar_revision_asistente_planeacion](https://github.com/udistrital/planeacion_cliente/assets/82072560/447b36bb-10b3-4864-bd54-2249da4efa94)

     - **Realizar observaciones**: 
     
     ![realizar_observacion_asistente_planeacion](https://github.com/udistrital/planeacion_cliente/assets/82072560/615b0306-23d7-43b9-94d8-95c75d94d29f)
     
     ![observacion_asistente_planeacion](https://github.com/udistrital/planeacion_cliente/assets/82072560/1f12767d-535e-42a5-8830-c9d10ab70a32)
     
     - **PLANEACION**:
     
     - **Realizar observaciones**: 
     
     ![realizar_observacion_planeacion](https://github.com/udistrital/planeacion_cliente/assets/82072560/e3410397-aa9e-47e3-b23c-514d5d2df817)
     
     ![observacion_planeacion](https://github.com/udistrital/planeacion_cliente/assets/82072560/a7fd5dcc-1e83-4d4b-a089-a6c05a46a060)
     
     - **Enviar revisión**: 
     
     - **ASISTENTE_PLANEACION**:
     
     ![enviar_revision_asistente_planeacion](https://github.com/udistrital/planeacion_cliente/assets/82072560/72dadc8a-472b-4871-8b0f-2a2d4fa32f8c)

     - **PLANEACION**:

     ![enviar_revision_planeacion](https://github.com/udistrital/planeacion_cliente/assets/82072560/559b4660-1fdf-408b-8606-e5bb8263e0a4)

- **Estado D y E (Revisado y Verificado)**: Solo el rol JEFE_DEPENDENCIA puede realizar: consulta del plan, revisar, devolver y aceptar el plan

     - **Opciones permitidas por el rol**: 

     ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/db336820-e175-448a-9a13-7bb9526b6152)
     
     - **Ajustar plan**: Se crea una nueva versión del plan y se reinicia el flujo pasando al estado A.
     
     ![ajustar-plan-jefe-dependencia](https://github.com/udistrital/planeacion_cliente/assets/82072560/29060ab9-ed21-4c1e-a21a-dca2f3617c59)

     - **Verificar plan**: Una vez realizados los ajustes se envía realiza los flujos por los estados B y C, para pasar nuevamente al D y realizar la verificación del plan:
     
     ![verificar_revision_jefe_dependencia](https://github.com/udistrital/planeacion_cliente/assets/82072560/03371329-8970-49d7-a9ac-faca3b6cdbc9)

- **Estado F (Pre avalado)**: Solo el rol PLANEACION puede pre-avalar el plan.

     - **ASISTENTE_PLANEACION**: El rol ASISTENTE_PLANECION no puede hacer pre avalar el plan como se muestra a continuacion:
     
     ![pre_avalar_plan_asistente_planeacion](https://github.com/udistrital/planeacion_cliente/assets/82072560/971dea83-5933-448e-a374-8cfdaba564bd)

     - **PLANEACION**:
     ![pre_avalar_plan_planeacion](https://github.com/udistrital/planeacion_cliente/assets/82072560/f120d68b-a4d5-49a7-b81b-ab82c8a84ea6)

**Nota estado F:** En este estado se permite remitir ajustes del plan de acción desde el rol PLANEACION, este botón llama a la misma función que utiliza para ajustar un plan desde el rol JEFE_DEPENDENCIA llamada realizarAjustes(), es decir, realiza una nueva versión de un plan y pasa de nuevo al estado A.

![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/0d1b998c-191b-4884-8936-5c10fb525653)


![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/c5498d23-b50b-4c60-b13e-2689377d9f49)

- **Estado H (Aval)**: Es cuando el plan está conforme con todas las disposiciones de la oficina asesora de planeación y solo puede ser realizado por el rol PLANEACION.

     ![avalar_plan_planeacion](https://github.com/udistrital/planeacion_cliente/assets/82072560/4e8f8a9e-63bf-4e02-b1f8-f8e9b7fc59b3)

### Notas Importantes
  **i.** Se continúa con la prueba del flujo de seguimiento.

**Comment by ccmendezt** [comment]
## Evidencias - Nuevas funcionalidades en nueva arquitectura PT2
### 05/06/2024 - 11:00

## Estandarización de Roles en SISGPLAN PT2

### Proceso de Seguimiento:

- **Estado A (Habilitado)**: Ambos roles, tanto _ASISTENTE_DEPENDENCIA_ como _JEFE_DEPENDENCIA_ pueden acceder a este estado del proceso:

     - **ASISTENTE_DEPENDENCIA**: 
     
     ![estado-a-habilitado-asistente-dependencia](https://github.com/udistrital/planeacion_cliente/assets/82072560/b6b30abe-d9c3-4a6a-8e77-075805c938bf)

     - **JEFE_DEPENDENCIA**: 
     
     ![estado-a-habilitado-jefe-dependencia](https://github.com/udistrital/planeacion_cliente/assets/82072560/1a179f56-216d-46cb-84d2-1fb43c834a7b)
     
- **Estado B (En reporte)**: Ambos roles, tanto _ASISTENTE_DEPENDENCIA_ como _JEFE_DEPENDENCIA_ pueden acceder a este estado del proceso, aunque normalmente lo realiza el ASISTENTE_DEPENDENCIA y las acciones permitidas para este estado son: _Consulta del plan, Seguimiento de planes, Evaluación cuantitativa y cualitativa, Editar evaluación cuantitativa y cualitativa_

     - **ASISTENTE_DEPENDENCIA**:
     
     ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/e1f1c4ee-e080-49ac-96b5-3b4acd5fdc3c)

     - **Componente cualitativo**:
        
     ![estado-b-comp-cualitativo-asistente-dep](https://github.com/udistrital/planeacion_cliente/assets/82072560/4b93c6e8-5cdb-4bde-b58a-2b1af8851b1b)

     - **Componente cuantitativo**:
        
     ![estado-b-comp-cuantitativo-asistente-dep](https://github.com/udistrital/planeacion_cliente/assets/82072560/4adab62b-73c6-4219-9c3e-fc74a8c7c210)

     En este estado, se permite tanto al ASISTENTE_DEPENDENCIA como al JEFE_DEPENDENCIA realizar el envío del reporte:

     - **ASISTENTE_DEPENDENCIA**: 
     
     ![generar-reporte-asistente](https://github.com/udistrital/planeacion_cliente/assets/82072560/a13e1fc4-366b-465d-851f-62e958466364)

     - **JEFE_DEPENDENCIA**: 
     
     ![generar-reporte-jefe](https://github.com/udistrital/planeacion_cliente/assets/82072560/122fa77d-3b4d-4a78-b888-56f60b5661ba)

- **Estado C (Enviado a revisión)**: En este estado se habilita un botón _Enviar Reporte_ en la visualización del trimestre tanto para JEFE_DEPENDENCIA como para ASISTENTE_DEPENDENCIA (normalmente lo hace este rol según el flujo) cuando el estado del seguimiento es _En reporte_, anteriormente se mostraba cuando estaba el estado _Habilitado_. Ya se corrigió:

     - **ASISTENTE_DEPENDENCIA**: 
     
     ![enviar-reporte-asistente](https://github.com/udistrital/planeacion_cliente/assets/82072560/2695b101-c8bc-4888-8686-cd3506b622f3)

     - **JEFE_DEPENDENCIA**:

     ![enviar-reporte-jefe](https://github.com/udistrital/planeacion_cliente/assets/82072560/95b1f413-a0b0-4732-a4c4-eb8c552278f9)

- **Estado D y E (En revisión JU y Revisión Verificada con Observaciones):** En este estado el JEFE_DEPENDENCIA inicia la revisión del seguimiento y en caso de que hayan observaciones, las realizará y finalizará la revisión del reporte de seguimiento:

![estado-d-en-revision-ju](https://github.com/udistrital/planeacion_cliente/assets/82072560/586c9900-f8e7-47b4-b2c6-ab39f75404a6)

En este caso, se devuelve el flujo para que el ASISTENTE_DEPENDENCIA revise las observaciones y reporte nuevamente el seguimiento para el periodo:

![estado-e-observaciones-ju](https://github.com/udistrital/planeacion_cliente/assets/82072560/16e37f2d-9991-43bd-848b-95a6b77bba6d)

- **Estado F (Revisión Verificada):** En este caso, entonces el JEFE_DEPENDENCIA revisa nuevamente el reporte de seguimiento y quita las observaciones para _Verificar la actividad_ y posteriormente asignarle el estado de _Revisión Verificada_ al reporte de seguimiento:

![estado-f-revision-verificada](https://github.com/udistrital/planeacion_cliente/assets/82072560/ce3bcad0-51b0-4d5d-89dc-3797fe27799e)

- **Estado G (En revisión OAP)**: Ambos roles, tanto _ASISTENTE_PLANEACION_ como _PLANEACION_ pueden acceder a este estado del proceso, para verificar el seguimiento y en dado caso realizar observación o avalar el reporte.

     - **ASISTENTE_PLANEACION**: 
     
     ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/f6c7ce3c-fda5-4665-bbea-0a9e4aa485b7)

     - **PLANEACION**:

     ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/a99e760e-0847-41c6-a238-f31e1c733f1d)

![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/6aad344b-42e5-4828-aeec-c7d52f7d9ee4)

**Revisión - ASISTENTE_PLANEACION:**

![observaciones-planeacion](https://github.com/udistrital/planeacion_cliente/assets/82072560/fb0e8810-3c8f-46ca-8ab1-7401a7218dfc)

- **Estado F (Con observaciones)**: Ambos roles, tanto _ASISTENTE_DEPENDENCIA_ como _JEFE_DEPENDENCIA_ pueden acceder a este estado del proceso, para para realizar las observaciones dadas por planeación:

     - **ASISTENTE_DEPENDENCIA**: 
     
     ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/ffcdc3a4-5986-4c0f-aa87-2b6014017d72)

     - **JEFE_DEPENDENCIA**:
     
     ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/c831a483-4810-449c-a032-19a07f80dd16)

El botón **enviar corrección** aparece incluso aún cuando no se han realizado las modificaciones de las observaciones, pero dicho botón tiene una validación que impide enviar el reporte sin que se haya realizado alguna modificación al reporte en cuestión:

![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/123a5eff-2c3b-4e1d-a205-a745bcf300bd)

Es por eso que se debe entrar al reporte de la actividad y luego realizar la modificación, dicho flujo funciona como se espera.

Luego, se vuelve al **Estado E** para que **PLANEACION** revise nuevamente la actividad, en este flujo es cuando dicho rol quita las observaciones y avala la actividad:

- **ASISTENTE_PLANEACION**: 

![revisar-actividad-asistente-planeacion](https://github.com/udistrital/planeacion_cliente/assets/82072560/3ad45e80-cf84-405d-a314-f43d97aca80b)

- **PLANEACION**:

![revisar-actividad](https://github.com/udistrital/planeacion_cliente/assets/82072560/8e281721-66b1-43fc-ac05-e66fe50613c7)

- **Estado G (Reporte Avalado)**: Únicamente el rol PLANEACION puede acceder a este estado en el que finaliza la revisión y finalmente avala el reporte, este apartado funciona como se espera:

![finalizar-revision-avalar-reporte](https://github.com/udistrital/planeacion_cliente/assets/82072560/cf172e1a-de4b-4117-806d-97cc60f6f892)

### Notas Importantes
  **i.** Se migró el componente plan-accion-seguimiento en planeacion_construccion_mf

![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/38e10346-34c9-4f68-a71b-d58155956fd1)

Pero no fue posible mostrarlo ya que hay error de cors para ambos componentes:
- **plan-accion-formulacion:**
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/ac6b5387-ac42-4071-a6ec-78e2862aacd0)

- **plan-accion-seguimiento:**
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/91b264f6-0427-4856-894f-c4d63120e835)

**Comment by ccmendezt** [comment]
## Pull Request Asociados a Issue
### 05/06/2024 - 12:00 pm

- **planeacion_construccion_mf:** https://github.com/udistrital/planeacion_construccion_mf/pull/6
- **planeacion_formulacion_mf:** https://github.com/udistrital/planeacion_formulacion_mf/pull/14
- **planeacion_seguimiento_mf:** https://github.com/udistrital/planeacion_seguimiento_mf/pull/14
- **planeacion_formulacion_mid:** https://github.com/udistrital/planeacion_formulacion_mid/pull/9
- **planeacion_seguimiento_mid:** https://github.com/udistrital/planeacion_seguimiento_mid/pull/15
