### ISSUE TITLE
Corrección de bugs encontrados en pruebas

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1067]
Tomando como referencia lo realizado en #1041 , se requieren terminar las pruebas funcionales en ambiente de pruebas, asociadas a los desarrollos realizados en SISGPLAN en los Sprints 3, 4 y 5 asociados al nuevo tablero, y comenzar con la corrección de los bugs encontrados.

**Especificaciones técnicas**

1. Las pruebas funcionales deben cubrir todos los desarrollos cargados en release en los Sprints 3, 4 y 5 asociados al nuevo tablero.
2. Se deben tomar como guía las pruebas realizadas por los desarrolladores en local en cada implementación.
3. El documento de pruebas debe especificar el estado en el que se encuentra el desarrollo, si se valida o no su funcionamiento y las observaciones correspondientes.
4. Los desarrollos a probar se encuentran en:
- [Sprint NP-3](https://github.com/orgs/udistrital/projects/54/views/1?filterQuery=sprint%3A%22Sprint+3%22)
- [Sprint NP-4](https://github.com/orgs/udistrital/projects/54/views/1?filterQuery=sprint%3A%22Sprint+4%22)
- [Sprint NP-5](https://github.com/orgs/udistrital/projects/54/views/1?filterQuery=sprint%3A%22Sprint+5%22)
5. Se deben probar solamente los desarrollos, las tareas de análisis o documentación no se tienen en cuenta.
6. Se trata de hacer un compendio de todas las pruebas realizadas hasta la fecha en un documento y validar su funcionamiento.
7. Adicional al documento que se debe presentar con las pruebas, se requiere realizar una anotación y seguimiento en forma de comentarios en este issue, de tal forma que se evidencien las pruebas realizadas en cada desarrollo y si aprueban o no. Tomar como guía: https://github.com/udistrital/sga_documentacion/issues/42
8. Carpeta para pruebas funcionales: https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EvgM4KowvOBKjdXD3aFLGV0BGcATolW8LorkydQUQnYMuA?e=MZjaiw

**Sub Tareas**

- [x] Terminar pruebas funcionales en ambiente de pruebas - SISGPLAN.
- [x] Seguimiento de pruebas funcionales en el issue.
- [x] Corrección de errores

**Criterios de aceptación**

- [x] Se presenta un documento con pruebas de los desarrollos implementados en los Sprints 3, 4 y 5 asociados al nuevo tablero.
- [x] Se presenta el seguimiento de las pruebas realizadas en el issue, asociadas a cada desarrollo.
- [x] Se presenta documento con errores corregidos

**Requerimientos**

- No presenta.

**Dependencias**

- planeacion_cliente.
- planeacion_mid.
- planes_crud.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
Se culmina con las pruebas realizadas dando un total de 76 pruebas funcionales realizadas y documentadas, el link de estas pruebas es el siguiente:

https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EQsDi0dVDLJIu2ZNiBwqPPcBROUILlJEFYOjXWFPPePT4Q?e=ziPobL

**Comment by Mechaz123** [comment]
Se corrigen los errores documentados en el excel presentado anteriormente, estos se encuentran marcados de color verde con el fin de dar como check el error de manera que se puede llevar un control de estos errores encontrados.

**Comment by Mechaz123** [comment]
Se adjunta el PR creado para los cambios que se formularon para este Issue:
https://github.com/udistrital/planeacion_cliente/pull/1121

**Comment by Mechaz123** [comment]
Se adjunta el PR creado para los cambios que se formularon para este Issue hacia Develop:
https://github.com/udistrital/planeacion_cliente/pull/1122
