### ISSUE TITLE
Implementación de notificaciones a nivel de sistema en MFs - SISGPLAN - (PARTE 1)

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1068]
Con base en la implementación realizada en planeacion_cliente, se requiere implementar sistema de notificaciones internas en la nueva arquitectura de SISGPLAN basada en MFs.

**Especificaciones Técnicas**

1. Se debe implementar sistema de notificaciones internas en los siguientes MFs:

- planeacion_formulacion_mf
- planeacion_seguimiento_mf

2. Se debe contemplar la posibilidad de que los servicios relacionados con notificaciones estén alojados en **core_mf** o **root_mf** para que sean consumidos por los MFs que los requieran.
3. La funcionalidad debe ser igual a la implementada en **planeacion_cliente**, satisfaciendo las mismas necesidades.
4. Las funcionalidades implementadas en web-components deben ser migradas y consumidas desde core_mf.

**Material de apoyo**

- Manual técnico: https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EdixQ978d0hFgJi-psItfw8B1HgCUT9vVDjo4hAqkWQ5qg?e=VMY9wm

**Sub Tareas**

- [x] Migración de funcionalidades de notificaciones de web-components a core_mf.
- [x] Implementación de sistema de notificaciones en planeacion_formulacion_mf.
- [x] Implementación de sistema de notificaciones en planeacion_seguimiento_mf.
- [x] Implementación de complementos en planeacion_root_mf y core_mf para el sistema de notificaciones.

**Criterios de aceptación**

- [x] La nueva arquitectura de SISGPLAN permite el envío y recepción de notificaciones internas en la formulación de un plan de acción.
- [x] La nueva arquitectura de SISGPLAN permite el envío y recepción de notificaciones internas en el seguimiento de un plan de acción.

**Requerimientos**

- [x] Documento técnico de implementación

**Dependencias**

- [x] planeacion_formulacion_mf
- [x] planeacion_seguimiento_mf
- [x] notificaciones_mid
- [x] core_mf
- [x] planeacion_root_mf

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Se asocia el link del commit debido a que no se enlazo correctamente: [commit](https://github.com/udistrital/core_mf_cliente/commit/4c430458a914cf7d3187659e862c0ebd480f88df)

**Comment by a52290451** [comment]
Para cerrar la actividad se requiere:

1. Video corto con el desarrollo implementado.
2. PR con cambios realizados en los diferentes MF.
