### ISSUE TITLE
Ocultar vinculaciones antiguas en fase de formulación, solo tomar la mas reciente.

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1069]
Se requiere optimizar el flujo de formulación para que una unidad solo pueda formular planes asociados a su vinculación mas reciente y no sobre vinculaciones antiguas relacionadas.

**Especificaciones Técnicas**

1. Para cada usuario en el sistema con sus diferentes roles, se requiere restringir el sistema en formulación para que solo pueda formular planes asociados a la vinculación mas reciente.
2. Si un usuario tiene mas de una vinculación, solo se tendrá en cuenta la vinculación mas reciente, las vinculaciones antiguas solo deben estar habilitadas para consulta.

**Sub Tareas**

- [x] Restringir sistema para permitir formulación de planes solo en la última vinculación asociada al usuario.

**Criterios de aceptación**

- [x] El sistema solo me permite realizar formulación de planes de acción asociados a mi vinculación mas reciente.

**Requerimientos**

- N/A

**Dependencias**

- planeacion_mid
- planeacion_cliente
- planeacion_formulacion_mid
- planeacion_formulacion_mf

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
Buen día, queda pendiente subir commit y realizar pruebas relacionadas.

**Comment by a52290451** [comment]
Falta realizar pruebas.

**Comment by Oscarjaimes1710** [comment]
Para cerrar la issue, a pesar de desarrollarse codigo para realizar la limitación encontramos que ya hay una limitación existente aquí en esta consulta : https://autenticacion.portaloas.udistrital.edu.co/apioas/planeacion_mid/v1/formulacion/vinculacion_tercero/1917 

pero nos encontramos consultado en un MF asi como se ve en esta consulta:  https://autenticacion.portaloas.udistrital.edu.co/apioas/planeacion_formulacion_mid/v1/formulacion/tercero/1917; aparecen las dos vinculaciones entonces basados en esto, se debe realizar una revisión a las consultas donde ya se esta limitando porque no sabemos si esta trayendo la vinculación correcta o no.

**Comment by a52290451** [comment]
Buen dia, se requiere validar desarrollo actual y comprobar su funcionamiento

**Comment by Oscarjaimes1710** [comment]
Queda pendiente realizar prueba funcional en local.

**Comment by norbeydanilo** [comment]
Queda pendiente verificación @a52290451

**Comment by a52290451** [comment]
@Oscarjaimes1710 Cargar evidencia para cerrar issue

**Comment by norbeydanilo** [comment]
Por favor actualizar con lo solicitado @Oscarjaimes1710 
Proceder con la revisión y cierre @a52290451

**Comment by Oscarjaimes1710** [comment]
Para dar cierre se hacen las pruebas requeridas y se encuentra que el funcionamiento no era el esperado se hace un ajuste de posición dentro de la lógica anteriormente crea para este ajuste y se dejan aquí las pruebas del funcionamiento. 

Funcionamiento Actual: 
![Captura de pantalla 2024-07-03 a la(s) 5 09 28 p  m](https://github.com/udistrital/planeacion_cliente/assets/145817817/aba0475b-dcb9-4a42-9936-6829819b97a7)

Funcionamiento después del ajuste: 
![Captura de pantalla 2024-07-03 a la(s) 5 09 44 p  m](https://github.com/udistrital/planeacion_cliente/assets/145817817/50ee3f2d-6373-4308-af9b-0e25f16190ba)

Aquí se deja la prueba de de que la vinculación que se muestra en la anterior imagen corresponde a la vinculacion mas reciente: 
<img width="579" alt="Captura de pantalla 2024-07-03 a la(s) 5 10 00 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/91e0a2b2-3450-46ef-ac82-f656dacdb10a">
<img width="579" alt="Captura de pantalla 2024-07-03 a la(s) 5 10 04 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/3e441c8d-e821-49e9-9c74-9a8e63c2a869">
<img width="579" alt="Captura de pantalla 2024-07-03 a la(s) 5 10 09 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/3bf0a333-fec2-40c8-b61a-2e8afffd1d75">

**Comment by Oscarjaimes1710** [comment]
Se hacen los ajustes solicitados por parte de @a52290451 y el funcionamiento quedo asi: 

![Captura de pantalla 2024-07-04 a la(s) 1 20 15 p  m](https://github.com/udistrital/planeacion_cliente/assets/145817817/c0c7961a-7742-46ec-a3e1-7c1737f8610e)
![Captura de pantalla 2024-07-04 a la(s) 1 19 54 p  m](https://github.com/udistrital/planeacion_cliente/assets/145817817/63e45f4a-d760-41a5-9198-be49b158552e)
![Captura de pantalla 2024-07-04 a la(s) 1 19 48 p  m](https://github.com/udistrital/planeacion_cliente/assets/145817817/00a9c358-ff3c-435f-84ed-1cd25248a69e)
![Captura de pantalla 2024-07-04 a la(s) 1 19 42 p  m](https://github.com/udistrital/planeacion_cliente/assets/145817817/addacf0e-1043-402d-93c8-cf1ee367f18d)

**Comment by Oscarjaimes1710** [comment]
Prueba de funcionamiento del ajuste en formulación de la ultima vinculación para la formulación y consulta de planes.

https://udistritaleduco-my.sharepoint.com/:v:/g/personal/computo_udistrital_edu_co/EVKNvTsKw_9DvZA8Z4pyB6QBjKh8snKwe7PiIz8QlqgTNg?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=WqiekQ

**Comment by a52290451** [comment]
Se valida y aprueba el desarrollo relizado.
