### ISSUE TITLE
Corrección de endpoint en seguimiento_mid

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1076]
Revisar el endpoint de seguimiento (seguimiento/:plan_id/index/semstre_id)
Revisar el bug reportado en #1048 , se requierecorregirlo para dejar estable las funcionalidades en la nueva arquitectura.

**Especificaciones técnicas**

1. El micro mid que en el que se debe realizar la corrección corresponde  a [planecion_seguimiento_mid](https://github.com/udistrital/planeacion_seguimiento_mid)

**Sub Tareas**

- [x] Identificar el error
- [x] Implementar la corrección del comportamiento no esperado
- [x] Realizar una prueba funcional.

**Criterios de aceptación**

- [x] Documenta la issue de manera completa con la identificación del error, la corrección del mismo, la prueba funcional y el commit con los cambios a develop.
- [x] Se corrige el bug.

**Requerimientos**

- No presenta.

**Dependencias**

- planeacion_seguimiento_mf

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by C0C045** [comment]
# Identificación del Error:
El problema consistía en que en la función `consultarActividad()` el método `ConvertirStringJson(detalle)` no retornaba correctamente el tipo de dato necesario para continuar con la lógica actual; ya que se esperaba un tipo de dato `map[string]interface{}`, pero en su lugar retornaba un `string`. Tal que así:

**En código:**
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/f21fca17-61da-4c82-9745-dc5178fde6c3)

**En consola:**
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/c8b8472f-0be9-49a0-bb53-fa85b4bc5665)

Por lo tanto, se comparo el método `ConvertirStringJson(detalle)` tanto en 'seguimiento_mid' como en 'planeacion_mid' y se encontró que ambos son diferentes entre sí:

**PLANEACION_MID:**
```golang
func ConvertirStringJson(diccionario map[string]interface{}) map[string]interface{} {
	dicStrings := map[string]interface{}{}
	for clave, valor := range diccionario {
		if clave == "informacion" || clave == "cualitativo" || clave == "cuantitativo" || clave == "estado" {
			datoJson := make(map[string]interface{})
			json.Unmarshal([]byte(valor.(string)), &datoJson)
			dicStrings[clave] = datoJson
		} else if clave == "evidencia" {
			var datoJson []map[string]interface{}
			json.Unmarshal([]byte(valor.(string)), &datoJson)
			dicStrings[clave] = datoJson
		} else {
			dicStrings[clave] = valor
		}
	}
	return dicStrings
}
```
**SEGUIMIENTO_MID:**
```golang
func ConvertirStringJson(diccionario map[string]interface{}) map[string]interface{} {
	diccionarioStrings := map[string]interface{}{}

	for clave, valor := range diccionario {
		jsonBytes, _ := json.Marshal(valor)
		if string(jsonBytes) == "null" {
			diccionarioStrings[clave] = "{}"
		} else if clave == "_id" || clave == "fecha_creacion" {
			diccionarioStrings[clave] = valor
		} else {
			diccionarioStrings[clave] = string(jsonBytes)
		}
	}
	return diccionarioStrings
}
```

En consecuencia, el método `ConvertirStringJson()` actual de 'seguimiento_mid' no soporta la conversión del 'detalle' de cada actividad y por ende la petición falla.

**Comment by C0C045** [comment]
# Solución del Error:
Como se mencionó con anterioridad el problema consistía en que la función actual de `ConvertirStringJson()` no soporta la conversión del detalle de cada actividad, por ende, se propuso implementar una función que si soporte este tipo de dato para que la petición pueda culminar con éxito.
Esta nueva función con el mismo nombre se desarrolló en `helpers/seguimiento_helper.go` para no modificar la general que se encuentra en [utils_oas](https://github.com/udistrital/utils_oas/blob/master/planeacion/planeacion.go#L100).

**Prueba Funcional:**
![PeticionSeguimiento](https://github.com/udistrital/planeacion_cliente/assets/55455142/d7c1a939-5a27-4da1-8fec-9fe86c539843)

**Comment by C0C045** [comment]
# PR
seguimiento_mid: https://github.com/udistrital/planeacion_seguimiento_mid/pull/13
