### ISSUE TITLE
Mejora: Ajustes en flujo de formulación

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1078]
Se requiere realizar el ajuste de las recomendaciones realizadas en: #1037 en el flujo de formulación.

**Especificaciones técnicas**

1. No se logra formular un plan con la vigencia 2023 ya que no se pueden agregar los contratistas correctamente
**Contexto:**
Con el rol de unidad y con un plan en estado de formulación, se desea hacer la identificación de contratistas.
**Comportamiento esperado:**
Configuración de los contratistas y posterior guardado dentro de la actividad.
**Comportamiento actual:**
![Image](https://github.com/udistrital/planeacion_cliente/assets/85894335/26972b54-278f-4231-8ebf-24a30289d4cc)
**Observaciones:**
Se hace la petición a `https://autenticacion.portaloas.udistrital.edu.co/apioas/parametros/v1/parametro_periodo?query=ParametroId:485,PeriodoId:25` la cual retorna un objeto vacío `[{}]`.

2. 
**Contexto:**
Se están revisando las actividades de un plan en estado "Aval".
**Comportamiento esperado:**
Mensajes y botones congruentes con el estado actual de el plan.
**Comportamiento actual:**
Mientras se está visualizando una actividad:
![Image](https://github.com/udistrital/planeacion_cliente/assets/85894335/b5b903f3-d645-4761-80f5-56a56696e68d)
1. Al dar click en "Cancelar", sale el siguiente mensaje:
  ![Image](https://github.com/udistrital/planeacion_cliente/assets/85894335/98900ca7-540d-4f0f-ad13-39a906191b58)
  Se esperaría una pregunta como "¿Desea cerrar la actividad?" ya que el plan ya se encuentra registrado.
2. Se tiene el botón "Guardar", a pesar de que no se pueden modificar los datos, este botón sigue estando habilitado para hacer la petición a los servicios pertinentes, comportamiento que no me parece el adecuado.

**Sub Tareas**

- [ ] Corrección de data y bugs asociados a la vigencia 2023 en formulación.
- [ ] Corrección de mensajes y botones en estado Aval en formulación.

**Criterios de aceptación**

- [ ] El sistema permite formular planes de acción correctamente para la vigencia 2023.
- [ ] El sistema muestra y controla correctamente la información cuando un plan se encuentra en estado Aval en formulación.

**Requerimientos**

- No aplica

**Dependencias**

- planeacion_cliente
- planeacion_mid
- planeacion_crud

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Oscarjaimes1710** [comment]
Se esta trabajando en el desarrollo y solución de esta issue.

**Comment by Oscarjaimes1710** [comment]
Issue culminada.

Pruebas funcionales Aquí : https://udistritaleduco-my.sharepoint.com/:v:/g/personal/computo_udistrital_edu_co/EQXb594ouaFNvGAJqqZWRv8BBsHHGRS9Skq4FaIQF57iWQ?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=CPLAMv 
y https://udistritaleduco-my.sharepoint.com/:v:/g/personal/computo_udistrital_edu_co/EatfdduMlxhHhmpqS1D3NV8BY7e8gjcP9b_E1fmb8U4M8A?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=pAro9p

Los videos son la prueba funcional de que todos los elementos están funcionando correctamente. 


En resumidas cuentas lo que estaba ocurriendo es que los elementos 485, 486, 487, 488 y 489 de parámetros id que corresponden a Servicios Técnicos o tecnológicos, Servicios profesionales, Servicios profesionales especializados, Perfil asesor l y Perfil asesor ll , Respectivamente no tenían la vigencia 25 que corresponde al id de la vigencia 2023 no tenían habilitado o cargado dicha vigencia por eso se presentaba el error , pero como se evidencia en las siguientes capturas ya quedo correcto. 
<img width="1512" alt="Captura de pantalla 2024-06-13 a la(s) 1 45 51 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/d34b53eb-c893-40a0-82ca-d1f59e6d6361">
<img width="1512" alt="Captura de pantalla 2024-06-13 a la(s) 1 46 48 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/9bb0d5cf-12c9-42e0-8c85-957b9b20075e">
<img width="1512" alt="Captura de pantalla 2024-06-13 a la(s) 1 46 55 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/fe560722-e416-4243-a513-25fbce742007">
![Uploading Captura de pantalla 2024-06-13 a la(s) 1.47.04 p. m..png…](
<img width="1512" alt="Captura de pantalla 2024-06-13 a la(s) 1 47 10 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/fcd90144-b56a-48da-95d7-149149564f19">

Se hizo la inserción de dicha data a través de un script tomando como base el scrip que se monto en la issue -https://github.com/udistrital/planeacion_cliente/issues/1135

**Comment by Oscarjaimes1710** [comment]
Parte 1 culminada, En desarrollo la parte 2.

**Comment by Oscarjaimes1710** [comment]
Parte 2: Evidencia de la modificación.

![Captura de pantalla 2024-06-14 a la(s) 9 36 45 p  m](https://github.com/udistrital/planeacion_cliente/assets/145817817/a00dbf50-1a54-4bb1-adf6-94299d4786c6)
![Captura de pantalla 2024-06-14 a la(s) 9 36 51 p  m](https://github.com/udistrital/planeacion_cliente/assets/145817817/60483d43-8ce9-4896-8a68-bb8b80e6b96d)

Se hace el respectivo commit y el pr.
