### ISSUE TITLE
Pruebas y Documentación Notificaciones MFs - AWS (PARTE 1)

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1090]
Se requiere complementar el documento técnico en el cual se describa el desarrollo realizado con el módulo de notificaciones internas a nivel de sistema, incluyendo el desarrollo realizado en MFs.

**Especificaciones técnicas**

1. El documento técnico debe contener los siguientes elementos:

- Portada.
- Tabla de Contenido.
- Objetivos.
- Requerimientos.
- Tecnologías implementadas.
- Costos de utilización.
- Conceptos básicos.
- Aspectos técnicos.
- Instrucciones de implementación.
- Conclusiones.
- Recomendaciones y Mejoras.

Se requiere complementar las secciones que sean necesarias.

2. Actualizar tabla de versionado de documento.

3. En la sección de aspectos técnicos se debe incluir el detalle de la implementación en MFs.

4. Se deben realizar pruebas funcionales en todo el cliente, verificando el correcto funcionamiento de los Puntos de notificación.

**Sub Tareas**

- [x] Actualización de Manual Técnico: Notificaciones Internas.
- [ ] Pruebas funcionales de puntos de notificación en MFs.

**Criterios de aceptación**

- [x] Existe un Manual Técnico actualizado que me permite implementar el servicio de notificaciones internas en cualquier sistema.
- [ ] La implementación de Notificaciones Internas para SISGPLAN en su nueva arquitectura, cuenta con pruebas funcionales.

**Requerimientos**

- [x] Completar issue #1068 .
- [x] Completar issue #1097 .

**Dependencias**

- microfrontends planeacion.
- notificaciones_mid.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Se asocia link del documento técnico: 
[Documento Técnico Notificaciones](https://udistritaleduco-my.sharepoint.com/:w:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7BDE43B1D8-77FC-4548-8098-BEA6C22D7F0F%7D&file=Documento%20T%C3%A9cnico%20Notificaciones.docx&action=default&mobileredirect=true&wdOrigin=OFFICE-METAOS.FILEBROWSER.FILES-HOME)

**Comment by diegobauto** [comment]
Se asocia nuevamente link del documento técnico:
- Documentación de notificaciones para microfrontends
- Diagramas de componentes y secuencia
- Enlaces de proyectos para su visualización
- Manejo de colas
- Consideraciones
- Otros

[Documento Técnico Notificaciones](https://udistritaleduco-my.sharepoint.com/:w:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7BDE43B1D8-77FC-4548-8098-BEA6C22D7F0F%7D&file=Documento%20T%C3%A9cnico%20Notificaciones.docx&action=default&mobileredirect=true&wdOrigin=OFFICE-METAOS.FILEBROWSER.FILES-HOME)

**Comment by a52290451** [comment]
Se valida y aprueba Documento técnico realizado.

**Comment by diegobauto** [comment]
Se mantiene tarea en pendiente debido a:

Errores presentados en el flujo (problema de planeación)
![imagen](https://github.com/udistrital/planeacion_cliente/assets/64450601/ee0b44c8-5731-4b13-bb19-6ce90bb981c0)

De igual manera al intentar asignar actividades para un plan: 
![imagen (1)](https://github.com/udistrital/planeacion_cliente/assets/64450601/7bd64545-8081-4a2b-be84-f7f22345aa19)

Por otro lado, aún falta la migración del microfrontend de seguimiento, por lo que aún quedan banderas pendientes para el modulo.

**Comment by a52290451** [comment]
Debido a la falta de sincronización entre el desarrollo realizado en el Monolito y la implementación en MFs, no es posible concluir con pruebas funcionales.
