### ISSUE TITLE
Optimización desarrollo de códigos de abreviación.

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1103]
Se requiere realizar la optimización relacionada con la implementación de códigos de abreviación de tal forma que la consulta de los códigos se realice cuando se requiera cada uno y no al inicio.

**Sub Tareas**

- [ ] 

**Criterios de aceptación**

- [ ] 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by felimarod** [comment]
Se modificó el servicio codigos.service.ts de tal manera que obtenga el ID al traer el elemento la primera vez
Commit asociado: https://github.com/udistrital/planeacion_cliente/commit/0545d5569cf18b36ed356677bf64e20ae66e65ba

**Comment by a52290451** [comment]
Queda pendiente realizar PR
