### ISSUE TITLE
Reformulación de planes de acción PT3

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1110]
Se requiere continuar y finalizar con la implementación de reformulación de planes de acción una vez estos se encuentran en la fase de seguimiento.

**Especificaciones técnicas**

- Las HU que acompañan esta primera parte del desarrollo son: https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7B35B71E3E-8F62-4FE1-A27D-62D3C527BD47%7D&file=hu%20menu%20de%20acceso%20reformulacion%20(1).xlsx&action=default&mobileredirect=true

- Los mockups correspondientes a este issue son: 

1. https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EZT3UasU9C1Jjt4oxrAjmW0BqholdiIrNyzaQqdJAUVBsA?e=EiLvLd
2. https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EQQ3KsAtUtVCoRlVG1HwfRcBfexnDdZW7cgUMx7wouiolg?e=ovcNPi

- Los repositorios de los MF son: 

1. [Root](https://github.com/udistrital/planeacion_root_mf)
5. [Utilidades](https://github.com/udistrital/planeacion_utilidades_mf)(Revisar como mostrar la imagen base de SISGPLAN).
6. [Formulacion](https://github.com/udistrital/planeacion_formulacion_mf) 
7. [Seguimiento](https://github.com/udistrital/planeacion_seguimiento_mf)5. [Evaluacion](https://github.com/udistrital/planeacion_evaluacion_mf)
8. [Macroplanes](https://github.com/udistrital/planeacion_macroplanes_mf)
9. [Pendientes](https://github.com/udistrital/planeacion_macroplanes_mf)
10. [Construccion](https://github.com/udistrital/planeacion_macroplanes_mf)

- Los repositorios de los mid son:

1. [planeacion_formulacion_mid](https://github.com/udistrital/planeacion_formulacion_mid)
2. [planeacion_seguimiento_mid](https://github.com/udistrital/planeacion_seguimiento_mid)
3. [planeacion_evaluacion_mid](https://github.com/udistrital/planeacion_evaluacion_mid)
4. [planeacion_reportes_mid](https://github.com/udistrital/planeacion_reportes_mid)
6. [planeacion_arbol_mid](https://github.com/udistrital/planeacion_arbol_mid)
7. [planeacion_formato_mid](https://github.com/udistrital/planeacion_formato_mid)

- La reformulación a grandes rasgos debe cumplir con las siguientes condiciones:

1. Todo cambio a realizar debe estar debidamente sustentado y aprobado por la OAP
2. Los cambios realizados deben conservar la regla que las ponderaciones totales de indicadores sumen el 100% tanto a nivel general como particular.
3. Los cambios realizados a los recursos sean ops o recursos docentes no deben afectar el presupuesto asignado.
4. Al momento de realizar un cambio e implementarlo en el plan de acción se genera un punto de corte en donde: la parte correspondiente a lo ya medido (el pasado) se conserva igual, generando un cierre de esa parte del plan. Para la parte futura del plan, después del punto de corte, el plan se genera con una versión superior y una nota aclaratoria que indique la reformulación de alguno de sus componentes.
5. Se debe asegurar al momento de implementar los cambios; estos no involucren un mayor gasto del presupuesto asignado.
6. Si, al realizar los cambios en el plan se libera parte del presupuesto asignado, este movimiento debe ser informado a la OAP para su autorización y se debe conocer el nuevo destino de los recursos monetarios liberados.

**Sub Tareas**

- [ ] Leer las HU y revisar los mockups para entender más el proceso requerido.
- [ ] Crear un componente visual que este relacionado con la solicitud formal de reformulación de plan la cual mostrará información relacionada con el plan escogido por parte de la unidad: "Unidad,  estado del reporte", ID de plan de acción, vigencia, Nombre de plan de acción. Además, la vista tiene que contar con tres acciones:

1. Cargar archivo PDF con la solicitud formal de reformulación del plan de acccón.
2. La visualización del archivo cargado.
3. Envío de la solicitud de reformulación.

Finalmente se debe habilitar un campo de observaciones limitado a 1000 caracteres con un contador que vaya indicando al usuario cuantos caracteres lleva diligenciado.

Deben quedar como campos obligatorios el cargue del archivo y las observaciones para enviar la solicitud.

**Criterios de aceptación**

- [ ] Los relacionados a las HU.
- [ ] Documentación del issue progresiva e informativa.
- [ ] Se evidencia el menú, la asociación a la tabla de búsqueda, la redirección a la solicitud formal de un plan de acción con su cargue de documento y diligenciamiento de observaciones.

**Requerimientos**

- [ ] Completar Issue #1065 .
- [ ] Completar Issue #1098 . 

**Dependencias**

- micromids de planeación.
- microfrontends de planeación.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by felimarod** [comment]
Desarrollos realizados
-
- Se ha completado la tabla
- Se completo la redirección
  - Seleccionando los inputs
  - Desde la tabla
- Se carga la información del plan necesaria para su identificación
  - Se agregó la información de la vigencia a la vista
- Se cambiaron los iconos de los botones
- Se agrego el campo para diligenciar las observaciones
- Se agregaron mensajes durante la carga de archivos
- Se mejoraron los estilos de la visualización del archivo
- Se agregaron mensajes de verificación al enviar la solicitud

Pruebas funcionales
- 
https://github.com/udistrital/planeacion_cliente/assets/85894335/d46296fd-6cf9-4273-8ab5-7646427ec1bd



Pendientes
-
1. Verificar que los planes que se cargan en la primer vista si son los esperados
  Actualmente se cargan los planes que se encuentran en estado avalado y son respectivos a las unidades del usuario
2. Subir el documento por medio del API respectivo*
    - Controlar el error
4. Hacer la conexión para hacer el cargue de la solicitud con la respectiva observación*
    - Controlar el error


*) Hacer los endpoints de ser necesarios

**Comment by felimarod** [comment]
**Deuda tecnica:** Manejo de las rutas correcto. Esto se debe a que no se logró agregar solicitud dentro de formulación correctamente

![Image](https://github.com/udistrital/planeacion_cliente/assets/85894335/96754297-66f3-4ff5-87ad-2408e8dc4fae)

**Comment by a52290451** [comment]
Queda pendiente revisar PR y cerrar issue.
