### ISSUE TITLE
Mejora: Bug, no se puede aprobar un solo plan o proyecto en Pendientes/formulación/seguimiento

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1112]
Se requiere habilitar la opción de aprobar un plan de acción (verificar) tanto en formulación como en seguimiento en el módulo de "Pendientes".

**Especificaciones técnicas**

1. El desarrollo se debe aplicar tanto en la nueva arquitectura como en el monolito.
2. Actualmente desde "Pendientes" se pueden verificar varios planes de acción (más de dos) por parte del jefe_dependencia.

**Sub Tareas**

- [x] Habilitar la opción de verificar un plan de acción tanto en formulación como en seguimiento.
- [x] Pruebas funcionales tanto en monolito como en nueva arquitectura

**Criterios de aceptación**

- [x] Documenta la issue de manera completa.
- [x] Se verifica la funcionalidad.

**Requerimientos**

- No presenta.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by C0C045** [comment]
# Bug Solucionado
Ya esta disponible la verificación de un solo plan tanto en la tabla de formulación como la de seguimiento. Además, esta nueva funcionalidad se agregó tanto en el monolito como en la nueva arquitectura.

**Prueba Funcional Monolito:**
![AprobarUno](https://github.com/udistrital/planeacion_cliente/assets/55455142/2d626f5c-a621-4a1f-9443-43b1415ae967)

**Prueba Funcional MF:**
![AprobarUnoMf](https://github.com/udistrital/planeacion_cliente/assets/55455142/fc313a05-95b5-4375-a3fe-89772d7c8ad1)

**Comment by C0C045** [comment]
# PR's
planeacion_cliente: https://github.com/udistrital/planeacion_cliente/pull/1123
pendientes_mf: https://github.com/udistrital/planeacion_pendientes_mf/pull/12
