### ISSUE TITLE
Revisión de gestión de usuarios

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1113]
Revisar el bug que se presenta al utilizar el módulo de gestión de usuarios, actualmente se genera un error 404 y posteriormente 504, al no encontrar la vinculación de los correos.

**Especificaciones técnicas**

1. Este desarrollo se ha realizado en el monolito y en la nueva arquitectura.

**Sub Tareas**

- [x] Identificar el error
- [x] Controlar el error
- [x] Realizar varias pruebas funcionales para corregir el comportamiento.

**Criterios de aceptación**

- [x] Documenta la issue de manera completa con la identificación del error, la corrección del mismo, la prueba funcional y el commit con los cambios a develop.
- [x] Se corrige el bug.

**Requerimientos**

- No presenta.

**Dependencias**

- 

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by ccmendezt** [comment]
## Evidencias - Revisión de gestión de usuarios
### 05/06/2024 - 16:00

Se corrió planeacion_cliente, planeacion_mid y autenticacion_mid en local para revisar el comportamiento del módulo de gestión de usuarios:

- El módulo cuando se corren los servidores localmente funciona con normalidad:

A continuación vemos la solicitud de **vinculación** del rol ASISTENTE_DEPENDENCIA a un usuario:
![gestion-usuarios1](https://github.com/udistrital/planeacion_cliente/assets/82072560/eb37d7cb-6843-4292-9240-6d830d4ca0b1)

**Desvinculación** de rol:
![gestion-usuarios2](https://github.com/udistrital/planeacion_cliente/assets/82072560/9c66d8cf-18c9-43c0-84cf-5430579cf081)

- Al intentar realizar la petición desde pruebasplaneacion obtenemos por consola los siguientes mensajes:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/e6cbfae5-4073-430c-b204-6fb771fba339)

Es posible que el error sea por CORS ya que como se mostró, cuando se utilizan **planeacion_cliente**, **planeacion_mid** y **autenticacion_mid** en su branch _develop_ para cada una, el módulo funciona con total _normalidad_ como se espera.

**Comment by ccmendezt** [comment]
## Evidencias - Revisión de gestión de usuarios
### 07/06/2024 - 11:07 am

- Se creó un nuevo servicio dentro de **planeacion_mid** que permite obtener las vinculaciones de un usuario a partir de su número de identificación, concretamente la ruta es _formulacion/vinculacion_tercero_identificacion/:identificacion_, a continuación una prueba funcional desde Swagger:

![vinculaciones-identificacion](https://github.com/udistrital/planeacion_cliente/assets/82072560/bff70bf9-a99c-4144-9ca4-3276514bd74e)

- En **planeacion_cliente** se modificó la estructura y validaciones del template para que reciba correctamente un número de identificación en lugar de un correo electrónico y se valida el correcto funcionamiento del mismo:

![vinculaciones-monolito](https://github.com/udistrital/planeacion_cliente/assets/82072560/72c0db06-ed3e-42da-b79a-fabdb7790575)

- Se comprueba el correcto funcionamiento de la adición de un rol a un usuario y el cambio de cargo_id a su vinculación:

![vinculacion-rol](https://github.com/udistrital/planeacion_cliente/assets/82072560/0b3565d4-06db-4fcc-8266-93b6f82b5f45)

- Se comprueba el correcto funcionamiento de la eliminación de un rol a un usuario y el cambio de cargo_id a su desvinculación:

![desvinculacion-rol](https://github.com/udistrital/planeacion_cliente/assets/82072560/e066fd90-3369-4d60-8fa7-ff55a2c3e225)

## Pull Request asociados a Issue:
- planeacion_mid: https://github.com/udistrital/planeacion_mid/pull/544
- planeacion_cliente: https://github.com/udistrital/planeacion_cliente/pull/1129

**Comment by ccmendezt** [comment]
## Evidencias - Revisión de gestión de usuarios
### 11/06/2024 - 15:24

- Se actualizó el Swagger en WSO2 y se comprueba funcionalidad.
- **Búsqueda por número de identificación y vinculación rol:**
![busqueda-vinculacion](https://github.com/udistrital/planeacion_cliente/assets/82072560/33777d02-d98e-40cf-b01d-b38d227d778f)

- **Búsqueda por número de identificación y devinculación rol:**
![busqueda-desvinculacion](https://github.com/udistrital/planeacion_cliente/assets/82072560/b1b1d626-92b1-42b6-904c-ed5e833feda7)
