### ISSUE TITLE
Gestion de usuarios - adición de rol de asistente_planeacion

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1114]
cargo_id: 320

Se requiere habilitar la opción de asignar y desvincular el rol de asistente_planeacion a un usuario desde el módulo fe gestión de usuarios encontrado en administración.

**Especificaciones técnicas**

1. El desarrollo se debe aplicar tanto en la nueva arquitectura como en el monolito.
2. Actualemente el único rol que se puede asignar correspondea  asitente_dependencia.

**Sub Tareas**

- [x] Se debe habilitar la opción de asignar el rol de "asistente_planeacion" tal y como se desarrolla el proceso de asistente_dependencia. Sin embargo, se tiene que tener en cuenta la consideración, que dentro de las vinculaciones de las cuales planeacion puede seleccionar, solo deben listarse aquellas activas y con la dependencia de "Oficina Asesora de Planeacion", de resto el cargo_id asignado corresponde al mismo.
- [ ] Se deben realizar pruebas funcionales tanto en el monolito como en la nueva arquitectura.

**Criterios de aceptación**

- [x] Documenta la issue de manera completa.
- [x] Se verifica la funcionalidad.

**Requerimientos**

- No presenta.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by ccmendezt** [comment]
## Evidencias - Avance Adición de rol de ASISTENTE_PLANEACION 
### 11/06/2024 - 15:10

- Se permite adicionar el rol de ASISTENTE_PLANEACION a un usuario del sistema. Para esto se realizaron validaciones tanto en _planeacion_cliente_ como en _planeacion_mid_ para que NO se permitiera adicionar dicho rol a una vinculación que no perteneciera a la Oficina Asesora de Planeación

- **Validación Backend:** Para mostrar esta validación desactivé la del Frontend, acá intentaremos adicionar el rol ASISTENTE_PLANEACION a un usuario con una vinculación en la Vicerrectoría Académica:

![validacionBackend](https://github.com/udistrital/planeacion_cliente/assets/82072560/7bb6b786-b7f2-43d7-9ebf-967065a202f0)

- **Validación Frontend:** La validación en el frontend muestra un popup con la misma información al momento de querer agregar el rol a una vinculación distinta a la OAPC

![validacionFrontend](https://github.com/udistrital/planeacion_cliente/assets/82072560/22b7c29a-7d9b-4653-a43e-461b4ce9785d)

Como se puede observar en los videos anteriores, en la validación del Backend se envía la petición a _planeacion_mid_ y allí valida si la vinculación que se quiere realizar es posible, con la validación del Frontend él también valida pero no realiza ninguna petición. La suma de ambas validaciones hace que la vinculación del rol ASISTENTE_PLANEACION solo sea posible a un usuario con una vinculación a la OAPC.

- Vinculación Rol:
![vinculacion-rol](https://github.com/udistrital/planeacion_cliente/assets/82072560/be495adb-bcb9-44d7-b279-279336928d05)

- Desvinculación Rol:
![desvinculacion-rol](https://github.com/udistrital/planeacion_cliente/assets/82072560/c2c5452d-a958-4bc7-9831-67602724be93)

Como se observa en la vinculación/desvinculación, la agregación del rol desde _AUTENTICACION_MID_ se realiza sí y solo sí se realiza correctamente la petición de _planeacion_mid_

**Comment by ccmendezt** [comment]
## Pull Request Asociados a Issue
### 11/06/2024 - 15:18

- **planeacion_cliente:** https://github.com/udistrital/planeacion_cliente/pull/1139
- **planeacion_mid:** https://github.com/udistrital/planeacion_mid/pull/552

**Comment by ccmendezt** [comment]
Se respondieron los comentarios de los PR.

- Se muestra popup informativo en el que dice que no es posible realizar la adición/eliminación del rol ya que no se pudo obtener la dependencia asociada a la vinculación seleccionada:
![desvinculacion-fallida](https://github.com/udistrital/planeacion_cliente/assets/82072560/460ebe29-7e5a-434c-9ad0-cc81fe39cac2)

**Comment by ccmendezt** [comment]
## Evidencias - Avance Adición de rol de ASISTENTE_PLANEACION 
### 13/06/2024 - 16:25

Se modificó el módulo de gestión de parámetros para obtener el correo de la OAP de los parámetros registrados en dicho módulo. Ahora, en lugar de tener quemado el correo de la OAP, se registra en el módulo de parámetros bajo el código de abreviación denominado "CORREO_OAP", dicho código de abreviación no se podrá modificar una vez se cree y tampoco será posible eliminar dicho parámetro:

![gestion-parametros](https://github.com/udistrital/planeacion_cliente/assets/82072560/8fd383db-3432-47be-8f99-002786e4b92d)

- Con el parámetro del correo de Planeacion en el módulo de gestión de parámetros ya es posible obtenerlo en el módulo de gestión de usuarios para realizar las mismas validaciones que antes se hacían con la constante quemada:

![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/d239189c-320a-4e72-bcb5-43fb19e894bf)
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/fef642a5-07e4-4519-92a2-148490973f7d)

- También se obtiene el correo en _planeacion_mid_ tal cual como se hace en _planeacion_cliente_ para realizar las validaciones:

![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/b6ab9d21-2596-498c-a358-19eddd85e940)
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/d9aeafbe-504b-42ea-aac5-a05d9c372288)


Las validaciones tanto en _planeacion_cliente_ como en _planeacion_mid_ se hacen exactamente igual a como se mostró anteriormente en los comentarios de esta issue.

Se agregaron pop ups informativos para que en caso de que no encuentre dicho parámetro, se comunique con computo@udistrital.edu.co:

**- Validación planeacion_cliente:**
![validacion-cliente](https://github.com/udistrital/planeacion_cliente/assets/82072560/7ef92131-4156-48fe-a032-ed17278ef814)

En la anterior prueba funcional se muestra que cuando NO obtiene el parámetro con CodigoAbreviacion=CORREO_OAP lanza un pop-up que imposibilita la vinculación/desvinculación de un rol, para mostrar dicha funcionalidad se buscó un parámetro con un código de abreviación similar, pero adicionándole un número para que no encontrara registros desde planeacion_cliente.

**- Validación planeacion_mid:**
![validacion-back](https://github.com/udistrital/planeacion_cliente/assets/82072560/1988aae7-c4b9-40de-9798-41eb06b45d6d)

En la anterior prueba funcional se muestra que cuando NO obtiene el parámetro con CodigoAbreviacion=CORREO_OAP lanza un pop-up que imposibilita la vinculación/desvinculación de un rol, para mostrar dicha funcionalidad se buscó un parámetro con un código de abreviación similar, pero adicionándole un número para que no encontrara registros desde planeacion_mid.

**- Vinculacion/Desvinculación exitosa:**
![vinculacion-desvinculacion-exitosa](https://github.com/udistrital/planeacion_cliente/assets/82072560/6974ecd5-a9d4-4efc-a71e-54fa4cdceb01)
