### ISSUE TITLE
Realizar prueba de escritorio desde la creación del formato del plan hasta la formulación de plan de acción de funcionamiento en una unidad.

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#112]
Se debe realizar una prueba de escritorio donde se realice el proceso completo de la formulación de un plan de acción de funcionamiento, la issue debe cumplir con los siguiente requerimientos:

- [x] Crear un formato de un plan de acción de funcionamiento, realizar acción de creación, edición y eliminar para la verificar que el proceso se encuentra bien.
- [x] Formular un plan de acción desde cero a un unidad y una vigencia, realizar acción de creación, edición y eliminar para la verificar que el proceso se encuentra bien. (armonizar, actividades, identificación y culminación del plan)
- [x] Documentar los bug, errores y funcionalidad correcto de los módulos

**Comment by brayaned** [comment]
Se da inicio a la issue.

**Comment by brayaned** [comment]
1. Se encontró un error en el componente de construcción, mas específicamente el componente editar_dialog. Se presentaba conflicto al momento de editar ya sea un plan o un nivel de ese plan. Este conflicto consistía en no poder guardar después de realizar cambios en el componente. **Este error ya fue solucionado y el componente esta 100% funcional**
2. Hay otro error al momento de realizar la formulación de un plan. Al momento de guardarse actividades de este plan no se esta mostrando las actividades que ya fueron agregadas en la tabla resumen. Los información si se esta guardando y trayendo del backend pero la tabla no se muestra.

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
