### ISSUE TITLE
Ajuste de pendientes para que el rol Planeación pueda acceder en el monolito

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1124]
Se requiere realizar el cambio https://github.com/udistrital/planeacion_cliente/issues/1048  para el monolito.

**Especificaciones técnicas**

1. El desarrollo se debe aplicar en el monolito.
2. Actualmente desde solo se puede acceder a "Pendientes" por el rol jefe_dependencia se rquiere que el rol de planeacion también pueda acceder.

**Sub Tareas**

- [x] Habilitar la opción ver planes pendientes de seguimiento y formulación (por pasar a plan verificado) para el rol de planeacion.
- [x] Pruebas funcionales en el monolito

**Criterios de aceptación**

- [x] Documenta la issue de manera completa.
- [x] Se verifica la funcionalidad.

**Requerimientos**

- No presenta.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by C0C045** [comment]
# Pendientes para rol PLANEACION
Se implementó el correcto funcionamiento del módulo de pendientes para el rol de PLANEACION, tal cuál que así:

**Prueba Funcional:**
![PendientesMonoito](https://github.com/udistrital/planeacion_cliente/assets/55455142/61d30ce5-b5cb-4691-894c-426c7eb3c2de)

**Comment by C0C045** [comment]
# PR
planeacion_cliente: https://github.com/udistrital/planeacion_cliente/pull/1131
