### ISSUE TITLE
Creación de la funcionalidad CRUD para la identificación de los docentes 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#113]
Se debe realizar la funcionalidad CRUD (post, Get, Put , Delete) para el componente de la identificación de los docentes desarrollado, la issue debe cumplir con los siguientes requerimientos:

- [x] Desarrollar la funcionalidad Post para la identificación de los docentes semejante a la identificación de recursos y contratistas.
- [x] Desarrollar la funcionalidad Get para la identificación de los docentes semejante a la identificación de recursos y contratistas.
- [x] Desarrollar la funcionalidad Put para la identificación de los docentes semejante a la identificación de recursos y contratistas.
- [x] Desarrollar la funcionalidad Delete para la identificación de los docentes semejante a la identificación de recursos y contratistas.

**Comment by ndmc98** [comment]
Se dio inicio a la issue el 10/11/2021

**Comment by ndmc98** [comment]
- Se realizaron pruebas sobre las funcionalidades de GET y PUT existentes en el MID para la identificación y se validó para el caso de Docentes, por lo cual no se necesitó su creación
- El método POST es utilizado directamente del CRUD. Por lo cual no se hace creación.
- Se crea el método DELETE.

**Comment by ndmc98** [comment]
Se hace Pull Request y se finaliza la issue

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
