### ISSUE TITLE
Pruebas funcionales monolito PT2

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1133]
Se requiere realizar continuar con las pruebas completas de todos los módulos de SISGPLAN, teniendo en cuenta la solución y hallazgos de bugs encontrados en #1067 y #1115 .

**Especificaciones técnicas**

1. Continuar con las pruebas funcionales deben cubrir todos los desarrollos hasta hoy (10/06/2024).
2. Se deben tomar como guía las pruebas realizadas por los desarrolladores en local en cada implementación.
3. El documento de pruebas debe especificar el estado en el que se encuentra el desarrollo, si se valida o no su funcionamiento y las observaciones correspondientes.
4. Tener encuenta los usuarios:
- pruebasoas1 - asistente_planeacion
- pruebasplaneacion - planeacion
- unidadtest - jefe_dependencia
- unidadtest2 - asitente_dependencia
5. Se deben probar solamente los desarrollos, las tareas de análisis o documentación no se tienen en cuenta.
6. Tener en cuenta el diagrama de estados: https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EapOYSf6DV5OpY_6uS7AXIkBLrxapQdD9iheXN88g8Hilg?e=XVQhNQ
7. Se trata de hacer un compendio de todas las pruebas realizadas hasta la fecha en un documento y validar su funcionamiento.
8. Adicional al documento que se debe presentar con las pruebas, se requiere realizar una anotación y seguimiento en forma de comentarios en este issue, de tal forma que se evidencien las pruebas realizadas en cada desarrollo y si aprueban o no. Tomar como guía: https://github.com/udistrital/sga_documentacion/issues/42
9. Carpeta para pruebas funcionales: https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EvgM4KowvOBKjdXD3aFLGV0BGcATolW8LorkydQUQnYMuA?e=MZjaiw

**Sub Tareas**

- [x] Realizar pruebas funcionales en ambiente de pruebas - SISGPLAN.
- [x] Seguimiento de pruebas funcionales en el issue.
- [x] Corrección de errores

**Criterios de aceptación**

- [x] Se presenta un documento con pruebas de todo el sistema.
- [x] Se presenta el seguimiento de las pruebas realizadas en el issue, asociadas a cada desarrollo.
- [x] Se presenta documento con errores corregidos

**Requerimientos**

- No presenta.

**Dependencias**

- planeacion_cliente.
- planeacion_mid.
- planes_crud.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
# RESULTADO PRUEBAS FUNCIONALES #

**Comment by ccmendezt** [comment]
## Evidencias - Pruebas funcionales monolito PT2
### 17/06/2024 - 19:40

En el siguiente enlace se encuentra una página con las pruebas funcionales realizadas:
https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ETwDpgZ4HwVFmdijMR4wvTMB8Cequ_A8VE1VPeEsKKT09A?e=C28R7y

Se realizaron en total 87 pruebas funcionales para el proceso de formulación y seguimiento principalmente, aunque también se revisó el proceso de evaluación. Dentro de las pruebas se encontraron algunos errores que se solucionaron en los Pull Request.

## Commits/Pull Request asociados a Issue
**- planeacion_cliente:** https://github.com/udistrital/planeacion_cliente/pull/1153
