### ISSUE TITLE
Optimización notificaciones

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1135]
De acuerdo con el listado de mejoras incluido en la [documentación de Notificaciones internas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EdixQ978d0hFgJi-psItfw8B1HgCUT9vVDjo4hAqkWQ5qg?e=D3LvW5), se requiere realizar su implementación a nivel de MicroFrontends.

**Especificaciones Técnicas**

1. Actualmente, el servicio de notificaciones requiere actualizar la lista de mensajes cuando el usuario solicita obtener las notificaciones, por lo que los tiempos de respuesta son altos dependiendo de la cantidad de notificaciones. Para mejorar esto, se pueden buscar alternativas que aceleren la respuesta. 

2. Cuando se envía una notificación, esta no se puede ver en tiempo real, por lo que es necesario recargar la página para solicitar y obtener la lista actualizada de notificaciones. 

3. Se requiere almacenar la lista mensajes en una base de datos. Se debe explorar la posibilidad de almacenar dicha información en parametros_crud o documentos_crud. Se debe tener en cuenta que debe ser un desarrollo global ya que los sistemas que implementen notificaciones internas deberán tener sus propias plantillas de mensajes.

**Sub Tareas**

- [x] Mejora proceso de consulta de notificaciones por usuario.
- [x] Persistencia de plantillas de mensajes en BDs.

**Criterios de aceptación**

- [x] La consulta de notificaciones en el sistema se hace de forma rápida.
- [x] Las plantillas de los mensajes de notificaciones se almacenan en una BD de forma global.

**Requerimientos**

- [x] Completar issue #1090 .

**Dependencias**

- microfrontends planeacion.
- notificaciones_mid.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Para el Almacenamiento de la lista de mensajes, se guardó la información en parametros_crud de la siguiente manera:

- area_tipo:
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/3f260621-3ece-4e60-bc86-c52b94c997ef)

- tipo_parametro:
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/85e4a7ba-7759-45ec-ae95-3c237a42b5ba)

- parametro (se incluye un único parametro para las notificaciones asociadas a planeación - SISGPLAN):
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/126377bc-a3ff-4744-9724-3020e1c37fab)

- parametro_periodo (lista de notificaciones):
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/9fa526cc-95a7-458d-80eb-7c2dcfeedf28)

Se añade el script el cúal sirve para insertar data en parametro_periodo unicamente para notificaciones en SISGPLAN (ParametroId) y Periodo académico 2024-2 (PeriodoId), considerando como datos de entrada la lista de plantillas, en donde cada plantilla corresponde al campo:'valor' (json) en la tabla: 
[script insertar plantilla notificaciones.zip](https://github.com/user-attachments/files/15825463/script.insertar.plantilla.notificaciones.zip)

Tener en cuenta que si se quiere utilizar el script para otros escenarios, revisar el campo 'valor', ParametroId y PeriodoId los cuales se quieren asociar.

**Comment by diegobauto** [comment]
Se realiza modificación del almacenamiento de las notificaciones, de acuerdo a reunión sobre "Revisisión aspectos de Notificaciones Internas", lo cual quedo de la siguiente manera:

parametros_crud:
- area_tipo: 
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/74b331f1-9682-4096-a68d-3812ee6bca04)

- tipo_parametro (hace referencia a las plantillas para el sistema de planeación - SISGPLAN):
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/30ad2096-a483-44a4-ac08-f1b9405258e3)

- parametro (contiene la lista de notificaciones):
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/1219ce94-e07a-4660-813c-0d6eafbb018d)

- parametro_periodo (contiene los metadatos en el campo valor: el mensaje y los destinatarios):
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/c018df14-9baf-4b95-a9da-839eb5949016)

Se incluye modificación del script perteneciente las plantillas para SISGPLAN: 
[script insertar plantilla notificaciones.zip](https://github.com/user-attachments/files/15845540/script.insertar.plantilla.notificaciones.zip)

**Comment by a52290451** [comment]
Subir estado final del issue, para su cierre.

**Comment by diegobauto** [comment]
Se realiza modificación para registrar mensajes por lotes de acuerdo a la documentación de AWS: [Agrupación en lotes de mensajes de Amazon SNS](https://docs.aws.amazon.com/es_es/sns/latest/dg/sns-batch-api-actions.html) 

Esto permite mejorar los tiempos, los cuales se realizó un promedio para cada cierta cantidad de mensajes en una cola: [Pruebas funcionales - Registro por lotes (tiempos)](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EXmrGQO4he9ArMI5bRtjv_gBHUJJ--Z9mON-gYos2bcTCg?e=3SpyTP)
