### ISSUE TITLE
Reformulación de planes de acción - Persistencia de Datos

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1136]
Se requiere implementar la persistencia de datos para el submódulo de reformulación de planes de acción de tal forma que las solicitudes de reformulación y documentos asociados se guarden en BDs y puedan ser cargados de forma transversal en la tabla de solicitudes de reformulación para el Jefe y Asistente de planeación.

**Especificaciones técnicas**

- Se debe guardar información relacionada con la solicitud de reformulación de tal forma que pueda ser cargada en la vista de solicitudes de reformulación asociada al Jefe y Asistente de planeación.
- Toda la información capturada en el formulario de reformulación debe ser alamacenada.
- El/Los documentos cargados como evidencia para la reformulación deben ser almacenados en nuxeo a través del API gestor_documental_mid, este devuelve un ID el cual debe ser registrado en la BD de sisgplan.
- Se debe proponer la forma en la que la información será almacenada en el modelo de datos actual.
- Si no es posible almacenar la información en el modelo de datos actual, se debe proponer una alternativa/complemento/modificación al modelo de datos actual para almacenar la información correctamente.

**Sub Tareas**

- [x] Propuesta de Modelo de datos para almacenar información de reformulación de planes de acción.
- [x] Ajustes del modelo de datos en BDs mediante planes_crud.
- [x] Creación de lógica en Micro Mids para el almacenamiento y consulta de solicitudes de reformulación.
- [x] Ajustes en MFs para registrar solicitudes de reformulación.
- [x] Ajustes en MFs para mostrar solicitudes de reformulación.

**Criterios de aceptación**

- [x] El modelo de datos de SISGPLAN en nuevas tecnologías permite almacenar información relacionada con la reformulación de planes de acción.
- [x] SISGPLAN permite registrar solicitudes de reformulación en bases de datos.
- [x] SISGPLAN permite consultar solicitudes de reformulación desde las bases de datos.

**Requerimientos**

- [x] Completar Issue #1110 .

**Dependencias**

- micromids de planeación.
- microfrontends de planeación.
- planes_crud.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by felimarod** [comment]
Propuesta
-
Se propone la adición de la siguiente tabla en el modelo de datos para que supla las necesidades de la reformulación:
![image](https://github.com/udistrital/planeacion_cliente/assets/85894335/65d1b8fb-e665-40f3-9840-47bbb7d85880)
La cual estaría ligada a la tabla plan y contendría el id de los archivos de evidencia necesarios

Modelo completo
-
![Modelo completo](https://github.com/udistrital/planeacion_cliente/assets/85894335/871ce082-c768-4406-9b35-9dde314ecb0b)

**Comment by a52290451** [comment]
Observaciones:

1. Corregir el diagrama para que la relación entre reformulación y planes sea uno a muchos.

**Comment by felimarod** [comment]
Ajuste del modelo
-
![planes](https://github.com/udistrital/planeacion_cliente/assets/85894335/2586837e-ecaf-4ab1-8e0d-af49a25bea23)

**Comment by felimarod** [comment]
Creación de el tipo_parametro en parametros_crud
-
![image](https://github.com/udistrital/planeacion_cliente/assets/85894335/05ce68a7-facb-401f-b886-a5809a597ca8)

Creación de los estados:
- Estado reformulación aprobada:
  ![image](https://github.com/udistrital/planeacion_cliente/assets/85894335/dbfab21c-4a42-4ad6-ae78-983fc7d619b2)
- Estado reformulación rechazada:
  ![image](https://github.com/udistrital/planeacion_cliente/assets/85894335/0dbcc10a-9559-446f-bd59-abf6ff34eeac)
- Estado reformulación :
  ![image](https://github.com/udistrital/planeacion_cliente/assets/85894335/f278fcfc-7d42-44e1-9fd4-4ebce7143421)

**Comment by felimarod** [comment]
Creación del tipo de documento para la reformulación
-
![image](https://github.com/udistrital/planeacion_cliente/assets/85894335/dd14b885-7ec1-4f5c-b3fe-9de8c0930c28)

**Comment by a52290451** [comment]
Quedan pendientes pruebas funcionales

**Comment by felimarod** [comment]
Vista con el rol de Unidad
-
[Grabación de pantalla desde 2024-06-17 21-50-04.webm](https://github.com/udistrital/planeacion_cliente/assets/85894335/eb8313d2-ba1b-4dd2-8db2-05911124037d)

Vista con el rol de Planeacion
-
[Grabación de pantalla desde 2024-06-17 21-51-23.webm](https://github.com/udistrital/planeacion_cliente/assets/85894335/85975e3e-12f4-42ff-8498-3cd3954cdaff)

**Comment by norbeydanilo** [comment]
Falta revisión @a52290451

**Comment by a52290451** [comment]
Se valida y aprueba avance realizado, junto con las pruebas funcionales.

Se da cierre a la actividad.
