### ISSUE TITLE
Funcionalidad de versiona miento de los planes de acción de funcionamiento 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#114]
Se debe desarrollar la funcionalidad para crear un versonamiento de un plan para una vigencia y unidad particular, esta funcion debe realizar la relación entre los planes (campo padre_plan_id) y ajustar el estado del plan versionado, la issue  debe cumplir con los siguientes requerimientos:

- [x] Crear la función para crear el versonamiento del plan con la relación entre versiones y al crear el versonamiento se debe cambiar el estado a "En Formulación"

**Comment by brayaned** [comment]
Se da inicio a la issue.

**Comment by brayaned** [comment]
Se realizó la función en planeacion_mid que hace el versionado del plan enviado, creando una nueva estructura y definiendo de nuevo un estado de "En formulación". Se da por terminado el desarrollo de esta issue.

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
