### ISSUE TITLE
Ajuste Avance de indicador - Seguimiento

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1140]
Se requiere realizar ajuste en el seguimiento de un plan de acción, para que se permita, cuando un denominador sea dinámico, realizar división por cero siempre y cuando el numerador también sea cero. En este caso el resultado debe ser 100% en el avance

**Ejemplo gráfico**

![Image](https://github.com/udistrital/planeacion_cliente/assets/36229498/ab07d107-c3d3-4c90-8c15-bde2219385f9)

![Image](https://github.com/udistrital/planeacion_cliente/assets/36229498/e637ad1f-e7f3-483a-9e8f-88c1dbb2f2be)

En este caso 0/0 indica que para esa meta de 100%, el avance es 100%.

**Mensaje del usuario**

Los planes de acción cuentan con indicadores que se denominan de demanda como las solicitudes que realiza la comunidad a las dependencias. En ocasiones no se reciben solicitudes. En ese caso, la dependencia en el seguimiento debe reportar 0/0 o 0 en el campo numerador y 0 en el denominador. La vigencia anterior, cuando se presentaba esta situación el sistema medía el avance como si se cumpliera al 100%, siempre y cuando en la formulación del plan, el denominador se hubiera parametrizado como variable. Lo cual era correcto y cumplía con la necesidad de no castigar el desempeño de la dependencia. Actualmente, cuando el sistema se enfrenta a esta situación genera un error con el siguiente mensaje "la división por 0 no está permitida". El caso se presentó con el plan de acción 2024 del Centro de Bienestar Institucional, en en el indicador 1 de la actividad 1.

Agradezco su colaboración realizando las gestiones, para que cuando se cumplan la condición de tener un denominador caracterizado como variable en la formulación, en el seguimiento el reporte 0/0 = 100%.

**Sub Tareas**

- [ ] Ajuste de lógica en planeacion_cliente para calcular el avance de un indicador en seguimiento planes de acción, cuan so presenta el caso 0/0.

**Criterios de aceptación**

- [ ] El sistema permite proporcionar un avance de 100% sobre la meta planteada cuando se presenta el caso 0/0 en seguimiento de planes de acción para un indicador particular en una actividad.

**Requerimientos**

- No presenta.

**Dependencias**

- planeacion_cliente

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
@Oscarjaimes1710 por favor actualizar avance

**Comment by Oscarjaimes1710** [comment]
Se hace el ajuste Respectivo del calculo cuando los valores de numerador y denominador son 0 dando como resultado el 100% sin afectar ni modificar el numerador ni denominador acumulado. 
![Captura de pantalla 2024-06-20 a la(s) 5 22 16 p  m](https://github.com/udistrital/planeacion_cliente/assets/145817817/5febd2e9-2ed4-45e7-ae00-a8a704867b98)
![Captura de pantalla 2024-06-20 a la(s) 5 22 25 p  m](https://github.com/udistrital/planeacion_cliente/assets/145817817/32f1fc7b-f4be-4aa3-9fda-b4e3f0cb4ffc)

Así como se muestra en la imagen.
