### ISSUE TITLE
Ajuste de numeración en actividades - Formulación de planes de acción.

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1142]
Se requiere implementar corrección en rama alternativa "Hotfix" y realizar merge directamente en master, de forma tal que se ajuste la numeración de actividades en la formulación de un plan de acción, para que cuando se elimine una actividad, la numeración de las actividades restantes se reinicie.

**Mensaje por parte del usuario**

De manera atenta solicitamos su colaboración respecto a la formulación del Plan de Acción anual en la plataforma SISGPLAN, dado que esta no permite eliminar las actividades cargadas, únicamente las inactiva; de igual manera la información cargada se refleja en las versiones siguientes, lo cual ocasiona que las actividades no queden numeradas en orden, sino que haya que adicionarlas posterior a las que están inactivadas. Esto genera que la información se vea desordenada y de la idea de que son más actividades que las que realmente están proyectadas (se adjunta pantallazo).
Por lo anterior, solicitamos revisar la posibilidad de ajustar esta situación dentro de la estructura de la plataforma, y así para actualizar correctamente el Plan de Acción anual.

**Imagen Guía**

![Image](https://github.com/udistrital/planeacion_cliente/assets/36229498/ad2f8b24-5f2c-4b75-abc8-f5f1047c058c)

**Sub Tareas**

- [ ] Reinicio de numeración en actividades - Formulación de planes de acción.

**Criterios de aceptación**

- [ ] Las actividades en la formulación de un plan de acción se visualizan correctamente, sin importar que se eliminen actividades del mismo.

**Requerimientos**

No aplica

**Dependencias**

- planeacion_cliente

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
@Oscarjaimes1710 actualizar estado de la actividad.

**Comment by Oscarjaimes1710** [comment]
Issue completamente terminada y cargado el pr para su respectiva revisión, Se añadió un index de conteo de la cantidad de actividad y no el index o posición por defecto de cada actividad como estaba implementado anteriormente.
