### ISSUE TITLE
Implementación de pruebas Unitarias - Monolito

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1148]
Se requiere completar esquema de pruebas unitarias en planeacion_mid, de forma tal que se cubran tanto las antiguas como nuevas funcionalidades en el sistema. Adicionalmente, se debe corregir pipeline de despliegue para que las pruebas unitarias se ejecuten automáticamente en cada despliegue.

**Especificaciones técnicas**

- Para la realización de pruebas Unitarias se requiere emplear las especificaciones señaladas en [Lineamientos](https://github.com/udistrital/lineamientos_oas).
- Las pruebas unitarias deben cubrir todos los controladores desarrollados en planeacion_mid
- Se deben ejecutar en local y comprar su funcionamiento.
- Se debe corregir el pipeline de despliegue en pruebas y producción, para que se ejecuten automáticamente en cada despliegue.

**Sub Tareas**

- [x] Desarrollo de pruebas unitarias en planeacion_mid.
- [x] Ajuste de pipeline de despliegue con pruebas unitarias.

**Criterios de aceptación**

- [x] planeacion_mid cuenta con pruebas unitarias.
- [x] Cuando se realiza un despliegue de planeacion_mid, se ejecutan automáticamente las pruebas unitarias.

**Requerimientos**

No aplica

**Dependencias**

- planeacion_mid

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by felimarod** [comment]
Realizados 77 test de 85 enpoints(aprx 91%) en https://github.com/udistrital/planeacion_mid/tree/feature/pruebas-unitarias

**Comment by a52290451** [comment]
Queda pendiente despliegue en ambiente de pruebas, con pruebas unitarias automáticas en peticiones GET.

Las peticiones POST, PUT y DELETE se inhabilitan para no afectar ni crear información de prueba y, por ende, los entornos.

**Comment by a52290451** [comment]
Se requiere evidencia de ejecución de pruebas unitarias en local.

**Comment by felimarod** [comment]
Dentro del archivo [test/controllers/pruebas.txt](https://github.com/udistrital/planeacion_mid/blob/feature/pruebas-unitarias/tests/controllers/pruebas.txt) se encuentran las pruebas ejecutadas

**Comment by a52290451** [comment]
Queda pendiente, análisis final de pruebas unitarias y aceptación PR en develop.

**Comment by a52290451** [comment]
Se requiere corrección en el manejo de errores.

**Comment by felimarod** [comment]
También se encontró una incongruencia con respecto a los endpoints que se encuentran en el swagger y los que se encuentran como tal en los controladores, por ello se anotaron los que estaban definidos en los controladores

En el controlador de _formulación_ se encontró un endpoint llamado _/get_rubros_ el cual llama a un servicio _PlanCuentasService_:
1. El endpoint no esta siendo consumido en el cliente
2. El servicio PlanCuentas no esta desplegado en pruebas
Por los puntos anteriores, se había quitado el endpoint pero se volvió a poner para no tener que actualizar el swagger
