### ISSUE TITLE
Optimización Notificaciones (PARTE 2)

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1149]
De acuerdo con el listado de mejoras incluido en la [documentación de Notificaciones internas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EdixQ978d0hFgJi-psItfw8B1HgCUT9vVDjo4hAqkWQ5qg?e=D3LvW5), se requiere **Continuar** con su implementación a nivel de MicroFrontends.

**Especificaciones Técnicas**

1. Actualmente, el servicio de notificaciones requiere actualizar la lista de mensajes cuando el usuario solicita obtener las notificaciones, por lo que los tiempos de respuesta son altos dependiendo de la cantidad de notificaciones. Para mejorar esto, se pueden buscar alternativas que aceleren la respuesta. 

2. Cuando se envía una notificación, esta no se puede ver en tiempo real, por lo que es necesario recargar la página para solicitar y obtener la lista actualizada de notificaciones. 

**Sub Tareas**

- [x] Mejora proceso de consulta de notificaciones por usuario.
- [x] Actualización en tiempo real de notificaciones.

**Criterios de aceptación**

- [x] La consulta de notificaciones en el sistema se hace de forma rápida.
- [x] Las notificaciones en el sistema se actualizan en tiempo real.

**Requerimientos**

- [x] Completar issue #1090 .
- [x] Completar issue #1111 .
- [x] Completar issue #1135 .

**Dependencias**

- microfrontends planeacion.
- notificaciones_mid.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
- [ ] Se requiere realizar un listado de los pasos a seguir para despliegue en producción de notificaciones.

**Comment by diegobauto** [comment]
Listado de los pasos a seguir para despliegue:
- [ ] Desplegar  notificacion_mid, no se requiere cambios en el swagger
- [ ] Desplegar web_components
- [ ] Copiar link generado en web_components en assets y desplegarlo
- [ ] Desplegar planeacion_cliente
- [ ] Registrar información en la base de datos de parametros_crud en producción

**Comment by diegobauto** [comment]
Se realizan pruebas funcionales de obtención de plantillas: [Pruebas funcionales - Almacenamiento de plantillas](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EVxOyiug_P5GpvcO6QiLP_oBTpE2MPYOCkDyL2mSx4p8aA?e=3XDaFX)

**Comment by diegobauto** [comment]
Para realizar pruebas en https://pruebasplaneacion.portaloas.udistrital.edu.co/#/pages/dashboard, se necesitan modificaciones en los siguientes usuarios:
utestunidad: Asociar el rol y la vinculación correctamente
pruebasplaneacion: Vincular el tercero
pruebasisgplan: Eliminar uno de los roles que ya presenta (PLANEACION)

**Comment by a52290451** [comment]
Se da cierre a la issue y se continua en #1197 .
