### ISSUE TITLE
Funcionalidad para la construcción  del árbol de versionamiento del plan de acción de funcionamiento 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#115]
Se debe desarrollar la funcionalidad para que se construya el árbol del versiona miento para una vigencia y unidad particular, esta debe consultar todos los planes y establecer el orden de las versión con su respectivo id del plan, la issue debe cumplir con los siguientes requerimientos:

- [x]  La función debe recibir como parámetro la vigencia y la unidad a consultar
- [x] Consultar todos los planes y organizar con el orden de las versiones junto a su id de cada plan 
- [x] Crear el reponse con el body organizado y el id del plan para cada versión

**Comment by brayaned** [comment]
Se dió inicio a la issue el 10/11/2021.

**Comment by brayaned** [comment]
Se realizó la función para la construcción del arreglo de versiones ordenado por el campo padre_plan_id. La función recibe como parámetros la unidad, la vigencia y el nombre del plan para el que se desea armar el arreglo de versiones. No se presentaron problemas en el desarrollo de la issue por lo que  se da por terminado el desarrollo de la tarea.

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
