### ISSUE TITLE
Reformulación de planes de acción - Persistencia de Datos - (PARTE 2)

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1150]
Se requiere FINALIZAR con la implementación de persistencia de datos para el submódulo de reformulación de planes de acción de tal forma que las solicitudes de reformulación y documentos asociados se guarden en BDs y puedan ser cargados de forma transversal en la tabla de solicitudes de reformulación para el Jefe y Asistente de planeación.

**Especificaciones técnicas**

- Se debe guardar información relacionada con la solicitud de reformulación de tal forma que pueda ser cargada en la vista de solicitudes de reformulación asociada al Jefe y Asistente de planeación.
- Toda la información capturada en el formulario de reformulación debe ser alamacenada.
- El/Los documentos cargados como evidencia para la reformulación deben ser almacenados en nuxeo a través del API gestor_documental_mid, este devuelve un ID el cual debe ser registrado en la BD de sisgplan.
- Se debe proponer la forma en la que la información será almacenada en el modelo de datos actual.
- Si no es posible almacenar la información en el modelo de datos actual, se debe proponer una alternativa/complemento/modificación al modelo de datos actual para almacenar la información correctamente.

**Sub Tareas**

- [x] Ajustes en MFs para registrar solicitudes de reformulación.
- [x] Ajustes en MFs para mostrar solicitudes de reformulación.

**Criterios de aceptación**

- [x] SISGPLAN permite registrar solicitudes de reformulación en bases de datos.
- [x] SISGPLAN permite consultar solicitudes de reformulación desde las bases de datos.

**Requerimientos**

- [x] Completar Issue #1110 .
- [x] Completar Issue #1136 .

**Dependencias**

- micromids de planeación.
- microfrontends de planeación.
- planes_crud.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
@felimarod por favor actualizar estado de la actividad.

**Comment by norbeydanilo** [comment]
Documentar avance @felimarod

**Comment by norbeydanilo** [comment]
Documentar issue @felimarod 
Revisar para poder dar el cierre @a52290451

**Comment by felimarod** [comment]
- Se agrega la aprobación desde la tabla de reformulación con el rol de planeacion
- Se terminan los detalles de estilos
- Se cambian textos en etiquetas
- Se corrigen pequeños errores en el flujo de la reformulación
- Se terminan de agregar los estados de las reformulaciones
- Se cambiaron los nombres de los codigos de abreviacion para que quede con '-SP' al final
  Esto afecta a seguimiento-mid

**Comment by felimarod** [comment]
PR's asociadas

**Comment by a52290451** [comment]
Queda pendiente corregir error encontrado y realizar prueba.

**Comment by felimarod** [comment]
Al intentar hacer una reformulación nueva, no se agrega la evidencia asociada a la reformulación, el error encontrado es:

![Image](https://github.com/udistrital/planeacion_cliente/assets/85894335/0f62dbd0-a961-46bd-9a52-1ce93490a1fb)

Se asocia con el tipo de documento que se creo especificamente para las reformulaciones, ya que fue en donde se agrego el "Workspace"


![Image](https://github.com/udistrital/planeacion_cliente/assets/85894335/2089f351-9f62-49f0-9db5-4500b2a322d4)

Se debe verificar que el espacio se haya creado para así poder realizar las pruebas funcionales completas

**Comment by a52290451** [comment]
Se retraza despliegue de Reformulación en ambiente de pruebas hasta desplegar release en ambiente de producción.

Actualmente, se presenta un cambio a nivel de base de datos **planes_crud** la cual se encuentra compartida con el monolito, por lo que no es posible realizar su despliegue en este momento.

**Comment by a52290451** [comment]
@felimarod Por favor adjuntar pruebas funcionales

**Comment by felimarod** [comment]
Flujo de reformulación con el rol de planeacion:

https://github.com/user-attachments/assets/30a5103e-c2f3-478e-9ad8-6c8f05bf22d1

Flujo de reformulación como unidad:

https://github.com/user-attachments/assets/4251605c-eb43-4cb3-96ab-8f43fcc5431f

Queda pendiente volver a poner el tipo de documento adecuado, esto teniendo en cuenta el comentario: https://github.com/udistrital/planeacion_cliente/issues/1150#issuecomment-2219308694

**Comment by a52290451** [comment]
Queda pendiente subida en ambiente de pruebas.
