### ISSUE TITLE
Corrección de errores encontrados en monolito

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1151]
Se requiere corregir los errores encontrados pruebas completas de todos los módulos de SISGPLAN, teniendo en cuenta la solución y hallazgos de bugs encontrados en #1067 , #1115 y #1133 .

**Especificaciones técnicas**

1. Tener encuenta los usuarios:
- pruebasoas1 - asistente_planeacion
- pruebasplaneacion - planeacion
- unidadtest - jefe_dependencia
- unidadtest2 - asitente_dependencia
2. Tener en cuenta el diagrama de estados: https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EapOYSf6DV5OpY_6uS7AXIkBLrxapQdD9iheXN88g8Hilg?e=XVQhNQ
3. Se deben corregir los errores en el monolito
**Sub Tareas**

- [x] Corrección de errores según los hallazgos en las pruebas funcionales.
- [x] Pruebas de funcionamiento después de realizar la corrección

**Criterios de aceptación**

- [x] Se presenta un documento con pruebas de todo el sistema con pruebas corregidas con un color verde en los comportamientos corregidos.
- [x] Se suben los cambios con las correcciones esperadas.
- [x] Se prueba el comportamiento corregido

**Requerimientos**

- No presenta.

**Dependencias**

- planeacion_cliente.
- planeacion_mid.
- planes_crud.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Oscarjaimes1710** [comment]
Solución bug visualización de gráfica circular y valor de avance general.

**Comment by felimarod** [comment]
Se solucionó la petición 401 en GestorDocumentalService

**Comment by Oscarjaimes1710** [comment]
Ajuste Gráfico del titulo de la Gráfica circular.

**Comment by C0C045** [comment]
# Pruebas Funcionales de actividades extra por desarrollar
- Restringir para que planeación solo pueda visualizar los planes en seguimiento y formulación por ser verificados (Por el jefe de unidad), lo que quiere decir que no pueden modificar su estado ya sea de manera individual o masiva.
![PlaneacionAprobacion](https://github.com/udistrital/planeacion_cliente/assets/55455142/cedd9a79-edc5-44f9-9850-380e42ad8c2d)

- Revisar que siempre una actividad este armonizada
![Armonizar](https://github.com/udistrital/planeacion_cliente/assets/55455142/bc872c33-2bae-440c-845c-a968a8dd7708)

- La observación cuantitativa, en la tabla de seguimiento puntual para una actividad debe quedar con 5 líneas de visualización por fila máximo, si no adecuarse al tamaño del contenido.
![Textarea](https://github.com/udistrital/planeacion_cliente/assets/55455142/245a85eb-bc0c-4444-a540-c0db3b80dd49)

**Comment by C0C045** [comment]
# PR
cliente: https://github.com/udistrital/planeacion_cliente/pull/1169

**Comment by C0C045** [comment]
# Inconsistencias encontradas en Monolito

1. Si voy a crear un plan en el módulo de construcción y selecciono que el plan no se establece como plantilla, entonces, me dice que el plan se creo correctamente, sin embargo, esto no es cierto, ya que no lo vemos presente en la lista de planes:
![CrearPlan](https://github.com/udistrital/planeacion_cliente/assets/55455142/d71b5a62-131c-407c-9f3b-7b9edcb61132)

2. Existen planes que pueden estar mal generados, ya que al generar sus indicadores; estos pueden estar mal estructurados, por ende, al intentar generar una actividad en el plan, esta dice que se genera, pero realmente no se crea:
![Actividad falla](https://github.com/udistrital/planeacion_cliente/assets/55455142/92aa193d-3ea0-4e79-a43f-433e70f7c31c)

3. Por otro lado, no es posible inactivar actividades en planes nuevos, esto se puede deber a un tema de estructura interna de los planes:
![Inactivar](https://github.com/udistrital/planeacion_cliente/assets/55455142/832b8c5b-df5c-4311-abaf-7b8ab24c2d9e)

**Comment by C0C045** [comment]
# Arreglo del filtro en tabla consulta
PR: https://github.com/udistrital/planeacion_cliente/pull/1207

**Comment by C0C045** [comment]
#Acción de Lupa desde Consulta hasta Formulación:
**Prueba Funcional:**
![Lupa Consulta Formulacion](https://github.com/udistrital/planeacion_cliente/assets/55455142/22b08b05-71b4-4d4d-bd83-3a541f01c6ec)

**Comment by C0C045** [comment]
# Acción de Lupa desde Pendientes a Formulación
**Prueba Funcional:**
![PendienteAFormulacion](https://github.com/udistrital/planeacion_cliente/assets/55455142/94c2135b-3b90-4f14-94d7-dcf517473dad)

**Comment by C0C045** [comment]
# Quitar opción 'establecer como plantilla'
Indagando más en el uso de esta opción, se encontró que algunos tipos de plan si son posibles crearlos sin establecerlos como plantilla, tal es el caso del 'Plan de Desarrollo'. Por ende, es pertinente dejar la opción para que estos tipos de planes mantengan su lógica.

**Prueba Funcional:**
![Plan de Desarrollo](https://github.com/udistrital/planeacion_cliente/assets/55455142/16d26c68-f9c5-4807-87b6-fad4375d4edf)

**Comment by C0C045** [comment]
# Aviso de Carga de Unidades en Formulación
Este 'pop up' no es posible implementarlo con éxito, ya que en sí la obtención de los planes no es la que se demora, si no que es la asignación de la unidad en el formulario y al ser esta una función propia de Angular no es posible agregar lógica Swal interna.

**Comment by C0C045** [comment]
# PR
cliente: https://github.com/udistrital/planeacion_cliente/pull/1209

**Comment by C0C045** [comment]
# Consulta Seguimiento Repite los Planes - FIX
**Pruebas Funcionales:**
![PlanesConsultaSeguimiento](https://github.com/udistrital/planeacion_cliente/assets/55455142/7c4f9321-c114-4013-a106-d8f0d4d0d851)

**Comment by C0C045** [comment]
# Pendientes Seguimiento Estado - FIX
**Pruebas Funcionales:**
![PendientesSeguimientoArreglado](https://github.com/udistrital/planeacion_cliente/assets/55455142/469f0c42-bff2-4f54-8566-4b4969dbc3b5)

**Comment by C0C045** [comment]
# PR
cliente: https://github.com/udistrital/planeacion_cliente/pull/1214
