### ISSUE TITLE
Diagramas Arquitectura de la Información

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/planeacion_cliente#1154]
Se requiere realizar la generación de los diagramas de Arquitectura de la Información del sistema SISGPLAN que se encuentra funcional en producción para garantizar la documentación que se está levantando y tener de una forma más inmediata y sencilla una visual general sobre el sistema.

**Sub Tareas**

- [ ] Realizar la construcción del diagrama de arquitectura de la información a modo gráfica y componentes.
- [ ] Realizar la construcción del diagrama de arquitectura de la información a mapa "de conceptos" desde la vista de la página web del sistema.

**Criterios de aceptación**

- [ ] Diagrama de Arquitectura gráfico general.
- [ ] Diagrama de Arquitectura "conceptual".

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by norbeydanilo** [comment]
@BikerMetalHead Ubicar enlaces de los dos diagramas.

**Comment by BikerMetalHead** [comment]
Se adjuntan los diagramas de arquitectura en su versión V1 y V2. En donde la V1 hace referencia a la versión para el usuario final y la V2 para el equipo de trabajo; según indicaciones recibidas 
[Arquitectura_V1](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EQp3EiXPcp9Gt1PmNxlktaEBbpOzgZCDxQV2UIvKBbZ1Vg?e=MWQwci)
[Arquitectura_V2](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/ES11L2ksBb5Ok4C_qQQj_f0BSF-w8FB0facbcimGPnAtfA?e=jroU4p)

**Comment by BikerMetalHead** [comment]
Se realiza correcciones al diagrama de arquitectura de información, aplicando las sugerencias dadas por el equipo.
[diagrama_arquitectura_v3 ](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EQ7jxnTpG8tLraxlIT_a4DkBa3DnH3lYUuH_SgTnTldLGg?e=RWFcJn)

**Comment by BikerMetalHead** [comment]
Se realiza correcciones al diagrama de arquitectura de información, aplicando las sugerencias dadas por el equipo.
[diagrama_arquitectura_v4](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EVJf4spfbjNMt9e0p8Bw78YBDL6x-CfRY5EyK3ByAtLctQ?e=ihd0Pe)

**Comment by norbeydanilo** [comment]
Se van ocultar desde el Sistema:

PED:

Seguimiento PED
Evaluación PED

PMEE: TODO

Plan Indicativo:

Seguimiento PI
Evaluación PI

Plan Operativo Anual: TODO

Solicitud de reformulación

Banco de proyectos: TODO

Programación presupuestal: TODO

**Comment by BikerMetalHead** [comment]
Se realizan los ajustes nombrados por el equipo: 

[ArquitecturaSISGPLANV4](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EQZrDCDsnihPordg6N5JrvkBZIoQQZHeQXxp8UJkA1mGLQ?e=GrN0Wa)
