### ISSUE TITLE
Flujo de funcionalidad-interacción del sistema SISGPLAN

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/planeacion_cliente#1155]
Se requiere realizar el flujo (tipo BPMN) a nivel de procesos de lo que contempla el sistema SISGPLAN para tener una documentación más robusta y de fácil entendimiento. 
 
**Sub Tareas**

- [ ] Generar el o los diagramas que representan los flujos respectivos. Debe estar creado bajo un estándar o formalismo para su fácil y entendimiento.

**Criterios de aceptación**

- [ ] Diagrama(s) con el flujo solicitado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by norbeydanilo** [comment]
@BikerMetalHead Ubicar los enlaces que llevan al diagrama que tiene el/los flujo/s.

**Comment by BikerMetalHead** [comment]
Se realizan los diagramas de flujo de los procesos de SISGPLAN en bizagi. Desde el diagrama general hasta los diagramas detallados por proceso y módulos:
[General](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/EUfbh8oG3SpAiSM3LomdldYBUFV0RLY5fFiCdhIzQFmYBA?e=vVs6bC)
[Construcción](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/EYgEFYfiE9hOsjuMPfIUSwABuqc3sqY2-iir4Gdo17m4Tw?e=73tB6T)
[Formulación](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/Ea9fV3oCAa9Ih1-V4vo6-KQBpw5wvsJIW__i7OFwp1zmAQ?e=CWuCX7)
[seguimiento](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/Ee2Lui6GGtNHsdEumolV-gEBAbSBxE7UD1FHhX8cmNcazQ?e=Nrcp0E)
[informes](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/Eeiyl4-6qRxEvnJjxQVYJtUBIpDcDc3IwenJa8c_xSPWSw?e=N6Lde7)
[Reformulación](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/Eb1x4G7DkhJKjbCxW4b4L9QBwMlD2CfAekMxR4oYUv8bUQ?e=eclzNm)

**Comment by norbeydanilo** [comment]
Realizar los ajustes y ubicar carpeta aquí, según lo hablado en la sesión de 25/06/24. @BikerMetalHead

**Comment by BikerMetalHead** [comment]
Se realizan ajustes según lo conversado con el equipo. 
[General](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/EUfbh8oG3SpAiSM3LomdldYBUFV0RLY5fFiCdhIzQFmYBA?e=vVs6bC)
[Construcción](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/EZQWg6GEb5BGsmJP2qv0VQQB8FPI1yLOT0iaYpnqre5mDA?e=ksHHTq)
[seguimiento](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/EdXeUhLb5ghLgq2PgtgbDnAB4b4-CJPNG2tKLTq9rwZPQg?e=jfYXcc)
[informes](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/Eeiyl4-6qRxEvnJjxQVYJtUBIpDcDc3IwenJa8c_xSPWSw?e=N6Lde7)
[Reformulación](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/Eb1x4G7DkhJKjbCxW4b4L9QBwMlD2CfAekMxR4oYUv8bUQ?e=eclzNm)

**Comment by BikerMetalHead** [comment]
Se realiza los ajustes conversados con el equipo.

[Diagramas ](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EpW3CnMMKK5HjmUQH6qltUQBsCwnLXFygOiMZNWStg_Z7A?e=JEdovf)
