### ISSUE TITLE
Análisis de formatos de planes de acción de inversión y proyectos de inversión

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/planeacion_cliente#1156]
Se requiere realizar el análisis de los formatos suministrados respecto a los planes de acción de inversión y su relación con los proyectos de inversión con el propósito de levantar un mapa general que permita entender el proceso y el negocio que este involucra: actores (roles), acciones, funcionalidades, etc. La idea es poder identificar aún más éste flujo para poder proyectar con el equipo, y aclarando con el usuario, vistas, funciones, lógicas de desarrollo.

**Sub Tareas**

- [ ] Aclarar el flujo con el concepto de plan de acción y proyecto de inversión, esto es tener en cuenta que un plan de acción se genera en cuánto a seguimiento de forma anual y trimestral, partiendo del proyecto de inversión por cuatrenio, y que la formulación e hace de forma general en el proyecto.
- [ ] Analizar el formato 7900_PEI-PR-008-FR-002 que se emplea para los planes de acción de inversión en la fase de seguimiento.
- [ ] Analizar el anexo que sirve de instrumento para la formulación del proyecto de inversión. Identificar lo que va por ERP, y la información que es útil y alimenta a los planes de acción.
- [ ] La necesidad de establecer el flujo está orientada a aclarar lo que va desde SISGPLAN para proyectos de inversión (programación presupuestal).
- [ ] Revisar el proyecto de resolución de banco de proyectos: [enlace](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EaZWgapAAVtJoinJt1vK98YBPUakRVRRmEX6U5R6XhKt8Q?e=iLnsLb)

**Criterios de aceptación**

- [ ] Documento con análisis y definición de planes de acción de inversión y su relación con los proyectos.
- [ ] Diagrama con flujos, roles, acciones, etc., que ayude a entender el negocio.

**Requerimientos**

El folder con los formatos está en: [carpeta de planes de acción de inversión](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EtAWxQF6yHJClmdfBwSyMkYBNZWi73xlGOeaIcVvdgoh_w?e=gwj7sa)

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by norbeydanilo** [comment]
Se da continuidad de la tarea en el Sprint 11 @BikerMetalHead

**Comment by norbeydanilo** [comment]
Ir documentando @BikerMetalHead

**Comment by BikerMetalHead** [comment]
Se realiza levantamiento de macro procesos de un proyecto de inversión. 

[Macroprocesos](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/ETauiatFUqhJq1_JMLlPB9kB1JGQCfDQTS2NbbW6jFBorQ?e=1e7sMR)

**Comment by norbeydanilo** [comment]
Generar documento con la explicación del proceso de formulación y la participación de programación presupuestal, basándose mayoritariamente en el formato de Plan de Acción documentado. Incluir las dificultades desde el punto del ERP y la definición misma de la Oficina Asesora de Planeación. @BikerMetalHead

**Comment by BikerMetalHead** [comment]
Se genera documento, con un pequeño informe propio, de las actividades adelantadas en el marco del levantamiento de requerimientos para banco de proyectos desde la óptica de SISGPLAN.
[Informe](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EZgbxD2ZUsZGppylQwKZwEABsa5k8YQIEHW-6ELttINqHg?e=GOmxMm)
