### ISSUE TITLE
Ajustar la distribución de menus del cliente 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#118]
Se debe ajustar la distribución del menú en el componente, teniendo en cuenta la siguiente distribución:

- Construcción (igual)
- Plan de Acción 
- Plan de Acción / Funcionamiento/ Formulación (componente actual)
- Plan de Acción / Funcionamiento/ Seguimiento 
- Plan de Acción / Funcionamiento/ Evaluación
- Plan de Acción / Funcionamiento/ Consolidación de del Plan de Acción Anual
- Plan de Acción / Inversión/ Formulación 
- Plan de Acción / Inversión/ Seguimiento 
- Plan de Acción / Inversión/ Evaluación
- Banco de Proyectos/ Formulación 
- Programación Presupuestal / Programación Presupuestal Inicial

La issue debe cumplir con los siguientes requerimientos:

- [x] Ajustar el menú con la distribución mencionada

**Comment by brayaned** [comment]
Se realizó la tarea ajustando el dashboard del cliente, se ajustaron los menús tal como se menciona en la definición de la issue. No se presento ningún problema en el desarrollo por lo que se da por terminado.

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
