### ISSUE TITLE
Estabilización de ambiente de pruebas Microfrontends

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1196]
Se requiere validar el correcto funcionamiento de los MF en ambiente de pruebas junto con su interoperabilidad con los micromids.

**Especificaciones técnicas**

- Los repositorios de los mid son:

1. [planeacion_formulacion_mid](https://github.com/udistrital/planeacion_formulacion_mid)
2. [planeacion_seguimiento_mid](https://github.com/udistrital/planeacion_seguimiento_mid)
3. [planeacion_evaluacion_mid](https://github.com/udistrital/planeacion_evaluacion_mid)
4. [planeacion_reportes_mid](https://github.com/udistrital/planeacion_reportes_mid)
5. [planeacion_arbol_mid](https://github.com/udistrital/planeacion_arbol_mid)

- Los repositorios de los MF son: 

1. [Root](https://github.com/udistrital/planeacion_root_mf)
2. [Utilidades](https://github.com/udistrital/planeacion_utilidades_mf)(Revisar como mostrar la imagen base de SISGPLAN).
3. [Formulacion](https://github.com/udistrital/planeacion_formulacion_mf) 
4. [Seguimiento](https://github.com/udistrital/planeacion_seguimiento_mf)5. [Evaluacion](https://github.com/udistrital/planeacion_evaluacion_mf)
6. [Macroplanes](https://github.com/udistrital/planeacion_macroplanes_mf)
7. [Pendientes](https://github.com/udistrital/planeacion_macroplanes_mf)
8. [Construccion](https://github.com/udistrital/planeacion_macroplanes_mf)

- Todos los MF ya se encuentran desplegados y cuentan con los DNS: https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ETUSQ1JOXG5Jnc9uh3iscfABEl-PJYHvXLEBY9yXz3_Axw?e=mNROD2.

**Subtareas**

- [x] Revisar el funcionamiento e interoperabilidad de las funcionalidades de SISPLAN en la nueva arquitectura
- [x] Se deben realizar pruebas funcionales sobre cada uno de los MF.
- [x] Realizar los ajustes requeridos.

**Criterios de aceptación**

- [x] Se documenta el issue correctamente con las pruebas realizadas.
- [x] Se corrigen los errores presentados.

**Requerimientos**

- [X] Despliegue de los MF en pruebas

**Dependencias**

- Todos los MF de SISGPLAN.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by C0C045** [comment]
# Avance Estabilización
Actualmente se logró enlazar cada uno de los microfrontends en el root, sin embargo, existen las siguientes inconsistencias, en dónde principalmente el CORE desplegado tiene un error de sintaxis, sin embargo, al ejecutarlo en local ese error no existe.

**Error:**
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/aa03ae44-81b1-49e2-8562-bb9f38bd7d00)
**Local:**
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/eff75841-9243-4a64-9c4e-c4b3a2b96c4a)

Por otro lado, cada uno de los microfrontends tienen un error de CORS, en dónde indica que el puerto 4200 no tiene permisos para acceder a ellos.

**Evidencia:**
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/6583dcfb-ff0f-4ef4-b77e-3311379f766e)
