### ISSUE TITLE
Optimización Notificaciones (PARTE 3) Alistamiento Salida a producción.

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1197]
De acuerdo con el listado de mejoras incluido en la [documentación de Notificaciones internas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EdixQ978d0hFgJi-psItfw8B1HgCUT9vVDjo4hAqkWQ5qg?e=D3LvW5), se requiere **Finalizar** con su implementación.

**Especificaciones Técnicas**

1. Se requiere realizar ajuste en el consumo y vista de notificaciones para que se carguen en el cliente hasta un máximo de 40. Si el usuario tiene mas notificaciones en cola, se deben cargar a medida que se revisen las que están en la vista.

2. Cuando se envía una notificación, esta no se puede ver en tiempo real, por lo que es necesario recargar la página para solicitar y obtener la lista actualizada de notificaciones. 

3. Se requiere completar el checklist de salida a producción con las tareas necesarias para su cumplimiento.

**Sub Tareas**

- [ ] Mejora proceso de consulta de notificaciones por usuario.
- [ ] Actualización en tiempo real de notificaciones.
- [ ] Checklist de salida a producción.

**Criterios de aceptación**

- [ ] La consulta de notificaciones en el sistema se hace de forma rápida y con límite.
- [ ] Las notificaciones en el sistema se actualizan en tiempo real.
- [ ] El sistema de notificaciones cuenta con el checklist de salida a producción completo.

**Requerimientos**

- [x] Completar issue #1090 .
- [ ] Completar issue #1111 .
- [x] Completar issue #1135 .
- [ ] Completar issue #1149 .

**Dependencias**

- notificaciones_mid.
- assets

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Listado de los pasos a seguir para despliegue:
- [ ] Desplegar  notificacion_mid, no se requiere cambios en el swagger
- [ ] Desplegar web_components
- [ ] Copiar link generado en web_components en assets y desplegarlo
- [ ] Desplegar planeacion_cliente
- [ ] Registrar información en la base de datos de parametros_crud en producción

**Comment by diegobauto** [comment]
Se realizan pruebas funcionales en la implementación de tiempo real en las notificaciones con websocket: [Pruebas funcionales - Notificaciones websocket](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EZEFJ4tRVCBAjQNH9VmYpPgBU3B8L_iacZ29rGc03ec0Zg?e=mkKLWD)

**Comment by diegobauto** [comment]
Actualmente, la implementación del sistema de notificaciones se ha llevado a cabo utilizando los servicios SNS y SQS de AWS, lo que permite registrar y consultar notificaciones. Sin embargo, para procesar todas las notificaciones asociadas a un usuario, dado que AWS no cuenta con un filtrado interno por cola, se ha optado por recorrer la cola en lotes de 10 mensajes, la cantidad máxima permitida por el servicio. Este proceso implica filtrar los mensajes por el documento del usuario, eliminarlos y, al finalizar, registrar nuevamente las notificaciones.

A pesar de haber implementado mejoras en el sistema, como la eliminación y el registro de notificaciones por lotes para reducir el tiempo de respuesta, al consultar las notificaciones el tiempo es alto.

Al buscar alternativas más eficientes para obtener la lista de notificaciones asociadas a un usuario, se ha encontrado que todas son inviables debido a que el servicio solo permite obtener 10 mensajes por solicitud. Además, las colas funcionan con una estructura FIFO, lo que implica que, para obtener las notificaciones más recientes, es necesario recorrer toda la cola.

**Comment by diegobauto** [comment]
Se añaden dos opciones de lo referente al modelo de datos para notificaciones, se tiene en cuenta prinicipalmente la primera opción debido a que se simplica todo en una colección, por lo que es mas sencillo el registro y consulta de la información:

Opción 1:
![notificaciones1](https://github.com/udistrital/planeacion_cliente/assets/64450601/301ababc-7367-4458-b976-a96cb54bbe4b)

Opción 2:
![notificaciones2](https://github.com/udistrital/planeacion_cliente/assets/64450601/3d793004-425b-4173-b6ca-d605b5b02d6b)
