### ISSUE TITLE
Verificación y actualización de Rubros - Módulo de Formulación - Planes de acción

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1218]
Se requiere realizar la verificación y, de ser requerido, la actualización de información relacionada con Rubros en producción, en el modulo de planes de acción, sub modulo de formulación. Se debe garantizar que la información de Rubros se encuentre actualizada al igual que el salario mínimo y demás información presupuestal que cambia año tras año.

**Aspectos técnicos**

- La información que se consume en el cliente de planeación para hacer los cálculos relacionados con información presupuestal, debe estar actualizada de acuerdo a la vigencia consultada. En caso de no estarla, se debe solicitar una actualización.
- Se debe verificar que los rubros mostrados en ambiente de producción, sean los vigentes y actualizados, año tras años.

**Sub Tareas**

- [x] Verificación y corrección de valores relacionados con información presupuestal para el calculo de salarios año por año.
- [ ] Verificación y corrección de rubros mostrados en el cliente año por año.

**Criterios de aceptación**

- [x] El sistema presenta información actualizada y pertinente para cada vigencia, relacionada con información presupuestal para el calculo de salarios y gastos en la formulación de planes de acción.
- [x] El sistema presenta información actualizada y pertinente para cada vigencia, relacionada con rubros en la formulación de planes de acción.

**Requerimientos**

No aplica

**Dependencias**

- planeacion_mid
- planeacion_cliente

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
@Oscarjaimes1710 se requiere actualizar estado de la actividad y finalizar.

**Comment by Oscarjaimes1710** [comment]
En primera instancia se hacen las debidas comprobaciones que los valores y cálculos estén haciéndose de forma correcta y se concluye que están correctos se procede a hacer la comparación con los valores en producción.

![Captura de pantalla 2024-07-08 a la(s) 12 14 27 p  m](https://github.com/udistrital/planeacion_cliente/assets/145817817/fbbc337d-1a07-428b-98c3-52efb37d1500)

**Comment by Oscarjaimes1710** [comment]
En primera instancia se hacen las debidas comprobaciones que los valores y cálculos estén haciéndose de forma correcta y se concluye que están correctos se procede a hacer la comparación con los valores en producción.

Vigencia 2023.

![Captura de pantalla 2024-07-08 a la(s) 2 41 23 p  m](https://github.com/udistrital/planeacion_cliente/assets/145817817/3e473a53-08ff-4778-98a3-5637e2cd6818)

**Comment by Oscarjaimes1710** [comment]
Se hacen todas las revisiones pertinentes y se encuentra que el funcionamiento es correcto y que los valores y cálculos están bien hechos y funcionando como en producción. 

Se hizo una comparación de el valore item por item pruebas vs producción vs cuadro comparativo.

<img width="1439" alt="Captura de pantalla 2024-07-08 a la(s) 12 53 24 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/14f0ac00-82bd-497e-8660-6a8d80d1b84b">
![Captura de pantalla 2024-07-08 a la(s) 12 53 10 p  m](https://github.com/udistrital/planeacion_cliente/assets/145817817/431ff15f-842d-4fa9-ac88-27193fe865a5)

<img width="641" alt="Captura de pantalla 2024-07-08 a la(s) 6 04 00 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/7e64ef2c-772d-4471-94d0-16d5bf7cac58">

**Comment by Oscarjaimes1710** [comment]
Tipos de Rubros Pruebas Vs Producción.
![Captura de pantalla 2024-07-08 a la(s) 6 14 42 p  m](https://github.com/udistrital/planeacion_cliente/assets/145817817/1091b9bf-0eaa-41da-a6ec-c9ad11e0c01f)

Todo Ok

**Comment by a52290451** [comment]
Se valida y aprueba verificación realizada,

Queda pendiente validación de rubros para 2024 y actualización de los mismos

**Comment by Oscarjaimes1710** [comment]
Prueba del funcionamiento de los nuevos rubros : 

![Captura de pantalla 2024-07-12 a la(s) 8 11 51 p  m](https://github.com/user-attachments/assets/db2ee6b2-be68-4abb-8a3e-bceb3a5a446f)
