### ISSUE TITLE
Implementación de notificaciones en nuevo modelo de datos (Validación DBAs)

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1223]
Se requiere socializar nuevo modelo de datos para Notificaciones a nivel de sistemas con el equipo de DBAs, de acuerdo a los hallazgos realizados en #1197 .También se debe realizar la implementación de un API CRUD que permita conectar con la BD de Notificaciones y conectar dicha API con notificaciones_mid.

**Especificaciones Técnicas**

- Se requiere validar modelo de datos de notificaciones con DBAs para su implementación. En este sentido se debe agendar reunión con los mismos en el menor tiempo posible.
- Se deben realizar las correcciones sugeridas sobre el modelo de datos y realizar su creación he implementación a través de un API CRUD.
- Una vez se tenga el API CRUD listo, se debe conectar con notificaciones_mid para encadenar servicios y que sea transversal su consumo desde los clientes.

**Sub Tareas**

- [x] Validación y corrección de nuevo modelo de datos de notificaciones con DBAs.
- [x] Creación de API CRUD y Base de datos de notificaciones.
- [x] Conexión API notificaciones_mid y notificaciones_crud.
- [x] Pruebas funcionales de servicios de notificación.

**Criterios de aceptación**

- [x] El modelo de datos de notificaciones se encuentra validado y aprobado por el quipo de DBAs.
- [x] Se crea un API CRUD llamado notificaciones_crud de acuerdo al modelo de datos aprobado.
- [x] Se habilitan los servicios de notificaciones mediante la conexión entre notificaciones_mid y notificaciones_crud.
- [x] El servicio de notificaciones a nivel de sistema queda funcional en SISGPLAN.

**Requerimientos**

- No presenta

**Dependencias**

- notificaciones_mid.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Se realiza modificación en modelo de datos, teniendo en cuenta la opción 1 del issue #1197:
![modelo notificaciones](https://github.com/udistrital/planeacion_cliente/assets/64450601/b5814d2b-222a-49c5-8cbd-6a3a179075bc)

**Comment by diegobauto** [comment]
Se realiza modificación de acuerdo a la reunión realizada con DBAs: 
![notificaciones](https://github.com/udistrital/planeacion_cliente/assets/64450601/12b5f2b2-b01d-4b6d-8abf-e2b95d016c52)

**Comment by a52290451** [comment]
@diegobauto actualizar estado de la actividad

**Comment by diegobauto** [comment]
# API CRUD: 

# sistema
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/c8e6ec39-1ab0-4350-b364-127849796163)

[POST]

[Grabación de pantalla desde 08-07-24 09:54:16.webm](https://github.com/udistrital/planeacion_cliente/assets/64450601/8ee70d6a-bdf6-4f9d-8c49-94bf8d7a4beb)

[GET]

[Grabación de pantalla desde 08-07-24 10:16:16.webm](https://github.com/udistrital/planeacion_cliente/assets/64450601/990c7477-a805-439d-8469-974fc70a0ea0)


[PUT]

[Grabación de pantalla desde 08-07-24 09:57:10.webm](https://github.com/udistrital/planeacion_cliente/assets/64450601/2cd902ab-3c7e-4484-ad6c-3dd19a40519c)

[DELETE]

[Grabación de pantalla desde 08-07-24 09:58:53.webm](https://github.com/udistrital/planeacion_cliente/assets/64450601/f5675340-13ed-4ed4-a89c-8d5a169fe6e8)

# tipo_notificacion

[POST]

[Grabación de pantalla desde 08-07-24 10:06:53.webm](https://github.com/udistrital/planeacion_cliente/assets/64450601/e55cd594-dce5-4b14-82d9-e61b41478ad5)

[GET]

[Grabación de pantalla desde 08-07-24 10:10:45.webm](https://github.com/udistrital/planeacion_cliente/assets/64450601/d7cd6f53-453a-4995-891c-45efba66cb9d)

[PUT]

[Grabación de pantalla desde 08-07-24 10:11:31.webm](https://github.com/udistrital/planeacion_cliente/assets/64450601/c098beec-87d4-4cb5-9f37-0f022e9af1ce)


[DELETE]

[Grabación de pantalla desde 08-07-24 10:13:22.webm](https://github.com/udistrital/planeacion_cliente/assets/64450601/ce068dec-e196-4f91-ac85-41a6c943c3c7)

# plantilla

[POST]

[Grabación de pantalla desde 08-07-24 10:18:15.webm](https://github.com/udistrital/planeacion_cliente/assets/64450601/70bedd4a-06b9-4a14-8905-375812b0268c)

[GET]

[Grabación de pantalla desde 08-07-24 10:19:00.webm](https://github.com/udistrital/planeacion_cliente/assets/64450601/9c194ebc-85cb-4e1a-a0e9-4f7ece294efa)

[PUT]

[Grabación de pantalla desde 08-07-24 10:19:41.webm](https://github.com/udistrital/planeacion_cliente/assets/64450601/2972f702-1e4e-441c-b5f4-1d87c0d3ef1f)

[DELETE]

[Grabación de pantalla desde 08-07-24 10:20:27.webm](https://github.com/udistrital/planeacion_cliente/assets/64450601/9fa481fe-a701-4e10-b55a-0bde5e6039c4)

# notificacion

[POST]

[Grabación de pantalla desde 08-07-24 10:32:27.webm](https://github.com/udistrital/planeacion_cliente/assets/64450601/a38bba33-6dfa-499d-9aee-e7fa20acb5ff)

[GET]

[Grabación de pantalla desde 08-07-24 10:33:00.webm](https://github.com/udistrital/planeacion_cliente/assets/64450601/fdcc43c7-d5b6-48f6-beb2-5c57033083d1)

[PUT]

[Grabación de pantalla desde 08-07-24 10:33:31.webm](https://github.com/udistrital/planeacion_cliente/assets/64450601/9e770a80-9c97-4ac0-a3f4-a79bfadd5113)

[DELETE]

[Grabación de pantalla desde 08-07-24 10:34:34.webm](https://github.com/udistrital/planeacion_cliente/assets/64450601/4d71ec3a-d80d-4e3f-9a87-64bae159483e)

**Comment by a52290451** [comment]
Se validan pruebas realizadas y se da cierre al issue

**Comment by diegobauto** [comment]
Enlace de pruebas funcionales: [API CRUD](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EROOT6D_K7lDqOH1f1xu3t0BxfZOOsQt_FzKxMZn-RUY7Q?e=9zLzOw)
