### ISSUE TITLE
Funcionalidad para cálculos de la liquidación  del componente de identificación docente en la formulación de un plan de acción de funcionamiento

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#123]
Se debe desarrollar la funcionalidad para los cálculos de la liquidación  de los diferentes conceptos para la edificación de docentes , teniendo en cuenta la información levantada en el excel, la issue debe cumplir con los siguientes requerimientos:

- [x] Ajustar el componente de docentes para la visualización solamente a las unidades de facultades y ILUD
- [ ] Consumir el servicio del core_crud  (https://autenticacion.portaloas.udistrital.edu.co/apioas/core_amazon_crud/v1/punto_salarial y http://pruebasapi.intranetoas.udistrital.edu.co:8106/v1/punto_salarial)  para cargar el valor del punto de la vigencia seleccionada en el plan de acción y poder calcular el valor del sueldo básico según la información suministrada 
- [ ] Calcular y crear la funcionalidad (bloquear la edición) para cada concepto de la tabla con la información suministrada 
- [ ] Ajustar la funcionalidad para los cálculos totales teniendo en cuenta la cantidad de docentes y sumas totales
[Formato Formulación Plan de Acción 2022 (1).xlsx](https://github.com/udistrital/planeacion_cliente/files/7524261/Formato.Formulacion.Plan.de.Accion.2022.1.xlsx)

**Comment by brayaned** [comment]
Se da inicio a la issue.

**Comment by brayaned** [comment]
Se realizo el ajuste en el componente de formulación para que solo las dependencias de las facultades puedan acceder al componente de identificación de recurso docente.

**Comment by brayaned** [comment]
La issue entro en un periodo de pausa por decisión del líder técnico (@fabianbarreto02 ) debido a un cambio en el flujo, esto porque se consumirá una función externa al sistema para realizar los cálculos de salario básico y factores prestacionales.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
