### ISSUE TITLE
Implementación de notificaciones en nuevo modelo de datos (PARTE 2)

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1237]
De acuerdo a los avances realizados en #1223 , se requiere continuar con la implementación del API CRUD notificaciones_crud que permita conectar con la BD de Notificaciones y conectar dicha API con notificaciones_mid, consumiendo los metodos desde webcomponents y clientes particulares.

**Especificaciones Técnicas**

- Una vez se tenga el API CRUD listo, se debe conectar con notificaciones_mid para encadenar servicios y que sea transversal su consumo desde los clientes.
- Se debe adecuar la implementación de notificaciones en webcomponents para que permita el consumo a través de notificaciones_crud.
- Se requiere implementar pruebas de forma masiva para verificar los tiempos de respuesta del sistema de notificaciones.

**Sub Tareas**

- [x] Finalización API CRUD notificaciones_crud.
- [x] Ajuste webcomponent para consumo de notificaciones desde notificaciones_crud.
- [x] Pruebas de verificación de tiempos de respuesta.
- [x] Ajuste de notificaciones_mid para consumo de notificaciones_crud.
- [x] Verificar y corregir despliegue de notificaciones_crud en ambiente de pruebas.

**Criterios de aceptación**

- [x] Existe una base de datos de notificaciones no relacional que puede ser accedida mediante un API.
- [x] SISGPLAN posee un sistema de notificaciones que carga la información rápidamente, manejando estados en las mismas.

**Requerimientos**

- Completar issue #1223 .
- Completar despliegue de notificaciones_crud.

**Dependencias**

- notificaciones_mid.
- notificaciones_crud.
- webcomponents.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Se añade evidencia: 
- Envio de notificación en tiempo real
- Consulta de lista de notificaciones por medio del panel
- Redirección a componente por medio de los metadatos
- Modificación de la lista de notificación, al ser una notificación leida pasa al final

[Grabación de pantalla desde 12-07-24 12:09:18.webm](https://github.com/user-attachments/assets/f7586662-aa0a-4a3d-b41c-1677f2cb0e1c)

**Comment by a52290451** [comment]
@diegobauto Se requiere crear PRs para despliegue en ambiente de pruebas, así como proporcionar datos de la BD y repositorio para creación de la misma en ambiente de pruebas.

**Comment by diegobauto** [comment]
Pull request: 
- Cliente: https://github.com/udistrital/planeacion_cliente/pull/1257
- Notificacion_mid: https://github.com/udistrital/notificacion_mid/pull/57

Datos bd (notificaciones_crud):
- Base de datos: udistritalcore
- Esquema: notificaciones

**Comment by a52290451** [comment]
Solicitudes para despliegue de notificaciones_crud en ambiente de pruebas:

solicitud 1: https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=62626
solicitud 2: https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=62639

**Comment by a52290451** [comment]
Solicitud de despliegue de notificaciones_crud en ambiente de pruebas:

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=62624
