### ISSUE TITLE
Ajustes módulo de Reportes (seguimiento con armonización y reportes cualitativos) (PARTE 2)

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1238]
Se requiere finalizar los ajustes del módulo de Reportes para mostrar información de armonización en reportes de planes de acción en fase de seguimiento, al igual que se hace en formulación, y agregar información cualitativa a los reportes en general.

**Descripción técnica**

- Se debe agregar información acerca de la armonización del plan de acción con el PED y el PI en los reportes que se generan en fase de seguimiento, al igual que se hace con los reportes de planes de acción en fase de formulación.
- Se requiere agregar en todos los reportes, información cualitativa de los planes de acción, como se muestra a continuación:

![Image](https://github.com/udistrital/planeacion_cliente/assets/36229498/1a00ead0-0cf9-4575-835f-b212e69465e6)

![Image](https://github.com/udistrital/planeacion_cliente/assets/36229498/57228d15-5ccb-49ba-85b2-e8f20f0a9e46)

**Sub Tareas**

- [ ] Adición de información de armonización en reportes de planes de acción en fase de seguimiento.
- [ ] Adición de información cualitativa en reportes generados.

**Criterios de aceptación**

- [ ] Los reportes de planes de acción en fase de seguimiento muestran información relacionada a la armonización que poseen con el PED y el PI.
- [ ] Los reportes de planes de acción muestran información cualitativa y cuantitativa.

**Requerimientos**

- [ ] Terminar issue #1221 .

**Dependencias**

- planeacion_cliente
- planeacion_mid

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
@felimarod Se requiere actualización del estado de la actividad con:

- Pruebas funcionales.
- Documentación del issue.
- Commits.

**Comment by felimarod** [comment]
La primera parte se encuentra en el siguiente comentario: https://github.com/udistrital/planeacion_cliente/issues/1221#issuecomment-2230876167

Modificaciones a verificar con el usuario final:
1. Agregar un 'título' que separe la armonización de la evaluación
    ![image](https://github.com/user-attachments/assets/f79bc4dc-9810-45f2-8a3b-777106bf902c)
2. Propuesta para agregar los reporte de avance y dificultades dentro de un trimestre
    ![image](https://github.com/user-attachments/assets/6119e086-c88f-4466-969a-a3b1b0fb20bf)
3. Etiqueta de "Evaluación" para separar de la armonización
    ![image](https://github.com/user-attachments/assets/f47a97d6-2211-4a85-a8da-eecdbf91c3fc)

**Comment by felimarod** [comment]
Prueba funcional con un reporte que solo tiene 1 trimestre reportado:

[Grabación de pantalla desde 2024-07-17 11-21-01.webm](https://github.com/user-attachments/assets/18c9d006-f166-43a5-938b-236646a76a72)

Se encontró un bug al realizar los reportes ya que solo se estaban revisando 4 trimestres de los 8 que llegan, se asocia esto con un fallo que tiene actualmente al intentar hacer un reporte de un plan que tenga reportado más de un trimestre

**Comment by felimarod** [comment]
Fallo solucionado, pruebas funcionales faltantes:

https://github.com/user-attachments/assets/e9e75410-bf81-4cf1-b02e-700fbff21747
