### ISSUE TITLE
Corrección de Errores (Pruebas de carga y seguridad)

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1239]
Se requiere realizar la corrección de fallos de seguridad y vulnerabilidades encontrados en las pruebas de carga y seguridad, de acuerdo con el [informe suministrado](https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=62069) y las observaciones descritas en el apartado técnico.

**Especificaciones Técnicas**

- Revisar configuración de CORS para que no se permita acceso desde otros orígenes distintos a *udistrital.edu.co 
https://github.com/udistrital/planeacion_mid/blob/release/0.0.1/main.go

Ejemplo: https://github.com/udistrital/resoluciones_crud_v2/blob/develop/main.go#L25

- Github Alerts: evaluar las Vulnerabilidades con severidad crítica y alta en https://github.com/udistrital/planeacion_cliente/security, https://github.com/udistrital/planes_crud/security  

- Revisar las observaciones generadas desde SonarQube:
https://sonarqube.portaloas.udistrital.edu.co/dashboard?id=udistrital%3Aplaneacion_cliente 
https://sonarqube.portaloas.udistrital.edu.co/dashboard?id=udistrital%3Aplaneacion_mid 

SonarQube

ejemplo: en el cliente, este archivo está vacío: src/app/app.component.scss

hay muchas que salen por los nombres de las variables, esos podríamos dejarlos para revisar después o no tenerlos en cuenta en el reporte, porque desde Sonar espera el nombre como camel case: nombreVariable y están definidas como nombre_variable

**Sub Tareas**

- [x] Corrección configuración de CORS.
- [x] Corrección Github Alerts: Vulnerabilidades con severidad crítica y alta.
- [x] Corrección observaciones generadas desde SonarQube.

**Criterios de aceptación**

- [x] El sistema se encuentra estable y cumple con las medidas de seguridad requeridas por el área de seguridad.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Oscarjaimes1710** [comment]
1.  Se hace el ajuste de cors queda pendiente por revisión y validación.
2. Github Alerts: Evaluación y Mitigación de Vulnerabilidades Críticas y Altas

Se han llevado a cabo evaluaciones exhaustivas de las vulnerabilidades clasificadas como críticas y altas en los repositorios planeacion_mid, planeacion_cliente y planeacion_crud. Las revisiones pertinentes se han realizado, implementando las correcciones necesarias y gestionando los Pull Requests (PR) viables mediante Dependabot: planeacion_cliente/security/dependabot.

A continuación, se documentan dos casos específicos en los cuales las correcciones no pudieron ser implementadas:

Caso A: Dependabot Alert #100

La corrección no pudo ser completada debido a que el ajuste requerido por Dependabot genera una advertencia indicando la necesidad de múltiples actualizaciones de dependencias. Esta situación podría desencadenar una falla catastrófica en el sistema.

Caso B: ip SSRF improper categorization in isPublic #958 

No se permite ejecutar puesto que encuentra unas singularidades de seguridad sin embargo se consulta con el equipo de seguridad específicamente con Maria Fernanda Avendaño y la sugerencia es esperar a que saquen una versión actualizada con la solución a la vulnerabilidad. Se deja notificado al equipo de la vulnerabilidad para que así puedan tenerla en cuenta en la próxima actualización.

**Comment by a52290451** [comment]
queda pendiente carga de correcciones en planeacion_cliente

**Comment by a52290451** [comment]
@Oscarjaimes1710 por favor documentar hallazgos finales de issue para su finalización.

**Comment by Oscarjaimes1710** [comment]
Se tuvieron que hacer 2 revert respecto de los pr que genero el dependabot para las correcciones criticas de seguridad puesto que estos actualizaron deliberadamente la versión de angular a la 18 y esto genero un desencadenamiento de errores en cascada en todo el cliente por la incompatibilidad entre librerias usadas actualmente con la version mas actual de angular por eso se tuvieron que hacer estos dos Revert : 

1. https://github.com/udistrital/planeacion_cliente/pull/1263
2. https://github.com/udistrital/planeacion_cliente/pull/1262

**Comment by Oscarjaimes1710** [comment]
Resumen: 

1. Revisar configuración de CORS para que no se permita acceso desde otros orígenes distintos a *udistrital.edu.co.
Solucion del primer iteral:  Se Hace el ajuste del cors en este PR haciendo el ajuste solicitado:https://github.com/udistrital/planeacion_mid/pull/584

2. Github Alerts: evaluar las Vulnerabilidades con severidad crítica y alta
Solucion de Alertar en el Cliente: Se encuentran las siguientes alertas 
             -https://github.com/udistrital/planeacion_cliente/security/dependabot/56
             -https://github.com/udistrital/planeacion_cliente/security/dependabot/100
             -https://github.com/udistrital/planeacion_cliente/security/dependabot/98
             -https://github.com/udistrital/planeacion_cliente/security/dependabot/94
             -https://github.com/udistrital/planeacion_cliente/security/dependabot/30
 En los hallazgos hechos para estas alertar se hicieron las correcciones necesarias ejecutando el dependabot pero al realizar esto se desencadenaron múltiples errores puesto que esto incluyo una actualización global de la versión de angular a la 18.19. Cuando se hace la revisiones de las posibles soluciones ejecutadas por el dependabot se generan una serie de errores de compatibilidad con las diferentes librerías con la nueva versión esto hace que el sistema falle por completo y se toma la decisión de hacer un revert de las soluciones presentadas por el dependabot para poder estabilizar el sistema. En especifico algunas de las actualizaciones como lo son actualizar "loader-utils" a una versión >=2.0.3" esta ligada directamente a actualización de angular puesto que lo anterior nombrado funciona solamente con una versión mas reciente de angular. En otras se opta por no ejecutar ningún despliegue de dependabot o actualizaciones manuales de librerías puesto que esto puede poner en jaque el sistema al tener que hacer múltiples acciones de este tipo.
 
 Solución de Alertar en el Crud: Se encuntra que hay 19 Alertas relacionadas con la actualizacion de librerias como: shelljs ,  "ansi-regex": ">=5.0.1" , "mongoose": ">=5.13.20" ,"minimist": ">=1.2.6",  "qs": ">=6.10.3" y  "minimatch": ">=3.0.5". Estas sugerencias del dependabot podría generar nuevamente una cascada de errores puesto que las versiones librerías mas recientes requieres de una actualización global de las versiones que se están usando actualmente de los clientes y crud.
 
 3. En las revisiones realizadas del SonarQube del MID no se encuentran bugs pero si se encuentran observaciones del índole de código no cubierto por test(pruebas unitarias). Esto no es necesario corregirlo pues se realizaron pruebas unitarias para todo el sistema y están funcionales.
 En cuanto a las revisiones realizadas del SonarQube del cliente se dejo la anotación en el anterior comentario donde se hace claridad que lo que el SonarQube detecta como bug no lo es en realidad.

**Comment by a52290451** [comment]
No se realizan mas observaciones relacionadas con pruebas de carga y seguridad, por lo tanto, se da por terminada la actividad.
