### ISSUE TITLE
Implementación de funcionalidad de observación a los planes de acción de funcionamiento

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#124]
Se debe desarrollar la funcionalidad para la creación, visualización de los campos de observación para los planes de acción de funcionamiento según el estado del plan (diagrama de estados), la issue debe cumplir los siguientes requerimientos:

- [x]  Ajustar el flujo de visualización, edición del campo observación teniendo en cuenta el diagrama de [estado ](https://drive.google.com/file/d/1OEzI2BrMiLnPzI6izfEV3kVqRYvyxFCR/view?usp=sharing) planeado 
- [x] Crear la funcionalidad para el registro de las observaciones cuando el estado lo permita 
- [x] Crear la funcionalidad para la visualización (consulta ) de las observaciones segun el diagrama de estados 
-

**Comment by ndmc98** [comment]
Se da inicio a la issue. 17/11/2021

**Comment by ndmc98** [comment]
Para el cumplimiento de la issue se realizó:

- Ajuste de visualización para el campo observación considerando los estados del diagrama de estados propuesto.
- Configuración a nivel MID y CLIENTE de la funcionalidad de guardar y consultar observaciones.

**Comment by ndmc98** [comment]
Se genera Pull Request para dar cierre a la issue

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
