### ISSUE TITLE
Documentación en videotutoriales parcial

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1241]
Se requiere realizar los videotutoriales de Sisgplan por rol y accion

**Sub Tareas**

- [x] Definir video tutoriales pequeños (no más de 2 min por c/u) para el flujo de formulación. Estos deben ser por rol (Jefe dependencia, asistente dependencia, Jefe planeación, asistente planeación.
- [x] Definir video tutoriales pequeños (no más de 2 min por c/u) para el flujo de seguimiento. Estos deben ser por rol c Jefe dependencia, asistente dependencia, Jefe planeación, asistente planeación. 
- [x] Definir videotutoriales pequeños (No más de 5 min) para el modelo de reportes, evaluación y construcción para los roles de Jefe planeación.  Hacer enfasis en gestion de roles.

**Criterios de aceptación**

- [x] Se crean video tutoriales pequeños, eficientes, particulares para rol, estado, acción.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by ccmendezt** [comment]
## Evidencias - Avance Documentación en videotutoriales parcial
### 12/07/2024 - 20:12

Se completaron los videotutoriales del flujo de Seguimiento.

## Notas importantes:
  **i.** Se están creando los videotutoriales para el módulo de evaluación y generación de reportes.

**Comment by Mechaz123** [comment]
# FORMULACIÓN Y CONSTRUCCIÓN #

- Se completan los tutoriales de Formulación y Construcción.
- El video acerca de Gestión de Usuarios, se encuentra dentro de la carpeta de Construcción
