### ISSUE TITLE
Creación del componente para la visualización del estado actual del plan de acción de funcionamiento

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#125]
Se debe crear el componente para visualización del estado del plan y de la versión del plan siguiendo el mockup presentado:

![image](https://user-images.githubusercontent.com/43799065/141397041-ab5d6b2c-caf7-494e-8c4d-55b15abfbe1b.png)

La issue debe cumplir con los siguientes requerimientos:

- [x] Crear el componente para la visualización del estado del plan y de la versión del plan
- [x] Consumir la información para mostrar en el componente

**Comment by ndmc98** [comment]
Se da inicio a la issue. 16/11/2021

**Comment by ndmc98** [comment]
Se crea la opción para dar alcance a la visualización del estado del plan y de la versión del plan. Se ajusta el componente para consumir la información que carga las versiones y mostrarla en el cliente con los ajustes visuales.

**Comment by ndmc98** [comment]
Se genera Pull Request para dar cierre a la issue.

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
