### ISSUE TITLE
Optimización Notificaciones

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1253]
Se requiere realizar la optimización de notificaciones adicionando la creación de una cola de peticiones en **planes_crud** y optimizaciones visuales del servicio.

**Aspectos Técnicos**

- Creación de cola de peticiones que permita atender las peticiones realizadas a notificaciones_crud por orden de llegada, garantizando que el sistema no se colapse y pueda responder adecuadamente a todas las peticiones entrantes.
- Ajuste visual en webcomponnets para señalar a través de un mensaje "No hay notificaciones" y un icono, que no se encuentran notificaciones para el usuario logueado.
- Creación de animación para el desplazamiento de las notificaciones en la tirilla de notificaciones, cuando sean consultadas o acaben de llegar, de tal forma que se perciba el movimiento de las mimas al inicio o fin de la tirilla.

**Sub Tareas**

- [x] Creación de cola de peticiones en notificaciones_crud.
- [x] Ajuste visual de notificaciones con mensaje de "No hay notificaciones".
- [x] Animación de transición entre notificaciones.

**Criterios de aceptación**

- [x] Todas las peticiones que se realizan a notificaciones_crud son atendidas sin pérdida de información.
- [x] El módulo de notificaciones avisa a través de un mensaje cuando no se tienen notificaciones.
- [x] Cuando se revisa una notificación se percibe la transición entre notificaciones.

**Requerimientos**

- [ ] Finalizar Issue #1237 .

**Dependencias**

- notificaciones_crud
- webcomponents
- planeacion_cliente

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Se tienen en cuenta los siguientes mockups pertenecientes al tema cuando un usuario no tienen notificaciones:

![Notificaciones SISGPLAN](https://github.com/user-attachments/assets/677db742-c661-40e9-9942-fc4dc0c9b143)

![Notificaciones SISGPLAN](https://github.com/user-attachments/assets/c31c0a49-d1d3-4e73-9849-fc9c1d446bee)

**Comment by diegobauto** [comment]
Se realiza prueba en local la cual consiste en enviar 5000 peticiones para la creación de notificaciones de manera paralela, y el api responde adecuadamente. Sin embargo, se solicita recrear nuevamente este proceso directamente en pruebas, para verificar el funcionamiento y rectificar el procesamiento.

Por otro lado, se trabajo el manejo de colas, el cúal permite procesar las peticiones una a una por orden de llegada, utilizando dos métodos diferentes (Async y Bull/redis). Ambos métodos cumplen la misma funcionalidad pero se implementan de forma diferente. Esto para poder tener una alternativa directa si el sistema no responde a las soliticitudes de la manera esperada.

**Comment by a52290451** [comment]
Con las observaciones realizadas por @diegobauto, queda pendiente validar respuesta del API notificaciones_crud con pruebas de carga, cuando se envían peticiones de forma masiva.

Las pruebas realizadas en local evidencian que no es necesario la creación de una cola de peticiones para atender solicitudes entrantes.

**Comment by a52290451** [comment]
@diegobauto por favor cargar evidencia final del issue y documentación para su finalización

**Comment by diegobauto** [comment]
Actualización en el modelo de datos para recibir directamente un lista de destinatarios, siguiendo la lógica de registrarlos independientemente:

![notificaciones_crud](https://github.com/user-attachments/assets/f79658bc-75de-4ec4-aff0-55c9c990c6ae)

**Comment by a52290451** [comment]
Queda pendiente revisión y despliegue de implementación.
