### ISSUE TITLE
Ajustes salida a producción nuevos

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1255]
Se requiere ajustar módulos del sistema para despliegue a producción previsto para el 2 de agosto de 2024.

**Aspectos Técnicos**

1. El mid, crud y cliente están actualizados a día de hoy en las ramas release/0.0.1.

**Sub Tareas**

**Construcción**

- [x] 1. En la construcción de planes de acción se requiere que en la estructura del formulario de plan de acción, cuándo el campo sea de tipo select se añada palabra por palabra con un campo input tipo texto y un botón adicionar, que adiciona una cajilla inferior con la palabra adicionada. La lista de palabras adicionadas debe tener un ícono de basura al lado y un lápiz que representan la eliminación de la lista y su edición de manera respectiva.

**Formulación**

- [x] 2. Revisar el flujo de formulación: "La formulación y el trámite de las observaciones realizadas desde el usuario de planeación, no fue posible con el usuario “asistente de dependencia” sino con el de “jefe de dependencia”, lo anterior acorde al [flujo definido](https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7B27614EAA-0DFA-4E5E-A58F-FAB92EC05C89%7D&file=Diagrama%20de%20Estados%20-%20acciones%20y%20flujo%20Actualizado.xlsx&action=default&mobileredirect=true&wdsle=0).
- [x] 3. En la identificación de contratistas y recurso docente, en la sección de rubros, establecer una opción de búsqueda o filtro por palabra clave que facilite la búsqueda.
- [x] 4. Luego de avalalado el plan, no es posible visualizar la armonización, es decir no se observa el símbolo (✓).

**Seguimiento**
- [x] 5. El reporte del seguimiento no se pudo realizar desde el rol de “asistente de pendencia”, solo fue posible desde el rol “jefe de la dependencia”. Lo anterior debe corregirse desde configuración y la lógica existente en el cliente.
- [x] 6. La información de la actividad no sale completa en las actividades específicas y una parte del texto queda oculto (Flujo de seguimiento).
![image](https://github.com/user-attachments/assets/97eaaafd-7515-45d8-a699-1eebe4887a03)

- [x] 7. Las observaciones que se realizan desde el rol de planeación, no deberían poderse borrar desde el rol “jefe de la dependencia” (Flujo de seguimiento).
- [x] 8. Cuando el “criterio del indicador” se haya parametrizado como “denominador variable” en la formulación, el reporte cuantitativo del seguimiento trimestral debe multiplicarse por el 25%. Estos indicadores corresponden a trámites solicitados por la comunidad, los cuales se cumplen al 100%, generando la sensación de que el plan se ejecutó mucho antes de que finalice la vigencia. (Flujo de seguimiento).
- [x] 9. Las actividades con estado “verificadas” deben resaltarse con un color distinto al verde de la actividad avalada. Se propone azul para el estado “verificadas”. Flujo de seguimiento.

**Reportes**
- [ ] 10. Incluir en el reporte la columna correspondiente al “criterio del indicador”. 
- [ ] 11. La denominación del archivo Excel “reporte” que se descarga del sistema debe ser el nombre de la dependencia en dado caso que el filtro haya sido con alguna dependencia en particular o si no reporte_nombreReporte.
- [ ] 12. En la lista desplegable solo debe aparecer las dependencias que formulan y realizan seguimiento al plan de acción. En la actualidad aparecen áreas de las dependencias lo cual dificulta la búsqueda de la unidad requerida. [(Aplicar filtro de dependencias)](https://github.com/udistrital/planeacion_mid/commit/91ceb94a7fa88a4a818b09ea4ce5903ca915f9e9). 

**Criterios de aceptación**

- [x] Se revisan cada una de las modificaciones solicitadas por el usuario dándo un concepto de: "Por corregir", "Ya se encuentra implementado".
- [x] Se realizan las correcciones identificadas por el concepto previo.
- [x] Se prueban funcionalmente las correcciones implementadas.

**Requerimientos**

- Finalizar issue #1150 .

**Dependencias**

- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
Se realiza la modificación para que se pueda cambiar el tamaño verticalmente de los textarea, mencionados en el Issue:

![Image](https://github.com/user-attachments/assets/e38abb04-4d5e-4782-9a52-599eabcd092a)

**Comment by Mechaz123** [comment]
# SEGUIMIENTO #
**AJUSTE NÚMERO 8**
- Se realiza la modificación para que al momento de realizar la operación 0/0, se realizar la multiplicación por el 0.25% en la actividad
- A continuación, se presenta un caso donde se reportan 2 actividades con ese valor y una con un valor diferente.

**Actividad 1**

![Image](https://github.com/user-attachments/assets/aeba2cad-98ab-49b8-91ee-157d564a1393)

**Actividad 2**

![Image](https://github.com/user-attachments/assets/a384718c-e66b-4d14-a9ed-fc3a7d4de67e)

**Actividad 3**

![Image](https://github.com/user-attachments/assets/ab4669ce-00f0-484c-b98d-6581ebfe31d0)

**Grafico en Evaluación**

![Image](https://github.com/user-attachments/assets/32caab0d-6462-44a4-b6f4-c93255c9b33b)

# NOTA #

- Queda pendiente validación del usuario acerca de la representación del grafico en evaluación y la corrección implementada

**Comment by ccmendezt** [comment]
## Evidencias - Ajustes salida a producción nuevos
### 19/07/2024 - 12:10

- ### Item 2. Revisar el flujo de formulación: "La formulación y el trámite de las observaciones realizadas desde el usuario de planeación, no fue posible con el usuario “asistente de dependencia” sino con el de “jefe de dependencia”, lo anterior acorde al [flujo definido](https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7B27614EAA-0DFA-4E5E-A58F-FAB92EC05C89%7D&file=Diagrama%20de%20Estados%20-%20acciones%20y%20flujo%20Actualizado.xlsx&action=default&mobileredirect=true&wdsle=0).

Se realizó el flujo de formulación de plan de acción y la observación en cuestión que realizó el usuario es la siguiente:
Una vez el plan fue formulado por el ASISTENTE_DEPENDENCIA, es enviado para que el ASISTENTE_PLANEACION lo revise, y realice observaciones en caso de haberlas, una vez realiza las observaciones y envía la revisión el plan queda en el estado **Revisado**:

![image](https://github.com/user-attachments/assets/d39374eb-5933-4bff-a123-b0e8fbdcaa5b)

Luego, según el flujo establecido, en caso de haber observaciones, es el JEFE_DEPENDENCIA quien toma la decisión de volver el plan al estado de **En formulación**, el ASISTENTE_DEPENDENCIA NO puede realizar esta acción:

![image](https://github.com/user-attachments/assets/56768c5c-d706-46fb-977f-ea010c3766ad)

Es por esto, que desde el rol JEFE_DEPENDENCIA está habilitado el botón **Realizar ajustes**:
![image](https://github.com/user-attachments/assets/c8344045-dab4-4941-8309-98b72a46154a)

Mientras que desde el rol ASISTENTE_DEPENDENCIA no lo está:
![image](https://github.com/user-attachments/assets/a52cba96-ffd3-4bde-82b8-8bc92f256c76)

Así que siguiendo el flujo indicado, NO habría nada que corregir porque el flujo en el sistema está implementado correctamente según el documento.

- ### Item 5. El reporte del seguimiento no se pudo realizar desde el rol de “asistente dependencia”, solo fue posible desde el rol “jefe de la dependencia”. Lo anterior debe corregirse desde configuración y la lógica existente en el cliente.

Se realizó el flujo de reporte de seguimiento para el T3 del plan **PRUEBA DE MONOLITO TIPO PLAN CAMILO** y **FACULTAD DE INGENIERIA**. Dicho flujo funcionó con normalidad según la siguiente prueba funcional:

![EnvioReporteSeguimientoAsistenteDependencia](https://github.com/user-attachments/assets/e55c2c0a-a5ce-43d1-b10f-632f795bc049)

Allí se puede observar que cuando las actividades ya han sido reportadas desde el rol ASISTENTE_DEPENDENCIA el estado del seguimiento es **En reporte**, luego se da clic al botón **Enviar reporte** y se envía correctamente el reporte cambiando su estado a **Enviado a revisión**. Dicho flujo también funciona con normalidad.

**Comment by a52290451** [comment]
@Oscarjaimes1710 por favor documentar avances realizados en las tareas 1, 3 y 4.

**Comment by Mechaz123** [comment]
# SEGUIMIENTO #
**AJUSTE NÚMERO 7**
- Se realizó un video explicando el flujo completo del sistema, donde se muestra la separación de observaciones y como se hizo: https://udistritaleduco-my.sharepoint.com/:v:/g/personal/daarojasg_udistrital_edu_co/EWJBLXbLRk9Bm79ls0E2MFABfiH3WQkzBGliGUKlppsQJQ?e=HJPsUd

- Así mismo en vista que el video es algo extenso y pesado para github, se carga la siguiente imagen de la estructura que se manejó para este cambio:

![Image](https://github.com/user-attachments/assets/0cd28c04-b20e-413a-8342-fa5704628713)

**Comment by Oscarjaimes1710** [comment]
> @Oscarjaimes1710 por favor documentar avances realizados en las tareas 1, 3 y 4.

1. Respecto del punto 4 de la issue, no se realizo ningún cambio puesto que la armonización esta ligada directamente a cada actividad esto hace que al visualizar el plan en estado Avalado se puede ver el árbol cuando se observa directamente cada actividad del plan, se deja evidencia aquí: https://udistritaleduco-my.sharepoint.com/:v:/g/personal/computo_udistrital_edu_co/EWepn_azhZdJnVD4nRDZnDQBn45qy84MeXJr6vasLP3s-w?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=GS2GGc.

2.Respecto del 1 y 3 ya se encuentre en fase de ajustes visuales se espera cargar todos los cambios en la revisión posterior a aprobación del desarrollo por parte del líder.

**Comment by Mechaz123** [comment]
> > # SEGUIMIENTO
> > **AJUSTE NÚMERO 7**
> > 
> > * Se realizó un video explicando el flujo completo del sistema, donde se muestra la separación de observaciones y como se hizo: https://udistritaleduco-my.sharepoint.com/:v:/g/personal/daarojasg_udistrital_edu_co/EWJBLXbLRk9Bm79ls0E2MFABfiH3WQkzBGliGUKlppsQJQ?e=HJPsUd
> > * Así mismo en vista que el video es algo extenso y pesado para github, se carga la siguiente imagen de la estructura que se manejó para este cambio:
> > 
> > ![Image](https://private-user-images.githubusercontent.com/73924638/351106083-0cd28c04-b20e-413a-8342-fa5704628713.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2ODQyNDAsIm5iZiI6MTcyMTY4Mzk0MCwicGF0aCI6Ii83MzkyNDYzOC8zNTExMDYwODMtMGNkMjhjMDQtYjIwZS00MTNhLTgzNDItZmE1NzA0NjI4NzEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDIxMzIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczZTA3ZDM2MGY3MDc3MGVkOGZlZDM5MzExODcyYzRlM2FlZTZkZjNiMTMwZmNjMWY4NWRiNWVkNzQ2ODYwMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mWkP8k7P66Y8OLhRj0lfZPDMbwgmfxNAWTjvoZRvMEw)
> 
> En cuanto a este item, es importante validar que esta lógica no afecte seguimientos que no tengan aún observaciones por parte del jefe_dependencia.

- Para las observaciones ya existentes, este campo donde se guardaban llamado "observaciones", se conservará para aquellas actividades que ya tenían el campo creado, ya que se crean dos campos nuevos "observaciones_planeacion" y "observaciones_dependencia", de manera que el campo aún existirá en la base de datos, pero no se volverá a usar una vez que el desarrollo se aplique.
- Por otra parte, para migrar dichas observaciones se tendría que tener en cuenta en qué estado se encuentra el plan y quien ha sido el último ente que ha modificado el campo, ya que al ser un campo compartido entre planeación y la dependencia, solo se conservaría el valor para uno de los dos.

**Comment by Oscarjaimes1710** [comment]
Correcciones finales de el desarrollo de la 1 y 3

Se hace el desarrollo como se solicito: 
Evidencias del funcionamiento en editar y añadir 
<img width="1252" alt="Captura de pantalla 2024-07-25 a la(s) 7 44 29 p  m" src="https://github.com/user-attachments/assets/98a75d26-595d-4f0c-9601-01109509f4ff">
<img width="1252" alt="Captura de pantalla 2024-07-25 a la(s) 7 45 16 p  m" src="https://github.com/user-attachments/assets/c06406aa-5d11-40f2-84cb-306b9b436ad9">

Punto 3 funcionamiento 
<img width="1017" alt="Captura de pantalla 2024-07-25 a la(s) 7 47 22 p  m" src="https://github.com/user-attachments/assets/76d63c47-e12e-405f-a0b3-42623eaa0ccc">

PR : https://github.com/udistrital/planeacion_cliente/pull/1280
