### ISSUE TITLE
Revisión de flujo con nuevos planes PED y PI

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1259]
Se requiere revisar el flujo completo de SISGPLAN, cambiando algunas actividades del Plan indicativo y del plan estratégico de desarrollo, dado que para salir a producción se requiere ajustar el plan indicativo.

**Especificaciones técnicas**

- Realizar la prueba en base de datos local

**Subtareas**

- [x] Se debe revisar el funcionamiento actual de los macroplanes PI y PED, para saber si se pueden diferenciar versiones por vigencia.
- [x] En dado caso de no poder diferenciar macroplanes para vigencias específicas se debe implementar una solición.
- [x] Tener en cuenta la creación de script para actualizar los macroplanes para las vigencias de los planes encontradas en producción.

**Criterios de aceptación**

- [x] Se documenta el issue correctamente con las pruebas realizadas.
- [x] Se presenta una propuesta ajustada a la necesidad.
- [x] Se crea script para que los datos de producción no se vean comprometidos a la hora de implementar la solución en ambiente productivo de la aplicación.

**Requerimientos**

- [X] Despliegue de los MF en pruebas

**Dependencias**

- Todos los MF de SISGPLAN.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by ccmendezt** [comment]
## Evidencias - Revisión de flujo con nuevos planes PED y PI
### 19/07/2024 - 13:00

Según lo acordado con el SM/Líder Técnico, la solución acordada es la siguiente:
- En la interfaz de Construir plan/proyecto cuando se seleccione el tipo de plan **PED** o **PI** se deberá diligenciar una opción más que serán las vigencias a las que aplicará dicho plan PED o PI mediante una lista desplegable. Eso se agregará a un nuevo campo en la colección _plan_ denominado **vigencia_aplica**, este campo solo se utilizará para los planes cuyo _tipo-plan_ sea corresponda a **PED** o **PI**. Ya teniendo las vigencias a las que aplican dichos planes, en la tabla de armonización de actividades se mostrarán únicamente los planes que coincidan con la vigencia del plan formulado y la vigencia a la que aplica el **PED** o **PI**. También, en el menú de **Consultar PI** o **Consultar PED** se agregará un botón que permitirá realizar una copia del **PED** o **PI** haciendo que la clonación del plan sea sencilla para que posteriormente el usuario pueda modificar las actividades necesarias (esto se hace pensando en evitar la construcción desde cero del plan **PED** o **PI**).

**Comment by ccmendezt** [comment]
## Evidencias - Avance Revisión de flujo con nuevos planes PED y PI
### 24/07/2024 - 15:10

- Se modificó **planes_crud** agregando el campo _vigencia_aplica_, dicho campo será utilizado únicamente por los planes que sean de tipo PI y PED, este campo es de tipo string que contendrá un array en formato scaped json con los id y nombres de las vigencias a las que aplicará el plan indicativo o de desarrollo. Esto se realizó para poder discriminarlos en la armonización de las actividades en la formulación de un plan.
- Se creó un endpoint en **planeacion_mid** dentro del controlador de _formulacion_ que permite duplicar los planes indicativos y estratégicos de desarrollo junto con sus nodos y subnodos. Esta función crea una réplica exacta del PI o PED añadiéndole al final del nombre del plan el string " - CLONADO":
![image](https://github.com/user-attachments/assets/cc64439c-75b8-448b-9d37-c08865e55ec8)

- Se creó la funcionalidad de duplicar planes en planeacion_cliente:
![clonar-pi-ped](https://github.com/user-attachments/assets/f90d34e5-86be-4ce0-b18e-378c710c02dd)

- Se agregó la columna vigencia_aplica en la consulta de PI o PED, allí se muestran las vigencias a las que aplica el plan separadas por coma:
     - Consulta PI:
     ![image](https://github.com/user-attachments/assets/a8f268f3-b7b2-4728-bdc9-89e613692669)

     - Consulta PED:
     ![image](https://github.com/user-attachments/assets/62133c84-46f4-47c3-8d8c-246127eeddae)

- En el proceso de armonización de PI y PED para las nuevas actividades creadas en la formulación de un plan se discriminan los PI y PED dependiendo de los valores que almacene los campos vigencia_aplica:

     - Carga de Planes Indicativos:
     ![image](https://github.com/user-attachments/assets/3f0da96e-7919-4e21-aad1-59cf8c253ec1)

     - Carga de Planes Estratégicos de Desarrollo:
     ![image](https://github.com/user-attachments/assets/62f23ad1-235a-44f5-8c4d-a46e647f88f1)

- Al momento de querer editar las vigencias a las que aplica se muestra un popup que indica básicamente que solo es posible adicionar vigencias y no quitarlas, las vigencias ya guardadas aparecerán deshabilitadas. Esto se hace ya que si se quitan vigencias la armonización de actividades no se vería correctamente:
![editar-vigencias-pi-ped](https://github.com/user-attachments/assets/b4b536dd-cba1-4060-8f27-6ba5742ccb7a)

- Se modificó el script **2-MigracionBDMongo**, se agregó una nueva función que permite agregar el campo vigencia_aplica a los PI y PED existentes en la base de datos consultando las vigencias desde parámetros_crud:
![image](https://github.com/user-attachments/assets/54d70efb-2563-4a1a-9e3b-b3c2f3a77c40)

- Script: [2-MigracionBDMongo.zip](https://github.com/user-attachments/files/16366967/2-MigracionBDMongo.zip)

## Commits/Pull Request asociados a Issue
- planes_crud: https://github.com/udistrital/planes_crud/pull/107
- planeacion_mid: https://github.com/udistrital/planeacion_mid/pull/599
- planeacion_cliente: https://github.com/udistrital/planeacion_cliente/pull/1277

## Notas importantes:
  **i.** Antes de ejecutar el script, se debe crear la vigencia 2025 en producción ya que se requiere que los nuevos PI y PED apliquen para dicha vigencia.
