### ISSUE TITLE
Análisis Plan Operativo General POG

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/planeacion_cliente#1260]
Se requiere realizar el análisis del Plan Operativo General. Debe contemplarse un alcance de acuerdo con la documentación existente que se consulte y lo que se hable en mesas de trabajo con el equipo de Planeación encargado.

**Sub Tareas**

- [ ] Definir el contexto del Plan Operativo General.
- [ ] Determinar un posible alcance.

**Criterios de aceptación**

- [ ] Documento que incluya el análisis solicitado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by BikerMetalHead** [comment]
Se realiza análisis del Sistema de planeación institucional, producto del análisis se genera diagrama que ubica el POG dentro del sistema y determina su papel. También se evidencia la relación de los planes padres, con el POG y como la información alimenta la programación presupuestal. Se presenta diagrama representar el análisis.
[Sistema de planeación institucional.drawio.pdf](https://github.com/user-attachments/files/16369743/Sistema.de.planeacion.institucional.drawio.pdf)

**Comment by norbeydanilo** [comment]
@BikerMetalHead Dejar documentación con la información levantada

**Comment by BikerMetalHead** [comment]
El documento adjunto trata sobre el levantamiento de requisitos del módulo de plan operativo general de la universidad. Este proceso se está llevando a cabo a través de sesiones colaborativas con el usuario final, lo que asegura que las necesidades y expectativas del mismo se comprendan y se integren adecuadamente en el diseño del módulo. Durante estas sesiones, se ha representado principalmente las necesidades y problemáticas en torno a el POG y propuestas de desarrollo para sisgplan
[Informe de Reunión levantamiento de requerimiento del Plan Operativo General.docx](https://github.com/user-attachments/files/16420619/Informe.de.Reunion.levantamiento.de.requerimiento.del.Plan.Operativo.General.docx)

**Comment by BikerMetalHead** [comment]
Se refina y completa el diagrama del sistema de planeación institucional  
[Sistema de planeación institucional.drawio.pdf](https://github.com/user-attachments/files/16421140/Sistema.de.planeacion.institucional.drawio.pdf)
