### ISSUE TITLE
Ajustes salida a producción nuevos (Parte 2)

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1268]
Se requiere continuar con el ajuste de los módulos del sistema para despliegue a producción previsto para el 2 de agosto de 2024.

**Aspectos Técnicos**

1. El mid, crud y cliente están actualizados a día de hoy en las ramas release/0.0.1.

**Sub Tareas**

**Construcción**

- [x] 1. En la construcción de planes de acción se requiere que en la estructura del formulario de plan de acción, cuándo el campo sea de tipo select se añada palabra por palabra con un campo input tipo texto y un botón adicionar, que adiciona una cajilla inferior con la palabra adicionada. La lista de palabras adicionadas debe tener un ícono de basura al lado y un lápiz que representan la eliminación de la lista y su edición de manera respectiva.

**Formulación**

- [x] 2. Revisar el flujo de formulación: "La formulación y el trámite de las observaciones realizadas desde el usuario de planeación, no fue posible con el usuario “asistente de dependencia” sino con el de “jefe de dependencia”, lo anterior acorde al [flujo definido](https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7B27614EAA-0DFA-4E5E-A58F-FAB92EC05C89%7D&file=Diagrama%20de%20Estados%20-%20acciones%20y%20flujo%20Actualizado.xlsx&action=default&mobileredirect=true&wdsle=0).
- [x] 3. En la identificación de contratistas y recurso docente, en la sección de rubros, establecer una opción de búsqueda o filtro por palabra clave que facilite la búsqueda.
- [x] 4. Luego de avalalado el plan, no es posible visualizar la armonización, es decir no se observa el símbolo (✓).

**Seguimiento**
- [x] 5. El reporte del seguimiento no se pudo realizar desde el rol de “asistente de pendencia”, solo fue posible desde el rol “jefe de la dependencia”. Lo anterior debe corregirse desde configuración y la lógica existente en el cliente.

- [x] 7. Las observaciones que se realizan desde el rol de planeación, no deberían poderse borrar desde el rol “jefe de la dependencia” (Flujo de seguimiento).

**Reportes**
- [x] 10. Incluir en el reporte la columna correspondiente al “criterio del indicador”. 
- [x] 11. La denominación del archivo Excel “reporte” que se descarga del sistema debe ser el nombre de la dependencia en dado caso que el filtro haya sido con alguna dependencia en particular o si no reporte_nombreReporte.
- [x] 12. En la lista desplegable solo debe aparecer las dependencias que formulan y realizan seguimiento al plan de acción. En la actualidad aparecen áreas de las dependencias lo cual dificulta la búsqueda de la unidad requerida. [(Aplicar filtro de dependencias)](https://github.com/udistrital/planeacion_mid/commit/91ceb94a7fa88a4a818b09ea4ce5903ca915f9e9). 

**Criterios de aceptación**

- [x] Se revisan cada una de las modificaciones solicitadas por el usuario dándo un concepto de: "Por corregir", "Ya se encuentra implementado".
- [x] Se realizan las correcciones identificadas por el concepto previo.
- [x] Se prueban funcionalmente las correcciones implementadas.

**Requerimientos**

- Finalizar issue #1150 .

**Dependencias**

- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
> [@Mechaz123](https://github.com/Mechaz123) por favor ajustar con base en lo comentado en [#1255 (comment)](https://github.com/udistrital/planeacion_cliente/issues/1255#issuecomment-2245587890)

# AVANCE CON RESPECTO AL AJUSTE #

- Se realizó la modificación para la gráfica de avance general para realizar la multiplicación del 0.25 de las actividades con denominador variable.

![Image](https://github.com/user-attachments/assets/632a96e9-64e4-4c86-9231-9a45489d9b72)

- Por otra parte, se hizo el cambio en la gráfica de avance general para que sume el avance general de los diferentes trimestres, ya que antes solo mostraba en la gráfica el avance general de ese trimestre en específico.

![Image](https://github.com/user-attachments/assets/c939202a-0e24-48c7-ad07-118ed5ed3228)

**En este caso el avance del primer trimestre fue 18,75% y en el segundo trimestre fue de 17,70 % dando como resultado 36,45% por lo cual la gráfica de avance general es correcta**

**NOTA: Aún se debe comprobar con el usuario si los valores de Cumplimiento por actividad son correctos, ya que se lleva es un acumulado de la actividad en los diferentes trimestres**

# NOTA IMPORTANTE #
- Se realizará el caso donde se presente el 5/0, para ver si el sistema se encuentra validado para dicha expresión matemática, para numerador y denominador.
- Se debe corregir el cálculo de la brecha, ya que la meta es un dato que se debe digitar por parte del usuario, este se debe hacer con respecto a ese valor ingresado, no se puede dejar como valor por default "1".
- Se debe realizar el caso donde se agregan diferentes tipos de denominadores en una actividad, donde sean un primer indicador de tipo "Denominador fijo" y otro denominador de tipo "Denominador variable".

**Comment by Mechaz123** [comment]
# CASO DE DIVISIÓN 5/0 #

- El sistema se encuentra validado para no permitir ese tipo de divisiones

![Image](https://github.com/user-attachments/assets/6abc5f0e-9842-4f11-a8e9-d7d9ccd017ec)

**Comment by ccmendezt** [comment]
## Evidencias - Ajustes salida a producción nuevos
### 25/07/2024 - 11:20

- ### Item 10. Incluir en el reporte la columna correspondiente al “criterio del indicador”.

Se incluyó la columna _Criterio del indicador_ en los reportes cuya categoría es **Plan de acción** y el tipo de reporte es **Por unidad** o **General**:
    - **Reporte por unidad:**
    ![image](https://github.com/user-attachments/assets/ec20de07-896c-4fde-989d-bbd8ab4e058d)
    - **Reporte general:**
    ![image](https://github.com/user-attachments/assets/6d762ec2-34b6-443f-8937-a4ee7ebcd734)

- ### Item 11. La denominación del archivo Excel “reporte” que se descarga del sistema debe ser el nombre de la dependencia en dado caso que el filtro haya sido con alguna dependencia en particular o si no reporte_nombreReporte.

Se cambió la denominación de los reportes según lo que el SM/Líder Técnico acordó con el cliente, los nombres de reportes se muestran de la siguiente manera:
![image](https://github.com/user-attachments/assets/d0e172ed-41c0-4274-b16f-79de9d109eb9)

**Comment by ccmendezt** [comment]
## Evidencias - Ajustes salida a producción nuevos
### 25/07/2024 - 19:55

- ### Item 12. En la lista desplegable solo debe aparecer las dependencias que formulan y realizan seguimiento al plan de acción. En la actualidad aparecen áreas de las dependencias lo cual dificulta la búsqueda de la unidad requerida. [(Aplicar filtro de dependencias)](https://github.com/udistrital/planeacion_mid/commit/91ceb94a7fa88a4a818b09ea4ce5903ca915f9e9).

Se aplicó el filtro mostrado en el siguiente commit: https://github.com/udistrital/planeacion_mid/commit/b08a88bb304932ced9da373231063e689c111208

Adicionalmente, se corrigió el filtro de registros de periodo-seguimiento ya que se estaba haciendo de manera errónea en _evaluacion.helper.go_

## Commits/Pull Request asociados a Issue
- **planeacion_mid:** https://github.com/udistrital/planeacion_mid/pull/602
- **planeacion_cliente:** https://github.com/udistrital/planeacion_cliente/pull/1279

**Comment by Mechaz123** [comment]
> [@Mechaz123](https://github.com/Mechaz123) excelente trabajo, por favor revisar:
> 
> * El cálculo de la brecha en evaluación y consulta planes de acción seguimiento
> * La relación entre actividad e indicadores cuándo hay más de un indicador por actividad.
> * Revisar los cálculos y redondeos.

# AVANCE CON RESPECTO A LA REVISIÓN #

## RELACIÓN ENTRE INDICADORES Y ACTIVIDADES ##
El error que se venía presentando con respecto a los indicadores de las actividades, era debido a un valor dentro de la función llamado "maxIndex", a continuación, se hace la impresión del MID con dicha variable cuando se realizaba el guardado de 2 actividades:

 - **Actividad 1**

![Image](https://github.com/user-attachments/assets/b093180b-e1c8-4e86-afa1-9dc2e91ce733)

![Image](https://github.com/user-attachments/assets/f6d85bcd-f18b-4b43-9126-d62aa6c4af44)

 - **Actividad 2**

![Image](https://github.com/user-attachments/assets/4afc0593-0287-4f49-97f8-a51ad6d2eb53)

![Image](https://github.com/user-attachments/assets/f578f64b-8eeb-4795-a3cd-67cfdf1a8e0d)

**NOTA: Como se puede apreciar en el video al momento de ingresar la segunda actividad había cosas que se ingresaban en el index 1, de manera que esta era la razón de dicho comportamiento en el sistema.**

### A continuación, se presenta un video de la formulación realizada con la corrección ###
-  Link del video: https://udistritaleduco-my.sharepoint.com/:v:/g/personal/daarojasg_udistrital_edu_co/EZ38i-WWb_JBj2oj0A_E0YIBvqosRijcuvAuO3FF6TdZrQ?e=BJC7D8

**Comment by Mechaz123** [comment]
# PULL REQUEST #
Se adjuntan los PR de lo desarrollado:
- PLANEACION_CLIENTE: https://github.com/udistrital/planeacion_cliente/pull/1282
- PLANEACION_MID: https://github.com/udistrital/planeacion_mid/pull/604

**Comment by Mechaz123** [comment]
# AVANCE CON SCRIPT PARA CALCULO #
- Se realiza un avance del Script, para el recalculo del seguimiento para la parte cuantitativa:

![Image](https://github.com/user-attachments/assets/69d38538-78a3-4cdb-8eda-4e8f87be0411)

## NOTA IMPORTANTE ##
- Hay varios planes que se encuentran sin denominador, pero su cálculo parece indicar que pueden ser "Denominador variable" o "Denominador Fijo", como se muestra en las siguientes imagenes:

### POSIBLEMENTE DENOMINADOR VARIABLE ###

![Image](https://github.com/user-attachments/assets/b480e862-92b9-4efe-96a9-7236f6d70945)

### POSIBLEMENTE DENOMINADOR FIJO ###

![Image](https://github.com/user-attachments/assets/5dc03304-6067-4494-bec8-b7e574d37df8)

- Así mismo se ha hecho una prueba de cuales indicadores tiene dicho campo en blanco y cuales no:

![Image](https://github.com/user-attachments/assets/57f6072e-fdd7-4578-85a3-cc9d5a7ca38a)

**Comment by ccmendezt** [comment]
## Evidencias - Ajustes salida a producción nuevos (Parte 2)
### 30/07/2024 - 15:30

- Se ajustó el **Reporte de evaluación** para que las celdas de armonización PED y PI se ajusten correctamente al reporte:
    **- Antes:**
    ![image](https://github.com/user-attachments/assets/b32e2ef4-5365-4fea-839c-7b4e91c86bc7)

    **- Después:**
    ![image](https://github.com/user-attachments/assets/07e6ec5d-5792-4278-9cc8-9dbeadb1404f)


- Se ajustó el **Reporte de Plan de Acción por Unidad** para que las celdas de indicadores por actividad salgan combinadas según sea el caso:

    **- Antes:**
    ![image](https://github.com/user-attachments/assets/0d3b5490-f8f3-4db3-b663-5ae0131db1ff)

    **- Después:**
    ![image](https://github.com/user-attachments/assets/3e0e7902-4642-4d03-8733-20198fd5b6d5)
    
    **- Antes:**
    ![image](https://github.com/user-attachments/assets/c5d9c83e-d0b1-4650-a12a-1c788faea464)

    **- Después:**
    ![image](https://github.com/user-attachments/assets/ee957743-fad4-44ae-80ee-f6bc8faae2be)

Dicho cambio también se implementó en el **Reporte de Plan de Acción General**, ya que en esencia es el mismo solo que recopila las unidades para el plan y estado establecido.

## Pull Request asociados a Issue
- **planeacion_mid:** https://github.com/udistrital/planeacion_mid/pull/605
