### ISSUE TITLE
Pruebas funcionales Salida a producción 9/08

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1269]
Se requiere realizar continuar con las pruebas completas de todos los módulos de SISGPLAN, teniendo en cuenta la solución y hallazgos de bugs encontrados en los sprint 11, 12, 13, 14, y 15.

**Especificaciones técnicas**

1. Continuar con las pruebas funcionales deben cubrir todos los desarrollos hasta este sprint.
2. Se deben tomar como guía las pruebas realizadas por los desarrolladores en local en cada implementación.
3. El documento de pruebas debe especificar el estado en el que se encuentra el desarrollo, si se valida o no su funcionamiento y las observaciones correspondientes.
4. Tener encuenta los usuarios:
- pruebasoas1 - asistente_planeacion
- pruebasplaneacion - planeacion
- unidadtest - jefe_dependencia
- unidadtest2 - asitente_dependencia
5. Se deben probar solamente los desarrollos, las tareas de análisis o documentación no se tienen en cuenta.
6. Tener en cuenta el diagrama de estados: https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EapOYSf6DV5OpY_6uS7AXIkBLrxapQdD9iheXN88g8Hilg?e=XVQhNQ
7. Se trata de hacer un compendio de todas las pruebas realizadas hasta la fecha en un documento y validar su funcionamiento.
8. Adicional al documento que se debe presentar con las pruebas, se requiere realizar una anotación y seguimiento en forma de comentarios en este issue, de tal forma que se evidencien las pruebas realizadas en cada desarrollo y si aprueban o no. Tomar como guía: https://github.com/udistrital/sga_documentacion/issues/42
9. Carpeta para pruebas funcionales: https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EvgM4KowvOBKjdXD3aFLGV0BGcATolW8LorkydQUQnYMuA?e=MZjaiw
10. Se puede realizar en una nueva hoja de las pruebas realizadas inicialmente para este despliegue.

**Sub Tareas**

- [x] Realizar pruebas funcionales en ambiente de pruebas - SISGPLAN.
- [x] Seguimiento de pruebas funcionales en el issue.
- [ ] Corrección de errores

**Criterios de aceptación**

- [ ] Se presenta un documento con pruebas de todo el sistema.
- [ ] Se presenta el seguimiento de las pruebas realizadas en el issue, asociadas a cada desarrollo.
- [ ] Se presenta documento con errores corregidos

**Requerimientos**

- No presenta.

**Dependencias**

- planeacion_cliente.
- planeacion_mid.
- planes_crud.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by ccmendezt** [comment]
## Evidencias - Corrección errores encontrados en pruebas funcionales
### 31/07/2024 - 14:25

- Se corrigió la funcionalidad de editar plan en el submódulo de consultar plan y construir plan/proyecto:

    - Consultar plan/proyecto:
    ![consultar-planes-proyectos](https://github.com/user-attachments/assets/d891fe0d-48c2-4910-9719-3d3146421d44)
 
    - Construir plan/proyecto:
    ![construir-planes-proyectos](https://github.com/user-attachments/assets/b531d79d-f496-41b9-82a6-166298920ee7)

## Pull Request asociados a Issue
- **planeacion_cliente:** https://github.com/udistrital/planeacion_cliente/pull/1297

**Comment by Mechaz123** [comment]
# Pull Request de corrección de autoselección de PED y PI #

- Planeación cliente: https://github.com/udistrital/planeacion_cliente/pull/1311

**Comment by Mechaz123** [comment]
# AVANCE DE CALCULOS EN EVALUACIÓN #

## Para Denominador Variable ##
- Se aplicó la corrección en el cálculo, para el indicador acumulado usando la formula **(Númerador Acumulado / Denominador Acumulado) x 0.25** para el primer trimestre.
- Se aplicó la corrección en el cálculo, para el indicador acumulado usando la formula **(Númerador Acumulado / Denominador Acumulado) x 0.50** para el segundo trimestre.
-  Se aplicó la corrección en el cálculo, para el indicador acumulado usando la formula **(Númerador Acumulado / Denominador Acumulado) x 0.75** para el tercero trimestre.
- Se aplicó la corrección en el cálculo, para el indicador acumulado usando la formula **(Númerador Acumulado / Denominador Acumulado)** para el cuarto trimestre.

## Caso de muestra ##

- Para este caso la segunda actividad tiene un indicador del tipo **"Denominador variable"** y en el primer trimestre se define un 10/10.

![Image](https://github.com/user-attachments/assets/58ce780f-0380-4c61-a1d1-31048e0572ba)

Por lo cual el cálculo sería: **((10/10) x 0.25) x 100 = 25**

- En el segundo trimestre tiene un avance de 5/10

![Image](https://github.com/user-attachments/assets/dea06860-9681-47c6-b113-96973022e9b2)

Por lo cual el cálculo sería: **((15/20) x 0.50) x 100 = 37.50**

**Comment by ccmendezt** [comment]
## Evidencias - Corrección errores encontrados en pruebas funcionales
### 05/08/2024 - 12:10

- Se corrigió el versionamiento de un nuevo plan en el estado _Pre-Aval_:
![realizar-ajustes-pre-aval](https://github.com/user-attachments/assets/2448e515-7be1-4092-87d4-8ffa761f27bd)

- Se corrigió el funcionamiento del módulo de evaluación:
![image](https://github.com/user-attachments/assets/b288419c-7eec-474f-89c7-80be574e2c17)
![image](https://github.com/user-attachments/assets/1d22231a-0a4a-4fb2-ac94-d948952cdcbd)
![image](https://github.com/user-attachments/assets/4ddcb92e-bce5-4d2b-b228-9cdbf9b3af4d)

- Se actualizó el [**Excel**](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ETwDpgZ4HwVFmdijMR4wvTMBKVSce-zl13WOYCk8MCFdYw?e=Fd5uAW) de pruebas funcionales con las correcciones realizadas.

## Notas importantes:
  **i.** Se continúa probando todo el flujo del sistema con el propósito de encontrar errores/oportunidades de mejora.

**Comment by Mechaz123** [comment]
# PULL REQUEST #
- PR planeacion_cliente: https://github.com/udistrital/planeacion_cliente/pull/1325
- PR planeacion_mid: https://github.com/udistrital/planeacion_mid/pull/612

**Comment by Mechaz123** [comment]
# AVANCE SCRIPT #

- Se realizó el script con respecto al método existente para los cálculos en seguimiento, sin embargo, al momento de ejecutar el script los valores en la mayoría de los casos se están quedando en valores negativos y demás, teniendo en cuenta que los cálculos en seguimiento se tendrán que volver a definir, la tarea se pospone hasta que se realice la corrección de dichos cálculos, para que estos sean implementados en el script.

![Image](https://github.com/user-attachments/assets/d9ee908d-ffc0-4414-ad8a-fb742743680f)

## NOTA ##

- Se queda a la espera de la definición de los nuevos cálculos o fórmulas para el módulo de seguimiento.

**Comment by ccmendezt** [comment]
## Evidencias - Avance Script Migración DB Develop
### 12/08/2024 - 20:40

- Se creó el PAF Formato llamado: **Plan Generico 2021-2024** que permitirá parametrizar las fechas para todos los planes de acción con el antiguo modelo de datos usado en _planes_crud_.
- Se desarrolló un script que permite migrar todos los planes con el modelo de datos antiguos al modelo de datos nuevo usado en _planes_crud_. Para esto se realiza lo siguiente:

- **Para todas las Vigencias**:

    1. Se enlistan los periodo_seguimiento_id antiguos de las vigencias 2022 y 2023.
    2. Se obtienen los datos relevantes del **Plan Generico 2021-2024**.
    3. Se obtienen las unidades de interés para la creación de los registros en la colección _periodo-seguimiento_.

- **Para la Vigencia 2022**:

    1. Se actualizan los planes de acción con el formato obtenido anteriormente. Solo se actualizan los planes cuya vigencia_id corresponda a la 2022 de develop, cuyo tipo plan sea PAF y cuyo parámetro nueva_estructura NO exista en los registros.
    2. Se crean e insertan los registros en la colección periodo-seguimiento con el periodo_id dado para la vigencia y trimestres de 2022.
    3. Se obtienen los registros de la colección _seguimiento_ cuyos periodo_seguimiento_id sea igual a los periodo_seguimiento_id antiguos de la vigencia 2022.
    4. Se actualizan los periodo_seguimiento_id de los registros obtenidos en el paso 5 por los insertados en el paso 4.

- **Para la Vigencia 2023**:

    1. Se actualizan los planes de acción con el formato obtenido anteriormente. Solo se actualizan los planes cuya vigencia_id corresponda a la 2023 de develop, cuyo tipo plan sea PAF y cuyo parámetro nueva_estructura NO exista en los registros.
    2. Se crean e insertan los registros en la colección periodo-seguimiento con el periodo_id dado para la vigencia y trimestres de 2023.
    3. Se obtienen los registros de la colección _seguimiento_ cuyos periodo_seguimiento_id sea igual a los periodo_seguimiento_id antiguos de la vigencia 2023.
    4.  Se actualizan los periodo_seguimiento_id de los registros obtenidos en el paso 3 por los insertados en el paso 2.

- **Para la Vigencia 2024**:

    1. Se actualizan los planes de acción con el formato obtenido anteriormente. Solo se actualizan los planes cuya vigencia_id corresponda a la 2024 de develop, cuyo tipo plan sea PAF y cuyo parámetro nueva_estructura NO exista en los registros.
    2. Se crean e insertan los registros en la colección periodo-seguimiento con el periodo_id dado para la vigencia y trimestres de 2024.


## Script Migración DB
[MigracionBDDesarrollo.zip](https://github.com/user-attachments/files/16593375/MigracionBDDesarrollo.zip)

## Notas importantes:
  **i.** Para la vigencia 2024 no fue necesario actualizar registros de seguimiento dado que no existen planes avalados con el antiguo modelo de datos.
