### ISSUE TITLE
Apropiación de Generalidades - Plantillas

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1272]
Con base en lo implementado en [Plantillas](https://github.com/orgs/udistrital/projects/40),  se requiere realizar la apropiación de generalidades con el fin de identificar el estado actual del sistema de plantillas y los elementos necesarios para retomar su desarrollo.

**Aspectos Técnicos**

- los repositorios del sistema de plantillas son:
1. [plantillas_cliente](https://github.com/udistrital/plantillas_cliente)
2. [plantillas_mid](https://github.com/udistrital/plantillas_mid)
3. [plantillas_crud](https://github.com/udistrital/plantillas_crud)

- [Historias de Usuario](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EZI5GpJBXzpBg2jWJvIXHKAB4p7h2UtQi0Uq0EylrnUo4g?e=RWr4b6) relacionadas con el desarrollo del sistema de plantillas.
- [Documentación](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EgVCEkRzaDNEh8VrGesgTWAB29_7AfuU0z-Ks1lWltFMOg?e=dCPeRK) del sistema de plantillas.
- Se debe identificar el estado actual del sistema de plantillas, ejecutando en local el sistema, determinando que nivel de avance se tiene con base en las HUs.
- Se debe determinar si el desarrollo actual cumple con lo necesario para continuar con el desarrollo del sistema (en términos de dinamicidad) o si se requiere iniciar de nuevo con otro enfoque. Se recuerda que el objetivo de este sistema es poder crear plantillas de forma dinámica para cualquier sistema, y que estas puedan ser utilizadas por los mismos.
- Se debe proponer una arquitectura alternativa del sistema en términos de Microservicios y Microclientes.

**Sub Tareas**

- [x] Estudio de documentación.
- [x] Instalación y prueba en local del sistema.
- [x] Documentación de estado actual del sistema.
- [x] Evaluación del cumplimiento de metas del sistema.
- [ ] Propuesta de nueva arquitectura para el sistema.

**Criterios de aceptación**

- [x] El desarrollo entiende en su totalidad el modelo de negocio del sistema.
- [x] El sistema es probado en local.
- [x] Se presenta el estado actual del sistema, con bondades y limitaciones.
- [x] Se evalúa si el sistema cumple o no con lo que se espera del mismo.
- [ ] Se presenta la nueva arquitectura del sistema en términos de Microservicios y Microclientes.

**Requerimientos**

No aplica

**Dependencias**

- plantillas_cliente
- plantillas_mid
- plantillas_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
@Oscarjaimes1710 Por favor actualizar issue con los avances realizados durante la semana.

**Comment by Oscarjaimes1710** [comment]
1. Se hace Estudio de toda la documentación encontrada entre ellas la historias de usuario, diagrama de flujo, entre otros. 

2. Se hace la descarga en local del cliente , mid y crud de plantilas, sin embargo solamente se ha podido realizar la ejecución y subida de el cliente de plantillas que actualmente esta así: 
![Captura de pantalla 2024-07-31 a la(s) 6 14 20 p  m](https://github.com/user-attachments/assets/bd55ff62-1dd3-40a0-90e1-63202c50629e)
![Captura de pantalla 2024-07-31 a la(s) 6 14 15 p  m](https://github.com/user-attachments/assets/69892f4e-934d-48e8-90d8-63ae5decfcfd)
![Captura de pantalla 2024-07-31 a la(s) 6 13 53 p  m](https://github.com/user-attachments/assets/05e03683-a753-4174-9bf3-7176a314d44c)

El Crud no se ha podido ejecutar en local puesto que no hay documentación ni explicación, adicionalmente es un crud_serverless. 

3. Estado actual del sistema: El sistema se encuentra implementado pero no esta desplegado en ninguna instancia. 
-El sistema actualmente se encuentra en fase de desarrollo solamente en el cliente no hay hasta el momento ninguna            implementación  del mid que se pueda probar o realizar un análisis de estado. 
-Basado en el flujo se encuentra que aun no se ha desarrollado por completo el menú de plantillas.
-Se encuentra la estructura actual del modelo puesto que se hizo una re-estructuración del planteamiento inicial del modelo y actualmente quedo implementado como se indica acá: https://github.com/udistrital/plantillas_cliente/issues/13#issuecomment-1852755720 . En el campo contenido es donde queda almacenada toda la información de la plantilla para posteriormente ser consumida y desglosada. 
-Se hace un análisis actual del alcance de este modelo y se llega a la conclusión que cumple con lo requerido pero requiere unos pequeños ajustes.

4. Evaluación de cumplimiento de metas basado en el estado actual:  

- A. Ingreso de apliacion: Cumplida. 
- B. Menu de plantillas : 50% de la meta esperada. 
- C. Crear plantilla : En fase de desarrollo con una base de elementos sentada como se ve en la siguiente imagen: 
![Captura de pantalla 2024-07-31 a la(s) 7 16 18 p  m](https://github.com/user-attachments/assets/4ab00897-d31c-470a-a666-ac5bf75e23bb)

-  Seleccionar una plantilla: Se encuentra en fase de desarrollo visual aun no tiene ninguna funcionalidad vigente o con lógica que requiera el mid o crud para traer alguna plantilla. 

![Captura de pantalla 2024-07-31 a la(s) 7 18 33 p  m](https://github.com/user-attachments/assets/c6ec9778-5315-4c35-a675-4fdd668ad084)

- Duplicar/Copiar Plantilla: 0% Ejecutado 
- Eliminar plantilla: 0% de ejecución solamente el botón de eliminar de forma visual. 
- Vista previa del documento: 0% de ejecución, solamente documento de prueba de visualización pero sin esta fundamentado en alguna plantilla.
- Historial de versión: Sin implementar. 

5. Actualmente se trabaja en el planteamiento de si realmente se requiere una nueva Arquitectura pues la que se tiene actualmente se puede decir a que a grandes rasgos cumple con el alcance deseado, sin embargo se deben hacer unos ajustes tales como: 

- Cambiar el campo VersionActual en el modelo por Plantilla_Estado esto teniendo en cuenta que se debe hacer un ajuste en el modelo para la referencia de las distintas versiones presentadas para una plantilla. Entonces se plantea en que los Id de las diferentes versiones vayan dirigidos en el orden de un Id_Padre y hereda para un Id_Hijo Cada vez que se genera una versión nueva de tal forma que genere el sistema una referencia entre versiónes basado en el Id. 
- Replanteamiento del json que contendría todo el flujo de datos de contenido de la plantilla de tal forma que funcione con niveles y sub-niveles teniendo en cuenta que todas las posibles secciones tengan sub-secciones y sub-secciones de la sub-seccion. Esto para que la estructura este en forma de Arbol y sea mucho mas manipulable al hacer el envió hacia el mid para su posterior procesamiento.

**Comment by Oscarjaimes1710** [comment]
La nueva Arquitectura no se presenta hasta no tener el nuevo modelo de la Base de datos.

**Comment by a52290451** [comment]
Se da por finalizada la Issue
