### ISSUE TITLE
Documentación y pruebas en ambiente de pruebas NOTIFICACIONES

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1284]
Se requiere actualizar la documentación técnica de notificaciones internas, teniendo en cuenta los cambios realizados con la adición de notificaciones_crud como API gestora de la BD y nuevos métodos implementados, así como la optimización de diversas características de notificaciones. Adicionalmente, se requiere realizar y documentar pruebas funcionales de notificaciones tanto en el monolito como en la nueva arquitectura de SISGPLAN, de tal forma que se evidencie su correcto funcionamiento.

**Aspectos técnicos**

- notificacion_crud se encuentra en ambiente de pruebas completamente funcional.
- la documentación de notificacioens internas se encuentra en:  #1042 .
- Se requiere actualizar la documentación de notificaciones agregando detalles relacionados con el nuevo API de notificaciones_crud, nuevos metodos desarrollados para la consulta y guardado de notificaciones y optimizaciones realizadas a nivel general. Esta documentación debe abordar la implementación realizada a nivel de monolito y a nivel de MFs.
- Se deben realizar pruebas funcionales y documentarlas en el archivo previsto en ambiente de pruebas.

**Sub Tareas**

- [x] Documentación notificaciones internas.
- [x] Pruebas funcionales notificaciones internas en Monolito.
- [x] Pruebas funcionales notificaciones internas en MFs.

**Criterios de aceptación**

- [x] La Documentación de Notificaciones Internas se encuentra debidamente actualizada.
- [x] Las pruebas funcionales de SISGPLAN a nivel de notificaciones internas se encuentran finalizadas y documentadas.

**Requerimientos**

- [x] Finalizar Issue #1223 .
- [x] Finalizar Issue #1237 .
- [x] Finalizar Issue #1253 .
- [x] Finalizar Issue #1270 .

**Dependencias**

- notificaciones_crud
- notificaciones_mid
- web-componnets
- assets
- planeacion_cliente

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Documento en desarrollo, alojado en: 
[Documento Técnico notificaciones_crud](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EfIecrKdSgFJuN6kvYsrod4Bbknc1tT7ZQxSSFOP8jQ4Ww?e=km8K8s)

**Comment by a52290451** [comment]
Se requiere ajustar documentación técnica de Notificaciones de acuerdo a la siguiente guía:

https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EcIfzzZkICtGsJpIPN-BcW4BRu-q_OECUVcKn2lkjmj7xg?e=WaypbH

**Comment by diegobauto** [comment]
Documento terminado. Se realizan modificaciones en el documento y el documento se añade en la carpeta correspondiente anteriormente mencionada, por favor revisar: 

[Documento Técnico notificaciones_crud](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EagFPm9pKfRLn1JZrfVCl9EBPye3vjDMgIbNMdwFwGOobg?e=VyDTuB)

**Comment by diegobauto** [comment]
Se añade realización de pruebas funcionales en ambiente de pruebas:

[Pruebas funcionales - Notificaciones crud ambiente pruebas](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EcW9xCYkFcVHnwO5wYIuVpwBmrcfLRJkyrF_Zju7EKuHCA?e=5Nsd4s)

Visualización prueba websocket por video:

[Grabación de pantalla desde 02-08-24 13:09:47.webm](https://github.com/user-attachments/assets/18c1ccac-4110-4224-be62-d5aaad18c1f9)

Visualización prueba redirección (formulación) por video:

[Grabación de pantalla desde 03-08-24 13:03:20.webm](https://github.com/user-attachments/assets/9b059231-69b7-43f2-a3d5-2b7421a7a7a5)

Visualización prueba redirección (seguimiento) por video:

[Grabación de pantalla desde 03-08-24 13:05:00.webm](https://github.com/user-attachments/assets/45144658-0a5b-45c0-8267-aa531841cd96)

**Comment by a52290451** [comment]
De finaliza issue.
