### ISSUE TITLE
Ajustes de compilado del presupuesto del plan de acción de funcionamiento 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#131]
Se debe realizar el ajuste para la asignación de la parte presupuesta no por actividad si no todo el plan de acción para los campos de presupuesto ( Código del rubro, Nombre del rubro y Valor) , la issue debe cumplir con los siguientes requerimientos:

- [x] Analizar como realizar el ajustes ( componente construcción y formulario dinámico) 
- [ ] Realizar el ajuste para formular de forma de compilado el presupuesto en un plan de acción de funcionamiento 
- [ ] Realizar ajuste en la tabla resumen para la visualización del compilado el presupuesto en un plan de acción de funcionamiento

**Comment by brayaned** [comment]
Se da inicio a la issue.

**Comment by brayaned** [comment]
Después de un análisis por parte del líder técnico (@fabianbarreto02 ) y el analista de requerimientos se decidió parar esta tarea, ya que, dentro del sistema no se ve necesario la implementación de este compilado de presupuesto.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
