### ISSUE TITLE
Reformulación de planes de acción FASE 2- PARTE 4

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1314]
Se requiere finalizar con el desarrollo en Evaluación y Reportes, de forma que se puedan visualizar planes de acción con reformulación. Además, se debe agregar un módulo de fechas para la reformulación de planes de acción, que cumpla con las mismas condiciones del modulo de fechas actual implementado para formulación y seguimiento.

**Aspectos Técnicos**

1. La reformulación de planes de acción se debe realizar sobre un plan que se encuentre en seguimiento.
2. La reformulación solo aplica para Trimestres que presenten un estado diferente a "**Avalado**".
3. Todos los trimestres posteriores al trimestre sobre el cual se reformula un plan, también deben ser reformulados, actualizando su contenido.
4. Los trimestres que ya se encuentran "Avalados" no podrán ser reformulados. Deben mantenerse con la estructura actual.
5. Si un plan es reformulado en un trimestre particular, por ejemplo, T3, los trimestres anteriores que ya deben estar en estado "Avalado", deben mantenerse con su estructura original. La reformulación solo aplica para el trimestre actual y los trimestres posteriores.
6. (BAJA PRIORIDAD) Al igual que como se hace para formulación y seguimiento, se deben habilitar fechas específicas para reformulación.
7. Para la reformulación, cuando esta sea aprobada por **PLANEACIÓN**, se debe cargar la vista de formulación en una nueva versión con la información diligenciada por la unidad en su momento. El proceso de reformulación es igual al de formulación, debe pasar por todos los estados nuevamente, sin embargo, no es la formulación original y esta diferencia debe estar marcada en el sistema para que solo afecte a los trimestres posibles. (Diferenciación de flujos).
8. Se debe verificar que implicaciones presenta la diferenciación de flujos (formulación y reformulación) en todos los aspectos del sistema.
9. De acuerdo con lo realizado en #1285 , se requiere desarrollar los ajustes necesarios en Evaluación y Reportes, de tal forma que SISGPLAN pueda soportar la visualización de este tipo de planes en los módulos mencionados.

**Sub Tareas**

- [x] Reformulación en Evaluación y Reportes.

**Criterios de aceptación**

- [x] El sistema permite la reformulación de planes de acción en Evaluación y Reportes.

**Requerimientos**

- Finalizar issue #1285 .

**Dependencias**

- planeacion_seguimiento_mf
- planeacion_formulacion_mf
- planeacion_seguimiento_mid
- planeacion_seguimiento_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
@felimarod se requiere actualización del estado de esta issue

**Comment by felimarod** [comment]
La tarea se ha visto retrasada debido a imprevistos y fallos en la lógica desarrollada en las partes anteriores. Se está trabajando para ponerla al día.

**Comment by a52290451** [comment]
@felimarod actualizar estado de la actividad

**Comment by felimarod** [comment]
Se avanzó en la parte de evaluación quedando de la siguiente manera:
![image](https://github.com/user-attachments/assets/519abfd5-7cc5-4046-9087-e1893785e38d)

[Grabación de pantalla desde 2024-08-20 08-09-21.webm](https://github.com/user-attachments/assets/35fa2194-9fce-4b69-a626-da865c39ef66)

**Notas:** Los avances completos se basan en el último trimestre y los valores que tenga almacenados al avalar los reportes desde el seguimiento

**Comment by felimarod** [comment]
Pull Request asociadas con la issue:

- https://github.com/udistrital/planeacion_seguimiento_mid/pull/18
  Se agrego un endpoint para obtener todos los seguimientos asociados a un plan_id
- https://github.com/udistrital/planeacion_evaluacion_mid/pull/17
  Se actualizo el endpoint que obtiene la evaluación de un plan, para utilizar el endpoint creado en la PR anterior
- https://github.com/udistrital/planeacion_evaluacion_mf/pull/15
  Se actualizó la interacción con el endpoint de evaluación para soportar los requerimientos de la reformulación

**Comment by a52290451** [comment]
Se completa Reformulación de planes de acción en evaluación.

Queda pendiente despliegue en ambiente de pruebas.
