### ISSUE TITLE
Revisión de código implementado y buenas practicas. (listado de funcionalidades)

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1316]
Se requiere llevar a cabo la revisión de código implementado en el módulo de plantillas, a fin de identificar su estado actual en cuanto a funcionalidades y lo que hace falta por desarrollar. En cada caso es necesario señalar si se han seguido buenas practicas de desarrollo o, por el contrario, es necesario realizar una optimización en el código.

**Especificaciones técnicas**

- se requiere realizar un listado de las funcionalidades implementadas según la revisión de código.
- Se requiere identificar en cada caso, y de acuerdo a los lineamientos de desarrollo de la OATI, si es necesario o no la optimización de código.

**Sub Tareas**

- [x] Listado de funcionalidades implementadas (tanto en el mid, como su visualización en el cliente).
- [x] Observaciones y comentarios relacionados a buenas prácticas de desarrollo.

**Criterios de aceptación**

- [x] Se presenta un listado con las funcionalidades implementadas del sistema.
- [ ] Se presentan las observaciones de cada funcionalidad.

**Requerimientos**

No aplica

**Dependencias**

- plantillas_crud
- plantillas_mid
- plantillas_cliente

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
@Oscarjaimes1710 se requiere actualización del estado de esta issue.

**Comment by Oscarjaimes1710** [comment]
<img width="1265" alt="Captura de pantalla 2024-08-09 a la(s) 7 10 37 p  m" src="https://github.com/user-attachments/assets/6204245c-ba75-419b-b12d-9630e02bdb00">
<img width="1265" alt="Captura de pantalla 2024-08-09 a la(s) 7 10 40 p  m" src="https://github.com/user-attachments/assets/3efce42d-2586-450a-a113-9099509edede">

Actualmente se tiene en ejecución el sistema y me encuentro haciendo el análisis de todo el código que esta actualmente desarrollado y haciendo también el listado de todas las funcionalidades para así poder generar un resumen y desarrollo de la issue según lo solicitado.

**Comment by a52290451** [comment]
@Oscarjaimes1710 por favor cargar avance del listado.

**Comment by Oscarjaimes1710** [comment]
Listado de las funcionalidades implementadas: 

1. Login de Ingreso a la aplicación: Actualmente Completamente funcional. Hace Falta corrección del logo de plantillas.
2.Menú de plantillas: Actualmente implementado,Falta completar el Menú con todas las funcionalidades requeridas: Actualmente solo esta Crear plantilla y Vista plantilla.
3. Crear plantilla: Funcional.
4. Editar plantilla: Componente creado solo visualmente. 
5. Duplicar/copiar Plantilla: No implementado ni desarrollado actualmente.
6. Eliminar Plantilla: Componente de vista de eliminar creado solamente de forma visual. 
7. Vista Previa del documento: Componente visual creado , se ejecuta crea una plantilla a raíz de un parámetro guardado previamente, requiere ajuste, planteamiento y revisión de la forma en la que genera el pdf. 
8. Historial de Versiones: No implementado actualmente. Cero Avance en el desarrollo de este componente.

**Comment by a52290451** [comment]
@Oscarjaimes1710 de acuerdo a lo señalado en revisión, por favor subir ajustes finales

**Comment by Oscarjaimes1710** [comment]
![Captura de pantalla 2024-08-15 a la(s) 3 07 57 p  m](https://github.com/user-attachments/assets/c422d24b-f87d-47f5-bae4-3c6120e8f9f1)

Se encuentra en fase de desarrollo el documento con el listado de funcionalidades a desarrollar junto con las revisión de código y el código actualmente ya implementado.

**Comment by Oscarjaimes1710** [comment]
Aquí el link donde esta el repositorio con el excel donde esta todo el análisis de plantillas incluido el Listado de funcionalidades a desarrollar. https://github.com/udistrital/planeacion_cliente/issues/1317.

-https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EUptQlUYzU1PugcscdyuOMMBRtDmZ3aILdQcjIeesBYf3A?e=BT57Yh

Conclusión Final: El archivo anterior proporciona un análisis exhaustivo del código actualmente implementado tanto en el mid como en el cliente. Incluye observaciones detalladas, un listado de buenas prácticas y lineamientos de desarrollo de OATI, así como un inventario de las funcionalidades ya implementadas y las pendientes de desarrollo.

**Comment by Oscarjaimes1710** [comment]
Lo anterior queda a consideración y revisión del líder @a52290451

**Comment by a52290451** [comment]
Se valida y aprueba listado, junto con observaciones.
