### ISSUE TITLE
Análisis y Construcción de base de datos - P1

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1318]
Se requiere llevar a cabo el análisis y construcción de la base de datos de plantillas, de acuerdo con el modelo de datos propuesto en #1292 .

**Especificaciones Técnicas**

- Se requiere llevar a cabo un análisis de rendimiento y de costos acerca de la infraestructura necesaria para implementar el modelo de datos. Este puede desarrollarse en Bases de datos relacionales o no relacionales, empleando una API CRUD para acceder a los datos, o utilizar serverless en AWS.
- Una vez realizado el análisis y elegida la infraestructura adecuada, se requiere realizar la implementación del modelo de datos.
- La base de datos debe cumplir con los lineamientos definidos por la OATI.

**Sub Tareas**

- [x] Análisis de implementación de BD.

**Criterios de aceptación**

- [x] Se elige correctamente la infraestructura sobre la cual se implementará el modelo de datos.

**Requerimientos**

No aplica

**Dependencias**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Oscarjaimes1710** [comment]
Local con VPN de OATI:
-Ventajas: Control total, sin dependencia de terceros, cumplimiento estricto de lineamientos de seguridad.

-Desventajas: Mayor costo inicial, mantenimiento continuo, escalabilidad limitada.

Serverless en AWS:

-Ventajas: Escalabilidad automática, pago por uso, infraestructura gestionada.

-Desventajas: Costos variables a largo plazo, dependencia del proveedor, cumplimiento de políticas de seguridad específicas.

**Comment by Oscarjaimes1710** [comment]
Serverless en AWS:

-Qué es: Serverless es un modelo de computación en la nube en AWS que permite ejecutar aplicaciones sin gestionar servidores. AWS maneja automáticamente la infraestructura, escalabilidad y disponibilidad.

-Funcionamiento: Las aplicaciones o bases de datos se ejecutan bajo demanda y se escalan automáticamente según el tráfico. Solo pagas por el tiempo de ejecución y los recursos consumidos.

Capacidad de Respuesta:

-Accesos y Velocidad: Altamente escalable y rápido, con tiempos de respuesta que pueden ser milisegundos. Ideal para aplicaciones con fluctuaciones en el tráfico.

¿Por qué Serverless?:

-Sí: Si necesitas escalabilidad, flexibilidad y no quieres preocuparte por la infraestructura, serverless es ideal.

-No: Si necesitas un control estricto, seguridad específica, o predecir con precisión los costos, podría no ser la mejor opción.

¿Por qué en Local con VPN de OATI?

Sí:
-Control y Seguridad: Ofrece control total sobre la infraestructura y datos, cumpliendo estrictamente con los lineamientos de seguridad de OATI.
-Conformidad: Ideal para entornos donde se requiere alta conformidad regulatoria y donde los datos sensibles deben permanecer en la red interna.
-Costos a Largo Plazo: Aunque los costos iniciales son altos, puede ser más económico a largo plazo si la demanda es constante.

No:
-Escalabilidad Limitada: Aumentar la capacidad requiere inversión en hardware.
-Mantenimiento: Requiere gestión continua, lo que puede ser un desafío operativo.

**Comment by a52290451** [comment]
De acuerdo con lo conversado con Infraestructura y DBAs, la mejor opción es utilizar serverless para acceder a la base de datos.
