### ISSUE TITLE
Crear  flujo de visualización de botones para cambio de estado según rol y estado del plan de acción 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#132]
Se debe realizar el desarrollo del flujo de visualización de los botones con funcionalidad para cambiar el estado de un plan, teniendo en cuenta el rol del usuario registrado en el sistema y el flujo de estados del plan de acción, la issue debe cumplir con los siguientes requerimientos:

- [x] Revisar e implementar la directiva que  oculta un componente segun el usuario registrado en el sistema, guiarse de la issue https://github.com/udistrital/sga_cliente/issues/558
- [x] Crear el flujo de los botones para cambiar el estado segun el estado que se encuentre y el rol del sistema

**Comment by brayaned** [comment]
Se da inicio a la issue.

**Comment by brayaned** [comment]
Se creó el flujo de visualización para los botones en los diferentes estados en los que puede estar un plan. Para esto se utilizó la directiva _ngIsGranted_. De acuerdo al rol se tienen en cuenta para la visualización de ciertos botones en cada uno de los diferentes estados.

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
