### ISSUE TITLE
Restricción de construcción de planes

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1327]
Se requiere restringir la creación de una nueva plantilla de plan en el módulo de construcción.

**Aspectos Técnicos**

1. El mid, crud y cliente están actualizados a día de hoy en las ramas release/0.0.1.
2. Actualmente la idea de flexibilidad sobre la creación de formatos "Plantillas" ha permitido la generación de planes de manera independiente, sin embargo, se requiere la restricción de ciertos aspectos que son necesarioas a lo largo del flujo de un plan de acción.

**Sub Tareas**

- [x] Se deben revisar cuales son todas las condiciones básicas para que un plan de acción se pueda llevar a cabo por los procesos de formulación, seguimiento y evaluación.
- [x] Con base en las condiciones básicas encontradas, se debe restringir en el módulo de construcción que un plan tenga dichas condiciones.
- [x] Al crear un nuevo plan de acción las condiciones básicas identificadas deben traerse por defecto de una manera inicial y no se deben permitir eliminar.

**Criterios de aceptación**

- [x] Se identifican las condiciones básicas para que un plan de acción cumpla con las características necesarias para pasar por los procesos de formulación, seguimiento y evaluación.
- [x] Se restringe el módulo de creación de planes de acción con base en las condiciones encontradas.
- [x] Al crear un nuevo plan, la estructura base que se crearía con base en las condiciones encontradas es traida por defecto.
- [x] Se prueba el sistema nuevamente

**Requerimientos**

- ninguno.

**Dependencias**

- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.
Se debe probar el correcto funcionamiento de todas las funcionalidades en nueva arquitectura.

**Comment by ccmendezt** [comment]
## Evidencias - Restricción de construcción de planes
### 16/08/2024 - 16:05

- Se agregó un parámetro en el módulo de parámetros cuyo código de abreviación es: **FORMATO_PAF** y tiene como función guardar el nombre del _Plan Formato_ de tipo _Plan de Acción de Funcionamiento_, dicho plan tendrá los niveles mínimos requeridos para el correcto funcionamiento del sistema en los módulos de _Formulación_, _Seguimiento_, _Evaluación_ y _Reportes_.

- Se agregó un endpoint en _planeacion_mid_ que permite clonar los hijos (niveles) del _Plan Formato_ obtenido mediante el código de abreviación **FORMATO_PAF** al plan formato que se está creando.

- Se agregó lógica en _planeacion_cliente_ que permite inhabilitar los inputs y radio button de los campos: _Nombre_, _Estado_, _Parámetros_ y _Obligatorio_ de todos los niveles del plan creado que fueron clonados al partir del Plan Formato, con el propósito de hacer inmodificables dichos campos para el correcto funcionamiento del sistema. Cuando se creen otros niveles, estos sí se podrán modificar ya que son niveles adicionales creados por el usuario.

## Pull Request asociados a Issue
- **planeacion_mid:** https://github.com/udistrital/planeacion_mid/pull/614
- **planeacion_cliente:** https://github.com/udistrital/planeacion_cliente/pull/1341

## Notas importantes:
  **i.** Las pruebas funcionales de la aplicación se subirán en un siguiente comentario.

**Comment by ccmendezt** [comment]
## Evidencias - Restricción de construcción de planes
### 20/08/2024 - 16:11

- Se adjunta prueba funcional de creación de un Plan de acción de funcionamiento como plantilla. Allí se evidencia que el plan se crea directamente con los niveles establecidos en el plan genérico:

![pruebaCreacionFormatoPAF](https://github.com/user-attachments/assets/8140105f-7333-49d8-bf07-87ef69e8bf24)

## Notas importantes:
   1. Luego de crear el Plan Formato en localhost, se continuó con la realización todo el flujo (formulación, seguimiento, evaluación y reportes) del plan creado en **pruebasplaneacion** y todo funcionó acorde a lo esperado. No hubo errores en el sistema.
   2. Se está esperando la actualización de Swagger para poder probar la funcionalidad en pruebasplaneacion, sin embargo, la prueba funcional mostrada anteriormente es con las versiones en _release_ (pero ejecutadas en **local**) de _planeacion_cliente_ y _planeacion_mid_
