### ISSUE TITLE
Estabilización de ambiente release MF

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1328]
Se requiere continuar con la migración de los desarrollos nuevos que se han realizado en el monolito.

**Especificaciones técnicas**

-Se han llevado a cabo los siguientes avances: #1196 #1222 #1236 #1256 #1267 #1312 
- Los repositorios de los mid son:

1. [planeacion_formulacion_mid](https://github.com/udistrital/planeacion_formulacion_mid)
2. [planeacion_seguimiento_mid](https://github.com/udistrital/planeacion_seguimiento_mid)
3. [planeacion_evaluacion_mid](https://github.com/udistrital/planeacion_evaluacion_mid)
4. [planeacion_reportes_mid](https://github.com/udistrital/planeacion_reportes_mid)
5. [planeacion_arbol_mid](https://github.com/udistrital/planeacion_arbol_mid)

- Los repositorios de los MF son: 

1. [Root](https://github.com/udistrital/planeacion_root_mf)
2. [Utilidades](https://github.com/udistrital/planeacion_utilidades_mf)(Revisar como mostrar la imagen base de SISGPLAN).
3. [Formulacion](https://github.com/udistrital/planeacion_formulacion_mf) 
4. [Seguimiento](https://github.com/udistrital/planeacion_seguimiento_mf)5. [Evaluacion](https://github.com/udistrital/planeacion_evaluacion_mf)
6. [Macroplanes](https://github.com/udistrital/planeacion_macroplanes_mf)
7. [Pendientes](https://github.com/udistrital/planeacion_macroplanes_mf)
8. [Construccion](https://github.com/udistrital/planeacion_macroplanes_mf)

- Todos los MF ya se encuentran desplegados y cuentan con los DNS: https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ETUSQ1JOXG5Jnc9uh3iscfABEl-PJYHvXLEBY9yXz3_Axw?e=mNROD2.

- Funcionalidades nuevas implementadas e identificadas: https://github.com/udistrital/planeacion_cliente/issues/1236#issuecomment-2224210411

**Subtareas**

- [x] Se deben migrar las nuevos desarrollos implementados en el monolito
- [x] Se debe probar el correcto funcionamiento de todas las funcionalidades en nueva arquitectura.

**Criterios de aceptación**

- [x] Revisar los sprints 15 16 y 17 (#1269 )
- [x] Se comprueba que se funcionalmente todos los componentes de la nueva arquitectura funcionan correctamente.
- [x] Se documenta el issue correctamente con las pruebas realizadas.
- [x] Se corrigen los errores presentados y se migran las funcionalidades a la nueva arquitectura.

**Requerimientos**

- [X] Despliegue de los MF en pruebas

**Dependencias**

- Todos los MF de SISGPLAN.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by C0C045** [comment]
# Culminación del ISSUE 1269
Se hizo la respectiva implementación de cada uno de los PR's que el issue #1269 presentaba en los diferentes microfrontend's.

### PR's
evaluacion_mid: https://github.com/udistrital/planeacion_evaluacion_mid/pull/15
construccion_mf: https://github.com/udistrital/planeacion_construccion_mf/pull/24
formulacion_mf: https://github.com/udistrital/planeacion_formulacion_mf/pull/33
seguimiento_mf: https://github.com/udistrital/planeacion_seguimiento_mf/pull/32
evaluacion_mf: https://github.com/udistrital/planeacion_evaluacion_mf/pull/13

**Comment by C0C045** [comment]
# Release PR's
evaluacion_mid: https://github.com/udistrital/planeacion_evaluacion_mid/pull/16
formulacion_mid: https://github.com/udistrital/planeacion_formulacion_mid/pull/21
reportes_mid: https://github.com/udistrital/planeacion_reportes_mid/pull/18
seguimiento_mid: https://github.com/udistrital/planeacion_seguimiento_mid/pull/26

construccion_mf: https://github.com/udistrital/planeacion_construccion_mf/pull/25
evaluacion_mf: https://github.com/udistrital/planeacion_evaluacion_mf/pull/14
formulacion_mf: https://github.com/udistrital/planeacion_formulacion_mf/pull/34
macroplanes_mf: https://github.com/udistrital/planeacion_macroplanes_mf/pull/14
pendientes_mf: https://github.com/udistrital/planeacion_pendientes_mf/pull/21
reportes_mf: https://github.com/udistrital/planeacion_reportes_mf/pull/9
seguimiento_mf: https://github.com/udistrital/planeacion_seguimiento_mf/pull/33

**Comment by C0C045** [comment]
# Pruebas Funcionales

1. En el módulo de construcción al querer editar un plan se quedaba cargando:
![image](https://github.com/user-attachments/assets/7c3c1f42-3201-44aa-90c8-d265dbeb80ed)
**Solución:** https://github.com/udistrital/planeacion_construccion_mf/pull/26

**Comment by C0C045** [comment]
# Pruebas Funcionales Actualizadas

1. En el módulo de construcción al querer editar un plan se quedaba cargando (SOLUCIONADO):
![first](https://github.com/user-attachments/assets/dcd721cc-58de-4eb1-99a5-edba907f55cd)

2. En el módulo de formulación no carga el detalle de un plan seleccionado (SOLUCIONADO):
![image](https://github.com/user-attachments/assets/739a1226-dff6-4f62-a317-acfe79f9e585)

3. No carga el detalle de un plan en el módulo de seguimiento (SOLUCIONADO):
![tercero](https://github.com/user-attachments/assets/90823b39-09ec-4ef1-8bf2-81aaceb1a6c7)

4. No cargan las unidades de un plan en el módulo de evaluación: (SOLUCIONADO):
![fourth](https://github.com/user-attachments/assets/55e15d75-5cba-4637-b6c0-b50254d193c3)
