### ISSUE TITLE
Ajuste de semaforo en módulo de evaluación

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1329]
Se requiere ajustar el módulo de evaluación en la gráfica de seguimiento trimestral y en la tabla de seguimientos la columna de brecha.

**Aspectos Técnicos**

1. El mid, crud y cliente están actualizados a día de hoy en las ramas release/0.0.1.

**Sub Tareas**

- [x] Validar si el indicador es variable o fijo. En dado caso que sea variable, Multiplicar por 0.25 los rangos del semáforo y de la gráfica para el trimestre 1, para el trimestre 2 se debe Multiplicar por 0.50 y así sucesivamente.
![image](https://github.com/user-attachments/assets/680556da-f0e6-4599-a1fa-a44a989df583)

- [x] En formulación cambiar el estilo que pinta cada una de las actividades dependiendo de su estado, para que solo cambie de color la columna que dice estado.

![image](https://github.com/user-attachments/assets/f9a42bfb-070f-4cec-a2d3-78606cf3a9d9)

**Criterios de aceptación**

- [ ] Se realizan los ajustes en la gráfica de evaluación para los indicadores de tipo variable
- [ ] Se ajusta el semaforo en la columna cumplimiento por meta
- [ ] Se corrigen los estilos para las actividades en formulación.
- [ ] Se prueba el sistema nuevamente

**Requerimientos**

- Finalizar issue #1150 .

**Dependencias**

- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.
Se debe probar el correcto funcionamiento de todas las funcionalidades en nueva arquitectura.

**Comment by Mechaz123** [comment]
# AVANCE DE AJUSTE #

- Se realiza el ajuste con respecto al semáforo usado en evaluación para la clasificación de avance de las actividades con indicadores con denominador variable, de manera que al ser denominador variable se hará el cálculo teniendo en cuenta la multiplicación de 0,25 | 0,5 | 0,75 | según cual trimestre sea:

![Image](https://github.com/user-attachments/assets/a25e36bd-c93a-46b2-bb71-f52f016f5c2b)

- Por otra parte, en el apartado de formulación se hizo la corrección de pintado, para las actividades con y sin observaciones.

![Image](https://github.com/user-attachments/assets/f44028ce-396f-42a7-887f-658552266cc4)

# PULL REQUEST #

- planeacion_cliente: https://github.com/udistrital/planeacion_cliente/pull/1337
