### ISSUE TITLE
Verificación y ajuste de cálculos en seguimiento

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1330]
Se requiere corregir en el módulo de seguimiento cada uno de los cálculos involucrados con indicadores variables.

**Aspectos Técnicos**

1. El mid, crud y cliente están actualizados a día de hoy en las ramas release/0.0.1.
2. Actualmente los cálculos de este componente son diferentes a los encontrados en el módulo de evaluación que se encuentran correctos.

**Sub Tareas**

- [x] Se deben revisar los cálculos de avance en el módulo de seguimiento al reportar el númerador y denominador de seguimiento.
- [x] Ajustar los cálculos a lo indicado por el usuario.
- [x] Revisar el correcto comportamiento.

**Criterios de aceptación**

- [x] Se identifican los errores y se corrigen, permitiendo calcular de manera correcta el avance.
- [x] Se prueba la funcionalidad

**Requerimientos**

- ninguno.

**Dependencias**

- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.
Se debe probar el correcto funcionamiento de todas las funcionalidades en nueva arquitectura.

**Comment by Mechaz123** [comment]
# AVANCE DE CORRECCIÓN #

Anteriormente se habían venido trabajando estas modificaciones donde se ha corregido el semaforo en evaluación para tener en cuenta casos de tipo 20.01% y también la multiplicación de valores como 0.25, 0.50 y 0.75 para calcular el indicador acumulado en seguimiento.

Todo esto se ha trabajado en la siguiente rama: https://github.com/udistrital/planeacion_cliente/tree/fix/correccion_seguimiento_y_evaluacion

# PULL REQUEST #

Se ha enviado el pull request con los cambios asociados al semaforo y al indicador acumulado para denominador variable:
- PLANEACION_CLIENTE: https://github.com/udistrital/planeacion_cliente/pull/1354

**Comment by Mechaz123** [comment]
# REPORTE FINAL DE AVANCE #
# !!! IMPORTANTE !!! #

Se realizó una reunión con el usuario el día 23/08/2024 donde se planteaba realizar las aclaraciones para los tipos de unidad "Variable" y "Tasa", pero la reunión se orientó a aclarar ciertas dudas acerca del sistema y así mismo, realizar anotaciones para oportunidades de mejora, por lo cual no se pudo abarcar este tema.

# ANÁLISIS EN PRODUCCIÓN #

Por otra parte, se realizó el análisis de los indicadores con los diferentes tipos de Unidad que pueden tener y se dan los siguientes resultados:
 - **Porcentaje:** 1084 Indicadores
 - **Unidad:** 627
 - **Vacíos:** 9

Adicional a esto se adjunta el Excel que se generó a partir de un script, que anteriormente ya se había trabajado:

[REPORTE.xlsx](https://github.com/user-attachments/files/16755958/REPORTE.xlsx)
