### ISSUE TITLE
Notificaciones por correo en MFs.

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1332]
Se requiere realizar la implementación de notificaciones por correo electrónico en SISGPLAN, adaptada a la arquitectura de MFs, de tal forma que se generen notificaciones utilizando los mismos puntos de notificación configurados para notificaciones internas.

**Especificaciones técnicas**

- Las notificaciones por correo electronico deben realizarse de forma automática, de acuerdo con los puntos de notificación definidos en: #819 .
- El sistema de notificaciones internas y de notificaciones por correo deben quedar sincronizados de tal forma que se generen notificaciones por ambos medios al mismo tiempo.
- Para realizar esta implementación es necesario utilizar las funcionalidades implementadas en notificacion_mid, el cual consume el servicio SNS en AWS. Estas funcionalidades permiten almacenar y enviar notificaciones por correo electrónico de forma automática.
- De igual forma, para crear y almacenar plantillas de notificaciones, se deben utilizar los servicios de notificaciones_mid.
- Las plantillas en cuanto a su contenido base, deben ser igual a las configuradas para notificaciones internas.
- Para mayor guía se sugiere consultar el [manual técnico de notificaciones por correo electrónico](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EWyWVY8EuIBEidY3ScBXSfkBDZEx2Xdv2QSbvUnm8U6MZw?e=Fm3pQq).

**Sub Tareas**

- [x] Implementación de sistema de notificaciones por correo electrónico en MFs.

**Criterios de aceptación**

- [x] El sistema realiza el envío automático de notificaciones por correo en MFs, de acuerdo a los puntos de notificación preconfigurados.

**Requerimientos**

No aplica

**Dependencias**

- SES en AWS.
- notificaciones_mid
- planeacion_MFs.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Se añade video de evidencia, envio de correo: 

[Grabación de pantalla desde 13-08-24 12:18:56.webm](https://github.com/user-attachments/assets/d6af99fb-1f5a-4648-b1b6-2faeb606d9ba)

**Comment by a52290451** [comment]
queda pendiente despliegue en ambiente de pruebas.
