### ISSUE TITLE
Despliegue de Notificaciones (Global) en ambiente de producción

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1333]
Se requiere realizar la salida a producción de todas las APIs relacionadas con notificaciones, teniendo en cuenta los siguientes requerimientos:

**Definition of Done - DoD - Despliegues**

- [x] Aprobación Gerente de Proyectos: no obligatorio Hotfix, Bugfix.
- [x] Aprobación Funcionamiento.
- [x] Actualización de Swagger en WSO2 notificaciones_crud
- [x] Actualización de Swagger en WSO2 notificaciones_mid
- [x] Revisión y actualización de variables de entorno notificaciones_mid
- [x] Creación de instancia en producción para notificaciones_Crud (infraestructura)
- [x] Pruebas funcionales
- [x] Pruebas de carga, estrés y seguridad (líder de seguridad)
- [x] Pruebas unitarias (en caso de ser requerido)
- [x] Despliegue de esquema de BD en producción (requiere script de creación)
- [x] Solicitud de configuración de variables de entorno en Entrypoint para notificaciones_crud
- [x] Creación de plantillas de notificacion en notificaciones_crud
- [x] Creación de plantillas de notificacion en SES
- [x] Configuración de SES para salida a producción.
- [x] Documento técnico

**APIs a ser desplegadas**

- [x] notificaciones_crud
- [x] notificaciones_mid
- [x] web_components
- [x] assets

**Comment by diegobauto** [comment]
- Para poder solicitar acceso a producción para el servicion de Amazon, se tienen las siguientes consideraciones: 
Enlace: [Solicitar acceso a la producción](https://docs.aws.amazon.com/es_es/ses/latest/dg/request-production-access.html)

![image](https://github.com/user-attachments/assets/5b63cd6f-7275-4ac9-8629-c4ab6f437b73)

- Sin embargo, al revisar el servicio, Amazon SES directamente, se observa que ya cuenta con un Acceso de producción: 
Enlace: [Amazon SES](https://us-east-1.console.aws.amazon.com/ses/home?region=us-east-1#/get-set-up)

![image](https://github.com/user-attachments/assets/a797cba8-316d-4c2f-8425-c5ba40244c06)

Por lo tanto, aún así estando el servicio en producción se persiste el problema de que no siempre se envia el correocorrectamente.

**Comment by diegobauto** [comment]
## Documento técnico

[Documento Técnico notificaciones_crud](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EagFPm9pKfRLn1JZrfVCl9EBPye3vjDMgIbNMdwFwGOobg?e=VyDTuB)

**Comment by diegobauto** [comment]
## Pruebas funcionales

[Carpeta NOTIFICACIONES_CRUD](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EimbPMkwO9dBvr_KcYou858BzB5VdMlBfMbqTmkBdhmNxw?e=tT1LDS)

**Comment by diegobauto** [comment]
## Pruebas unitarias

**Comment by diegobauto** [comment]
## Creación de plantillas de notificacion en notificaciones_crud

[insertarPlantillaNotificaciones.zip](https://github.com/user-attachments/files/16640888/insertarPlantillaNotificaciones.zip)

## Creación de plantillas de notificacion en SES (notificacion_mid)

[plantillasCorreo.zip](https://github.com/user-attachments/files/16640893/plantillasCorreo.zip)

**Comment by diegobauto** [comment]
## Revisión y actualización de variables de entorno notificaciones_mid

No aplica

**Comment by diegobauto** [comment]
## Pruebas unitarias

Rama: [feature/puCorreo](https://github.com/udistrital/notificacion_mid/tree/feature/puCorreo)

**Comment by a52290451** [comment]
PRs relacionados:

#1313 .
#1284 .
#1253 .
#1237 .
#1223 .
#1197 .
#1149 .
#1135 .
#1042 .
#1002 .
#1035 .
#1018 .
#1003 .
#990 .

**Comment by a52290451** [comment]
@diegobauto Se requiere hacer ajuste en el modelo de datos, eliminando la tabla "Sistema" y consumiendo esta de parametros_crud.

Es decir que se requiere ingresar información paramétrica de sisgplan en ese modelo de datos.

Cargar la evidencia de la modificación en esta issue

**Comment by diegobauto** [comment]
Se ajusta el modelo de datos, de acuerdo a los lineamientos y eliminando la tabla sistema: 
![notificaciones_crud](https://github.com/user-attachments/assets/f5b314f8-c440-4f4d-a711-78e05f5de598)

El consumo para sistema_id se realiza directamente en parametros_crud por el area_tipo:
![image](https://github.com/user-attachments/assets/d19edd08-28cd-443a-a964-c5e1e5ee28f8)

En donde al registrar una notificación queda de la siguiente manera: 
![image](https://github.com/user-attachments/assets/e80ec7e8-0078-43a0-a961-ca7cbad645dd)

**Comment by a52290451** [comment]
queda pendiente anvanzar en solicitudes con DBAs

**Comment by diegobauto** [comment]
Se realiza ajuste para el modelo de datos de notificaciones_crud, quedando de la siguiente manera:

![notificaciones_crud](https://github.com/user-attachments/assets/af529c3e-5ddb-44ae-9f3f-273759a99452)

**Comment by a52290451** [comment]
En caso de despliegue a producción, es necesario quemar las plantillas de notificaciones hasta que se despliegue plantillas_crud

**Comment by diegobauto** [comment]
Modelo de datos:

![notificaciones_crud](https://github.com/user-attachments/assets/0efd0cc6-a532-4eeb-8a63-82ff893fc511)

**Comment by a52290451** [comment]
Solicitud para despliegue de BD en ambiente de pruebas:

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=64229&group_id=177

**Comment by diegobauto** [comment]
Verificación de notificaciones_crud en ambiente de pruebas:

- Swagger (colecciones 'sistema' y 'plantilla' eliminadas)
![image](https://github.com/user-attachments/assets/be08b854-01c5-4cdb-abd6-4ae4841b5d96)
![image](https://github.com/user-attachments/assets/baaea245-df31-4f72-93b8-e0edad1cf6cd)
![image](https://github.com/user-attachments/assets/4770b1b3-ac88-47b5-9400-d0ebd6d1adc0)

- Registro de tipo_notificación:
![image](https://github.com/user-attachments/assets/e5b23f7e-36c5-4528-8dc6-15ad132da95c)
![image](https://github.com/user-attachments/assets/ed39247f-3de3-4b70-8bab-adfb91f17bd9)

- Registro de notificación:
![image](https://github.com/user-attachments/assets/e7db4cd6-fab9-4829-9e4e-92db0f3449d4)
![image](https://github.com/user-attachments/assets/3c269ab6-2d4e-4e01-8e3f-73a838c1959b)
![image](https://github.com/user-attachments/assets/2fcbf817-f6d3-4077-9afa-5356d0e3751c)


- Verificación de variable de notificaciones (environment.prod):

**Comment by diegobauto** [comment]
Se realizó reunión para estabilización en despliegue, en ambiente de pruebas y producción, incluyendo apartado de notificaciones.

**Comment by a52290451** [comment]
Solicitud despliegue notificaciones_crud en ambiente de producción:

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=64516

Solicitud creación de BD notificaciones en ambiente de producción

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=64427&group_id=177

**Comment by norbeydanilo** [comment]
- Despliegue MID OK
- Pendiente despliegue CRUD

Gestionar para dar cierre y desplegar pendiente @a52290451

**Comment by a52290451** [comment]
@diegobauto validar despliegue y funcionamiento de notificaciones_crud en ambiente de producción, gracias

**Comment by a52290451** [comment]
Se realiza actualización del swagger de notificaciones_crud

**Comment by diegobauto** [comment]
Verificación notificaciones en ambiente de producción:

- Función healthCheck :
![Captura de pantalla 2024-09-19 a la(s) 5 14 07 p  m](https://github.com/user-attachments/assets/7cc3b44b-496b-4e4f-998c-4990d3785416)

- Verificación incial del contenido para notificacion y tipo_notificación: 
![Captura de pantalla 2024-09-19 a la(s) 5 17 15 p  m](https://github.com/user-attachments/assets/d6db5171-4d6a-457f-9108-ab1fb1b4c151)
![Captura de pantalla 2024-09-19 a la(s) 5 17 01 p  m](https://github.com/user-attachments/assets/69b534f9-1a9b-4b56-a580-db51bd011fa4)

- Creación de tipo_plantilla para verificar la correcta inserción en una colección:
![Captura de pantalla 2024-09-19 a la(s) 5 19 24 p  m](https://github.com/user-attachments/assets/e798fa4e-4fad-434d-9408-3ba701a56d9c)
![Captura de pantalla 2024-09-19 a la(s) 5 20 06 p  m](https://github.com/user-attachments/assets/8f5582bb-2c1e-4fe2-9978-0b91b629531c)
