### ISSUE TITLE
Reformulación de planes de acción FASE 2- PARTE 5 y Corrección de errores en Reportes

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1334]
Se requiere finalizar con el desarrollo en Reportes, de forma que se puedan generar reportes de planes de acción con reformulación.

**Aspectos Técnicos**

1. La reformulación de planes de acción se debe realizar sobre un plan que se encuentre en seguimiento.
2. La reformulación solo aplica para Trimestres que presenten un estado diferente a "**Avalado**".
3. Todos los trimestres posteriores al trimestre sobre el cual se reformula un plan, también deben ser reformulados, actualizando su contenido.
4. Los trimestres que ya se encuentran "Avalados" no podrán ser reformulados. Deben mantenerse con la estructura actual.
5. Si un plan es reformulado en un trimestre particular, por ejemplo, T3, los trimestres anteriores que ya deben estar en estado "Avalado", deben mantenerse con su estructura original. La reformulación solo aplica para el trimestre actual y los trimestres posteriores.
6. Para la reformulación, cuando esta sea aprobada por **PLANEACIÓN**, se debe cargar la vista de formulación en una nueva versión con la información diligenciada por la unidad en su momento. El proceso de reformulación es igual al de formulación, debe pasar por todos los estados nuevamente, sin embargo, no es la formulación original y esta diferencia debe estar marcada en el sistema para que solo afecte a los trimestres posibles. (Diferenciación de flujos).
7. Se debe verificar que implicaciones presenta la diferenciación de flujos (formulación y reformulación) en todos los aspectos del sistema.
8. De acuerdo con lo realizado en #1285 , se requiere desarrollar los ajustes necesarios en Reportes, de tal forma que SISGPLAN pueda soportar la visualización de este tipo de planes en los módulos mencionados.

**Sub Tareas**

- [x] Reformulación en Reportes.

**Criterios de aceptación**

- [x] El sistema permite la reformulación de planes de acción en Reportes.

**Requerimientos**

- Finalizar issue #1285 .

**Dependencias**

- planeacion_seguimiento_mf
- planeacion_formulacion_mf
- planeacion_seguimiento_mid
- planeacion_seguimiento_mid
- planeacion_reportes_mid
- planeacion_reportes_mf
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by felimarod** [comment]
Solución a pequeños fallos y avance en la correcta generación de los reportes teniendo en cuenta la reformulación:
1. Falto actualizar el endpoint con respecto al MID:
    ![image](https://github.com/user-attachments/assets/cdb0c14a-b9ea-4eba-811a-1666e18791c1)
2. **Reporte de error:** Al ingresar en el modulo de reportes con el rol de Unidad, al intentar seleccionar la unidad, no se puede seleccionar, esto se da ya que el endpoint retorna un arreglo y no un solo objeto como se espera en el código, esto se solucionó en el MF
    ![image](https://github.com/user-attachments/assets/c93f0222-e9cf-4248-b8ab-7d3b3a02e65b)
3. La categoria no llega como se espera desde el frontend, se aplico una solución rápida para el caso probado(Categoría "Plan de Acción") en reportes_mid
    ![image](https://github.com/user-attachments/assets/a697b377-d8d6-4f07-80a9-cb0e4144a4dd)
4. Generación de reportes de Plan de Acción correcta
    ![image](https://github.com/user-attachments/assets/67cb67f6-4692-404a-b0a0-550a221fc047)
    Se genera el reporte con el último plan que se encuentre en el estado esperado

**Comment by felimarod** [comment]
Como tal en los reportes de la evaluación se encontró un problema
Desde reportes_mid se utiliza el helper de evaluación que se encuentra en planeacion_mid, al intentar cambiarlo a evaluacion_mid(cambio necesario), no se puede hacer ya que no se reconoce planeacion_evaluacion_mid como un paquete en los repositorios de go

![image](https://github.com/user-attachments/assets/ca6d270d-5c04-48c3-9da4-7d3376814fce)

![image](https://github.com/user-attachments/assets/cb8c6073-1216-47a8-a322-139c373e40a9)

Posibles soluciones:
- Agregar planeacion_evaluacion_mid a los paquetes de go
- "Convertir" la función en un endpoint

**Comment by norbeydanilo** [comment]
Actualizar nombre y descripción de issue @a52290451

**Comment by felimarod** [comment]
Durante el desarrollo se han presentado errores inesperados que han retrasado el avance de la tarea
![image](https://github.com/user-attachments/assets/39eb89ba-600d-4765-b85e-aaf50ef4501d)

**Comment by felimarod** [comment]
Se realizaron las correcciones especificadas en el [comentario anterior con sus respectivos commits](https://github.com/udistrital/planeacion_cliente/issues/1334#issuecomment-2303627738), se continuará con la adaptación de la reformulación en https://github.com/udistrital/planeacion_cliente/issues/1358
