### ISSUE TITLE
Visualización de fechas parametrizadas para planes de acción en fase de formulación y seguimiento por trimestre

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1335]
Se requiere crear un menú de consulta de fechas parametrizadas para los planes de acción de formulación y en seguimiento por trimestre.

**Aspectos Técnicos**

1. El mid, crud y cliente están actualizados a día de hoy en las ramas release/0.0.1.
2. Actualmente la funcionalidad se encuentra inoperante.

**Sub Tareas**

- [x] Se debe crear un nuevo menú llamado "Consulta de fechas" como hijo de "Construcción".
- [x] Crear un mockup con propuesta de diseño para visualizar las fechas parametrizadas para las fases de formulación y seguimiento de los planes de accción.
- [x] Generar el servicio en el mid que traiga la información solicitada teniendo en cuenta los posibles filtros que tenga la funcionalidad (fase, nombre de plan, trimestre, vigencia)
- [x] Al aprobarse el mockup generar la implementación en código de la vista propuesta.
- [x] Probar la funcionalidad.
- [x] En la vista de "Administrar sistema" eliminar el botón de "Mostrar Unidades Interés Habilitadas/Reporte".

**Criterios de aceptación**

- [x] Se genera mockup con propuesta visual.
- [x] Se realiza la implementación de la tabla de consulta.
- [x] Se prueba la funcionalidad

**Requerimientos**

- ninguno.

**Dependencias**

- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.
Se debe probar el correcto funcionamiento de todas las funcionalidades en nueva arquitectura.

**Comment by ccmendezt** [comment]
## Evidencias - Avance Visualización de fechas parametrizadas
### 21/08/2024 - 15:00

Se presentan los mockups de cómo luciría el módulo de visualización de fechas parametrizadas para planes de acción de funcionamiento:

- Menú hamburguesa:
![Mockup Consulta Fechas Parametrizadas-Componente Menú](https://github.com/user-attachments/assets/ae8a6777-37c0-4a38-ab4e-89ca8ddc7981)

- Menú de consulta, Ejemplo 1:
![Mockup Consulta Fechas Parametrizadas-Componente - Consulta Fechas](https://github.com/user-attachments/assets/e9979cd7-cdb6-4189-8945-90969b96abda)

En la anterior imagen se muestra cómo luciría la consulta de fechas para un plan de acción de funcionamiento seleccionado el proceso de formulación para una vigencia y unidad determinadas.

- Menú de consulta, Ejemplo 2:
![Mockup Consulta Fechas Parametrizadas-Ej  2 - Consulta Fechas](https://github.com/user-attachments/assets/3f3cb802-9f51-4044-91f9-b2e3cd91657b)

En la anterior imagen se muestra cómo luciría la consulta de fechas para un plan de acción de funcionamiento seleccionado el proceso de seguimiento para una vigencia y unidad determinadas.

## Notas importantes:
  **i.** Este modelo está abierto a modificaciones. Se podría agregar otra columna a la tabla con los datos consultados, donde se muestre la fecha en la que se modificaron las fechas parametrizadas, para así tener certeza de cuándo se realizó la asignación de dichas fechas y quién fue. Se consultará con el SM.

**Comment by ccmendezt** [comment]
## Evidencias - Avance Visualización de fechas parametrizadas
### 21/08/2024 - 15:00

- Se implementó la opción en el menú hamburguesa en el módulo de construcción:
![image](https://github.com/user-attachments/assets/5bc522eb-cb6b-425d-9f33-e79fdf505686)

- Se implementó la vista del formulario para consulta de fechas:
![image](https://github.com/user-attachments/assets/bb35353d-d451-4026-a491-b019c926026a)

- Se implementó servicio en _planeacion_mid_ que permite consultar las fechas parametrizadas para las opciones seleccionadas.

- El módulo de la vista permite consultar el servicio en el mid para mostrar las fechas aunque aún no en un formato de tabla:
![consultaFechas](https://github.com/user-attachments/assets/c8767fb7-9185-4e2b-abd0-bab16437702d)

## Actualización de código en ramas
- **planeacion_mid:** https://github.com/udistrital/planeacion_mid/tree/feature/issue-1335
- **planeacion_cliente:** https://github.com/udistrital/planeacion_cliente/tree/feature/issue-1335
- **planes_crud:** https://github.com/udistrital/planes_crud/tree/feature/issue-1335

**Comment by ccmendezt** [comment]
## Evidencias - Avance Visualización de fechas parametrizadas
### 23/08/2024 - 16:00

- Así va el funcionamiento del módulo de visualización de fechas:
![consultaFechas](https://github.com/user-attachments/assets/4a6a6981-c98e-466d-883b-e35366fcb82a)

- Se implementó la tabla que muestra los datos. Finalmente se decidió mostrar la fecha de modificación del registro a petición del SM.
- Actualmente el módulo funciona correctamente, pero falta ajustar algunas cosas como el responsive, añadir un mensaje de carga para los planes del tipo seleccionado, también quitar el botón de mostrar la funcionalidad del componente del módulo administrar sistema, entre otros.

**Comment by ccmendezt** [comment]
## Evidencias - Módulo de visualización de fechas parametrizadas
### 26/08/2024 - 20:30

Se culminó satisfactoriamente el desarrollo del módulo de visualización de fechas parametrizadas.

- Se eliminó el botón de "Mostrar Unidades Interés Habilitadas/Reporte".
- Se eliminó el código en componente listar-plan asociado al botón Mostrar Unidades Interés Habilitadas/Reporte.
- Se corrigió el responsive de la tabla del módulo del módulo de visualización de fechas parametrizadas:
![responsiveConsultaFechas](https://github.com/user-attachments/assets/913f3c3c-2657-407b-8b2b-56ef8356ed18)
- Se corrigió el responsive de las tablas mostradas en el módulo de Construcción.

## Pull Request asociados a Issue
- **planes_crud:** https://github.com/udistrital/planes_crud/pull/109
- **planeacion_mid:** https://github.com/udistrital/planeacion_mid/pull/617
- **planeacion_cliente:** https://github.com/udistrital/planeacion_cliente/pull/1360
