### ISSUE TITLE
Corrección de observaciones en los documentos de seguimiento

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1336]
Se requiere corregir el comportamiento de almacenamiento y muestra de observaciones sobre los documentos anexados a los seguimientos como soporte.

**Aspectos Técnicos**

1. El mid, crud y cliente están actualizados a día de hoy en las ramas release/0.0.1.
2. Actualmente la funcionalidad se encuentra inoperante.

**Sub Tareas**

- [x] Se debe revisar la persistencia de las observaciones por documentos.
- [x] Con base en la revisión, se debe corregir el comportamiento de almacenamiento y recuperación de la información diligenciada en el campo de observaciones.
- [x] En la caja de observaciones mostrar cuantos caracteres lleva escritos y poner un límite de 1000.

**Criterios de aceptación**

- [x] Se identifican los errores y se corrigen, permitiendo almacenar y observar las observaciones realizadas.
- [x] La visualización de la cajilla se acualiza y muestra cuantos caracteres lleva la persona digitados respecto al límite que son 1000.
- [x] Se prueba la funcionalidad

**Requerimientos**

- ninguno.

**Dependencias**

- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.
Se debe probar el correcto funcionamiento de todas las funcionalidades en nueva arquitectura.

**Comment by Mechaz123** [comment]
# Avance con respecto a la persistencia #

Se realiza el flujo de con respecto al reporte de seguimiento, teniendo en cuenta que se ha subido un documento, pero al momento de consultarlo para las observaciones, este responde de la misma manera para todos los roles **(No se habilita para su uso el campo de observaciones)**

![Image](https://github.com/user-attachments/assets/70d8c80a-d223-43bf-9abc-05701e7b1316)

- Asistente de planeación

![Image](https://github.com/user-attachments/assets/ea8693ef-fbd8-4e8c-9bb9-3df87fd332c6)

**Comment by Mechaz123** [comment]
> Por favor quitar de los condicionales para avanzar en el flujo la revisión de que no haya caracteres en las observaciones de los documentos.
> 
> Revisar que el botón de guardar observaciones en los documentos se habilite solo en los casos requeridos.

# CORRECCIÓN # 

- Se realiza el ajuste del botón donde se presenta la información y donde se edita, este botón solo será visible cuando el campo textarea, sea modificable.

![Image](https://github.com/user-attachments/assets/7bc2cf1c-a071-41fb-838c-d0f46c062d62)

- Ahora en adelante solo se tendrán en cuenta las observaciones del apartado cualitativo y cuantitativo, de manera que en las observaciones de evidencia si se podrá colocar información en las observaciones, pero no se tendrá en cuenta para el flujo.

![Image](https://github.com/user-attachments/assets/95426010-a899-432a-8b95-a2614b425601)

![Image](https://github.com/user-attachments/assets/cb9401ff-e6f8-4901-bb52-3ef714c5bdef)

**Comment by Mechaz123** [comment]
# PULL REQUEST #

Se solicitan los PR a los siguientes repositorios:
- PLANEACION_CLIENTE: https://github.com/udistrital/planeacion_cliente/pull/1351
- PLANEACION_MID: https://github.com/udistrital/planeacion_mid/pull/616
