### ISSUE TITLE
Revisión y aplicación de estilos mejorados MF

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1343]
Se requiere revisar los estilos propuestos en ISSUE y generar su apliación en cada uno de los componentes de los MF con los que cuenta SISGPLAN.

**Aspectos Técnicos**

- Los repositorios de los mid son:

1. [planeacion_formulacion_mid](https://github.com/udistrital/planeacion_formulacion_mid)
2. [planeacion_seguimiento_mid](https://github.com/udistrital/planeacion_seguimiento_mid)
3. [planeacion_evaluacion_mid](https://github.com/udistrital/planeacion_evaluacion_mid)
4. [planeacion_reportes_mid](https://github.com/udistrital/planeacion_reportes_mid)
5. [planeacion_arbol_mid](https://github.com/udistrital/planeacion_arbol_mid)

- Los repositorios de los MF son: 

1. [Root](https://github.com/udistrital/planeacion_root_mf)
2. [Utilidades](https://github.com/udistrital/planeacion_utilidades_mf)(Revisar como mostrar la imagen base de SISGPLAN).
3. [Formulacion](https://github.com/udistrital/planeacion_formulacion_mf) 
4. [Seguimiento](https://github.com/udistrital/planeacion_seguimiento_mf)5. [Evaluacion](https://github.com/udistrital/planeacion_evaluacion_mf)
6. [Macroplanes](https://github.com/udistrital/planeacion_macroplanes_mf)
7. [Pendientes](https://github.com/udistrital/planeacion_macroplanes_mf)
8. [Construccion](https://github.com/udistrital/planeacion_macroplanes_mf)

- Todos los MF ya se encuentran desplegados y cuentan con los DNS: https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ETUSQ1JOXG5Jnc9uh3iscfABEl-PJYHvXLEBY9yXz3_Axw?e=mNROD2.

**Sub Tareas**

- [x] Revisar como se utilizan los estilos propuestos en [ISSUE](https://github.com/udistrital/sga_documentacion/issues/415#issuecomment-2282312127).
- [ ] Generar un servicio en el módulo Utility para traducir la parte inferior de la tabla y que se pueda consumir de todos los MF.
- [ ] Aplicar los estilos revisados en todos los componentes de los MF.
- [x] Revisar la documentación de Angular Material y sugerir que componentes se pueden adoptar en los componentes que no se han intervenido en [ISSUE](https://github.com/udistrital/sga_documentacion/issues/415#issuecomment-2282312127), a menos que sea una mejora estética a lo allí propuesto.
- [x] Corregir los estilos de los MF que actualmente se encuentran generando error (ejemplo: Botones como labels).

**Criterios de aceptación**

- [x] Se identifican los estilos nuevos y se aplican en el MF.
- [ ] Se genera el servicio de traducción en el módulo utility
- [x] Se proponen nuevos estilos.
- [x] Se prueba la funcionalidad del sistema con nuevos estilos.
- [x] Se corrigen los estilos en componentes actuales de los MF.

**Requerimientos**

- ninguno.

**Dependencias**

- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.
Se debe probar el correcto funcionamiento de todas las funcionalidades en nueva arquitectura.

**Comment by C0C045** [comment]
# Estilos y Lógica Mejorados
## Microfrontend Construcción
Se ajustaron los estilos de los botones, tablas e input's de cada uno de los módulos de construcción.

**Pruebas Funcionales:**
![image](https://github.com/user-attachments/assets/52b6bf9c-bb61-4de3-81b2-a37a4ca80f73)

Por otro lado, los módulos de Consulta de Formulación y Seguimiento fueron adaptados para que desde el rol 'JEFE_DEPENDECIA' fuera posible el correcto funcionamiento de los mismos; independientemente si tiene más de una unidad vinculada.

**Antes:**
![image](https://github.com/user-attachments/assets/aca926dc-2ecf-4a1f-b0f4-57a1c38105ad)
![image](https://github.com/user-attachments/assets/90765772-7823-4202-92e9-75fa43a6a389)

**Ahora:**
![image](https://github.com/user-attachments/assets/c499b8f4-7608-4798-b620-49120879370d)
![image](https://github.com/user-attachments/assets/9e7268e2-12bd-4844-9085-79fda89ba18e)

### PR's:
https://github.com/udistrital/planeacion_construccion_mf/pull/27

**Comment by C0C045** [comment]
# Implementación de nuevos estilos
Como se mencionó anteriormente, para llevar a cabo la implementación de las nuevas propuestas de estilos, es necesario tener configurado los módulos de angular y angular material correctamente en cada Microfrontend; ya que de no ser así, los estilos no podrían aplicarse satisfactoriamente. Por ende, una vez configurado cada MF podemos estilizarlo con Angular Material.

## Construcción MF
En este microfrontend se implementaron cada uno de los nuevos estilos presentados en https://github.com/udistrital/sga_documentacion/issues/415#issuecomment-2282312127; en dónde el único que genera dudas es el hover en cada una de las tablas, ya que de por sí cada tabla maneja un intercalado de colores entre filas, por ende, al aplicar un hover se sobresatura de colores.

**Ejemplo Hover Tabla:**
![tablahover](https://github.com/user-attachments/assets/28c13ddd-ebf5-41df-ad0a-eebf6b65b4eb)

En contraste, los demás estilos fueron aplicados correctamente en cada una de las tablas, agregando colores, nombres e iconos.

**Pruebas funcionales:**
![image](https://github.com/user-attachments/assets/84251459-712e-445b-a946-425829d88ace)

![image](https://github.com/user-attachments/assets/0179c8b8-0bf5-43a1-b049-06626fe295c3)

![image](https://github.com/user-attachments/assets/f790c830-851b-4594-b61a-d2bf278c6b89)

![image](https://github.com/user-attachments/assets/b478ddfb-9321-47ea-a6b2-1e6ca33c24b8)

![image](https://github.com/user-attachments/assets/6dcf46a3-3c0c-403a-ae11-2a6ee7130622)

![image](https://github.com/user-attachments/assets/a346985d-0748-47a7-a965-95a65d3bc597)

**Comment by C0C045** [comment]
# Propuesta de Estilos para Fechas
En el microfrontend de construcción actualmente al asignar fechas de inicio y fin de un plan de acción de Funcionamiento se usan dos inputs para capturar la fecha inicial y la fecha final; tal que así:
![image](https://github.com/user-attachments/assets/0d754631-aa30-4e34-aee0-7eeef5b70430)

Sin embargo, la [documentación](https://v16.material.angular.io/components/datepicker/overview#date-range-input-forms-integration) de Angular Material versión 16, nos ofrece un solo input para manejar una fecha inicial y otra final; el cuál ocupa menos espacio y es más intuitivo de usar; tal que así:
![Propuesta](https://github.com/user-attachments/assets/5fbecc43-bfac-4a48-87b4-c72b01609622)

**Comment by C0C045** [comment]
# Hover de tabla eliminado
### PR
construccion_mf: https://github.com/udistrital/planeacion_construccion_mf/pull/29
