### ISSUE TITLE
Refinamiento de documento técnico

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1344]
Se requiere refinar el documento técnico con base en la nueva arquitectura, servicios y funcionalidades desarrollados.

**Aspectos Técnicos**

1. El mid, crud y cliente están actualizados a día de hoy en las ramas release/0.0.1.
2. La nueva arquitectura tiene la siguiente estructura

- Los repositorios de los mid son:

1. [planeacion_formulacion_mid](https://github.com/udistrital/planeacion_formulacion_mid)
2. [planeacion_seguimiento_mid](https://github.com/udistrital/planeacion_seguimiento_mid)
3. [planeacion_evaluacion_mid](https://github.com/udistrital/planeacion_evaluacion_mid)
4. [planeacion_reportes_mid](https://github.com/udistrital/planeacion_reportes_mid)
5. [planeacion_arbol_mid](https://github.com/udistrital/planeacion_arbol_mid)

- Los repositorios de los MF son: 

1. [Root](https://github.com/udistrital/planeacion_root_mf)
2. [Utilidades](https://github.com/udistrital/planeacion_utilidades_mf)(Revisar como mostrar la imagen base de SISGPLAN).
3. [Formulacion](https://github.com/udistrital/planeacion_formulacion_mf) 
4. [Seguimiento](https://github.com/udistrital/planeacion_seguimiento_mf)5. [Evaluacion](https://github.com/udistrital/planeacion_evaluacion_mf)
6. [Macroplanes](https://github.com/udistrital/planeacion_macroplanes_mf)
7. [Pendientes](https://github.com/udistrital/planeacion_macroplanes_mf)
8. [Construccion](https://github.com/udistrital/planeacion_macroplanes_mf)

**Sub Tareas**

- [x] Inicialmente debe agregarse al [documento técnico ](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EcIfzzZkICtGsJpIPN-BcW4BRu-q_OECUVcKn2lkjmj7xg?e=vhwMz1)aquellas funcionalidades recientemente controladas y mejoradas, así como las nuevas desarrolladas en el monolito.
- [x] Crear un nuevo documento técnico a partir de la nueva arquitectura.

**Criterios de aceptación**

- [x] Se actualiza el documento técnico actual (Monolito).
- [x] Se genera nuevo documento técnico con la arquitectura basada en MF y micromids

**Requerimientos**

- ninguno.

**Dependencias**

- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
# AVANCE EN LOS DOCUMENTOS #

Se realizaron los cambios asociados a la arquitectura anterior en este caso el monolito donde se hace la explicación de en qué consiste un monolito y los cambios que se han realizado dentro del sistema, a partir de los cambios nuevos que se han generado, hay que tener en cuenta que se han resaltado los cambios más críticos, como lo puede ser el tema de la plantilla de creación de un plan, la creación de los valores de un "Select" y un nuevo apartado para consultar las fechas en el menú.


[DocumentoTécnico-SISGPLAN-MONOLITO.docx](https://github.com/user-attachments/files/16711982/DocumentoTecnico-SISGPLAN-MONOLITO.docx)

Por otra parte, se desarrolló otro documento enfocado a la estructura nueva que hace uso del concepto de Microservicios y Microfrontends, donde se realiza también la explicación de estos 2 conceptos y se manejan también los mismos cambios que se han realizado en ambos sistemas, ya que el sistema en la nueva arquitectura conservará los mismos cambios que existan en el monolito.

[DocumentoTécnico-SISGPLAN-MICROFRONTEND.docx](https://github.com/user-attachments/files/16712002/DocumentoTecnico-SISGPLAN-MICROFRONTEND.docx)

# NOTA #
Se envían los documentos para revisión y se queda al tanto de cambios o mejoras que se requieran en estos documentos.

**Comment by Mechaz123** [comment]
# AVANCE DESARROLLO DEL ESQUEMA PARA LA NUEVA ARQUITECTURA #

Se desarrolló el esquema que encapsula todos los microservicios y microfrontends, donde muestra como está construido SISGPLAN en la nueva arquitectura.

![Image](https://github.com/user-attachments/assets/5d9d9166-56e1-4f35-889e-abca9813d465)

**Comment by Mechaz123** [comment]
# CORRECCIÓN DEL ESQUEMA #

Se realizó las siguientes modificaciones al diagrama:
-  Se agrupó por color los microservicios, microfrontends y CRUD.
- Se eliminó uno de los API GATEWAY y se aclaró que es "API GATEWAY / WSO2".
- Se realizó la modificación de algunas flechas para indicar que puede tanto recibir como enviar información.
- Se agregó un apartado de guía para la separación de los componentes entre CLIENTE, MID, CRUD.

![Image](https://github.com/user-attachments/assets/2ca0f74c-4008-4070-b888-a3b87bf7e3c5)

# NOTA # 
Se queda al pendiente de cambios u observaciones que se requieran en el diagrama.
