### ISSUE TITLE
Construcción plantillas_crud / Investigación implementación serverless

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1345]
Se requiere realizar la construcción de plantillas_crud, con base en el modelo de datos aprobado en #1292.

**Especificaciones Técnicas**

- Se debe implementar la Base de Datos en MongoDB.
- El API CRUD debe ser implementado en NestJS.
- plantillas_crud debe contener todos los metodos y formas de consulta necesarias para acceder a la información, de acuerdo con las funcionalidades planificadas para el sistema de plantillas.

**Sub Tareas**

- [ ] Investigaciòn Serverless.

**Criterios de aceptación**

- [x] Investigaciòn Serverless.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Se sube desarrollo en el repositorio de:
[plantillas_crud](https://github.com/udistrital/plantillas_crud)

En la siguiente rama: 
[feature/plantillasNestJS](https://github.com/udistrital/plantillas_crud/tree/feature/plantillasNestJS)

Sin embargo queda incompleto el desarrollo de la API CRUD con NestJS y Mongodb, dado que, el sistema de plantillas se realizará por medio de serverless.

**Comment by a52290451** [comment]
@diegobauto De acuerdo a lo conversado con Infraestructura, se opta por implementar el acceso a la BD mediante Serverless. Por tal razón, se requiere iniciar consultando documentación relacionada con este tipo de implementación en AWS utilizando lambdas.

Por favor registrar dicha investigación en este issue.

Adicionalmente, se esta gestionando una reunión con Heiner para capacitarnos en este tema.

**Comment by diegobauto** [comment]
Para trabajar con serverless por medio de Lambda se tiene lo siguiente:

- Creación de la base de datos (Ejemplo: DynamoDB como base de datos no relacional), incluyendo la creación de tablas.

- Creación de funciones Lambda "sin aprovisionar ni administrar servidores", por medio de un lenguaje de programación. Los pasos sería los siguientes, descritos en [Ejecute un "¡Hola, mundo!" sin servidor con AWS Lambda](https://aws.amazon.com/es/tutorials/run-serverless-code/),  teniendo en cuenta que es en base a la creación de funciones hacia la base de datos:

      1. Ingresar a la consola Lambda
      2. Seleccione un modelo Lambda y configúrelo 
      3. Revisar la configuración de Lambda (opcional)
      4. Invocar la función Lambda y verificar los resultados
      5. Monitorea tus métricas (adicional)

- Configurar Trigger, para la creación de una API Gateway para exponer la Lambda como un servicio HTTP o REST. Esto permitirá invocar la Lambda a través de solicitudes HTTP, lo que es útil para operaciones CRUD sobre DynamoDB desde aplicaciones front-end o clientes externos (Ejemplo: Angular).
[Invocación de una función de Lambda mediante un punto de conexión de Amazon API Gateway](https://docs.aws.amazon.com/es_es/lambda/latest/dg/services-apigateway.html)


Toda la informcación asociada a AWS Lambda se puede encontrar en el siguiente enlace: [Guía para desarrolladores](https://docs.aws.amazon.com/es_es/lambda/latest/dg/welcome.html)
