### ISSUE TITLE
Mejoras SISGPLAN

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1349]
Se requiere revisar los estilos propuestos en ISSUE y generar su apliación en cada uno de los componentes de los MF con los que cuenta SISGPLAN.

**Aspectos Técnicos**

1. El mid, crud y cliente están actualizados a día de hoy en las ramas release/0.0.1.
2. Actualmente la funcionalidad se encuentra inoperante.

**Sub Tareas**

- [ ] Se deben adicionar mensajes de carga al abrir Identificaciones de Contratistas, Recursos y Docentes en el módulo de Formulación.
- [ ] Se deben adicionar mensajes de carga para el menú de "administrar sistema" al momento de cargar los respectivos filtros y almacenamiento de fechas.
- [x] En la identificación de rubros encontrada en el módulo de Formulación se debe permitir la búsqueda de rubros mediante un filtro.
- [x] Permitir que las observaciones dentro de la identificación de rubros se expanda (textarea).
- [ ] En el módulo de seguimiento, se requiere mostrar los mensajes de procesando petición o mensajes de carga según sea el caso en los botones de: Guardar componente cualitativo, guardar componente cuantitativo, generar reporte, guardar revisión actividad, iniciar y finalizar revisión JU, enviar corrección, iniciar y finalizar revisión OAPC.
- [ ] Ajustar ancho de filas en reporte de Evaluacion para planes armonizados con varios lineamientos, metas y estrategias del PED - Módulo Reportes
- [ ] Estandarizar el formato de fecha en todos los componentes de la siguiente manera: dd-mm-yyyy hh:mm:ss

**Criterios de aceptación**

- [ ] Se adicionan los mensajes de carga requeridos en los módulos de formulación y seguimiento.
- [x] Se adicionan los filtros en la identificación de rubros.
- [x] Se investiga dónde reposan dichos rubros.
- [ ] Se corrigen visualmente los reportes y las observaciones enla identifiación de rubros.
- [ ] Se prueban las funcionalidades y correcciones en el monolito.

**Requerimientos**

- ninguno.

**Dependencias**

- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Con prioridad items 3 y 4.

**Comment by Mechaz123** [comment]
# Avance Búsqueda de Rubos #

Se realizó la modificación para los apartados de identificación en la fase de formulación para que en las 3 secciones donde se consultan rubros se permita realizar la búsqueda más sencilla de estos.

![Image](https://github.com/user-attachments/assets/4064a2d5-ec8e-424b-b713-75118cebedf7)

**Comment by Mechaz123** [comment]
# Avance de modificación en TextArea #

Se realiza la modificación para permitir la edición del tamaño del textarea, cabe aclarar que solo se permite modificar verticalmente, esto con el fin de no perjudicar la estructura base de la tabla.

![Image](https://github.com/user-attachments/assets/6651a876-c476-4a1c-a505-46aa15b78d5c)

**Comment by Mechaz123** [comment]
# LOCALIZACIÓN DE LOS RUBROS #

Para el cliente, los rubros se encuentran en un archivo de tipo TS, dentro de una de las vistas de identificación llamada "recursos".

![Image](https://github.com/user-attachments/assets/736aba4f-eb59-4b9b-9e82-e1057dbff246)

Este es el contenido de ese archivo.

![Image](https://github.com/user-attachments/assets/f3787570-971c-4d0d-a8cb-98c166441757)
