### ISSUE TITLE
Diagrama de arquitectura

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1350]
Se requiere crear un diagrama arquitectural sobre el monolito y la nueva arquitectura.

**Aspectos Técnicos**

1. El mid, crud y cliente están actualizados a día de hoy en las ramas release/0.0.1.
2. La nueva arquitectura tiene la siguiente estructura

- Los repositorios de los mid son:

1. [planeacion_formulacion_mid](https://github.com/udistrital/planeacion_formulacion_mid)
2. [planeacion_seguimiento_mid](https://github.com/udistrital/planeacion_seguimiento_mid)
3. [planeacion_evaluacion_mid](https://github.com/udistrital/planeacion_evaluacion_mid)
4. [planeacion_reportes_mid](https://github.com/udistrital/planeacion_reportes_mid)
5. [planeacion_arbol_mid](https://github.com/udistrital/planeacion_arbol_mid)

- Los repositorios de los MF son: 

1. [Root](https://github.com/udistrital/planeacion_root_mf)
2. [Utilidades](https://github.com/udistrital/planeacion_utilidades_mf)(Revisar como mostrar la imagen base de SISGPLAN).
3. [Formulacion](https://github.com/udistrital/planeacion_formulacion_mf) 
4. [Seguimiento](https://github.com/udistrital/planeacion_seguimiento_mf)5. [Evaluacion](https://github.com/udistrital/planeacion_evaluacion_mf)
6. [Macroplanes](https://github.com/udistrital/planeacion_macroplanes_mf)
7. [Pendientes](https://github.com/udistrital/planeacion_macroplanes_mf)
8. [Construccion](https://github.com/udistrital/planeacion_macroplanes_mf)

- En la tarea #1344 se llevó a cabo la creación inicial de un diagrama arquitectural para la nueva arquitectura.

**Sub Tareas**

- [x] Refinar los estilos de los componentes en el diagrama de la nueva arquitectura encotnrada en #1344 para que sus recuadros se denoten correctamente.
- [x] Adicionar al diagrama de #1344 la base de datos de mongo para que se conecte con **planes crud**.
- [x] Crear un diagrama arquitectural del monolito con las consideraciones de esta issue y las leyendas respectivas.

**Criterios de aceptación**

- [x] Se actualiza el diagrama de la nueva arquitectura.
- [x] Se genera diagrama arquitectural del monolito.

**Requerimientos**

- ninguno.

**Dependencias**

- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Según el [documento gráfico de SGA](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/ETKXN4aYc_9OtInCD8A3zp0BKsWLM0b5FGl7FYpa7250vg?e=F10V6J) aplicar en el diagrama de SISGPLAN información de repositorio, Drone, pruebas y producción. Incluir también "imagen/ícono" sobre las tecnologías empleadas en cada API.

Debe incluirse las APIs transversales (CORE) que se consumen.

**Comment by Mechaz123** [comment]
#Avance del diagrama de SISGPLAN #

Se realiza la modificación del diagrama para la nueva arquitectura de SISGPLAN, donde se realiza la aplicación de los comentarios y cambios requeridos para una mejor entrega.

![Image](https://github.com/user-attachments/assets/1d612c9d-c8f1-4974-bf98-c33aab07a4b1)

## NOTA ##
Se realizará un diagrama por aparte donde se mostrará lo relacionado a información de repositorio, Drone, pruebas y producción de SISGPLAN, ya que actualmente el diagrama se podría ver sobrecargado de información.

**Comment by Mechaz123** [comment]
> Por favor cambiar la leyenda de "los componentes del Api" a "tecnologías del componente"

Se realiza la modificación del texto en la leyenda:

![Image](https://github.com/user-attachments/assets/e40699a4-c218-4051-8d0c-960a8d1764bb)

**Comment by norbeydanilo** [comment]
- Poner NestJS como framework que se usa en el CRUD
- Ubicar leyenda para los servicios CORE (caso de CORE MF), Pintar de un rojo claro o similar
- Quitar el fondo de los íconos, por ejemplo de SingleSPA, Beego, Go.

**Comment by Mechaz123** [comment]
# CORRECCIONES A LOS DIAGRAMAS #

Se realizan las correcciones a los diagramas:

- **Diagrama antigua arquitectura:**

![Image](https://github.com/user-attachments/assets/5c1ba6ee-45fb-4c84-962e-a9474646b38b)

- **Diagrama nueva arquitectura:**

![Image](https://github.com/user-attachments/assets/378a6622-f66b-4d6f-9fc3-da1e4cf217cd)

**Comment by Mechaz123** [comment]
# CORRECCIÓN AL CRUD #

Se realiza la corrección mencionada a ambos diagramas:

- **Diagrama nueva arquitectura:**

![Image](https://github.com/user-attachments/assets/86391a29-352c-447e-a37d-f3bc7d1888fc)

- **Diagrama antigua arquitectura:**

![Image](https://github.com/user-attachments/assets/a4395ffc-52d1-4605-b86b-9dbe1bc218d1)

**Comment by Mechaz123** [comment]
# ACTUALIZACIÓN DE LOS DOCUMENTOS #

Se realiza la actualización de ambos documentos con los diagramas que se han venido desarrollando:

- SISGPLAN NUEVA ARQUITECTURA: [DocumentoTécnico-SISGPLAN-MICROFRONTEND.docx](https://github.com/user-attachments/files/16841754/DocumentoTecnico-SISGPLAN-MICROFRONTEND.docx)
- SISGPLAN ANTIGUA ARQUITECTURA: [DocumentoTécnico-SISGPLAN-MONOLITO.docx](https://github.com/user-attachments/files/16841755/DocumentoTecnico-SISGPLAN-MONOLITO.docx)

**Comment by Mechaz123** [comment]
# SUBIDA DE DOCUMENTOS #

- Se realiza la subida de los archivos a la siguiente ruta de carpetas:

![Image](https://github.com/user-attachments/assets/e139fb70-6f74-43f2-9b3f-cef19c0bc727)

- Así mismo se adjunta el link del Draw.io, donde se trabajó los diagramas

LINK: https://udistritaleduco-my.sharepoint.com/:u:/g/personal/daarojasg_udistrital_edu_co/EXPOWv2NuDtJnqkKemyLIJkBcFqGC2XxyuTEqQc2lndNTQ?e=xQ1RQr
