### ISSUE TITLE
Codificación en base 64 los parámetros

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1352]
Se requiere implementar un método de codificación y decodificación de URIs para peticiones HTTP que envien información alfanumérica en parámetros.

**Aspectos Técnicos**

- Los repositorios de los mid son:

1. [planeacion_formulacion_mid](https://github.com/udistrital/planeacion_formulacion_mid)
2. [planeacion_seguimiento_mid](https://github.com/udistrital/planeacion_seguimiento_mid)
3. [planeacion_evaluacion_mid](https://github.com/udistrital/planeacion_evaluacion_mid)
4. [planeacion_reportes_mid](https://github.com/udistrital/planeacion_reportes_mid)
5. [planeacion_arbol_mid](https://github.com/udistrital/planeacion_arbol_mid)

**Sub Tareas**

- [x] Generar un método de codificación de peticiones HTTP dónde se le pase por parámetro la URI y este devuelva la petición en base 64.
- [x] Escoger un API dónde implementarlo.
- [x] Probar el método y envío de caracteres especiales dentro de una petición HTTP del API escogida, a través de WSO2 (Por lo tanto, en el ejemplo debe subirse el código a release del API).

**Criterios de aceptación**

- [x] Se crea función que codifique la URI en base 64.
- [x] Se debe evidenciar el envío de una petición a través de WSO2 sin codificación y con codificación

**Requerimientos**

- ninguno.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.
Se debe probar el correcto funcionamiento de todas las funcionalidades en nueva arquitectura.

**Comment by C0C045** [comment]
# Prueba Evaluación Mid Codificación Base 64
Se implementó correctamente un servicio en utility module que me permite codificar en Base 64 cada uno los planes que se envían desde el microfrontend de evaluación hacia el endpoint de evaluación para obtener las unidades; tal que así:
![image](https://github.com/user-attachments/assets/0f12737e-f433-47d4-a3ff-6e696ae9e042)
Cómo podemos ver el parámetro del plan esta totalmente codificado.

Por otro lado, al llegar al endpoint en el micromid de evaluación se usa otra función para decodificar el plan y así obtener su nombre correspondiente.
```go
func DecodeBase64(encoded string) (string, error) {
	// Decodifica la cadena Base64
	data, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return "", err
	}

	// Convierte los bytes UTF-8 en una cadena
	decodedStr := string(data)
	return decodedStr, nil
}
```

**Prueba funcional:**
![Base64](https://github.com/user-attachments/assets/5527da3c-c208-436c-8198-83eec0888847)

### PR's
utility_module: https://github.com/udistrital/planeacion_utility_module/pull/8
evaluacion_mf: https://github.com/udistrital/planeacion_evaluacion_mf/pull/17
evaluacion_mid: https://github.com/udistrital/planeacion_evaluacion_mid/pull/18

**Comment by C0C045** [comment]
# Release PR's
utility_module: https://github.com/udistrital/planeacion_utility_module/pull/9
evaluacion_mf: https://github.com/udistrital/planeacion_evaluacion_mf/pull/18
evaluacion_mid: https://github.com/udistrital/planeacion_evaluacion_mid/pull/19

**Comment by C0C045** [comment]
# Prueba en WSO2
Actualmente la codificación actual en Base64 presenta problemas, ya que al final de cada codificación agrega un carácter especial (=), por ende la petición falla.

**Ejemplo:**
**Entrada:** UGxhbiBkZSBBY2Npw7NuIGRlIHBydWViYXMgU2lzZ3BsYW4gRS5CLlM=
**Interpretación de WSO2:** UGxhbiBkZSBBY2Npw7NuIGRlIHBydWViYXMgU2lzZ3BsYW4gRS5CLlM%3D
![image](https://github.com/user-attachments/assets/4bd85dc5-bde3-49e8-aaac-9fefdbc14f80)

**Comment by C0C045** [comment]
# Soporte de Codificación Base64 para URLs
Investigando se encontró que existe una codificación especifica para el manejo de peticiones por URL; la cuál se aplicó y es funcional.

### PR's
evaluacion_mid: https://github.com/udistrital/planeacion_evaluacion_mid/pull/20
utility_module: https://github.com/udistrital/planeacion_utility_module/pull/10

**Comment by C0C045** [comment]
# PR's a Release
evaluacion_mid: https://github.com/udistrital/planeacion_evaluacion_mid/pull/21
utility_module: https://github.com/udistrital/planeacion_utility_module/pull/11

**Comment by C0C045** [comment]
# Prueba Final en WSO2
Una vez implementada la codificación de Base64 segura para URLs se obtienen los siguientes resultados:

### Sin codificación:
![Ws02First](https://github.com/user-attachments/assets/bf56339d-44b8-4acb-ba3d-3642fed888aa)

### Con codificación:
![Ws02Second](https://github.com/user-attachments/assets/90140aa0-30c1-4b8c-928e-bdb61a0eec3f)

Como podemos notar en ambas situaciones se logra una respuesta exitosa, por ende, se puede concluir que la implementación de la codificación en Base64 es viable y evita la mala lectura de caracteres especiales en los parámetros de una URL.

**Respuesta:**
![image](https://github.com/user-attachments/assets/850dbd80-aea3-4072-9793-5fc7b4dec711)
