### ISSUE TITLE
Servicio que retorne campos paramétricos empleados en SISGPLAN

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1353]
Se requiere que carguen previamente campos "paramétricos" que se consumen en diferentes módulos para disminuir el consumo de servicios y envío de peticiones repetitivas.

**Aspectos Técnicos**

- Los repositorios de los MF son: 

1. [Root](https://github.com/udistrital/planeacion_root_mf)
2. [Utilidades](https://github.com/udistrital/planeacion_utilidades_mf)(Revisar como mostrar la imagen base de SISGPLAN).
3. [Formulacion](https://github.com/udistrital/planeacion_formulacion_mf) 
4. [Seguimiento](https://github.com/udistrital/planeacion_seguimiento_mf)5. [Evaluacion](https://github.com/udistrital/planeacion_evaluacion_mf)
6. [Macroplanes](https://github.com/udistrital/planeacion_macroplanes_mf)
7. [Pendientes](https://github.com/udistrital/planeacion_macroplanes_mf)
8. [Construccion](https://github.com/udistrital/planeacion_macroplanes_mf)

- Todos los MF ya se encuentran desplegados y cuentan con los DNS: https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ETUSQ1JOXG5Jnc9uh3iscfABEl-PJYHvXLEBY9yXz3_Axw?e=mNROD2.

**Sub Tareas**

- [x] Revisar la implementación de consumo de códigos de abreviación encontrada en los MF.
- [x] Hacer un listado de datos que se consumen repetitivamente a lo largo de los MF por funcionalidad (Por ejemplo: consumo de dependencias hacia Oikos).
- [x] Para los datos identificados se deben generar los respectivos consumos previos por MF, de manera que al estar precargados no se envien las peticiones nuevamente cada oportunidad que se cargue alguna de las funcionalidades de cada MF.
- [x] Probar el respectivo funcionamiento.

**Criterios de aceptación**

- [x] Se identifican los servicios que se consumen repetitivamente en cada MF
- [x] Se realiza un precargado de la infomación identificada.
- [x] Se prueban las funcionalidades del sistema.

**Requerimientos**

- ninguno.

**Dependencias**

- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.
Se debe probar el correcto funcionamiento de todas las funcionalidades en nueva arquitectura.

**Comment by C0C045** [comment]
# Listado de Peticiones repetitivas
## Construcción Microfrontend
### - arbol.ts
- [ ] CodigosService
### - plan/construir-plan-proyecto.ts
- [ ] CodigosService
### - plan/construir-plan.ts
- [ ] CodigosService
### - plan/construir-plan.ts
- [ ] CodigosService
### - plan/crear-plan.ts
- [ ] CodigosService
- [ ] loadPeriodos
### - plan/listar-plan.ts
- [ ] CodigosService
### - plan/plan-accion/plan-accion-seguimiento.ts
- [ ] cargarPlanes

**Comment by C0C045** [comment]
# Construcción Microfrontend Culminado
Se ajustaron todas aquellas peticiones o funciones que se cargaban varias veces en el microfrontend, con el objetivo de obtener una mejor eficiencia en cuanto a la obtención de datos.

### PR
construccion_mf: https://github.com/udistrital/planeacion_construccion_mf/pull/32

**Comment by C0C045** [comment]
# Formulación Microfrontend Culminado
Se ajustaron todas aquellas peticiones o funciones que se cargaban varias veces en el microfrontend, con el objetivo de obtener una mejor eficiencia en cuanto a la obtención de datos.

### PR
formulacion_mf: https://github.com/udistrital/planeacion_formulacion_mf/pull/39

**Comment by C0C045** [comment]
# Macroplanes Microfrontend Culminado
Se ajustaron todas aquellas peticiones o funciones que se cargaban varias veces en el microfrontend, con el objetivo de obtener una mejor eficiencia en cuanto a la obtención de datos.

### PR
macroplanes_mf: https://github.com/udistrital/planeacion_macroplanes_mf/pull/17

**Comment by C0C045** [comment]
# Pendientes Microfrontend Culminado
Se ajustaron todas aquellas peticiones o funciones que se cargaban varias veces en el microfrontend, con el objetivo de obtener una mejor eficiencia en cuanto a la obtención de datos.

### PR
pendientes_mf: https://github.com/udistrital/planeacion_pendientes_mf/pull/23

**Comment by C0C045** [comment]
# Reportes Microfrontend Culminado
Se ajustaron todas aquellas peticiones o funciones que se cargaban varias veces en el microfrontend, con el objetivo de obtener una mejor eficiencia en cuanto a la obtención de datos.

### PR
reportes_mf: https://github.com/udistrital/planeacion_reportes_mf/pull/14

**Comment by C0C045** [comment]
# Seguimiento Microfrontend Culminado
Se ajustaron todas aquellas peticiones o funciones que se cargaban varias veces en el microfrontend, con el objetivo de obtener una mejor eficiencia en cuanto a la obtención de datos.

### PR
seguimiento_mf: https://github.com/udistrital/planeacion_seguimiento_mf/pull/37

**Comment by C0C045** [comment]
## Prueba funcional
![codigos](https://github.com/user-attachments/assets/78496d12-5d1a-48f8-a468-1f3d3bff6e37)

La anterior prueba funcional nos muestra como cada uno de los códigos son cargados apenas iniciar el microfrontend y una vez cargados no se vuelve a mandar ninguna petición para obtenerlos.

**Comment by C0C045** [comment]
# PR's a Release
construccion_mf: https://github.com/udistrital/planeacion_construccion_mf/pull/33
formulacion_mf: https://github.com/udistrital/planeacion_formulacion_mf/pull/40
macroplanes_mf: https://github.com/udistrital/planeacion_macroplanes_mf/pull/18
pendientes_mf: https://github.com/udistrital/planeacion_pendientes_mf/pull/24
reportes_mf: https://github.com/udistrital/planeacion_reportes_mf/pull/15
seguimiento_mf: https://github.com/udistrital/planeacion_seguimiento_mf/pull/38

**Comment by C0C045** [comment]
# Pruebas funcionales Release
Se afirma que cada una de las implementaciones son evidenciadas en release, tal que así:

![image](https://github.com/user-attachments/assets/44965d78-659e-4bb2-8f68-df5ece4b8b14)
![image](https://github.com/user-attachments/assets/37aa4dce-9be4-4e2a-b427-49c09b3346ff)
![image](https://github.com/user-attachments/assets/28c018f4-3bc8-435e-a841-b5096038c71b)
