### ISSUE TITLE
Corrección de flujo SISGPLAN

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1355]
Se requiere ajustar el flujo de formulación para satisfacer las necesidades del usuario.

**Aspectos Técnicos**

1. El mid, crud y cliente están actualizados a día de hoy en las ramas release/0.0.1.
2. Actualmente la funcionalidad se encuentra inoperante.

**Sub Tareas**

- [ ] Se debe corregir el flujo de manera que la revisión de actividades de un plan formulado sean validados por el jefe inmediatamente, previo a que planeación lo revise.

![image](https://github.com/user-attachments/assets/f8b06f8d-98b8-4cbf-a1ba-64975a8ecfd5)

- [ ] Se debe corregir el comportamiento de almacenamiento o guardado de identificación de rubros por parte del asistente de dependencia cuándo el jefe revise un plan.

**Criterios de aceptación**

- [ ] Se corrige el flujo y el comportamiento de guardado cuando un rol no tiene permisos.
- [ ] Se valida el funcionamiento de todo el sistema.

**Requerimientos**

- ninguno.

**Dependencias**

- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.
Se debe probar el correcto funcionamiento de todas las funcionalidades en nueva arquitectura.

**Comment by ccmendezt** [comment]
## Evidencias - Avance Corrección de flujo SISGPLAN
### 29/08/2024 - 16:00

- El nuevo flujo diseñado es el siguiente:
![image](https://github.com/user-attachments/assets/c6994f0e-b2a4-4001-9adc-f1d4fdd48ee5)
