### ISSUE TITLE
Migración Lógica Renderizado de documentos a plantillas_mid

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1357]
Se requiere migrar la lógica relacionada con el renderizado de documentos a plantillas_mid, disponible en https://github.com/udistrital/prueba_piloto_funciones_lambda, de tal forma que este servicio pueda ser utilizado de forma transversal por otros servicios.

**Especificaciones técnicas**

- Se requiere migrar y adaptar toda la lógica relacionada con el renderizado y construcción de documentos PDF, teniendo en cuenta que se envia para el renderizado una estructura de datos definida.
- Se debe mejorar el desarrollo realizado para que sea versatil y adaptable a los diferentes tipos de plantillas que se manejan. Tomar como referencia el modelo de datos creado.
- El servicio debe poder conectarse y utilizarce por otros servicios al interior de plantillas_mid y de forma externa. 

**Sub Tareas**

- [x] Migración de lógica de renderizado de documentos a plantillas_mid.
- [x] Optimización de lógica de renderizado de documentos en plantillas_mid.

**Criterios de aceptación**

- [x] Se presenta la funcionalidad para renderizar documentos en plantillas_mid, con sus metodos optimizados.

**Requerimientos**

- [x] Completar nueva estructura de plantillas_mid

**Dependencias**

- plantillas_mid

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Para el desarrollo se contempla manejar editores WYSIWYG, estos editores permiten una mejor interacción con el usuario para la creación de plantillas, y además cuentan con la creación directa de una estructura HTML, por lo que facilita el desarrollo de creación de esta estructura. Sin embargo, muchos de estos editores tienen diferentes limitaciones, ya que manejan versiones gratuitas y otras de pago, por lo habría que encontrar el editor mas adecuado para la funcionalidad del sistema.

Ejemplo de editor WYSIWYG, en donde se observa el contenido HTML por consola:
![image](https://github.com/user-attachments/assets/94bd611d-ce0d-441b-85fc-02f072ab9121)

**Comment by diegobauto** [comment]
Se implementaron varios ejemplos de diferentes editores WYSIWYG, consideranto uno de estos como una alternativa para el sistema de plantillas: 

**SunEditor**
Sitio oficial: http://suneditor.com/sample/index.html

Vista general:
![image](https://github.com/user-attachments/assets/b1c5cd5a-9996-455a-be31-d1e21ea39f7b)

Vista previa:
![image](https://github.com/user-attachments/assets/38bbc1a5-f1b4-4e0a-98b9-82acfb780eb0)

Codigo HTML:
![image](https://github.com/user-attachments/assets/e38bcc4a-476b-496e-9c8b-aaf01dbe80af)

Impresión:
![image](https://github.com/user-attachments/assets/8ce35f4b-0e54-4fb9-ae6a-22d55b6fa5bd)

Documento pdf:
![image](https://github.com/user-attachments/assets/4cdea2e4-d227-40aa-bac9-65827cb0ea7e)

**Comment by a52290451** [comment]
De acuerdo con la investigación realizada, se elige SunEditor como la mejor opción para Incrustar un editor de documentos dinámico en el módulo de plantillas.

**Comment by diegobauto** [comment]
Se evaluaron varios editores WYSIWYG, realizando pruebas y tomando como referencia sus características y funcionalidades.

Los siguientes dos editores ofrecen una amplia gama de componentes, aunque con ciertas limitaciones. Ambos proporcionan un conjunto básico de componentes de forma gratuita, pero para acceder a otros más avanzados es necesario realizar un pago:

- CKEDITOR
- TINY

- SCEDITOR: Este editor cuenta con una comunidad y soporte más reducidos, lo que puede resultar en una implementación menos consistente. Esto podría afectar su capacidad de ser extensible o adaptable.

- EDITOR JS: Aunque este editor ofrece varios componentes adicionales, la estructura de salida que genera es en formato JSON, lo que puede requerir un procesamiento adicional dependiendo del uso previsto (estructura HTML).
