### ISSUE TITLE
Reuniones de empalme para la sesión de contrato 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#136]
Se debe realizar la reunión para presentar el flujo, funcionamiento y conceptos técnicos del cliente para contextualizar al nuevo compañero del proyecto, la issue debe cumplir con los siguientes requerimientos:

- [x] Realizar las reuniones para tratar los temas mencionados

**Comment by ndmc98** [comment]
Se da inicio a la issue que relaciona las sesiones personalizadas con el nuevo contratista para el proceso de empalme y contexto del proyecto.

**Comment by ndmc98** [comment]
- Primera sesión: 29/11/2021 - 11.00 am - Enlace: meet.google.com/nor-aokc-mmh. Temas tratados: contexto de arquitectura y tecnologías trabajadas en la OAS para el sistema en desarrollo. Explicación del ambiente de desarrollo, especificaciones del cliente y estructura por componentes del mismo.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
