### ISSUE TITLE
Ajuste de plantilla Base para construir plan

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1362]
Se requiere realizar el ajuste de la plantilla base y de las condiciones relacionadas con la creación de formatos con una estructura base

**Sub Tareas**

- [x] Revisar si los campos de la estructura: actividad general y actividad especifica son requeridos durante el flujo de la gestion de planes 
- [x] Si estos campos se usan en la lógica funcional del flujo de formulación, seguimiento, evaluación y reportes. Realizar la respectiva corrección para que: 1) Actividad General da nombrado como "Actividad" 2) Actividad especifica se pueda eliminar 
- [x] Realizar pruebas funcionales del sistema una vez se realicen los ajustes

**Criterios de aceptación**

- [x] se ajustan los campos baje para la generación de nuevas plantillas 
- [x] Se prueban los cambios a lo largo de todo el sistema

**Requerimientos**
.
No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] SeAprobada por SM/Líder técnico.

**Comment by ccmendezt** [comment]
## Evidencias - Requerimientos salida a producción
### 04/09/2024 - 16:40

Se quitó de la plantilla base el campo "**Actividades específicas**".

Para la correcta ejecución del flujo para planes que tengan la nueva y antigua plantilla se realizaron modificaciones tanto el cliente como en planeacion_mid.
En el cliente se ajustó la renderización de algunas etiquetas dependiendo de si tienen o no datos. En planeacion_mid se modificaron los controladores de seguimiento y reportes junto con sus respectivos helpers para agregar un control sobre si el plan que se estaba tocando tiene la nueva o antigua estructura, de acuerdo a eso se hace la lectura de datos en seguimiento y reportes.

- La generación de reportes de **plan de acción por unidad** se hace de acuerdo a lo solicitado:
    - Para reportes antiguos no se realizó ninguna modificación:
    ![image](https://github.com/user-attachments/assets/4e6484d2-a146-49d4-994b-e24c777eb13a)

    - Para reportes con la nueva plantilla:
    ![image](https://github.com/user-attachments/assets/2faab7ed-40f3-4f97-9d5e-03e8773b4766)

- La generación de la hoja de identificaciones en los reportes de plan de acción por unidad también se ajustó según lo solicitado:

    - Para reportes antiguos no se realizó ninguna modificación:
    ![image](https://github.com/user-attachments/assets/d0654413-a3ab-42b3-9b8d-d0af15c163e6)

    - Para reportes con la nueva plantilla:
    ![image](https://github.com/user-attachments/assets/6fff3a4f-2b19-4863-9b33-2ecdfbbc11bd)

- La generación de reportes de **plan de acción general** se hace de acuerdo a lo solicitado:

    - Para reportes antiguos no se realizó ninguna modificación:
    ![image](https://github.com/user-attachments/assets/d3c7aafa-3569-460d-866c-1c46e0ae98c6)

    - Para reportes con la nueva plantilla:
    ![image](https://github.com/user-attachments/assets/22452d5c-91c5-4f99-bc9f-647199661236)

## Pull Request asociados a Issue
- **planeacion_mid:** https://github.com/udistrital/planeacion_mid/pull/621
- **planeacion_cliente:** https://github.com/udistrital/planeacion_cliente/pull/1380

## Notas importantes:
  **i.** Se probó el flujo completo (formulación, seguimiento, evaluación y reportes) para un plan de acción con antigua y nueva plantilla, el sistema funcionó de acuerdo a lo esperado, sin embargo, hay que realizar más pruebas.
