### ISSUE TITLE
Mejoras SISGPLAN PT2

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1363]
Se requiere continuar con la corrección de los elementos mencionados en las subtareas pendientes de #1349 .

**Aspectos Técnicos**

1. El mid, crud y cliente están actualizados a día de hoy en las ramas release/0.0.1.
2. Actualmente la funcionalidad se encuentra inoperante.

**Sub Tareas**

- [x] Se deben adicionar mensajes de carga al abrir Identificaciones de Contratistas, Recursos y Docentes en el módulo de Formulación.
- [x] Se deben adicionar mensajes de carga para el menú de "administrar sistema" al momento de cargar los respectivos filtros y almacenamiento de fechas.
- [x] En la identificación de rubros encontrada en el módulo de Formulación se debe permitir la búsqueda de rubros mediante un filtro.
- [x] Permitir que las observaciones dentro de la identificación de rubros se expanda (textarea).
- [x] En el módulo de seguimiento, se requiere mostrar los mensajes de procesando petición o mensajes de carga según sea el caso en los botones de: Guardar componente cualitativo, guardar componente cuantitativo, generar reporte, guardar revisión actividad, iniciar y finalizar revisión JU, enviar corrección, iniciar y finalizar revisión OAPC.
- [x] Ajustar ancho de filas en reporte de Evaluacion para planes armonizados con varios lineamientos, metas y estrategias del PED - Módulo Reportes
- [x] Estandarizar el formato de fecha en todos los componentes de la siguiente manera: dd-mm-yyyy hh:mm:ss

**Criterios de aceptación**

- [x] Se adicionan los mensajes de carga requeridos en los módulos de formulación y seguimiento.
- [x] Se adicionan los filtros en la identificación de rubros.
- [x] Se investiga dónde reposan dichos rubros.
- [x] Se corrigen visualmente los reportes y las observaciones enla identifiación de rubros.
- [x] Se prueban las funcionalidades y correcciones en el monolito.

**Requerimientos**

- ninguno.

**Dependencias**

- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Se ubica documento de rubros para la actualización en el sistema.

[Listado rubros](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EeCzmNTzSblCrb8o_FgM9Q4BX5MDIvDDYLrQxrhlFqsZig?e=7VvfVq)

**Comment by Mechaz123** [comment]
# ACTUALIZACIÓN LISTADO RUBROS #

Teniendo en cuenta el archivo Excel que enviando con la información de los Rubros, se realizó el siguiente script para realizar su conversión al formato que se maneja dentro del sistema.

![Image](https://github.com/user-attachments/assets/42a91180-f7f9-48bd-acf6-df212db08ba2)

Este script guarda la información en formato .txt y con la estructura que se venía manejando en el sistema.

![Image](https://github.com/user-attachments/assets/f1788f58-2b88-4c01-a896-943e66d5004c)

Ya simplemente se hace un pequeño reemplazo de información y de esta manera ya quedan actualizados los rubos.

![Image](https://github.com/user-attachments/assets/a0385770-75d5-46ad-97af-762325daf31e)

## NOTA ##

Existían varios Rubros repetidos, de manera que con la nueva conversión se pasa de aproximadamente 2586 líneas a 1451 líneas.

**Comment by Mechaz123** [comment]
# !!! IMPORTANTE !!! #

Aún se está verificando el apartado de los rubros en Producción y en lo agregado en el Issue, ya que hay muchos códigos de rubros que no coinciden con los enviados, así mismo la cantidad de rubros en el Excel enviado es de 364 y en producción existen 572.

Se adjunta el Excel donde se realizó la comparativa de ambos Rubros manejados.

[COMPARATIVA DE RUBROS.xlsx](https://github.com/user-attachments/files/16863013/COMPARATIVA.DE.RUBROS.xlsx)

Los Códigos de color verde, son los rubros que existen en ambas partes.

**Comment by Mechaz123** [comment]
# CORRECCIÓN DE RUBROS Y MENSAJES DE CARGA #

Se realiza la sincronización de los rubros que existían en producción y en el excel enviado, de manera que se generó un solo archivo JSON, se adjunta el archivo:

[rubros.json](https://github.com/user-attachments/files/16875643/rubros.json)

Por otro lado, se realizó la corrección de los mensajes de carga para la vinculación y desvinculación de roles a los usuarios.

![Gestion usuarios](https://github.com/user-attachments/assets/73ee732e-38f7-4b4f-9cd8-8b34987824e8)

Así mismo se ha agregado un servicio para manejar los mensajes de carga de una manera más fácil, teniendo en cuenta en código proporcionado por Cristian.

![image](https://github.com/user-attachments/assets/8c3f5488-3695-4ffc-abe2-2e4477d66675)

Por último, se agregaron mensajes de carga al apartado de Identificación de recursos y demás, usando el servicio mencionado.

![Mensajes carga de identificacion](https://github.com/user-attachments/assets/fc570915-955b-4d06-bdfc-228c1d45ef80)

## NOTA ##

Se seguirá realizando los otros cambios que tienen prioridad baja, pero en otra rama.

**Comment by Mechaz123** [comment]
# Formato de fecha #

Se verifica en el sistema donde se manejan los formatos de fecha y estos manejan la estructura definida de día/mes/año, se adjuntan imágenes donde se encontraron el uso de fechas en el sistema.

![Image](https://github.com/user-attachments/assets/d6caab71-0a78-471b-b445-e58fb68cf7d9)

![Image](https://github.com/user-attachments/assets/50830339-d06f-400b-8e60-b9503812769e)

## NOTA ##

Teniendo en cuenta lo anterior se da por cumplida esta tarea.

**Comment by Mechaz123** [comment]
# CORRECCION DE ANCHO DE REPORTE DE EVALUACION #

Se realiza la corrección para que, al momento de generar el reporte de evaluación de un plan, este se ajuste al tamaño del texto que se digite.

- **Sin el cambio**

[Reporte_Evaluacion_FACULTAD DE INGENIERIA PRUEBA ORIGINAL 2.xlsx](https://github.com/user-attachments/files/17068615/Reporte_Evaluacion_FACULTAD.DE.INGENIERIA.PRUEBA.ORIGINAL.2.xlsx)

- **Con el cambio**

[Reporte_Evaluacion_FACULTAD DE INGENIERIA PRUEBA CAMBIO 2.xlsx](https://github.com/user-attachments/files/17068617/Reporte_Evaluacion_FACULTAD.DE.INGENIERIA.PRUEBA.CAMBIO.2.xlsx)
