### ISSUE TITLE
Requerimientos salida a producción

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1364]
Se requiere revisar los ítems solicitados por la Oficina Asesora de Planeación, para la salida a producción de SISGPLAN.

**Aspectos Técnicos**

1. El mid, crud y cliente están actualizados a día de hoy en las ramas release/0.0.1.

**Sub Tareas**

- [x] Se deben actualizar los rubros con base en archivo ARCHIVO.
- [x] En la tabla de Identificación de Contratistas se deben actualizar los campos de la siguiente manera:

Se requiere ajustar el encabezado de "Descripción de necesidad" por "Descripción de la necesidad (objeto contractual)" y aumentar su tamaño de registro. Añadir una columna con encabezado "Requisitos mínimos (formación académica y experiencia)", ubicada entre "Descripción de la necesidad (objeto contractual)" y
"Perfil", como se muestra a continuación:
![Screenshot_2024-09-01-21-07-25-276_com.github.android.png](https://github.com/user-attachments/assets/504abdf9-e206-4a67-b4b1-e165308f8968)

Como se menciona revisar la cantidad de caracteres que se pueden registrar actualmente la columna "Descripción de la necesidad (objeto contractual)".
- [x] Tener en cuenta la tarea #1362.

**Criterios de aceptación**

- [x] Se realizan los ajustes y se relizan pruebas funcionales.

**Requerimientos**

- ninguno.

**Dependencias**

- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Tener en cuenta la solicitud mencionado por usuario en el oficio:

Adicionalmente, en el archivo excel en la hoja de identificaciones que se descarga del sistema, además de los campos que se incluyen actualmente, se debe incluir el nuevo campo creado (Requisitos mínimos formación académica y experiencia).

**Comment by C0C045** [comment]
# Avance Vista Tabla Identificación de Contratistas
Actualmente se cambio el nombre de la primera columna de Descripción y también se agregó una nueva columna para el campo de requerimientos, además de guardar satisfactoriamente el campo de requerimientos para tener persistencia en los datos.

**Pruebas Funcionales:**
![Contratistas](https://github.com/user-attachments/assets/b30a6e7f-4fe6-4d4c-8d73-2ebf2bce2876)

### PR's
planes_crud: https://github.com/udistrital/planes_crud/pull/110
planeacion_cliente: https://github.com/udistrital/planeacion_cliente/pull/1374

**Comment by C0C045** [comment]
# PR a Release
planes_crud: https://github.com/udistrital/planes_crud/pull/111
planeacion_cliente: https://github.com/udistrital/planeacion_cliente/pull/1375

**Comment by C0C045** [comment]
# Generación de Reportes desde JEFE_DEPENDENCIA
Se implementó la solución para obtener correctamente las unidades pertenecientes a un rol JEFE_DEPENDENCIA.

**Pruebas Funcionales:**
![reportesJefeUnidad](https://github.com/user-attachments/assets/840f9987-231d-4511-8f29-886624f8aa41)

### PR
planeacion_cliente: https://github.com/udistrital/planeacion_cliente/pull/1376

**Comment by C0C045** [comment]
# PR's a Release
planeacion_clliente: https://github.com/udistrital/planeacion_cliente/pull/1377

**Comment by ccmendezt** [comment]
## Evidencias - Requerimientos salida a producción
### 04/09/2024 - 16:20

- La generación de reportes de **plan de acción por unidad** se hace de acuerdo a lo solicitado:
    - Para reportes antiguos no se realizó ninguna modificación:
    ![image](https://github.com/user-attachments/assets/4e6484d2-a146-49d4-994b-e24c777eb13a)

    - Para reportes con la nueva plantilla:
    ![image](https://github.com/user-attachments/assets/2faab7ed-40f3-4f97-9d5e-03e8773b4766)

- La generación de la hoja de identificaciones en los reportes de plan de acción por unidad también se ajustó según lo solicitado:

    - Para reportes antiguos no se realizó ninguna modificación:
    ![image](https://github.com/user-attachments/assets/d0654413-a3ab-42b3-9b8d-d0af15c163e6)

    - Para reportes con la nueva plantilla:
    ![image](https://github.com/user-attachments/assets/6fff3a4f-2b19-4863-9b33-2ecdfbbc11bd)

- La generación de reportes de **plan de acción general** se hace de acuerdo a lo solicitado:

    - Para reportes antiguos no se realizó ninguna modificación:
    ![image](https://github.com/user-attachments/assets/d3c7aafa-3569-460d-866c-1c46e0ae98c6)

    - Para reportes con la nueva plantilla:
    ![image](https://github.com/user-attachments/assets/22452d5c-91c5-4f99-bc9f-647199661236)

## Pull Request asociados a Issue
- **planeacion_mid:** https://github.com/udistrital/planeacion_mid/pull/621
