### ISSUE TITLE
Pruebas funcionales sprint 21

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#1365]
Se requiere realizar continuar con las pruebas completas de todos los módulos de SISGPLAN, teniendo en cuenta los desarrollos previos y los llevados a cabo desde el sprint 16.

**Especificaciones técnicas**

1. Continuar con las pruebas funcionales deben cubrir todos los desarrollos hasta el sprint 16.
2. Se deben tomar como guía las pruebas realizadas por los desarrolladores en local en cada implementación.
3. El documento de pruebas debe especificar el estado en el que se encuentra el desarrollo, si se valida o no su funcionamiento y las observaciones correspondientes.
4. Tener encuenta los usuarios:
- pruebasoas1 - asistente_planeacion
- pruebasplaneacion - planeacion
- unidadtest - jefe_dependencia
- unidadtest2 - asitente_dependencia
5. Se deben probar solamente los desarrollos, las tareas de análisis o documentación no se tienen en cuenta.
6. Tener en cuenta el diagrama de estados: https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EapOYSf6DV5OpY_6uS7AXIkBLrxapQdD9iheXN88g8Hilg?e=XVQhNQ
7. Se trata de hacer un compendio de todas las pruebas realizadas hasta la fecha en un documento y validar su funcionamiento.
8. Adicional al documento que se debe presentar con las pruebas, se requiere realizar una anotación y seguimiento en forma de comentarios en este issue, de tal forma que se evidencien las pruebas realizadas en cada desarrollo y si aprueban o no. Tomar como guía: https://github.com/udistrital/sga_documentacion/issues/42
9. Carpeta para pruebas funcionales: https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EvgM4KowvOBKjdXD3aFLGV0BGcATolW8LorkydQUQnYMuA?e=MZjaiw
10. Se puede realizar en una nueva hoja de las pruebas realizadas inicialmente para este despliegue.

**Sub Tareas**

- [x] Realizar pruebas funcionales en ambiente de pruebas - SISGPLAN.
- [x] Seguimiento de pruebas funcionales en el issue.
- [ ] Corrección de errores

**Criterios de aceptación**

- [ ] Se presenta un documento con pruebas de todo el sistema.
- [ ] Se presenta el seguimiento de las pruebas realizadas en el issue, asociadas a cada desarrollo.
- [ ] Se presenta documento con errores corregidos

**Requerimientos**

- No presenta.

**Dependencias**

- planeacion_cliente.
- planeacion_mid.
- planes_crud.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by C0C045** [comment]
# Avances pruebas al sistema

## Mejora

- Al crear, editar o inactivar un plan en cualquier módulo la página se recarga y devuelve al usuario al inicio. Este tipo de acción podría generar confusión, ya que usuario espera ver su cambio en el módulo que lo realizo; no espera tener que volver a buscar el respectivo módulo.
![image](https://github.com/user-attachments/assets/f835ae94-6850-473e-85d6-eef16b6f1105)
![image](https://github.com/user-attachments/assets/83c3a16a-a56f-489e-80f4-f5fef70ae724)


## Problema
El promedio de brechas de qué se muestra en el módulo de Consulta para planes en Formulación no concuerdan con las brechas mostradas en el módulo de Evaluación.
### Ejemplo 1:
![image](https://github.com/user-attachments/assets/8cfa3ebd-83c7-4035-be34-283264469bab)
![image](https://github.com/user-attachments/assets/f21b8fb1-82e9-431e-832c-46f5b8470f6b)
### Ejemplo 2:
![image](https://github.com/user-attachments/assets/8edf51c6-e017-42b1-b17f-7e03c48356ca)
![image](https://github.com/user-attachments/assets/4f368ddf-5773-453d-84be-24281e01bdea)

**Comment by Mechaz123** [comment]
# CORRECCIÓN DE BUSQUEDA DE RUBROS #

Se realiza la corrección de la búsqueda de rubros en la fase de formulación.

![Image](https://github.com/user-attachments/assets/97d6eb75-5bcb-406f-ae22-a2328be481cf)

**Comment by C0C045** [comment]
# Restricción de Verificación de Planes
Se implementó la funcionalidad para evitar la verificación de un plan en formulación si este posee observaciones.

## Pruebas funcionales
### Desde Formulación
![Formulacion](https://github.com/user-attachments/assets/b7cd5736-5c1d-4206-be47-ca3e83ddd9db)

### Desde Pendientes
![Pendientes](https://github.com/user-attachments/assets/cd1916bc-7ad7-4231-9569-00e127b248a3)
