### ISSUE TITLE
Despliegue modelo de plantillas_crud en ambiente de pruebas - Serverless - Lambdas - AWS

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1367]
Se requiere llevar a cabo el despliegue de infraestructura de plantillas crud en AWS, mediante la utilización de Lambdas.

**Especificaciones Técnicas**

- Se requiere configurar infraestructura  en AWS a través de lambdas y servicios complementarios para plantillas_crud.
- Se requiere emplear una lambda para cada entidad en el modelo de datos.
- Se debe probar conexión con la base de datos en cada lambda.
- Una vez cargados los servicios, se debe probar su funcionamiento, mendiante peticiones y respuestas.
- Se deben ajustar elementos no funcionales.
- Se deben realizar pruebas de tiempo de respuesta de las lambdas.

**Sub Tareas**

- [x] Configuación de modelo de datos de plantillas_crud en AWS mediante lambdas.
- [x] Pruebas de conexión con la BD.
- [x] Pruebas de funcionamiento de las lambdas.
- [x] Pruebas de tiempo de respuesta de las lambdas.
- [x] Ajustes requeridos.

**Criterios de aceptación**

- [x] Se presenta plantillas_crud completamente funcional empleando lambas en AWS.

**Requerimientos**

- [x] Completar issue #1356 .
- [x] Credenciales de acceso y permisos AWS - Lambdas.
- [x] Aprobación modelo de datos plantillas.

**Dependencias**

- Infraestructura AWS.
- plantillas_crud.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Se asocia desarrollo de serverless, con funciones Lambda y modelo de datos:

Repostorio y rama respectiva: 
https://github.com/udistrital/plantillas_crud_serverless/tree/feature/plantillas_tipo

**Comment by diegobauto** [comment]
![image](https://github.com/user-attachments/assets/7d801488-60ad-4c70-875d-cce512d0e5d1)

**Comment by diegobauto** [comment]
Actualización grupo_id como uuid:

![image](https://github.com/user-attachments/assets/2066c366-83b8-427e-ac92-2e7a1ba98a25)

**Comment by diegobauto** [comment]
Se realizó reunión para el despligue y se ajusto desarrollo hacia develop:
https://github.com/udistrital/plantillas_crud_serverless/pull/2

**Comment by a52290451** [comment]
Solicitud de creación de BD de plantillas en ambiente de pruebas:

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=64230&group_id=177

**Comment by diegobauto** [comment]
Despliegue funcionando correctamente: 

- Función health:
![image](https://github.com/user-attachments/assets/bcfce7e2-51fd-4948-ba45-c65b56ab7cdf)

- Obtención de plantillas: 
![image](https://github.com/user-attachments/assets/a5e69e3a-dfaa-47a0-b07d-7e4f4d9edf70)

- Inserción y obtención de tipo_plantilla:
![image](https://github.com/user-attachments/assets/e76efbe9-fa36-497b-9c0c-917da19a5a83)

**Comment by diegobauto** [comment]
Pull request:

https://github.com/udistrital/plantillas_crud_serverless/pull/2
