### ISSUE TITLE
Revisión de parámetros de sisgplan en parametros_crud - Pruebas y Producción.

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1373]
Se requiere realizar la revisión y ajuste de parametros consumidos en parametros_crud en pruebas y producción.

**Especificaciones Técnicas**

- Todos los parametros que se utilizan en ambiente de pruebas, consumidos desde parametros_crud, deben ser iguales en ambiente de producción.

**Sub Tareas**

- [ ] Revisión de parametros consumidos en parametros_crud
- [ ] Ajuste de parametros en producción

**Criterios de aceptación**

- [x] Los parametros consumidos en parametros_crud son iguales en pruebas y producción.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Oscarjaimes1710** [comment]
Se trabaja actualmente sobre el documento de consumos : https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7B6c0c956c-8603-478d-aad2-f8b51ecd3639%7D&action=edit&activeCell=%27Pruebas%20Funcionales%20-%20Daniel%27!F3&wdinitialsession=43e49333-36f4-d87c-e8e0-d77f768670dd&wdrldsc=2&wdrldc=1&wdrldr=AccessTokenExpiredWarningUnauthenticated%2CRefreshin

**Comment by Oscarjaimes1710** [comment]
Lista de Endpoint's consultas en pruebas: 

- http://pruebasapi.intranetoas.udistrital.edu.co:8510/v1/periodo?query=CodigoAbreviacion:VG,activo:true
- http://pruebasapi.intranetoas.udistrital.edu.co:8510/v1/tipo_parametro?query=CodigoAbreviacion:PC,Activo:true
- http://pruebasapi.intranetoas.udistrital.edu.co:8510/v1/parametro?query=TipoParametroId:36
- http://pruebasapi.intranetoas.udistrital.edu.co:8510/v1/parametro_periodo?query=ParametroId.TipoParametroId.CodigoAbreviacion:P_SISGPLAN,Activo:true
- http://pruebasapi.intranetoas.udistrital.edu.co:8510/v1/periodo?query=Id:39
- http://pruebasapi.intranetoas.udistrital.edu.co:8510/v1/periodo?query=Id:3
- http://pruebasapi.intranetoas.udistrital.edu.co:8510/v1/periodo?query=Id:25
- http://pruebasapi.intranetoas.udistrital.edu.co:8510/v1/periodo?query=Id:35
- http://pruebasapi.intranetoas.udistrital.edu.co:8510/v1/parametro_periodo?query=ParametroId.CodigoAbreviacion:FORMATO_PAF,ParametroId.TipoParametroId.CodigoAbreviacion:P_SISGPLAN,Activo:true
- http://pruebasapi.intranetoas.udistrital.edu.co:8510/v1/parametro_periodo?query=ParametroId.CodigoAbreviacion:CORREO_OAP,ParametroId.TipoParametroId.CodigoAbreviacion:P_SISGPLAN,Activo:true

Lista de Endpoint's consultados en producción: 

- http://api.intranetoas.udistrital.edu.co:8510/v1/periodo?query=CodigoAbreviacion:VG,activo:true
- http://api.intranetoas.udistrital.edu.co:8510/v1/tipo_parametro?query=CodigoAbreviacion:PC,Activo:true
- http://api.intranetoas.udistrital.edu.co:8510/v1/parametro?query=TipoParametroId:36
- http://api.intranetoas.udistrital.edu.co:8510/v1/parametro_periodo?query=ParametroId.TipoParametroId.CodigoAbreviacion:P_SISGPLAN,Activo:true
- http://api.intranetoas.udistrital.edu.co:8510/v1/periodo?query=Id:39
- http://api.intranetoas.udistrital.edu.co:8510/v1/periodo?query=Id:3
- http://api.intranetoas.udistrital.edu.co:8510/v1/periodo?query=Id:25
- http://api.intranetoas.udistrital.edu.co:8510/v1/periodo?query=Id:35
- http://api.intranetoas.udistrital.edu.co:8510/v1/parametro_periodo?query=ParametroId.CodigoAbreviacion:FORMATO_PAF,ParametroId.TipoParametroId.CodigoAbreviacion:P_SISGPLAN,Activo:true
- http://api.intranetoas.udistrital.edu.co:8510/v1/parametro_periodo?query=ParametroId.CodigoAbreviacion:CORREO_OAP,ParametroId.TipoParametroId.CodigoAbreviacion:P_SISGPLAN,Activo:true

Códigos de abreviación consultados: 

- CodigoAbreviacion:VG
- CodigoAbreviacion:P_SISGPLAN
- CodigoAbreviacion:CORREO_OAP
- CodigoAbreviacion:FORMATO_PAF
- CodigoAbreviacion:P_SISGPLAN
- CodigoAbreviacion:PC

**Comment by Oscarjaimes1710** [comment]
![Captura de pantalla 2024-09-04 a la(s) 8 48 31 p  m](https://github.com/user-attachments/assets/fd5148d7-dc47-46ea-a975-eeec18f25c34)

Se hace la inserción de la vigencia del ano 2025 a producción.
