### ISSUE TITLE
Realizar la funcionalidad para la verificación de la ponderación de todas las actividades no puede ser diferente de 100%

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#138]
Se debe desarrollar la funcionalidad que al momento de culminar un plan se verifique la suma del campo Ponderación de la actividad tienen que ser igual al 100%, se debe tener en cuenta que nombre no necesariamente es el mismo siempre, implementar una funcionalidad que rastree si el campo contiene el nombre de ponderación y actividad, si no se cumple la condición del 100 % se debe notificar al usuario por medio de un mensaje de alerta y no permitir la culminación del plan, la issue debe cumplir con los siguiente requerimientos: 

- [x] Desarrollar la funcionalidad de verificación de la suma de la ponderación según lo explicado 
- [x] Desarrollar el mensaje de alerta notificando al usuario y la no culminación del plan de acción

**Comment by brayaned** [comment]
Se realizó la funcionalidad para la búsqueda del campo ponderación, y con la suma de todas la ponderaciones de actividades activas, se retorna un json con las ponderaciones y el total. En el cliente se realiza la verificación para poder culminar o no un plan dependiendo de su correcta ponderación.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
