### ISSUE TITLE
Actualización de Documentación NOTIFICACIONES

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#1423]
De acuerdo con los avances realizados hasta la issue #1333 , se requiere actualizar toda la documentación relacionada con notificaciones internas, incluyendo los cambios realizados en notificaciones_mid, notificaciones_crud y su implementación mediante webcomponents y MFs en el CORE.

**Sub Tareas**

- [x] Actualización de documento técnico de notificaciones.

**Criterios de aceptación**

- [x] Se entrega documento técnico de notificaciones actualizado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by diegobauto** [comment]
Actualización documentación notificaciones:
https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EagFPm9pKfRLn1JZrfVCl9EBPye3vjDMgIbNMdwFwGOobg?e=Ali3ij

**Comment by diegobauto** [comment]
Se añade documento Diagnostido de notificaciones en el siguiente enlace: [Enlace](https://udistritaleduco-my.sharepoint.com/personal/computo_udistrital_edu_co/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%2FINVERSI%C3%93N%2FPROYECTOS%20DE%20INVERSI%C3%93N%2FGERENCIA%20DE%20PROYECTOS%2FPROYECTOS%20OAS%2FPROYECTO%20PLANEACI%C3%93N%2F2024%2FEJECUCI%C3%93N%2FDocumentos%20Planeaci%C3%B3n%2FDocumentaci%C3%B3n%20Final&ct=1726933139746&or=Teams%2DHL&ga=1)

Además de añadir la descripcion en Diagnostico Final SISGPLAN.
