### ISSUE TITLE
Implementación de la consulta del arbol del rubro con solo la rama de gasto 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#145]
Se debe desarrollar la implementación la consulta del árbol de rubros para el componente de identificación presupuestal, la issue debe cumplir los siguientes requerimientos:

- [x] Consumir el servicio de pruebas de kronos en back http://pruebasapi.intranetoas.udistrital.edu.co:8203/v1/arbol_rubro
o en el cliente https://autenticacion.portaloas.udistrital.edu.co/apioas/plan_cuentas_mongo_crud/v1/arbol_rubro_apropiacion/arbol_apropiacion_valores/%7Bunidadejecutora%7D/%7Bvigencia%7D

- [x] Filtrar solo las ramas con código inicial 3 y solo las ultimas ramas del árbol 
- [x] Implementar el nombre y el código en el componente de identificación presupuestal

**Comment by brayaned** [comment]
Se da inicio a la issue.

**Comment by brayaned** [comment]
Se realizo la implementación de una función en el mid que sea capaz de filtrar las hojas del árbol de rubros. Específicamente la rama correspondiente a gastos. Esta función se consume desde el cliente y se cargan los rubros correspondientes en la tabla de identificación de recursos.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
