### ISSUE TITLE
Analizar y establecer los reportes de consolidado presupuestal, plan de acción anual y plan de acción unidad con herramienta SpagoBI 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#146]
Se debe realizar un análisis de la herramienta SpagoBI  para la realización de los tres reportes solicitados, una vez analizado la herramienta se debe implementar  los reportes, la issue debe cumplir con los siguientes requerimientos:

- [x] Revisar la documentación desarrollada en otros proyectos
- https://github.com/udistrital/arka_cliente/issues/400
- https://github.com/udistrital/sga_mid/issues/148
- https://github.com/udistrital/produccion_academica_cliente/issues/70
- https://github.com/udistrital/arka_cliente/issues/660

- [ ] Implementar el reporte plan de acción unidad
- [ ] Implementar el reporte plan de acción anual

**Comment by JoseAlejoGonza** [comment]
Se da inicio a la issue.

**Comment by JoseAlejoGonza** [comment]
Se pasa a segundo plano dado que se encontró inconvenientes con la conexión a la bd, de igual manera se sigue revisando paralelamente a las demás issues que se están trabajando en el momento.

**Comment by JoseAlejoGonza** [comment]
Se realizaron pruebas respecto a la conexión a la base de datos en las cuales se identificó que el inconveniente de conexión es la autenticación, dado que al iniciar mongodb de manera segura utilizando un usuario, no permite la conexión con la herramienta, sin embargo al iniciar mongodb de forma no segura, si permite el enlace con knowage.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
