### ISSUE TITLE
Revisar la documentación técnica de la oficina  

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#147]
Se debe realizar la lectura y el entendimiento de la documentación técnica dispuesta en la oficina, la issue debe cumplir con los siguiente requerimientos:

- [x] Realizar la lectura y el entendimiento de la documentación técnica https://github.com/udistrital/lineamientos_oas

**Comment by JoseAlejoGonza** [comment]
Se da inicio a la issue.

**Comment by JoseAlejoGonza** [comment]
Se completó la lectura y entendimiento de la documentación técnica requerida

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
