### ISSUE TITLE
Completar el flujo para la generación de observaciones y cambios de estados segun rol y estado 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#150]
Se debe desarrollar el flujo completo y la integración del cambio de entados con el flujo de los botones, también  incluir en le componente de  estado plan un icono que represente el estado del plan, la issue debe cumplir con los siguientes requerimientos:

- [x] Desarrollar el flujo completo que integre el flujo de los estados y el flujo de los botones 
- [x] Incluir en le componente de  estado plan un icono que represente el estado del plan
- [x] Realizar una prueba de escritorio para comprobar el flujo completo de la observación jugando con los roles del sistema 
- [x] Desarrollar el flujo de versonamiento a las identificaciones

**Comment by brayaned** [comment]
Se da inicio a la issue.

**Comment by brayaned** [comment]
Se realizo el desarrollo de la issue realizando el flujo de botones segun el estado y rol que este loggeado en el sistema. Se añadieron los iconos para cada estado y se realizo una prueba de escritorio para verificar el funcionamiento del flujo de estados. 
Por ultimo, se realizo una modificación a la función de versionar en planeacion_mid para que también realizara el versionamiento de todas las identificaciones asociadas a un plan.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
