### ISSUE TITLE
Ajuste de observación para la identifiación de contratista y de recursos para cada registro 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#151]
Se debe desarrollar la funcionalidad para incluir una observación por cada registro (fila) en los componentes de identificación de contratistas e identificación de recursos, se debe tener presente el flujo actual definido en el diagrama, (visualización, edición, bloqueo de edición, edición y visualización de las observaciones), la issue debe cumplir con los siguientes requerimientos:

- [x] Desarrollar la funcionalidad en el componente  para la creación de observaciones para cada registro teniendo en cuenta el rol del usuario y el estado del plan según el diagrama de flujo 
- [x] Desarrollar funcionalidad back de almacenamiento, consulta y edición de las observaciones.
- [x] Desarrollar la funcionalidad de bloqueo de los componentes de identificación cuando el plan pasa por un estado pre aval, solo se puede observar la tabla sin observaciones

**Comment by brayaned** [comment]
Se da inicio a la issue.

**Comment by brayaned** [comment]
Se realizó el flujo para la columna de observaciones y sus respectivas banderas para el manejo de los diferentes roles y estados. No fue necesario modificar el mid para el guardado y edición de las observaciones de cada fila. No se presento ningún problema mayor durante el desarrollo, por lo tanto se da como terminado este.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
