### ISSUE TITLE
Creación del flujo de observación para el componente de identificación docente 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#155]
Se debe desarrollar la funcionalidad para incluir una observación por cada registro (fila) en el componente de identificación de docentes, se debe tener presente el flujo actual definido en el diagrama, (visualización, edición, bloqueo de edición, edición y visualización de las observaciones), la issue debe cumplir con los siguientes requerimientos:

- [x] Desarrollar la funcionalidad en el componente  para la creación de observaciones para cada registro teniendo en cuenta el rol del usuario y el estado del plan según el diagrama de flujo 
- [x] Desarrollar funcionalidad back de almacenamiento, consulta y edición de las observaciones.
- [x] Desarrollar la funcionalidad de bloqueo de los componentes de identificación cuando el plan pasa por un estado pre aval, solo se puede observar la tabla sin observaciones

**Comment by brayaned** [comment]
Se da inicio a la issue.

**Comment by brayaned** [comment]
Se realizó el flujo de observaciones siguiendo como guía el flujo realizado para la identificación de recursos y contratistas. Se encontró que la función para el guardado de informacion se encuentra en el mid pero falta la implementación en el cliente. El desarrollo de la issue se da por terminado.
