### ISSUE TITLE
Ajustar el select de las unidades sin los programas académicos 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#156]
Se debe ajustar la consulta del select de las unidas con el filtro de solo unidades académicas y administraba, excluyendo los proyectos académicos, la issue debe cumplir con los siguientes requerimientos:
 

- [x] Realizar el ajuste de la consulta con los requerimientos mencianos

**Comment by brayaned** [comment]
Se dio inicio a la issue el 16/12/2021.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
