### ISSUE TITLE
Ajuste de menú según lo definido en la mesa de trabajo 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#157]
Se debe realizar el ajuste de la distribución de los menús según lo definido en la mesa de trabajo, la issue debe cumplir con los siguientes requerimientos:

- [x]  Realizar los ajustes según el documento definido por la oficina de planeación

**Comment by fabianbarreto02** [comment]
[Menú Sistema.pptx](https://github.com/udistrital/planeacion_cliente/files/7716078/Menu.Sistema.pptx)

**Comment by brayaned** [comment]
Se da inicio a la issue.

**Comment by brayaned** [comment]
Se realizó el ajuste correspondiente al dashboard de planeacion_cliente siguiendo el documento definido por la oficina de planeación. No se presento ningún problema durante el desarrollo.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
