### ISSUE TITLE
Registro del plan de acción de funcionamiento por parte de la dependencia encargada 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#163]
Se debe realizar la funcionalidad y el flujo para realizar el registro de un plan de acción de funcionamiento por parte de una dependencia, la issue debe cumplir con los siguientes requerimientos:

- [x] Implementar funcionalidad para el cambio de estado del plan segun el diagrama de estados

**Comment by brayaned** [comment]
Se dio inicio a la issue el 6/01/2022.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
