### ISSUE TITLE
Prueba de funcionamiento para el componente de formulación de plan de acción 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#164]
Se debe realizar una prueba de escritorio del modulo completo con todos los componentes (actividades, identificación de recursos, contratistas y docentes), funcionalidad de creación, edición y eliminación (actividades, identificación de recursos, contratistas y docentes) y cambio de estado al culminar el plan, la issue debe cumplir con los siguientes requerimientos:

- [x] Realizar la prueba mencionada 
- [x] Arreglar los bugs encontrado en la prueba

**Comment by brayaned** [comment]
Se dio inicio a la issue el 6/01/2022.

**Comment by brayaned** [comment]
Se dio inicio a la issue el 6/01/2022.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
