### ISSUE TITLE
Implementación del reporte de consolidado presupuestal con la herramienta Knowage segun el formato 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#165]
Se debe implementar de forma local el reporte del consolidado presupuestal con la herramienta Knowage segun el formato, la issue debe cumplir con los siguientes requerimientos:

- [ ]  Desarrollar el reporte definido

**Comment by JoseAlejoGonza** [comment]
se realizan pruebas de manera local con la base de datos de mongo, dando como resultado que al intentar conectar de manera segura con un usuario definido, la herramienta no lo permite, sin embargo al conectar de manera local sin usuario definido, la herramienta permite la conexión.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
