### ISSUE TITLE
Creación del componente para la visualización de consolidado de los planes de acción de funcionamiento 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#166]
Se debe crear el componente con tres menús para los tres reportes (Reporte plan de acción por unidad, Reporte plan de acción anual y Reporte consolidado presupuestal), este componente contendrá los embebidos de los reportes, la issue debe cumplir con los siguientes requerimiento:

- [x] Desarrollar el componente antes explicado

**Comment by JoseAlejoGonza** [comment]
se da inicio a la issue

**Comment by JoseAlejoGonza** [comment]
se creo y desarrolló el componente de reportes en la rama feat/OpcionReporte
