### ISSUE TITLE
Analisis  de los ajustes necesarios para el registro del seguimiento y evaluación de los planes de acción de funcionamiento 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#168]
Se debe realizar una análisis para la modificación del modelo de datos de planes crud  por el desarrollo de los módulos de seguimiento y evaluación de los planes de acción de funcionamiento tener como referencia el documento excel y el [mockup ](https://drive.google.com/file/d/1wAthn9dD3RSdLTYMF9aAmT8o0Lsfkrb2/view?usp=sharing), la issue debe cumplir con los siguientes requerimientos:

- [x]  Realizar el análisis de las posibles ajustes del modelo de datos (tener presente toda la información que se debe registrar)
- [x] Tener presente tabla para el manejo de seguimiento y evaluación de un plan de acción 
- [x] Tener presenta la necesidad de una bandera para habilitar o inhabilitar un trimestre particular (cuatro trimestres) 
- [x] Analizar la reutilización o no de la tabla estado plan para el manejo de estados en el proceso de seguimiento ( estamos pendientes ) con versonamiento 
- [x] Realizar una prueba de escritorio de la propuesta 

[R2 - C3 Formato de Reporte Plan de Acción.xlsx](https://github.com/udistrital/planeacion_cliente/files/7716303/R2.-.C3.Formato.de.Reporte.Plan.de.Accion.xlsx)

**Comment by brayaned** [comment]
Se dio inicio a la issue el 11/01/2022.

**Comment by brayaned** [comment]
Se realizo el desarrollo de la issue modificando el modelo de datos para agregar las nuevas tablas que tendrán la informacion del seguimiento y la evaluación. Se tuvo en cuenta los nuevos estados propuestos por el analista de requerimientos para seguimiento. También se realizo una prueba de escritorio para verificar la necesidad de banderas para la activación de los diferentes periodos.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
