### ISSUE TITLE
Subir los reportes al servidor de Knowage de la oficina  

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#169]
Se debe realizar el proceso de subir los reportes en el servidos de Knowage de la oficina, apoyarse en el compañero ludwing, la issue debe cumplir con lo siguientes requerimientos:

- [ ] Subir los reportes desarrollado de forma local al servidor de la oficina

**Comment by JoseAlejoGonza** [comment]
se realizan pruebas de manera local con la base de datos de mongo, dando como resultado que al intentar conectar de manera segura con un usuario definido, la herramienta no lo permite, sin embargo al conectar de manera local sin usuario definido, la herramienta permite la conexión.
