### ISSUE TITLE
Pruebas funcionales de los desarrollado  en el modulo de reportes 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#171]
Se debe realizar una prueba de escritorio del modulo de reportes, se debe verificar en el entorno de pruebas que se generen los reportes antes desarrollados, la issue debe cumplir con los siguientes requerimientos:

- [ ] Realizar la prueba de escritorio 
- [ ]  Ajustar los bug encontrados

**Comment by JoseAlejoGonza** [comment]
se realizan pruebas de manera local con la base de datos de mongo, dando como resultado que al intentar conectar de manera segura con un usuario definido, la herramienta no lo permite, sin embargo al conectar de manera local sin usuario definido, la herramienta permite la conexión.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
