### ISSUE TITLE
Implementación del servicio de desagregado para el componente de docencia parte 2

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#172]
Se debe implementar el servicion de desagregado desarrollado para los cálculos del componente docencia, la issue debe cumplir con los siguientes requerimientos:

- [x] Ajustar el componente para el nuevo campo de definición de horas y semanas segun analista 
- [x] Consumir el servicio de desagregación de sueldo, en el endpoint http://pruebasapi2.intranetoas.udistrital.edu.co:8529/v1/services/desagregado_planeacion o https://autenticacion.portaloas.udistrital.edu.co/apioas/resoluciones_docentes_mid/v2/services/desagregado_planeacion usar un metodo post con la siguiente cuerpo 

`[
    {
        "Vigencia": 2021,
        "Dedicacion": "HCP",
        "Categoria": "Titular",
        "NivelAcademico": "POSGRADO"
    },
    {
        "Vigencia": 2021,
        "Dedicacion": "TCO",
        "Categoria": "Asociado",
        "NivelAcademico": "PREGRADO"
    }
]`

la respuesta del servicio es 

`{
    "Data": [
        {
            "Categoria": "Titular",
            "Dedicacion": "HCP",
            "NivelAcademico": "POSGRADO",
            "Vigencia": 2021,
            "arl": 949,
            "caja": 7268,
            "cesantias": 15142,
            "icbf": 5451,
            "interesCesantias": 1817,
            "pension": 29073,
            "primaNavidad": 13460,
            "primaVacaciones": 7537,
            "salarioBasico": 181705.2,
            "salud": 22713,
            "vacaciones": 7537
        },
        {
            "Categoria": "Asociado",
            "Dedicacion": "TCO",
            "NivelAcademico": "PREGRADO",
            "Vigencia": 2021,
            "arl": 30405,
            "caja": 232986,
            "cesantias": 485387,
            "icbf": 174739,
            "interesCesantias": 58246,
            "pension": 931942,
            "primaNavidad": 431455,
            "primaVacaciones": 241615,
            "salarioBasico": 5824640,
            "salud": 728080,
            "vacaciones": 241615
        }
    ],
    "Message": "Cálculos realizados con éxito",
    "Status": 201,
    "Success": true
}`

- [x] Implementar el servicio para el componente 
- [x] Ajustar funcionalidad para comprobación de asignación de maxima horas semanales y minimas horas semanales 

`horas_semanales_maximas(hch,8).
horas_semanales_maximas(hcp,16).
horas_semanales_maximas(mto,20).
horas_semanales_maximas(tco,40).`

`horas_semanales_minimas(hcp,2).
horas_semanales_minimas(hch,4).
horas_semanales_minimas(mto,16).
horas_semanales_minimas(tco,24).`

- [x] Implementar funcionalidad para de campos publico y privado

**Comment by fabianbarreto02** [comment]
[Formato Formulación Plan de Acción 2022 (4).xlsx](https://github.com/udistrital/planeacion_cliente/files/7722702/Formato.Formulacion.Plan.de.Accion.2022.4.xlsx)

**Comment by brayaned** [comment]
Se dio inicio a la issue el dia 27/12/2021.

**Comment by brayaned** [comment]
Se debió alargar el desarrollo de la issue debido a que durante la semana se realizó el flujo para el guardado y cargado de la información desde la base de datos. Las funciones estaban creadas en el mid pero no se habían implementado en el cliente. Al flujo del mid para la carga de información de las identificaciones se modifico, ya que el flujo para la identificación docente es diferente a el de las otras dos identificaciones.

**Comment by brayaned** [comment]
Se terminó de implementar el servicio del desagregado para la tabla de identificacion docente. Se modificaron algunas funciones del mid y se realizó la implementación de las operaciones correspondientes entre los campos de la tabla.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
