### ISSUE TITLE
Implementación del mockup para el seguimiento rol unidad académico administrativa componentes Planes de acción anual y Información basica plan de acción 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#173]
Se debe realizar la implementación de los componentes para el seguimiento rol unidad académico administrativa componentes Planes de acción anual y Información básica plan de acción según el [mockup ](https://drive.google.com/file/d/1wAthn9dD3RSdLTYMF9aAmT8o0Lsfkrb2/view?usp=sharing), la issue debe cumplir con los siguientes requerimientos:

- [x] Implementar el componente   PLANES DE ACCIÓN ANUAL (imagen de referencia, guiarse con el documento en drive)
![image](https://user-images.githubusercontent.com/43799065/146297464-663729c5-6253-46ee-ac93-c344a912dd8e.png)

- [x] Implementar la funcionalidad del botón seguimiento para la dirección hacia el componente Información básica 
- [x] Implementar el componente  INFORMACIÓN BASICA PLAN DE ACCIÓN  (imagen de referencia, guiarse con el documento en drive)
![image](https://user-images.githubusercontent.com/43799065/146297625-3c5663d9-5198-4077-83f1-7f610d883847.png)

**Comment by JoseAlejoGonza** [comment]
se da inicio a la issue

**Comment by JoseAlejoGonza** [comment]
se completó la tarea creando los mockups mencionados y la redirección del botón

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
