### ISSUE TITLE
Implementación del del mockup para el seguimiento rol unidad académico administrativa componentes Información del plan, Reporte Trimestral, resumen avance trimestre y avance del indicador 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#174]
Se debe realizar la implementación de los componentes para el seguimiento rol unidad académico administrativa componentes Información del plan, Reporte Trimestral, resumen avance trimestre y avance del indicador   plan de acción según el [mockup ](https://drive.google.com/file/d/1wAthn9dD3RSdLTYMF9aAmT8o0Lsfkrb2/view?usp=sharing), la issue debe cumplir con los siguientes requerimientos:

- [x] Implementar el componente    INFORMACIÓN DEL PLAN  (imagen de referencia, guiarse con el documento en drive)
![image](https://user-images.githubusercontent.com/43799065/146298506-cd4a29dc-2765-4713-85a9-246245316547.png)

- [x] Implementar la funcionalidad del botón Reporte periodo para la dirección hacia el componente reporte 
- [x] Implementar el componente    REPORTE TRIMESTRAL  (imagen de referencia, guiarse con el documento en drive)
![image](https://user-images.githubusercontent.com/43799065/146298581-aca87b9b-1694-4c1b-a826-43403e07ed27.png)

- [x] Implementar el componente    RESUMEN AVANCE POR TRIMESTRE  (imagen de referencia, guiarse con el documento en drive)
![image](https://user-images.githubusercontent.com/43799065/146298632-a48590e1-a77d-47b3-8187-8e0ac627fd3a.png)

- [x] Implementar la funcionalidad del botón Generar  para la dirección hacia el componente reporte trimestre X
- [x] Implementar el componente     AVANCE DEL INDICAROR  (imagen de referencia, guiarse con el documento en drive)
![image](https://user-images.githubusercontent.com/43799065/146298698-c14ba471-c732-4781-b88f-451b34f5d729.png)

**Comment by JoseAlejoGonza** [comment]
se da inicio a la issue

**Comment by JoseAlejoGonza** [comment]
Se completó la tarea implementando los mockups requeridos incluyendo las funcionalidades de los botones para el flujo

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
