### ISSUE TITLE
Ajuste de modelos de datos y apis CRUD para la definición del registro de los indicadores de seguimientos en planes de acción de funcionamiento  

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#175]
Se debe realizar el ajuste del modelo de datos para el registro y definición del seguimiento y evaluación del plan de acción, también ajustar el api para los nuevos controladores básicos, la issue debe cumplir con los siguientes requerimientos:

- [x]  Ajustar el modelo de datos en el drive con la propuesta presentada (versión 7)
- [x] Implementar los ajuste del api con el modelo (migración, controlador, modelo, metodos get,post, put y delete)
- [x] Desplegar en test (release/0.0.1)

**Comment by brayaned** [comment]
Se dio inicio a la issue el 19/01/2022.

**Comment by brayaned** [comment]
Se realizaron los ajuste necesarios en el crud para la implementación de las nuevas tablas para el manejo de la información del seguimiento y evaluación.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
