### ISSUE TITLE
Implementación del mockup para el seguimiento rol unidad académico administrativa componentes Descripción cualitativa trimestre, del rol de Planeación los componentes Listado planes de acción anual, Información básica plan de acción y Listado activadas 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#176]
Se debe Implementación del mockup para el seguimiento rol unidad académico administrativa componentes Descripción cualitativa trimestre, del rol de Planeación los componentes Listado planes de acción anual, Información básica plan de acción y Listado activadas, la issue debe cumplir con los siguientes requerimientos:

- [x]  Implementar el componente   DESCRIPCIÓN CUALITATIVA TRIMESTRE rol unidad  (imagen de referencia, guiarse con el documento en drive)

 
![image](https://user-images.githubusercontent.com/43799065/146304379-57863e27-44b2-4fb7-a8d2-2f1c33e881a7.png)

- [x] Implementar el componente     LISTADO PLANES DE ACCIÓN ANUAL  rol Planeación (imagen de referencia, guiarse con el documento en drive)

![image](https://user-images.githubusercontent.com/43799065/146304436-90c31ed3-0277-4378-8c05-80b35e3363e3.png)

- [x] Implementar la funcionalidad del botón seguimiento para la dirección hacia el componente Información básica rol planeación 

- [x] Implementar el componente      INFORMACIÓN BASICA PLAN DE ACCIÓN y   LISTADO ACTIVIDADES  rol Planeación (imagen de referencia, guiarse con el documento en drive)

![image](https://user-images.githubusercontent.com/43799065/146304516-9ce51320-9860-4bab-b971-1ed684a9a346.png)

**Comment by JoseAlejoGonza** [comment]
se da inicio a la issue

**Comment by JoseAlejoGonza** [comment]
se completó la issue implementando el mockup en el cliente.
