### ISSUE TITLE
Construcción de componente en el modulo de construcción  para la habilitación de reporte por trimestre para una vigencia particular 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#177]
Se debe desarrollar el componte componente en el modulo de construcción  para la habilitación de reporte por trimestre para una vigencia particular ( a la espera del mockup), a su vez desarrollar la funcionalidad para el cambio de la bandera (habilitar el registro de un trimestre y vigencia particular), la issue debe cumplir con los siguientes requerimientos:

- [x] Se debe construir el componente para la función mencionado 
- [x]  Crear la funcionalidad para la habilitación del seguimiento

**Comment by brayaned** [comment]
Se da inicio a la issue.

**Comment by brayaned** [comment]
Se desarrollo el componente gestionar-reportes para la habilitación de reportes trimestrales por parte de la oficina de planeación. También se crearon algunas funciones en el mid que permitirán el flujo para la habilitación de cada uno de los trimestres durante todo el seguimiento.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
