### ISSUE TITLE
Implementación del mockup para el seguimiento rol componentes   INFORMACIÓN DEL PLAN,   REPORTE TRIMESTRAL, RESUMEN AVANCE POR TRIMESTRE,    AVANCE DEL INDICAROR,  DESCRIPCIÓN CUALITATIVA TRIMESTRE, EVIDENCIAS y   OBSERVACIONES PLANEACIÓN

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#180]
Se debe Implementación del mockup para el seguimiento rol componentes   INFORMACIÓN DEL PLAN,   REPORTE TRIMESTRAL, RESUMEN AVANCE POR TRIMESTRE,    AVANCE DEL INDICAROR,  DESCRIPCIÓN CUALITATIVA TRIMESTRE y   OBSERVACIONES PLANEACIÓN, reutilizar componente ya creados  la issue debe cumplir con los siguientes requerimientos:

- [x]  Implementar el componente    INFORMACIÓN DEL PLAN rol Planeación (imagen de referencia, guiarse con el documento en drive)

 
![image](https://user-images.githubusercontent.com/43799065/146570661-b6be5d96-cc0d-4577-a4d7-bbe09e4ea811.png)

- [x] Implementar el componente      REPORTE TRIMESTRAL y RESUMEN AVANCE POR TRIMESTRE  rol Planeación (imagen de referencia, guiarse con el documento en drive)

![image](https://user-images.githubusercontent.com/43799065/146570756-e3a85c25-7f3a-4627-98ac-03742b2ac58e.png)

- [x] Implementar la funcionalidad del botón REVISAR para la dirección hacia el componente AVANCE DEL INDICAROR  rol planeación 

- [x] Implementar el componente        AVANCE DEL INDICAROR  y   DESCRIPCIÓN CUALITATIVA TRIMESTRE  rol Planeación (imagen de referencia, guiarse con el documento en drive)

![image](https://user-images.githubusercontent.com/43799065/146570963-813cd1ed-55e9-422e-88ed-ea62eb6394bb.png)

- [x] Implementar funcionalidad boton de documentos 

- [x] Implementar el componente       EVIDENCIAS  rol Planeación (imagen de referencia, guiarse con el documento en drive)

![image](https://user-images.githubusercontent.com/43799065/146571054-4a0939f1-47f6-4000-b66d-042f5ae7e5c2.png)

- [x] Implementar el componente         OBSERVACIONES PLANEACIÓN rol Planeación (imagen de referencia, guiarse con el documento en drive)
![image](https://user-images.githubusercontent.com/43799065/146571168-d9fe37bc-8d1f-4cdf-98be-447942fa41b1.png)

**Comment by JoseAlejoGonza** [comment]
se da inicio a la issue

**Comment by JoseAlejoGonza** [comment]
se completó la issue implementando los mockups para el rol planeación en el cliente

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
