### ISSUE TITLE
Desarrollar la funcionalidad para el componente de seguimiento de planes de acción  rol unidad académico administrativa  tag de   PLANES DE ACCIÓN ANUAL,    INFORMACIÓN BASICA PLAN DE ACCIÓN y carga de la actividades en   INFORMACIÓN DEL PLAN

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#193]
Se debe desarrollar la funcionalidad para el componente de seguimiento de planes de acción  rol unidad académico administrativa en los  tags de   PLANES DE ACCIÓN ANUAL,    INFORMACIÓN BASICA PLAN DE ACCIÓN y carga de la actividades en   INFORMACIÓN DEL PLAN, la issue debe cumplir con los siguientes requerimientos, [mockup](https://drive.google.com/file/d/1wAthn9dD3RSdLTYMF9aAmT8o0Lsfkrb2/view?usp=sharing):

- [x] Desarrollar  la funcionalidad para el tag  SEGUIMIENTO PLANES DE ACCIÓN/   PLANES DE ACCIÓN ANUAL ( carga de la tabla) e inclusión del select de la unidad 

![image](https://user-images.githubusercontent.com/43799065/150557858-3f868d38-7468-4dd0-ba79-8e1f6b4f6075.png)

- [x] Desarrollar  la funcionalidad para el tag  SEGUIMIENTO PLANES DE ACCIÓN/   INFORMACIÓN BASICA PLAN DE ACCIÓN, carga información solicitada 
![image](https://user-images.githubusercontent.com/43799065/150558095-f1727040-ae40-439d-9195-3b9657e5afea.png)

- [x] Desarrollar  la funcionalidad para el tag    INFORMACIÓN DEL PLAN / ACTIVIDAD GENERAL carga del select e información de la actividad 
![image](https://user-images.githubusercontent.com/43799065/150558282-27032d80-3343-4ab1-8ade-9765e154a9f8.png)

**Comment by brayaned** [comment]
Se dió inicio a la issue el 27/01/2022.

**Comment by brayaned** [comment]
Se realizaron las funciones correspondientes en el cliente y mid para la carga de planes y actividades para la gestión del seguimiento.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
