### ISSUE TITLE
Crear el cliente base para el proyecto de planeación

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#2]
Se debe crear el cliente del proyecto de planeación a partir del cliente de [alternacia](https://github.com/udistrital/alternancia_cliente/tree/release/0.0.1), este se debe ajustar, eliminar y analizar el funcionamiento para la adaptación del sistema de planeación, la issue debe cumplir con los siguientes requerimientos:

- [x] Entender la arquitectura del cliente  
- [x] Clonar y acloplar el  cliente desarrollado en alternancia a nuestro cliente 
- [x] Ajustar readme segun los [lineamientos](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md) 
- [x] Realizar la limpieza de los componentes, y demás código que no sea necesario en nuestro cliente
- [x]  Ajustar la paleta de colores según los lineamientos  enviados al correo 
-

**Comment by ndmc98** [comment]
**Arquitectura del cliente**

Se analizó el funcionamiento del cliente de alternancia con el propósito de adaptarlo para el cliente del sistema de planeación. Del estudio del proyecto de alternancia se entendieron las siguientes características respecto de la arquitectura y el funcionamiento:

- Paquete _src_ que contiene el paquete _app_ con las _pages_ y los _components_; además contiene los _assets_ y _environments_. Así mismo tiene el _index.html_ que renderiza los componentes; el _main.ts_ y los estilos.
- Cada _page_ asocia el _html_ con el archivo _ts_. Son registrados en _page-module_ y _page-component_. 
- En _environments_ se asocian las apis que serán consumidas por el cliente.
- Dentro de _pages_ en el paquete _services_, se define el _requestManager.ts_ que gestiona todas las peticiones (define la estructura de cada una de las operaciones).

![image](https://user-images.githubusercontent.com/24207969/126728655-832609fc-6d65-4d77-a006-7f2cdf1ad270.png)

**Comment by ndmc98** [comment]
**Clonación, ajuste y README**

Se clonó y ajustó el cliente de [_alternancia_](https://github.com/udistrital/alternancia_cliente/tree/master) para ser subido en el proyecto del cliente de [_planeación_](https://github.com/udistrital/planeacion_cliente). De igual forma se ajustó el README según los [lineamientos](https://github.com/udistrital/lineamientos_oas) de la OAS.

![image](https://user-images.githubusercontent.com/24207969/126730626-65f11582-57b1-4d4d-8fc2-272637b77e17.png)

**Comment by ndmc98** [comment]
**Consideraciones del cliente**

- El logo aparece en el login y en el header, y eso hace parte del web component.
- En el identity server de wso2 se registra la url de la aplicación y se define el tipo de autenticación si será por wso2, Google o ambas. En pruebas están ambas (http://localhost:4200).
- La información que se trae del usuario de wso2 indica también qué rol tiene asignado. Otros clientes manejan algo llamado Angular Guard para trabajar con la limitación de las vistas de acuerdo al rol.

**Comment by ndmc98** [comment]
Se finaliza la tarea

**Comment by fabianbarreto02** [comment]
Se revisa la issue y se da por finalizada
