### ISSUE TITLE
Desarrollar funcionalidad de consultar en el modulo de construcción

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#20]
Desarrollar el componente y la funcionalidad para la consulta de los planes y proyectos en el modulo de construcción del sistema, esta funcionalidad debe permitir la visualización de los arboles para los planes y proyectos creados,  para esto se escoge cual es el plan/proyecto a visualizar en un select y mostrar todo el árbol definido, la issue debe cumplir con los siguientes requerimientos:

- [x]  Desarrollar el componente para la visualización ( reutilizar componentes ya creados)
- [x] Desarrollar funcionalidad para la carga de la información ya establecida en el api de planes_crud

**Comment by ndmc98** [comment]
Se da inicio a la tarea

**Comment by ndmc98** [comment]
Se desarrolla el componente para la visualización empleando la directiva asociada al componente _árbol_. El componente permite seleccionar el plan del cual se desea obtener la información desde API MID y API CRUD. El árbol trae la información para ser consultada:

![image](https://user-images.githubusercontent.com/24207969/130260311-302ee042-2647-472e-a650-a24257175572.png)

![image](https://user-images.githubusercontent.com/24207969/130260334-01d53985-c18e-4555-90de-93ac2cd5914f.png)

**Comment by ndmc98** [comment]
Se da por finalizada las tareas y la issue con el pull request.
