### ISSUE TITLE
Desarrollar la funcionalidad para el componente de seguimiento de planes de acción rol unidad académico administrativa tag de SEGUIMIENTO PLANES DE ACCIÓN y REPORTAR

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#200]
Se debe desarrollar la funcionalidad para el componente de seguimiento de planes de acción rol unidad académico administrativa en los tags de SEGUIMIENTO PLANES DE ACCIÓN y REPORTAR, la issue debe cumplir con los siguientes requerimientos, [mockup](https://drive.google.com/file/d/1Yhy7opR2Fjbtt62wk2I3TVc8H5zO-jkW/view?usp=sharing):

- [x] Ajustar el componente   INFORMACIÓN DEL PLAN con el campo para el segundo indicador y meta 

![image](https://user-images.githubusercontent.com/43799065/151278421-f592a28f-b110-4251-9c93-82721e51e19e.png)

- [x] Desarrollar la funcionalidad para el tag SEGUIMIENTO PLANES DE ACCIÓN/ SEGUIMIENTO PLANES DE ACCIÓN( carga de lineamiento, meta estratégica, estrategia, indicador asociado, meta y tareas).

![image](https://user-images.githubusercontent.com/43799065/151092746-6fc835b2-c965-4044-bb2d-29150f7adc35.png)

- [x] Desarrollar la funcionalidad para el componente   REPORTE TRIMESTRAL ACTIVIDAD X (nombre de la actividad, ojo se hace actividad por actividad), solo se debe cargar el trimestre que este activo para el reporte 

![image](https://user-images.githubusercontent.com/43799065/151093345-6eda6c51-832d-46ac-88a2-0696bb2fb702.png)

**Comment by brayaned** [comment]
Se dio inicio a la issue el 31/01/2022.

**Comment by brayaned** [comment]
Se desarrollaron las funciones para la respectiva carga de la informacion del plan y las diferentes actividades seleccionadas por el usuario. También se ajusto el cliente para que sea capaz de recibir uno o dos indicadores diferentes con sus respectivas metas.

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
