### ISSUE TITLE
Desarrollar la funcionalidad para el componente de seguimiento de planes de acción rol unidad académico administrativa tag de   REPORTE TRIMESTRE X y  DESCRIPCIÓN CUALITATIVA TRIMESTRE

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#201]
Se debe desarrollar la funcionalidad para el componente de seguimiento de planes de acción rol unidad académico administrativa en los tags de REPORTE TRIMESTRE X y  DESCRIPCIÓN CUALITATIVA TRIMESTRE la issue debe cumplir con los siguientes requerimientos, [mockup](https://drive.google.com/file/d/1Yhy7opR2Fjbtt62wk2I3TVc8H5zO-jkW/view?usp=sharing):

- [x] Desarrollar funcionalidad para almacenar el documento del campo evidencia ciñéndose al gestor documental, seguir la [documentación ](https://docs.google.com/document/d/1ETG2KtDpNXN8hTyjDIe-VkVJ9gGFqzaC/edit?usp=sharing&ouid=102492667183582276825&rtpof=true&sd=true)disponible  

![image](https://user-images.githubusercontent.com/43799065/151279963-f10640c8-8253-4b37-8fb2-2a761b8645ed.png)

- [x] Desarrollar la funcionalidad para la carga de información de los campos avance en el periodo, avance acumulado, producto, evidencia(documento almacenado), logros, dificultades y observaciones 
 
- [x] Desarrollar la funcionalidad para la edición de información de los campos avance en el periodo, avance acumulado, producto, evidencia(documento almacenado), logros, dificultades y observaciones

**Comment by brayaned** [comment]
Se dio incio a la issue el 3/02/2022.

**Comment by brayaned** [comment]
Se desarrollo la funcionalidad para la carga de diferentes documentos y el guardado y carga de toda la informacion de seguimiento.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
