### ISSUE TITLE
Desarrollar la funcionalidad para el componente de seguimiento de planes de acción rol unidad académico administrativa tag de RESUMEN AVANCE POR TRIMESTRE

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#202]
Se debe desarrollar la funcionalidad para el componente de seguimiento de planes de acción rol unidad académico administrativa en los tags de RESUMEN AVANCE POR TRIMESTRE, la issue debe cumplir con los siguientes requerimientos, [mockup](https://drive.google.com/file/d/1Yhy7opR2Fjbtt62wk2I3TVc8H5zO-jkW/view?usp=sharing):

- [x] Crear funcionalidad para almacenar la información de los campos avance en el periodo, avance acumulado, producto, evidencia, logros, dificultades y observaciones 

![image](https://user-images.githubusercontent.com/43799065/151279597-cc0ee158-3a89-4dd1-9d2c-dc1b6d017fed.png)

- [x] Desarrollar la funcionalidad para el calculo del avance Periodo para cuando exista una o dos indicadores según la formula. debe estar registrado  los avances del periodo individual 
![image](https://user-images.githubusercontent.com/43799065/151280940-5db0d5ec-101a-48f6-b0e7-ab697e5a4e2e.png)

- [x] Desarrollar el calculo del avance Acumulado para los cuatro trimestres según la formula
- [x] Desarrollar la funcionalidad para almacenar la información de avance 
- [x] Desarrollar la funcionalidad para cargar la información de avance
- [x] Desarrollar la funcionalidad para actualizar la información de avance

**Comment by brayaned** [comment]
Se dio inicio a la issue el 27/01/2022.

**Comment by JoseAlejoGonza** [comment]
se da inicio a la issue

**Comment by JoseAlejoGonza** [comment]
Se creó la funcionalidad para el avance acumulado

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
