### ISSUE TITLE
Desarrollar el componente Evaluación para los planes acción de funcionamiento 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#203]
Se debe desarrollar el componente para la Evaluación para los planes acción de funcionamiento, según el [mockup ](https://drive.google.com/file/d/1Yhy7opR2Fjbtt62wk2I3TVc8H5zO-jkW/view?usp=sharing)definido, la issue debe cumplir con los siguientes requerimientos:  

- [x] Desarrollar el componente según el mockup 
![image](https://user-images.githubusercontent.com/43799065/151463476-569b9bfe-98e2-487e-a9bb-1333f89c537e.png)

- [x] Realizar funcionalidad de suma general con datos simulados (json)

**Comment by JoseAlejoGonza** [comment]
se da inicio  la issue

**Comment by JoseAlejoGonza** [comment]
se crearon los mockups con la funcionalidad simulando datos desde un json

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
