### ISSUE TITLE
Desarrollar la funcionalidad para el componente de seguimiento de planes de acción rol Planeación tag de LISTADO PLANES DE ACCIÓN ANUAL  y SEGUIMIENTO PLANES DE ACCIÓN

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#208]
Se debe desarrollar la funcionalidad para el componente de seguimiento de planes de acción rol Planeación tag de LISTADO PLANES DE ACCIÓN ANUAL  y SEGUIMIENTO PLANES DE ACCIÓN, la issue debe cumplir con los siguientes requerimientos, [mockup](https://drive.google.com/file/d/1Yhy7opR2Fjbtt62wk2I3TVc8H5zO-jkW/view?usp=sharing):

- [x] Desarrollar en el componente un select con las vigencias en el sistema 

- [x] Desarrollar la funcionalidad para el tag LISTADO PLANES DE ACCIÓN ANUAL, cargar la información en la tabla con los planes de acción anual de la vigencia selecciona  
![image](https://user-images.githubusercontent.com/43799065/151683662-8723f2eb-e428-4268-912f-6368573176e2.png)

- [x] Desarrollar la funcionalidad para el tag SEGUIMIENTO PLANES DE ACCIÓN, cargar   INFORMACIÓN BASICA PLAN DE ACCIÓN y   LISTADO ACTIVIDADES.

![image](https://user-images.githubusercontent.com/43799065/151683718-6cc36bd3-a467-4b4b-817b-9ff6f5ef530c.png)

**Comment by brayaned** [comment]
Se da inicio a la issue.

**Comment by brayaned** [comment]
Se desarrollo la tabla de actividades para el  filtrado de planes por vigencia y la revisión de actividades generales para el rol de Planeación.

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
