### ISSUE TITLE
Hacer pruebas funcionales al modulo de construcción

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#21]
Se debe realizar prueba funcionales para el modulo de construcción, dentro estas pruebas se deben realizar la pruebas de los siguientes item:

- [x]  Creación de información del componente  definir Poryecto/Plan
- [x] Consulta del componente listar 
- [x] Creación de un plan en el componente de construir 
- [x] Consulta de información en el componente consultar 

Si se llega a encontrar un error durante el proceso de pruebas se debe realizar el ajuste y notificar sobre el hallazgo, si el error encontrado requiere un nivel de atención superior informar a líder técnico

**Comment by ndmc98** [comment]
Inicio y desarrollo de pruebas como usuario en las funcionalidades

**Comment by ndmc98** [comment]
Se valida la funcionalidad de _Creación de información del componente definir Proyecto/Plan_

Sin todos los campos requeridos no se habilita el registro:
![image](https://user-images.githubusercontent.com/24207969/130118138-7283e14d-5c73-4b21-9c6f-0287a180248e.png)

El componente indica cuando el registro de la información se ha efectuado:
![image](https://user-images.githubusercontent.com/24207969/130118264-64fda067-ef34-49d3-87e8-6be056fbf24b.png)

Tras aprobar el registro, se redirecciona a plan/listar-planes:
![image](https://user-images.githubusercontent.com/24207969/130118415-69e69186-8948-4cd6-864c-0df9950fb14b.png)

**Comment by ndmc98** [comment]
Se valida la funcionalidad de _Consulta del componente listar_

El componente listar carga los planes/proyectos con su nombre, descripción y estado. Permite además las opciones de editar (PUT de información) o Inactivar (PUT campo _activo_)
![image](https://user-images.githubusercontent.com/24207969/130118794-60e6e7ba-e4cc-4689-89f9-574c9b96c6a0.png)

El componente permite el método de paginación:
![image](https://user-images.githubusercontent.com/24207969/130119066-e2b4a8d6-791a-45de-8511-9b16a8edfe8e.png)

El componente permite la opción de filtrado o búsqueda:
![image](https://user-images.githubusercontent.com/24207969/130119157-b9d3b76e-835a-4526-abe5-5a7fceb4b404.png)

La opción de editar permite modificar nombre, descripción y activo:
![image](https://user-images.githubusercontent.com/24207969/130119280-e7b3a043-8b3d-4905-8b08-3a9b6fb8250c.png)

La actualización (PUT) recarga la lista con la modificación realizada:
![image](https://user-images.githubusercontent.com/24207969/130119399-e29fda82-4bd8-4687-afcb-9f222d63465a.png)

Inactivar un plan cambia campo de _true_ por _false_:
![image](https://user-images.githubusercontent.com/24207969/130119532-234a7262-a607-4b66-aff7-1961089554a7.png)
![image](https://user-images.githubusercontent.com/24207969/130119760-eda6a45a-bc9c-4e18-b650-8b2cc99f8047.png)

Si ya está _Inactivo_ se genera la advertencia:
![image](https://user-images.githubusercontent.com/24207969/130119920-34b8fa85-cb56-42fa-84b1-34d0a1b38e5f.png)

El cambio de _true_ por _Activo_ y _false_ por _Inactivo_ se realiza en el cliente

**Comment by ndmc98** [comment]
Se valida la funcionalidad de _Creación de un plan en el componente de construir_

El componente carga unicamente los planes activos:
![image](https://user-images.githubusercontent.com/24207969/130120558-fc7c7727-198a-45dc-8fc2-26345ddabba1.png)

Dependiendo si es tipo _Plan_ o _Proyecto_ se muestra la vista:
![image](https://user-images.githubusercontent.com/24207969/130120656-48a5bb93-6f0a-4dd4-8ffd-8f8be473db5e.png)

![image](https://user-images.githubusercontent.com/24207969/130120678-2c7e6317-e36e-43dc-9831-9b711862160a.png)

Cuando es _plan_ se realiza la construcción del árbol:
![image](https://user-images.githubusercontent.com/24207969/130120759-31fd001f-917e-4f33-ab88-ee71f1a579cb.png)

Cada nivel del árbol tiene las opciones de editar su información (PUT) o adicionar un nuevo nivel/hijo/subgrupo (POST):
![image](https://user-images.githubusercontent.com/24207969/130120945-70cab976-b28e-471a-be04-d229688865a1.png)

La opción de editar nos indica el nivel y los datos correspondientes que pueden ser modifcados:
![image](https://user-images.githubusercontent.com/24207969/130121017-49706864-04b5-44ef-8d0b-aaabc72045e9.png)

La modificación del nivel genera mensaje de confirmación y con ello la actualización del registro (se recarga el árbol desde el MID):
![image](https://user-images.githubusercontent.com/24207969/130121134-3c9b2688-6cc9-49d5-bdce-be087fa3cfef.png)

Para agregar un nuevo nivel se obtiene el dialogo con el respectivo número de nivel y las validaciones a los campos:
![image](https://user-images.githubusercontent.com/24207969/130121347-9155ec61-4bbf-411b-b15c-561368faa59c.png)
![image](https://user-images.githubusercontent.com/24207969/130121434-2a226cdd-26ca-40de-83b7-83a929fe1a9a.png)

Tras agregar el nuevo nivel (cualquiera n=1,2,3,....) se obtiene un mensaje confirmación del registro en la base de datos:
![image](https://user-images.githubusercontent.com/24207969/130121599-2d754bdd-965b-4262-9205-9c4c4f8960b6.png)

Se recarga entonces automaticamente el árbol actualizado:
![image](https://user-images.githubusercontent.com/24207969/130121673-1d80ecf0-f58e-4323-a54a-f242f6699884.png)

Cada vez que se cambia de plan, se carga su respectivo árbol o vista. Este problema se encontró en el desarrollo de las pruebas y fue resuelta a través del control del ID que se tiene cuando se selecciona un plan (estableciendo como el _valor actual_).

Los valores del campo _activo_ deben regresar como _Activo_ o _Inactivo_ desde el MID. Funcionalidad pendiente. 

Se tenía el error de la carga de la información de un plan que aún no tiene árbol (return NULL desde MID); esto es que no se tiene data para la creación de la tabla-arbol. Desde el cliente se entró a manejar el error identificando cuando viene vacío el árbol desde MID y cancelando la creación de la tabla-árbol; entonces se genera un mensaje de advertencia que indica que no hay datos registrados. 
![image](https://user-images.githubusercontent.com/24207969/130122624-83287a19-882a-4ea0-833f-ef6a3d576027.png)

**Comment by ndmc98** [comment]
Se valida la funcionalidad de _Consulta de información en el componente consultar_

![image](https://user-images.githubusercontent.com/24207969/130260633-45c9bf23-48c8-4ef6-8b67-fb5e5b110f7f.png)

No se encuentran inconvenientes mas allá de los hablados en las sesiones diarias en las que se espera el cambio de los campos _true_ y _false_ por _activo_ e _inactivo_ desde el MID. Por su parte lo relacionado con proyectos no se valida ya que no se cuenta aún con un flujo para la gestion de documentos.

**Comment by ndmc98** [comment]
Se encuentran como modificaciones próximas a los componentes de construcción:

- Desactivar el árbol por completo y considerar la validación para desactivar dependiendo si es Plan o Proyecto.
- No recargar el componente de listar tras una modificación sino actualizar la tabla (en LISTAR).
- En el componente de Construcción no permitir la creación de un nuevo nivel si el actual es _false o inactivo_.

**Comment by ndmc98** [comment]
Se dan por finalizadas las tareas y la issue con los comentarios de las modificaciones, errores encontrados o cambios pendientes.
