### ISSUE TITLE
Desarrollar la funcionalidad para el componente de seguimiento de planes de acción rol Planeación tag de   OBSERVACIONES PLANEACIÓN

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#210]
Se debe desarrollar la funcionalidad para el componente de seguimiento de planes de acción rol Planeación tag de  OBSERVACIONES PLANEACIÓN, la issue debe cumplir con los siguientes requerimientos, [mockup](https://drive.google.com/file/d/1Yhy7opR2Fjbtt62wk2I3TVc8H5zO-jkW/view?usp=sharing):

- [x] Desarrollar funcional para el tag de observaciones, almacenar comentarios y quien da la respuesta y almacenar los comentarios 
![image](https://user-images.githubusercontent.com/43799065/151684501-725eb749-f977-4230-a638-a6fb54af5be4.png)

- [x]  Desarrollar funcional ADJUNTAR SOPORTE ciñéndose al gestor [documental  ](https://docs.google.com/document/d/1ETG2KtDpNXN8hTyjDIe-VkVJ9gGFqzaC/edit)

![image](https://user-images.githubusercontent.com/43799065/151684755-4adb92f6-0f29-49db-ab39-b8a65099d0a6.png)

**Comment by brayaned** [comment]
Se dio inicio a la issue el 01/03/2022.

**Comment by brayaned** [comment]
Flujo de documentos realizado para que la oficina de planeación pueda adjuntar evidencias en cada una de las observaciones que realicen por indicador.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
