### ISSUE TITLE
Desarrollar la funcionalidad para el componente  Evaluación Planes de Acción Anuales

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#211]
Se debe desarrollar la funcionalidad para el componente de Evaluación Planes de Acción Anuales rol Planeación tag de Evaluación, la issue debe cumplir con los siguientes requerimientos, [mockup](https://drive.google.com/file/d/1Yhy7opR2Fjbtt62wk2I3TVc8H5zO-jkW/view?usp=sharing):

- [x] Desarrollar la funcionalidad para la carga del componente de evaluación con la información relacionada 

![image](https://user-images.githubusercontent.com/43799065/151685080-c8324dd4-ede6-436b-8fa0-577891aa8f2b.png)

**Comment by JoseAlejoGonza** [comment]
se da inicio a la issue

**Comment by JoseAlejoGonza** [comment]
se crearon los mockups y funcioanlidad simulada con datos desde un json

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
