### ISSUE TITLE
Bloquear la Identificación de contratistas, actividades y docentes y ocultar identificación para unidades administrativas en el componente de formulación de plan de acción 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#221]
Se debe desarrollar la función para bloquear Identificación de contratistas, actividades y docentes una vez el estado de un plan pase por el estado aval y ocultar identificación para unidades administrativas en el componente de formulación de plan de acción, la issue debe cumplir con los siguientes requerimientos:

- [x]  Crear  función para bloquear Identificación de contratistas, actividades y docentes una vez el estado de un plan pase por el estado pre aval 
- [x] Ocultar identificación docentes  para unidades administrativas en el componente de formulación de plan de acción

**Comment by brayaned** [comment]
Se da inicio a la issue.

**Comment by brayaned** [comment]
Se actualizó la funcionalidad para el bloqueo de la identificación de contratistas y recursos. También se  modifico la petición get_unidades en el mid para traer el tipo de unidad y así poder realizar el filtro de las unidades académico-administrativas para ocultar el componente de identificación docente para las unidades que no lo necesitan.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
