### ISSUE TITLE
Desarrollar Funcionalidad para generar el excel a partir de la consulta de Planes de acción en estado de pre aval 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#223]
Se debe desarrollar Funcionalidad para generar el excel a partir de la consulta de Planes de acción en estado de pre aval con la información codigo(rubro), concepto(nombre del rubro), Valor (ingresado por la unidad) y que este desagradado por unidad para una vigencia particular, la issue debe cumplir con los siguientes requerimientos:

- [ ] Desarrollar la funcionalidad para la generación del excel, la función debe recibir la consulta y generar un documento en excel organizado

**Comment by fabianbarreto02** [comment]
https://github.com/udistrital/sga_mid/blob/develop/controllers/generar_recibo.go

**Comment by JoseAlejoGonza** [comment]
se da inicio a la issue

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
