### ISSUE TITLE
Desarrollar funcionalidad para consulta para el componente tabla con desagregado necesario 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#224]
Se debe desarrollar la funcionalidad para consulta para el componente tabla con desagregado necesario este es  codigo(rubro), concepto(nombre del rubro), Valor (ingresado por la unidad) y que este desagradado por unidad para una vigencia particular, también consultar por el estado del plan de formulación y el tipo de plan, la issue debe cumplir con los siguientes requerimientos:

- [x] La función debe recibir como parámetros de entrada ( vigencia, tipo plan y el estado del plan )

- [x] Desarrollar la funcionalidad con los requerimientos mencionados 
- [x] Datos a entregar la función codigo(rubro), concepto(nombre del rubro), Valor (ingresado por la unidad), nombre de la unidad y Descripción del bien y/o servicio

**Comment by JoseAlejoGonza** [comment]
se da inicio a la issue

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
