### ISSUE TITLE
Desarrollar funcionalidad para ROL UNIDAD ACADÉMICO ADMINISTRATIVA para la visualización de observaciones por parte de planeación 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#225]
Se debe desarrollar funcionalidad para ROL UNIDAD ACADÉMICO ADMINISTRATIVA para la visualización de observaciones por parte de planeación, este tag se sebe observar sin edición y solo se debe poder observar en un plan que previamente ha recibido una observación por parte de la oficina de planeación, la issue  debe cumplir con los siguientes requerimientos:

- [x]  Ajustar componente para ROL UNIDAD ACADÉMICO ADMINISTRATIVA para que se visualice la observación cuando se exista alguna estado Con observación  
- [x] Ajustar solo visualización de la observación sin permitir edición de la observación el resto del componte se podrá editar

**Comment by brayaned** [comment]
Se da inicio a la issue.

**Comment by brayaned** [comment]
Se realizaron las funcionalidades necesarias para el flujo de observaciones entre la oficina de planeacion y todas las unidades en el componenete de seguimiento.
