### ISSUE TITLE
Desarrollar flujo de estado para el seguimiento de los planes de planes de acción de funcionamiento 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#226]
se debe desarrollar flujo de estado para el seguimiento de los planes de planes de acción de funcionamiento, ceñirse al flujo del diagrama suministrado, la issue debe cumplir con los siguientes requerimientos:  

- [x] Se deje ajustar el flujo del componente de seguimiento siguiendo el flujo de estados 

![image](https://user-images.githubusercontent.com/43799065/155130088-60b58aba-7365-47d8-8e27-70f715b437a6.png)

**Comment by brayaned** [comment]
Se dió inicio a la issue el 09/03/2022.

**Comment by brayaned** [comment]
Se desarrollo el flujo completo de observaciones para que los usuarios puedan realizar ajustes según las observaciones a el seguimiento de cada actividad.
