### ISSUE TITLE
Ajustar Menú según el mockup establecido por los usuarios, Parte uno

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#228]
Se debe realizar el Ajuste del menú según el [mockup ](https://drive.google.com/file/d/1theRb4PzcZo2bz6TsBWEDr43phgd6dsX/view?usp=sharing)establecido por los usuarios, la issue debe cumplir con los siguientes requerimientos:

- [x] Incluir el menú " Proyecto Universitario Institucional" / "Consultar PUI", desarrollar el [mockup](https://drive.google.com/file/d/1VToyzYe76D_RGzKYISBPNBPh1CDzEtK_/view?usp=sharing) para el modulo de construcción y el de consultar sin funcionalidad 

- [x]  Incluir el menú " Plan Estratégico de Desarrollo" / "Consultar PED", dentro de este menú debe implementar el componente Construcción/listar incluir botón acción (lupa) que redirecciona al componente de consultar  con el plan previamente seleccionado, solo se deben cargar los planes que tengan el tipo   Plan Estratégico de Desarrollo(crear tipo).

- [x]  Incluir el menú " Plan Estratégico de Desarrollo" / "Seguimiento PED", dentro de este menú debe implementar un componente modal que informe que este modulo en construcción 

- [x]  Incluir el menú " Plan Estratégico de Desarrollo" / "Evaluación PED", dentro de este menú debe implementar un componente modal que informe que este modulo en construcción 

- [x]  Incluir el menú " Plan Maestro de Espacios Educativos" / "Consultar PMEE",  dentro de este menú debe implementar un componente modal que informe que este modulo en construcción .

- [x]  Incluir el menú " Plan Maestro de Espacios Educativos" / "Seguimiento PMEE", dentro de este menú debe implementar un componente modal que informe que este modulo en construcción 

- [x]  Incluir el menú " Plan Maestro de Espacios Educativos" / "Evaluación PMEE", dentro de este menú debe implementar un componente modal que informe que este modulo en construcción

**Comment by JoseAlejoGonza** [comment]
se da inicio a la issue

**Comment by JoseAlejoGonza** [comment]
se realizó el ajuste del menú lateral conforme lo describe la issue

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
