### ISSUE TITLE
Ajustar Menú según el mockup establecido por los usuarios, Parte Dos

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#229]
Se debe realizar el Ajuste del menú según el [mockup ](https://drive.google.com/file/d/1theRb4PzcZo2bz6TsBWEDr43phgd6dsX/view?usp=sharing)establecido por los usuarios, la issue debe cumplir con los siguientes requerimientos:

- [x] Incluir el menú " Plan Indicativo" / "Consultar PI", dentro de este menú debe implementar el componente Construcción/listar incluir botón acción (lupa) que redirecciona al componente de consultar  con el plan previamente seleccionado, solo se deben cargar los planes que tengan el tipo   Plan Indicativo (crear tipo).

- [x]  Incluir el menú " Plan Indicativo" / "Seguimiento PI", dentro de este menú debe implementar un componente modal que informe que este modulo en construcción 

- [x]  Incluir el menú " Plan Indicativo" / "Evaluación PI", dentro de este menú debe implementar un componente modal que informe que este modulo en construcción 

- [x] Incluir el menú "Plan Operativo Anual" / "Consulta POA", ddentro de este menú debe implementar un componente modal que informe que este modulo en construcción 

- [x]  Incluir el menú " Plan Operativo Anual" / "Evaluación POA", dentro de este menú debe implementar un componente modal que informe que este modulo en construcción 

- [x]  Incluir el menú " Banco de Proyectos UD" / "Proyectos de Inversión MACRO"/ "Consulta Proyectos Inversion inscritos.", dentro de este menú debe implementar un componente modal que informe que este modulo en construcción 

- [x]  Incluir el menú " Banco de Proyectos UD" / "Proyectos de Inversión MACRO"/ "Formulacion  Proyectos de Inversión (Ajuste)", dentro de este menú debe implementar un componente modal que informe que este modulo en construcción 

- [x]  Incluir el menú " Banco de Proyectos UD" / "Proyectos de Inversión MACRO"/ "Seguimiento Proyectos de Inversión", dentro de este menú debe implementar un componente modal que informe que este modulo en construcción 

- [x]  Incluir el menú " Banco de Proyectos UD" / "Proyectos de Inversión MACRO"/ "Evaluación proyectos de inversión", dentro de este menú debe implementar un componente modal que informe que este modulo en construcción 

- [x]  Incluir el menú " Banco de Proyectos UD" / "Proyectos de Inversión MACRO"/ "Generación de reportes", dentro de este menú debe implementar un componente modal que informe que este modulo en construcción 

- [x]  Incluir el menú " Banco de Proyectos UD" / "Banco de Iniciativas de inversión Institucionales"/ "Consulta Proyectos de Inversión Inscitos", dentro de este menú debe implementar un componente modal que informe que este modulo en construcción 

- [x]  Incluir el menú " Banco de Proyectos UD" / "Banco de Iniciativas de inversión Institucionales"/ "Formulación SubProyecto de Inversión   (formulación previa - formulación previa)", dentro de este menú debe implementar un componente modal que informe que este modulo en construcción

- [x]  Incluir el menú " Banco de Proyectos UD" / "Banco de Iniciativas de inversión Institucionales"/ "Seguimiento SubProyecto de Inversión", dentro de este menú debe implementar un componente modal que informe que este modulo en construcción

- [x]  Incluir el menú " Banco de Proyectos UD" / "Banco de Iniciativas de inversión Institucionales"/ "Evaluación SubProyecto de Inversión", dentro de este menú debe implementar un componente modal que informe que este modulo en construcción

- [x]  Incluir el menú " Banco de Proyectos UD" / "Banco de Iniciativas de inversión Institucionales"/ "Generación de reportes", dentro de este menú debe implementar un componente modal que informe que este modulo en construcción

- [x]  Incluir el menú " Programación Presupuestal" / "Reportes de necesidades de funcionamiento", dentro de este menú debe implementar un componente modal que informe que este modulo en construcción

- [x]  Incluir el menú " Programación Presupuestal" / "Reportes de necesidades de inversión", dentro de este menú debe implementar un componente modal que informe que este modulo en construcción

**Comment by JoseAlejoGonza** [comment]
se da inicio a la issue

**Comment by JoseAlejoGonza** [comment]
se realizó el ajuste del menú lateral conforme lo describe la issue
