### ISSUE TITLE
Realizar ajustes de bugs y experiencia de usuario encontradas por el analista de requerimientos  

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#237]
Se debe realizar los ajustes de forma, bug y experiencia de usuario encontradas por el analista de requerimientos, la issue debe cumplir con los siguientes requerimientos:

- [x] Ajustar en las tablas de identificación (recursos y contratistas por que no se carga el nombre de la actividad en la columna de Actividades

![image](https://user-images.githubusercontent.com/43799065/153527187-41dd0424-dd44-4556-bf1a-c06639cd12c6.png)

- [x] Quitar el buscador del componente Construcción/ construir y Construcción/ consultar no tiene funcionalidad

 
![image](https://user-images.githubusercontent.com/43799065/153527366-7b7a70b3-3d35-49df-9807-62589a389301.png)

- [x] Cambiar nombre del campo ACTIVO de las tablas a Estado 

![image](https://user-images.githubusercontent.com/43799065/153527474-1d2d7b12-38ea-4d95-9c2a-75ce2a33e1bb.png)

- [x] Ajustar para en el componente de construcción de planes se puede definir un campo resumen a un primer nivel por ejemplo actividad

- [x] Para el rol de planeación se debe bloquear el botón de agregar actividades o inhabilitarlas, junto a la edición de la armonización con el PED
- [x] Revisión para que que el componente de armonización con el rol de planeación se abra con las opciones seleccionas se muestres o solo muestre la selección definida 
- [x] Incluir un mensaje para el rol de planeación antes de la tabla de resumen infamando que para revisar las actividades se debe dar click en el botón editar (lapiz)
- [x] Ampliar las etiquetas para la identificación del estado del plan 
- [x] Ajustar la no visualización de los parámetros de niveles que cuenten con parámetros en la edición de un nivel en el modulo de construcción

**Comment by brayaned** [comment]
Se da inicio a la issue.

**Comment by brayaned** [comment]
Se realizaron todos los ajustes correspondientes para solucionar los errores e inconsistencias encontradas.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
