### ISSUE TITLE
Creación de la función de consulta del plan de acción anual de todas las unidades por una vigencia particular, un estado particular  y tipo de plan 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#240]
Se debe realizar la creación de la función de consulta del plan de acción anual de todas las unidades por una vigencia particular, un estado particular del plan y un tipo de plan, la issue debe cumplir con los siguientes requerimientos;

- [x] La función debe recibir como parámetros de entradas los siguientes requisito: Vigencia, estado del plan, tipo de plan, si es global (todas las unidades) o solo una unidad.
- [x] La función debe devolver la siguiente información:

![image](https://user-images.githubusercontent.com/43799065/153616329-08ee4eb9-d662-492a-9947-354422caf3d6.png)

- [x]  Información general de la consulta (vigencia, tipo de plan y estado de los planes)

- [x] Información por unidad y actividad por actividad  (un objeto json por unidad si aplica consulta global o por unidad): Plan Estratégico de Desarrollo Armonizado( lineamiento, meta y estrategia),  Numero de la actividad, Ponderación de la actividad, Período de ejecución, Actividad, tareas, Indicadores( Nombre, formula y meta). 

- [x] Información por unidad y actividad por actividad  (un objeto json por unidad si aplica consulta global o por unidad): Plan Estratégico de Desarrollo Armonizado( lineamiento, meta y estrategia),  Numero de la actividad, Ponderación de la actividad, Período de ejecución, Actividad, tareas, Indicadores( Nombre, formula y meta), Avance actividad hasta el ultimo periodo registrado y avance acumulado

**Comment by JoseAlejoGonza** [comment]
se da inicio a la issue

**Comment by JoseAlejoGonza** [comment]
Se creó la función para consultar el plan de acción anual para una unidad particular y para todas las unidades

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
