### ISSUE TITLE
Configuración del servicio de consulta de menús según rol y api de configuraciones

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#247]
Se debe desarrollar la configuración del servicio de consulta de menús según rol y api de configuraciones, para esto se debe ajustar el flujo del cliente, una vez consultado los roles de los usuarios con el servicio de autenticacion_mid se debe realizar la consulta al servicio de configuraciones_crud disponible en https://autenticacion.portaloas.udistrital.edu.co/apioas/configuracion_crud_api/v1/menu_opcion_padre/ArbolMenus/JEFE_DEPENDENCIA/PLANEACION función GET, una vez consultado ajustar la estructura del json y implementar el menú en el archivo main, la issue debe cumplir con los siguientes requerimientos:

- [x] Desarrollar la funcionalidad de la carga de los menus con el flujo comentado

**Comment by brayaned** [comment]
Se da inicio a la issue.

**Comment by fabianbarreto02** [comment]
se da pro finalizado la issue
