### ISSUE TITLE
Inclusión de etiquetas  informativas en los módulos de construcción y formulación de plan de acción 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#248]
Se debe realizar la inclusión de etiquetas  informativas en los módulos de construcción y formulación de plan de acción, junto a sus sub módulos se debe tener presente  la documentación de las etiquetas, la issue debe cumplir con los siguientes requerimientos:

- [x] Incluir etiquetas y mensajes para el modulo de construcción de planes https://docs.google.com/document/d/1X8CUsB43dD4WhYqKElGfuTjU-hnRY4Ep/edit?usp=sharing&ouid=102492667183582276825&rtpof=true&sd=true
- [x] Incluir etiquetas y mensajes para el modulo de formulación de planes https://docs.google.com/document/d/1JYhRGXe-zJydk9N5myLB8GdIrUIU-Jgb/edit?usp=sharing&ouid=102492667183582276825&rtpof=true&sd=true

**Comment by JoseAlejoGonza** [comment]
se da inicio a la issue

**Comment by JoseAlejoGonza** [comment]
Se crearon las etiquetas de los modulos de formulacion y construccion

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
