### ISSUE TITLE
Crear modelo de datos para el manejo de los planes requeridos por parte de la oficina de planeación

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#3]
Se debe crear un modelo que logre contener los diferentes planes ( proyecto universitario institucional,  plan maestro de espacios educativos, plan estratégico de desarrollo, plan operativo general, Plan indicativo y otro plan que surgiera) , para este diseño se surgiere tener como guía el modelo  de [catalogo_elementos_crud](https://drive.google.com/drive/u/2/folders/1LkLHwuF-FKOyuMEMs0DjMdIUH-YXDJnY), la issue debe cumplir con los siguientes requerimientos:

- [x] Se debe tener presente los [lineamiento ](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/estandar.md)para la creación de la propuesta del modelo 
- [x] Realizar la propuesta teniendo presente que un plan puede tener diferentes niveles jerárquico que se relacionen entre si ( Lineamientos, metas, Estrategias, entre otros).
- [x]  Planear que el modelo pueda relacionar diferentes armonizaciones entre los planes y proyectos ( Plan estratégico desarrollo y Plan indicativo)

**Comment by brayaned** [comment]
Se inicia la tarea empezando a diseñar el modelo de datos para diferentes tipos de planes, para este diseño se utiliza la herramienta pgmodeler.

**Comment by brayaned** [comment]
Para la realización del modelo de datos se tienen dos modelos de datos existentes, los cuales son catalogo y terceros. Siguiendo los lineamientos de la OAS se obtiene el modelo de datos relacional para el manejo de planes del sistema.
![modelo_datos_final](https://user-images.githubusercontent.com/30885597/127684618-8d6c7822-bd28-4f46-b748-d8e2d0bab5f1.png)

**Comment by brayaned** [comment]
En la reunión de aprobación del modelo de datos relacional por parte de los dba y arquitectos de la oficina, se propone la idea de utilizar un modelo de datos no relacional. Debido a esto se empieza a estudiar la posibilidad de trabajar bajo este tipo de bases de datos no relacionales utilizando la herramienta Mongodb.

**Comment by fabianbarreto02** [comment]
Documentación de modelos https://drive.google.com/drive/u/0/folders/1hOSsq3PifFbPsYFLiQjvjRqQbVnPRuGw

**Comment by brayaned** [comment]
Se toma la decisión de realizar el modelo de datos en bases de datos no relacionales. Para esto se utilizara la herramienta MongoDb. Debido a esto se adapta el modelo para bases de datos no relacionales. Se obtiene el siguiente resultado que es aprobado por los dba y arquitectos de la OAS.
![Captura de pantalla de 2021-08-08 19-49-51](https://user-images.githubusercontent.com/30885597/128651134-71919b62-0d19-4a78-a7ca-7f1f8c010ec3.png)

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
