### ISSUE TITLE
Ajustar el flujo y los componentes del modulo de construcción con los nuevos requerimientos 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#300]
Se debe Ajustar el flujo y los componentes del modulo de construcción con los nuevos requerimientos, la issue debe cumplir con los siguientes requerimientos:

- [ ] Unificar los componentes de listar y consultar del modulo actual de construcción con los siguientes requerimiento, incluir un botón de acción de consulta en la tabla de listar (lupa), en la tabla  incluir la información del tipo de plan, la tabla debe mostrar todos los planes, quitar filter.
![image](https://user-images.githubusercontent.com/43799065/159057505-3d8db8f2-f7b9-4112-a6a3-720864855522.png)

- [ ] al seleccionar la lupa se debe redireccionar al componente de consulta actual con el select bloqueado y cargado con el plan previamente seleccionado, incluir un botón para poder devolverse al listado de todos los planes

![image](https://user-images.githubusercontent.com/43799065/159057804-ab4890ac-33b1-43df-a6e9-cf37a97ea5d1.png)

- [ ] El nuevo menú debe llamarse  Consultar Planes / Proyectos  (Listar +consultar)
- [ ] Unificar en un nuevo menú llamado Construir Plan / Proyecto (Definir + construir) el componente de listar con todos los planes y un nuevo botón de acción de editar que al ser seleccionado se lleve al módulo de construcción actual con plan seleccionado. incluir un botón nuevo para devolverse a la tabla general 
- [ ] Incluir un botón en la parte de abajo de la tabla  llamado "Definir plan /proyecto" que al ser seleccionado muestre en un modal el componente de definir actual, una vez definido el plan o proyecto se notifica con un modal y devolverse al listado inicial actualizado con el nuevo plan

**Comment by fabianbarreto02** [comment]
![Sin título](https://user-images.githubusercontent.com/43799065/159059044-c30bbad6-2adb-417f-b0f4-31d0619a920f.png)

**Comment by JoseAlejoGonza** [comment]
se da inicio a la issue

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
