### ISSUE TITLE
Ajustes componente de formulación segun los hallazgos por el usuario parte dos 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#301]
Se debe realizar los Ajustes componente de formulación según los hallazgos por el usuario, la issue deb cumplir con los siguientes requerimientos: 

- [x] Cambiar el nombre del componente definir por "Definir Plan/ Proyecto" en el componente definir 
![image](https://user-images.githubusercontent.com/43799065/159010982-219e3ea2-adbf-48d1-8821-ee8880abeb78.png)

- [x] Cambiar el nombre del label formato por "Establecer como plantilla" en el componente de definir 
![image](https://user-images.githubusercontent.com/43799065/159010488-2e8cb197-e487-4284-b60d-932869eebbbf.png)

- [x] Cambiar el nombre del componente definir por "Construcción Plan/ Proyecto" en el componente construir 
![image](https://user-images.githubusercontent.com/43799065/159011467-e3747149-1b44-4d66-b66a-a0419e33c71d.png)

- [x] Revisar si es posible organizar los niveles y subniveles en el arbol de construcción con botones de acción o si no es posible dejar en el ultimo index del nivel los hijos o niveles inactivados 
- [x] Ajustar la función de activación de hijos de un nivel por demanda (misma función de desactivar un padre) 
- [x] En el componente de identificación de contratista se debe incluir un porcentaje de incremento general que afectaría los campos unitarios y valor total sin incremento y con incremento (valor unitario y valor total)

**Comment by brayaned** [comment]
Se dió inicio a la issue el 23/03/2022.

**Comment by brayaned** [comment]
Se desarrollaron los ajustes necesarios segun los hallazgos encontrados por el usuario.

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
