### ISSUE TITLE
Desarrollo de función para carga de automática de la unidad para el rol de JEFE_DEPENCIA segun lo definido del api terceros 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#306]
Se debe desarrollo de función para carga de automática de la unidad para el rol de JEFE_DEPENCIA según lo definido del api terceros, para cumplir con la issue se debe desarrollar con los siguientes requerimientos:

- [x] Realizar el registo de la información de prueba en el api de tercero (tabla vinculación) para las pruebas
- [x] Desarrollar función a nivel del MID para la consulta  de la vinculación del tercero que ingresa al sistema por medio de la cedula registrada en el servicio de userrol, una vez identificado se debe devolver la dependencia del tercero
- [x] Implementar la funcionalidad para el rol de JEFE_DEPENCIA en el cliente se debe seleccionar de forma automática en los módulos de formulación y seguimiento y bloquear el select, para el rol PLANEACION no aplica la implementación

**Comment by brayaned** [comment]
Se da inicio a la issue.

**Comment by brayaned** [comment]
Se realizaron las funcionalidades necesarias en el cliente y en el mid para conocer la vinculación de los usuarios loggeados.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
