### ISSUE TITLE
Ajustar el color de card de todo el sistema para que no sea totalmente blanca 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#307]
Se debe ajustar el color de card de todo el sistema para que no sea totalmente blanca, la issue debe cumplir con los siguientes requerimientos:

- [x]  Ajustar todas la card mediante estilos ccs para que el fono no sea blanco puro si no una paleta un poco mas oscura

**Comment by brayaned** [comment]
Se realizaron los ajustes necesarios en los css correspondientes para el cambio de color de las cards.

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
