### ISSUE TITLE
Ajuste componente recursos docente con los nuevos requerimientos definidos parte uno

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#320]
Se debe realizar los ajustes a los componente del sub modulo de recursos docentes con los nuevos requerimientos definidos por el equipo de planeación la issue debe cumplir con los siguientes requerimientos:

- [x] Desarrollar los componentes Administración de valores pregrado( Recurso horas fijas  y Recurso horas variable) y Administración de valores posgrado ( Recurso horas variable ) teniendo en cuenta el [mockup ](https://drive.google.com/file/d/1_zPv5mBxe_QTRGehmXK5cOIa6rBVSM5_/view?usp=sharing)

- [x] Desarrollar los flujos basicos del componente, botones, select, validación de campos, color de la sección e identificación por color de las filas

**Comment by brayaned** [comment]
Se dió inicio a la issue el 19/04/2022.

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
