### ISSUE TITLE
Revisión y ajuste para las campos nuevos de formulación (Clasificación Unidad de medida, Tendencias del indicdor -OAPC-, Criterio del indicador -OAPC-

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#336]
Se debe realizar la Revisión y ajuste para las campos nuevos de formulación (Clasificación Unidad de medida, Tendencias del indicdor -OAPC-, Criterio del indicador -OAPC- segun el [mockup ](https://drive.google.com/file/d/1_zPv5mBxe_QTRGehmXK5cOIa6rBVSM5_/view?usp=sharing)hoja de formulación y construcción, la issue debe cumplir con lo siguientes requerimientos:

- [x] Ajustar el formato del plan de acción para formular un nuevo plan con los campos mencionado 
- [x] Formular un plan de acción y revisar si el campo de observación funciona con el flujo de observaciones de la formulación

**Comment by fabianbarreto02** [comment]
![image](https://user-images.githubusercontent.com/43799065/166006653-feb8efad-64ca-46be-bb17-a7dc49dd4ce5.png)

**Comment by fabianbarreto02** [comment]
![image](https://user-images.githubusercontent.com/43799065/166006677-5bc6703f-86cd-4b7a-94bc-345dfb2a6b66.png)

**Comment by fabianbarreto02** [comment]
![image](https://user-images.githubusercontent.com/43799065/166006709-9da9fb82-e958-46c1-b827-e1c383860e90.png)

**Comment by brayaned** [comment]
Se realizo la creación de los nuevos campos y la formulación del plan para verificar el funcionamientos de los nuevos campos select. No se presentaron errores.
