### ISSUE TITLE
Ajustar el reporte del modulo de formulación para una unidad e inclusión del reporte de  Necesidades presupuestales - Unidad Académica o Administrativa

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#340]
Se debe realizar el ajuste del reporte del modulo de formulación para una unidad e inclusión del reporte de  Necesidades presupuestales - Unidad Académica o Administrativa, la issue debe cumplir con los siguientes requerimientos: 

- [x] Incluir en el reporte ya desarrollado para los planeas anuales los campos Clasificación Unidad de medida, Tendencia del Indicador

- [x] OAPC -, Criterio del indicador OAPC  , incluir el reporte de la armonización del plan indicativo, tener presente el desarrollo del PED

- [x]  Desarrollar en el mismo reporte en una nueva hoja el reporte Necesidades presupuestales - Unidad Académica o Administrativa segun el excel dado, el cual contiene Identificación de recursos, Identificación de contratistas y el resumen de Identificación recurso docente 

![image](https://user-images.githubusercontent.com/43799065/167158445-3a215586-9d81-40ab-9d97-9b5511917311.png)

**Comment by fabianbarreto02** [comment]
[Reporte.xlsx](https://github.com/udistrital/planeacion_cliente/files/8641599/Reporte.xlsx)

**Comment by fabianbarreto02** [comment]
https://pkg.go.dev/github.com/360entsecgroup-skylar/excelize

**Comment by fabianbarreto02** [comment]
http://pruebasapi2.intranetoas.udistrital.edu.co:8524/v1/reportes/plan_anual

**Comment by fabianbarreto02** [comment]
{
        "tipo_plan_id" : "61639b8c1634adf976ed4b4c",
        "vigencia" : "25",
        "estado_plan_id" : "6153355601c7a2365b2fb2a1",
        "unidad_id" : ""
}

**Comment by fabianbarreto02** [comment]
https://docs.google.com/spreadsheets/d/1QOHO36AjKG3PftW2DYz7UsXP22Sr50zW/edit#gid=481186137

**Comment by brayaned** [comment]
Se realizaron los ajustes necesarios con la nueva armonización con el Plan Indicativo y se consultan las identificaciones para incluirlas en el reporte de plan anual por unidad.

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
