### ISSUE TITLE
Ajustar el calculo de desagregado para los campos de pensión y salud con los aportes que realiza la universidad no el docente 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#347]
Se debe realizar el ajustar el calculo de desagregado para los campos de pensión y salud con los aportes que realiza la universidad no el docente, la issue  debe cumplir con los siguiente requerimientos:

- [x] Ajustar la funcionalidad del desagregado para que los campos de las tablas salud y pensión realice el calculo con los aportes realizado por la universidad y no por el docente 

![image](https://user-images.githubusercontent.com/43799065/168202928-18a0f5ff-44e7-4610-a1a7-3c7f8ce65155.png)

**Comment by brayaned** [comment]
Se realizaron los ajustes necesarios para calcular el valor pagado por la universidad por cada docente agregado a la identificación.

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
