### ISSUE TITLE
Ajustar el reporte de plan anual general para unificar las hojas de cada unidad en una sola hoja con los encabezados de los nombres de la unidad 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#348]
Se debe relaizar el ajuste del reporte de plan anual general para unificar las hojas de cada unidad en una sola hoja con los encabezados de los nombres de la unidad, la issue debe cumplir con los siguientes requerimientos:

- [x] Ajustar el reporte del plan anual general para unificar todas las unidades en una sola hoja, teniendo presente la cantidad de filas y el encabezado definido 
![image](https://user-images.githubusercontent.com/43799065/168204507-ddf23d71-44a6-4549-a573-2344fe8ed51a.png)

- [x] Ajustar el reporte de cada unidad con los ajustes realizados en la issue #340

**Comment by fabianbarreto02** [comment]
http://pruebasapi2.intranetoas.udistrital.edu.co:8524/v1/reportes/plan_anual

{
        "tipo_plan_id" : "61639b8c1634adf976ed4b4c",
        "vigencia" : "25",
        "estado_plan_id" : "6153355601c7a2365b2fb2a1",
        "unidad_id" : ""
}

**Comment by fabianbarreto02** [comment]
https://docs.google.com/spreadsheets/d/1QOHO36AjKG3PftW2DYz7UsXP22Sr50zW/edit#gid=481186137

**Comment by brayaned** [comment]
Se implemento la modificación para que todos los planes de acción estén en la misma hoja del reporte.

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
