### ISSUE TITLE
Ajustes varios modulo de construcción, formulación y observación 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#349]
se debe realizar los ajustes ajustes varios modulo de construcción, formulación y observación, la issue debe cumplir con los siguientes requerimientos:

- [x] Ajustar flujo para que al crear el plan se redirección al componente de construcción, actualmente se dirige al de consulta 

- [x] Ajustar carga de niveles en el modulo de construcción cuando se crea el primer nivel
![image](https://user-images.githubusercontent.com/43799065/168310842-c8619b9c-b827-403d-9875-e9340b5066df.png)

- [x] Revisar función de activar rama 

- [x] Ajustar el botón de agregar actividad para que solo sea activo cuanto este en rol  unidad  cuando este en estado en formulación, para el rol planeación no debe estar activo en ningún estado 
- [x] Para el componente de identificación docente para los recurso horas variables en el tipo hora catedra honorarios, se debe desactiva la validación de la discriminación de publico y privado, para posgrado y pregrado.
- [x] Mover la etiqueta de nivel educativo  del componente interno a la etiqueta externa 

![image](https://user-images.githubusercontent.com/43799065/168330323-d7707eab-8c3b-4bf6-bb94-4f4acdf98fba.png)

 

- [x] Ajustar el menu con servicio de configuración

**Comment by brayaned** [comment]
Se desarrollaron todos los ajustes solicitados por el usuario y fueron posteriormente aprobado en la reunión de entrega de los módulos.
