### ISSUE TITLE
Implementación reporte de necesidades presupuestal por unidad con nuevos requerimiento y necesidades consolidados

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#359]
Se debe implementación reporte de necesidades presupuestal por unidad con nuevos requerimiento y necesidades consolidados, la issue debe cumplir con los siguientes requerimientos:

- [x] Generar el reporte de necesidades consolidadas para todas las unidades de una vigencia particular y en estado aval, se debe generar un reporte por hoja para cada unidad 

![image](https://user-images.githubusercontent.com/43799065/169542985-2740e234-6732-4669-aa2e-73414c0b9b23.png)

- [x] Crear la funcionalidad para la consulta de necesidades presupuestales por rubro, debe consultar todos los rubros de todas las unidades para un vigencia particular y estado aval, unificar el valor por rubro
- [x] Crear funcionalidad para la consulta de las vinculacion docente total de todas las unidades definidas para una vigencia particular y estado aval con los totales de docente y valor 
- [x] Crear reporte de necesidades generales segun el excel 

![image](https://user-images.githubusercontent.com/43799065/169543748-762b12ff-d59c-41a6-8a6e-b46dc96c580b.png)

**Comment by brayaned** [comment]
Se integraron las identificaciones de recursos, contratistas y docentes para incluirlas en el reporte anual por unidad.

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
