### ISSUE TITLE
Ajuste la parametrización de la creación de los sub niveles con tipo de dato y si es requerido 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#36]
Se debe realizar el ajuste en el modulo de construcción de los planes al momento de crear un nivel dos en adelante, al momento de crear el sub nivel se debe incluir una pequeña sección para ingresa los parámetros del campo en el formulario, entre ellos el tipo de dato (numérico, texto o un select) y si el campo es requerido o no (ver imagen guía).

![image](https://user-images.githubusercontent.com/43799065/131141065-38b74951-6247-4693-98e5-37d589970adb.png)

También se debe ajustar a nivel de Mid   la función para el registro del subgrupo, estos nuevos parámetros se registran en la tabla subgrupo_detalle en el campo dato en formato json, estos campos tanto en el cliente como en backend no deben ser obligatorios y desde el cliente se debe observar desde el segundo nivel, la issue debe cumplir con los siguientes requerimientos:

- [ ]    Ajustar el cliente con la solicitud mencionada 
- [ ] Ajustar el metodo de registro Post, Get y Put con los ajustes informados

**Comment by brayaned** [comment]
Se da inicio a la issue.

**Comment by brayaned** [comment]
Se realizó el ajuste correspondiente en los componentes agregar y editar subgrupo, dentro de la construcción de planes. Se actualizo la vista generando un select para escoger el tipo de dato que desee el usuario y un radio button para que el usuario escoja si el campo es requerido o no.

**Comment by brayaned** [comment]
Se actualizaron las funciones POST y PUT para registrar nuevos subgrupos, y así mismo registrar el subgrupo-detalle de cada uno de estos nuevos subgrupos creados. También se cumple la condición que solo los subgrupos de nivel 2 en adelante puedan registrar esta información paramétrica en subgrupo-detalle.

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
