### ISSUE TITLE
Implementación de reportes para el proceso de seguimiento en el cliente 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#372]
Se debe Implementación de reportes para el proceso de formulación de planes de acción en el cliente, la issue debe cumplir con los siguientes requerimientos:

- [x]  Implementar  los [mockups](https://drive.google.com/file/d/1KKeKK7C5niUPHZfA0bzznanTqEBshNZH/view?usp=sharing) en el cliente para la generación de los reportes
- [x]  Implementar las funcionalidades de generación de reporte para los cuatro reporte.
- [x] Implementar la descarga de los excel desde el cliente convirtiendo la base 64 a excel 
- [x] Implementar la función de conversión a pdf para la pre visualización de reportes desde el cliente

**Comment by brayaned** [comment]
Se desarrolló el nuevo componente para la consulta de reportes desde el cliente para los planes anuales por unidad y generales.

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
