### ISSUE TITLE
Construcción del componente dinámico para la formulación de planes de acción de funcionamiento e inversión con función del mid

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#39]
Se debe desarrollar la construcción del componente dinámico para la formulación de los planes de acción de funcionamiento e inversión con la función desarrollada en el mid, este componente debe consultar por medio de select el tipo de plan se va formular por el momento seria solo de acción, una vez seleccionada el plan, se debe seleccionar por medio de un select la unidad a crear la formulación y la vigencia (año), una seleccionado todo  se consume el método desarrollado y construir el componente con los campos para la formulación, la issue debe cumplir los siguientes requerimientos :

- [x] #47
- [x]  Crear el componente  dinámico  con la consulta del mid 
- [x] Realizar pruebas con el funcionamiento explicado

**Comment by ndmc98** [comment]
Se inicia la issue el 06/09/2021

**Comment by ndmc98** [comment]
Se crea el componente con los select solicitados y la consulta de los planes y el formato en el MID. Se realizan pruebas que llevan a sugerir cambios en el cliente. 
Además se construyó un tercer nivel para probar el plan de acción de inversión. Este se consiga construir de forma dinámica empleando la consulta al MID.

**Comment by ndmc98** [comment]
Se da fin a la issue con el Pull Request respectivo el 13/09/2021

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
