### ISSUE TITLE
Implementación de mockups para la creación de planes 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#4]
Se debe realizar el enmaquetado de los [mockups ](https://drive.google.com/file/d/1G52KIATYIpwv7XtgY5xXRjanyc4uJm-U/view) para el proceso de creación de planes en nuestro cliente, la issue debe cumplir los siguientes requerimientos:

- [x] Crear la distribución de los menus definidos en el mockup 
- [x] Crear el componente sin funcionalidad de Formulación/ proyectro/planes / definir 
- [x]  Crear el componente sin funcionalidad de Formulación/ proyectro/planes / construcción
- [x] Crear el componente sin funcionalidad de Formulación/ proyectro/planes / construcción para la creación y edición del PUI
- [x] Crear el componente sin funcionalidad de Formulación/ proyectro/planes / construcción para la creación y edición del PED

**Comment by ndmc98** [comment]
Se inicia la tarea con la revisión del cliente [ARKA II ](https://github.com/udistrital/arka_cliente) para revisar las opciones de menú para la creación de planes y la jerarquía asociada al cliente del subsistema de planeación.

**Comment by ndmc98** [comment]
Sobre el cliente de planeación se empieza con la limpieza, ajuste y creación de las diferentes vistas necesarias y establecidas en los Mockups. Se realiza una breve sesión de aclaración con los ingenieros Fabián Sánchez y Fabián Barreto para entender y realizar la inclusión de submenús en el menú principal de la interfaz. 

![image](https://user-images.githubusercontent.com/24207969/127320692-08ea8802-e613-48ef-837e-149a83cacae6.png)

**Comment by ndmc98** [comment]
Se siguen los Mockups para realizar los ajustes y configuraciones iniciales del _menú_ y la vista _crear_ dentro de los _Proyectos / Planes_. 

![image](https://user-images.githubusercontent.com/24207969/127320951-5448cc8c-ff34-468f-ba89-154a0a68532f.png)

![image](https://user-images.githubusercontent.com/24207969/127320988-a0361005-b9db-4414-b68e-6ec85609b1eb.png)

![image](https://user-images.githubusercontent.com/24207969/127321033-55722ea0-6189-4e8c-a379-c796649bc537.png)

**Comment by ndmc98** [comment]
Se realiza la limpieza de algunos archivos con el propósito de ajuste y adaptación al cliente de planeación. De esta forma, se limpian componentes e instrucciones que se relacionaban al cliente base tomado [_alternancia_](https://github.com/udistrital/alternancia_cliente)

**Comment by ndmc98** [comment]
Se modifica el menú del cliente según los cambios realizados en el [Mockup](https://docs.google.com/document/d/1G52KIATYIpwv7XtgY5xXRjanyc4uJm-U/editl)

![image](https://user-images.githubusercontent.com/24207969/128741586-c2c73318-ad94-418b-a25c-967027271359.png)

**Comment by ndmc98** [comment]
Se crea el componente para definir y construir (PUI y PED) siguiendo el [Mockup](https://docs.google.com/document/d/1G52KIATYIpwv7XtgY5xXRjanyc4uJm-U/edit) 

Las vistas muestran, respectivamente: componente _definir_, componente _construir_, vista para construir _PUI_ y vista para la construcción de _PED_ ubicando la tabla con el arbol, las opciones de _agregar nivel_ (primer nivel), _editar_ y _agregar_ (n niveles).

![image](https://user-images.githubusercontent.com/24207969/128743607-ae4e30d4-8cac-4c0b-8923-412667fc1de5.png)

![image](https://user-images.githubusercontent.com/24207969/128743654-6914dcaa-1fdb-4a61-b92b-ec26aca8322e.png)

![image](https://user-images.githubusercontent.com/24207969/128743717-61a88286-b0db-4c7f-95d8-1851c0790f52.png)

![image](https://user-images.githubusercontent.com/24207969/128743762-79c392f3-0dec-44b3-bbed-d5fa2dce48ad.png)

**Comment by ndmc98** [comment]
Se da finalización a la tarea
