### ISSUE TITLE
Creación del flujo para la generación de actividades en los planes de acción en general

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#43]
Se debe desarrollar el flujo sugerido para la creación de las actividades de forma individual  para los planes  de acción, para esto se debe crear una tabla estática con información pre cargada , por ahora las columna se definirán como numero de actividad, nombre de actividad, rubro presupuestal, valor presupuestal, observación, estado, y acciones ( ver/editar), también agregar dos botones   (agregar nueva actividad y culminar plan), al presionar el botón nueva actividad   se debe activar el componente dinámico de formulación  para ingresar la información, al presionar el  botón Culminar plan  se debe mostrar un modal de advertencia informado si esta seguro de enviar el plan a revisión, la issue debe cumplir con el siguiente requerimiento:

- [x] Crear los ajustes al componente como la tabla con información quemada y el flujo de acciones del los botones en la tabla
- [x] Implementación del flujo explicado

**Comment by ndmc98** [comment]
Se dio inicio a la issue el 13/09/2021

**Comment by ndmc98** [comment]
Se creó la tabla con la información quemada y el flujo de operación con las opciones de botones, dialogos y lo esperado para cada uno. Se presenta el desarrollo el cual cumple con las tareas de la issue.

**Comment by ndmc98** [comment]
Se genera el Pull Request y se da por finalizada la issue.

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
