### ISSUE TITLE
Ajustar dialogo de edición en el componente listar y componente definir  por ajustes en api de crud

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#44]
Se debe realizar los ajustes correspondientes a nivel de crud, mid y cliente por los ajustes realizados en la tabla plan del api planes crud, la issue debe cumplir con los siguientes requerimientos:

- [x] Realizar ajustes a nivel de crud  si es necesario (vigencia no obligatorio y dependencia no obligatorio)
- [x] Realizar los ajustes a nivel de mid para el registro, consulta y la función de inhabilitar hijas de arboles padres
- [x] Realizar ajuste a nivel de cliente en el componente de dialogo de edición por ajustes realizados
- [x] Realizar ajuste en el componente de definir con un nueva opción para seleccionar si es un plan/ proyecto si es formato o no

**Comment by brayaned** [comment]
Se da inicio a la issue.

**Comment by brayaned** [comment]
Se realizaron las 4 tareas de ajuste, analizando cada uno de lo errores y encontrando la solución sin ningún problema mayor.  Se da por teminado el desarrollo de la issue.

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
