### ISSUE TITLE
Analizar  y avanzar la funcionalidad para incluir un campo adicional de observación en el componente dinámico

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#45]
Se debe realizar el análisis para la creación de un campo de observación con la función de construcción de un componente de formulación dinámica y iniciar el avance con los ajustes correspondientes para la funciones ya creadas,  la issue debe cumplir con los siguientes requerimientos:

- [x] Realizar el análisis para el ajuste correspondiente para el ajuste indicado
- [x] Iniciar el ajuste de las funciones desarrolladas con el análisis

**Comment by ndmc98** [comment]
Se da inicio a la issue el 15/09/2021

**Comment by ndmc98** [comment]
Se da por finalizada la issue el 17/09/2021.
Se genera el Pull Request respectivo.

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
