### ISSUE TITLE
Creación de funcionalidad para asignación de parametrización de un nivel particular en el arbol 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#46]
Se debe crear la funcionalidad para que la parametrización de un nivel de un árbol se puede decidir con un botón o un select , la issue debe cumplir con los siguientes requerimientos:

- [x] Crear la funcionalidad definida

**Comment by brayaned** [comment]
Se da inicio a la issue.

**Comment by brayaned** [comment]
Se desarrollo la funcionalidad para que el usuario decida cuando quiere o no  parametrizar a cada uno de los subgrupos que agrega. No se presentaron problemas en el desarrollo y se da como terminado el desarrollo de  la issue.

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
