### ISSUE TITLE
Ajuste incremento salarial modulo docente en Formulación de plan de acción

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/planeacion_cliente#475]
La issue debe cumplir los siguientes requerimientos:
- [x] Revisar módulo formulacion/docentes para incluir incremento porcentual a salarios.
- [x] Añadir input al componente mencionado para manejar el incremento porcentual.

**Comment by NeFaWaltPint** [comment]
Se da desarrollo a los requerimientos.

**Comment by NeFaWaltPint** [comment]
Actividades desarrolladas para [Planeación](https://github.com/orgs/udistrital/projects/30)

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue, se realiza despliegue en ambiente de test y prod
