### ISSUE TITLE
Análisis, definición e implementación del flujo en el cliente para la creación de del plan clonado y reasignación de formato a plan asignado 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#58]
Se debe realizar el análisis para la implementación del flujo para la funcionalidad del método post en la formulación de planes de acción, al asignar la primera actividad al plan se debe consumir el método de clonar plan definido en api MID, una vez creado el clon del plana asignado la unidad   y la vigencia,  se debe implementar la función post para realizar el registro de la información de la actividad   una vez creado el plan clonado y asignado, al finalizar este flujo se debe implementar el flujo para que la vista en el cliente se cambie de forma automática del formato inicial al plan asignado  para dar continuidad a la formulación del plan de acción, también se debe  realizar una funcionalidad adicional para que al momento de ingresar al componente y al seleccionar la unidad y posterior vigencia se seleccione el formato a ingresar (plan de acción) de no tener asignado aun plan, si por el contrario la unidad en la vigencia  seleccionada se debe seleccionar de forma automática el plan el cual esta formulado, la issue debe cumplir con los siguientes requerimientos:

- [x] Analizar cual es el flujo que se puede implementar.
- [x] Implementar el flujo para clonar el plan de acción 
- [x] Implementar el flujo para la función post para la creación de actividades 
- [x] Implementar el flujo para el select de formato o plan asignado

**Comment by ndmc98** [comment]
Se da inicio a la issue el 28/09/2021

**Comment by ndmc98** [comment]
Se realizó el análisis sobre el flujo a implementar considerando las opciones de vigencia, unidad y plan. Del análisis se encontró la necesidad de ajustar el MID para obtener los filtros por campos específicos; la necesidad surgió como una nueva feature a desarrollar.

**Comment by ndmc98** [comment]
Tras los ajustes en el MID, se implementó el flujo para la selección y asignación del plan, el cuál involucró el flujo de clonación. 
Tras seleccionar unidad, vigencia y plan, se valida la existencia de clon, y según sea el caso, se despliega la opción de clonar o de adicionar actividades; para todos los casos siempre se mantiene el plan clonado al momento de formular, garantizando la diferencia entre formato y clon.

**Comment by ndmc98** [comment]
La opción de adicionar actividad consume la función PUT del MID para registrar la información registrada en el formulario.

Se genera Pull request con las actualizaciones mencionadas en el cliente.

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
