### ISSUE TITLE
Consumir los servicios de vigencia y unidad en los select del cliente 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#59]
Se debe consumir los servicios de vigencia y unidad  para los select del la formulación de planes de acción, la issue debe cumplir con los siguientes requerimientos:

- [x] Consumir el servicio para la vigencia del api de parametros_crud http://pruebasapi.intranetoas.udistrital.edu.co:8510/v1/periodo?query=CodigoAbreviacion:VG   (https://autenticacion.portaloas.udistrital.edu.co/apioas/parametros_crus/v1/periodo?query=CodigoAbreviacion:VG)
- [x] Consumir el servicio para las unidades del api de oikos_crud (http://api.intranetoas.udistrital.edu.co:8087/v1/dependencia?limit=0) (https://autenticacion.portaloas.udistrital.edu.co/apioas/oikos_crud_api/v2/dependencia)

**Comment by ndmc98** [comment]
Se da inicio a la issue el 27/09/2021

**Comment by ndmc98** [comment]
Se consumen los servicios de las api's parametros_crud y oikos_crud para obtener las vigencias y las unidades en el cliente.

Se dejan definidas en _environment_ para pruebas y en _test_ y _producción_ a través de _autenticación_.

![image](https://user-images.githubusercontent.com/24207969/135019114-a07233bf-1dfd-4da1-a3c8-8979c85f7fae.png)

![image](https://user-images.githubusercontent.com/24207969/135019140-7d7ccd41-6d7f-43f7-a388-bc3fa5ac5587.png)

**Comment by ndmc98** [comment]
Se genera el respectivo Pull Request con la feature solicitada en la issue

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
