### ISSUE TITLE
Implementación de funcionalidad delete y función Put en el cliente 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#65]
Se debe implementar la funcionalidad para las funciones Delete desarrollada en el mid  y la funcionalidad de  actualización de una actividad, se debe ajusatar flujos en el cliente, actualización de tablas y mensajes de notificación, la issue debe cumplir con los siguientes requerimientos:

- [x] Implementar del  flujo para la actualización de actividades en el componente de formulación 
- [x] Implementación del flujo  para la eliminación de actividades en el componente de formulación

**Comment by ndmc98** [comment]
Se da inicio a la issue el 11/10/2021

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
