### ISSUE TITLE
Creación del flujo para la tabla de resumen de las actividades 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#67]
Se debe realizar la creación del flujo para la visualización de la tabla resumen con las actividades, se debe realizar las siguientes actividades:

- [x] Crear formato sin tener en cuanta la armonización para los  planes de acción de funcionamiento
- [x] Crear el flujo para la visualización de la tabla para planes de  funcionamiento e inversión 
- [x] Crear tabla con la información marcada con la bandera para los  planes de funcionamiento

**Comment by ndmc98** [comment]
Se dio inicio de la issue el 07/10/2021

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
