### ISSUE TITLE
Funcionalidad para los componentes del menu de construcción de listar y definir

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#7]
Se debe desarrollar la funcionalidad para los componentes de listar(tabla) y definir (función post y put), la issue debe cumplir con los siguientes requerimientos:

- [x] Desarrollar la funcionalidad para la tabla que lista los planes (función get)
- [x] Desarrollar la funcionalidad para la creacion de planes (función post y put)
- [x] Desarrollar la funcionalidad para la función de inactivar un plan ( Put con cambio de campo "activo")

**Comment by ndmc98** [comment]
Se da inicio a la issue

**Comment by ndmc98** [comment]
Se concluyen los ajustes de los componentes para cumplir con las funcionalidades de los planes de listar, editar, crear y cambiar estado. 

- Listar planes (GET):

![image](https://user-images.githubusercontent.com/24207969/129382681-fe3869fb-9647-4088-9cde-cc8e336c977a.png)

- Crear plan (POST):

![image](https://user-images.githubusercontent.com/24207969/129382960-9a1485bb-0bb9-48d1-a038-cdd002e7cf3f.png)
![image](https://user-images.githubusercontent.com/24207969/129382993-80fbc1d2-58aa-4649-b542-2a71165557f9.png)

- Editar plan (PUT):

![image](https://user-images.githubusercontent.com/24207969/129383216-767029d2-79c0-4b45-854b-df175b1d06cf.png)
![image](https://user-images.githubusercontent.com/24207969/129383254-27dc7f43-aabb-4d71-aa7c-6c3eb6c04da7.png)

- Editar _activo_ (PUT cambio en campo "activo"):

![image](https://user-images.githubusercontent.com/24207969/129383421-80db06ae-6eb2-4b99-929b-e314af4f88c4.png)
![image](https://user-images.githubusercontent.com/24207969/129383449-56719ae3-e37d-4b62-981c-a0594e157e98.png)

**Comment by ndmc98** [comment]
Se da por finalizada la issue.
