### ISSUE TITLE
Implementación de select dinámico en el formulario 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#73]
Se debe desarrollar la implementación de select dinámico en el formulario, para cumplir la tarea se debe desarrollar con los siguientes requerimientos:

- [x] Ajustar el componente de construcción de planes para en la parte de parametrización para que se muestre un input al seleccionar un select y se pueda incluir los valores del input, mostrar un mensaje para el usuario informando como ingresar cada elemento.
- [x] Ajustar el método a nivel de mid para almacenar la parametrización con el formato necesario para la consulta del componente dinámico.
- [x] Realizar los ajustes necesarios a nivel del cliente o MID para la consulta de un select en un formulario dinámico  con un valor previamente seleccionado

**Comment by ndmc98** [comment]
Se ajusta el componente de construcción de planes de modo que en la parte de parametrización se muestra un _input_ al seleccionar el tipo _select_ y así incluir los valores correspondientes a la lista de selección que desea el usuario; adicionalmente se muestra un mensaje para el usuario informando como ingresar cada elemento, en este caso separado por comas (por ejemplo: valor1,valor2,valorN).

Se ajusta el método a nivel de MID para guardar y obtener la parametrización con el formato necesario para la consulta del componente dinámico.

Se realizan los ajustes necesarios a nivel del cliente para capturar el retorno de la consulta para el tipo _select_ de forma que se construya adecuadamente el formulario dinámico con el valor previamente seleccionado.

**Comment by ndmc98** [comment]
Se genera Pull Request para Cliente y para MID para dar cierre a las tareas

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
