### ISSUE TITLE
Funcionalidad y ajustes del flujo de modificación para el árbol de planes

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#8]
Se debe realizar los ajustes hablado para el flujo de construcción de los planes, puntualmente incluir el componente de dialogo para la edición de información de cualquier nivel del plan, se debe anexar un botón para la ejecución del dialogo, una vez ajustado el flujo, realizar la funcionalidad para la creación de un nivel, edición de un nivel y consulta del arbol del plan, la issue debe cumplir con los siguientes requerimientos:

- [x]   Crear el componte para la edición y la creación de los niveles con un dialogo para cada nivel, debe ser un componente general para todos los actividades.
- [x] Realizar la funcionalidad  para la creación de un nivel con el api de planes_crud
- [x] Realizar la funcionalidad  para la modificación de un nivel con el api de planes_crud
- [x] Realizar la funcionalidad  para la consulta de un plan con el api de planes_crud

**Comment by ndmc98** [comment]
Se da inicio a la issue

**Comment by ndmc98** [comment]
Se crea el componente para _editar_ y _crear_ a través del componente _Dialog_ de Material para la edición y creación de información de cualquier nivel del plan. Se crea como componente general. 

![image](https://user-images.githubusercontent.com/24207969/129385053-008731d0-1149-43f7-90d0-f5d7dece94f4.png)
![image](https://user-images.githubusercontent.com/24207969/129385124-bbe13b11-19de-4f9d-92a5-0e18ad45cb44.png)

**Comment by ndmc98** [comment]
- Se realiza la funcionalidad para la creación de un nivel con el api de planes_crud (POST)

- Se realiza la funcionalidad para la modificación de un nivel con el api de planes_crud (PUT)

- Se realiza la funcionalidad para la consulta de un plan con el api de planes_crud (GET ARBOL a través de MID y CRUD)

**Comment by ndmc98** [comment]
Se da finalización a las tareas y la issue con la generación del pull request.
