### ISSUE TITLE
División del sistema en Microservicios

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#803]
Se requiere realizar la planeación para dividir el sistema SISGPLAN en microservicios, de tal forma que cada uno sea independiente, autosuficiente, escalable, resiliente y tolerante a fallos. El objetivo es lograr desacoplar las funcionalidades del sistema y descentralizar los servicios de forma lógica para que sea mas sencillo realizar mantenimiento en los mismos y facilitar tareas de intervención por parte del equipo de desarrollo.

**Especificaciones técnicas**
1. Cada Microservicio debe estar conformado por el conjunto de servicios que se relacionen funcionalmente.
2. Dependiendo de las funcionalidades del microservicios, cada uno debe consumir la BD que requiera.
3. Cada Microservicio debe ser descentralizado, lo cual implica que debe poder ser desarrollado, implementado y escalado de forma independiente de otros.

**Sub Tareas**

- [x] Análisis del sistema a nivel de código para comprender su funcionamiento y grado de acoplamiento y unión entre servicios y funcionalidades.
- [x] Creación de diagrama de componentes de la arquitectura propuesta para el sistema de SISGPLAN.
- [x] Creación de listado de Microservicios a detalle, señalando las funcionalidades que lo conforman, así como su relación con otros microservicios y componentes de la OATI.

**Criterios de aceptación**

- [x] El diagrama de componentes muestra la división clara del sistema en múltiples microservicios y su relación con los diferentes componentes de la OATI para su funcionamiento como sistema de información.
- [x] El detalle de los microservicios, muestra el listado de funcionalidades que componen cada microservicio y que relación existe entre cada uno de los microservicios entre si y con otros componentes de la OATI.

**Requerimientos**

- [x] Link del sistema en ambiente de pruebas.
- [x] Material de apoyo.
- [x] Credenciales de acceso al sistema.

**Dependencias**

- No presenta.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
**Material de apoyo:** https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Eg7Us5oK-YFEpOPjBM8F3jsBbfu0tkTE8wlwwfK0Kq-0NQ?e=BMb48z
**Link del sistema en ambiente de pruebas:**  https://pruebasplaneacion.portaloas.udistrital.edu.co/#/pages/dashboard

Las credenciales del sistema se pasaron por interno.

**Comment by Mechaz123** [comment]
Se realiza el levantamiento con respecto a cómo está construido el sistema de PLANEACION_MID, y así mismo se crea en una hoja a parte la propuesta para la división en Microservicios, dando un resultado de 4 microservicios.

https://drive.google.com/file/d/1h9gerErueRXNr2StkfX3srKsRQG05m2J/view?usp=sharing

Se adjunta el diagrama creado en draw.io y así mismo se queda al pendiente para ajustes y revisión.

**Comment by Mechaz123** [comment]
Se desarrolló el diagrama detallado de cómo se encuentra actualmente conectado el sistema.

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/90f2ceed-ba54-4501-8005-d432bf374b20)

En base al anterior diagrama se desarrolló la propuesta para la división en microservicios y se adjunta un diagrama más detallado de la propuesta.

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/a8cfe7b7-7d64-499b-80ed-54531ae4b257)

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/c659c5fd-6577-41d7-a4d4-fd3e26a302a2)

**Comment by Mechaz123** [comment]
Se desarrolla la propuesta versión 2 en base a las observaciones realizadas.

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/2006b3ae-bdfc-4c0c-8ebd-20540144e846)

Así mismo se adjunta un diagrama general y uno detallado de la nueva propuesta.

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/6818a7da-9c48-41a8-8675-64f4b09e0015)

**Comment by Mechaz123** [comment]
Se adjunta descripción del funcionamiento del cada uno de los Componentes.

![SISGPLAN-Propuesta (V2) drawio (2)](https://github.com/udistrital/planeacion_cliente/assets/73924638/63fa23fa-e24d-44a0-93ef-b727ee33e154)
