### ISSUE TITLE
Revisión y Estabilización de SISGPLAN en ambiente de pruebas.

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#804]
Se requiere revisar y estabilizar el sistema de SISGPLAN en ambiente de pruebas, de tal forma que quede funcional con información de prueba.

**Especificaciones técnicas**
1. El ambiente de pruebas de SISGPLAN es: https://pruebasplaneacion.portaloas.udistrital.edu.co/#/pages/dashboard 
2. Se deben emplear usuarios de Planeación y de las Dependencias (unidades) de prueba.
3. Las APis y el cliente asociados a SISGPLAN son:
- [planeacion_mid](https://github.com/udistrital/planeacion_mid)
- [planes_crud](https://github.com/udistrital/planes_crud)
- [planeacion_cliente](https://github.com/udistrital/planeacion_cliente)
4. Los datos asociados a la BD son:
- Base de Datos: udistrital_administrativa
- Esquema: planes

**Sub Tareas**

- [x] Revisión de funcionalidades del sistema en ambiente de pruebas.
- [x] Pruebas funcionales del sistema en ambiente de pruebas.
- [x] Ajuste de información en BDs.

**Criterios de aceptación**

- [x] El sistema permite realizar pruebas sin inconvenientes en las funcionalidades disponibles en ambiente de pruebas.
- [x] La BD se encuentra con información de prueba que permite utilizar todas las funcionalidades del sistema.

**Requerimientos**

- [x] Link del sistema en ambiente de pruebas.
- [x] Credenciales de acceso al sistema.
- [x] Información de la BD.

**Dependencias**

- No presenta.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
Las credenciales de acceso al sistema se comparten por interno.

**Comment by a52290451** [comment]
Se realiza la revisión del módulo de Construcción de planes con las siguientes observaciones:

1. El modulo se encuentra estable y funcional en ambiente de pruebas. No se requieren realizar ajustes de información en BDs.
2. Se encontraron los siguientes inconvenientes en las pruebas realizadas:

- No actualiza información asociada al plan (nombre, descripción, etc). Esto se relaciona con un error en la información enviada en el PUT ya que esta incompleta.
- Cuando se crea un nuevo plan o proyecto y este se va a construir por primera vez, se queda en pantalla de carga y hay que darle clic en un costado para que se quite.
- Cuando se agrega un nuevo nivel en la construcción de un plan, al seleccionar "No" en "Parámetros", debería marcarse automáticamente la opción "No" en "Campo en tabla resumen", ya que son codependientes. Actualmente no se marca nada y cuando se elige la opción "Si" en "Campo en tabla resumen", sale un letrero de advertencia y se marca por defecto "No".
- No permite actualizar Niveles "Metas" en una plantilla de proyecto ya creada. Se totea ya que el put a "subgrupo" esta incompleto.
- En la formulación de un nuevo plan para una Unidad presenta problemas, ya que hace un post para clonar la plantilla base y luego un PUT sobre ese nuevo registro clonado. Este Post modifica el ID original y esto no se puede hacer ya que es un campo inmutable.

**Nota:** Para la revisión de los demás módulos se requiere apoyo de un experto en el sistema ya que hay partes complejas, difíciles de entender.

**Comment by felimarod** [comment]
### Ejecución en local
- API CRUD con NestJS y Mongo
![Captura desde 2024-01-12 10-16-17](https://github.com/udistrital/planeacion_cliente/assets/85894335/c6262b9f-5ba0-40aa-8dd7-3ed82de80004)

- API MID con Beego
![Captura desde 2024-01-12 10-16-25](https://github.com/udistrital/planeacion_cliente/assets/85894335/e2818b8e-a339-4aec-aba3-7766d2ca144f)

- Cliente
![Captura desde 2024-01-12 10-18-18](https://github.com/udistrital/planeacion_cliente/assets/85894335/2392a19d-dd45-4c3f-9846-6a6c3cb4c181)

![Captura desde 2024-01-12 10-18-26](https://github.com/udistrital/planeacion_cliente/assets/85894335/aa2dc7bc-0c4f-4d0e-bb75-70609bf33eb5)

**Comment by a52290451** [comment]
Nueva revisión del sistema SISGPLAN:

https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EWEgo9OWgQJBtENs1ljbZUQB30mH8JYu2nYH4wGKprTaBw?e=pSP6T4

**Comment by milo19980525** [comment]
Se cierra teniendo en cuenta que la depuración de la base de datos no se realizó.
