### ISSUE TITLE
Instalación y pruebas en local de APIs y cliente SISGPLAN

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#806]
Se requiere instalar y conectar en local las APIs y el cliente de SISGPLAN, realizar la conexión con la BD y comprobar el funcionamiento del sistema.

**Especificaciones técnicas**
1. La base de datos de SISGPLAN se encuentra en Mongo DB.
2. Las APIs asociadas son: 
- [planeacion_mid](https://github.com/udistrital/planeacion_mid)
- [planes_crud](https://github.com/udistrital/planes_crud)
- [planeacion_cliente](https://github.com/udistrital/planeacion_cliente)
3. Los datos de conexión a la BD se proporcionan por interno.
4. Para lograr conectar con la BD es necesario tener activa la VPN.
5. La información que se registre en la BD afecta el ambiente de pruebas directamente, por lo que se debe tener cuidado con las modificaciones que se realicen.
6. La conexión entre APIs y el cliente se realiza mediante puertos y la configuración de variables de entorno.

**Sub Tareas**

- [x] Instalación de APIs y Cliente en local.
- [x] Configuración de API CRUD con BD en MongoDB.
- [x] Conexión entre APIs y el cliente.
- [x] Pruebas del sistema en local.

**Criterios de aceptación**

- [x] Los servicios de las APIs responden correctamente en ambiente local.
- [x] Se comprueba el funcionamiento del sistema en local, conectando las APIs y el Cliente.
- [x] Se evidencia el funcionamiento del sistema en local a través de capturas de pantalla enviadas por el desarrollador.

**Requerimientos**

- [x] Credenciales de BD.
- [x] Variables de entorno para API MID.
- [x] Variables de entorno para API CRUD.
- [x] Acceso a la VPN.

**Dependencias**

- No presenta.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Comment by a52290451** [comment]
Variables de entorno planes_crud:

- PLANES_CRUD_HOST: mongotest.udistritaloas.edu.co
- PLANES_CRUD_PORT: 27017
- PLANES_CRUD_DB: udistrital_administrativa
- PLANES_CRUD_AUTH_DB: admin
- PLANES_CRUD_HTTP_PORT: XXXX **(Depende del puerto que quieran habilitar en local)**
- PLANES_CRUD_USER: **Se remite por interno.**
- PLANES_CRUD_PASS: **Se remite por interno.**

Variables de entorno planeacion_mid:

- PLANES_SERVICE: pruebasapi2.intranetoas.udistrital.edu.co:8523 **(reemplazar por url de planes_crud en local)**
- PLAN_CUENTAS_SERVICE: pruebasapi.intranetoas.udistrital.edu.co:8203/v1
- OIKOS_SERVICE: api.intranetoas.udistrital.edu.co:8087/v1
- PARAMETROS_SERVICE: pruebasapi.intranetoas.udistrital.edu.co:8510/v1
- TERCEROS_SERVICE: pruebasapi.intranetoas.udistrital.edu.co:8121/v1
- PLANES_MID_STATIC_PATH: static/
- GESTOR_DOCUMENTAL_SERVICE: pruebasapi2.intranetoas.udistrital.edu.co:8199/v1

**Nota:** para el funcionamiento de las APIs y las variables de entorno, se requiere  establecer conexión con la VPN, de lo contrario no se tendrá acceso a las APIs externas y a la Base de Datos.

**Recomendación:** se debe tener cuidado con las pruebas que se realicen en el sistema ya que la información que se modifique, repercute en la información que se encuentra actualmente en ambiente de pruebas.

**Comment by felimarod** [comment]
### Ejecución en local
- API CRUD con NestJS y Mongo
![Captura desde 2024-01-12 10-16-17](https://github.com/udistrital/planeacion_cliente/assets/85894335/c6262b9f-5ba0-40aa-8dd7-3ed82de80004)

- API MID con Beego
![Captura desde 2024-01-12 10-16-25](https://github.com/udistrital/planeacion_cliente/assets/85894335/e2818b8e-a339-4aec-aba3-7766d2ca144f)

- Cliente
![Captura desde 2024-01-12 10-18-18](https://github.com/udistrital/planeacion_cliente/assets/85894335/2392a19d-dd45-4c3f-9846-6a6c3cb4c181)

![Captura desde 2024-01-12 10-18-26](https://github.com/udistrital/planeacion_cliente/assets/85894335/aa2dc7bc-0c4f-4d0e-bb75-70609bf33eb5)

**Comment by ccmendezt** [comment]
# Ejecución en ambiente local
## API CRUD - NestJS
- Ejecución API CRUD: 
![API Crud](https://github.com/udistrital/planeacion_cliente/assets/82072560/34a13067-7c5f-42c6-bf7c-dbba0b438667)
- Petición API CRUD: 
![Peticion API Crud](https://github.com/udistrital/planeacion_cliente/assets/82072560/f226c9c0-3f41-44cf-bf7f-bcded61c966d)
## API MID - Go
- Ejecución API MID: 
![API Mid](https://github.com/udistrital/planeacion_cliente/assets/82072560/f5158ab5-ba46-4ad7-9ebd-f3431faa196e)
- Petición API MID: 
![Peticion API Mid](https://github.com/udistrital/planeacion_cliente/assets/82072560/b7b9e392-0d02-4919-87a1-5f45a797baf0)
## Cliente - Ángular
- Ejecución Cliente: 
![Cliente](https://github.com/udistrital/planeacion_cliente/assets/82072560/23445b9b-19df-4ea7-8210-171e4b21b64b)
![demoClienteSISGPLAN](https://github.com/udistrital/planeacion_cliente/assets/82072560/2e634853-df87-4505-93a3-119b46d8ac77)

**Comment by diegobauto** [comment]
## planeacion_crud
- Ejecución:
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/8d3347ff-a640-4a2e-a7d2-58942dee13dd)
- Resultado: 
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/a03b00b5-a1b3-4531-9e20-8662f25ab601)

## planeacion_mid
- Ejecución:
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/9a17ae39-6e50-4afb-84a6-d3bbaa787f66)
- Resultado: 
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/0350d32a-9b81-47e7-9202-f68951282f99)

## planeacion_cliente
- Ejecución:
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/c5fd96fe-b53d-4d9a-9a20-7facfc7c7cb6) 
- Resultado:
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/a93b6faf-776f-4f18-bde4-755638c3bbb5)

**Comment by C0C045** [comment]
# SISGPLAN EN AMBIENTE LOCAL
## API CRUD
`1.` **Ejecución:**
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/713e3b9e-2a1c-4169-b451-0375ee6c006a)

`2.` **Petición GET:**
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/a962a5ff-af95-49c1-a0c2-8538e54cbdb5)

## API MID
`1.` **Ejecución:**
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/1fb52e0a-a66a-4219-bf50-e8b590ce1c31)

`2.` **Petición GET:**
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/44921517-eea4-4242-99df-f98c7a883488)

## CLIENTE
`1.` **Ejecución:**
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/285cfb16-03d6-48a5-989b-ebf92348221b)

`2.` **Prueba:**
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/57c5fac2-aa39-4446-9bfe-5fa90cec38f1)

**Comment by EdissonFrancisco** [comment]
API CRUD
![imagen](https://github.com/udistrital/planeacion_cliente/assets/109987805/89e4c29b-8437-459a-ad7c-c8c2340e9e71)
![imagen](https://github.com/udistrital/planeacion_cliente/assets/109987805/9d84e72a-6598-4526-b0d6-087649609a26)

API IMD
![imagen](https://github.com/udistrital/planeacion_cliente/assets/109987805/d411b9d8-73dd-4f20-97be-ebea76947527)
![imagen](https://github.com/udistrital/planeacion_cliente/assets/109987805/64520245-c38e-4029-8a04-b80c3dcfaa83)

CLIENTE
![imagen](https://github.com/udistrital/planeacion_cliente/assets/109987805/60a50e1e-5185-469d-839c-3cbe70671e2d)
![imagen](https://github.com/udistrital/planeacion_cliente/assets/109987805/848bb326-c948-4b83-bb75-378f9ad44520)

**Comment by a52290451** [comment]
Se valida actividad para todos los responsables y se da por terminado el ISSUE.

¡Buen trabajo para todos!
