### ISSUE TITLE
Revisión y pruebas de funcionamiento de SISGPLAN.

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#807]
Se requiere realizar la revisión y pruebas de funcionamiento de SISGPLAN en ambiente local, siguiendo todos los flujos habilitados en el sistema (Construcción, Formulación, Seguimiento, Evaluación y Reportes). El objetivo es encontrar los bugs, fallas del sistema, funcionamiento erróneo o posibles mejoras en el sistema, y registrar estos hallazgos en el formato adjunto.

**Especificaciones técnicas**

1. Las APIs y el cliente asociadas a SISGPLAN son: 
- [planeacion_mid](https://github.com/udistrital/planeacion_mid)
- [planes_crud](https://github.com/udistrital/planes_crud)
- [planeacion_cliente](https://github.com/udistrital/planeacion_cliente)
2. El formato de registro de hallazgos en el sistema es: [Formato de registro de hallazgos en el sistema.xlsx](https://github.com/udistrital/planeacion_cliente/files/13922079/Formato.de.registro.de.hallazgos.en.el.sistema.xlsx)
3. Se deben realizar pruebas en el sistema desde el usuario **Planeación** como superusuario y desde los usuarios **Unidad**.
4. Los hallazgos encontrados en el sistema deben registrarse en el formato adjunto con el mayor detalle posible, incluyendo capturas de pantalla, rutas de acceso, usuarios, descripción de lo sucedido y una posible solución.
5. Material de apoyo: [Videotutoriales](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Ent7y0c2P1pKoWEyqizK8xQBShFYJi9Xz9o1a2oL6JjtHw?e=0322n5).

**Sub Tareas**

- [x] Pruebas de funcionamiento del sistema.
- [x] Registro de hallazgos encontrados en el sistema, con el formato adjunto.

**Criterios de aceptación**

- [x] Se evidencia en el formato de registro de hallazgos: bugs, errores, fallas de funcionamiento y posibles mejoras identificadas en las pruebas de funcionamiento del sistema, con gran detalle y una posible solución a cada una.

**Requerimientos**

- [x] Formato de registro de hallazgos.

**Dependencias**

- [x] Completar actividad #806 

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Comment by C0C045** [comment]
# Errores y posibles mejoras de SISGPLAN
## Error 500 al cerrar sesión
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/0cafb93f-a055-4760-863f-655175b3a83b)
**Descripción:** Al intentar cerrar sesión en SISGPLAN se nos indica un error 500 por parte del servidor que no nos permite cerrar sesión y loguear con otra. Por otra parte, se resalta que el tipo de petición afectada es GET, por ende, el error existe dentro de la definición de aquella petición o más allá de esta.
## Carga lenta en peticiones GET
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/0d385881-7cff-4fe5-85ef-e616f2953baf)
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/8e859958-a3b2-4d28-9815-971258a7c5f5)
**Descripción:** En el modulo de Construcción al consultar o construir planes la lista de estos es demorada en cargar, ya que como se ve en la segunda imagen tarda un total de 8.55 segundos en obtener toda la información.

**Posible soluciones:**
- Probablemente esta demora se deba a la ejecución en local, en dónde la velocidad de cada petición y proceso sea afectada por el rendimiento del mismo equipo.
- Por otra parte, es probable que el código de la presente petición llame datos, declare variables o haga procesos innecesarios o muy poco optimizados afectando así el rendimiento de la misma petición.
- En caso contrario, otra posible solución sería limitar la petición a lo que vemos en el front-end, es decir, sí en primera instancia se listan 5 objetos, entonces que la petición llame a los primeros 5 y qué cada vez que el usuario requiera más objetos o buscar uno en concreto; pues realizar otra petición. Por ende, si se sigue esta metodología quitaríamos peso de una sola petición para que este sea equilibrado en varias.

## Formulario con información persistente
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/dff6ba32-134e-4643-bc58-81ad85aefc79)
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/e58cc0ac-fd2d-4cae-882b-bf3414f44db9)
**Descripción:** En el modulo de Banco de proyecto -> Proyectos de Inversión MACRO -> Formulación Proyecto de Inversión existe el formulario presentado en la primera captura, en dónde una vez que se llena; la información diligenciada persiste sin importar la recarga del mismo formulario, generando así una consulta automática qué no permite al usuario diligenciar el formulario desde cero nuevamente.
Por otro lado, el modulo Proyectos de Inversión MACRO esta mal escrito, tal cual como se muestra en la segunda captura.

## Borra una fuente de financiación así se le indique que no
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/a1954b6d-ca53-4f1f-ad17-14f7a431ff15)
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/e78cd1e0-b86c-493c-9c89-7e887c2909dc)
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/89f1b7b3-4520-4921-8c93-fe3ce82436a1)
**Descripción:** Al entrar al modulo de Banco de proyecto -> Proyectos de Inversión MACRO -> Fuentes de Financiación se listan todas la fuentes de financiación disponibles, sin embargo, al intentar eliminar alguna y luego dar click en que no quiere eliminarla, aún así la elimina; tal cual como se muestra en la secuencia de capturas en la parte de arriba.

**Posible soluciones:** Una posible solución es que seguramente el botón de NO tiene como función la misma del botón SI, por ende, ejecuta el mismo procedimiento de inhabilitar la fuente de financiación. Por ende, simplemente sería quitarle tal función ligada al botón.

## Idea de Mejora en el modulo de Evaluación Plan de Acción Anual
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/6c0e7bdc-39d0-4c3c-81c1-fda1e5ee4cde)
**Mejora:** En vez de tener una tabla dinámica de trimestres al lado de otra estática de evaluaciones, es mucho mejor implementar una columna de acción para que de esta manera sea más sencilla la visualización de los trimestres con sus respectivos atributos en una ventana emergente debidamente rotulada.

## Idea de Mejora menú principal
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/dc4388ae-b02e-4ec6-8102-7c6cca0e4557)
**Mejora:** Una vez que en el menú principal tenemos un modulo que a su vez tiene un submodulo que tiene otro submodulo puede ser confuso ubicarse en el menú y tener presente qué modulo es padre de cuál submodulo. Por ende, se me ocurre separar cada submodulo con un background del mismo color, pero mucho más claro. Para que de esta forma sea más fácil para el usuario ubicar en que modulo esta ubicado.

**Comment by EdissonFrancisco** [comment]
Error 500 al cerrar sesión

apoyando lo que el compañero menciona sobre este error esto pasa asi la sesion se cierre automaticamente, al regresal al link de ingreso para el inicio de sesion no permite pasar de aqui, 
![imagen](https://github.com/udistrital/planeacion_cliente/assets/109987805/16274e3c-e565-4243-bba1-2f2d95016462)

y se genera un error de autenticacion con el tocken 
![imagen](https://github.com/udistrital/planeacion_cliente/assets/109987805/87a989d6-472a-452e-bece-72c23802fe76)

**Comment by felimarod** [comment]
Adjunto el **registro de hallazgos**
[Registro.de.hallazgos.en.el.sistema (Martin).xlsx](https://github.com/udistrital/planeacion_cliente/files/13951707/Registro.de.hallazgos.en.el.sistema.Martin.xlsx)

**Comment by C0C045** [comment]
Errores y posibles mejoras de SISGPLA
[Formato.de.registro.de.hallazgos.en.el.sistema.xlsx](https://github.com/udistrital/planeacion_cliente/files/13952162/Formato.de.registro.de.hallazgos.en.el.sistema.xlsx)

**Comment by ccmendezt** [comment]
Adjunto el registro de hallazgos:

[Formato de registro de hallazgos en el sistema.xlsx](https://github.com/udistrital/planeacion_cliente/files/13952607/Formato.de.registro.de.hallazgos.en.el.sistema.xlsx)

**Comment by ccmendezt** [comment]
> Adjunto el registro de hallazgos:
> 
> [Formato de registro de hallazgos en el sistema.xlsx](https://github.com/udistrital/planeacion_cliente/files/13952607/Formato.de.registro.de.hallazgos.en.el.sistema.xlsx)

[Formato.de.registro.de.hallazgos.en.el.sistema.Camilo.xlsx](https://github.com/udistrital/planeacion_cliente/files/13964109/Formato.de.registro.de.hallazgos.en.el.sistema.Camilo.xlsx)

**Comment by a52290451** [comment]
Observaciones @diegobauto 

1. Se requiere mayor detalle en el bug # 3, especificar con que vigencia y plan de acción ocurre, y demás elementos necesarios para replicar el error.
2. Se requiere mayor detalle en el bug # 4, especificar con que vigencia y plan de acción ocurre, y demás elementos necesarios para replicar el error.
3. Se requiere mayor detalle en el bug # 6, especificar con que vigencia, plan de acción y trimestre ocurre. Al realizar algunas pruebas, el contenido carga correctamente.

**Comment by diegobauto** [comment]
@a52290451 

Adjunto el documento con detalles mejorados. Sin embargo, aún estoy en proceso de validación para el bug #3, ya que no se ha replicado en ningún otro caso hasta el momento.
[Registro.de.hallazgos.en.el.sistema.xlsx](https://github.com/udistrital/planeacion_cliente/files/13969156/Registro.de.hallazgos.en.el.sistema.xlsx)

**Comment by a52290451** [comment]
Observaciones @felimarod 

1. Complementar el registro del error # 13, con imágenes y los errores que se causan a raíz de oprimir nuevamente el botón "Formular plan". Además, revisa el por qué se queda en la pantalla y no recarga, hay un fallo en el PUT con estado 400.
2. Agregar mayor información en error # 14, no es posible replicarlo.

**Comment by a52290451** [comment]
@diegobauto 

El bug # 4 se descarta. Lo que pasa es que se trata de un plan ya formulado y avalado por lo que la vista solo permite visualizar la información ya registrada, en ese caso, cuando cargas información de recursos docentes, para ese plan especifico no hay nada registrado por lo que no muestra nada. Lo que si se debe corregir es que debería mostrar un mensaje de alerta especificando eso o la tabla sin campos.

Reformula el error con lo señalado por favor. Gracias.

**Comment by a52290451** [comment]
@diegobauto 

Agrega mayor información al bug # 5, evidencia con imágenes y el flujo que seguiste.

**Comment by Mechaz123** [comment]
@C0C045 

- Por favor verificar de nuevo el Bug #4 ya que se realizó la prueba en ambiente de pruebas y permitió la "eliminación" correcta de la fuente de apropiación.

**Comment by diegobauto** [comment]
@a52290451

Se adjunta las correcciones indicando la solicitud de mejora en el bug # 4 y la adición de evidencias en el bug # 5.
[Registro.de.hallazgos.en.el.sistema.xlsx](https://github.com/udistrital/planeacion_cliente/files/13970637/Registro.de.hallazgos.en.el.sistema.xlsx)

Dado que en las evidencias en el bug # 5 no se ve claramente el problema, y por solicitud, adjunto link del video indicando el flujo: [Link del video](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/dabautistac_udistrital_edu_co/EbW98OC1OmVBnsS1GpUBoNMBSMniUDKJpJkj_R5cWDI7jA?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=HOc2t5)

**Comment by Mechaz123** [comment]
@ccmendezt 

- Por favor adjuntar imagen o evidencia del Bug encontrado en la celda # 8

**Comment by felimarod** [comment]
@a52290451 

> 1. Complementar el registro del error # 13, con imágenes y los errores que se causan a raíz de oprimir nuevamente el botón "Formular plan". Además, revisa el por qué se queda en la pantalla y no recarga, hay un fallo en el PUT con estado 400.

Agrego las observaciones sobre el **error # 13** [Registro.de.hallazgos.en.el.sistema (Martin).xlsx](https://github.com/udistrital/planeacion_cliente/files/13971932/Registro.de.hallazgos.en.el.sistema.Martin.xlsx)


> 2. Agregar mayor información en error # 14, no es posible replicarlo.

Y sobre el **error # 14** yo tampoco logré replicarlo, hice las pruebas de la misma manera pero en esta ocasión si se desplegaba el formulario para seguir ingresando los datos del nuevo plan

Tenía ganas de seguir probando cositas pero se cayó el servicio de autenticación
![image](https://github.com/udistrital/planeacion_cliente/assets/85894335/5c5f8feb-3aa0-4c31-bd58-cb1bee26f427)

**Comment by ccmendezt** [comment]
> @ccmendezt
> 
> * Por favor adjuntar imagen o evidencia del Bug encontrado en la celda # 8

Adjunto Excel actualizado con la evidencia del Bug encontrado en la celda # 8.
[Formato.de.registro.de.hallazgos.en.el.sistema.Camilo.xlsx](https://github.com/udistrital/planeacion_cliente/files/13982693/Formato.de.registro.de.hallazgos.en.el.sistema.Camilo.xlsx)

**Comment by C0C045** [comment]
> Errores y posibles mejoras de SISGPLA [Formato.de.registro.de.hallazgos.en.el.sistema.xlsx](https://github.com/udistrital/planeacion_cliente/files/13952162/Formato.de.registro.de.hallazgos.en.el.sistema.xlsx)

Adjunto actualización del formato "Errores y posibles mejoras de SISGPLAN":
[Formato.de.registro.de.hallazgos.en.el.sistema.xlsx](https://github.com/udistrital/planeacion_cliente/files/13983138/Formato.de.registro.de.hallazgos.en.el.sistema.xlsx)

**Comment by a52290451** [comment]
Adjunto versión preliminar # 2 de [Formato de registro de hallazgos en el sistema.xlsx](https://github.com/udistrital/planeacion_cliente/files/13983790/Formato.de.registro.de.hallazgos.en.el.sistema.xlsx), con asignación de responsable por Bug.

**Comment by a52290451** [comment]
Queda pendiente revisar hallazgos encontrados por @EdissonFrancisco y algunas actualizaciones subidas recientemente.

**Comment by felimarod** [comment]
Acabo de agregar el registro los bugs encontrados después de las correcciones asignadas. Puntualmente son los hallazgos # 14, 24 y 25, el error 14 es el que no se había podido replicar antes. [Documento con los hallazgos](https://docs.google.com/spreadsheets/d/1E4eq-ZDrkm44HwFjN0EdpyJjLcQjY4uZxBKhj5wHnPo/edit?usp=sharing)

**Comment by milo19980525** [comment]
> https://udistritaleduco-my.sharepoint.com/:x:/g/personal/efaceror_udistrital_edu_co/EfYcmxF_3W5JusFLp1obQToB8ObRI2r26J9DeR8oxHoinA?e=y2MkCS
> 
> link a Registro.de.hallazgos.en.el.sistema

@EdissonFrancisco Respecto al hallazgo con id número 8, se debe especificar sobre cuales elementos no se habilita la opción de editar, dado que se probó y con algunos elementos si se habilita el guardado y se valida la persistencia en BD.

**Comment by a52290451** [comment]
Revisión de nuevos Hallazgos @felimarod :

1. Para el error # 16, no es posible limitar el sistema para que no acepte un % superior a 100 ya que esto es total autonomía de los usuarios al crear las plantillas. Se debe estudiar el caso y ver con el usuario si es posible limitar el campo para evitar errores.
2. Error # 18 aprobado.
3. Error # 19 aprobado.
4. Error # 20 aprobado.
5. Error # 21 aprobado.
6. En el error # 22, para realizar observaciones en la identificación de recursos docentes, se tiene el campo "observación" al final de la tabla.

![image](https://github.com/udistrital/planeacion_cliente/assets/36229498/2c79a8a9-9089-475d-9664-28b05eca31da)

7. Error # 23, no fue posible replicar el error.
8. Error # 14 aprobado.
9. Error # 24 ya se encuentra agregado.
10. Error # 25 aprobado.
