### ISSUE TITLE
Planeación SISGPLAN

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#808]
Se requiere adjuntar toda la documentación asociada a las actividades de gerencia y planeación de SISGPLAN.

**Especificaciones técnicas**
1. No aplica.

**Sub Tareas**

- [x] Listado de elementos necesarios para la gerencia y planeación de SISGPLAN.
- [x] Cronograma de actividades SISGPLAN.
- [x] Limitaciones del proyecto (que se incluye y que se excluye en cada requerimiento).
- [x] Identificación de dependencias entre requerimientos.
- [x] Planeación de reuniones con usuarios.
- [x] Presentación de Gerencia y Planeación de Actividades de SISGPLAN.

**Criterios de aceptación**

- [x] Se entrega un listado de todos los elementos necesarios para realizar una adecuada gerencia y planeación de actividades en SISGPLAN.
- [x] El cronograma de actividades contempla todos los hitos y tareas que serán contemplados en la fase de desarrollo del proyecto, identificando tiempos, recursos, prioridades y demás elementos necesarios.
- [x] Se evidencian limites claros en la presentación de los requerimientos, identificando que elementos serán incluidos y excluidos en cada uno.
- [x] Se detallan las dependencias entre requerimientos y se toman en cuenta para la priorización de los mismos.
- [x] Se especifica la forma, tipo, horarios, tiempo y documentos necesarios para realizar reuniones periódicas con los usuarios del sistema.
- [x] En una presentación, se detallan todos los elementos anteriormente mencionados.

**Requerimientos**

- [x] Análisis de requerimientos.
- [x] Capacitación en SISGPLAN

**Dependencias**

- No presenta.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Comment by a52290451** [comment]
Material de Apoyo: 

[Listado de elementos necesarios para la gerencia y planeación de SISGPLAN.docx](https://github.com/udistrital/planeacion_cliente/files/13941603/Listado.de.elementos.necesarios.para.la.gerencia.y.planeacion.de.SISGPLAN.docx)

**Comment by a52290451** [comment]
Ejemplo de historias de Usuario:

https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EcIOxeegldJAh6G041Mxj0wBLim5Jj8uI1bFpakKUmK6cQ?e=lWiPiQ

**Comment by a52290451** [comment]
@BikerMetalHead Por favor subir actividades de planeación al issue para seguimiento

**Comment by BikerMetalHead** [comment]
Documento de borrador historias de usuarios iniciales: [enlace documento ](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ERnXVlOzYglGiQxvKqRZ7SkBXK6kdFyl6mB6wnqyf3Kpag?e=yfxDUb)

**Comment by BikerMetalHead** [comment]
Documento presentación de caso de negocio planeación SISGPLAN: [Enlace documento]([url](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EUjeooVzQltJorPOIZ1NIIMBc4yXUXkq7Cx8De4syB5KGA?e=DtVOYk))

**Comment by BikerMetalHead** [comment]
Documentos de reuniones: [reunión diciembre ](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MGIzOTE3ODgtYTg0Zi00N2M2LWE2ZDctYmE3YjkwNmQ2Nzcz%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%2229f64d73-8b12-4c53-a9f3-1c223397a229%22%7d)
[SISGPLAN EMPALME](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MGVmZDk2YjktOWYyNy00ZmIyLWFiZjItOGYxMGJlMzNmMjUz%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%220682e8de-4c08-41cb-8451-60d5505efa7b%22%7d)

**Comment by BikerMetalHead** [comment]
Documentos reuniones de enero:

Reunión equipo [SISGPLAN](https://teams.microsoft.com/l/meetup-join/19%3ameeting_YmFjNThhZDgtM2NmMy00NTc0LWI4NWUtN2M3ZmIzYTdkOTg0%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%22b989c328-89fa-4486-abfe-df75fdd723ba%22%7d):

**Comment by BikerMetalHead** [comment]
Reuniones de capacitación:
reuniones capacitaciones del sistema: [Documento](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MjZmNzFiMDctNjQwMi00NTY2LWJmMDctM2I0YmJkYzhjNzQ3%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%22f14a0609-8ba1-4ca2-b5ef-fdf01e12f0c9%22%7d)
[Documento 3 ](https://teams.microsoft.com/l/meetup-join/19%3ameeting_OTI4OGRmZTItMjg0ZC00NjI1LTkwYTYtOTc1ZTk1YWUwMTY1%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%228ae12514-62fc-4134-b546-49cc078c9f00%22%7d)

reuniones de planeación de historias de usuario: [Documento ](https://teams.microsoft.com/l/meetup-join/19%3ameeting_NGRmOTQwYTYtMjQ0My00NmIzLWI3ZTEtNzdhMjYxYjg3MTNm%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%228ae12514-62fc-4134-b546-49cc078c9f00%22%7d)

**Comment by BikerMetalHead** [comment]
Para la actividad de presentación de equipo de trabajo con la unidad de OPAC: [Documento ](https://teams.microsoft.com/l/meetup-join/19%3ameeting_YmFjNThhZDgtM2NmMy00NTc0LWI4NWUtN2M3ZmIzYTdkOTg0%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%22b989c328-89fa-4486-abfe-df75fdd723ba%22%7d)

**Comment by BikerMetalHead** [comment]
@a52290451 adjunto los documentos de historias de usuario y estimación SISGPLAN V2:
[HISTORIAS DE USUARIO](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ERnXVlOzYglGiQxvKqRZ7SkBXK6kdFyl6mB6wnqyf3Kpag?e=0rksLc)
[ESTIMACION SISGPLAN](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ETpuknGc7EFMoacQZaKHZk8Bic6TkdQah1aceajK3mJ0dA?e=IjfSsE)

**Comment by milo19980525** [comment]
@BikerMetalHead por favor completar tarea relacionada con "Presentación de Gerencia y Planeación de Actividades de SISGPLAN", la cual va relacionada con los otros elementos de las subtareas:

- [x] Listado de elementos necesarios para la gerencia y planeación de SISGPLAN.
- [ ] Cronograma de actividades SISGPLAN.
- [ ] Limitaciones del proyecto (que se incluye y que se excluye en cada requerimiento).
- [ ] Identificación de dependencias entre requerimientos.
- [ ] Planeación de reuniones con usuarios.
- [ ] Presentación de Gerencia y Planeación de Actividades de SISGPLAN.

**Comment by norbeydanilo** [comment]
> @BikerMetalHead por favor completar tarea relacionada con "Presentación de Gerencia y Planeación de Actividades de SISGPLAN", la cual va relacionada con los otros elementos de las subtareas:
> 
> * [x]  Listado de elementos necesarios para la gerencia y planeación de SISGPLAN.
> * [ ]  Cronograma de actividades SISGPLAN.
> * [ ]  Limitaciones del proyecto (que se incluye y que se excluye en cada requerimiento).
> * [ ]  Identificación de dependencias entre requerimientos.
> * [ ]  Planeación de reuniones con usuarios.
> * [ ]  Presentación de Gerencia y Planeación de Actividades de SISGPLAN.

Con prioridad trabajar sobre el cronograma, pensando en lo ya establecido, realizado y los ajustes proyectados futuros (hitos); así como en la presentación. Esto considerando la proximidad de la reunión con Planeación. Gracias

**Comment by norbeydanilo** [comment]
Subir la Presentación para su revisin antes del 17/02/2024 @BikerMetalHead

**Comment by BikerMetalHead** [comment]
Siguiendo la instrucción dada, subo el esqueleto y plantilla de presentación en borrador. La presentación aún se encuentra en **_construcción._** Igualmente, se puede la dirección planeada para la presentación del proyecto, siguiendo estos pasos: 
- Alcance del Proyecto
- Planificación del Tiempo
- Recursos Humanos: Equipo De Desarrollo 
- . Contacto con usuarios
- Proceso de seguimiento a avance del proyecto 
- Gestión De La Información 

[presentacion_de_proeycto](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/ESDizdjaF-5Ls5qpw_4Z7jwBw55Pl8qAmF0wmSIsvV1OIw?e=9NjMsR)

**Comment by BikerMetalHead** [comment]
se realizan modificaciones sobre la presentación. Siguiendo instrucciones de la reunión. Adjunto link:
[presentacion_de_proyecto](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/ESDizdjaF-5Ls5qpw_4Z7jwBw55Pl8qAmF0wmSIsvV1OIw?e=9NjMsR)

**Comment by BikerMetalHead** [comment]
Se añade el cronograma como se solicitó. (en construcción) 
[cronograma](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EYqsHcS3tTBJhyJpXNIpbdYBJD5f08TnBooWAnvj9ys6sQ?e=5jUpmf)

**Comment by BikerMetalHead** [comment]
Se actualiza cronograma a dia de hoy 01-04-2024
[cronograma](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EYqsHcS3tTBJhyJpXNIpbdYBJD5f08TnBooWAnvj9ys6sQ?e=5jUpmf)
