### ISSUE TITLE
Solución de Errores y Bugs en SISGPLAN

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#809]
Se requiere realizar la corrección de Errores y Bugs de SISGPLAN encontrados en #807, de acuerdo con las pautas establecidas por el líder técnico. Se deben realizar las modificaciones correspondientes en ambiente local, realizar pruebas funcionales y subir el código en una rama feature.

**Especificaciones técnicas**

1. Las APIs y el cliente asociadas a SISGPLAN son: 
- [planeacion_mid](https://github.com/udistrital/planeacion_mid)
- [planes_crud](https://github.com/udistrital/planes_crud)
- [planeacion_cliente](https://github.com/udistrital/planeacion_cliente)
2. El formato de pruebas funcionales es: [Formato de registro de hallazgos en el sistema.xlsx](https://github.com/udistrital/planeacion_cliente/files/13922079/Formato.de.registro.de.hallazgos.en.el.sistema.xlsx)
3. Se deben realizar pruebas en el sistema con los usuarios implicados, cubriendo el flujo de funcionamiento del error tratado.
4. Descripción de [Errores y bugs encontrados en SISGPLAN - Parte 1](https://github.com/udistrital/planeacion_cliente/files/13992491/Formato.de.registro.de.hallazgos.en.el.sistema.xlsx).

La asignación de errores se encuentra de la siguiente forma:

1. @C0C045: 1, 5 y 10.
2. @diegobauto: 2, 3 y 14.
3. @felimarod: 4, 6 y 15.
4. @EdissonFrancisco: 7, 8 y 11.
5. @ccmendezt: 9, 12 y 13.

**Sub Tareas**

- [x] Corrección de Bugs en sistema SISGPLAN
- [x] Pruebas funcionales de corrección de Bugs.

**Criterios de aceptación**

- [x] El sistema presenta un correcto funcionamiento en los puntos de fallo señalados en el documento guía.

**Requerimientos**

- [x] Descripción de errores y bugs encontrados en el sistema.

**Dependencias**

- [x] Completar actividad #807 .

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Comment by felimarod** [comment]
Se agregan las soluciones realizadas a los diferentes bugs [Soluciones Felipe.xlsx](https://github.com/udistrital/planeacion_cliente/files/13996182/Soluciones.Felipe.xlsx)
Los commits los subí en la rama [feature/bugs_felipe](https://github.com/udistrital/planeacion_cliente/commits/feature/bugs_felipe/)

**Comment by C0C045** [comment]
Bugs solucionados en la rama [feature/BugsFixedSteven](https://github.com/udistrital/planeacion_cliente/tree/feature/BugsFixedSteven)
Formato de Bugs solucionados: [Bugs solucionados Steven.xlsx](https://github.com/udistrital/planeacion_cliente/files/13999491/Bugs.solucionados.Steven.xlsx)

**Comment by ccmendezt** [comment]
## Solución de hallazgos asignados
- **Soluciones a los hallazgos asignados:** [Pruebas funcionales corrección de Bugs - Parte 1 - Cristian Mendez.xlsx](https://github.com/udistrital/planeacion_cliente/files/14015371/Pruebas.funcionales.correccion.de.Bugs.-.Parte.1.xlsx)


## Los commits se subieron en
- **Cliente (planeacion_cliente):** [feature/BugsFixedCristian](https://github.com/udistrital/planeacion_cliente/tree/feature/BugsFixedCristian)
- **API MID (planeacion_mid):** [feature/BugsFixedCristian](https://github.com/udistrital/planeacion_mid/tree/feature/BugsFixedCristian)

**Comment by diegobauto** [comment]
Bugs solucionados en la rama: [feature/bugs_diego](https://github.com/udistrital/planeacion_cliente/tree/feature/bugs_diego)
Observaciones adicionales: [Tareas OATI.xlsx](https://github.com/udistrital/planeacion_cliente/files/14015697/Tareas.OATI.xlsx)

**Comment by milo19980525** [comment]
> ## Solución de hallazgos asignados
> * **Soluciones a los hallazgos asignados:** [Pruebas funcionales corrección de Bugs - Parte 1 - Cristian Mendez.xlsx](https://github.com/udistrital/planeacion_cliente/files/14015371/Pruebas.funcionales.correccion.de.Bugs.-.Parte.1.xlsx)
> 
> ## Los commits se subieron en
> * **Cliente (planeacion_cliente):** [feature/BugsFixedCristian](https://github.com/udistrital/planeacion_cliente/tree/feature/BugsFixedCristian)
> * **API MID (planeacion_mid):** [feature/BugsFixedCristian](https://github.com/udistrital/planeacion_mid/tree/feature/BugsFixedCristian)

Revisión de bug número 9, el error en pruebas no se evidencia.

**Comment by EdissonFrancisco** [comment]
Bugs solucionados 7 y 11. 

queda pendiente validar el 8.

en la rama: [https://github.com/udistrital/planeacion_cliente/tree/feature/fixedEdisson](url)

**Comment by a52290451** [comment]
@EdissonFrancisco por favor subir pruebas funcionales de los errores corregidos.

**Comment by ccmendezt** [comment]
PR asociado a issue: https://github.com/udistrital/planeacion_mid/pull/475
