### ISSUE TITLE
Implementación de componente para la inclusión de identificación de recursos para planes de acción de funcionamiento

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#81]
Se debe implementar el componenta para la asignación de identificación de recursos con el análisis realizada en la issue #80 , el componente debe cumplir con los siguientes requerimientos:

- [x] Construir el componente teniendo en cuenta el excel definido por la oficina de planeación
[Formato Formulación Plan de Acción 2022 (4) (3).xlsx](https://github.com/udistrital/planeacion_cliente/files/7354689/Formato.Formulacion.Plan.de.Accion.2022.4.3.xlsx)

- [x] Implementar flujo para mostrar el componte al presionar "Agregar identificación de recursos" y se active una card para la visualización, se debe controlar que al menos debe existir al menos una actividad registrada en el plan de trabajo.
![image](https://user-images.githubusercontent.com/43799065/137522106-7c807188-1a26-402b-9920-f85adff7516a.png)

- [x] Realizar pruebas de funcionamiento del componente, agregar fila, select y calculo de totales 
- [x] Diseñar y crear la funcionalidad para relacionar las actividades previamente creadas con cada recursos

**Comment by ndmc98** [comment]
Se da inicio a la issue y desarrollo del componente el día 20/10/2021

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
