### ISSUE TITLE
Solución de Errores y Bugs en SISGPLAN - PARTE 2

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#810]
Se requiere realizar la corrección de Errores y Bugs de SISGPLAN encontrados en #807, de acuerdo con las pautas establecidas por el líder técnico. Se deben realizar las modificaciones correspondientes en ambiente local, realizar pruebas funcionales y subir el código en una rama feature.

**Especificaciones técnicas**

1. Las APIs y el cliente asociadas a SISGPLAN son: 
- [planeacion_mid](https://github.com/udistrital/planeacion_mid)
- [planes_crud](https://github.com/udistrital/planes_crud)
- [planeacion_cliente](https://github.com/udistrital/planeacion_cliente)
2. El formato de pruebas funcionales es: [Formato de registro de hallazgos en el sistema.xlsx](https://github.com/udistrital/planeacion_cliente/files/13922079/Formato.de.registro.de.hallazgos.en.el.sistema.xlsx)
3. Se deben realizar pruebas en el sistema con los usuarios implicados, cubriendo el flujo de funcionamiento del error tratado.
4. Descripción de [Errores y bugs encontrados en SISGPLAN - Parte 2](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EQ_B42dbFmBFiYf9v5PAkdUBTbv1CTz0g5ZYCVSd_BG5RQ?e=yS4J9F).

La asignación de errores se encuentra de la siguiente forma:

1. @C0C045: 1 y 5
2. @diegobauto: 6 y 8
3. @felimarod: 3 y 7
4. @EdissonFrancisco: 9, 10 y 11 
5. @ccmendezt: 2 y 4

**Sub Tareas**

- [x] Corrección de Bugs en sistema SISGPLAN
- [x] Pruebas funcionales de corrección de Bugs.

**Criterios de aceptación**

- [x] El sistema presenta un correcto funcionamiento en los puntos de fallo señalados en el documento guía.

**Requerimientos**

- [x] Descripción de errores y bugs encontrados en el sistema.

**Dependencias**

- [x] Completar actividad #807 .

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by ccmendezt** [comment]
## Solución de hallazgos asignados
- **Soluciones a los hallazgos asignados:** [Pruebas funcionales corrección de Bugs - Parte 2 - Cristian Mendez.xlsx](https://github.com/udistrital/planeacion_cliente/files/14054862/Pruebas.funcionales.correccion.de.Bugs.-.Parte.2.xlsx)



## Los commits se subieron en
- **Cliente (planeacion_cliente):** [feature/BugsFixedCristian](https://github.com/udistrital/planeacion_cliente/tree/feature/BugsFixedCristian)
- **API CRUD (planes_crud):** [feature/BugsFixedCristian](https://github.com/udistrital/planes_crud/tree/feature/BugsFixedCristian)

**Comment by diegobauto** [comment]
Bugs solucionados en la rama: [feature/bugs_diego](https://github.com/udistrital/planeacion_cliente/tree/feature/bugs_diego)
Observaciones adicionales (Hoja2): [Tareas.xlsx](https://github.com/udistrital/planeacion_cliente/files/14059453/Tareas.PARTE.2.xlsx)

**Comment by C0C045** [comment]
Bugs solucionados en la rama [feature/BugsFixedSteven](https://github.com/udistrital/planeacion_cliente/tree/feature/BugsFixedSteven)
Formato de Bugs solucionados: [Bugs solucionados Steven PARTE 2.xlsx](https://github.com/udistrital/planeacion_cliente/files/14060002/Bugs.solucionados.Steven.PARTE.2.xlsx)

**Comment by felimarod** [comment]
Bugs solucionados en la rama: [feature/bugs_felipe](https://github.com/udistrital/planeacion_cliente/commits/feature/bugs_felipe/)
Formato de solución y nuevos bugs encontrados: [Soluciones Felipe - Parte 2](https://docs.google.com/spreadsheets/d/1xdqEQZzXiKImw-soVmgEv4thCkppo75el3hFeVKrm5k/edit?usp=sharing)

**Comment by ccmendezt** [comment]
PR asociado a issue: https://github.com/udistrital/planes_crud/pull/86

**Comment by EdissonFrancisco** [comment]
- Bugs solucionados en la rama: [https://github.com/udistrital/planeacion_cliente/tree/feature/fixedEdisson](https://github.com/udistrital/planeacion_cliente/issues/url)

- Formato de solución:  [https://udistritaleduco-my.sharepoint.com/:x:/g/personal/efaceror_udistrital_edu_co/EWldDB1pZYlMgpyKGE5Jx9IBHZ-1lfLVXnNYuF9_v7jF4g?e=fB46FG](url)

**Comment by diegobauto** [comment]
@a52290451 

Adjunto documento con la revisión de los bugs realizados: [Verificación de bugs.ods](https://github.com/udistrital/planeacion_cliente/files/14088403/Verificacion.de.bugs.en.ambiente.de.pruebas.ods)

Por otra parte, solicito el favor de realizar la revisión del pull request. 
Muchas gracias.

**Comment by ccmendezt** [comment]
## Pruebas funcionales - Ambiente de Pruebas
- Adjunto formato de pruebas funcionales en ambiente de pruebas: [**Pruebas funcionales Corrección de Hallazgos - Ambiente de pruebas.xlsx**](https://github.com/udistrital/planeacion_cliente/files/14089678/Pruebas.funcionales.Correccion.de.Hallazgos.-.Ambiente.de.pruebas.xlsx)

**Comment by felimarod** [comment]
# Pruebas funcionales
Adjunto la verificación de los bugs solucionados en la PR #827 
- [Soluciones - Parte 1](https://docs.google.com/spreadsheets/d/1kQGVBxb8oYXbnz1k2W-YuDm-G2KRexCVOsJ9Oz70VAs/edit?usp=sharing)
- [Soluciones - Parte 2](https://docs.google.com/spreadsheets/d/1xdqEQZzXiKImw-soVmgEv4thCkppo75el3hFeVKrm5k/edit?usp=sharing)

**Comment by C0C045** [comment]
Verificación de bugs solucionados en el PR #826 :
- [Bugs solucionados Steven.xlsx](https://github.com/udistrital/planeacion_cliente/files/14091527/Bugs.solucionados.Steven.xlsx)

Nuevos bugs encontrados en el proceso de solución:
- [Bugs Encontrados.xlsx](https://github.com/udistrital/planeacion_cliente/files/14091534/Bugs.Encontrados.xlsx)

**Comment by a52290451** [comment]
@EdissonFrancisco Por favor subir corrección de último bug y pruebas asociadas para finalización de Issue.

**Comment by EdissonFrancisco** [comment]
Realizo correcion de bug faltante y subo las pruebas de funcionamiento en el link del docuento que estoy manejando.

Link Pruebas: https://udistritaleduco-my.sharepoint.com/:x:/g/personal/efaceror_udistrital_edu_co/EWldDB1pZYlMgpyKGE5Jx9IBt8XVwyMNY34F44NZKvVQAA?e=4JOLzk

**Comment by a52290451** [comment]
@EdissonFrancisco actualizar estado de la actividad.

**Comment by EdissonFrancisco** [comment]
se realiza validacion del bug y se hacen pruebas 

mensaje cuando no hay datos
![imagen](https://github.com/udistrital/planeacion_cliente/assets/109987805/3b6ce492-1200-4b88-8d6e-a99f7e00c19a)

mensaje cuando no hay actividades
![imagen](https://github.com/udistrital/planeacion_cliente/assets/109987805/c7226106-4c58-4c09-850d-f5eef0902be6)

**Comment by a52290451** [comment]
@EdissonFrancisco al Subir el commit a pruebas con los cambios realizados, asociados al bug solucionado, se encontraron diversos problemas en la solución. **Se debe reevaluar y ajustar.**

**Comment by EdissonFrancisco** [comment]
se realiza ajuste al bug y se muestra de esta forma 
al cargar la informacion tiene la ventana de load
![imagen](https://github.com/udistrital/planeacion_cliente/assets/109987805/178a113e-2f17-4a6b-8d3c-59e211fff8d4)
si tiene datos se muestran los campos corespondientes.
![imagen](https://github.com/udistrital/planeacion_cliente/assets/109987805/9eb80cc8-419c-4a37-a656-8fd422fc723c)
si no hay datos se muestra esta ventana con mensaje
![imagen](https://github.com/udistrital/planeacion_cliente/assets/109987805/ff73d175-5d03-400a-a142-b1bd98e1414a)
si hay datos pero la busqueda del plan no tiene sale este mensaje
![imagen](https://github.com/udistrital/planeacion_cliente/assets/109987805/55c5a961-1356-4162-be81-f86ef63d11f0)
en cada uno de los casos la ventana con informacion se recarga y se muestran o no los datos dependiendo del error y lo que se necesita (en este caso no hay datos).
![imagen](https://github.com/udistrital/planeacion_cliente/assets/109987805/e1eef445-088b-43cc-b156-48dbc603ebcb)

**Comment by a52290451** [comment]
Se realiza despliegue en ambiente de pruebas.
