### ISSUE TITLE
HU1 - 1 Definir fechas procesos formulación y seguimiento

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#812]
Se requiere implementar [HU1 - 1](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/resanchezc_udistrital_edu_co/EYc_4k5TayBEgwWaq2wQt9UBOxFJ-y2a-Z_lj5bsjlDkUQ?wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1706125306937&web=1), relacionada con la asignación de fechas para formulación y seguimiento de un nuevo proyecto.

Descripción: **Como** rol planeación **quiero** tener la capacidad de definir fechas específicas para los procesos de formulación y seguimiento para establecer fechas distintas **para** cada aspecto del proceso de planeación.

**Especificaciones técnicas**

- Actualmente el desarrollo del aplicativo se encuentra estabilizado en ambiente develop (Cliente, mid y crud).
- Se requiere validar el funcionamiento actual de este módulo y escoger una opción que permita reutilizar el código empleado.

**Sub Tareas**

- [x] Adicionar en el siguiente orden los filtros para asignar las fechas asociadas a proyectos y planes: 
- Vigencia (ya se encuentra)
- Proceso (ya se encuentra)
- Unidad
- Plan o proyecto
- [x] En el filtro de unidad deben traerse en un select todas las unidades y debe haber un checkbox para seleccionar todas las unidades. 
- [x] En el filtro de plan o proyecto deben traerse todos los proyectos y debe haber un checkbox para seleccionar todos los estos.
- [x] El botón limpiar debe vaciar todas las selecciones efectuadas por el usuario previamente.
- [x] El botón de guardado debe validar que se escogan todas las unidades y proyectos.

**Criterios de aceptación**

- [x] (Pendiente de rony).
- [x] (Pendiente de rony).
- [x] (Pendiente de rony).
- [x] (Pendiente de rony).

**Requerimientos**

- [x] Ninguno.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by ccmendezt** [comment]
## Evidencias - Avance HU1
- Se agregaron los respectivos botones para mostrar las tablas de las **unidades** y **planes/proyectos**:
![Botones](https://github.com/udistrital/planeacion_cliente/assets/82072560/7376ccb4-7126-4b85-af59-5fa789f85b2f)

- Una vez diligenciado el formulario con la vigencia y proceso (formulación/seguimiento) se habilitan los botones:
![Diligenciamiento](https://github.com/udistrital/planeacion_cliente/assets/82072560/449babd0-ec77-468f-9355-26466d3c9515)

- El botón de _**unidades a las que desea asignar el proceso**_ está completamente funcional mostrando la tabla:
![Cargando_Unidades](https://github.com/udistrital/planeacion_cliente/assets/82072560/75c20bf5-2ecd-4efb-87d1-f9579488158b)
![Tabla_Unidades](https://github.com/udistrital/planeacion_cliente/assets/82072560/a60addf2-30ba-4bd5-acaa-4c3afc956892)
![Unidad_Seleccionada](https://github.com/udistrital/planeacion_cliente/assets/82072560/e4ad221a-edab-469f-9109-df6227158ebc)


- El botón **_Seleccionar todos_** permite seleccionar todas las unidades para asignarlas al proceso y la vigencia seleccionada.
![Seleccionar_Todos](https://github.com/udistrital/planeacion_cliente/assets/82072560/dba92c28-52c2-44d6-bcaf-22c77bff7192)

- El botón **_Borrar selección_** permite deseleccionar todas las unidades para el proceso y la vigencia seleccionada.
![Borrar_Selección](https://github.com/udistrital/planeacion_cliente/assets/82072560/f1b2e363-aa81-465b-ad65-186fefd6a406)

- El botón de _**Planes/proyectos a las que desea asignar el proceso**_ está completamente funcional mostrando la tabla:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/0c658d63-cf37-491a-937b-55377148109a)
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/d13725b5-1feb-4404-889b-1dc0cc502442)

**Notas importantes:**
  **i.** Se reutilizó el componente de **_listar-plan_** para mostrar los planes/proyectos en el componente _**habilitar_reporte**_.
  **ii.** Aún se está trabajando en la funcionalidad para seleccionar los planes/proyectos que el usuario desee.
  **iii.** Falta crear funcionalidad para seleccionar/borrar selección de los planes/proyectos.
  **iv.** Se está mejorando el ancho de las columnas en la tabla de planes/proyectos ya que está desproporcionado para algunos casos.

**Comment by ccmendezt** [comment]
## Evidencias - Avance HU1
### 02/02/2024 - 9:50 am

Como se mostró en el comentario anterior, el botón listar los planes/proyectos ya estaba en funcionamiento, sin embargo, se realizaron algunas mejoras al componente:

- Se agregó la funcionalidad para permitir **_seleccionar un plan/proyecto_** al proceso y vigencia seleccionada:
![Seleccionar_plan](https://github.com/udistrital/planeacion_cliente/assets/82072560/6061ce56-42b3-4a89-b7a2-af5b91a07a7a)

- Se agregó la funcionalidad al botón **_Seleccionar todos_** que permite seleccionar todos los planes/proyectos para asignarlos al proceso y la vigencia seleccionada:
![Seleccionar_Todos](https://github.com/udistrital/planeacion_cliente/assets/82072560/a6420b99-ef3d-4738-8223-fd742902e021)

- Se agregó la funcionalidad al botón **_Borrar selección_** que permite eliminar la selección de todos los planes/proyectos para el proceso y la vigencia seleccionada:
![Borrar_Seleccion](https://github.com/udistrital/planeacion_cliente/assets/82072560/7924c782-ca99-41e5-b712-805b13881ca5)

- Se ajustó el ancho de las columnas en la tabla _**listar-plan**_ para mejorar su visualización.
    **Antes:**
![AnchoCol_Antes](https://github.com/udistrital/planeacion_cliente/assets/82072560/d13725b5-1feb-4404-889b-1dc0cc502442)

   **Después:**
![AnchoCol_Despues](https://github.com/udistrital/planeacion_cliente/assets/82072560/99dd6cd0-4161-4bbc-b13e-4b5fa07b4bfd)


- El componente _**listar-plan**_ incluye dentro de su tabla un input de búsqueda totalmente funcional:
![Buscar_Plan](https://github.com/udistrital/planeacion_cliente/assets/82072560/cf380dee-8f75-42f4-a706-4fefe357f56c)

- Basándose en el input de búsqueda de _**listar-plan**_, se agregó la misma funcionalidad al componente **_tabla-unidades_**:
![Buscar_Unidad](https://github.com/udistrital/planeacion_cliente/assets/82072560/a4b41675-5b55-4a60-8798-414e3eb3d463)

- El botón de _**limpiar**_ vacía correctamente todas las selecciones hechas por el usuario:
![Boton_Limpiar](https://github.com/udistrital/planeacion_cliente/assets/82072560/b940dbae-f898-4af8-bbfa-1ec8fc88bc6b)


**Notas importantes:**
  **i.** Se están evaluando las validaciones que se deben hacer al momento de elegir o no unidades y/o planes/proyectos.
  **ii.** Se está revisando cómo realizar la petición al endpoint para almacenar los datos de las unidades y/o proyectos de interés asociados a una vigencia y proceso establecido.
  **iii.** Falta ajustar algunos aspectos estéticos de la tabla de planes/proyectos.

**Comment by ccmendezt** [comment]
## Evidencias - Avance HU1
### 02/02/2024 - 4:00 pm

- Los datos de las unidades y planes seleccionados por el usuario ya persisten en la base de datos para el proceso de **Formulación** en los **Planes de Acción de Funcionamiento**:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/69413073-34a5-4010-93b7-e957c1796d17)
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/1467ded8-4848-481c-9189-663da194b32f)

- Los datos de las unidades y planes seleccionados por el usuario ya persisten en la base de datos para el proceso de **Seguimiento** en los **Planes de Acción de Funcionamiento**:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/9661acc7-52ad-4889-b3c4-263ee0316bec)
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/01eccfc6-e4d1-4f4b-bbb8-cdb5b386adf3)
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/f95d71e4-1d3b-4966-8132-e8ebd0640014)
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/3a8f2dc3-2bbf-4496-869f-6c5e72e2459a)




**Notas importantes:**
  **i.** El _**periodo_id**_ mostrado en el registro para el proceso de formulación hace referencia a este registro de **parametros_crud**:
![periodo_id_46](https://github.com/udistrital/planeacion_cliente/assets/82072560/376957ba-e6c4-44cd-b7fa-2b2a66b654cc)

**Comment by ccmendezt** [comment]
## Pull Request asociados al issue.

**Planes_crud:** https://github.com/udistrital/planes_crud/pull/90
**Planeacion_mid:** https://github.com/udistrital/planeacion_mid/pull/478

**Comment by milo19980525** [comment]
@ccmendezt Perfecto, queda pendiente el diagrama de base de datos actualizado para dar por finalizado el issue.

**Comment by ccmendezt** [comment]
## Evidencias - Avance HU1
### 06/02/2024 - 5:45 pm

- Se actualizó el modelo de datos agregándole el campo _**planes_interes**_ a la tabla **seguimiento_periodo**:
![planes_crud](https://github.com/udistrital/planeacion_cliente/assets/82072560/77b30473-244d-4f54-be49-ec3034f37f19)

- Se subió a la carpeta pactada tal como se estableció con el SM/Líder técnico:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/93a75f42-ed63-4d5a-8431-36ead3971293)
