### ISSUE TITLE
1 - 1 Creación de controlador - tabla general de resumen para el rol de planeación modulo de formulación de planes de acción de funcionamiento

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#813]
Se requiere realizar la creación de un controlador en planeacion_mid que consulte la información de **todos los planes de acción existentes**, tanto **activos como inactivos**, en fase de **formulación**, y los devuelva como respuesta de la petición.

**Especificaciones técnicas**

1. La petición realizada al controlador no tiene parámetros adicionales (GetAll).
2. Los parámetros que debe recopilar y devolver el controlador por cada registro son:
- Unidad Académica y / o Administrativa (Nombre)
- Vigencia 
- Plan de acción (Nombre)
- Estado del plan de acción

**Sub Tareas**

- [x] Desarrollo de controlador en planeacion_mid.
- [x] Desarrollo de lógica de controlador en Helpers.

**Criterios de aceptación**

- [x] Planeación mid permite realizar la consulta de todos los planes de acción que se encuentren registrados en el sistema en fase de formulación, sin importar su estado, vigencia o unidad académica y / o administrativa.

**Requerimientos**

- No presenta.

**Dependencias**

- planes_crud.
- planeacion_mid.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by felimarod** [comment]
Falta documentación sobre el parámetro "Estado del plan de acción"
¿Este sale de el estado de seguimiento?

**Comment by a52290451** [comment]
El parámetro **Estado del plan de acción** que contempla los estados en formulación, se obtiene de la tabla **estado-plan**, como se muestra a continuación:

![image](https://github.com/udistrital/planeacion_cliente/assets/36229498/1e0b3bac-3bde-496a-9730-cb76c9557e59)

**Comment by felimarod** [comment]
Versión preliminar del endpoint, agregue la rama a la issue para su revisión

![image](https://github.com/udistrital/planeacion_cliente/assets/85894335/47fee970-d2ae-473c-b8b4-e5fbcb3740ee)

**Comment by a52290451** [comment]
Muy bien, por favor implementar pruebas funcionales, cargar formato en ONE DRIVE y adjuntar link.

**Comment by felimarod** [comment]
Quedo con los filtros de tipos "Plan" y "Plan de acción de funcionamiento"

Aquí está el [formato de pruebas](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EbgRUdlsK7NGjyjFogtWxkkBjVLnXEN7NZoZDrR4lIHzlQ?e=ApEPed)

**Comment by a52290451** [comment]
Se requiere complementar archivo de pruebas funcionales probando otro tipo de casos, como el control de errores y demás que se consideren necesarias

**Comment by felimarod** [comment]
Ya quedó actualizado

**Comment by a52290451** [comment]
Para despliegue en ambiente de pruebas, se requiere realizar actualización de SWAGGER. @a52290451

**Comment by a52290451** [comment]
Se realiza merge con develop:

https://github.com/udistrital/planeacion_mid/pull/477

**Nota:** para próximos PRs y Commits, se debe manejar el sistema de etiquetas en titulos y descripciones tal como se menciona en los lineamientos.

![image](https://github.com/udistrital/planeacion_cliente/assets/36229498/33adbfe6-281d-4363-a14c-7ffead964361)
