### ISSUE TITLE
1 - 2 Creación de componente (cliente) - tabla general de resumen para el rol de planeación modulo de formulación de planes de acción de funcionamiento

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#815]
Se requiere realizar la creación de un componente grafico y sus elementos complementarios en **planeacion_cliente**, en la vista **plan de acción/formulación** en el cual se muestre una **tabla resumen de todos los planes de acción** en la parte final de la vista, manteniendo el estilo y paleta de colores de SISGPLAN.

**Especificaciones técnicas**

1. La tabla de resumen se debe implementar de forma gráfica sin cargar elementos en la misma.
2. Las columnas de la tabla son:
- Unidad Académica y / o Administrativa (Nombre)
- Vigencia 
- Plan de acción (Nombre)
- Estado del plan de acción
- Acciones
3. Para el apartado **Acciones** se requiere mostrar un icono de lupa deshabilitado (no se debe desarrollar una acción en esta fase).

**Sub Tareas**

- [x] Mockups de tabla resumen en **planes de acción/formulación**.
- [x] Vista de tabla resumen, con elementos mencionados, en **planes de acción/formulación**.

**Criterios de aceptación**

- [x] Se muestra la tabla resumen de todos los planes de acción en fase de formulación en la parte inferior de la vista de planes de acción/formulación.

**Requerimientos**

- No presenta.

**Dependencias**

- planeacion_cliente.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by felimarod** [comment]
[Mockup de tabla resumen en Figma](https://www.figma.com/file/F5ZE2llLnHeA7mJK98RfJw/UD-team-library?type=design&node-id=2311%3A46&mode=design&t=pC7icJjgAXzyKn09-1)

**Comment by felimarod** [comment]
Mockups de la tabla resumen con la retroalimentación de el daily:
[Prototipo 1](https://www.figma.com/proto/F5ZE2llLnHeA7mJK98RfJw/UD-team-library?type=design&node-id=2311-2&t=pGXMNwYaCqHGDo7Q-1&scaling=contain&page-id=0%3A1&mode=design)
    ![2024-01-30_12-40](https://github.com/udistrital/planeacion_cliente/assets/85894335/7a39686c-dbe6-4700-80c5-f7d303c7e2f8)
[Prototipo 2](https://www.figma.com/proto/F5ZE2llLnHeA7mJK98RfJw/UD-team-library?type=design&node-id=2324-8&t=pGXMNwYaCqHGDo7Q-1&scaling=contain&page-id=0%3A1&mode=design)
![2024-01-30_12-40_1](https://github.com/udistrital/planeacion_cliente/assets/85894335/b18f6ad6-3fd6-48a5-b7ba-c189ecc4567b)

Se podrían hacer diferentes variaciones agregando y/o quitando el título, la barra de búsqueda o el paginador.
Quedo pendiente a su aprobación u observaciones. @a52290451

**Comment by a52290451** [comment]
Se valida propuesta 2, sin embargo, se debe corregir:

1. Titulo: Listado de planes de acción
2. Aplicación filtro de búsqueda por columna, ejemplo:

![image](https://github.com/udistrital/planeacion_cliente/assets/36229498/3abb955d-c279-4999-9743-afe7b433c74b)

**Comment by felimarod** [comment]
Diseño final
![image](https://github.com/udistrital/planeacion_cliente/assets/85894335/859ced78-0e1a-4b9c-aba3-a45af5cbdc9d)

**Comment by a52290451** [comment]
Se valida y aprueba el diseño de la tabla. Continuar con su implementación.

**Comment by felimarod** [comment]
Ya quedó hecho. No hago la PR ya que todavía no esta hecha la integración con el MID.

Se le agrego el campo de versión y se muestra solo para el rol 'PLANEACION' cuando no se tiene un plan seleccionado

[Documento de pruebas funcionales](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EQQtr3sRWihBkblQZ2Z5OMkBlpX_q532v3Zmn_G8n7o3kg?e=f0ZYKt)

**Comment by a52290451** [comment]
Se requiere adjuntar en las pruebas la visual de la tabla en su estado actual, es decir, sin registros.

**Comment by a52290451** [comment]
Se requiere realizar commit en rama feature y adjuntar link

**Comment by felimarod** [comment]
Acabo de agregar la ram a la issue y también ya actualice las pruebas
