### ISSUE TITLE
HU1 - 2 Definir fechas por unidades específicas para procesos formulación y seguimiento

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#816]
Se requiere implementar [HU1 - 2](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/resanchezc_udistrital_edu_co/EYc_4k5TayBEgwWaq2wQt9UBOxFJ-y2a-Z_lj5bsjlDkUQ?wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1706125306937&web=1), relacionada con la asignación de fechas para formulación y seguimiento de un nuevo proyecto.

Descripción: **Como** rol planeación **quiero** quiero tener la capacidad de definir fechas por unidad específicas para los procesos de formulación y seguimiento **para** establecer fechas distintas para cada unidad especifica en los procesos formulación y seguimiento .

**Especificaciones técnicas**

- Actualmente el desarrollo del aplicativo se encuentra estabilizado en ambiente develop (Cliente, mid y crud).
- Se requiere validar el funcionamiento actual de este módulo y escoger una opción que permita reutilizar el código empleado.

**Sub Tareas**

- [x] Adicionar en el siguiente orden los filtros para asignar las fechas asociadas a proyectos y planes: 
- Vigencia (ya se encuentra)
- Proceso (ya se encuentra)
- Unidad
- Plan o proyecto
- [x] En el filtro de unidad deben traerse en un select todas las unidades y debe haber un checkbox para seleccionar todas las unidades. Además, deben poderse seleccionar más de una unidad sin tener que seleccionar todas las unidades.
- [x] En el filtro de plan o proyecto deben traerse solo aquellos proyectos y debe haber un checkbox para seleccionar todos los proyectos.
- [x] El botón limpiar debe vaciar todas las selecciones efectuadas por el usuario previamente.
- [x] El botón de guardado debe validar que se escoga por lo menos una unidad y todos sus proyectos.
- [x] El controlador de guardado debe contemplar la opción de asignar el calendario para varios proyectos de una unidad, para uno solo, para varias unidades, etc.

**Criterios de aceptación**

- [x] (Pendiente de rony).
- [x] (Pendiente de rony).
- [x] (Pendiente de rony).
- [x] (Pendiente de rony).

**Requerimientos**

- [x] Ninguno.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by ccmendezt** [comment]
## Documentación - Avance HU1 - 2
### 09/02/2024 - 2:30 pm

- El filtro de **_unidades_** trae una tabla con todas las unidades y permite seleccionar una, varias y todas las unidades:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/787fe7db-3eb3-46cf-bd8e-624967609a7a)

- Para el filtro de **_planes o proyectos_** asociados a una unidad o unidades seleccionadas se creó un botón en la tabla de unidades:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/5ee5092f-2ce8-437a-bb43-fb8e588a07d1)

	De esa forma, cuando se seleccionen una o varias unidades, y sí dichas unidades tienen planes de interés asociados a ellas, el botón se habilitará y al darle clic mostrará únicamente dichos planes. En este caso se seleccionó la unidad **Vicerrectoría Académica**:
    - Se habilita el botón del filtro hablado anteriormente:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/6c702768-f01d-4cd9-a0a6-171a875cafd4)
    - La tabla se actualiza al oprimir el botón:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/11bc0c2b-7ec0-4564-baeb-14834865ee6b)
    - Se seleccionan todos los planes/proyectos:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/882376f5-7a12-432a-95df-6684242a8800)

- El botón de limpiar vacía todas las selecciones efectuadas por el usuario:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/60dab45f-d124-4af8-8593-a573cb76754e)

- El controlador de guardado contempla la opción de asignar el calendario para varios proyectos de una unidad, para uno solo, para varias unidades, etc:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/1189b7f2-cc9f-4970-829d-e777102742e9)
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/19f1085b-23fe-4635-9ffd-bce27659eece)
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/1e9d9b77-fb15-414b-b80e-f321b31f8371)

**Comment by milo19980525** [comment]
@ccmendezt Perfecto, buen trabajo.
Falta push a feature y pr a develop poserior al push.
