### ISSUE TITLE
HU1 - 3 Definir fechas por unidades, planes, proyectos específicos para procesos formulación y seguimiento

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#817]
Se requiere implementar [HU1 - 3](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/resanchezc_udistrital_edu_co/EYc_4k5TayBEgwWaq2wQt9UBOxFJ-y2a-Z_lj5bsjlDkUQ?wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1706125306937&web=1), relacionada con la asignación de fechas para formulación y seguimiento de un nuevo proyecto.

Descripción: **Como** rol planeación **quiero** tener la capacidad de definir fechas por unidad específicas y plan y proyectos específicos  para los procesos de formulación y seguimiento **para** establecer fechas distintas para cada unidad especifica y proyectos específicos en los procesos formulación y seguimiento .

**Especificaciones técnicas**

- Actualmente el desarrollo del aplicativo se encuentra estabilizado en ambiente develop (Cliente, mid y crud).
- Se requiere validar el funcionamiento actual de este módulo y escoger una opción que permita reutilizar el código empleado.

**Sub Tareas**

- [x] Adicionar en el siguiente orden los filtros para asignar las fechas asociadas a proyectos y planes: 
- Vigencia (ya se encuentra)
- Proceso (ya se encuentra)
- Unidad
- Plan o proyecto
- [x] En el filtro de unidad deben traerse en un select todas las unidades y debe haber un checkbox para seleccionar todas las unidades. Además, deben poderse seleccionar más de una unidad sin tener que seleccionar todas las unidades.
- [x] En el filtro de plan o proyecto deben traerse solo aquellos proyectos o planes asociados con la unidad o unidades seleccionadas y debe haber un checkbox para seleccionar todos los proyectos resultantes. Además, deben poderse seleccionar más de un proyecto sin tener que seleccionar todos los proyectos.
- [x] El botón limpiar debe vaciar todas las selecciones efectuadas por el usuario previamente.
- [x] El botón de guardado debe validar que se escoga por lo menos una unidad y un plan o proyecto.
- [x] El controlador de guardado debe contemplar la opción de asignar el calendario para varios proyectos de una unidad, para uno solo, para varias unidades, etc.

**Criterios de aceptación**

- [x] (Pendiente de rony).
- [x] (Pendiente de rony).
- [x] (Pendiente de rony).
- [x] (Pendiente de rony).

**Requerimientos**

- [x] Ninguno.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by ccmendezt** [comment]
## Documentación - Avance HU1 - 3
### 09/02/2024 - 2:40 pm

- El filtro de **_unidades_** trae una tabla con todas las unidades y permite seleccionar una, varias y todas las unidades:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/787fe7db-3eb3-46cf-bd8e-624967609a7a)

- Para el filtro de **_planes o proyectos_** asociados a una unidad o unidades seleccionadas se creó un botón en la tabla de unidades:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/5ee5092f-2ce8-437a-bb43-fb8e588a07d1)

	De esa forma, cuando se seleccionen una o varias unidades, y sí dichas unidades tienen planes de interés asociados a ellas, el botón se habilitará y al darle clic mostrará únicamente dichos planes. En este caso se seleccionó la unidad **Vicerrectoría Académica**:
    - Se habilita el botón del filtro hablado anteriormente:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/6c702768-f01d-4cd9-a0a6-171a875cafd4)
    - La tabla se actualiza al oprimir el botón:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/11bc0c2b-7ec0-4564-baeb-14834865ee6b)
    - Se pueden seleccionar más de un proyecto sin tener que seleccionar todos los proyectos.:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/18f6b3f6-4b57-45b9-87d8-61502e53b957)
    - Se habilita el botón para quitar el filtro y mostrar todos los planes:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/a94dc4c5-b778-4640-b06c-821a72130b57)
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/83cbe539-6033-4fdb-9a38-27c1ac6e8266)

- El botón de limpiar vacía todas las selecciones efectuadas por el usuario:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/60dab45f-d124-4af8-8593-a573cb76754e)

- El botón de guardado valida que se escoja por lo menos una unidad y un plan o proyecto:
     - Para unidades:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/e49e4863-c0fe-4899-aab5-8caa5ba0e768)
     - Para planes/proyectos:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/b1e8e48d-66b3-44bf-a159-4b1c002e0c2b)

- El controlador de guardado contempla la opción de asignar el calendario para varios proyectos de una unidad, para uno solo, para varias unidades, etc, tal como se muestra en la HU1 - 2.

**Comment by milo19980525** [comment]
@ccmendezt Perfecto, buen trabajo.
Falta push a feature y pr a develop poserior al push.
