### ISSUE TITLE
1 - 3 Implementación de funcionalidad en el componente (cliente) para la consulta de tabla general de resumen para el rol de planeación modulo de formulación de planes de acción de funcionamiento

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#818]
Se requiere incluir el flujo de funcionamiento en el componente grafico implementado en #815 , de tal forma que se consulte toda la información asociada a planes de acción en fase de formulación mediante **planeacion_mid** y se almacene esta información en la Tabla resumen de la vista **plan de acción/formulación**. Adicionalmente se debe implementar la funcionalidad que permita redireccionar al usuario a la vista especifica del plan de acción en formulación, y asignarla como evento al icono de lupa habilitado para cada plan de acción disponible en la tabla resumen.

**Especificaciones técnicas**

1. Los registros que deben ser incluidos en la tabla resumen, deben consultarse a través de **planeacion_mid**, de acuerdo con el controlador implementado en #813 .
2. En caso de no tener respuesta por parte de la api **planeación_mid** se debe controlar el error con un mensaje de alerta hacia el usuario.
3. Para cada registro en la tabla resumen, se debe habilitar el icono de lupa, en el campo **Acciones**, y asociar este con la vista en la cual se encuentra el registro en cuestión. Debe ser un evento que redireccione al usuario a la vista del plan de acción en formulación.
4. En caso de que no se pueda enlazar un registro particular con la vista correspondiente a través del icono, este debe aparecer deshabilitado en la tabla.
5. La información que debe completarse por cada registro en la tabla resumen es:
- Unidad Académica y / o Administrativa (Nombre)
- Vigencia 
- Plan de acción (Nombre)
- Estado del plan de acción
- Acciones (lupa).
6. En caso de que la consulta de todos los planes de acción sea robusta y tome mas tiempo del esperado, se debe controlar los tiempos de carga y no mostrar la tabla resumen hasta que contenga los registros requeridos. Se debe mostrar una pantalla de carga que no se cierre hasta que se genere la tabla resumen.

**Sub Tareas**

- [x] Implementación de funcionalidad para traer información de tabla resumen de **planeación_mid**
- [x] Implementación de funcionalidad para llenar tabla resumen con información consultada.
- [x] Implementación de funcionalidad para controlar el error cuando la consulta a **planeación_mid** sea nula.
- [x] Implementación de funcionalidad para acción "Ver" en tabla resumen.
- [x] Implementación de funcionalidad para controlar el erro en acción "Ver" en tabla resumen.
- [x] Implementación de funcionaldiad para controlar tiempos de respuesta al cargar la tabla resumen.

**Criterios de aceptación**

- [x] Se muestra tabla resumen en vista "planes de acción/formulación" con todos los registros asociados a planes de acción.
- [x] Para cada plan de acción existe una acción que permite ver el contenido del plan de acción en fase de formulación.
- [x] Cuando no existen registros de planes de acción se muestra un mensaje de alerta asociado.
- [x] Cuando el formulario del plan de acción en formulación no esta disponible, se muestra el icono de lupa desactivado.
- [x] Se muestra un mensaje de carga antes de mostrar la tabla resumen.

**Requerimientos**

- Completar issue #813.
- Completar issue #815 

**Dependencias**

- planeacion_cliente.
- planeacion_mid.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
@felimarod Por favor actualizar estado de la actividad

**Comment by felimarod** [comment]
Ya se obtienen los datos desde el API MID, sin embargo no se han logrado visualizar en la tabla, esto sucede ya que no se han inicializado los datos al momento de pasarlos a la tabla. Para solucionar esto se ha estado intentando implementar promesas en la creación del componente. Más sin embargo he tenido problemas con ello

**Comment by felimarod** [comment]
Una duda, a que se refiere el criterio de aceptación 4:
> Cuando el formulario del plan de acción en formulación no esta disponible, se muestra el icono de lupa desactivado.

Es que en teoría todos deberían estar disponibles.

**Comment by felimarod** [comment]
(Pruebas funcionales)[https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EQQtr3sRWihBkblQZ2Z5OMkBlpX_q532v3Zmn_G8n7o3kg?e=h6nhPM]

**Comment by a52290451** [comment]
El criterio de aceptación es una medida de control para no redireccionar al usuario a un formulario que no tenga data asociada, en algunos casos se tiene la información del formulario pero su contenido es nulo. En estos casos se debe controlar el error para no redireccionar a una página rota.

**Comment by felimarod** [comment]
[Sesión de revisión](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/afmartinr_udistrital_edu_co/EZfAHcuYxcZJnam9XUOFnNUBqFZ_dq_URcK98IUCnExSaA?referrer=Teams.TEAMS-WEB&referrerScenario=MeetingChicletGetLink.view.view)
Ya se actualizaron las pruebas funcionales con las sugerencias en las observaciones

**Comment by a52290451** [comment]
Se realiza merge en Develop
