### ISSUE TITLE
2 - 1 Análisis de puntos de notificación en flujos de funcionamiento del sistema, por rol. (Levantamiento con Usuarios)

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#819]
Se requiere realizar el análisis de puntos de notificación en el sistema, de acuerdo con los flujos de funcionamiento habilitados en SISGPLAN. Este análisis debe realzarse junto con el usuario final. Como resultado se espera que se indique en que partes del sistema y que acciones desencadenarán las notificaciones, desde y hacia que usuario (por rol).

**Especificaciones técnicas**

1. El análisis debe realizarse con el siguiente nivel de detalle por punto de notificación.
- Ubicación en el sistema (menú, vista, formulario).
- Acción que desencadena la notificación
- Rol que desencadena la notificación.
- Rol al cual le llegará la notificación.
- Plantilla de la notificación.
- Elementos dinámicos en la notificación.

2. Los puntos de notificación deben cubrir los flujos de funcionamiento del sistema que sean requeridos por el usuario.

**Sub Tareas**

- [ ] Documento en el cual se registren a detalle los puntos de notificación requeridos en el sistema.

**Criterios de aceptación**

- [ ] Se logra identificar a detalle en que puntos del sistema se deben ubicar eventos para notificar a usuarios, con un rol particular, acerca de cambios que requieren su atención.

**Requerimientos**

- Disponibilidad del usuario.

**Dependencias**

- No presenta.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by BikerMetalHead** [comment]
Diagramas de flujo del sistema (en proceso)

**Comment by milo19980525** [comment]
@BikerMetalHead 

Se revisa la relación de notificaciones en los flujos del sistema, dónde se encuentra que falta revisar la redacción y colocar todos los casos de cambio de estados (se debe tener en cuenta los que se agregaron en la issue relacionado con las verificaciones de los jefes de dependencia)

Evitar realizar notificaciones para el mismo usuario que está generando la acción.

Revisar comentarios realizados en el documento subido: https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EX72h7JHOldEibcHUqiiEl4BknvFoZRU6aUGx72c3uFxbw?e=b3zP4n

En este diagrama se encuentran los respectivos estados (Adicionar el estado "verificación revisión" tanto en formulación como para seguimiento)

**Comment by norbeydanilo** [comment]
@BikerMetalHead realizar correcciones de acuerdo a los comentarios efectuados por @milo19980525  

Actualizar enlaces para los diagramas.

**Comment by norbeydanilo** [comment]
@BikerMetalHead 

Ajustar puntos de notificación:

**Construcción**

- [ ] Editar plantilla

**En general**

- [ ] Incluir columna de estados de acuerdo al diagrama de estados actualizado (https://drive.google.com/file/d/1_Tg0AS8WAGgvqAOjw3H6p28wah1Ovc_V/view?usp=sharing)
- [ ] Revisar los puntos de notificaciones que presentan inconsistencia o redacción.

**Diagrama de estados**

- [ ] Ajustar el diagrama de estados

**Comment by BikerMetalHead** [comment]
Se actualizan los diagramas de estados según indicaciones recibidas:
https://drive.google.com/file/d/1_Tg0AS8WAGgvqAOjw3H6p28wah1Ovc_V/view?usp=sharing )

**Comment by BikerMetalHead** [comment]
Se actualizan los puntos de notificación con las correcciones en redacción y con los estados asociados a los mismos 
[Puntos de Notificación](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EX72h7JHOldEibcHUqiiEl4BknvFoZRU6aUGx72c3uFxbw?e=b3zP4n)

**Comment by norbeydanilo** [comment]
@a52290451 Revisará los puntos de notificación actualizados para comentarios y/o aprobación final.

**Comment by milo19980525** [comment]
@BikerMetalHead revisando el **diagrama de formulación** se presentan las siguientes observaciones:

Con base en el diagrama de estados https://drive.google.com/file/d/1_Tg0AS8WAGgvqAOjw3H6p28wah1Ovc_V/view?usp=sharing, se evidencia que planeación tiene una incidencia en el estado de "En revisión" la OAP interviene en el proceso, por lo que falta incluirlo en el diagrama.

De igual manera falta el estado "ajuste presupuestal".

Respecto al diagrama de **Seguimiento** se identifica correctamente cada una de las fases con sus respectivos estados implícitos.

Respecto al diagrama de **Estados** en la fase de seguimiento la descripción del estado "Enviado a Revisión" cambia dado que no se envía a la OAP si no al jefe de la dependencia, mientras que en estado "Revisión verificada", si se envía a la OAP. Por lo tanto se deben ajustar las dos descripciones de estos estados.

**Comment by a52290451** [comment]
Se revisa del documento asociado a los puntos de notificación, realizado por @BikerMetalHead. Se deben tener en cuenta las siguientes observaciones:

1. Tanto para el caso de formulación y seguimiento, se requiere establecer puntos de notificación, principalmente cuando se presente un cambio de estado.
2. Para cada cambio de estado, se debe tener en cuenta tanto el caso positivo, que es cuando se acepta, como el caso negativo, cuando se rechaza el plan.
3. Se deben tener en cuenta los roles que deben ser notificados, de acuerdo a su influencia en el proceso, en el estado particular del plan.
4. Se requiere un ajuste en la estructura de las plantillas de los puntos de notificación, especificando el usuario que emite, el plan, el estado, la vigencia y, en el caso de seguimiento, el trimestre. También se debe agregar el estado al cual pasa el plan cuando aplique. (se presenta una sugerencia de la plantilla en comentarios en el apartado "seguimientos")
5. Se debe revisar ortografía en general.

Para mayor detalle, se recomienda revisar el documento, junto con todas las observaciones realizadas en cada caso.

**Comment by BikerMetalHead** [comment]
De acuerdo a las observaciones se realiza rediseño de los puntos de notificación. En donde se elaboran bajo la lógica de cambios de estado para los diferentes momentos del proceso. Se realiza para los procesos de formulación y seguimiento. 
[Puntos_notificacion_estados](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EeuYa5l-sIJIhoIo5nSIDXIB5qnI9DtFw_2fdpeY4h0oaw?e=H3g1dx)

**Comment by BikerMetalHead** [comment]
Se realizan los ajustes solicitados 
[Puntos_notificacion_estados](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EeuYa5l-sIJIhoIo5nSIDXIB5qnI9DtFw_2fdpeY4h0oaw?e=H3g1dx)

**Comment by norbeydanilo** [comment]
Revisar ajustes sobre puntos de notificación @a52290451

**Comment by BikerMetalHead** [comment]
Se realiza la revisión y se generan algunos ajustes, otros son descartados y quedan unas dudas que me gustaría compartirlas en review.

**Formulación:**
Se realiza ajuste de mención de vigencia en la plantilla de notificación. 
 En el estado C en revisión, Se evalúa el comentario y al revisar con el diagrama de flujo de estados se descarta comentario, puesto que es el asistente de planeación el que genera la revisión. En este punto es el quién realiza la acción y, por lo tanto, quien emite la notificación.
En el estado E verificado, Se establece el estado verificado a la acción de poner un check de aprobación por parte del jefe de unidad. El paso a estado pre avalado ocurre con la acción de revisar y dar pre aval por parte del jefe de planeación. Aunque se parecen, son estados diferentes. Para acciones diferentes. Como lo solicitaron en el oficio de planeación

**Seguimiento** 
Se realiza ajuste de mención de vigencia en la plantilla de notificación. 
En los estados C Y D existe una ambigüedad en el concepto de revisión y verificación que me gustaría revisar en grupo. 
En el estado G no cambio, no encuentro la incongruencia. Me gustaría verlo en equipo 

[Puntos_notificacion_estados](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EeuYa5l-sIJIhoIo5nSIDXIB5qnI9DtFw_2fdpeY4h0oaw?e=H3g1dx)

**Comment by a52290451** [comment]
Se realizan observaciones sobre puntos de notificación en el submódulo de seguimiento.

@BikerMetalHead por favor revisar y corregir, gracias.

**Comment by BikerMetalHead** [comment]
Se realiza refinamientos según observaciones y se dejan notas para la discusión de dos puntos que a mi parecer no deberían moverse por la forma en que fue construido el sistema. 
[Puntos_notificacion_estados](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EeuYa5l-sIJIhoIo5nSIDXIB5qnI9DtFw_2fdpeY4h0oaw?e=H3g1dx)
