### ISSUE TITLE
HU1 - 4 Consulta de Fechas Asignadas por Otros Usuarios

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#820]
Se requiere implementar [HU1 - 4](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/resanchezc_udistrital_edu_co/EYc_4k5TayBEgwWaq2wQt9UBOxFJ-y2a-Z_lj5bsjlDkUQ?wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1706125306937&web=1), relacionada con la consulta de fechas asignadas por otros usuarios a los proyectos.

Descripción: **Como** rol planeación **quiero** consultar las fechas asignadas por otros usuarios **para** asegurar la coherencia en la programación y validar la misma.

**Especificaciones técnicas**

- Actualmente el desarrollo del aplicativo se encuentra estabilizado en ambiente develop (Cliente, mid y crud).
- Se asocia con las tareas desarrolladas en #812 #816 y #817 .

**Sub Tareas**

- [x] Para cada una de las tablas del menú de administración de fechas se debe visualizar el usuario y la última fecha de modificación de fecha sosbre la persona que realizó la configuración de fechas por última vez, la fecha inicial y la fecha final.

**Criterios de aceptación**

- [x] En dado caso que el usuario se encuentre en las tablas que relacionen unidades y planes después de oprimir el botón "Mostrar Planes de Interés Habilitados/Reporte" o la tabla inicial del menú "Administración" después de diligenciar los campos básicos de consulta, deben visualizarse los campos: usuario y fecha modificación.
- [x] En dado caso que el usuario se encuentre en las tablas que relacionen unidades y planes después de oprimir el botón "Mostrar Planes de Interés Habilitados/Reporte" o la tabla inicial del menú "Administración" después de diligenciar los campos básicos de consulta y no se encuentren planes debe desplegarse un POP UP que informe "Las unidades escogidas no cuentan con planes/proyectos con fechas parametrizadas".

**Requerimientos**

- [x] Ninguno.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by ccmendezt** [comment]
## Evidencias - Avance Consulta de Fechas Asignadas por Otros Usuarios
### 05/04/2024 - 15:22

- Se revisó y arregló el almacenamiento de fechas, no se tuvieron que hacer cambios mayores, solo cambios mínimos.

- Se agregaron los campos **Usuario**, **Fecha inicio** y **Fecha fin** en la tabla de listar unidades:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/fdd3d123-d9d1-4659-b1d3-166d4408b14d)

- Funcionalidad completa mostrando los criterios de aceptación establecidos en la issue:
![consultaFechas](https://github.com/udistrital/planeacion_cliente/assets/82072560/1e80ff1b-503d-4520-89b9-4b8e81d2ef33)

**Comment by ccmendezt** [comment]
## Pull Request Asociados a Issue
### 08/04/2024 - 15:30

- **planeacion_cliente:** https://github.com/udistrital/planeacion_cliente/pull/979
- **planes_crud:** https://github.com/udistrital/planes_crud/pull/98
