### ISSUE TITLE
HU5 - Aprobación de seguimiento plan de acción para los proceso de formulación y seguimiento

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#821]
Se requiere implementar [HU 5](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ERnXVlOzYglGiQxvKqRZ7SkBXK6kdFyl6mB6wnqyf3Kpag?e=0rksLc) - HU1-1, relacionada con la preaprobación de planes por parte del jefe de la unidad.

Descripción: **Como** rol jefe de unidad **quiero** poder aprobar un seguimiento de un plan de acción para los procesos de formulacion y seguimiento **para** garantizar la completa satisfaccion sobre el seguieminto realizado a algunos proyectos en particular.

**Especificaciones técnicas**

- Actualmente el desarrollo del aplicativo se encuentra estabilizado en ambiente develop (Cliente, mid y crud).

**Sub Tareas**

- [x] Se debe verificar la lógica que presenta el seguimiento y envío a pre aval por parte de la unidad al jefe actualmente, dado que se entiende que existe un check por parte del jefe desde el mismo usuario y rol de la unidad.
- [x] Se debe ajustar la fase de aprobación de preaval para que solo sea accesible desde el rol de jefe de la unidad (realizar inscripción de rol jefe_dependencia_planeacion en el [api de configuración](https://pruebasconfiguracion.portaloas.udistrital.edu.co/) entrar con el usuario pruebasoas1).
- [x] Se debe observar el detalle del plan que se debe aprobar (reutilizar vista en dado caso de que el componente ajustado no cuente con esta opción).
- [x] Adicionar un checklist que indique aprobación preaval.
- [x] Adicionar dos botones "Enviar seguimiento" y "Enviar observaciones"
- [x] El botón "Enviar seguimiento" está relacionado con la aprobación del plan y solo debe estar habilitado cuando el checkbox sea escogido por el usuario y por ende una vez se ejecute la acción el plan pasa a estado "pre aval revisado".
- [x] El botón "Enviar observaciones" está relacionado con el rechazo del plan y solo debe habilitado cuando no haya sido escogido por el usuario, además se deberá crear un text area para que el usuario pueda digitar las observaciones por corregir en el plan y por ende una vez se ejecute la acción el plan continua en el mismo estado y debe ser revisado por el rol de unidad.

**Criterios de aceptación**

- [x] El usuario con rol "jefe dependencia" debe visualizar los detalles de un plan de acción escogido previamente.
- [x] Se evidencian los botones requeridos con el comportamiento descrito.
- [x] El usuario puede aprobar el seguimiento del plan y se debe reflejar el cambio de estado.
- [x] El usuario puede rechazar el seguimiento del plan y realizar comentarios sobre el rechazo, se debe generar persistencia de este para mostrarse al rol unidad el motivo del rechazo.

**Requerimientos**

- [x] Creación de roles y asignación de permisos tanto en WSO2 como en el api de configuración.
- [x] Desarrollo de vista de tabla con los proyectos pendientes por aprobar.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by C0C045** [comment]
# Flujo de verificación para seguimiento y formulación de parte del rol JEFE_UNIDAD_PLANEACION
## En Formulación
En el siguiente video se observa con claridad cada uno de los estados por lo que pasa un plan en formulación y cómo el jefe de unidad es participe en la nueva implementación.

https://github.com/udistrital/planeacion_cliente/assets/55455142/ca226b5e-3904-4a9e-a1b2-06fd0dd47c29

## En Seguimiento
1.  En este caso, se observa que en el estado 'En reporte' la unidad ya no puede enviar el reporte a revisión directamente; ya que primero debe tener el visto bueno por parte del jefe de la unidad.

![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/bec5105a-4b32-4843-ac6b-f46dc1f91f85)

2. Ahora bien, el jefe de la unidad debe verificar la revisión para que esta pase al estado 'Revisión Verificada' y posteriormente la unidad pueda enviar el reporte a revisión.

![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/7e8b16bf-e569-4c96-af72-8491cc144775)
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/d430897a-7286-4a8d-b25c-c01da882dbda)

3. Una vez el jefe de unidad de el visto bueno con el estado 'Revisión Verificada', entonces, la unidad podrá enviar el reporte a revisión para que planeación pueda progresar en el seguimiento del plan.

![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/8cba4cd6-efdd-45c8-8877-935dc36a9619)
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/d5eba20a-2a1b-49a6-a232-67c5ed178393)

**Comment by C0C045** [comment]
# PR's
En rama mid: https://github.com/udistrital/planeacion_mid/pull/479
En rama cliente: https://github.com/udistrital/planeacion_cliente/pull/868

**Comment by C0C045** [comment]
# Generación Swagger.
Fix rama: https://github.com/udistrital/planeacion_mid/pull/481
