### ISSUE TITLE
Creación API planeacion_arbol_mid

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#822]
Se requiere crear el API **PLANEACION_ARBOL_MID** con base en el API **PLANEACION_MID**, de forma tal que los controladores asociados queden desacoplados del API principal.

**Especificaciones técnicas**

1. El repositorio para **PLANEACION_ARBOL_MID** es: https://github.com/udistrital/planeacion_arbol_mid
2. Se requiere migrar el código asociado a Arbol, del API **PLANEACION_MID** al API **PLANEACION_ARBOL_MID**.
3. El API debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevas APIs GO definidos por la OATI.
4. Los métodos de utilidades que son globales a todas las APIs deben ser migrados a la librería **utils_oas**.
5. Se debe optimizar el código migrado, eliminando malas practicas de desarrollo.

**Sub Tareas**

- [x] Desarrollo de API **PLANEACION_ARBOL_MID**
- [x] Migración de código entre APIs.
- [x] Optimización de código.

**Criterios de aceptación**

- [x] El API se encuentra desarrollada y probada.
- [x] El código fuente del API está optimizado.

**Requerimientos**

- [x] Completar Issue #803 .

**Dependencias**

- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
Se termina la construcción del API de planeacion_arbol_mid, sea realiza una pequeña comparación con respecto a un GET, para comprobar que esté respondiendo de la misma manera que planeacion_mid

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/51a2d29e-e2f7-4d9c-95fc-c6ece589c634)

Ahora se están construyendo las pruebas unitarias para probar tanto de manera manual como por código que la API esté respondiendo de manera correcta.

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/1997418c-1b01-4f88-8509-03c93e354497)

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/758f8efd-c840-4def-9e48-c3bb8083b8db)

**Comment by Mechaz123** [comment]
Se realizan las pruebas unitarias del sistema, con los 5 controladores que se crearon para esta API.

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/2ef538f0-064e-439b-a8f5-77f0328d15bf)

**Comment by Mechaz123** [comment]
Se realizan las pruebas funcionales del API, se adjunta en el siguiente link:
https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EQ_B42dbFmBFiYf9v5PAkdUBArDV_07qRp5HESkBL_ODZA?e=anDIYj
