### ISSUE TITLE
HU6 - Vista pendientes por aprobar (Jefe dependencia) PT1

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#830]
Se requiere implementar [HU 6](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ERnXVlOzYglGiQxvKqRZ7SkBXK6kdFyl6mB6wnqyf3Kpag?e=0rksLc) - HU 1-2, relacionada con la preaprobación de planes por parte del jefe de la unidad.

Descripción: **Como** rol jefe de unidad **quiero** ver una lista de todos los verificación pendientes de aprobación para los proceso de **formulación para** poder visualizar y generar la verificación necesarios según los pendientes. Y acceder a cada verificación desde la lista de pendientes.

**Especificaciones técnicas**

- Actualmente el desarrollo del aplicativo se encuentra estabilizado en ambiente develop (Cliente, mid y crud).
- Se creó un servicio orientado a traer todos los planes de acción (inactivos e inactivos que se encuentren en formulación en #813 )
- El componente visual que consume el controlador mencionado anteriormente se encuentra relacionado en #815. 
- [Diagrama de estados](https://drive.google.com/file/d/1_Tg0AS8WAGgvqAOjw3H6p28wah1Ovc_V/view?usp=sharing)

**Sub Tareas**

- [x] Se debe crear un submenú llamado "Pendientes" en el el menú "Plan de acción" realizando su respectiva configuración en el [API de configuración](https://pruebasconfiguracion.portaloas.udistrital.edu.co/) con el usuario pruebasoas1.
- [x] Asignar permisos al rol "JEFE_UNIDAD_PLANEACION" la consulta al nuevo menú.
- [x] Crear vista para la consulta de aprobaciones pendientes de funcionamiento e inversión en el cliente y linkearlo al nuevo menú.
- [x] La nueva vista debe contener una tabla con todas aprobaciones pendientes (basarse en los componentes ya creados - MID y CLIENTE) asociados a planes en fase de funcionamiento.
- [x] El servicio del MID debe ser modificado para que puedan filtrarse los planes de acción o proyectos por unidad (La unidad del jefe que está consultando)
- [x] Inicialmente la tabla debe mostrar aquellos planes de acción que se encuentran en estado "Revisado" y "En reporte"  o por lo menos traer primero aquellos que tengan ese estado (orden).

**Criterios de aceptación**

- [x] El usuario con rol "JEFE_UNIDAD_PLANEACION" debe visualizar un nuevo menú en plan de acción titulado "Pendientes". 
- [x] El usuario con rol "JEFE_UNIDAD_PLANEACION"puede acceder al menú y visualizar todas las solicitudes pendientes de aprobación.
- [x] Cuando el jefe de unidad Accede al sistema, en el menú de "Pendientes". Visualiza información relevante sobre cada seguimiento (Vigencia, plan de acción, versión, estado). 
- [x] Por cada uno de los registros debe existir un botón que genere la acción de revisar la aprobación (relacionado con la issue #821 )

**Requerimientos**

- [x] Creación de roles y asignación de permisos tanto en WSO2 como en el api de configuración.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by C0C045** [comment]
# Avance Vista Planes en Formulación
1. **Primera vista al entrar al submenú "Pendientes":** Se implementó un select menú para controlar el tema de las unidades a cargo del jefe de unidad, por otro lado, se quito el filtrado para estado, ya que todos los planes tendrán un estado anterior al verificado.
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/011a1c40-c4fe-4784-aac8-e4915e521f26)
2. Una vez, seleccionada la unidad carga todos los planes de **formulación** con verificación pendiente, cabe aclarar que para lograr esto se tuvo que hacer un filtrado tanto de estado como de versiones, y esta última porque solo nos interesa la última versión vigente.
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/df634b19-ff4a-4007-b23c-4e86923d0866)
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/67d53d5c-1f23-4770-af99-c92c6be19ac9)

**Comment by C0C045** [comment]
# Versión final de Planes Pendientes en Formulación.
1. Se mejoró el filtro de planes por versiones, ya que anteriormente se mostraban las últimas versiones qué estuvieron en "Revisado" sin importar que hubiese una versión más reciente en otro estado.
2. Se implementó el botón de acción que nos redirecciona a formulación para verificar el plan seleccionado.
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/c347e465-e41f-4f3d-adff-d25469d432c2)

3. Se implementó un aviso en caso de que no existan planes pendientes para modificar
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/e65a39bf-1a0f-42a6-ba5f-dd116e87fdf2)

4. Por último, se agregó la vista de Identificación de Contratistas, Identificación de Recursos e Identificación de Recurso Docente para el rol JEFE_UNIDAD_PLANEACION, ya que en #821 no se implementó por descuido.
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/74c979a6-a890-40b2-a808-3fce6d9d8303)
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/cd6e6fe4-3c89-4ba2-980b-36c6f4254fe4)
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/d0a8fbb5-82b8-43ab-b0b0-bc05f74ce71e)
