### ISSUE TITLE
5-1 Revisión de elementos y componentes habilitados por estado

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#831]
Se requiere implementar HU 7, relacionada con la verificación de acceso y permisos sobre los flujos encontrados en planeación.

**Especificaciones técnicas**

- Actualmente el desarrollo del aplicativo se encuentra estabilizado en ambiente develop (Cliente, mid y crud).

**Sub Tareas**

- [x] Identificar los diferentes flujos que se encuentran en SISGPLAN.
- [x] Definir los roles necesarios para el sistema.
- [x] Relacionar los roles con cada parte de los flujos identificados.
- [x] Elaborar un documento excel que relacione la información solicitada.

**Criterios de aceptación**

- [x] Se identifican los flujos, roles y la relación entre estos, plasmandose en un documento excel.
- [x] Documentación de la issue.

**Requerimientos**

- [x] ninguno.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by BikerMetalHead** [comment]
Se adjuntan los documentos de funcionalidades accesos:
Acceso por roles: [Accesos](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EQjQo8cg2YNMnP4TmbiIHjoBIFGJnNRRtj3QFuwlXx2KDw?e=lggw3X)
  acciones por rol: [Acciones](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EQMxr7UqL5ZDiZK4t20m_8ABlg1KNqEcYl6WNI0uuGWIjA?e=XszCpo)

**Comment by milo19980525** [comment]
@BikerMetalHead Se debe comentar que acciones permite realizar cada rol por estado (Está a nivel de proceso más no a nivel de estado)

**Comment by milo19980525** [comment]
@BikerMetalHead desde comienzo de semana se comentaron las correcciones respectivas, en los documentos no se evidencia el avance mencionado en el daily. Además no se comenta el issue.

**Comment by milo19980525** [comment]
Por favor relacionar los estados de planes/proyectos (formulación y seguimiento) con cada uno de los menús y roles encontrados.

**Comment by BikerMetalHead** [comment]
Atendiendo a la solicitud se actualizan los diagramas de estado. Adjuntando el estado de "**_en verificación_**" el cual hace referencia  a la revisión que hace el jefe de unidad antes de enviar un seguimiento o una formulación. Se plantea para los dos procesos para asegurar el conocimiento pleno del jefe de unidad sobre sus proyectos, planes o actividades en las dos fases.

Documento: [diagramas_estados](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EYct3LCyOshNiUa0KrgkJeMBkmofaS7gADCHusLthPeB2Q?e=Jatl6k)

**Comment by milo19980525** [comment]
@BikerMetalHead Falta terminar la adición del estado "revisión verificada" en el apartado de seguimiento. Además, no se ha relacionado cada uno de estos estados en los documentos "Acceso por rol" y "Acciones por rol"

**Comment by BikerMetalHead** [comment]
Se completa la descripción con un cuadro que describe el estado, las acciones permitidas y el rol que lo ejecuta en un flujo normal de ejecución para los procesos de formulación y seguimiento:
[cuadro_estados_acciones_flujo](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EeNjPFNBwsRBjDqSepON5WABPt4F9mmyAGakA_vQnhXwRg?e=uMyDAl)

**Comment by BikerMetalHead** [comment]
Se llevó a cabo una mejora en el diagrama y se introdujo un cuadro de acciones por rol, detallando las acciones generales por cada rol en el estado. Durante el proceso de formulación, se identificó que la actual configuración impide tanto la edición como la eliminación de un plan, ya que estas acciones se realizan a un nivel más bajo, específicamente en el nivel de actividades.

En cuanto a la "edición" de un plan, propongo referirnos a ella como un "ajuste", dado que esta acción solo es posible si hay observaciones sobre el plan. Al realizar cambios y enviarlos para su revisión. El plan adquiere una nueva versión, comportándose más como un documento nuevo que como una edición convencional. Este ajuste se alinea al concepto del plan dentro del flujo establecido en el sistema.

En el proceso de seguimiento, la edición del plan es posible cuando es necesario, ya que no implica un cambio de versión en el seguimiento realizado. Sin embargo, igual que el proceso anterior, no se permite la eliminación completa de un plan. Solo se pueden realizar eliminaciones a nivel de actividades.

[cuadro_estados_acciones_flujo](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EeNjPFNBwsRBjDqSepON5WABPt4F9mmyAGakA_vQnhXwRg?e=uMyDAl)

**Comment by milo19980525** [comment]
@BikerMetalHead Se presenta un avance notable frente a las primeras versiones, sin embargo, en las primeras fases de formulación según se había hablado y como se muestra en las columnas de planeación cuando se está revisando un plan por parte de estos o el jefe de la unidad no se evidencia la acción en los asistentes de la unidad de "editar" o "ajustar" el plan. De igual manera en seguimiento se menciona "edición" y en el resto de documento "ajustar", por lo que se debe ser coherente frente a la notación empleada en el flujo.

Por favor revisar los detalles comentados, establecer las diferencias entre las celdas con fondo azul pastel y blanco, y corroborar las acciones permitidas en cada uno de los pasos.

**Comment by BikerMetalHead** [comment]
Se atienden las observaciones según lo acordado en los dailys 
[cuadro_estados_acciones_flujo](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EeNjPFNBwsRBjDqSepON5WABPt4F9mmyAGakA_vQnhXwRg?e=uMyDAl)

**Comment by norbeydanilo** [comment]
Llevar a nivel de detalle de operaciones asociado a las acciones dadas por rol dentro de un estado. Editar, eliminar, consultar, agregar. @BikerMetalHead

**Comment by BikerMetalHead** [comment]
Se realiza ajuste frente a nivel de detalle de operaciones asociadas a las acciones dadas por rol dentro de un estado. Editar, eliminar, consultar, agregar
[cuadro_estados_acciones_flujo](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EeNjPFNBwsRBjDqSepON5WABPt4F9mmyAGakA_vQnhXwRg?e=uMyDAl)

**Comment by milo19980525** [comment]
@BikerMetalHead se mejora la estructura general del documento. Por favor corregir con base en los comentarios realizados para cerrar la issue.

**Comment by norbeydanilo** [comment]
Ajustar diagrama según comentarios en Review @BikerMetalHead

**Comment by BikerMetalHead** [comment]
Se realiza ajuste sobre la descripción de actividades posibles. Según los comentarios en el estado revisado para formulación y en revisión para verificación. 
[cuadro_estados_acciones_flujo](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EeNjPFNBwsRBjDqSepON5WABPt4F9mmyAGakA_vQnhXwRg?e=uMyDAl)

**Comment by BikerMetalHead** [comment]
Se realiza cambios recomendados:
[cuadro_estados_acciones_flujo](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EeNjPFNBwsRBjDqSepON5WABPt4F9mmyAGakA_vQnhXwRg?e=uMyDAl)
