### ISSUE TITLE
2 - 2 Revisión y ajustes, API de notificaciones

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#834]
Se requiere revisar el API notificaciones_mid y el sistema de Cumplidos, a fin de identificar la forma en que se encuentran desarrolladas las notificaciones a nivel de sistema. En dado caso de requerir ajustes en el API de notificaciones_mid, se deben realizar para que alimente y soporte las notificaciones a nivel de sistema.

**Especificaciones técnicas**

1. El análisis de funcionamiento acerca de la construcción de notificaciones a nivel de sistema debe realizarse en notificaciones_mid, API en la que se encuentra soportada esta lógica y en el sistema de cumplidos en donde se desarrollaron.
2. notificaciones_mid se encuentra implementada en GO y se conecta con un servicio en AWS que realiza la persistencia de las notificaciones por sistema, utilizando un sistema de colas y pilas.
3. cumplidos tiene implementadas las notificaciones por sistema, sin embargo, no se encuentra en funcionamiento actualmente. 
4. El API de notificaciones debe permitir almacenar notificaciones hasta que sean solicitadas por el sistema y debe guardar persistencia de las mismas por un periodo de tiempo determinado, hasta que el sistema especifique que no requiere mas dichas notificaciones.
5. El API de notificaciones debe mantener un registro de 10 notificaciones por usuario.
6. Material de apoyo:

- [ Documentación básica](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EqdxCcNSVddFqqXF4r8nl4kB8gsA9aQIH84kPd1nzq9rTQ?e=XzfnCT)
- [Repositorio de notificaciones](https://github.com/udistrital/notificacion_mid)

**Sub Tareas**

- [x] Estudio, estabilización y ajuste de API notificaciones_mid.
- [x] Estudio de sistema de cumplidos en cuanto a notificaciones a nivel de sistema.

**Criterios de aceptación**

- [x] Se estabiliza y ajusta el API notificaciones_mid para que permita realizar notificaciones a nivel de sistema, almacenando información por sistema acerca de las notificaciones entrantes y salientes.
- [x] El API de notificaciones_mid permite almacenar información de las notificaciones hasta que el sistemas envía una señal para que sean descartadas.
- [x] Se realiza un análisis acerca del funcionamiento de las notificaciones en cumplidos.

**Requerimientos**

- [x] Documentación del API

**Dependencias**

- No presenta.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
Por favor actualizar estado de la actividad.

**Comment by EdissonFrancisco** [comment]
Realizo analisis de notificaciones_mid y creo una documentacion que indica lo que implementa y la descripcion de tablas y parametros.

esta usa AWS SES y sus funciones de correo, las cuales son SNS, SQS y logica de Topic para recepcion y suscripcion de usuarios, y para las notificaciones.

link a documento de documentacion: https://udistritaleduco-my.sharepoint.com/:w:/g/personal/efaceror_udistrital_edu_co/EU39FBUswnhNp2vZ0F84-m4BFPSepyuoHjfK-cWKAc_y4g?e=aJGjnm

**Comment by a52290451** [comment]
Se requiere señalar, de forma clara y concisa, de que forma se va a realizar el consumo del API de notificacion_mid desde el cliente de planeación para registrar y consultar notificaciones por usuario.

**Comment by EdissonFrancisco** [comment]
el api notificaciones mid no requier ajustes adicionales dado que cumple con la logica necesaria para las especificaciones.

para el almacenamiento de las notificaciones la documentacion de AWS SQS tien un limite maximo de 14 dias, este tiene opciones de eliminacion de mensaje, si se requiere se puede eliminar el mensaje segun se requiera.

**Comment by EdissonFrancisco** [comment]
ya que el api cuenta con la logica de envio y recepcion de mensajes, se pretende realizar una funcionalidad que permita consumir el api y realizar el envio y recepcion de las notificaciones por medio de los endpoind que ya tiene definidos, si se establece necesario la persistencia de las notificaciones por mas del tiempo que establece AWS, se puede implementar una persistencia local.

las url que permiten el manejo de los mensajes son: 

![imagen](https://github.com/udistrital/planeacion_cliente/assets/109987805/5618890b-512f-4071-9c8c-c69e4d320b8c)

![imagen](https://github.com/udistrital/planeacion_cliente/assets/109987805/8867d337-4106-498a-bd4c-ac98b51f78b5)

**Comment by EdissonFrancisco** [comment]
ara el consumo del api notificaciones mid 

El api se va a usar para tener las notificaciones almacenadas en el servicio AWS, las caracteristicas que se van a usar en la implementacion son las siguientes:  

- Creacion de colas por rol 

Ruta: /colas/crear/ 
Cuerpo:  
{ 
  "EsFifo": true, 
  "EsperaVisibilidad": 1, 
  "NombreCola": "nombre de rol", 
  "Politica": { 
    "Id": "politica definida", 
    "Statement": [ 
      {} 
    ], 
    "Version": "1" 
  }, 
  "Retencion": 345600, 
  "Retraso": 0, 
  "TamañoMaximo": 262144, 
  "TiempoEspera": 0 
} 

- Registrar o enviar Notificaciones: 

Ruta: /notificaciones/enviar/ 
Cuerpo:  
{ 
  "ArnTopic": "arn:aws:sns:us-east-1:699001025740:test-PruebaNotificaciones", 
  "Asunto": "revisar prueba", 
  "Atributos": { 
      “dato1”: “”, 
      “dato2”: “”, 
      “dato3”: “” 
}, 

  "DestinatarioId": [ 
    "string del id" 
  ], 
  "IdDeduplicacion": "string", 
  "IdGrupoMensaje": "string", 
  "Mensaje": "este mensaje es de prueba", 
  "RemitenteId": "string" 
} 

- Consultar por notificaciones: 

Ruta: colas/mensajes 
Cuerpo: colas/mensajes?nombre=nombre de la cola 
Respuesta: 
{ 
    "Data": null, 
    "Message": "Successful", 
    "Status": "200", 
    "Success": true 
} 

- Borrar notificacion 

Ruta: colas/mensajes/', elemento, token 
Cuerpo: /colas/mensajes/nombre/nombre-cola

**Comment by a52290451** [comment]
Se requiere enviar evidencia de las pruebas realizadas para cierre de la actividad @EdissonFrancisco

**Comment by a52290451** [comment]
@EdissonFrancisco Se requiere subir evidencia final para cerrar el issue.

**Comment by EdissonFrancisco** [comment]
Realizo pruevas y documento flujo de trabajo del api
el flujo de envio yrecepcion de mensajes esta dado por las siguientes url del api notificaciones_mid.

1.Se debe crear o tener existente una cola, esta estara asociada al servicio de SQS (almacenamiento de mensajes), el cual recibira los mensajes que estaran almacenados por un tiempo definido (entre 1 a 14 dias).

Ejemplo de creacion de cola SQS con el API 
Ruta: colas/crear
{
"EsFifo": true,
"EsperaVisibilidad": 0,
"NombreCola": "prueva-planeacion",
"Retencion": 345600,
"Retraso": 0,
"TamañoMaximo": 262144,
"TiempoEspera": 0
}

![imagen](https://github.com/udistrital/planeacion_cliente/assets/109987805/3cb4dfca-d50e-4e3b-a377-202db8d705f6)

2.se debe crear o tener definido el topic, este estara asociado al SNS quie se encarga de la publicación y suscripción, el mensaje a publicar se envia a un topic y los consumidores/suscriptores lo resibiran una vez sea enviado a SNS, este se encarga de controlar y dirigir los mensajes a donde corresponden.
Ejemplo de creacion de SNS con el API.
Ruta: notificaciones/topic
{
  "Display": "Notificaciones del Sistema planeacion_cliente",
  "EsFifo": true,
  "Nombre": "planeacion_cliente_sns"
}

![imagen](https://github.com/udistrital/planeacion_cliente/assets/109987805/025eca24-9de5-4c44-94e5-9c83c0e1b45f)

3.se debe asociar o referenciar el arn de SQS (cola) con el arn de SNS (tema o topic), de esta forma al publicar un mensaje en el SNS se enviara a la cola de SQS.
Ruta: notificaciones/suscribir/
{
  "ArnTopic": "arn:aws:sns:us-east-1:699001025740:test-planeacion_cliente_sns.fifo",
  "Suscritos": [
    {
      "Endpoint": "arn:aws:sqs:us-east-1:699001025740:test-prueva-planeacion.fifo",
      "Id": "pruebaSubs1",
      "Protocolo": "sqs"
    }
  ]
}

Ejemplo de asociacion de SQS con SNS con el API.

![imagen](https://github.com/udistrital/planeacion_cliente/assets/109987805/1690354f-d9e7-4840-9366-62becd4fc5f3)
 
4.se valida la suscripcion 
Ruta: notificaciones/suscripcion/
{
  "ArnTopic": "arn:aws:sns:us-east-1:699001025740:test-planeacion_cliente_sns.fifo",
  "Endpoint": "arn:aws:sqs:us-east-1:699001025740:test-prueva-planeacion.fifo"
}

![imagen](https://github.com/udistrital/planeacion_cliente/assets/109987805/dd7d5e1b-ebf8-411d-8b12-5561be834dee)

5.se realiza el envio del mensaje al sns para que lo envie a la cola y pueda ser solicitado.

{
  "ArnTopic": "arn:aws:sns:us-east-1:699001025740:test-planeacion_cliente_sns.fifo",
  "Asunto": "revision-prueba",
  "DestinatarioId": [
    "pruebaSubs1"
  ],
  "IdDeduplicacion": "publicacion-1",
  "IdGrupoMensaje": "prueba",
  "Mensaje": "primer mensaje de prueba",
  "RemitenteId": "edisson"
}

Ejemplo de envio de mensaje con el API.

![imagen](https://github.com/udistrital/planeacion_cliente/assets/109987805/8c5a3ab1-19b6-432f-b2de-dac3ea2ad0de)

6.se realiza la peticion para ver los mensajes.
esta requier de permisos y variables de validacion especificas del servicio AWS. 
Ruta: /mensajes?nombre=nombredecola
al generar la peticion devuelbe el siguiente mensaje: 
“operation error SQS: GetQueueUrl, get identity: get credentials: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, request canceled, context deadline exceeded”

posibles opciones de interpretacion: 
ocurre cuando el SDK de AWS no puede obtener las credenciales necesarias para hacer una solicitud. Aquí hay algunas posibles causas:

No se encontró el rol de EC2 IMDS: Esto significa que el SDK de AWS intentó obtener las credenciales de la instancia de EC2 en la que se está ejecutando tu aplicación, pero no pudo encontrar un rol de IAM asociado con la instancia.
Error de ec2imds: GetMetadata, request canceled, context deadline exceeded: Este error indica que el SDK de AWS intentó obtener metadatos de la instancia de EC2 (como las credenciales del rol de IAM), pero la solicitud fue cancelada porque excedió el tiempo límite.
Error al actualizar las credenciales almacenadas en caché: Esto podría indicar un problema con la forma en que se están almacenando o recuperando las credenciales.

![imagen](https://github.com/udistrital/planeacion_cliente/assets/109987805/bbc46c94-431a-4e6a-b3ed-23c7ef884b1a)
