### ISSUE TITLE
3 - 1 Adaptación del cliente de planeación para consumo de servicios asociados a Identificación Docentes desde el API MID.

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#842]
Se requiere adaptar el componente de **Identificación Docente** en Formulación, planes de acción de funcionamiento, de tal forma que se consuman todos los cálculos asociados desde el API MID, de acuerdo a lo implementado en #843 .

**Especificaciones técnicas**

1. planeacion_mid expone, a través de un controlador, el conjunto de servicios asociados con los cálculos que se requieren para la **La identificación docente**. Por lo que se deben consumir y visualizarse en sus respectivos campos.
2. Los cálculos registrados de forma automática en cada uno de los campos  de la tabla de identificación docente deben coincidir con los realizados en la versión actual.
3. Cada vez que se realice una actualización en los campos de ingreso de información y se encuentren los demás campos requeridos listos, se deben actualizar automáticamente todos los demás campos de la tabla. En caso contrario, si se aplican cambios pero no todos los campos requeridos están completos, se bloquea esta opción.

**Sub Tareas**

- [x] Ajuste de componente de **identificación docente** para el consumo de servicios de API_MID.
- [x] Ajuste de visualización y control de errores en el componente de **Identificación Docente.**

**Criterios de aceptación**

- [x] No se registran cambios aparentes a nivel visual en el componente de **Identificación Docente** en el cliente.
- [x] El cliente realiza el consumo de servicios asociados a **Identificación Docente** desde el API de planeacion_mid.

**Requerimientos**

- [x] Terminar Issue #843 

**Dependencias**

- planeacion_mid.
- planeacion_cliente.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
@diegobauto Por favor adjuntar evidencia de avances en la actividad. Gracias

**Comment by diegobauto** [comment]
Desarrollo de función para el consumo de calculos en la identificación recursos docente: 

[feature/migracionDocente](https://github.com/udistrital/planeacion_cliente/tree/feature/migracionDocente)

**Comment by diegobauto** [comment]
Modificaciones en el cliente: 
Rama: [feature/migracionDocente](https://github.com/udistrital/planeacion_cliente/tree/feature/migracionDocente)

Modificaciones en el mid:
Rama: [feature/calculosDocentes](https://github.com/udistrital/planeacion_mid/tree/feature/calculosDocentes)

**Comment by a52290451** [comment]
@diegobauto Cuando se trate del cliente, al realizar commits a la rama feature, enlázalo directamente con el issue, es decir:

git commit -m "feat: Actualización Migración Docente #842 "

**Comment by diegobauto** [comment]
Modificaciones en el cliente: 
Rama: [feature/migracionDocente](https://github.com/udistrital/planeacion_cliente/tree/feature/migracionDocente)

Modificaciones en el mid:
Rama: [feature/calculosDocentes](https://github.com/udistrital/planeacion_mid/tree/feature/calculosDocentes)

**Comment by a52290451** [comment]
La realización de pruebas asociadas a el componente de **Identificación docente** se realizará en el issue #884
