### ISSUE TITLE
3 - 2 Migración de lógica de cálculos del componente "identificacion docente"desde el cliente al mid

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#843]
Se requiere evaluar y migrar lógica asociada a cálculos en el componente de **Identificación Docente** del modulo de formulación en planes de acción, del Cliente al MID de planeación.

**Especificaciones técnicas**

1. En el Cliente **planeacion_cliente** se encuentra lógica asociada a cálculos de algunos campos del componente de **Identificación Docente** lo cual constituye una mala práctica de programación. Este código debe ser migrado al API **planeacion_mid** de forma tal que el flujo de funcionamiento de los cálculos no sea alterado.
2. La lógica de los cálculos debe ubicarse en el controlador asociado a formulación en planes de acción, de tal forma que se habilite un servicio o grupo de servicios para su consumo desde el cliente.

**Sub Tareas**

- [x] Implementación de servicios en el controlador "formulación" en el API **planeacion_mid**, para consumir cálculos requeridos por el componente de **Identificación Docente**.
- [x] Migración de lógica asociada a cálculos en el componente de **Identificación Docente**, del Cliente al MID de planeación (Adaptación del cliente).

**Criterios de aceptación**

- [x] El API **planeacion_mid** realiza el calculo de algunos campos asociados al componente de **Identificación Docente** y los expone para ser consumidos por el cliente de planeación.

**Requerimientos**

- No aplica.

**Dependencias**

- planeacion_mid.
- planeacion_cliente.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
Se requiere adjuntar archivo excel en el que se especifiquen los calculos realizados en el componente de **Identificación docente**

**Comment by diegobauto** [comment]
Adjunto el archivo excel con los respectivos calculos (Faltan campos por validar): 
[Calulos docentes.ods](https://github.com/udistrital/planeacion_cliente/files/14106467/Calulos.docentes.ods)

**Comment by a52290451** [comment]
Se requiere actualizar estado de la actividad

**Comment by a52290451** [comment]
@diegobauto Por favor subir todo lo referente al issue para su validación.

**Comment by diegobauto** [comment]
Se realiza controlador para obtener los caluclos correspondientes a Indentificación de Contratistas:

Rama: [feature/migracionDocente](https://github.com/udistrital/planeacion_mid/tree/feature/migracionDocente)

![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/5c04b0ed-b007-4f56-8b15-39de88f72e58)

Sin embargo, para obtener los datos correctamente es importante que la petición hacia Resoluciones Docentes responda con todos los datos correspondientes, sin embargo esto no ocurre: 
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/e4da108f-410a-4af5-9308-228219732f7f)
La respuesta deria ser algo como: 
{
		"Categoria":        "valor",
		"Dedicacion":       "valor",
		"EsDePlanta":       valor,
		"NivelAcademico":   "valor",
		"Vigencia":         valor,
		"arl":              valor,
		"caja":             valor,
		"cesantias":        valor,
		"icbf":             valor,
		"interesCesantias": valor,
		"pension":          valor,
		"primaNavidad":     valor,
		"primaVacaciones":  valor,
		"prima_servicios":  valor,
		"salarioBasico":    valor,
		"salud":            valor,
		"vacaciones":       valor,
	}
Por lo tanto las pruebas a seguir sería aparte de que los calculos se esten obteniendo correctamente, es definir que es lo que se espera en este tipo de casos.

**Comment by diegobauto** [comment]
Rama [feature/migracionDocente](https://github.com/udistrital/planeacion_mid/tree/feature/migracionDocente)

Adjunto formato con prubras:
[Formato de pruebas MID.xlsx](https://github.com/udistrital/planeacion_cliente/files/14175382/Formato.de.pruebas.MID.xlsx)

**Comment by diegobauto** [comment]
Se realizo el pull request:
[Pull Requests](https://github.com/udistrital/planeacion_mid/pull/480)

Variable de entorno: 
- Archivo app.conf
ResolucionesDocentes = ${RESOLUCIONES_DOCENTES_SERVICE}

- Valor correspondiente: 
export RESOLUCIONES_DOCENTES_SERVICE=pruebasapi2.intranetoas.udistrital.edu.co:8529/v1

**Comment by a52290451** [comment]
Pruebas funcionales en ONE DRIVE: https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/Ef6kTtH-qe5AhSBeEinRECgBT7T6pz80WmmWayESRkS0Qw?e=UspyEr

**Comment by a52290451** [comment]
Se requiere complementar las pruebas funcionales con los casos en que no responda el endpoint o que no se encuentre respuesta a la consulta realizada. @diegobauto

**Comment by a52290451** [comment]
Se validan y aprueban las pruebas funcionales realizadas.

Queda pendiente realizar correcciones de código sugeridas en:

https://github.com/udistrital/planeacion_mid/pull/482

**Comment by a52290451** [comment]
Se completa PR  a rama Develop

**Comment by a52290451** [comment]
Se solicita actualización de variables de entorno para despliegue en ambiente de pruebas:

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=58532
