### ISSUE TITLE
0 - 1 Creación de controlador para la consulta de tabla general de resumen para el rol de planeación y unidad modulo de planes de acción - PARTE 1

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#849]
Se requiere realizar la creación de un controlador en planeacion_mid que consulte la información de **todos los planes de acción existentes**, tanto **activos como inactivos**, y los devuelva como respuesta de la petición.

**Especificaciones técnicas**

1. La petición principal realizada al controlador no tiene parámetros adicionales (GetAll).
2. Los parámetros que debe recopilar y devolver el controlador por cada registro son:
- Unidad Académica y / o Administrativa (Nombre)
- Vigencia 
- Plan de acción (Nombre)
- Estado del plan de acción (Formulación / Seguimiento / Evaluación)
- Versión en el caso de Formulación (N/A para los demás casos)
****3. Para el caso de una unidad, se debe agregar como parámetro adicional de búsqueda, el nombre  o identificador de la unidad.****

**Sub Tareas**

- [x] Desarrollo de controlador en planeacion_mid con servicios GetAll *****y GetAll con parámetro de búsqueda.*****
- [x] Desarrollo de lógica de controlador en Helpers.

**Criterios de aceptación**

- [x] Planeación mid permite realizar la consulta de todos los planes de acción que se encuentren registrados en el sistema, sin importar su estado, vigencia o unidad académica y / o administrativa.
- [x] Planeación mid permite realizar la consulta de todos los planes de acción que se encuentren registrados en el sistema asociados a una unidad, sin importar su estado o vigencia.****

**Requerimientos**

- No presenta.

**Dependencias**

- planes_crud.
- planeacion_mid.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
@felimarod por favor actualizar estado del issue

**Comment by felimarod** [comment]
Ya se encuentra listo el controlador nuevo con los parametros pedidos

**Comment by a52290451** [comment]
@felimarod por favor realizar commit en la rama feature e incluir el link aquí.

También se requieren pruebas funcionales del controlador.

**Comment by felimarod** [comment]
Agrego las pruebas funcionales: https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ETDt1607us9LsOohADUMumQBtnhWJ4-SM-UWGc5L3eOZAg?e=AuZQxd

**Comment by a52290451** [comment]
Posibles mejoras:

1. Implementación de multilistas para consulta de planes de acción.

**Comment by a52290451** [comment]
Se validan y aprueban pruebas funcionales realizadas.

**Comment by felimarod** [comment]
Se agrego la propiedad fase a los planes que se retornan
Los planes que están en fase de 'Seguimiento' no retornan el valor de 'version'
![image](https://github.com/udistrital/planeacion_cliente/assets/85894335/99570a9f-d21e-4c61-b136-fcb5acc3c804)

Se encuentra un error ya que no se deberían obtener planes con versión -1
Los planes que retornan version -1 pueden que se hallan creado mal y se hagan llamados a elementos null:
![image](https://github.com/udistrital/planeacion_cliente/assets/85894335/c489cab5-198a-442b-8828-4b4dd8565774)

**Comment by a52290451** [comment]
Swagger actualizado
