### ISSUE TITLE
0 - 3 Implementación de funcionalidad en el componente para la consulta de tabla general de resumen en planes de acción, tanto para el rol de planeación como el de unidad.

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#850]
Se requiere incluir el flujo de funcionamiento en el componente grafico implementado en #878 , de tal forma que se consulte toda la información asociada a planes de acción mediante **planeacion_mid** y se almacene esta información en la Tabla resumen de la vista **plan de acción/consulta**. Adicionalmente se debe implementar la funcionalidad que permita redireccionar al usuario a la vista especifica del plan de acción y asignarla como evento al icono de lupa habilitado para cada plan de acción disponible en la tabla resumen. Este desarrollo debe implementarse tanto para el rol de planeación como el de unidad.

**Especificaciones técnicas**

1. Los registros que deben ser incluidos en la tabla resumen, deben consultarse a través de **planeacion_mid**, de acuerdo con el controlador implementado en #878 .
2. En caso de no tener respuesta por parte de la api **planeación_mid** se debe controlar el error con un mensaje de alerta hacia el usuario.
3. Para cada registro en la tabla resumen, se debe habilitar el icono de lupa, en el campo **Acciones**, y asociar este con la vista en la cual se encuentra el registro en cuestión. Debe ser un evento que redireccione al usuario a la vista del plan de acción en formulación o seguimiento.
4. En caso de que no se pueda enlazar un registro particular con la vista correspondiente a través del icono, este debe aparecer deshabilitado en la tabla.
5. La información que debe completarse por cada registro en la tabla resumen es:
- Unidad Académica y / o Administrativa (Nombre)
- Vigencia 
- Plan de acción (Nombre)
- Fase (Formulación / Seguimiento)
- Estado del plan de acción (estado interno en formulación o seguimiento)
- Acciones (lupa).
6. En caso de que la consulta de todos los planes de acción sea robusta y tome mas tiempo del esperado, se debe controlar los tiempos de carga y no mostrar la tabla resumen hasta que contenga los registros requeridos. Se debe mostrar una pantalla de carga que no se cierre hasta que se genere la tabla resumen.

**Sub Tareas**

- [x] Implementación de funcionalidad para traer información de tabla resumen de **planeación_mid**
- [x] Implementación de funcionalidad para llenar tabla resumen con información consultada.
- [x] Implementación de funcionalidad para controlar el error cuando la consulta a **planeación_mid** sea nula.
- [x] Implementación de funcionalidad para acción "Ver" en tabla resumen.
- [x] Implementación de funcionalidad para controlar el erro en acción "Ver" en tabla resumen.
- [x] Implementación de funcionalidad para controlar tiempos de respuesta al cargar la tabla resumen.
- [x] Implementación de funcionalidad para condicionar la vista de  **consulta** por rol, mostrando los datos asociados a los planes de acción cargados para cada rol.

**Criterios de aceptación**

- [x] Se muestra tabla resumen en vista "planes de acción/consulta" con todos los registros asociados a planes de acción para el rol de **planeación (administrador)**.
- [x] Se muestra tabla resumen en vista "planes de acción/consulta" con todos los registros asociados a planes de acción para el rol de **Unidad**.
- [x] Para cada plan de acción existe una acción que permite ver el contenido del plan de acción.
- [x] Cuando no existen registros de planes de acción, se muestra un mensaje de alerta asociado.
- [x] Cuando el formulario del plan de acción en formulación o seguimiento no esta disponible, se muestra el icono de lupa desactivado.
- [x] Se muestra un mensaje de carga antes de mostrar la tabla resumen.

**Requerimientos**

- [x] Completar issue #849 .
- [x] Completar issue #878 .

**Dependencias**

- planeacion_cliente.
- planeacion_mid.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by felimarod** [comment]
¿Existe alguna manera para traer el id de la dependencia de un usuario? obtuve esta info pero pues no se si en algún otro lugar este el id de la dependencia, esto ya que es necesario para traer solo los planes que sean relacionados al usuario en especifico
![MicrosoftTeams-image](https://github.com/udistrital/planeacion_cliente/assets/85894335/aa4fecae-5445-4c4b-b33b-2d2a8632b18a)

**Comment by a52290451** [comment]
@felimarod por favor actualizar estado de la actividad.

La rama DEVELOP ya se encuentra estable.

**Comment by felimarod** [comment]
Ya se adaptó el código para estar al día con la rama **develop** y se solucionaron los problemas que se habían estado presentando. De momento solo falta la opción de ver para los planes en fase de 'seguimiento'

**Comment by felimarod** [comment]
Actualización en: https://github.com/udistrital/planeacion_mid/tree/feature/resumen_planes_accion

**Comment by felimarod** [comment]
Se agregan las pruebas funcionales, los referentes a esta issue son los del item 3 al 10.
[Pruebas funcionales](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EditWYMuq9tLuheDIsNQu-QBokWMuK5fijLJ6DN8muf3Yg?e=P0hrK4)
