### ISSUE TITLE
Creación API planeacion_formulacion_mid PT1

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#852]
Se requiere crear el API **PLANEACION_FORMULACION_MID** con base en el API **PLANEACION_MID**, de forma tal que los controladores asociados queden desacoplados del API principal.

**Especificaciones técnicas**

1. El repositorio para **PLANEACION_FORMULACION_MID** es: https://github.com/udistrital/planeacion_formulacion_e_inversion_mid/tree/feature/planeacion_formulacion
2. Se requiere migrar el código asociado a Formato, del API **PLANEACION_MID** al API **PLANEACION_FORMULACION_MID**.
3. El API debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevas APIs GO definidos por la OATI.
4. Los métodos de utilidades que son globales a todas las APIs deben ser migrados a la librería **utils_oas**.
5. Se debe optimizar el código migrado, eliminando malas practicas de desarrollo.

**Sub Tareas**

- [x] Desarrollo de API **PLANEACION_FORMULACION_MID**
- [x] Migración de código entre APIs.
- [x] Optimización de código.

**Criterios de aceptación**

- [x] El API se encuentra desarrollada y probada.
- [x] El código fuente del API está optimizado.

**Requerimientos**

- [x] Completar Issue #803 .

**Dependencias**

- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
Se logra reducir el código en ciertas funciones, al momento de realizar la migración:
![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/16198afa-012d-410c-b467-7dc343e8be9d)

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/8501edc4-c333-4ddc-9963-47955f6a4ed4)

Igualmente se seguirá trabajando en la creación de esta API, ya que posee bastante código que hay que refactorizar.

**Comment by Mechaz123** [comment]
A lo largo de la semana se ha estado desarrollando los controladores asociados a la parte de formulación, al día de hoy, se tienen desarrollados 16 de los 17 controladores para este apartado, aún queda faltando realizar el refactor del ConsultarUnidades, y a la vez realizar la corrección para ConsultarRubros.

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/dd5c2fba-02f5-43cc-ac12-3048dbd860b3)

La tarea se extendió bastante debido al contenido en cantidad de código que posee cada uno de los apartados, siendo 1.800 aproximadamente para formulación y 2400 aproximadamente para inversión, apenas se terminé el controlador faltante y la corrección se continuará con la sección de inversión.

**Comment by milo19980525** [comment]
@Mechaz123 buen trabajo, quedamos pendientes para la segunda a: https://github.com/udistrital/planeacion_cliente/issues/880

**Comment by milo19980525** [comment]
Por favor subir lo realizado al feature.
