### ISSUE TITLE
1 - Inclusión de campo "Brecha" en la tabla "Evaluación Plan de Acción" del módulo de evaluación.

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#859]
Se requiere incluir el campo **Brecha** en la tabla de **Evaluación Plan de Acción** del módulo de evaluación. El campo debe ubicarse al lado derecho del campo **Meta** en el aparatado **Avance General Plan de acción**. Este campo hace alusión _al porcentaje restante que le hace falta a cada actividad para cumplir con su meta_.

**Especificaciones técnicas**

1. Se debe implementar un Mockup del resultado que se obtendrá tras realizar el ajuste de la tabla, incluyendo el nuevo campo.
2. El nuevo campo se debe ubicar a la derecha del campo **Meta** en el aparatado **Avance General Plan de acción**, y debe quedar fijado como los demás elementos.
3. El calculo del campo se realiza de la siguiente forma:

- _Meta de la actividad - Avance actual de la actividad._

4. El campo debe calcularse por cada actividad de forma automática, una vez se cargue la información en la tabla.

**Sub Tareas**

- [x] Creación de Mockup para la modificación de la vista **Evaluación** en planes de acción, evidenciando la nueva apariencia de la tabla **Avance General Plan de acción** con la adición del campo **Brecha**.
- [x] Adición de campo **Brecha** la tabla **Avance General Plan de acción** de la vista **Evaluación** en planes de acción.
- [x] Inclusión de lógica para cálculo automático del campo **Brecha**.

**Criterios de aceptación**

- [x] En la tabla **Avance General Plan de acción** en el módulo de **Evaluación** en **Planes de acción**, se muestra el campo **Brecha**, a la derecha del campo **Meta**, calculado por cada actividad.

**Requerimientos**

- [x] Validar calculo del campo **Brecha** por Fila.
- [x] Validar ubicación del campo **Brecha**.

**Dependencias**

- planeacion_cliente.
- planeacion_mid.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
@EdissonFrancisco Por favor actualizar estado de la actividad.

**Comment by EdissonFrancisco** [comment]
realizo el mockup.
![imagen](https://github.com/udistrital/planeacion_cliente/assets/109987805/f7647295-2ac9-43bb-9049-cf9816cc0f2e)

**Comment by a52290451** [comment]
El mockup debe ajustarse a los estilos y paleta de colores del modulo en cuestión. No se acepta diseño propuesto.

Se deben realizar correcciones pertinentes.

**Comment by a52290451** [comment]
@EdissonFrancisco Queda pendiente aprobación de diseño final.

Por favor subir pruebas funcionales de la implementación.

**Comment by norbeydanilo** [comment]
@EdissonFrancisco Por favor actualizar estado con pruebas para cierre.

**Comment by a52290451** [comment]
Se realiza commit a ambiente de pruebas. 

La revisión de código deja las siguientes observaciones:

1. La lógica para el calculo de la brecha y disposición de colores debe hacerse en los componentes, no en las vistas HTML, por lo que se requiere un ajuste asociado.
2. Se requiere realizar pruebas con diferentes planes, en diferentes trimestres y ver el comportamiento del desarrollo. Todo esto en ambiente de pruebas.

**Comment by EdissonFrancisco** [comment]
se realiza ajuste solicitado .

adjunto archivo de pruebas: https://udistritaleduco-my.sharepoint.com/:x:/g/personal/efaceror_udistrital_edu_co/EW8i2i3YAspIvDXWfi3KODQBH6SbHGyp65WtU6585EVflg?e=wAlIY1

**Comment by a52290451** [comment]
@EdissonFrancisco Se requiere completar documentación de pruebas y completar las mejoras requeridas para terminar la actividad.

**Comment by a52290451** [comment]
Una vez terminados los cambios, se debe adjuntar rama feat y realizar PR a Develop

**Comment by a52290451** [comment]
El desarrollo se encuentra en ambiente de pruebas.
