### ISSUE TITLE
HU2 - 1 - Implementación de semáforo de colores para el campo "Brecha" en la tabla "Evaluación Plan de Acción" en Evaluación.

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#861]
Asociado al campo **Brecha**, en la tabla **Evaluación Plan de Acción** en Evaluación, se requiere incluir un sistema de **Semáforo de colores**, de tal forma que se logre identificar el estado actual en el que se encuentra cada actividad.

**Especificaciones técnicas**

1. Se debe implementar una serie de Mockups del resultado que se obtendrá tras realizar el ajuste de la tabla, incluyendo el nuevo sistema de semáforo de colores sobre el campo **Brecha**.
2. El campo **Brecha**, además de mostrar su valor correspondiente, debe estar coloreada con laguna de las siguientes opciones:

- **Verde:**  _Cuando la brecha entre el indicador y la meta sea menor o igual al 10%._
- **Amarillo:** _Cuando la brecha sea mayor al 10% y menor o igual al 20%._
- **Rojo:** _Cuando la brecha sea mayor al 20%._

3. El campo, para cada fila, debe colorearse de forma automática, una vez se cargue la información en la tabla.
4. Como Material Guía, se recomienda consultar la [Historia de Usuario - HU2 - 1](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ERnXVlOzYglGiQxvKqRZ7SkBXK6kdFyl6mB6wnqyf3Kpag?e=WPHbcQ) relacionada.

**Sub Tareas**

- [x] Creación de Mockups para modificación de la vista **Evaluación** en planes de acción, evidenciando la nueva apariencia de la tabla **Avance General Plan de acción** con la adición del sistema de **Semáforo de colores** sobre el campo **Brecha**.
- [x] Adición de **Sistema de colores** sobre el campo **Brecha** de la tabla **Avance General Plan de acción** en la vista **Evaluación** en planes de acción.

**Criterios de aceptación**

- [x] En la tabla **Avance General Plan de acción** en el módulo de **Evaluación** en **Planes de acción**, se muestra el campo **Brecha** junto con un color especifico que indica su estado actual.

**Requerimientos**

- [x] Validar rangos para el sistema de **Semáforo de colores** asociado al campo **Brecha**.

**Dependencias**

- planeacion_cliente.
- planeacion_mid.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by EdissonFrancisco** [comment]
se realiza la inclucion de los colores dependiendo del porcentaje en el campo brecha
![imagen](https://github.com/udistrital/planeacion_cliente/assets/109987805/68ea9675-464b-42ee-bc9b-a24f86e5baff)

**Comment by a52290451** [comment]
Observaciones del Mockup,

1. Se requiere ajustar coloreado para que cubra el total de la casilla.
2. Los colores son demasiado fuertes, se debe reducir su intensidad para que se visualice correctamente la brecha.

**Comment by a52290451** [comment]
@EdissonFrancisco Queda pendiente aprobación de diseño final.

Por favor subir pruebas funcionales de lo realizado.

**Comment by norbeydanilo** [comment]
@EdissonFrancisco Por favor actualizar estado con pruebas para cierre.

**Comment by EdissonFrancisco** [comment]
como comento en el issu #859 se implementa el campo brecha y se pinta toel espacio dependiendo del porcentaje 
![imagen](https://github.com/udistrital/planeacion_cliente/assets/109987805/f13c7814-6678-4007-9264-652651acfa0b)

**Comment by a52290451** [comment]
Se realiza commit a ambiente de pruebas. 

La revisión de código deja las siguientes observaciones:

1. La lógica para el calculo de la brecha y disposición de colores debe hacerse en los componentes, no en las vistas HTML, por lo que se requiere un ajuste asociado.
2. Se requiere realizar pruebas con diferentes planes, en diferentes trimestres y ver el comportamiento del desarrollo. Todo esto en ambiente de pruebas.

**Comment by a52290451** [comment]
![image](https://github.com/udistrital/planeacion_cliente/assets/36229498/6f329c15-167a-4abe-8e05-58171dd3d625)

**Comment by a52290451** [comment]
@EdissonFrancisco por favor subir ajustes requeridos.

**Comment by EdissonFrancisco** [comment]
se realizan ajustes requeridos y se coloca un valor de NA cuando no hay dato o su Operacion es dada con valor cero indicando que no hay breca.

![image](https://github.com/udistrital/planeacion_cliente/assets/109987805/159d1a87-efa0-415c-bf82-3bf438b38acd)

**Comment by a52290451** [comment]
El desarrollo se encuentra en ambiente de pruebas.
