### ISSUE TITLE
2 - 4 Desarrollo de componente de notificaciones en cliente de planeación

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#862]
Se requiere desarrollar el componente de notificaciones en planeacion_cliente de tal forma que se permita registrar y consultar notificaciones asociadas a un usuario, a través del API notificacion_mid.

**Especificaciones técnicas**

1. Las notificaciones que se generen en el sistema deben ser registradas a través de notificacion_mid, como se especifica en #834 . El registro se debe hacer con los parámetros requeridos por notificacion_mid.
2. Todas las notificaciones disponibles, asociadas a un usuario, según la cola correspondiente al ROL, deben ser consultadas a través del API de notificacion_mid, como se especifica en #834 .
3. En caso de que la respuesta de **notificacion_mid** sea nula para cuando se consultan notificaciones, se debe controlar el flujo.
4. En caso de no tener respuesta por parte de la api **notificacion_mid** se debe controlar el error . (No es posible mostrar notificaciones en este momento / Módulo en mantenimiento).
5. En los metadatos registrados para notificaciones se debe registrar el estado de las mismas, con lo cual se podrá controlar si una notificación fue atendida o no.
6. Para cada Rol en SISGPLAN debe existir una cola de notificaciones.
7. El componente debe cargar y reordenar las notificaciones por usuario de tal forma que se muestren en primer lugar las notificaciones sin leer, por fecha de registro y, posteriormente, las que ya se han leído hasta un máximo de 5.
8. El componente debe reenviar las notificaciones a notificaciones_mid para actualizar su registro, de tal forma que no se eliminen en el tiempo establecido por AWS.
9. Se deben eliminar notificaciones que ya se encuentren fuera del plazo establecido para su persistencia.

**Sub Tareas**

- [x] Funcionalidad para registrar notificaciones por usuario mediante **notificacion_mid**.
- [x] Funcionalidad para consultar notificaciones por usuario mediante **notificacion_mid**
- [x] Funcionalidad para controlar el error cuando la consulta a **notificacion_mid** sea nula.
- [x] Funcionalidad para controlar el error cuando la consulta a **notificacion_mid** no responda.
- [x] Funcionalidad para ordenar las notificaciones por estado y fecha de registro.
- [x] Funcionalidad para eliminar notificaciones que se encuentren fuera del plazo establecido para su persistencia.
- [x] Funcionalidad para registrar nuevamente las notificaciones de un usuario.

**Criterios de aceptación**

- [x] Se registran notificaciones asociadas a un usuario a través de  **notificacion_mid** desde **planeacion_cliente**.
- [x] Se consultan notificaciones asociadas a un usuario a través de  **notificacion_mid** desde **planeacion_cliente**.
- [x] Se controla el error cuando la consulta a **notificacion_mid** es nula.
- [x] Se controla el error cuando la consulta a **notificacion_mid** no responde.
- [x] Las notificaciones consultadas son ordenadas por estado y fecha de registro.
- [x] Las notificaciones que se encuentren fuera del plazo establecido para su persistencia, son eliminadas.
- [x] Se registran nuevamente las notificaciones de un usuario cada vez que son consultadas.

**Requerimientos**

- Completar issue #834 .

**Dependencias**

- planeacion_cliente.
- notificacion_mid.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
Se realiza solicitud para obtención de credenciales en AWS para los servicios SQS y SNS:

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=58518

**Comment by a52290451** [comment]
@EdissonFrancisco Por favor actualizar estado de la actividad

**Comment by a52290451** [comment]
@EdissonFrancisco Se requiere actualización de estado del issue, subir desarrollo realizado a la fecha en la rama feature correspondiente.

**Comment by a52290451** [comment]
@EdissonFrancisco Ultimo llamado, por favor actualizar Issue, con evidencia de lo realizado, gracias.

**Comment by a52290451** [comment]
@EdissonFrancisco Por favor actualizar estado de la actividad.

Para el acceso a AWS, el Ingeniero JAIME ACOSTA se estará comunicando por teams.

**Comment by a52290451** [comment]
Se requiere solicitar permisos en WSO2 para consultar API de notificacion_mid desde planeacion_cliente.

**Comment by a52290451** [comment]
Se concede acceso de consulta a notificacion_mid desde planeacion_cliente.

**Comment by EdissonFrancisco** [comment]
hoy recibi acceso a aws y tengo credenciales para poder hacer pruebas desde api

**Comment by a52290451** [comment]
@EdissonFrancisco  Por favor finalizar actividad con tareas pendientes

**Comment by a52290451** [comment]
@EdissonFrancisco Por favor subir evidencia de los avances realizados.

**Comment by a52290451** [comment]
@EdissonFrancisco Ultimo llamado, por favor subir actualización de la actividad y su estado.

**Comment by a52290451** [comment]
Se solicitan credenciales de acceso a SQS y SNS para @diegobauto :

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=59666

**Comment by a52290451** [comment]
@diegobauto por favor subir desarrollo en rama feature y enviar PR a develop

**Comment by diegobauto** [comment]
Se realizó el desarrollo en la rama: [feature/notificaciones](https://github.com/udistrital/planeacion_cliente/tree/feature/notificaciones)
