### ISSUE TITLE
Creación API planeacion_seguimiento_mid Parte 1

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#863]
Se requiere crear el API **PLANEACION_SEGUIMIENTO_MID** con base en el API **PLANEACION_MID**, de forma tal que los controladores asociados queden desacoplados del API principal.

**Especificaciones técnicas**

1. El repositorio para **PLANEACION_SEGUIMIENTO_MID** es: https://github.com/udistrital/planeacion_seguimiento_mid

2. Se requiere migrar el código asociado a Formato, del API **PLANEACION_MID** al API **PLANEACION_SEGUIMIENTO_MID**.
3. El API debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevas APIs GO definidos por la OATI.
4. Los métodos de utilidades que son globales a todas las APIs deben ser migrados a la librería **utils_oas**.
5. Se debe optimizar el código migrado, eliminando malas practicas de desarrollo.

**Sub Tareas**

- [X] Desarrollo de API **PLANEACION_SEGUIMIENTO_MID**
- [X] Migración de código entre APIs.
- [X] Optimización de código.

**Criterios de aceptación**

- [x] El API se encuentra desarrollada parcialmente.
- [x] El código fuente del API está optimizado.

**Requerimientos**

- [x] Completar Issue #803 .

**Dependencias**

- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by milo19980525** [comment]
@Mechaz123 por favor comentar estado actual y que hay pendiente.

**Comment by Mechaz123** [comment]
El sistema actualmente se encuentra creado, pero se está realizando la migración de los controladores existentes, actualmente se tiene 1 desarrollado y una parte del siguiente controlador, este es apenas el inicio de esta API, por lo cual se continuará en la parte 2 de la construcción de la API.

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/9d788129-bda5-486e-8e47-f6192f7f7a6f)
