### ISSUE TITLE
2 - 5 Desarrollo de notificaciones en el sistema por banderas

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#865]
Se requiere implementar puntos de notificación en planeacion_cliente, consumiendo el componente de notificaciones previamente implementado #862 y la documentación relacionada #819 .

**Especificaciones técnicas**

1. Se deben registrar notificaciones a través del componente correspondiente #862 , de tal forma que queden registradas en la cola de notificaciones del usuario destinatario.
2. De acuerdo con #819 , se deben establecer los puntos requeridos en el sistema para disparar las notificaciones.
3. Para cada punto de notificación se debe utilizar una plantilla de mensaje única, definida en #819. Además, se deben incluir metadatos señalados y demás información requerida.

**Sub Tareas**

- [x] Implementación de banderas de notificaciones en SISGPLAN.
- [x] Registro de plantillas para puntos de notificación.
- [x] Configuración de plantillas para puntos de notificación.

**Criterios de aceptación**

- [x] Para cada modulo del sistema, se encuentran configuradas una serie de puntos de notificación que envían notificaciones desde el usuario logueado en el sistema hacia el usuario destinatario.
- [x] Cada punto de notificación cuenta con una plantilla personalizada.

**Requerimientos**

- [x] Completar issue #862 .
- [x] Completar issue #819 .

**Dependencias**

- planeacion_cliente.
- notificacion_mid.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
En la PARTE 1, se requiere cubrir puntos de notificación para el Módulo de CONSTRUCCIÓN.

**Comment by a52290451** [comment]
@EdissonFrancisco por favor subir actualización del estado de la actividad.

**Comment by a52290451** [comment]
@EdissonFrancisco por favor subir avances de la actividad.

**Comment by norbeydanilo** [comment]
Documentar issue @diegobauto 

Asociar PR a desarrollo y proceder a paso a Done @a52290451

**Comment by diegobauto** [comment]
Observación: 
Para el item G, en la notificaciones de formulación se tiene lo siguiente:
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/d3318147-4c60-456a-ae78-c5a8cbf57fcd)

Y al revisar los estados de acciones y flujo luego del estado Pre Avalado pasaría a Ajuste prsupuestal:
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/e3aed1aa-fc77-42ee-99a4-eb609bc5b8fe)

Sin embargo, luego de que un plan se esncuentre en estado Pre Aval, se muestran los siguientes botones:
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/de881e80-e510-4ea9-bd11-f4c73043fdcd)
Y al darle "clic" en el boton de "Remitir Ajuste Plan de Acción" el estado del plan pasa nuevamente a En formulación. Por lo que no se cumple lo que indice el mensaje de notificación para el item G (...El plan se encuentra en estado pre avalado.).

**Comment by diegobauto** [comment]
Desarrollo realizado en rama: [feature/notificaciones](https://github.com/udistrital/planeacion_cliente/tree/feature/notificaciones)
Se realiza el pull requets a develop: [Link](https://github.com/udistrital/planeacion_cliente/pull/998)

Tener en cuenta la actualización de la variable de entorno ARM_AWS_NOTIFICACIONES en producción y comprobar las diferentes colas.

**Comment by a52290451** [comment]
El desarrollo se mantendrá en la rama feature hasta completar el proceso de despliegue de las funcionalidades existentes en producción.
