### ISSUE TITLE
0 - 1 Creación de controlador para la consulta de tabla general de resumen para el rol de planeación y unidad modulo de planes de acción - PARTE 2

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#866]
Se requiere realizar la creación de un controlador en planeacion_mid que consulte la información de **todos los planes de acción existentes**, tanto **activos como inactivos**, y los devuelva como respuesta de la petición para una unidad en particular.

**Especificaciones técnicas**

1. La petición principal realizada al controlador tiene un parámetro adicional asociado a la identificación de la unidad (GetAll + ID).
2. Los parámetros que debe recopilar y devolver el controlador por cada registro son:
- Unidad Académica y / o Administrativa (Nombre)
- Vigencia 
- Plan de acción (Nombre)
- Estado del plan de acción (Formulación / Seguimiento / Evaluación)
- Versión en el caso de Formulación (N/A para los demás casos)

**Sub Tareas**

- [x] Desarrollo de controlador en planeacion_mid con servicio GetAll con parámetro de búsqueda.
- [x] Desarrollo de lógica de controlador en Helpers.

**Criterios de aceptación**

- [x] Planeación mid permite realizar la consulta de todos los planes de acción que se encuentren registrados en el sistema asociados a una unidad, sin importar su estado o vigencia.

**Requerimientos**

- [x] Completar issue #849 .

**Dependencias**

- planes_crud.
- planeacion_mid.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by felimarod** [comment]
Se agregan las pruebas funcionales en https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ETDt1607us9LsOohADUMumQBtnhWJ4-SM-UWGc5L3eOZAg?e=AuZQxd

**Comment by a52290451** [comment]
Se validan y aprueban pruebas funcionales realizadas.

**Comment by felimarod** [comment]
Actualizar el swagger, dada la creación de controlador

**Comment by a52290451** [comment]
Swagger Actualizado
