### ISSUE TITLE
0-1 Restricción de planes/proyectos por unidad en su formulación

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#870]
Se requiere implementar el filtrado de planes de acción o proyectos asociados a la unidad correspondiente al usuario (unidad) que ingresa al menú de formulación o seguimiento.

**Especificaciones técnicas**

- Actualmente el desarrollo del aplicativo se encuentra estabilizado en ambiente develop (Cliente, mid y crud).
- En las issues #812 #816 y #817 se estableció una relación a nivel de plan y proyecto para una unidad en particular.

**Sub Tareas**

- [x] Verificar de dónde se trae la información de la dependencia sobre el usuario que pertenece. Se cree que se trae de terceros de una tabla vinculación la cual responde a cuales dependencias pertenece el usuario (Filtrar solo por vinculaciones activas).
- [x] Contrastar con la tabla "periodo_seguimiento" cuales planes o proyectos están asociadas a esa unidad o dependencia.
- [x] Para los menús "Formulación" y "Seguimiento" se debe restringir la selección de planes o proyectos que solo estén relacionados con la dependencia a la que pertenece el usuario que ingresa al sistema.

**Criterios de aceptación**

- [x] El usuario con rol "JEFE_UNIDAD_PLANEACION" o "JEFE_DEPENDENCIA" o "ASISTENTE_DEPENDENCIA" en los menús "Formulación" y "Seguimiento" cuando le dan clic en el select con los planes/proyectos solo debe visualizar los proyectos y planes asociados a esa dependencia. 
- [x] En dado caso que el usuario que ingrese encuentre que no tiene planes/proyectos asociados a su dependencia debe mostrarse un popup que le advierta que todavía no tiene asignado un proyecto/plan para su dependencia correspondiente a la vigencia ______.

**Requerimientos**

- [X] Creación de roles y asignación de permisos tanto en WSO2 como en el api de configuración.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by ccmendezt** [comment]
## Evidencias - Avance 0-1
### 15/02/2024 - 6:00 pm

- Se evidencia el filtro correcto de los planes asociados a una **unidad/dependencia** y **vigencia** seleccionada desde el menú de formulación:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/6c67f82d-96bb-446e-82ef-e68e1b6f3ac7)

- Se contrasta correctamente la información obtenida en periodo-seguimiento mediante expresiones regulares. Para esto, se creó un servicio en **planes_crud** que valida el Id de la unidad correspondiente y trae el registro con los _planes_interes_ asociados a dicha unidad:
     - Implementación método en **_periodo-seguimiento.service.ts_**: 
       ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/44ac90b2-b280-4b4b-ab2e-30329bbf40d1)
     - Funcionamiento en **_Swagger_**: 
       ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/f2bd07e5-2388-4009-92a9-af0dec7d4661)

- El usuario con rol "JEFE_UNIDAD_PLANEACION" o "JEFE_DEPENDENCIA" o "ASISTENTE_DEPENDENCIA" en los menús "Formulación" y "Seguimiento" cuando le dan clic en el select con los planes/proyectos solo debe visualizar los proyectos y planes asociados a esa dependencia:
     - Evidencia de cumplimiento criterio en **Formulación**:
     ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/8c2eb965-051e-452d-a29e-9b756765997b)     
     - Evidencia de cumplimiento criterio en **Seguimiento**:
     ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/605ec3fd-0844-4cc4-b76e-32afe9fb38aa)

- En dado caso que el usuario que ingrese encuentre que _no tiene planes/proyectos_ asociados a su **dependencia** se muestra un popup que le advierta que todavía no tiene asignado un proyecto/plan para su dependencia correspondiente a la _vigencia_ seleccionada.
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/5e18958d-14ce-44aa-a882-12beb12f1500)

**Notas importantes:**
  **i.** En el menú de seguimiento el filtro de planes/proyectos asociados a la unidad logueada ya se estaba realizando anteriormente, por lo cual no fue necesario modificar el componente en cuestión.

**Comment by ccmendezt** [comment]
## Evidencias - Avance 0-1
### 16/02/2024 - 6:00 pm

- Se realizó un push a una rama feature de **planes_crud** que permitió cumplir con los criterios de aceptación de esta issue: 
[Commit **planes_crud**](https://github.com/udistrital/planes_crud/commit/d55150aae69776f38f41e3b7e08e8ddc51f3652d)

**Comment by ccmendezt** [comment]
## Pull Request Asociados a Issue:
- **planeacion_cliente:** https://github.com/udistrital/planeacion_cliente/pull/900
- **planes_crud:** https://github.com/udistrital/planes_crud/pull/91
