### ISSUE TITLE
0-3 Filtro proyecto/plan de acción

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#872]
Se requiere implementar un filtro por proyecto/plan de acción en el menú "Administrar sistema".

**Especificaciones técnicas**

- Actualmente el desarrollo del aplicativo se encuentra estabilizado en ambiente develop (Cliente, mid y crud).

**Sub Tareas**

- [x] Tanto para funcionamiento como seguimiento se debe poder escoger la opción inicial sobre querer filtrar por unidad academica/administrativa o plan acción/proyecto (Actualmente por defecto es unidad y después plan).
- [x] Una vez se habilite esta opción en dado caso de escoger el filtro por unidad se debe dejar el flujo tal y como se encuentra en este momento.
- [x] Una vez se habilite esta opción en dado caso de escoger el filtro por plan/proyecto el flujo cambia dado que debe existir un select que traiga todos los planes de acción/proyectos para la vigencia escogida. Una vez el usuario escoga uno o varios planes/proyectos se desplegara una tabla con todas las unidades que tiene/n en común  esos planes/proyectos escogidos.
- [x] La tabla con las unidades que tengan esos proyectos deberá desplegar usuario que realizó la última modificación y la fecha de la misma.

**Criterios de aceptación**

- [x] En dado caso que el usuario se encuentre en las tablas que relacionen unidades y planes después de oprimir el botón "Planes asociados a unidad" deben visualizarse los campos: usuario y fecha modificación.
- [x] En dado caso que el usuario se encuentre en las tablas que relacionen unidades y planes después de oprimir el botón "Planes asociados a unidad" y no se encuentren planes debe desplegarse un POP UP que informe "Las unidades escogidas no cuentan con planes/proyectos con fechas parametrizadas".

**Requerimientos**

- [x] Ninguno.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by ccmendezt** [comment]
## Evidencias - Avance 0-3 Filtro proyecto/plan de acción
### 29/02/2024 - 14:40 pm

- Se creó el select que permite elegir el filtro deseado por el usuario (Filtro por Unidad y Filtro por Proyecto/Plan de acción):
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/0ddd19cb-a873-438d-a83f-279021f60470)

- Dado que se estaba sobrecargando el frontend para mostrar los planes/proyectos asociados a las unidades seleccionadas por el usuario en el filtro por unidad. Se creó un nuevo método _(aún en desarrollo)_ dentro del controlador de **formulación** que permita enviarle las _unidades_interes_ seleccionadas por el usuario para así compararlas y saber si tienen o no _planes_interes_ en común:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/4334847b-73ad-45cd-b0dc-33a6ca51798f)
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/aee432a3-13bd-444d-8ceb-97dd8b861d58)

## Notas importantes:
  **i.** Actualmente se está corrigiendo el guardado de los registros en la tabla periodo-seguimiento en la API CRUD asociados a la vigencia y proceso seleccionado para así poder realizar los filtros correctamente.

**Comment by ccmendezt** [comment]
## Evidencias - Avance 0-3 Filtro proyecto/plan de acción
### 13/03/2024 - 11:14 am

- Se evidencia el correcto funcionamiento de los filtros desde el cliente:
![filtros](https://github.com/udistrital/planeacion_cliente/assets/82072560/a3dcbd4c-4c75-449a-96fd-af20f9a7286e)
- Se evidencia el correcto funcionamiento en los casos que no encuentra registros con fechas parametrizadas:
![filtro no encontrado](https://github.com/udistrital/planeacion_cliente/assets/82072560/66e65111-74d7-4b59-953b-46780ba0e978)

- **Pull Request asociado a issue:** https://github.com/udistrital/planeacion_cliente/pull/947
