### ISSUE TITLE
HU2 - 1 Consulta de usuario por roles y correo PT1

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#873]
Se requiere implementar [HU2 - 1](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/resanchezc_udistrital_edu_co/EYc_4k5TayBEgwWaq2wQt9UBOxFJ-y2a-Z_lj5bsjlDkUQ?wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1706125306937&web=1), relacionada con la consulta de usuarios por rol y correo electrónico.

Descripción: **Como** rol planeación **quiero** realizar la Consulta por correo y roles **para** observar un usuario en particular o una lista de usuarios que  obedezcan a diferentes características.

**Especificaciones técnicas**

- Actualmente el desarrollo del aplicativo se encuentra estabilizado en ambiente develop (Cliente, mid y crud).

**Sub Tareas**

- [x] Adicionar submenú "Gestión Usuarios" en el menú "Construcción" con permiso de acceso para el rol "PLANEACION", lo anterior realizandose en el [api de configuración](https://pruebasconfiguracion.portaloas.udistrital.edu.co/) en entorno de pruebas con el usuario pruebasoas1.
- [x] Crear un mockup asociado al submenú "Gestión Usuarios" el cual debe contener dos campos de filtro el primero tipo texto para consultar un usuario por un correo electrónico y otro un select que contenga todos los roles asociados a planeación (PLANEACION, JEFE_DEPENDENCIA_PLANEACION, JEFE_DEPENDENCIA y ASISTENTE_DEPENDENCIA). Además, debe existir un botón que se llame "Consultar usuario", el cual generará la acción de búsqueda de usuarios que contengan dichos filtros. Posteriormente debe desplegarse visualemnte una tabla con los registros asociados a los filtros diligenciados por el usuario. Los campos de la tabla son: nombre usuario, correo, permisos. Finalmente debe existir un botón "Limpiar".
- [x] Crear el componente visual en angular asociado al mockup realizado y aprobado.

**Criterios de aceptación**

- [x] Mockup realizado
- [x] Acceso al menú submenú "Gestión Usuarios" en el menú "Construcción" desde el rol "PLANEACION"
- [x] Documentación del issue con el avance del desarrollo del componente.

**Requerimientos**

- [x] Servicio de consulta usuarios WSO2.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by milo19980525** [comment]
Los endpoints se encuengtran en el api de autenticacion_mid: https://autenticacion.portaloas.udistrital.edu.co/store/apis/info?name=autenticacion_mid&version=v1&provider=admin&tenant=carbon.super#!/token/TokenController_GetEmail

getEmail y addRole

**Comment by ccmendezt** [comment]
## Evidencias - Avance HU2 - 1 Consulta de usuario por roles y correo PT1
### 29/02/2024 - 14:20 pm

- Se creó el **mockup** asociado a la _Historia de Usuario_ con las siguientes _vistas_:
    - **Componente Menú principal:**
    ![(0) Mockup Consulta de usuario por roles y correo-Componente Menú](https://github.com/udistrital/planeacion_cliente/assets/82072560/0248e16f-2cff-4f51-838a-b52d710b03c1)

    - **Componente Consulta de Usuarios por Email/Roles:**
        - _Ejemplo 1:_
        ![(1) Mockup Consulta de usuario por roles y correo-Componente - Consulta Usuarios Ej  1](https://github.com/udistrital/planeacion_cliente/assets/82072560/3fbee490-d8df-4f65-9918-d1a976a95349)

        - _Ejemplo 2:_
        ![(2) Mockup Consulta de usuario por roles y correo-Ej  2 - Consulta Usuarios](https://github.com/udistrital/planeacion_cliente/assets/82072560/c3830cb5-b79a-4982-9577-91300c04767f)

- Se adicionó submenú **"Gestión Usuarios"** en el menú **"Construcción"** con permiso de acceso para el rol **"PLANEACION"**, lo anterior realizándose en el [_api de configuración_](https://pruebasconfiguracion.portaloas.udistrital.edu.co/) en entorno de pruebas con el usuario _pruebasoas1_:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/4a158b81-d5a0-41c8-be3f-9b77816a5b86)

**Comment by ccmendezt** [comment]
## Evidencias - Avance **HU2 - 1 Consulta de usuario por roles y correo PT1**
### 15/03/2024 - 15:50 pm

- Se implementó el **componente visual en Angular** asociado al mockup realizado y aprobado:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/2b78a49c-f6af-452c-bdcc-46f75707f5c3)

- Se agregó el campo de digitación de **correo electrónico** con validaciones en front para que acepte correos electrónicos _válidos_:
     - **Caso correo electrónico válido:**
     ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/7aa44233-6f8d-4cec-84e5-bd594dbff418)

     - **Caso correo electrónico inválido:**
     ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/4a2ea4ba-c42f-46b4-98fd-2ad96aeb5466)

     - **Caso correo electrónico obligatorio:**
     ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/5a03da0b-ba28-406b-9689-72d7b63967d4)

- Se agregó una _lista desplegable_ **(sin ninguna funcionalidad habilitada aún)** que permite seleccionar los roles asociados al sistema SISGPLAN para realizar búsqueda de usuarios por _roles_:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/6e4c28c6-470e-4b1f-9cfc-3ceedeb9fb74)

- Para buscar el usuario por correo electrónico, se debe diligenciar completa y correctamente el formulario, de lo contrario no se habilitará el botón **buscar**:
     - **Caso botón NO habilitado:**
     ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/b64999f1-1302-42fc-81ce-89690cc71012)

     - **Caso botón habilitado:**
     ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/31e0c740-d951-47b6-a8a2-19aeabc41c84)

- Se implementó el botón de **limpiar** que vacía automáticamente todo el formulario.

- **Prueba de flujo completo:**
![consulta-usuarios](https://github.com/udistrital/planeacion_cliente/assets/82072560/80df39de-1687-475f-9bee-d311c9334eb3)

## Notas importantes:
  **i.** Seleccionar el rol dentro de la lista desplegable NO tiene ninguna funcionalidad asociada a la búsqueda de usuarios aún, ya que se espera habilitar la funcionalidad próximamente.

**Comment by milo19980525** [comment]
Excelente trabajo, queda pendiente inhabilitación de campo obligatorio "rol"
