### ISSUE TITLE
HU2 - 2 Edición de roles usuario PT1

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#874]
Se requiere implementar [HU2 - 2](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/resanchezc_udistrital_edu_co/EYc_4k5TayBEgwWaq2wQt9UBOxFJ-y2a-Z_lj5bsjlDkUQ?wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1706125306937&web=1), relacionada con la edición de roles de usuarios.

Descripción: **Como** rol planeación **quiero** Quiero realizar la Asignación de Roles  Específicos a un usuario **para** para poder actualizar los roles de un usuario registrado en el sistema.

**Especificaciones técnicas**

- Actualmente el desarrollo del aplicativo se encuentra estabilizado en ambiente develop (Cliente, mid y crud).
- Se debe partir de la issue #873.

**Sub Tareas**

- [x] En el componente realizado en #873 adicionar en cada registro de la tabla una acción de edición "ícono lapiz".
- [x] A la acción edición desplegar un listado de roles asociados al usuario al lado izquierdo (los que ya tiene) y al lado derecho los que puede asignar "PLANEACION" que son: PLANEACION, JEFE_DEPENDENCIA_PLANEACION, JEFE_DEPENDENCIA y ASISTENTE_DEPENDENCIA (solo listar de estos los que no tenga el usuario), por lo que se puede generar dos acciones (vincular y desvincular) realizandose de la misma manera que en el api de configuración.
Ejemplo: 
![image](https://github.com/udistrital/planeacion_cliente/assets/106636533/3d02b4b1-167d-458f-8886-210dcabe1b6e)

**Criterios de aceptación**

- [x] Dado que Un administrador realiza la búsqueda de usuarios por medio del campo de búsqueda, al encontrar el usuario especifico, cuando elige la opción "edición" gestiona los roles del usuario y le da guardar, entonces se atualiza la tabla de usuarios y en la columna roles se refleja el cambio. 

**Requerimientos**

- [x] Servicio de edición usuarios WSO2.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by ccmendezt** [comment]
## Evidencias - Avance HU2 - 2 Edición de roles usuario
### 21/03/2024 - 12:45 pm

- Se adicionó a cada registro de la tabla un **botón** con _ícono de lápiz_ para la edición de los roles de usuarios del sistema:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/b01f97fd-eb96-4dfb-a9ae-4e01e8c5d925)

- Al realizar la acción de **edición** se despliega un listado de _roles asociados al usuario_ al lado izquierdo (los que ya tiene) y al lado derecho los que puede asignar (cumpliendo los criterios dados en la subtarea):
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/8bf8c6ab-2b85-4ceb-a11a-40e350f52bd0)

- Al seleccionar un _rol_ para **vincular/desvincular** y oprimir su respectivo botón se muestra un cuadro de diálogo para asegurar la agregación/eliminación del rol o roles:
    - **Vincular rol:**
    ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/0538e485-9311-42a1-96ad-8b9dc832503c)

   - **Desvincular rol:**
   ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/7d5f8f3a-5065-4ca2-b7fa-2ffbd8f0b7b0)

- En caso de **cancelar la acción** se muestra un **popup** informativo diciendo que _la acción se canceló_:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/8c46bb31-58cb-45df-853d-fd02f48ee8a4)

- **Flujo completo:**
![gestion-usuarios](https://github.com/udistrital/planeacion_cliente/assets/82072560/7593cf33-c009-4208-a4e9-8c6d42b57d2d)

En el gif anterior se muestra el flujo completo y el correcto funcionamiento del componente visual, además, también se muestra que el componente desarrollado en completamente responsive.

## Notas importantes:
  **i.** Aún no se implementa la agregación/eliminación de roles persistiendo los datos en la base de datos ya que se está esperando información sobre los **endpoints** a los que se debe apuntar y el _formato del body correcto_ para realizar dichas peticiones.

**Comment by ccmendezt** [comment]
## Pull Request Asociados a Issue
### 27/03/2024 - 17:05

Se realizó un _commit_ y _push a rama feature_ con todos los cambios documentados en esta issue:

- **Pull Request _planeacion_cliente_:** https://github.com/udistrital/planeacion_cliente/pull/955

**Comment by milo19980525** [comment]
La continuación de la edición de roles se hará en #956
