### ISSUE TITLE
3-1 administración parámetros generales

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#875]
Se requiere implementar la administración de datos paramétricos en el sistema.

**Especificaciones técnicas**

- Actualmente el desarrollo del aplicativo se encuentra estabilizado en ambiente develop (Cliente, mid y crud).

**Sub Tareas**

- [x] Adicionar submenú "Gestión Parámetros" en el menú "Construcción" con permiso de acceso para el rol "PLANEACION", lo anterior realizandose en el [api de configuración](https://pruebasconfiguracion.portaloas.udistrital.edu.co/) en entorno de pruebas con el usuario pruebasoas1.
- [x] Crear un mockup asociado al submenú "Gestión Parámetros" el cual debe contener una tabla con cuatro columnas (Concepto, valor, vigencia y edición - icóno de lápiz). Además, al final de la tabla debe existir un botón que se llame "Crear Parámetro", el cual generará la acción de desplegar un formulario con los campos (Nombre (texto), valor (numérico), vigencia (select con años)). Posteriormente se debe desplegar un botón "Guardar". Finalmente debe existir un botón "Limpiar".
- [x] Crear el componente visual en angular asociado al mockup realizado y aprobado.
- [x] Asociar la tabla a un endpoint de parámetros que traiga los parámetros asociados a SISGPLAN (Generar un nuevo tipo en el api de parámetros).
- [x] Asociar la acción "Guardar" a una petición que guarde el parámetro diligenciado (Verificar que todos los campos estén diligenciados).
- [x] Asociar la acción de Limpiar para que oculte el formulario de creación.
- [x] La acción edición (lapíz) debe permitir cambiar en la tabla los valores del parámetro seleccionado y debe habilitarse el botón "Guardar en la parte inferior" que ejecute la actualización del parámetro escogido.

**Criterios de aceptación**

- [x] Dado que Un administrador desea visualizar una lista de todos los parámetros del sistema Cuando Accede al menú "Gestión Parámetros", visualiza una tabla con los parámetros generales del sistema.
- [x] Dado que un usuario con rol PLANEACION se encuentra en el sistema y accede al menpu "Gestión Parámetros" Cuando oprime el botón crear, se despliega un formulario con la información requerida para adicionar un parámetro y digita los valores correspondientes en todos los campos y da clic en "Guardar" entonces se genera un popup confirmando el registro.
- [x] Dado que un usuario con rol PLANEACION se encuentra en el sistema y accede al menpu "Gestión Parámetros" Cuando oprime el botón crear, se despliega un formulario con la información requerida para adicionar un parámetro y NO digita los valores correspondientes en todos los campos y da clic en "Guardar" entonces se genera un popup mencionando que los campos no se diligenciaron completamente.
- [x] Dado que un usuario con rol PLANEACION se encuentra en el sistema y accede al menpu "Gestión Parámetros" Cuando oprime el botón crear, se despliega un formulario con la información requerida para adicionar un parámetro y digita los valores correspondientes en todos los campos y da clic en "Guardar" pero no se almacena la información en la base de datos entonces se genera un popup mencionando que no se almacenó el registro por fallas en el servicio, intente nuevamente más tarde.
- [x] Dado que un usuario con rol PLANEACION se encuentra en el sistema y accede al menpu "Gestión Parámetros" Cuando oprime el botón editar en un registro (Lápiz), se habilita en la tabla la opción de editar los valores del registro escogido, el usuario diligencia los campos correctamente y da clic en "Guardar" pero no se almacena la información en la base de datos entonces se genera un popup mencionando que no se almacenó el registro por fallas en el servicio, intente nuevamente más tarde.
- [x] Dado que un usuario con rol PLANEACION se encuentra en el sistema y accede al menpu "Gestión Parámetros" Cuando oprime el botón editar en un registro (Lápiz), se habilita en la tabla la opción de editar los valores del registro escogido, el usuario NO diligencia los campos correctamente y da clic en "Guardar" entonces se genera un popup mencionando que los campos no se diligenciaron completamente.
 - [x] Dado que un usuario con rol PLANEACION se encuentra en el sistema y accede al menpu "Gestión Parámetros" Cuando oprime el botón editar en un registro (Lápiz), se habilita en la tabla la opción de editar los valores del registro escogido, el usuario diligencia los campos correctamente y da clic en "Guardar" pero no se almacena la información en la base de datos entonces se genera un popup confirmando la actualización.

**Requerimientos**

- [x] Servicio de consulta usuarios WSO2.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by ccmendezt** [comment]
## Evidencias - Avance 3-1 _Administración parámetros generales_
### 20/02/2024 - 8:55 am

- Se creó el mockup asociado al submenú "Gestión Parámetros" el cual debe contener una tabla con cuatro columnas (Concepto, valor, vigencia y edición - icóno de lápiz):
    - Vista principal de **_visualización de parámetros_**:
      ![Mockup administración parámetros generales-Tabla Visualización Parámetros](https://github.com/udistrital/planeacion_cliente/assets/82072560/bf51fec2-b60f-448d-bc6a-232ba339ae9f)
    - Vista de componente de **_edición de parámetro_** (dentro del componente principal):
      ![Mockup administración parámetros generales-Formulario Edición Parámetro](https://github.com/udistrital/planeacion_cliente/assets/82072560/a8105c48-5eb8-4a40-9bf3-99419bccc5e1)

### Notas importantes:
i. Se aprobó el mockup por parte del **SM/Líder Técnico** y se da inicio al desarrollo de la funcionalidad.

**Comment by ccmendezt** [comment]
## Evidencias - Avance 3-1 _Administración parámetros generales_
### 22/02/2024 - 10:20 pm

Los siguientes registros creados en la base de datos especificada a continuación se utilizaron para asociar los parámetros que el usuario como rol **PLANEACIÓN** agregará o actualizará:
- Se agregó el registro en la tabla _area_tipo_ del esquema **parametros** de la base de datos **_udistrital_core_** utilizando la siguiente sentencia **SQL**:
```sql
INSERT INTO parametros.area_tipo(nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion)
	VALUES ('Planeación', 'Parámetros del Sistema de Planeacion y Seguimiento a la Gestión SISGPLAN',
		'PL_SISGPLAN', true, 0, '2024-02-20 17:02:37.814455', '2024-02-20 17:02:37.814455');
```
- Se agregó el registro en la tabla _tipo_parametro_ del esquema **parametros** de la base de datos **_udistrital_core_** utilizando la siguiente sentencia **SQL**:
```sql
INSERT INTO parametros.tipo_parametro(nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion, area_tipo_id)
	VALUES ('Sistema de Planeacion y Seguimiento a la Gestión', 'Parámetros del Sistema de Planeacion y Seguimiento a la Gestión SISGPLAN',
		'P_SISGPLAN', true, 0, '2024-02-20 17:02:37.814455', '2024-02-20 17:02:37.814455', 22);
```
- Se creó el componente **_gestion-parametros_** que permite observar en una tabla los parámetros asociados al sistema **SISGPLAN** asociándose al endpoint correspondiente. También se incluyó el ícono de **_editar_**:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/b4bbf592-0204-4a13-8de6-c2fd45b59626)

- El botón de **_agregar_** despliega un **formulario** en la parte _inferior_ del apartado que permite escribir los campos _Concepto_, _Valor_ y _Vigencia_ del **parámetro** que el usuario desea crear:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/85b406f3-ff96-4f2b-939f-a87bd4aa2b45)

- El ícono de **editar** despliega un formulario en la parte inferior del apartado que permite actualizar los campos _Concepto_, _Valor_ y _Vigencia_ del parámetro seleccionado:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/a50c9465-ab84-44a7-9f4c-d54808d2e099)

- El botón de **_limpiar_** oculta automáticamente el formulario de edición/adición:
![limpiarForm](https://github.com/udistrital/planeacion_cliente/assets/82072560/d708e739-2be7-41e6-916a-4d048ebdff72)

- **Flujo de creación de parámetro correcto:**
![creacionParametro](https://github.com/udistrital/planeacion_cliente/assets/82072560/0b9b3a63-2b94-4a5f-ab48-79ead09b502c)

- **Flujo de actualización de parámetro correcto:**
![actualizacionParametro](https://github.com/udistrital/planeacion_cliente/assets/82072560/68dcdda1-5ff4-4e6d-895c-cbe6c28cb07b)

- **Flujo de creación de parámetro generando error:**
![errorCreacion](https://github.com/udistrital/planeacion_cliente/assets/82072560/99355df0-aa93-4c6b-8663-7b8a656e924e)

- **Flujo de actualización de parámetro generando error:**
![errorActualizacion](https://github.com/udistrital/planeacion_cliente/assets/82072560/88af08b5-c1d0-413f-a900-c92d3deb0b44)

- El formulario no permite accionar el **botón Guardar** si los campos no están diligenciados correctamente:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/c41818c9-3cf6-4629-a31b-6c85857be2a5)

- En caso de que se edite el campo y se deje vacío muestra textos en rojo señalando que los campos son obligatorios:
![Caso1](https://github.com/udistrital/planeacion_cliente/assets/82072560/c4867ddc-1523-4e05-a2a4-e1c974b76e58)
![Caso2](https://github.com/udistrital/planeacion_cliente/assets/82072560/dfa11fd1-d914-4642-97e1-b95408d28c12)

## Notas importantes:
  **i.** A continuación encontrará el script SQL utilizado para la inserción de datos en la base de datos: [script_sql.zip](https://github.com/udistrital/planeacion_cliente/files/14381204/insert_parametros.zip)
  **ii.** Para la prueba de los flujos de creación y actualización con error, se estableció un dato dentro del cuerpo de la petición en nulo, provocando así el error en la misma.

**Comment by ccmendezt** [comment]
## Evidencias - Avance 3-1 _Administración parámetros generales_
### 23/02/2024 - 11:40 pm

- Se agregó el **ícono (basura)** de **_inactivar parámetro_** junto con su funcionalidad:
![inactivarParametro](https://github.com/udistrital/planeacion_cliente/assets/82072560/1481d289-7d68-47ec-b010-990c1d1d72bb)
