### ISSUE TITLE
4 - 1 Crear controlador en planeacion_mid para actualización de la estructura de una plantilla en utilización en fase de formulación. - PARTE 1

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#876]
Se requiere implementar un controlador en planeacion_mid que realice la actualización de la plantilla de planes de acción en formulación, modificada en el modulo de construcción. La modificación solo aplicará sobre planes que se encuentren en fase de formulación.

**Especificaciones técnicas**

1. En el módulo de construcción se realiza la modificación de una plantilla de plan de acción que actualmente esta siendo utilizada por las unidades en el módulo de formulación en planes de acción. Una vez se actualice su estructura, esta también debe actualizarse sobre los planes que estén en formulación.
2. Los cambios no deben aplicarse sobre planes que hayan superado la etapa de formulación.
3. El ajuste debe mantener la información diligenciada por el usuario en la plantilla original, eliminando los campos no requeridos y agregando con espacios vacíos aquellos que sean nuevos.
4. El controlador debe recibir el id de la plantilla modificada, realizar una consulta para identificar todas las que están en fase de formulación y aplicar lógica predeterminada para realizar los cambios correspondientes en cada una.

**Sub Tareas**

- [x] Creación de controlador en planeacion_mid.
- [x] Consulta de todos los planes de acción por ID en fase de formulación desde el nuevo controlador en planeacion_mid.
- [x] Lógica para ajuste de plantilla en planes de acción en formulación consultados.

**Criterios de aceptación**

- [x] Una vez se modifique la plantilla de un plan de acción en el modulo de construcción, los planes de acción que se encuentran en formulación son ajustados al formato de la plantilla modificada.
- [x] Cuando la unidad ingresa al modulo de formulación en planes de acción, puede ver su plan de acción ajustado a la nueva plantilla del mismo.

**Requerimientos**

- No presenta

**Dependencias**

- planeacion_cliente.
- planeacion_mid.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
@diegobauto Actualizar documentación del desarrollo de la issue.

**Comment by diegobauto** [comment]
Rama en donde se esta llevando a cabo el desarrollo:
[feature/actEstPlantilla](https://github.com/udistrital/planeacion_mid/tree/feature/actEstPlantilla)

Capturas (evidencias):
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/0ad4820f-fad5-4e20-a5db-4e3b447613a5)
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/fa0c6f80-1ef4-48b7-a478-e5b0a4ce8d3b)
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/8021fb54-0fd5-4549-b00d-f11a681db742)
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/ede3d1bc-c0cf-4530-863d-7321d949ade4)
...

**Comment by a52290451** [comment]
Se da por terminado la PARTE 1.
