### ISSUE TITLE
4 - 2 Ajuste lógica de componentes en el cliente asociados a la modificación de plantillas de planes de acción en formulación.

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#877]
Se requiere realizar los ajustes necesarios en planeacion_cliente para consumir el controlador implementado en #876 , y actualizar la estructura de todos los planes de acción que se encuentren en fase de formulación.

**Especificaciones técnicas**

1. Tras realizar la actualización de la estructura de una plantilla en el módulo de **Construcción**, se requiere consumir el controlador, pasando como parámetro el ID de la plantilla modificada.
2. Se debe crear un proceso de **rollback** en el que se garantice la actualización de todos los planes de acción en fase de formulación asociados a la plantilla modificada.
3. Para el modulo de formulación en planes de acción, una vez se elija y se cargue el plan de acción modificado, se debe garantizar que este se encuentre con los ajustes realizados en el controlador **(REVISAR FLUJO)**.
4. Para los planes de acción ya creados que no tengan la Referencia a la plantilla original, deberá implementarse una lógica en el modulo de construcción para que no se actualicen.

**Sub Tareas**

- [x] Ajuste del módulo de construcción para consumir el controlador #876 una vez se realicen las modificaciones en la plantilla correspondiente.
- [x] Creación de proceso de **Rollback** asociado a la actualización de planes de acción en formulación, para garantizar paridad en los registros.
- [x] Revisión y ajuste del flujo de carga de planes de acción en formulación, de tal forma que se vean reflejados los cambios realizados en la plantilla base.

**Criterios de aceptación**

- [x] Tras realizar una modificación en una plantilla de plan de acción, se realiza una petición a planeacion_mid para actualizar los planes de acción en formulación relacionados con la plantilla.
- [x] Se garantiza que, cuando una plantilla de plan de acción es modificada, también se modifican los planes de acción en formulación relacionados.
- [x] Cuando se ingresa a planes de acción en formulación y se selecciona el plan de acción cuya plantilla a sido modificada, se reflejan los cambios manteniendo la información original.

**Requerimientos**

- Completar #876 .

**Dependencias**

- planeacion_cliente.
- planeacion_mid.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Se realizarión modificaciones en planeacion_mid, para correción al marcar un nivel como inactivo: 
[feature/clientActPlanes](https://github.com/udistrital/planeacion_mid/tree/feature/clientActPlanes)

Además se realizó el consumo del controlodar por parte del cliente: 
[feature/clientActPlanes](https://github.com/udistrital/planeacion_cliente/tree/feature/clientActPlanes)

Por otro lado, se realizarón las pruebas funcionales:
[Link](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EfAXnurdJEZLvJGn7FM59V8B5mvEnCarInXUCKiXTDS4yQ?e=SVTXr2)

**Comment by a52290451** [comment]
Queda pendiente aprobación de pruebas funcionales

**Comment by a52290451** [comment]
Se aprueban pruebas funcionales realizadas
