### ISSUE TITLE
0-2 Creación de componente para la consulta de tabla general de resumen para el rol de planeación y unidad modulo de consulta de planes de acción

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#878]
Se requiere crear una vista que se relacione con la consulta general de planes de acción para los roles de PLANEACION, JEFE_DEPENDENCIA, ASISTENTE_DEPENDENCIA, JEFE_UNIDAD_PLANEACION.

**Especificaciones técnicas**

- Actualmente el desarrollo del aplicativo se encuentra estabilizado en ambiente develop (Cliente, mid y crud).
- Esta tarea es consecuente con la issue #866.

**Sub Tareas**

- [x] Adicionar permisos al submenú "Consultar Planes" en el menú "Plan de acción" con permiso de acceso para los roles " PLANEACION, JEFE_DEPENDENCIA, ASISTENTE_DEPENDENCIA, JEFE_UNIDAD_PLANEACION", lo anterior realizandose en el [api de configuración](https://pruebasconfiguracion.portaloas.udistrital.edu.co/) en entorno de pruebas con el usuario pruebasoas1.
- [x] Crear un mockup asociado al submenú "Consultar Planes de Acción" el cual debe contener una tabla con los campos : Unidad Académica y / o Administrativa (Nombre), Vigencia, Plan de acción (Nombre), Estado del plan de acción (Formulación / Seguimiento / Evaluación) y una lupa para acceder a la información específicas de cada plan.
- [x] Crear el componente visual en angular asociado al mockup realizado y aprobado. En esta issue no es necesario asociar el componente con la petición del mid.

**Criterios de aceptación**

- [x] Se evidencia acceso de los roles PLANEACION, JEFE_DEPENDENCIA, ASISTENTE_DEPENDENCIA, JEFE_UNIDAD_PLANEACION al submenú "Consultar Planes".
- [x] El mockup diseñado es aprobado.
- [x] Se evidencia en el componente asociado al submenú "Consultar Planes" visualizandoce una tabla con datos dummy.

**Requerimientos**

- Completar issue #849 .
- Completar issue #866 .

**Dependencias**

- planeacion_cliente.
- planeacion_mid.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by felimarod** [comment]
Se propone el mockup, bastante similar al de la issue #815 

[Link](https://www.figma.com/proto/F5ZE2llLnHeA7mJK98RfJw/UD-team-library?type=design&node-id=2390-303&t=rnjCcCC8UhmPvjEp-1&scaling=scale-down&page-id=2390%3A290&mode=design)

![image](https://github.com/udistrital/planeacion_cliente/assets/85894335/61e61edd-cd13-48da-918f-c17b639156b3)

**Comment by a52290451** [comment]
Se proporciona usuario de pruebas a @felimarod para ingresar a configuración.

**Comment by a52290451** [comment]
@felimarod Con lo referente al mockup, se requiere incluir un campo adicional que haga alusión al estado interno de cada plan, ya sea que se encuentre en formulacion o en seguimiento

**Comment by felimarod** [comment]
Mockup ajustado:
![image](https://github.com/udistrital/planeacion_cliente/assets/85894335/a7f17a67-e4cc-442e-9dd7-bc8d9dec11c5)

Se realizaron ajustes en el MID para que se traiga la información directamente

**Comment by a52290451** [comment]
Se requiere realiza un ajuste final:

El "Estado del Plan" debe nombrarse como "Fase" y debe ser anterior a la casilla "Estado" y posterior a "Versión"

**Comment by a52290451** [comment]
@felimarod se requiere subir evidencia de las demás actividades, gracias.

**Comment by felimarod** [comment]
Ajustes realizados:
![image](https://github.com/udistrital/planeacion_cliente/assets/85894335/7ae0fe54-c33f-45e8-bd53-f5aad8a7b43f)

**Comment by felimarod** [comment]
(Pruebas funcionales)[https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EditWYMuq9tLuheDIsNQu-QBokWMuK5fijLJ6DN8muf3Yg?e=9IVx1a]

**Comment by a52290451** [comment]
Se validan y aprueban pruebas funcionales realizadas
