### ISSUE TITLE
HU6 - Vista pendientes por aprobar (Jefe dependencia) PT2

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#879]
Se requiere implementar la parte dos de la [HU 6](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ERnXVlOzYglGiQxvKqRZ7SkBXK6kdFyl6mB6wnqyf3Kpag?e=0rksLc) - HU 1-2, relacionada con la preaprobación de planes por parte del jefe de la unidad.

Descripción: **Como** rol jefe de unidad **quiero** ver una lista de todos los verificación pendientes de aprobación para los proceso de **seguimiento para** poder visualizar y generar la verificación necesarios según los pendientes. Y acceder a cada verificación desde la lista de pendientes.

**Especificaciones técnicas**

- Actualmente el desarrollo del aplicativo se encuentra estabilizado en ambiente develop (Cliente, mid y crud).
- [Diagrama de estados](https://drive.google.com/file/d/1_Tg0AS8WAGgvqAOjw3H6p28wah1Ovc_V/view?usp=sharing)

**Sub Tareas**

- [x] En la vista para la consulta de aprobaciones pendientes de funcionamiento e inversión traer aquellos planes/proyectos asociados a inversión teniendo en cuenta que estos se evaluan por trimestres.
- [x] La nueva vista debe contener una tabla con todas aprobaciones pendientes de seguimiento. Por lo tanto debe crear un servicio (CRUD) que contenga todos los planes/proyectos de seguimiento con un parámetro de búsqueda que sea la/s unidad/es a las que pertenezca el jefe.
- [x] Inicialmente la tabla debe mostrar aquellos planes de acción que se encuentran en estado "En reporte"  o por lo menos traer primero aquellos que tengan ese estado (orden).
- [x] Puede existir la opción de contar con un menú llamado (Seguimiento) para diferenciar los planes/proyectos de formulación y tomar la misma estructura de tabla expuesta en el módulo de seguimiento que filtra por plan.
![image](https://github.com/udistrital/planeacion_cliente/assets/106636533/ee010bcd-2a48-44e4-8de5-83fdfd9f4c21)

**Criterios de aceptación**

- [x] Cuando el jefe de unidad Accede al sistema, en el menú de "Pendientes". Visualiza información relevante sobre cada  plan en fase de seguimiento (Vigencia, plan de acción, versión, estado). 
- [x] Por cada uno de los registros debe existir un botón que genere la acción de revisar la aprobación (relacionado con la issue #821 )

**Requerimientos**

- [x] Creación de roles y asignación de permisos tanto en WSO2 como en el api de configuración.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by C0C045** [comment]
# Avance Vista Planes Pendientes en Seguimiento
1. Se modifico el menú de "Pendientes" para que desplegará dos hijos para las diferentes tablas de Formulación y Seguimiento (**Planes pendientes en Formulación** y **Planes pendientes en Seguimiento**).
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/373c142a-4768-40fd-bcbf-272e38320669)

2. **Primera vista al entrar al submenú "Pendientes -> Planes pendientes en Seguimiento":** Se implementó un select menú para controlar el tema de las unidades a cargo del jefe de unidad, por otro lado, se quito el filtrado para estado, ya que todos los planes tendrán un estado anterior al verificado.
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/7b12489a-bcc6-443c-8464-c63dee7ab004)

3. Una vez, seleccionada la unidad carga todos los planes de **seguimiento** con verificación pendiente de cada trimestre.
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/46f1f470-139d-4411-95ec-68c0a3b49a77)

**Comment by C0C045** [comment]
# Versión final de Planes Pendientes en Seguimiento.
1. Se implementó el apartado de acción (lupa) para redirigir a la vista de verificación del plan seleccionado.
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/1faa5794-8e7e-4cc9-b43c-80e117681b65)

2. Al dar click en regresar en la vista de verificación vuelve a la lista de planes pendientes en seguimiento.
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/23c7b502-18b3-4dbd-a7a0-ef9e8151c4f5)
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/ee7e373b-61bb-469d-83f2-57d1afa6fe61)

3. Por último, al redirigir a la vista de un plan pendiente de verificar en formulación, entonces, se oculta el formulario de selección de unidad, vigencia y plan.
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/5085cb47-bc8f-4216-a446-33157e9bf5f7)

**Comment by C0C045** [comment]
# PR's
En rama mid: https://github.com/udistrital/planeacion_mid/pull/486
En rama cliente: #894
