### ISSUE TITLE
Creación API planeacion_formulacion_mid PT2

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#880]
Se requiere crear el API **PLANEACION_FORMULACION_MID** con base en el API **PLANEACION_MID**, de forma tal que los controladores asociados queden desacoplados del API principal.

**Especificaciones técnicas**

1. El repositorio para **PLANEACION_FORMULACION_MID** es: https://github.com/udistrital/planeacion_formulacion_e_inversion_mid/tree/feature/planeacion_formulacion
2. Se requiere migrar el código asociado a Formato, del API **PLANEACION_MID** al API **PLANEACION_FORMULACION_MID**.
3. El API debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevas APIs GO definidos por la OATI.
4. Los métodos de utilidades que son globales a todas las APIs deben ser migrados a la librería **utils_oas**.
5. Se debe optimizar el código migrado, eliminando malas practicas de desarrollo.
6. La primera parte asociada a esta creación del API se encuentra en: https://github.com/udistrital/planeacion_cliente/issues/852

**Sub Tareas**

- [x] Desarrollo de API **PLANEACION_FORMULACION_MID**
- [x] Migración de código entre APIs (controladores faltantes - inversión/ acabar funcionamiento).
- [x] Optimización de código.
- [x] Pruebas unitarias
- [x] Pruebas funcionales

**Criterios de aceptación**

- [x] El API se encuentra desarrollada y probada.
- [x] El código fuente del API está optimizado.

**Requerimientos**

- [x] Completar Issue #803 .

**Dependencias**

- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
Se desarrollaron casi en su totalidad las 42 pruebas unitarias para la API de planeacion_formulacion_mid, sin embargo, con algunos put o consultar donde requieren el ingreso de un archivo JSON, no se pudo deducir mediante el código, ya que dentro del mismo realiza muchos movimientos con los datos.

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/f61119e9-387d-4e6b-8e58-f30655691f76)

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/73e590c8-1e9d-473a-b6d2-a818374ab251)
