### ISSUE TITLE
3 - 3 Pruebas funcionales - componente "Identificación docente"

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#884]
Se requiere realizar pruebas funcionales asociadas al componente de **Identificación Docente** en Formulación, planes de acción de funcionamiento, de tal forma que se cubran todos los cálculos asociados al componente por cada tipo de docente.

**Especificaciones técnicas**

1. Se deben realizar pruebas a cada calculo realizado en el componente de **Identificación Docente**, de tal forma que se cubran todos los elementos del mismo y se garantice su integridad.
2. Se deben resolver errores o bugs encontrados durante las pruebas realizadas, como por ejemplo, campos sin limitación, cálculos erróneos, etc.
3. El componente debe ser intuitivo y fácil de utilizar por el usuario por lo que se requiere garantizar un adecuado control y manejo de errores, señalando claramente cuando un elemento debe ser llenado o cuando a sido diligenciado erróneamente.

**Sub Tareas**

- [x] Pruebas funcionales sobre planeacion_mid y planeacion_cliente, cubriendo todos los cálculos asociados al componente de **Identificación Docente**.
- [x] Corrección de bugs, errores y deuda técnica encontrados en las pruebas realizadas.

**Criterios de aceptación**

- [x] Se presenta un documento claro y detallado con todas las pruebas asociadas al componente de **Identificación docente**.
- [x] El componente de **Identificación docente** realiza correctamente todos los cálculos asociados, mostrando la información correcta en cada caso.

**Requerimientos**

- [x] Terminar issue #842 .
- [x] Terminar issue #843 .

**Dependencias**

- planeacion_mid.
- planeacion_cliente.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Adjunto pruebas: 
[Pruebas Planeación MID - Migración de calculos.xlsx](https://github.com/udistrital/planeacion_cliente/files/14290697/Pruebas.Planeacion.MID.-.Migracion.de.calculos.xlsx)

**Comment by diegobauto** [comment]
Observación: Para la petición hacia Parametros Service se realiza con una vigencia de un año anterior

**Comment by a52290451** [comment]
Se validan y aprueban pruebas funcionales realizadas.
