### ISSUE TITLE
Refinamiento HUs Módulo de plan de acción

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/planeacion_cliente#886]
Se requiere realizar el refinamiento de las Historias de Usuario HU 1-3 asociadas a reporte de consulta de aprobaciones de seguimiento y HU 1-4 asociada a la aprobación masiva de seguimientos.

[Hoja módulo de plan de acción HU 1-3 y HU 1-4](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ERnXVlOzYglGiQxvKqRZ7SkBXK6kdFyl6mB6wnqyf3Kpag?e=LsXNWm)

**Sub Tareas**

- [x] Refinar los escenarios correspondientes a la HU 1-3.
- [x] Refinar los escenarios correspondientes a la HU 1-4.

**Criterios de aceptación**

- [x] HU 1-3 refinada y finalizada siendo claro el contexto, evento y resultados esperados.
- [x] HU 1-4 refinada y finalizada siendo claro el contexto, evento y resultados esperados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by BikerMetalHead** [comment]
Se revisa y se realizan ajustes a los criterios de aceptación, redacción y producto esperado de las historias de usuario del submódulo de plan de acción HU 1-1 a HU 1-4:

[Hoja módulo de plan de acción HU 1-3 y HU 1-4](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ERnXVlOzYglGiQxvKqRZ7SkBXK6kdFyl6mB6wnqyf3Kpag?e=LsXNWm)

**Comment by norbeydanilo** [comment]
Pendiente de revisar HU 1-3 para paso a desarrollo.

**Comment by BikerMetalHead** [comment]
Se realiza el refinamiento de la historia de usuario HU1 -3

[HU1-3_plan_Accion](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ET2pmTPD6JFFqLhvmq2KZLwB0T9a-D34_45di-wMvIiwXg?e=tu62VT)

**Comment by BikerMetalHead** [comment]
Se refina las historias y se añade una historia extra, para diferenciar la visión de la tabla resumen desde el rol unidad y el rol planeación. 
[HU1-3_plan_Accion](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ET2pmTPD6JFFqLhvmq2KZLwB0T9a-D34_45di-wMvIiwXg?e=tu62VT)
