### ISSUE TITLE
4 - 1 Crear controlador en planeacion_mid para actualización de la estructura de una plantilla en utilización en fase de formulación. - PARTE 2

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#888]
Se requiere implementar un controlador en planeacion_mid que realice la actualización de la plantilla de planes de acción en formulación, modificada en el modulo de construcción. La modificación solo aplicará sobre planes que se encuentren en fase de formulación.

**Especificaciones técnicas**

1. En el módulo de construcción se realiza la modificación de una plantilla de plan de acción que actualmente esta siendo utilizada por las unidades en el módulo de formulación en planes de acción. Una vez se actualice su estructura, esta también debe actualizarse sobre los planes que estén en formulación.
2. Los cambios no deben aplicarse sobre planes que hayan superado la etapa de formulación.
3. Si se mantiene un campo de ingreso de información pero se cambia el tipo de dato aceptado, se debe eliminar la información cargada por el usuario y dejar el campo en blanco.
4. Se debe tomar como base lo implementado en #876 .

**Sub Tareas**

- [x] Lógica para ajuste de plantilla en planes de acción en formulación consultados.

**Criterios de aceptación**

- [x] Una vez se modifique la plantilla de un plan de acción en el modulo de construcción, los planes de acción que se encuentran en formulación son ajustados al formato de la plantilla modificada.
- [x] Cuando la unidad ingresa al modulo de formulación en planes de acción, puede ver su plan de acción ajustado a la nueva plantilla del mismo.

**Requerimientos**

- Completar issue #876 .

**Dependencias**

- planeacion_cliente.
- planeacion_mid.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Para la realización del problema, se tomo en cuenta una solución, la cúal se hace una refencia desde un plan la plantilla.

Se actualizó planes_crud, agregando lo siguiente (indicando el nuevo valor que contrendra el id de la referencia):
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/45fd19ee-22a8-412f-80cc-3736eccacfce)
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/9f1bc9a7-0e0d-4818-b888-afabf1b5e66e)

Se actualizó planes_mid, agregando lo siguiente (asignando el valor de la referencia que hace parte de la plantilla):
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/e9ead1ea-712f-4361-a55b-527a114b0e0a)

Se actualizó planes_mid, mostrando el valor de la referencia al obtener el formato:
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/2fa853e5-0d51-4f4f-9113-4bb7a6d8f000)

Por el momento la opción es viable, sin embargo cabe resaltar que durante el desarrollo podrian presentarse dificultades.

**Comment by diegobauto** [comment]
Se actualiza el estado en la rama: 
[feature/actEstPlantilla](https://github.com/udistrital/planeacion_mid/tree/feature/actEstPlantilla)

**Comment by diegobauto** [comment]
Se actualiza el estado en la rama:
[feature/actEstPlantilla](https://github.com/udistrital/planeacion_mid/tree/feature/actEstPlantilla)

Se realizaron las pruebas funcionales: [Link](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ES3fZ39Ru_pOt2Q_3La7Q0kBdcKB1Sa5vu974g9SV3op4w?e=NAoMgW)

Obsercación: Dado que la búsqueda para los planes que estan asociados a una plantilla se realiza por nombre, se puede presentar el inconveniente que dos o mas plantillas tengan el mismo nombre.

**Comment by a52290451** [comment]
Se validan pruebas funcionales realizadas.

**Comment by a52290451** [comment]
Por favor enviar a develop

**Comment by a52290451** [comment]
Especificar si se requiere o no alguna modificación, ya sea de swagger o variables de entorno.

**Comment by diegobauto** [comment]
Se requiere actualización del swagger para: planes_crud y planeacion_mid

**Comment by a52290451** [comment]
Queda actualizado el swagger
