### ISSUE TITLE
Analizar y crear el flujo para la visualización de la armonización de los planes de acción previamente almacenados 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#89]
Se debe desarrollar y analizar el flujo para la visualización del la armonización de los cada actividad registradas en un plan de  acción de funcionamiento, la issue debe cumplir con los siguiente requerimientos:

- [x] Analizar si es posible utilizar el mismo componte inicial del árbol para visualizar o editar una armonización o establecer una nueva forma de visualización de la armonización.
- [x] Implementar el flujo  analizado para la actualización de la armonización del plan de acción de funcionamiento.

**Comment by brayaned** [comment]
Se implemento el mismo  componente de registro de armonización para la visualización de esta misma. El componente de armonización quedo funcional al 100% para el registro, actualización y visualización de la armonización de cada actividad. No se presento ningún problema mayor.

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
