### ISSUE TITLE
División del Cliente en Microfrontends PT1

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#892]
Se requiere realizar la planeación para dividir el sistema SISGPLAN en microclientes, de tal forma que cada uno sea independiente, autosuficiente, escalable, resiliente y tolerante a fallos. El objetivo es lograr desacoplar los componentes del cliente y descentralizar el frontend de un solo cliente para que sea mas sencillo realizar mantenimiento en los mismos y facilitar tareas de intervención por parte del equipo de desarrollo.

**Especificaciones técnicas**
1. Cada microcliente debe estar conformado por el conjunto de componentes y vistas que se relacionen funcionalmente.
2. Se debe tener en cuenta el cliente base (orquestador de microclientes) se desarrollo en SGA en el repositorio:  [SGA_cliente_root](https://github.com/udistrital/sga_cliente_root).
3. Un ejemplo de microcliente es: https://github.com/udistrital/sga_cliente_calendario_academico_mf o https://github.com/udistrital/sga_cliente_proyecto_curricular_mf.
4. El microcliente Core_mf es uno que tienes los componentes globales como: Header, footer, sidebar, estilos, funciones globales (Parecido al web component).
5. Cada Microcliente debe ser descentralizado, lo cual implica que debe poder ser desarrollado, implementado y escalado de forma independiente de otros.
6. Issues a tener en cuenta:
https://github.com/udistrital/sga_cliente/issues/1454
https://github.com/udistrital/sga_documentacion/issues/4
https://github.com/udistrital/sga_cliente/issues/1517
https://github.com/udistrital/sga_cliente/issues/1531
https://github.com/udistrital/sga_documentacion/issues/10

**Sub Tareas**

- [x] Creación de diagrama de componentes de la arquitectura propuesta para el sistema de SISGPLAN, ejemplo .

**Criterios de aceptación**

- [x] El diagrama de componentes muestra la división clara del sistema en múltiples microclientes y su relación con los diferentes componentes de la OATI para su funcionamiento como sistema de información.

**Requerimientos**

- [x] Link del sistema en ambiente de pruebas.
- [x] Material de apoyo.
- [x] Credenciales de acceso al sistema.

**Dependencias**

- No presenta.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
Se adjunta el link del diagrama desarrollado en Draw.io que se ha estado trabajando a lo largo de la semana, actualmente el sistema por lo que se ha podido apreciar gira en torno a dos componentes llamados ARBOL y CONSTRUCCIÓN, de manera que se ha pintado de morado los que necesitan de CONSTRUCCIÓN y de verde fosforescente los que necesitan de ARBOL.

Actualmente se está organizando el diagrama de una manera que se puedas apreciar mejor el ordenamiento en base a estos componentes principalmente.

https://udistritaleduco-my.sharepoint.com/:u:/g/personal/daarojasg_udistrital_edu_co/EYokYcdfRD9FomBr8J2MlUkBiTfYdiKwOSaTsdbAiKqbbA?e=MfPaNj

![SISGPLAN Microfrontends drawio](https://github.com/udistrital/planeacion_cliente/assets/73924638/b2cd8e90-d89c-4adc-b8d7-833589600752)

**Comment by milo19980525** [comment]
Se debe refinar el diagrama y continuar con la issue #910
