### ISSUE TITLE
HU 1-4 Aprobación simultánea de planes/proyectos PT1 (Formulación)

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#893]
Se requiere implementar la parte uno de la [HU 1-4](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ERnXVlOzYglGiQxvKqRZ7SkBXK6kdFyl6mB6wnqyf3Kpag?e=0rksLc) - del hito 2 (Plan de acción), relacionada con la preaprobación de planes por parte del jefe de la unidad de manera simultánea (Formulación).

Descripción: **Como** rol jefe de unidad **quiero** Poder aprobar varios seguimientos simultáneamente, **para** optimizar el tiempo de seguimiento en épocas de alto volumen de asignación.

**Especificaciones técnicas**

- Actualmente el desarrollo del aplicativo se encuentra estabilizado en ambiente develop (Cliente, mid y crud).
- [Diagrama de estados](https://drive.google.com/file/d/1_Tg0AS8WAGgvqAOjw3H6p28wah1Ovc_V/view?usp=sharing)
- Issues relacionadas con esta funcionalidad: #830 y #879 .

**Sub Tareas**

- [x] En las tablas con todas aprobaciones pendientes de funcionamiento del menú "Pendientes"debe existir una acción en cada registro (seleccionable), que permita esoger todos los planes de acción en fase de Formulación (XOR).
Ejemplo:

[imagen](https://private-user-images.githubusercontent.com/82072560/303752914-6c702768-f01d-4cd9-a0a6-171a875cafd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMzEwNTMsIm5iZiI6MTcwODAzMDc1MywicGF0aCI6Ii84MjA3MjU2MC8zMDM3NTI5MTQtNmM3MDI3NjgtZjAxZC00Y2Q5LWEwYTYtMTcxYTg3NWNhZmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDIwNTkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1YWFlZjE1OTM5YjBlZTc4YzIzOTA3YTc2MWUxMTVmZDkwYWRjOTdhODg4M2Q0MGQ5NWEwMzE2NGMyOWRmMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DT6CsgqxARnaTVOqIMIPD5zlL5-QOnQ-lQ95ytwN2-I)
- [x] En dado caso de seleccionar más de un plan/proyecto en formulación (XOR) al final de la tabla debe mostrarse un botón "Aprobar planes/proyectos" que genere la acción de aprobar  pasar al siguiente estado a los planes/proyectos seleccionados que en formulación sería (pasar de Revisado a Revisión verificada). Previo a generar la acción lanzar un popup cicada). Previo a generar la acción lanzar un popup con el on el mensaje "Por favor confirme el cambio de estado para los planes/proyectos seleccionados".
- [x] Debe existir un boton de limpiar que genere la acción de deseleccionar todos los planes/proyectos escogidos previamente.
- [x] Debe existir un botón llamado "Seleccionar Todos", el cual debe generar la acción de mostrar todos los registros como seleccionados en la nueva columna (selección).
- [x] Se debe desplegar un popup cuando el usuario de clic en el botón "seleccionar todos" que informe al usuario que está escogiendo todos los planes/proyectos pendientes por revisar (no solo los de la primera página de la tabla).

**Criterios de aceptación**

- [x] Cuando el jefe de unidad Accede al sistema, en el menú de "Pendientes". Visualiza información relevante sobre cada  plan en fase de formulación, permitiendo seleccionar todos los planes o proyectos allí mostrados.
- [x] Cuando el jefe de unidad Accede al sistema, en el menú de "Pendientes". Visualiza información relevante sobre cada  plan en fase de formulación, permitiendo seleccionar dos o más planes o proyectos allí mostrados.
- [x] A los planes escogidos se puede generar su aprobación y cambiar su respectivo estado (avanzando en las fases del flujo) siempre y cuando seleccione más de un plan, en caso contrario no se habilitará la opción "Aprobar Planes/Proyectos"
- [x] En dado caso de que la aprobación de alguno de los planes genere un error se debe mostrar un popup que informe que uno de los planes está generando error en su aprobación, intente más tarde o comuniquese con la OATI.
- [x] El jefe de cada unidad puede deseleccionar todos los planes/proyectos escogidos.

**Requerimientos**

- [x] Creación de roles y asignación de permisos tanto en WSO2 como en el api de configuración.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by C0C045** [comment]
# PR's
En rama mid: https://github.com/udistrital/planeacion_mid/pull/489
En rama cliente: #913
