### ISSUE TITLE
Analizar y crear el flujo para la creación de la data de identificación de recurso y contratistas 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#90]
Se debe realizar el análisis para el flujo de almacenamiento de la data de identificación de recurso y contratistas  en el sistema, para esto se debe realizar los siguientes requerimientos:

- [x] Analizar el modelo de plan_crud para el almacenamiento de dicha información, una vez analizado realizar ajustes de controladores modelos y migraciones del modelo ya establecido, documentar el modelo en el [drive V6](https://drive.google.com/drive/u/0/folders/1hOSsq3PifFbPsYFLiQjvjRqQbVnPRuGw)
- [x] Crear la funcionalidad a nivel mid para el registro de cada uno de los recurso y contratistas de forma dinámica para cada tipo, tener presente que se debe identificar con un index por separado.
- [x] Crear función de consulta para las tablas de identificación, esta función debe tener un filter que permita traer por separado cada identificación

**Comment by ndmc98** [comment]
Se finaliza la issue generando el Pull Request con las funciones de Put y Get en el MID. 

Ejemplos para prueba: 

- Put: /v1/formulacion/guardar_identificacion/:id/:idTipo
- Get: /v1/formulacion/get_all_identificacion/:id/:idTipo 

id: 616f6911a985e921bca12e96
idTipo: 617b6630f6fc97b776279afa

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
