### ISSUE TITLE
Pruebas funcionales SISGPLAN en ambiente de pruebas - Sprints 1,2 y 3.

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#903]
Se requieren llevar a cabo pruebas funcionales en ambiente de pruebas, asociadas a los desarrollos realizados en SISGPLAN en los Sprints 1, 2 y 3.

**Especificaciones técnicas**

1. Las pruebas funcionales deben cubrir todos los desarrollos cargados en develop en los sprints 1, 2 y 3.
2. Se deben tomar como guía las pruebas realizadas por los desarrolladores en local en cada implementación.
3. El documento de pruebas debe especificar el estado en el que se encuentra el desarrollo, si se valida o no su funcionamiento y las observaciones correspondientes.
4. Los desarrollos a probar se encuentran en:
- [Sprint 1](https://github.com/udistrital/planeacion_cliente/milestone/79)
- [Sprint 2](https://github.com/udistrital/planeacion_cliente/milestone/80)
- [Sprint 3](https://github.com/udistrital/planeacion_cliente/milestone/81)
5. Se deben probar solamente los desarrollos, las tareas de análisis o documentación no se tienen en cuenta.
6. Se trata de hacer un compendio de todas las pruebas realizadas hasta la fecha en un documento y validar su funcionamiento.

**Sub Tareas**

- [ ] Desarrollo de pruebas funcionales en ambiente de pruebas - SISGPLAN.

**Criterios de aceptación**

- [ ] Se presenta un documento con pruebas de los desarrollos implementados en el Sprint 1, 2 y 3, asociados a SISGPLAN.

**Requerimientos**

- No presenta.

**Dependencias**

- planeacion_cliente.
- planeacion_mid.
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
@a52290451 https://github.com/udistrital/sga_documentacion/issues/42

**Comment by a52290451** [comment]
@EdissonFrancisco por favor actualizar estado de la actividad.

**Comment by EdissonFrancisco** [comment]
se realiza validaciones en entorno de pruebas y se realiza llenado del formato para revision.

archivo de pruebas: https://udistritaleduco-my.sharepoint.com/:x:/g/personal/efaceror_udistrital_edu_co/EexnIEcdCOBKh2nuZm4he2MBtlyfTtbUPJySM18LCDVQCw?e=3IIgAY

**Comment by a52290451** [comment]
Observaciones:

1. Realizar correcciones a pruebas, de acuerdo a las observaciones especificadas en cada caso en el documento base.
2. Agregar pruebas de:

- [ ] #813 .
- [ ] #879 .
- [ ] #849 .
- [ ] #866 .

**Comment by EdissonFrancisco** [comment]
se realizan ajustes en el archivo de pruebas y se termina la revision, en espera de validación.

**Comment by a52290451** [comment]
Queda pendiente realizar entrega formal de la actividad.
