### ISSUE TITLE
Ajustar el tamaño de los text área que detallan cada una de las actividades de un plan en seguimiento dependiendo de la cantidad de información que estos contengan.

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#904]
Se requiere realizar la optimización de todos los componentes gráficos asociados a **Text Area** en el modulo de seguimiento en planes de acción, de tal forma que se ajusten de forma automática a la cantidad de texto que ingrese el usuario.

**Especificaciones técnicas**

1. Se requiere que cada **Text Area** que este incluido en seguimiento en planes de acción, sea autoajustable de acuerdo al tamaño del texto ingresado por el usuario. Actualmente, el tamaño de los **Text Area** se ajusta de forma manual:

![image](https://github.com/udistrital/planeacion_cliente/assets/36229498/d843eaea-d9d7-414c-ac60-19c59e25485d)
![image](https://github.com/udistrital/planeacion_cliente/assets/36229498/3b6c5620-6e1f-4214-bf21-e8b60722c125)

2. Se deben mantener las proporciones de los demás componentes en seguimiento. Es decir, cuando un **Text Area** ajusta su tamaño, esto no debe influir en la correcta visualización de los demás elementos.

**Sub Tareas**

- [x] Ajuste de componentes de tipo **Text Area** en el módulo de seguimiento en planes de acción.

**Criterios de aceptación**

- [x] Cuando un usuario ingresa información en campos descriptivos (text area) en el modulo de seguimiento en planes de acción, el campo se ajusta automáticamente a la cantidad de texto que se introduce.
- [x] Cuando un campo descriptivo se auto ajusta, los demás campos circundantes mantienen sus propiedades y proporciones.

**Requerimientos**

- No presenta.

**Dependencias**

- planeacion_cliente.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
@felimarod por favor actualizar estado de la actividad.

**Comment by felimarod** [comment]
Se hizo el seguimiento de la issue y se identificaron los componentes a modificar. Al momento de intentar hacer el ajuste se presentaron fallos inesperados que se encuentran en estudio.

**Comment by felimarod** [comment]
Acabo de agregar la rama feature asociada a esta issue, en ella agregue lo que se ha hecho hasta el momento aunque no se ha logrado obtener un avance significativo

**Comment by felimarod** [comment]
[Prueba funcional](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EYvhSNpbAQFCriLz8tlAa8oBeWAkvGM6FYczrjZMjP_iAQ?e=PJs6RO)

**Comment by felimarod** [comment]
Hay un problema cuando los TextArea solo se pueden visualizar, lo que sucede es que no se actualiza el tamaño y por tanto no se logra visualizar todo el contenido

**Comment by a52290451** [comment]
Se aprueba alcance asociado al campo text area.

**Deuda técnica:**

Los campos text area no se redimensionan al contenido en su visualización. La redimensión solo se aplica cuando se agrega información o se editan los campos.
