### ISSUE TITLE
División del Cliente en Microfrontends PT2

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#910]
Se requiere continuar la planeación para dividir el sistema SISGPLAN en microclientes, de tal forma que cada uno sea independiente, autosuficiente, escalable, resiliente y tolerante a fallos. El objetivo es lograr desacoplar los componentes del cliente y descentralizar el frontend de un solo cliente para que sea mas sencillo realizar mantenimiento en los mismos y facilitar tareas de intervención por parte del equipo de desarrollo.

**Especificaciones técnicas**
1. Cada microcliente debe estar conformado por el conjunto de componentes y vistas que se relacionen funcionalmente.
2. Se debe tener en cuenta el cliente base (orquestador de microclientes) se desarrollo en SGA en el repositorio:  [SGA_cliente_root](https://github.com/udistrital/sga_cliente_root).
3. Un ejemplo de microcliente es: https://github.com/udistrital/sga_cliente_calendario_academico_mf o https://github.com/udistrital/sga_cliente_proyecto_curricular_mf.
4. El microcliente Core_mf es uno que tienes los componentes globales como: Header, footer, sidebar, estilos, funciones globales (Parecido al web component).
5. Cada Microcliente debe ser descentralizado, lo cual implica que debe poder ser desarrollado, implementado y escalado de forma independiente de otros.
6. Issues a tener en cuenta:
https://github.com/udistrital/sga_cliente/issues/1454
https://github.com/udistrital/sga_documentacion/issues/4
https://github.com/udistrital/sga_cliente/issues/1517
https://github.com/udistrital/sga_cliente/issues/1531
https://github.com/udistrital/sga_documentacion/issues/10

**Sub Tareas**

- [x] Análisis del sistema a nivel de código para comprender su funcionamiento y grado de acoplamiento y unión entre componentes y funcionalidades.
- [x] Refinamiento del diagrama de componentes de la arquitectura propuesta para el sistema de SISGPLAN.
- [x] Creación de listado de Microclientes a detalle, señalando os componentes que lo conforman, así como su relación con otros microclientes y componentes de la OATI.

**Criterios de aceptación**

- [x] El diagrama de componentes refinado, muestra la división clara del sistema en múltiples microclientes y su relación con los diferentes componentes de la OATI para su funcionamiento como sistema de información.
- [x] El detalle de los microclientes, muestra el listado de funcionalidades que componen cada microcliente y que relación existe entre cada uno de los microclientes entre si y con otros componentes de la OATI.

**Requerimientos**

- [x] Link del sistema en ambiente de pruebas.
- [x] Material de apoyo.
- [x] Credenciales de acceso al sistema.

**Dependencias**

- No presenta.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
Se adjunta el link del diagrama desarrollador como PROPUESTA, cabe aclarar que la propuesta se encuentra en la pestaña de ORDENAMIENTO:

https://udistritaleduco-my.sharepoint.com/:u:/g/personal/daarojasg_udistrital_edu_co/EYokYcdfRD9FomBr8J2MlUkBiTfYdiKwOSaTsdbAiKqbbA?e=wBfwC0

**Comment by Mechaz123** [comment]
Se adjunta también la imagen del diagrama desarrollado:

![Uploading SISGPLAN Microfrontends-ORDENAMIENTO.drawio.png…]()

**Comment by Mechaz123** [comment]
Después de la revisión por parte del equipo de SISGPLAN, se deben realizar los siguientes cambios:
- Observar de qué manera se puede desacoplar el PUI del MF de seguimiento.
- Crear un MF llamado Utilidades para incluir información básica y evaluación.
- Observar de qué manera se puede desacoplar "Formulación Plan", en un MF nuevo, actualmente todo está unido en el componente llamado PLAN.

Se queda al pendiente de si falta alguna otra indicación a listar, para realizar el respectivo cambio.

**Comment by Mechaz123** [comment]
Se realizan las modificaciones mencionadas al diagrama.

![SISGPLAN Microfrontends-CORRECCIÓN V1](https://github.com/udistrital/planeacion_cliente/assets/73924638/118e3b04-7813-445a-9d3f-7efa6da31a12)
