### ISSUE TITLE
HU 1-4 Aprobación simultánea de planes/proyectos PT2 (Seguimiento)

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#911]
Se requiere implementar la parte dos de la [HU 1-4](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ERnXVlOzYglGiQxvKqRZ7SkBXK6kdFyl6mB6wnqyf3Kpag?e=0rksLc) - del hito 2 (Plan de acción), relacionada con la preaprobación de planes por parte del jefe de la unidad de manera simultánea para la fase de seguimiento.

Descripción: **Como** rol jefe de unidad **quiero** Poder aprobar varios seguimientos simultáneamente, **para** optimizar el tiempo de seguimiento en épocas de alto volumen de asignación.

**Especificaciones técnicas**

- Actualmente el desarrollo del aplicativo se encuentra estabilizado en ambiente develop (Cliente, mid y crud).
- [Diagrama de estados](https://drive.google.com/file/d/1_Tg0AS8WAGgvqAOjw3H6p28wah1Ovc_V/view?usp=sharing)
- Issues relacionadas con esta funcionalidad: #830 y #879 .

**Sub Tareas**

- [x] En las tablas con todas aprobaciones pendientes de seguimiento del menú "Pendientes"debe existir una acción en cada registro (seleccionable), que permita esoger todos los planes de acción en fase de segumiento. 
Ejemplo:

[imagen](https://private-user-images.githubusercontent.com/82072560/303752914-6c702768-f01d-4cd9-a0a6-171a875cafd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMzEwNTMsIm5iZiI6MTcwODAzMDc1MywicGF0aCI6Ii84MjA3MjU2MC8zMDM3NTI5MTQtNmM3MDI3NjgtZjAxZC00Y2Q5LWEwYTYtMTcxYTg3NWNhZmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDIwNTkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1YWFlZjE1OTM5YjBlZTc4YzIzOTA3YTc2MWUxMTVmZDkwYWRjOTdhODg4M2Q0MGQ5NWEwMzE2NGMyOWRmMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DT6CsgqxARnaTVOqIMIPD5zlL5-QOnQ-lQ95ytwN2-I)
- [x] En dado caso de seleccionar más de un plan/proyecto en seguimiento al final de la tabla debe mostrarse un botón "Aprobar planes/proyectos" que genere la acción de aprobar  pasar al siguiente estado a los planes/proyectos seleccionados que en seguimiento de (Enviado a Revisión **a** Revisión Verificada). Previo a generar la acción lanzar un popup con el mensaje "Por favor confirme el cambio de estado para los planes/proyectos seleccionados".
- [x] Debe existir un boton de limpiar que genere la acción de deseleccionar todos los planes/proyectos escogidos previamente.
- [x] Debe existir un botón llamado "Seleccionar Todos", el cual debe generar la acción de mostrar todos los registros como seleccionados en la nueva columna (selección).
- [x] Se debe desplegar un popup cuando el usuario de clic en el botón "seleccionar todos" que informe al usuario que está escogiendo todos los planes/proyectos pendientes por revisar (no solo los de la primera página de la tabla).

**Criterios de aceptación**

- [x] Cuando el jefe de unidad Accede al sistema, en el menú de "Pendientes". Visualiza información relevante sobre cada  plan en fase de seguimiento, permitiendo seleccionar todos los planes o proyectos allí mostrados.
- [x] Cuando el jefe de unidad Accede al sistema, en el menú de "Pendientes". Visualiza información relevante sobre cada  plan en fase de seguimiento, permitiendo seleccionar dos o más planes o proyectos allí mostrados.
- [x] A los planes escogidos se puede generar su aprobación y cambiar su respectivo estado (avanzando en las fases del flujo) siempre y cuando seleccione más de un plan, en caso contrario no se habilitará la opción "Aprobar Planes/Proyectos"
- [x] En dado caso de que la aprobación de alguno de los planes genere un error se debe mostrar un popup que informe que uno de los planes está generando error en su aprobación, intente más tarde o comuniquese con la OATI.
- [x] El jefe de cada unidad puede deseleccionar todos los planes/proyectos escogidos.

**Requerimientos**

- [x] Creación de roles y asignación de permisos tanto en WSO2 como en el api de configuración.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by C0C045** [comment]
# Versión final de Planes Pendientes en Seguimiento.
1. Se añadió una nueva columna 'Seleccionar', para implementar la acción de seleccionar uno o varios planes.
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/67b06384-5bdf-4b4c-a109-c0b7d7db1201)

2. Se implementó el botón de seleccionar todos los planes con su respectivo 'popup' que advierte la selección de todos los planes existentes en tabla.
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/32ee745a-336f-4fc3-b109-e860471b23db)
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/71fb75de-2e76-4947-8d4a-38613f890fa4)
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/96525495-430e-41e4-8967-df06f11e30b8)

3. Por otro lado, también se implementó el botón para deseleccionar todos los planes de seleccionados.
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/47150918-2475-4efd-b62e-6ea5b931a212)
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/aabec65d-f93d-471e-80d0-c96d9af15f8a)

4. Por último, se tiene el botón para verificar todos los planes/proyectos seleccionados, el cuál solo se activa cuando hay más de un plan seleccionado.
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/a3c7b02b-45aa-419b-b14b-d56ac43b93b4)
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/7523c83c-a1a9-4854-866e-952629d76167)
4.1. Una vez se de 'click' en continuar, pueden haber dos caminos. Qué todos los planes sean verificables, ya que sus actividades están todas aprobadas o qué algunos planes tengan actividades pendientes y por ende no es posible verificarlos por el momento.
**Caso 1:**
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/352347d1-d1d9-4260-805e-7f9a3896948f)
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/c6a49270-966b-4745-8b87-cca7884aa4cc)
**Caso 2:**
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/5840e55c-2d26-4cf4-92a3-18f751493b6c)

**Comment by C0C045** [comment]
# PR
En rama cliente: #922

**Comment by milo19980525** [comment]
@C0C045 Por favor enviar PR con ajuste en el mensaje de fallo en la aprobación cuando falta por aprobar alguna actividad para que salga el trimestre del plan.
