### ISSUE TITLE
HU2 - 1 Consulta de usuario por roles y correo PT2

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#912]
Se requiere implementar la segunda parte de [HU2 - 1](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/resanchezc_udistrital_edu_co/EYc_4k5TayBEgwWaq2wQt9UBOxFJ-y2a-Z_lj5bsjlDkUQ?wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1706125306937&web=1), relacionada con la consulta de usuarios por rol y correo electrónico.

Descripción: **Como** rol planeación **quiero** realizar la Consulta por correo y roles **para** observar un usuario en particular o una lista de usuarios que  obedezcan a diferentes características.

**Especificaciones técnicas**

- Actualmente el desarrollo del aplicativo se encuentra estabilizado en ambiente develop (Cliente, mid y crud).

**Sub Tareas**

- [x] Completar el componente visual en angular asociado al mockup realizado y aprobado.
- [x] Asociar la acción de búsqueda al servicio de consulta de wso2 (autenticacion_mid).
- [x] Asociar la acción de Limpiar para que oculte la tabla y limpie los campos de filtrado.

**Criterios de aceptación**

- [x] Dado que Un administrador desea visualizar una lista de todos los usuarios asignados a roles específicos en el sistema de planeación Cuando Accede al módulo de consulta de usuarios, selecciona un rol específico y obtiene una lista de usuarios asociados a ese rol.
- [x] Dado que Se necesita identificar usuarios específicos Cuando Accede al módulo de consulta, busca por medio de un campo de consulta  por correo electrónico obtiene una lista de usuarios asociados a la palabra de búsqueda.
- [x] Dado que Un administrador realiza la búsqueda de usuarios por medio del campo de búsqueda. y el usuario no es encontrado por el sistema , se muestra un un popup "No se encontraron datos registrados".
- [x] Visualmente las márgenes de la tabla se ajustan al tamaño de la información y al tamaño de la página (responsive).

**Requerimientos**

- [x] Servicio de consulta usuarios WSO2.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by milo19980525** [comment]
Queda pendiente desarrollo de servicio en autenticación que traiga usuarios a partir de un rol.

**Comment by ccmendezt** [comment]
## Evidencias - Avance **HU2 - 1 Consulta de usuario por roles y correo PT2**
### 19/03/2024 - 16:05 pm

- Visualmente las márgenes de la tabla se ajustan al tamaño de la información y al tamaño de la página (responsive):
![responsive](https://github.com/udistrital/planeacion_cliente/assets/82072560/d65ba9d9-0e34-4c90-b395-f07c49ac4c77)

**Comment by milo19980525** [comment]
Buen trabajo Cristian, queda pendiente el servicio de consulta.
