### ISSUE TITLE
2 - Interfaz general que muestra el avance de todas las unidades por plan de acción y vigencia. (PARTE 1)

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#916]
Se requiere implementar una vista en **planeacion_cliente**, módulo de planes de acción, componente de **evaluación**, en el que se muestre el avance general de cada unidad asociada a un plan de acción y vigencia en particular, a modo de grafico y tabla resumen.

**Especificaciones técnicas**

1. Se deben reorganizar los filtros del componente de evaluación en planes de acción para que se registren de la siguiente forma:
- Plan de acción.
- Vigencia.
- Unidad.
- Trimestre.
2. En este caso, para el filtro unidad, se tendrá que agregar la opción "Todas las Unidades". Esta será la puerta de entrada para la interfaz que se trabajará en esta actividad.
3. Si se selecciona la opción "Todas las Unidades", se debe bloquear el filtro "Trimestre" y habilitar el botón "Consultar Evaluación".
4. Si se oprime el botón "Consultar Evaluación", cumpliéndose las condiciones anteriormente mencionadas, se deberán generar los siguientes elementos en la interfaz.
- Grafico (Revisar opciones) en el que se muestren todas las unidades que tengan el plan seleccionado en fase de seguimiento, con su respectivo avance promedio (La suma del avance de cada trimestre dividido en la cantidad de trimestres registrados).
- Tabla resumen del plan de acción en el que se apilen todas las unidades por filas. Se debe manejar la misma estructura he información que se registra en la tabla resumen por unidad.
5. Aspectos a tener en cuenta:
- La tabla resumen debe poder desplegar y guardar la información del plan, por cada unidad registrada. Es decir que en principio, cada fila muestra la unidad y el avance promedio de esa unidad con respecto al plan. Oprimiendo encima de una unidad en particular, se despliega toda la información del plan asociada a esa unidad.
- La grafica debe mostrar claramente la información asociada a cada unidad.

**Sub Tareas**

- [x] Adecuación y restricción de filtros y ajuste de opciones por filtro.
- [x] Creación de mockup para grafico del nivel de avance de todas las unidades.
- [x] Creación de mockup para tabla resumen del plan de acción en el que se incluyen todas las unidades.

**Criterios de aceptación**

- [x] En el componente de evaluación del modulo de planes de acción, puedo seleccionar la información de todas las unidades asociadas a un plan de acción y vigencia en particular.

**Requerimientos**

- No presenta.

**Dependencias**

- planeacion_cliente.
- planeacion_mid.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by felimarod** [comment]
[Avance en el mockup](https://www.figma.com/proto/F5ZE2llLnHeA7mJK98RfJw/UD-team-library?type=design&node-id=2411-296&t=IDh9qpYg6J4qQiZw-1&scaling=scale-down&page-id=2411%3A290&mode=design)

**Comment by a52290451** [comment]
https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ERnXVlOzYglGiQxvKqRZ7SkBXK6kdFyl6mB6wnqyf3Kpag?e=EbFujs&nav=MTVfezkxRDZEMjYyLTdFOTctNEYwNC04MzA3LTM3NjkwNEE4RTVGRn0

**Comment by a52290451** [comment]
Se aprueban Mockups presentados con las siguientes observaciones:

1. El grafico de barras debe contener los detalles que aparecen a continuación:

![image](https://github.com/udistrital/planeacion_cliente/assets/36229498/ccd755a1-a036-4873-bbed-7312d69bb2b1)

- Porcentaje de avance encima de cada barra.
- Sistema de colores para cada unidad, dependiendo del porcentaje de avance
![image](https://github.com/udistrital/planeacion_cliente/assets/36229498/ae242bde-1862-46b0-82fb-ddde27a5ea2d)
- Indice de colores.

**Comment by a52290451** [comment]
@felimarod por favor actualizar estado de la actividad.

**Comment by felimarod** [comment]
Se realizó la creación de un endpoint que traerá los nombres de los planes que se pueden consultar y acceder desde la vista de seguimiento. Y se realizó el ajuste de los filtros.

**Comment by felimarod** [comment]
[Pruebas funcionales en el MID](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EbYLbSTwStdGjp6dRlNBCWsBXT2Xi89Dd--oJMZbil8XhA?e=juX9Hv)

[Pruebas funcionales en el cliente](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EXLPJuPpSZ5Fp0FRxAnHROUBg7zJLS3HKttjoDtDJstF4A?e=GiX7uc)

**Comment by felimarod** [comment]
Se requiere actualizar el swagger ya que se creo una nueva ruta en el MID

**Comment by a52290451** [comment]
Se realiza actualización del swagger, el desarrollo se encuentra en develop
