### ISSUE TITLE
Creación API planeacion_reportes_mid (PARTE 1)

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#917]
Se requiere crear el API **PLANEACION_REPORTES_MID** con base en el API **PLANEACION_MID**, de forma tal que los controladores asociados queden desacoplados del API principal.

**Especificaciones técnicas**

1. El repositorio para **PLANEACION_REPORTES_MID** es: 
https://github.com/udistrital/planeacion_reportes_mid
3. Se requiere migrar el código asociado a Reportes, del API **PLANEACION_MID** al API **PLANEACION_REPORTES_MID**.
4. El API debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevas APIs GO definidos por la OATI.
5. Los métodos de utilidades que son globales a todas las APIs deben ser migrados a la librería **utils_oas**.
6. Se debe optimizar el código migrado, eliminando malas practicas de desarrollo.
7. Tomar como referencia el diagrama de componentes elaborado en #803 .
8. Tomar como referencia la implementación de otros microservicios: #852 , #880 , #844 , #822 .

**Sub Tareas**

- [x] Desarrollo de API **PLANEACION_REPORTES_MID**
- [x] Migración de código entre APIs.
- [x] Optimización de código.

**Criterios de aceptación**

- [x] El API se encuentra desarrollada.
- [x] El código fuente del API está optimizado.

**Requerimientos**

- [x] Completar Issue #803 .
- [x] Dependencia con la creación del API **PLANEACION_EVALUACION_MID**

**Dependencias**

- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
@diegobauto por favor actualizar estado de la actividad.

**Comment by diegobauto** [comment]
Se realizó la creación de la API: 

Se añaden evidencias: 
- Estructura: 
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/b55a58e0-003b-4244-ac10-12e49e3a8cd8)

- Configuración inicial (abierta a cambios): 
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/34fe88fa-fccd-4387-a598-2bfd994bb46f)

- Controlador:
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/271e314c-a796-402b-a687-d2a89bd21284)

- Helper: 
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/ce82c1f7-69de-4831-aa07-c7c5db052064)

**Comment by diegobauto** [comment]
Observaciones: 
- Se realizó la impieza del controlador, dejando el código en el archivo helper
- Manejo de constantes en el helper
- Manejo de ErrorController en el controlador 
- Manejo de los defer en el helper
- Falta validar los body de las diferentes peticiones
- Falta validar los códigos de estado
- Falta optimizar código
- Falta realizar pruebas

**Comment by diegobauto** [comment]
Actualmente se tiene la dependencia de evaluación en el helper, se debe realizar el cambio para que apunte directamente hacia planeacion_evaluacion_mid ya que se encuentra hacie planeacion_mid.

En la funcion ValidarPlan(), se tiene quemado un id (validar):
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/0511d43e-558a-4bc8-8808-651429537f3b)
