### ISSUE TITLE
Ajuste de almacenamiento de periodos y creación de servicio consulta planes/proyectos y unidades con su respectivo periodo

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#923]
Se requiere ajustar el almacenamiento de periodos correspondientes a cada uno de los planes/proyectos de manera diferenciada por unidad.

**Especificaciones técnicas**

- Actualmente el desarrollo del aplicativo se encuentra estabilizado en ambiente develop (Cliente, mid y crud).
- Actualmente e almacena un periodo por seguimiento y funcionamiento.

**Sub Tareas**

- [x] Ajustar el almacenamiento de periodos particulares por proyecto/plan dependiente a la unidad/es seleccionada/s. Se debe almacenar la información en "periodo_seguimiento".
- [x] Crear servicio en el mid que permita consultar ya sea por unidad o por plan/proyecto las fechas de los planes en común.
- [x] Para el almacenamiento se debe seguir la lógica de buscar si para ese plan de acción y las unidades seleccionadas ya existe un registro para esa vigencia en periodo_seguimiento, en dado caso que exista se debe borrar esa unidad del campo unidades_interes y adicionar un nuevo registro.
- [x] Ajuste de consumo de fechas en formulación/seguimiento almacenadas en periodo_seguimiento.

**Criterios de aceptación**

- [x] Se evidencia almacenamiento con base en las indicaciones señaladas.
- [x] El servicio del mid proporciona la información de planes segun los filtros planes/proyetos y unidad.
- [x] En los procesos de formulación y seguimiento se ajusta la consulta a la tabla periodo_seguimiento para verificar las fechas en las que se puede realizar dichos procesos.

**Requerimientos**

- [x] Ninguno.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico

**Comment by ccmendezt** [comment]
## Evidencias - Ajuste de almacenamiento
### 08/03/2024 - 18:30 pm

- Se implementó un _servicio_ en la **API CRUD** que permitiera buscar registros en _planes_interes_ y _unidades_interes_ mediante expresiones regulares según sea el caso ya que el _query_ del método **get** no lo permitía:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/2d7b1bdf-3d02-4b25-be72-80a5ccc432ca)

- Se creó un servicio en la **API MID** que permitió almacenar periodos particulares por proyecto/plan asociando la unidad/es seleccionada/s en la tabla _periodo-seguimiento_. El servicio se nombró _DefinirFechasFuncionamiento_ y es una petición tipo **POST**:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/e62e46e1-8219-47d7-880b-72d0a4c19ea6)
- El servicio recibe un **JSON** que genera el **Cliente** con la siguiente estructura:
```json
{
  "fecha_inicio":"2024-03-01T00:00:00.000Z",
  "fecha_fin":"2024-04-30T00:00:00.000Z",
  "periodo_id":"30",
  "tipo_seguimiento_id":"6260e975ebe1e6498f7404ee",
  "unidades_interes":"[{\"Id\":14,\"Nombre\":\"FACULTAD DE INGENIERIA\"},{\"Id\":8,\"Nombre\":\"VICERRECTORIA ACADEMICA\"}]",
  "planes_interes":"[{\"_id\":\"61305c7edf020f065956ba26\",\"nombre\":\"Ejemplo para SubDetalle v1\"},{\"_id\":\"61398379df020f786256e5a7\",\"nombre\":\"Plan de Acción Proyecto de Inversión\"}]",
  "activo":true
}
````
- Toda la lógica utilizada para cumplir con el almacenamiento correcto se manejó dentro del helper de formulación llamado _formulacion.helper.go_, las siguientes imágenes son un fragmento del código empleado para realizar las validaciones requeridas:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/5288eb5e-5a0e-4f98-86b7-10c1fc82d4b2)
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/e20327c0-ec36-4e0c-a46b-2504322c2790)

- Así se vería el almacenamiento en **MongoDB** de los registros indicados según el cuerpo de la petición (JSON):
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/a8a47756-b555-4e45-827a-2416ff0b952e)
En la imagen se puede apreciar como se _genera un registro_ para cada _plan de interés_ contenido en la petición asociándole las _unidades_interes_ establecidas.

- Los planes habilitados para su formulación que se seleccionaron desde el rol **planeación** se cargan en desde la vista de unidad académica utilizando el endpoint de la **API CRUD**:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/14bc6ea1-63c0-439e-aa2c-b1a1f037efca)
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/92179492-eee5-4df3-b0e5-5ae5e00d34b3)

- La _verificación de fechas_ se hace para los nuevos planes almacenados en los registros de periodo-seguimiento utilizando el servicio de la **API CRUD** mencionado anteriormente, (para los planes antiguos se omite):
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/c21033aa-6494-41f1-acd9-9d96b7bfc7ed)

## Notas importantes:
  **i.** El proceso de almacenamiento sirve tanto para **Formulación** como para **Seguimiento** de los Planes de Acción de Funcionamiento ya que el formato de la petición es la misma y la estructuración del servicio en la API MID lo permite, evitando tener que escribir otra función para otro proceso.
  **ii.** Este servicio ya se implementó correctamente en el **Cliente**.
  **iii.** Se está trabajando en la vista de _seguimiento de planes de acción activos_ desde el **Cliente** para rol **Planeación** y **Unidad**: [Issue asociado](https://github.com/udistrital/planeacion_cliente/issues/932).

**Comment by ccmendezt** [comment]
## Pull Request asociados - Ajuste de almacenamiento
### 09/03/2024 - 12:40 pm

- **planes_crud:** https://github.com/udistrital/planes_crud/pull/95
- **planeacion_mid**: No se realizó PR ya que el build _falló_, a continuación las imágenes del fallo:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/ae1dca62-1e94-4de1-a361-79554e889bd8)
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/86077a36-6582-426b-a774-8f3262e27d5a)
- **planeacion_cliente**: Aún no se realiza PR ya que se está implementando la issue #932, pero en los commits de la rama **_feature/ccmendezt_** se puede evidenciar el progreso.

## Notas importantes:
  **i.** Se debe revisar con el **_líder técnico_** el _build_ de la **API MID** antes de realizar el Pull Request.

**Comment by milo19980525** [comment]
Buen trabajo Cristian.

**Comment by ccmendezt** [comment]
## ACTUALIZACIÓN - Pull Request asociados
### 12/03/2024 - 10:30 pm

- **planes_crud:** https://github.com/udistrital/planes_crud/pull/95
- **planeacion_mid**: Se realizó el PR logrando solucionar el build fallido https://github.com/udistrital/planeacion_mid/pull/500
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/827d5d71-96a9-42dd-81cb-136580497c43)

- **planeacion_cliente**: Aún no se realiza PR ya que se está implementando la issue #932, pero en los commits de la rama **_feature/ccmendezt_** se puede evidenciar el progreso.

**Comment by milo19980525** [comment]
Perfecto, olvidar lo mencionado en el anterior issue.

**Comment by ccmendezt** [comment]
## Evidencias - Ajuste de almacenamiento
### 13/03/2024 - 11:00 am

- Se implementó la llamada al servicio post desde el cliente para el proceso de **formulación** y **seguimiento**:
    - **Para formulación:** 
    ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/bc39d976-517f-48d4-85ec-92c4d4404489)
    - Para seguimiento:**
    ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/e00f0410-88b1-4321-b881-6baf156ff7e9)
