### ISSUE TITLE
2-0 Creación Microfrontend Root-mf

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#925]
Se requiere crear el microfrontend **planeacion-root-mf** con base en el cliente **PLANEACION_CLIENTE**, de forma tal que los componentes asociados queden desacoplados del Cliente principal.

**Especificaciones técnicas**

1. El repositorio para **planeacion-root-mf** es: 
https://github.com/udistrital/planeacion_root_mf
3. Se requiere crear el cliente a partir de single-spa.
4. El API debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevos clientes definidos por la OATI.
5. Se debe consumir el microfrontend core-mf.
6. Se debe optimizar el código migrado, eliminando malas practicas de desarrollo.
7. Tomar como referencia el diagrama de componentes elaborado en #910 .

**Sub Tareas**

- [x] Desarrollo del cliente **planeacion-root-mf**
- [x] Consumo de core-mf.
- [x] Optimización de código.

**Criterios de aceptación**

- [x] El cliente se encuentra desarrollado.
- [x] El código está optimizado.
- [x] Se consume a core-mfy se evidencia su integración.

**Requerimientos**

- [x] Completar Issue #910  .

**Dependencias**

- planeacion_cliente
- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by milo19980525** [comment]
Por favor comentar estado del issue.

**Comment by Mechaz123** [comment]
Actualmente se ha estado configurando el root, pero aún no se logra conectar con el core, ya que presenta algunos problemas tanto el root como el Core, para enlazarlos.

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/510babc4-64a1-4d48-94cb-b292df430865)

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/547f8902-42bc-4905-ae3f-c1a78e73e678)

**Comment by milo19980525** [comment]
En dado caso de ser necesario informar para agendar reunión, esta semana se empiezan nuevos mf.

**Comment by Mechaz123** [comment]
Se logra conectar el root con el core, de manera que se visualiza la estructura base del cliente.

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/11efc8e9-a175-4f67-858a-7ed1a83fe98c)
