### ISSUE TITLE
2 - Interfaz general que muestra el avance de todas las unidades por plan de acción y vigencia. (PARTE 2)

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#926]
Se requiere completar la implementación de la vista en la que se muestra el avance general de cada unidad asociada a un plan de acción y vigencia en particular, en **planeacion_cliente**, módulo de planes de acción, componente de **evaluación**.

**Especificaciones técnicas**

1. Si se oprime el botón "Consultar Evaluación", cumpliéndose las condiciones anteriormente mencionadas, se deberán generar los siguientes elementos en la interfaz.
- Grafico (Revisar opciones) en el que se muestren todas las unidades que tengan el plan seleccionado en fase de seguimiento, con su respectivo avance promedio (La suma del avance de cada trimestre dividido en la cantidad de trimestres registrados).
- Tabla resumen del plan de acción en el que se apilen todas las unidades por filas. Se debe manejar la misma estructura he información que se registra en la tabla resumen por unidad.
2. Aspectos a tener en cuenta:
- La tabla resumen debe poder desplegar y guardar la información del plan, por cada unidad registrada. Es decir que en principio, cada fila muestra la unidad y el avance promedio de esa unidad con respecto al plan. Oprimiendo encima de una unidad en particular, se despliega toda la información del plan asociada a esa unidad.
- La grafica debe mostrar claramente la información asociada a cada unidad.
3. Para mas información, consultar [Variables de Historia de Usuario relacionada](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ERnXVlOzYglGiQxvKqRZ7SkBXK6kdFyl6mB6wnqyf3Kpag?e=Oyydp3&nav=MTVfezE2Nzc5OUZCLTkzQTMtNDBDRS04ODYxLTdEOTMyMTQyQjUwNH0).

**Sub Tareas**

- [x] Creación de grafico del nivel de avance de todas las unidades.
- [x] Creación de tabla resumen del plan de acción en el que se incluyen todas las unidades.

**Criterios de aceptación**

- [x] Puedo ver en un grafico intuitivo, la información del nivel de avance general de cada unidad con respecto al plan de acción.
- [x] Puedo ver la información especifica de cada unidad, por trimestre y a nivel general, del plan de acción asociado, en una tabla resumen.

**Requerimientos**

- No presenta.

**Dependencias**

- planeacion_cliente.
- planeacion_mid.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
@felimarod por favor subir avances realizados a la fecha.

**Comment by felimarod** [comment]
Se agrego la funcionalidad del desplegable, sin embargo, faltan pruebas

**Comment by felimarod** [comment]
Pruebas funcionales https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EXLPJuPpSZ5Fp0FRxAnHROUBg7zJLS3HKttjoDtDJstF4A?e=x0gioB

**Comment by a52290451** [comment]
Observaciones y posibles mejoras:

1. La información asociada a la grafica y la tabla se podría cargar al seleccionar el Periodo y/o al seleccionar la opción "TODOS" en la unidad, quitando la necesidad de dar click en el botón “Consultar evaluación”.
2. Mejoramiento en la grafica de barras respecto a lo señalado en la PARTE 1.
3. En ocasiones las consultas tardan mucho dada la naturaleza de buscar bastante información desde bastantes puntos, esto sucede tanto en los filtros como al traer la información para la tabla o el desplegable de la misma.

**Comment by a52290451** [comment]
Se validan y aprueban pruebas realizadas tanto en planeacion_mid como en planeacion_cliente
