### ISSUE TITLE
1 - Refinamiento de campo Brecha y Sistema de colores en submódulo de Evaluación.

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#927]
Se requiere refinar la implementación asociada al campo **Brecha** en la tabla de **Evaluación Plan de Acción** del módulo de evaluación y el sistema de colores relacionado. 

**Especificaciones técnicas**

1. El campo **Brecha** debe ubicarse en cada trimestre, al lado derecho del campo **Cumplimiento por meta**. Este campo hace alusión _al porcentaje restante que le hace falta a cada actividad para cumplir con su meta en el trimestre indicado_.
2. El sistema de colores (Semáforo) debe ser ajustado a 5 colores y se debe ubicar en el campo **Cumplimiento por meta** asociado a cada trimestre.

![image](https://github.com/udistrital/planeacion_cliente/assets/36229498/a5e603c4-7537-46d2-b401-de07c1ae1d68)

3. El calculo del campo se realiza de la siguiente forma:

- _Meta(100%) - Cumplimiento por meta._

4. El campo debe calcularse por cada indicador de la actividad en cada trimestre de forma automática, una vez se cargue la información en la tabla.

**Sub Tareas**

- [x] Creación de Mockup para la modificación de la vista **Evaluación** en planes de acción, con el ajuste del campo **Brecha** y el sistema de colores en el campo **Cumplimento por meta** en cada trimestre.
- [x] Ajuste de campo **Brecha** en la tabla **Avance General Plan de acción** de la vista **Evaluación** en planes de acción.
- [x] Ajuste de lógica de sistema de colores (Semáforo) en campo **Cumplimiento por meta**.

**Criterios de aceptación**

- [x] En la tabla **Avance General Plan de acción** en el módulo de **Evaluación** en **Planes de acción**, se muestra el campo **Brecha** por trimestre asociado a cada indicador de cada actividad, a la derecha del campo **Cumplimiento por meta**.
- [x] En la tabla **Avance General Plan de acción** en el módulo de **Evaluación** en **Planes de acción**, se muestra en funcionamiento el sistema de colores asociado al campo **Cumplimiento por meta**.

**Requerimientos**

- No presenta.

**Dependencias**

- planeacion_cliente.
- planeacion_mid.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Se realiza el desarrollo en la siguiente rama:  [feature/modBrecha](https://github.com/udistrital/planeacion_cliente/tree/feature/modBrecha)

Se realizan las pruebas funcionales:
[Pruebas funcionales - Refinamiento de campo Brecha](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EVDm5HgOGnlHhlJLh3CgrEMBhC0eWSd3Nr6ZQ951qiSZqA?e=7EYvWE)

**Comment by a52290451** [comment]
@diegobauto por favor realizr PR a rama develop.

**Comment by a52290451** [comment]
Se completa la tarea.
