### ISSUE TITLE
Creación API planeacion_reportes_mid (PARTE 2)

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#928]
Se requiere completar la creación y pruebas del API **PLANEACION_REPORTES_MID** con base en el API **PLANEACION_MID**, de forma tal que los controladores asociados queden desacoplados del API principal.

**Especificaciones técnicas**

1. El repositorio para **PLANEACION_REPORTES_MID** es: 
https://github.com/udistrital/planeacion_reportes_mid
3. Se requiere migrar el código asociado a Reportes, del API **PLANEACION_MID** al API **PLANEACION_REPORTES_MID**.
4. El API debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevas APIs GO definidos por la OATI.
5. Los métodos de utilidades que son globales a todas las APIs deben ser migrados a la librería **utils_oas**.
6. Se debe optimizar el código migrado, eliminando malas practicas de desarrollo.
7. Tomar como referencia el diagrama de componentes elaborado en #803 .
8. Tomar como referencia la implementación de otros microservicios: #852 , #880 , #844 , #822 .

**Sub Tareas**

- [x] Desarrollo de API **PLANEACION_REPORTES_MID**
- [x] Migración de código entre APIs.
- [x] Optimización de código.

**Criterios de aceptación**

- [x] El API se encuentra desarrollada.
- [x] El código fuente del API está optimizado.

**Requerimientos**

- [x] Completar Issue #803 .
- [x] Completar Issue #917 .
- [ ] Dependencia con la creación del API **PLANEACION_EVALUACION_MID**

**Dependencias**

- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
### Reporte

- Se modificó el nombre de las siguientes funciones:
LimpiarDetalles -> limpiarDetalles
LimpiaIds -> limpiarIds
Limp -> limpiar
GetActividades -> getActividades
BuildTreeFa -> construirArbol
convert  -> convertir
getChildren -> getHijos
ArbolArmonizacionV2 -> arbolArmonizacionV2
ArbolArmonizacionPIV2 -> arbolArmonizacionPIV2
MinComMul_Armonization -> minComMulArmonizacion
TablaIdentificaciones -> tablaIdentificaciones
nombreRubroByCodigo -> nombreRubroPorCodigo
TotalDocentes -> getTotalDocentes
GetDataDocentes -> getDataDocentes
SombrearCeldas -> sombrearCeldas
Convert2Num -> convertirNumero

- Se mantuvo el nombre de las siguientes funciones:
add (igual)
contains (igual)
calcMinCol (igual)
construirTablas (igual)
codigoRubrosDocentes (igual)

- Se eliminaron las siguientes funciones:
Limpia (se eliminó)
ArbolArmonizacion (se eliminó)
ArbolArmonizacionPI (se eliminó)

- Se crearon nuevas funciones:
identificacionNueva
identificacionAntigua
estiloExcel
estiloExcelRotacion
estiloExcelBordes
DeformatNumberInt
DeformatNumberFloat
getTotales
getIdEstadoAval
Validar
ProcesarDesagregado
ProcesarPlanAccionAnual
ProcesarPlanAccionAnualGeneral
actualizarRecursosGeneral
actualizarRubro
ProcesarNecesidades
ProcesarPlanAccionEvaluacion

**Comment by diegobauto** [comment]
### Se deben tener en cuenta las siguientes variables de entorno:
httpport = ${PLANEACION_REPORTES_MID_HTTP_PORT}
runmode = ${PLANEACION_REPORTES_MID_RUNMODE||dev}
PlanesService = ${PLANES_SERVICE}
PlanCuentasService = ${PLAN_CUENTAS_SERVICE}
OikosService = ${OIKOS_SERVICE}
ParametrosService = ${PARAMETROS_SERVICE}

### Sus respectivos valores: 
export PLANEACION_REPORTES_MID_HTTP_PORT=8081
export PLANES_SERVICE=pruebasapi2.intranetoas.udistrital.edu.co:8523
export PLAN_CUENTAS_SERVICE=pruebasapi.intranetoas.udistrital.edu.co:8203/v1
export OIKOS_SERVICE=api.intranetoas.udistrital.edu.co:8087/v1
export PARAMETROS_SERVICE=pruebasapi.intranetoas.udistrital.edu.co:8510/v1

**Comment by a52290451** [comment]
@diegobauto por favor cargar pruebas funcionales relacionadas

**Comment by a52290451** [comment]
Se realiza solicitud para creación de ambiente de pruebas del API:

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=59320

**Comment by a52290451** [comment]
Variables de entorno en ambiente de pruebas:

- Name: PLANEACION_REPORTES_MID_PLANES_SERVICE
Value: pruebasapi2.intranetoas.udistrital.edu.co:8523
- Name: PLANEACION_REPORTES_MID_PLAN_CUENTAS_SERVICE
Value: pruebasapi.intranetoas.udistrital.edu.co:8203/v1
- Name: PLANEACION_REPORTES_MID_OIKOS_SERVICE
Value: api.intranetoas.udistrital.edu.co:8087/v1
- Name: PLANEACION_REPORTES_MID_PARAMETROS_SERVICE
Value: pruebasapi.intranetoas.udistrital.edu.co:8510/v1

**Comment by diegobauto** [comment]
El siguiente enlace va relacionado a una carpeta la cual contiene tanto las pruebas funcionales como los archivos excel generados en las diferentes pruebas: [Link de la carpeta](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EuWoeFp3o7xOoVO1o8ziiRcBvSE2c2mWJ0uNblNs6paPlA?e=UDlNQy)

**Comment by a52290451** [comment]
Se actualiza swagger,

@diegobauto, se requiere realizar pruebas del API en ambiente de pruebas, tanto por intranet como por autenticación:

http://pruebasapi3.intranetoas.udistrital.edu.co:8556/

https://autenticacion.portaloas.udistrital.edu.co/apioas/planeacion_reportes_mid/v1

**Comment by diegobauto** [comment]
Se realiza la validación para los diferentes endpoints, en la siguiente dirección: http://pruebasapi3.intranetoas.udistrital.edu.co:8556 , perteneciente a planeacion_reportes_mid.

- /validar_reporte (para los diferentes reportes):
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/587178e7-7a09-4640-beff-2a7772250b23)
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/e637ff54-e7ec-4990-b9f9-4413f89beb3c)
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/56592c6c-de38-4e91-ba78-961f1013aa02)
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/7add0d6f-b255-4517-9731-3f837ffaeebf)

- /plan_anual: 
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/6ad46fa8-104c-46fe-974d-d52dbef8bc33)
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/d2659963-9394-4b5f-817b-2f95faa94acd)

- /plan_anual_general:
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/3291c439-af87-4969-869c-c4f0e4f7bee9)
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/3d104958-d2cc-40ed-ac29-17bf216cebdb)

- /necesidades:
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/6bfb5d13-dd61-45ab-87b8-75933b95dcea)
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/d26c6ff1-52c6-4191-b089-b809ca090eba)

- /plan_anual_evaluacion:
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/e8f763f2-c62d-4859-bddf-8a9aafdf4e59)
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/9e552131-72f5-4867-8ba2-5e9496923618)
