### ISSUE TITLE
Creación API planeacion_seguimiento_mid Parte 2

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#929]
Se requiere terminar la creación el API **PLANEACION_SEGUIMIENTO_MID** con base en el API **PLANEACION_MID**, de forma tal que los controladores asociados queden desacoplados del API principal.

**Especificaciones técnicas**

1. El repositorio para **PLANEACION_SEGUIMIENTO_MID** es: https://github.com/udistrital/planeacion_seguimiento_mid
2. Se requiere migrar el código asociado a Formato, del API **PLANEACION_MID** al API **PLANEACION_SEGUIMIENTO_MID**.
3. El API debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevas APIs GO definidos por la OATI.
4. Los métodos de utilidades que son globales a todas las APIs deben ser migrados a la librería **utils_oas**.
5. Se debe optimizar el código migrado, eliminando malas practicas de desarrollo.

**Sub Tareas**

- [x] Desarrollo de API **PLANEACION_SEGUIMIENTO_MID**
- [x] Migración de código entre APIs.
- [x] Optimización de código.
- [x] Pruebas unitarias y funcionales.

**Criterios de aceptación**

- [x] El API se encuentra desarrollada.
- [x] El código fuente del API está optimizado.

**Requerimientos**

- [x] Completar Issue #803 .

**Dependencias**

- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
Se desarrollan las pruebas unitarias, pero por lo que se necesitan algunos formatos JSON, para su ejecución, no se pueden ejecutar con exito.

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/b82051c6-01f7-47c8-8c02-ec461e0eb496)

**Comment by Mechaz123** [comment]
Se adjuntan las pruebas funcionales:

https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EU94jqZYJTNFrx9X-Dy2Dt8BM8m_u2bzkpbJAHG3MsXeKQ?e=OzuzW3

**Comment by milo19980525** [comment]
No se evidencia cuales son las pruebas unitarias que deben contener su respectivo JSON para poderlas ejecutar. De igual manera el resultado de las pruebas no se observa.

Falta PR a develop.

**Comment by Mechaz123** [comment]
Se sube pantallazo de las pruebas unitarias, se debe de realizar la corrección del control de errores de los controladores, ya que algunos arrojan 200, pero la API detecta un APIBeegoError.

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/c449d1b2-efe0-4907-a0cc-e14cc78ee671)

**Comment by Mechaz123** [comment]
Las pruebas unitarias que requieren el archivo JSON son las mismas que están resaltadas en amarillo en el excel de pruebas funcionales del sistema.

**Comment by Mechaz123** [comment]
Los cambios se encuentran en develop actualmente, ya que, por un error de mi parte, se subieron a esa rama directamente, de igual manera se creó la rama feature/planeacion_seguimiento_mid.

**Comment by milo19980525** [comment]
Perfecto Daniel
