### ISSUE TITLE
Ajuste de consulta fechas de planes Seguimiento

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#932]
Se requiere ajustar la vista de seguimiento de planes/proyectos para que la fecha de periodo_seguimiento pueda ser consultada de manera correcta.

**Especificaciones técnicas**

- Actualmente el desarrollo del aplicativo se encuentra estabilizado en ambiente develop (Cliente, mid y crud).

**Sub Tareas**

- [x] La vista trae un seleccionable por vigencia y por unidad, la unidad debe ser escogida de manera automática para los roles: ASISTENTE_DEPENDENCIA, JEFE_DEPENDENCIA_PLANEACION Y JEFE_UNIDAD_PLANEACION (se saca de la dependencia donde pertenecen actualmente). Mientras que para el rol PLANEACION se debe permitir escoger la dependencia tal como se encuentra actualmente.
- [x] Posterior al seleccionable de unidad, debe existir un seleccionable por planes asociados a esa unidad (Lista de planes relacionados con esa unidad en periodo_seguimiento).
- [x] Una vez se escoge el plan se escoge la vigencia y esta muestra la configuración de fechas para ese plan y cada uno de sus trimestres.
- [x] Finalmente se despliega una tabla con la información correspondiente a un plan, sus trimestres, asociados a una vigencia, unidad y plan específico.

**Criterios de aceptación**

- [x] Los usuarios con roles ASISTENTE_DEPENDENCIA, JEFE_DEPENDENCIA_PLANEACION Y JEFE_UNIDAD_PLANEACION, seleccionan vigencia, proyecto y se despliega una tabla con la información relacionada a cada trimestre de ese plan, de igual manera en la información de fechas se muestran todas las fechas asociadas a ese plan.
- [x] El usuario con rol PLANEACION, seleccionan unidad, vigencia, proyecto y se despliega una tabla con la información relacionada a cada trimestre de ese plan, de igual manera en la información de fechas se muestran todas las fechas asociadas a ese plan.
- [x] El usuario con rol PLANEACION, seleccionan unidad, vigencia y se despliega una tabla con la información relacionada a cada trimestre de todos los planes de esa unidad y vigencia. En el componente informativo de fechas parametrizadas para los planes no se muestra ninguna fecha hasta que se seleccione un plan y su trimestre.

**Requerimientos**

- [x] Ninguno.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by ccmendezt** [comment]
## Evidencias - Ajuste de almacenamiento
### 08/03/2024 - 22:29 pm

- Se modificó el modelo agregándole 2 nuevas propiedades al _schema_ **plan**:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/bdf3d6b2-7de4-4be1-a957-fd31a171d59e)
Dichas propiedades se agregaron para poder distinguir los planes seleccionados para su seguimiento en las fechas planteadas.

- Las nuevas propiedades ya se implementaron en el flujo de la formulación de un plan de acción a partir de un formato desde la **API MID** (no fue necesario hacer cambios en el cliente para este item):
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/e3f5e042-3b13-4377-81c7-a6224ee16c33)

- Para el rol **planeación** el flujo ya se implementó en un 75%:
![almacenamientoSeguimiento](https://github.com/udistrital/planeacion_cliente/assets/82072560/dd8f7a64-aed1-416c-b368-320f04657071)

## Notas importantes:
  **i.** Aún falta validar las fechas para los planes que no tienen las nuevas propiedades para el rol planeación y ajustes menores.
  **ii.** Falta implementar el flujo para los roles ASISTENTE_DEPENDENCIA, JEFE_DEPENDENCIA_PLANEACION Y JEFE_UNIDAD_PLANEACION.

**Comment by milo19980525** [comment]
Por favor actualizar issue y subir el pr del cliente

**Comment by ccmendezt** [comment]
## Evidencias - Ajuste de consulta fechas de planes Seguimiento
### 13/03/2024 - 15:20 pm

- Se realizó la _validación de fechas_ que anteriormente **no funcionaba completamente**, ni _el cambio de colores de trimestres_ por plan:
    - **Flujo en pruebasplaneación actualmente:** 
    ![pruebasplaneacion-seguimiento-rol-unidad](https://github.com/udistrital/planeacion_cliente/assets/82072560/2469a4e9-37a2-4639-a0c0-8b3b45244171)
    
A continuación, se muestra el **flujo completo funcionando correctamente** para los **roles especificados** en la issue, _cargando correctamente las fechas_ y _evaluando los trimestres (cambiando los colores según su estado)_:

- Para el rol **PLANEACION** se muestra el flujo completo funcionando correctamente:
![seguimiento-rol-planeacion](https://github.com/udistrital/planeacion_cliente/assets/82072560/bb6392ff-87e8-4328-b4f5-9fc8a04b6743)

- Para los roles **ASISTENTE_DEPENDENCIA**, **JEFE_DEPENDENCIA_PLANEACION** Y **JEFE_UNIDAD_PLANEACION** se muestra el flujo completo funcionando correctamente:
![seguimiento-rol-unidad](https://github.com/udistrital/planeacion_cliente/assets/82072560/6f5f8198-ad6b-4768-a7d6-0b44a1eb299e)

## Pull Request asociados a issue

- **planes_crud:** https://github.com/udistrital/planes_crud/pull/96
- **planeacion_mid**: https://github.com/udistrital/planeacion_mid/pull/501
- **planeacion_cliente**: https://github.com/udistrital/planeacion_cliente/pull/947

**Comment by milo19980525** [comment]
Buen trabajo Cristian
