### ISSUE TITLE
2-1 Creación de microfrontend "utilidades-mf"

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#935]
Se requiere crear el microfrontend **planeacion-utilidades-mf** con base en el cliente **PLANEACION_CLIENTE**, de forma tal que los componentes asociados queden desacoplados del Cliente principal.

**Especificaciones técnicas**

1. El repositorio para **planeacion-utilidades-mf** es: 
https://github.com/udistrital/planeacion_utilidades_mf
3. Se requiere crear el cliente a partir de single-spa.
4. El API debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevos clientes definidos por la OATI.
5. Se debe adicionar el consumo de "planeacion-utilidades-mf" al microfrontend planeacion-root-mf* desarrollado en #925 .
7. Se debe optimizar el código migrado, eliminando malas practicas de desarrollo.
8. Tomar como referencia el diagrama de componentes elaborado en #910 .
9. Capacitación de Microfrontends: https://udistritaleduco-my.sharepoint.com/:v:/g/personal/ndmunozc_udistrital_edu_co/EQ18oP3BMztCuGj4fRbI540BKawZvWw7muAnTX3jDINSAQ?referrer=Teams.TEAMS-WEB&referrerScenario=MeetingChicletGetLink.view.view

**Sub Tareas**

- [x] Desarrollo del cliente **planeacion-utilidades-mf**
- [x] Consumo de "planeacion-utilidades-mf" desde "planeacion-root-mf".
- [x] Optimización de código.

**Criterios de aceptación**

- [x] El cliente se encuentra desarrollado.
- [x] El código está optimizado.
- [x] Se consume a core-mfy se evidencia su integración.

**Requerimientos**

- [x] Completar Issue #910  .

**Dependencias**

- planeacion_cliente
- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
Se realiza la migración del componente dashboard únicamente, ya que el componente de información básica, no se encuentra actualmente en funcionamiento en el sistema de planeación y así mismo no tiene conexiones con otros componentes dentro del miccrofrontend creado.

**Comment by Mechaz123** [comment]
Se logra realizar la conexión del dashboard de manera que no se tenga que acceder a utilidades/dashboard, si no directamente este se cargue al momento de ingresar al sistema automáticamente.

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/ab4cb119-1a45-4b66-bfd9-5bc43e996bc9)

**Comment by milo19980525** [comment]
Muy buen trabajo Daniel, por favor pr a Develop (ya está habilitado el repositorio), marca las casillas de tareas con las completadas en tareas.

Gracias

**Comment by Mechaz123** [comment]
Se solicitó el PR a la rama creada, por un error cometido y se actualizó la rama feature/planeacion_root_mf donde se agrega la ruta para el microfrontend de utilidades.
