### ISSUE TITLE
2-2 Creación de microfrontend "construccion-mf" PT-1

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#936]
Se requiere crear el microfrontend **planeacion-construccion-mf** con base en el cliente **PLANEACION_CLIENTE**, de forma tal que los componentes asociados queden desacoplados del Cliente principal.

**Especificaciones técnicas**

1. El repositorio para **planeacion-construccion-mf** es: 
https://github.com/udistrital/planeacion_construccion_mf
3. Se requiere crear el cliente a partir de single-spa.
4. El API debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevos clientes definidos por la OATI.
5. Se debe adicionar el consumo de "planeacion-construccion-mf" al microfrontend planeacion-root-mf* desarrollado en #925 .
7. Se debe optimizar el código migrado, eliminando malas practicas de desarrollo.
8. Tomar como referencia el diagrama de componentes elaborado en #910 .
9. Capacitación de Microfrontends: https://udistritaleduco-my.sharepoint.com/:v:/g/personal/ndmunozc_udistrital_edu_co/EQ18oP3BMztCuGj4fRbI540BKawZvWw7muAnTX3jDINSAQ?referrer=Teams.TEAMS-WEB&referrerScenario=MeetingChicletGetLink.view.view

**Sub Tareas**

- [x] Desarrollo del cliente **planeacion-construccion-mf**
- [x] Consumo de "planeacion-utilidades-mf" desde "planeacion-root-mf".
- [x] Optimización de código.

**Criterios de aceptación**

- [x] El cliente se encuentra desarrollado.
- [x] El código está optimizado.
- [x] Se consume a construccion-mf  se evidencia su integración.

**Requerimientos**

- [x] Completar Issue #910  .

**Dependencias**

- planeacion_cliente
- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
Gracias a Steven se logra migrar de una manera ágil y rápida el componente de árbol, pero aún se debe de refinar una parte de requestmanager, que parece que está presentando algún problema.

**Comment by milo19980525** [comment]
Por favor comentar estado actual del issue, y que queda pendiente para la segunda parte. Gracias.

**Comment by Mechaz123** [comment]
Se migra el apartado de listar-plan:
![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/3b3ca4aa-ad6b-4484-8b59-9f0c7ad6d379)

Se migra consultar-plan, pero aún se debe de realizar el ajuste para enlazarlo con listar-plan:
![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/a6753ccc-b2ca-40d6-a699-16491d674d18)

Y editar-dialog, se sigue modificando aún, ya que se está ajustando para las importanciones de algunas funciones propias de angular, pero ya se conecta con listar-plan:
![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/40543fac-10c2-4d2c-b723-91ea00b4200a)

**Comment by Mechaz123** [comment]
Aún queda pendiente migrar los siguientes componentes de plan:
![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/e3cbf0eb-cff9-4cf1-95a4-3cb997079a69)

**Comment by milo19980525** [comment]
También queda pendiente ajustar los estilos.
