### ISSUE TITLE
0-3 Transacciones de almacenamiento periodos de planes/proyectos

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#937]
Se requiere investigar e implementar un método que garantice el almacenamiento correcto de los periodos de cada uno de los planes tanto en formulación como en seguimiento.

**Especificaciones técnicas**

1. El almacenamiento de los periodos se realiza de manera separada por cada plan y fechas (dependiendo de las unidades), por lo que pueden suceder errores en las diferentes peticiones de almacenamiento. Tener en cuenta el issue #923 .
2. Se deben revisar las transacciones en mongo o una cola de peticiones de almacenamiento fallidas e informar al usuario.

**Sub Tareas**

- [x] Investigar la gestión de transacciones en Mongo DB a través de NEST JS

**Criterios de aceptación**

- [x] Se investiga sobre las migraciones.
- [x] Se emplea un mecanísmo para garantizar el almacenamiento de datos.

**Requerimientos**

- [x] Completar Issue #910  .

**Dependencias**

- planeacion_cliente
- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by ccmendezt** [comment]
## Evidencias - Avance **Transacciones de almacenamiento periodos de planes/proyectos**
### 15/03/2024 - 18:00 pm

Investigando la documentación sobre Mongo y NestJS se encontró lo siguiente:

Las transacciones son nuevas en **MongoDB 4.0** y **Mongoose 5.2.0**. Las transacciones le permiten ejecutar múltiples operaciones de forma aislada y potencialmente deshacer todas las operaciones si una de ellas falla. [Referencia](https://mongoosejs.com/docs/transactions.html)

Se encontró un [foro](https://wanago.io/2021/09/06/api-nestjs-transactions-mongodb-mongoose/) que permite implementar transacciones en NestJS usando Mongoose así que se siguió ese tutorial y se complementó con [otra documentación encontrada en Stackoverflow](https://stackoverflow.com/questions/67879357/nestjs-how-to-use-mongoose-to-start-a-session-for-transaction).

También se debe tener en cuenta que cuando el usuario con rol **PLANEACION** quiere registrar fechas para _formulación_ y _seguimiento_ para planes/proyectos, se realiza un registro por plan_interes en la tabla periodo_seguimiento y se le asocian las unidades de interés seleccionadas, por lo cual, en una petición pueden haber más de 1 solicitud de tipo POST/PUT para una asignación de fechas a un plan/es y unidad/es específicas. El siguiente es un _ejemplo_ de las **peticiones** que se realizan para almacenar unas fechas para la formulación de varios planes asociadas a unidades específicas:
```json
[
   {
      "Method":"PUT",
      "Id":"65f4c9a95983ba0abd0ff52c",
      "Body":{
         "__v":0,
         "_id":"65f4c9a95983ba0abd0ff52c",
         "activo":true,
         "fecha_creacion":"2024-03-15T22:20:25.207Z",
         "fecha_fin":"2024-04-30T00:00:00.000Z",
         "fecha_inicio":"2024-03-01T00:00:00.000Z",
         "fecha_modificacion":"2024-03-15T22:20:25.208Z",
         "periodo_id":"26",
         "planes_interes":"[{\"_id\":\"61305c7edf020f065956ba26\",\"nombre\":\"Ejemplo para SubDetalle v1\"}]",
         "tipo_seguimiento_id":"6260e975ebe1e6498f7404ee",
         "unidades_interes":"[{\"Id\":8,\"Nombre\":\"VICERRECTORIA ACADEMICA\"},{\"Id\":14,\"Nombre\":\"FACULTAD DE INGENIERIA\"}]"
      }
   },
   {
      "Method":"POST",
      "Id":"",
      "Body":{
         "activo":true,
         "fecha_fin":"2024-03-30T00:00:00.000Z",
         "fecha_inicio":"2024-03-01T00:00:00.000Z",
         "periodo_id":"26",
         "fecha_inicio":"2024-03-01T00:00:00.000Z",
         "periodo_id":"26",
         "planes_interes":"[{\"_id\":\"61305c7edf020f065956ba26\",\"nombre\":\"Ejemplo para SubDetalle v1\"}]",
         "tipo_seguimiento_id":"6260e975ebe1e6498f7404ee",
         "unidades_interes":"[{\"Id\":15,\"Nombre\":\"FACULTAD TECNOLOGICA\"}]"
      }
   },
   {
      "Method":"PUT",
      "Id":"65f4c9a95983ba0abd0ff52e",
      "Body":{
         "__v":0,
         "_id":"65f4c9a95983ba0abd0ff52e",
         "activo":true,
         "fecha_creacion":"2024-03-15T22:20:25.346Z",
         "fecha_fin":"2024-04-30T00:00:00.000Z",
         "fecha_inicio":"2024-03-01T00:00:00.000Z",
         "fecha_modificacion":"2024-03-15T22:20:25.346Z",
         "periodo_id":"26",
         "planes_interes":"[{\"_id\":\"61398379df020f786256e5a7\",\"nombre\":\"Plan de Acción Proyecto de Inversión\"}]",
         "tipo_seguimiento_id":"6260e975ebe1e6498f7404ee",
         "unidades_interes":"[{\"Id\":8,\"Nombre\":\"VICERRECTORIA ACADEMICA\"},{\"Id\":14,\"Nombre\":\"FACULTAD DE INGENIERIA\"}]"
      }
   },
   {
      "Method":"POST",
      "Id":"",
      "Body":{
         "activo":true,
         "fecha_fin":"2024-03-30T00:00:00.000Z",
         "fecha_inicio":"2024-03-01T00:00:00.000Z",
         "periodo_id":"26",
         "planes_interes":"[{\"_id\":\"61398379df020f786256e5a7\",\"nombre\":\"Plan de Acción Proyecto de Inversión\"}]",
         "tipo_seguimiento_id":"6260e975ebe1e6498f7404ee",
         "unidades_interes":"[{\"Id\":15,\"Nombre\":\"FACULTAD TECNOLOGICA\"}]"
      }
   }
]
```
Cabe destacar que las peticiones se realizan en orden _ascendente_ según se encuentran en el array.

- Dada la información encontrada se _implementó_ el siguiente código:
     **- En el controlador de _periodo-seguimiento_:**
     ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/0bebac10-7fe7-40ef-83cf-bab4bf4e27ab)
     **Comportamiento:** El controlador recibe justamente un array de peticiones guardando el tipo de petición a realizar con sus respectivos datos. Luego, el servicio procesa esas peticiones en una sola transacción y las ejecuta.
     **- En el servicio de _periodo-seguimiento_:**
     ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/8c69f163-1c58-42c5-89bd-389c31f8d294)
     ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/a84f1e8f-bef5-4f5f-be9e-784a48420793)
     **Comportamiento:** El servicio inicia una sesión y mediante la función _session.withTransaction()_ se le envían promesas asíncronas para la resolución de cada una de las peticiones existentes en el array mostrado anteriormente, en caso de que se hagan bien se hace el _session.commitTransaction()_ y en caso de que falle se realiza el _session.abortTransaction()_.

Como se puede apreciar en el _array de transacciones de ejemplo_ se realiza primero una petición tipo **PUT** y luego una tipo **POST**, así que a modo de prueba lo que se hizo fue lanzar un error intencional en la petición tipo POST, para que se realice primero de manera correcta la **PUT** y luego realizando la **POST**, ésta falle. Para eso se agregó simplemente la siguiente línea en el servicio de creación:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/4676b7e2-637e-45ed-97aa-cf2e74862ca5)
Así que se ejecuta la petición desde swagger y obtenemos la siguiente salida por consola:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/5761dcd2-20a1-43d3-97b3-ad775ccb4c0d)
El error nos dice que no se puede ejecutar el _session.abortTransaction()_ dos veces, lo cual es raro porque según la forma en la que se estructuró el código, cuando se genera un error pasa directamente al **catch** y se hace el **rollback**, lo cual NO sucede porque sí se edita el primer registro quedando de la siguiente manera:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/77c29e77-75eb-4089-9e8f-90965478a97d)
Allí se puede apreciar como sí se realiza correctamente la petición tipo **PUT** y en la petición tipo **POST** (donde se lanza el error intencionalmente), se termina la transacción, pero NO la aborta para dejar los registros tal como se encontraban antes de la edición del registro.

## Notas importantes:
  **i.** Se sigue investigando el origen del error y se está revisando si la implementación de las transacciones se realizó correctamente en la **API CRUD**.
  **ii.** A petición del líder técnico se realizará una prueba con una base de datos local instanciada en el pc mediante **Docker** para validar si el comportamiento en la base de datos local es o no el mismo.

**Comment by ccmendezt** [comment]
## Evidencias - Avance **Transacciones de almacenamiento periodos de planes/proyectos**
### 18/03/2024 - 15:38 pm

- Se creó un _contenedor en Docker_ con una base de datos de **MongoDB**:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/93d75b21-0fd8-43ad-8654-bc5eeffcf725)
- Se conectó la base de datos alojada en el contenedor de _Docker_ a la **API CRUD**:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/d25a2cbb-f971-4899-b0e5-820958399cea)
- Se probó nuevamente el flujo mencionado en el comentario anterior para las peticiones arrojando el error de manera intencional y este fue el resultado obtenido por consola:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/fe29b326-93fd-4cb6-a2ac-e37f519445d5)
A partir de la imagen podemos inferir que el error arrojado es el mismo, **Error aborting transaction:  MongoError: Cannot call abortTransaction twice**.
**El flujo realizado es el siguiente:** se realiza primero la petición tipo **PUT** _correctamente_, y cuando se realiza la petición tipo **POST** (la que tiene el error), se lanza el error, NO se completa la operación, pero tampoco se hace el _rollback_ de la operación realizada antes de la que lanza el error.

**Comment by milo19980525** [comment]
Por favor terminar de comentar con el método propuesto. Buen trabajo!

**Comment by ccmendezt** [comment]
## Evidencias - Avance **Transacciones de almacenamiento periodos de planes/proyectos**
### 19/03/2024 - 8:53 am

Debido a que no se pudo implementar correctamente la solución de transacciones para MongoDB, se propone una solución como alternativa que ya está implementada. Dicha solución envuelve un arreglo de peticiones que se realiza desde la API MID a la API CRUD para almacenar los periodo-seguimiento parametrizados por el usuario, y en dado caso de que alguna de estas no se realice correctamente, se le informa al usuario. También se tiene contemplada la contingencia frente a que se guarden algunos datos y otros no, ya que, en dado caso que se guarden lo mismos datos parametrizados (mismos planes, mismas fechas y mismas unidades) la API MID mediante un endpoint busca los registros duplicados y los sobreescribe, de tal forma que no habrá datos inutilizados o basura.
