### ISSUE TITLE
2-3 Creación de microfrontend "formulacion-mf"

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#939]
Se requiere crear el microfrontend **planeacion-formulacion-mf** con base en el cliente **PLANEACION_CLIENTE**, de forma tal que los componentes asociados queden desacoplados del Cliente principal.

**Especificaciones técnicas**

1. El repositorio para **planeacion-formulacion-mf** es: 
https://github.com/udistrital/planeacion_formulacion_mf
3. Se requiere crear el cliente a partir de single-spa.
4. El API debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevos clientes definidos por la OATI.
5. Se debe adicionar el consumo de "planeacion-formulacion-mf" al microfrontend planeacion-root-mf* desarrollado en #925 .
7. Se debe optimizar el código migrado, eliminando malas practicas de desarrollo.
8. Tomar como referencia el diagrama de componentes elaborado en #910 .
9. Capacitación de Microfrontends: https://udistritaleduco-my.sharepoint.com/:v:/g/personal/ndmunozc_udistrital_edu_co/EQ18oP3BMztCuGj4fRbI540BKawZvWw7muAnTX3jDINSAQ?referrer=Teams.TEAMS-WEB&referrerScenario=MeetingChicletGetLink.view.view

**Sub Tareas**

- [x] Desarrollo del cliente **planeacion-formulacion-mf**
- [x] Consumo de "planeacion-utilidades-mf" desde "planeacion-root-mf".
- [x] Optimización de código.

**Criterios de aceptación**

- [x] El cliente se encuentra desarrollado.
- [x] El código está optimizado.
- [x] Se consume a core-mfy se evidencia su integración.

**Requerimientos**

- [x] Completar Issue #910  .

**Dependencias**

- planeacion_cliente
- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by C0C045** [comment]
# Integracion del microfrontend de 'Formulación'
Ingresando a la ruta '/formulacion' podemos observar el respectivo componente y usar cada una de sus funcionalidades; tal cual como se muestra a continuación:
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/075fc0bd-93cf-4651-9e8f-d16fa7ccb5d0)
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/11da3a1c-b03c-4be0-bbde-99b48ccdd912)
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/8429be16-8a2d-4f01-b8b4-800d61a37469)

Por otro lado, el microfrontend se organiza de la siguiente forma; en dónde además podemos ver cuales fueron los componente y servicios adicionales para el correcto funcionamiento del modulo de formulación:
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/8421f203-9edf-43a0-9f02-3918b6765e9f)

**Comment by C0C045** [comment]
# Pruebas Funcionales
Enlace de acceso: https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EYwUggimZ5FKnkO3mytAOtoBZeGd3L88PKb7stS-fROT_g?e=qGwB92

**Comment by C0C045** [comment]
# PR's
En el root-mf: https://github.com/udistrital/planeacion_root_mf/pull/2
En formulacion-mf: https://github.com/udistrital/planeacion_formulacion_mf/pull/1

**Comment by milo19980525** [comment]
Muy buen trabajo Steven
