### ISSUE TITLE
2-4 Creación de microfrontend "evaluacion_mf"

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#940]
Se requiere crear el microfrontend **planeacion_evaluacion_mf** con base en el cliente **PLANEACION_CLIENTE**, de forma tal que los componentes asociados queden desacoplados del Cliente principal.

**Especificaciones técnicas**

1. El repositorio para **planeacion_evaluacion_mf** es: 
**(https://github.com/udistrital/planeacion_evaluacion_mf)**
3. Se requiere crear el cliente a partir de single-spa.
4. El API debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevos clientes definidos por la OATI.
5. Se debe adicionar el consumo de "planeacion_evaluacion_mf" al microfrontend planeacion_root_mf* desarrollado en #925 .
7. Se debe optimizar el código migrado, eliminando malas practicas de desarrollo.
8. Tomar como referencia el diagrama de componentes elaborado en #910 .

**Material de apoyo**

- Sesión de capacitación Microfrontends: https://udistritaleduco-my.sharepoint.com/:v:/g/personal/ndmunozc_udistrital_edu_co/EQ18oP3BMztCuGj4fRbI540BKawZvWw7muAnTX3jDINSAQ?referrer=Teams.TEAMS-WEB&referrerScenario=MeetingChicletGetLink.view.view 

**Sub Tareas**

- [x] Desarrollo del cliente **planeacion_evaluacion_mf**
- [x] Consumo de "planeacion_evaluacion_mf" desde "planeacion_root_mf".
- [x] Optimización de código.

**Criterios de aceptación**

- [x] El cliente se encuentra desarrollado.
- [x] El código está optimizado.
- [x] Se consume a core-mf y se evidencia su integración.

**Requerimientos**

- [x] Completar Issue #910  .

**Dependencias**

- planeacion_cliente
- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Se sube el desarrollo en rama develop: https://github.com/udistrital/planeacion_evaluacion_mf
Se realizan pruebas funcionales: [Link](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EQUBhw26icBEg0U6TYuNlT4Br2APDi4LM3tVhl6P7AgFVg?e=IchXmX)

**Comment by a52290451** [comment]
@diegobauto,

Para finalizar la actividad, se requiere actualizar el Readme del repositorio, de acuerdo a los [lineamientos ](https://github.com/udistrital/lineamientos_oas)establecidos.
