### ISSUE TITLE
2-5 Creación de microfrontend "reportes_mf"

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#941]
Se requiere crear el microfrontend **planeacion_reportes_mf** con base en el cliente **PLANEACION_CLIENTE**, de forma tal que los componentes asociados queden desacoplados del Cliente principal.

**Especificaciones técnicas**

1. El repositorio para **planeacion_reportes_mf** es: 
**(https://github.com/udistrital/planeacion_reportes_mf)**
3. Se requiere crear el cliente a partir de single-spa.
4. El API debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevos clientes definidos por la OATI.
5. Se debe adicionar el consumo de "planeacion_reportes_mf" al microfrontend **planeacion_root_mf** desarrollado en #925 .
7. Se debe optimizar el código migrado, eliminando malas practicas de desarrollo.
8. Tomar como referencia el diagrama de componentes elaborado en #910 .

**Material de apoyo**

- Sesión de capacitación Microfrontends: https://udistritaleduco-my.sharepoint.com/:v:/g/personal/ndmunozc_udistrital_edu_co/EQ18oP3BMztCuGj4fRbI540BKawZvWw7muAnTX3jDINSAQ?referrer=Teams.TEAMS-WEB&referrerScenario=MeetingChicletGetLink.view.view 

**Sub Tareas**

- [x] Desarrollo del cliente **planeacion_reportes_mf**
- [x] Consumo de "planeacion_reportes_mf" desde "planeacion_root_mf".
- [x] Optimización de código.

**Criterios de aceptación**

- [x] El cliente se encuentra desarrollado.
- [x] El código está optimizado.
- [x] Se consume a core_mf y se evidencia su integración.

**Requerimientos**

- [x] Completar Issue #910  .

**Dependencias**

- planeacion_cliente
- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
![image](https://github.com/udistrital/planeacion_cliente/assets/36229498/94575057-9fba-45cb-8213-85ed2220fe46)

**Comment by diegobauto** [comment]
Se actualiza el repositorio con los cambios correspondientes de acuerdo a la creación del microfrontend para reportes, en rama develop: https://github.com/udistrital/planeacion_reportes_mf

**Comment by diegobauto** [comment]
Se realizaron pruebas funcionales, link de acceso: [Link](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EUxQjUOaS5dCheE4_5TtJFgBQbiMEfHtCMwqP0FpTOTm0g?e=Qp4IwS)

En la siguiente carpeta ( [Link carpeta](url) ), se encuentran los archivos excel de las pruebas correspondientes a las diferentes categorias (PlanAccion, PlanAccionGeneral, Necesidades y Evaluación), cada una incluye tres archivos:
  1. El reporte de como funciona actualmente (pruebasplaneacion)
  2. El reporte apuntando a planeacion_mid
  3. El reporte apuntando a planeacion_reportes_mid.

**Comment by a52290451** [comment]
Se valida y aprueba documentación subida.
