### ISSUE TITLE
Levantamiento de requerimientos Reversión de planes (seguimiento -> formulación)

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#946]
Efectuar el levantamiento de requerimientos asociado a la reversión de planes de la fase de seguimiento a formulación.

Actividades:

- [ ] Presentar propuesta base para discutir y refinar con el usuario.
- [ ] Establecer, en comunicación con el usuario, el requerimiento a detalle.
- [ ] Construir HU para llevar a fase de desarrollo por parte del equipo.

**Comment by BikerMetalHead** [comment]
Adjunto proceso de reversión a formulación general.
[Proceso_Reversion](https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7B41BCF109-BD6A-4B32-B6ED-695936D84874%7D&file=propuesta%20de%20proceso%20de%20reformulacion%20(general).xlsx&action=default&mobileredirect=true)

**Comment by milo19980525** [comment]
Hoy se llevó a cabo el seguimiento sobre este issue, del cual se realizaron las observaciones de:

- [ ] Especificar más sobre cada una de las fases y cuales son las posibles opciones que se pueden dar en estas.
- [ ] Crear diagrama BPMN con la piscina asociada al proceso de reversión de plan con los carriles correspondientes a cada uno de los actores involucrados.
- [ ] En dado caso de requerir generar la diagramación de subprocesos al encontrar agrupamiento de tareas o la descripción de una tarea compleja.
El jueves se llevará a cabo la reunión con el usuario, por lo que es necesario que para el día miércoles se tenga la propuesta relacionada con los puntos previamente mencionados.

**Comment by BikerMetalHead** [comment]
Se traslada y mejora el diagrama (aún general) a BPMN BIZAGI. El proceso general seguirá en construcción mientras se evalúan los escenarios de evaluación e implicaciones a los procesos:
[PrGeneralV2](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EWDsjHGqqkBPsovuP0c-YREBlciq_b5VQ66UaOwbQ53Xvg?e=pdzqc8)

**Comment by milo19980525** [comment]
Se evidencia el avance, sin embargo se requiere especificar en la decisión a que hace referencia cada flujo saliente, ajustar el texto de la decisión para que se visualice cercano a esta.

Por otra parte, es necesario ser más específico en cada uno de los subprocesos definidos.

El agrupamiento  "Rechaza" no existe, esto es una tarea en el flujo, no la terminación del mismo.

**Comment by BikerMetalHead** [comment]
Análisis preliminares para la reformulación de planes de acción
Posibles cambios a efectuar en la reformulación:
-	Cambios en indicador
-	Cambios en actividades
-	Cambios en definición (objetivos)
-	Cambios en aportes a los lineamientos
-	Cambios en recursos ops
-	Cambios en recurso docentes 
-	Cambio total del plan 
Reglas generales propuestas frente a los cambios 
-	Todo cambio a realizar debe estar debidamente sustentado y aprobado por la oap
-	Los cambios realizados deben conservar la regla que las ponderaciones totales de indicadores sumen el 100% tanto a nivel general como particular 
-	Los cambios realizados a los recursos sean ops o recursos docentes no deben afectar el presupuesto asignado. 
-	Al momento de realizar un cambio e implementarlo en el plan de acción se genera un punto de corte en donde: la parte correspondiente a lo ya medido (el pasado) se conserva igual, generando un cierre de esa parte del plan. Para la parte futura del plan, después del punto de corte, el plan se genera con una versión superior y una nota aclaratoria que indique la reformulación de alguno de sus componentes 
-	Se debe asegurar al momento de implementar los cambios; estos no involucren un mayor gasto del presupuesto asignado
-	Si, al realizar los cambios en el plan se libera parte del presupuesto asignado, este movimiento debe ser informado a la oap para su autorización y se debe conocer el nuevo destino de los recursos monetarios liberados

estos lineamientos están pendientes de ser discutidos y avalados por  OAP

**Comment by BikerMetalHead** [comment]
Se realiza maqueta de las pantallas de menú, ubicación de plan de acción y solicitud de reformulación.
[drawio](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EZXnlf8ml91Om9Sv5SaMrA8BI8CjwMkyo-OtECvp4KhfWw?e=7RazTt)
[menu](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/EeiMfZdeAD1Fhknrd5gSYnEBsFdMeGhtJ_4sZL5_1WEpeQ?e=7L1eDF)
[ubicacion](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/ESZ9C8hs1o5Lj0Br2kX-PNUBhwAUtaODHyNAZPkzfFsHVg?e=U1WFpZ)
[reformulacion](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/EbegFFZMWfhJmOnQZSfduloB3K3uB4FnQzwxJQCbDHkrJA?e=9rt3sw)

**Comment by BikerMetalHead** [comment]
Se adjunta primera versión de hu para ID de actividades (en espera de aprobación)
[HusuarioID](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ERIMfyWAt6hKo6IHRZx9mfABe2VKYiESlSePOwYzfW940w?e=4MOOIM)

**Comment by BikerMetalHead** [comment]
Se realiza historia de usuario para el menú y el avance del proceso de reformulación
[HususarioReformulacion](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EblbB6lpKflDo68m43r7hawBTXmOkSght8jweLAVacoZBg?e=AJet1J)

**Comment by norbeydanilo** [comment]
- [ ] Revisar observacines de @milo19980525 

- [ ] Avanzar en propuesta de mockups/HUs para reversión.

@BikerMetalHead

**Comment by BikerMetalHead** [comment]
Se presentan avances en la propuesta para las hu de id por actividad (falta de aprobación por parte de planeación)
y hu de reformulación 

[HusuarioID](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ERIMfyWAt6hKo6IHRZx9mfABe2VKYiESlSePOwYzfW940w?e=4MOOIM)
[HususarioReformulacion](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EblbB6lpKflDo68m43r7hawBTXmOkSght8jweLAVacoZBg?e=AJet1J)

**Comment by BikerMetalHead** [comment]
Según las observaciones recibidas se adjuntan los archivos trabajados. Con la revisión ortográfica, la colección de la denominación del rol auxiliar por rol asistente y se adjuntan los backups
[HusuarioID](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ERIMfyWAt6hKo6IHRZx9mfABe2VKYiESlSePOwYzfW940w?e=4MOOIM)
[HususarioReformulacion](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EblbB6lpKflDo68m43r7hawBTXmOkSght8jweLAVacoZBg?e=AJet1J)
Mockups[https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EZXnlf8ml91Om9Sv5SaMrA8BI8CjwMkyo-OtECvp4KhfWw?e=ZFTjss](url)

**Comment by BikerMetalHead** [comment]
Actualización de contenido 
[HusuarioID](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ERIMfyWAt6hKo6IHRZx9mfABe2VKYiESlSePOwYzfW940w?e=4MOOIM)
[HususarioReformulacion](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EblbB6lpKflDo68m43r7hawBTXmOkSght8jweLAVacoZBg?e=AJet1J)
[Mockups](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EV_z5J91Qv1Et28hh6XkwPcBLDlh8mjnjo3itTqhuD3wrw?e=P8wkRs)

**Comment by BikerMetalHead** [comment]
Se actualizan, corrigen y generan historias de usuario para reformulación. También se actualiza mockup:
[Mockups](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/EXPP-MxpcbNImSGZo3c3_L0BfOrjPdxv5EqKol-Rm5k2WQ?e=RzvgNn)
[HusuarioID](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ERIMfyWAt6hKo6IHRZx9mfABe2VKYiESlSePOwYzfW940w?e=4MOOIM)
[HuReformulacion](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EU8JAVlgKopIjCO3x_y-37UBinCjGRfVNWaa_W5caPskyQ?e=Mzl6yX)

**Comment by BikerMetalHead** [comment]
Se muestra los avances frente a los backups realizados 
[pantalla_1 ](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/ER5rAn96qPxHnGLukZVMd2IBxhgnGo4lG1JKMyMmB9L3fQ?e=QfpF6T)
[pantalla_2](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EXz1YcBxqdRLudbZ09F_PSQBYFDLfw0TQqPc9aVtsTYXGg?e=y0EFOY)
[pantalla_3](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EaAxSXxrkkRLlnqy8dwwH7kBb_IOJck1jKpV-HpBYD5rTg?e=LGkqcg)
[pantalla_4](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EXz1YcBxqdRLudbZ09F_PSQBYFDLfw0TQqPc9aVtsTYXGg?e=GBccoY)
[pantalla_5](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/ER5rAn96qPxHnGLukZVMd2IBxhgnGo4lG1JKMyMmB9L3fQ?e=FOd2SC)

[HuSolciitud](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ET4etzVij-FPon1i08UnvUcBRUwrgNKMiksDUbVR_YEdsw?e=56Pvfd)
[HuTablaSolcitudes](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ET4etzVij-FPon1i08UnvUcBRUwrgNKMiksDUbVR_YEdsw?e=56Pvfd)

**Comment by norbeydanilo** [comment]
@BikerMetalHead Adjuntar flujo con estados para claridad del proceso e HUs completadas para dar cierre a la issue.

**Comment by BikerMetalHead** [comment]
Se realiza corrección sobre los links de los backups
[pantalla_1](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/ETN2DmPjP_REiPxPJRI5uIIBED_YVPN4NeN6Ddf-Qz6Tgw?e=W4gksw)
[pantalla_2](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EZT3UasU9C1Jjt4oxrAjmW0BqholdiIrNyzaQqdJAUVBsA?e=ZV9Sdp)
[pantalla_3](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EQQ3KsAtUtVCoRlVG1HwfRcBfexnDdZW7cgUMx7wouiolg?e=gj9bzb)
[pantalla_4](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EeW4ShhK9vFKv9nCqNHdSooBaLA7G4AW6HIG2Auj-HbhMQ?e=Qy6uon)
[pantalla_5](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EUat2NsFmoxCiDqjcGTKcQ4BYZ_IZpGlETIm9XB0sxzgLA?e=lka2DY)

[HuSolciitud](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ET4etzVij-FPon1i08UnvUcBRUwrgNKMiksDUbVR_YEdsw?e=56Pvfd)
[HuTablaSolcitudes](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EbeHVCB3RUlAqzJQeoHiTGwBByhNjCkMhhPkjAfwsMmxVA?e=Aplk4u)

**Comment by norbeydanilo** [comment]
Ya se han tomado en consideración para el desarrollo e implementación. Se da cierre a la issue.

Cualquier observación puede y debe ser añadida.
