### ISSUE TITLE
2-2 Creación de microfrontend "construccion-mf" PT-2

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#950]
Se requiere continuar con el desarrollo del microfrontend **planeacion-construccion-mf** con base en el cliente **PLANEACION_CLIENTE**, de forma tal que los componentes asociados queden desacoplados del Cliente principal.

**Especificaciones técnicas**

1. El repositorio para **planeacion-construccion-mf** es: 
https://github.com/udistrital/planeacion_construccion_mf
3. Se requiere crear el cliente a partir de single-spa.
4. El API debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevos clientes definidos por la OATI.
5. Se debe adicionar el consumo de "planeacion-construccion-mf" al microfrontend planeacion-root-mf* desarrollado en #925 .
7. Se debe optimizar el código migrado, eliminando malas practicas de desarrollo.
8. Tomar como referencia el diagrama de componentes elaborado en #910 .
9. Capacitación de Microfrontends: https://udistritaleduco-my.sharepoint.com/:v:/g/personal/ndmunozc_udistrital_edu_co/EQ18oP3BMztCuGj4fRbI540BKawZvWw7muAnTX3jDINSAQ?referrer=Teams.TEAMS-WEB&referrerScenario=MeetingChicletGetLink.view.view
10. Continuar con lo desarrollado en: #936 

**Sub Tareas**

- [x] Desarrollo del cliente **planeacion-construccion-mf**
- [x] Consumo de "planeacion-utilidades-mf" desde "planeacion-root-mf".
- [x] Optimización de código.

**Criterios de aceptación**

- [x] El cliente se encuentra desarrollado.
- [x] El código está optimizado.
- [x] Se consume a construcción_mf y se evidencia su integración.
- [x] Se prueba y valida que el mf responda correctamente.

**Requerimientos**

- [x] Completar Issue #910  .

**Dependencias**

- planeacion_cliente
- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
Dentro de las vistas que quedaban faltando se desarrolla:
- crear-plan
![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/2accca92-a5d8-41bc-95b4-3a1d1bfb818c)

- construir-plan
![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/be3f024e-c9c0-4483-a64e-60c40d41a15a)

- agregar-dialog
![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/5bca0239-80b6-45ea-9368-b6f768cb9298)

- construir-plan-proyecto
![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/dc401263-29c2-491c-bd64-b027791baa5d)

- gestion-parametros
![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/805f0831-6aa3-4f2c-ae0f-6266f179d427)

- habilitar-reporte
![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/2b33fcae-105d-48c2-89e5-7b87d34ad159)

- consultar-plan (Plan de Acción)
![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/d900edd2-243b-4ecd-94bc-3ad6cae21c57)

**Comment by milo19980525** [comment]
Buen trabajo Daniel, por favor realizar el respectivo pull request.

**Comment by Mechaz123** [comment]
Listo, ya se solicitó el PR para la revisión.

**Comment by milo19980525** [comment]
Por favor conectar con los mf's de formulación y seguimiento

**Comment by Mechaz123** [comment]
Existe un pequeño inconveniente al enlazar los datos con Formulación, el siguiente ejemplo es una vista desde planeación en ambiente de pruebas:

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/252e2152-2bc2-4f44-9067-7273255b05f2)

Ahora se selecciona el que se encuentra en fase de formulación

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/c410a3e9-2c25-4147-8c7b-60d857e66d62)

Carga los datos de manera exitosa !

**Comment by Mechaz123** [comment]
Ahora con el sistema que se encuentra actualmente en desarrollo, se va a recrear el mismo caso:

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/00d1853f-62df-4fa1-8a28-df53ea41a147)

Ahora se selecciona el que se encuentra en fase de formulación

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/ca337d55-657d-4625-9eb8-8548c9a554fc)

Se carga otra vista diferente a la esperada, pero la URL con los datos coincide, para cargar los datos del plan seleccionado, se requiere seleccionarlos manualmente.

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/7fa2f8a1-90a4-45b8-995e-c2c1749f2190)

**Comment by Mechaz123** [comment]
Para el caso de la conexión con seguimiento si ha intentado con varios casos tanto en planeacion pruebas, como en el sistema que se está desarrollando y el resultado es el mismo, aparece que no se encontraron planes y aparece la vista base.

Planeación Pruebas:

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/35d64d61-13ec-4391-baf3-33c90dc2386f)

Sistema en desarrollo:

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/e4048cfc-3f00-4e93-8cef-6f096fddcc99)

**Comment by Mechaz123** [comment]
Se conecta el microfrontend de construcción con el microfrontend de formulación.

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/89ffa26c-a80e-4c06-a0b5-dd02661273fd)

**Comment by Mechaz123** [comment]
Hola buen día, ya se acaba de solicitar el PR
