### ISSUE TITLE
2-8 Creación de microfrontend "macroplanes_mf"

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#951]
Se requiere crear el microfrontend **planeacion_macroplanes_mf** con base en el cliente **PLANEACION_CLIENTE**, de forma tal que los componentes asociados queden desacoplados del Cliente principal.

**Especificaciones técnicas**

1. El repositorio para **planeacion_macroplanes_mf** es: 
**(https://github.com/udistrital/planeacion_macroplanes_mf)**
3. Se requiere crear el cliente a partir de single-spa.
4. El API debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevos clientes definidos por la OATI.
5. Se debe adicionar el consumo de "planeacion_macroplanes_mf" al microfrontend **planeacion_root_mf** desarrollado en #925 .
7. Se debe optimizar el código migrado, eliminando malas practicas de desarrollo.
8. Tomar como referencia el diagrama de componentes elaborado en #910 .

**Material de apoyo**

- Sesión de capacitación Microfrontends: https://udistritaleduco-my.sharepoint.com/:v:/g/personal/ndmunozc_udistrital_edu_co/EQ18oP3BMztCuGj4fRbI540BKawZvWw7muAnTX3jDINSAQ?referrer=Teams.TEAMS-WEB&referrerScenario=MeetingChicletGetLink.view.view 
- Sesión 2: [Revisión de MF Planeación-20240311_111601-Grabación de la reunión.mp4](https://udistritaleduco-my.sharepoint.com/personal/cerochac_udistrital_edu_co/Documents/Grabaciones/Revisi%C3%B3n%20de%20MF%20Planeaci%C3%B3n-20240311_111601-Grabaci%C3%B3n%20de%20la%20reuni%C3%B3n.mp4)
- Sesión 3: [https://udistritaleduco-my.sharepoint.com/:v:/g/personal/cerochac_udistrital_edu_co/ES41RgsHxCpKhdRlRiH-kgMB_jD0IfyQHvJkSjHNnb3ZYw?referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/cerochac_udistrital_edu_co/ES41RgsHxCpKhdRlRiH-kgMB_jD0IfyQHvJkSjHNnb3ZYw?referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view&isSPOFile=1)

**Sub Tareas**

- [x] Desarrollo del cliente **planeacion_macroplanes_mf**
- [x] Consumo de "planeacion_pendientes_mf" desde "planeacion_root_mf".
- [x] Optimización de código.

**Criterios de aceptación**

- [x] El cliente se encuentra desarrollado.
- [x] El código está optimizado.
- [x] Se consume a planeacion_macroplanes_mf y se evidencia su integración.
- [x] Se debe probar el funcionamiento de los componentes visuales.

**Requerimientos**

- [x] Completar Issue #910  .

**Dependencias**

- planeacion_cliente
- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
El microfrontend se encuentra desarrollado, gran parte de las vistas de este microfrontend se encuentran en fase de construcción por lo cual el sistema desplega el siguiente mensaje:

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/53f8b99d-41ec-44cd-9b17-f0d879b8f0fa)

Aún se sigue trabajando en el despliegue de la imagen de fondo ya que se ha intentado de varias maneras y no se ha podido lograr conectar, por temas del root y el microfrontend.

Por otra parte, las vistas relacionadas que si poseian código, se encuentran migradas:

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/b3af3777-cae8-4c2c-ab28-4e9f05963641)

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/dc0f17f0-ce64-49d8-a616-6f64ad3f75d8)

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/8fb9a905-7928-4620-99d9-3abb4a5a12ad)
