### ISSUE TITLE
Apropiación de generalidades SISGPLAN

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#953]
Se requiere realizar la apropiación de generalidades asociadas a las características generales del sistema SISGPLAN y el enfoque de trabajo utilizado en la OATI para el desarrollo ágil.

**Especificaciones técnicas**

1. Revisión general de grabaciones de capacitación del sistema SISGPLAN y su lógica de negocio. 
2. Revisión general de grabaciones de capacitación del enfoque de trabajo utilizado en la OATI para el desarrollo ágil.
3. Desarrollo de ejercicios prácticos para afianzar el conocimiento obtenido en las sesiones de capacitación.

**Material de apoyo**

- [Jornada de capacitación 1.](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/luasanchezl_udistrital_edu_co/EWlFFK5IMrpEhZuDCZIXM4QBZNxZJWTx2CM8LzrYyVyo5Q?referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view)
- [Jornada de capacitación 2.](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/resanchezc_udistrital_edu_co/EZv6iVXZGI5PrHZoovd3EfIBHbJyIQ2UvH56hxsmHlezqg?referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view)
- [Jornada de capacitación 3.](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/resanchezc_udistrital_edu_co/EUPTE__l0IhDrHpKSTDBxXEBrJWufZyi490qb2kwM3hCww?referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view)
- [Jornada de capacitación 4.](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/resanchezc_udistrital_edu_co/Ea9IlIzW01lBnIc1pBwjobMBJYVT7SUdCSalE29x1nJC_g?referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view)
- [Jornada de capacitación 5.](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/resanchezc_udistrital_edu_co/EanNhswn0P9No8_MttF40OMBWdOZytlS1-PiFtVT82KsSQ?referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view)
- [Jornada de capacitación 6.](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/daarojasg_udistrital_edu_co/EeHlI7pFpBRBvtpsYLbgkdcBxK8dyejD3tVC2q2HsDsfGw?referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view)
- [Jornada de capacitación 7.](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/luasanchezl_udistrital_edu_co/EWzTIiV4HBhMgKdsbfRgU8cBopWNynOh2pWweNK6_ljW-w?referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view)
- [Documentación de SISGPLAN.](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Eg7Us5oK-YFEpOPjBM8F3jsBbfu0tkTE8wlwwfK0Kq-0NQ?e=tNMGfK)
- [Inventario de APIs](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EXe1wj9ZcSJDmu3HbTz6yd8BmVEACcVmmBxio-uEmxPVag?e=HsCF12).
- [Drone.](https://hubci.portaloas.udistrital.edu.co/)
- [API Store.](https://autenticacion.portaloas.udistrital.edu.co/store/apis/list?query=&tenant=carbon.super)
- [Lineamientos OATI.](https://github.com/udistrital/lineamientos_oas)
- Ambiente de pruebas SISGPLAN: https://pruebasplaneacion.portaloas.udistrital.edu.co/#/pages/dashboard

**Sub Tareas**

- [x] #965
- [x] #966
- [x] #967
- [x] #968

**Criterios de aceptación**

- [x] El desarrollador ha revisado y analizado las capacitaciones del sistema SISGPLAN, generando dudas e inquietudes al respecto.
- [x] El desarrollador ha revisado y analizado las capacitaciones del enfoque de trabajo utilizado en la OATI para el desarrollo ágil, generando dudas e inquietudes al respecto.
- [x] El desarrollador ha revisado la documentación asociada a SISGPLAN, comprendiendo aspectos clave del sistema.
- [ ] El desarrollador ha completado todos los ejercicios prácticos asociados a las capacitaciones, quedando listo para iniciar actividades de desarrollo.

**Requerimientos**

- [x] Acceso a grabaciones de capacitaciones.
- [x] Acceso a documentación de SISGPLAN.
- [x] VPN

**Dependencias**

- planeacion_cliente
- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Oscarjaimes1710** [comment]
1.Se termina la Revisión de capacitaciones de sisgplan al 100%, y se generan bastantes dudas que se han ido resolviendo con la lectura de los lineamientos.

2.Se Revisan las capacitaciones de desarrollo Ágil y se general inquietudes que se responden con la documentación de los lineamientos de OAS.

3.Se revisa toda la documentación de SISGPLAN tratando así de entender la estructura del sharepoint de SISGPLAN, para así poder tener una visión clara de donde se encuentran las rutas de la documentación.

**Comment by Oscarjaimes1710** [comment]
<img width="273" alt="Captura de pantalla 2024-04-01 a la(s) 11 42 01 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/b8301b40-c80f-45e0-a5b5-bf7bcfc8e69a">

<img width="1512" alt="Captura de pantalla 2024-04-01 a la(s) 11 43 37 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/73146d19-4afc-46fb-b837-a49d5a834966">
<img width="1382" alt="Captura de pantalla 2024-04-01 a la(s) 11 45 28 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/b9c8062f-bbb0-46b1-9de3-bbb0502c5455">

**Comment by Oscarjaimes1710** [comment]
<img width="1512" alt="Captura de pantalla 2024-04-02 a la(s) 12 26 25 a  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/b080dcca-f9db-473f-9601-2c3d44fe203e">

**Comment by a52290451** [comment]
@Oscarjaimes1710 por favor subir evidencia de la instalación del cliente y su funcionamiento en local. Adicionalmente realizar algunas pruebas entre el cliente y el mid.

**Comment by Oscarjaimes1710** [comment]
Cliente ya corriendo 
<img width="1512" alt="Captura de pantalla 2024-04-02 a la(s) 3 31 29 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/52173bc5-5acf-4285-98a5-c138afb52c86">

**Comment by Oscarjaimes1710** [comment]
<img width="1512" alt="Captura de pantalla 2024-04-03 a la(s) 8 38 10 a  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/d8798666-7a97-49e5-8f6d-c46ffdebc31d">
<img width="1512" alt="Captura de pantalla 2024-04-03 a la(s) 8 40 23 a  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/698e9a86-f9e6-40f9-8b45-a557f2fe50d5">

**Comment by Oscarjaimes1710** [comment]
<img width="1512" alt="Captura de pantalla 2024-04-04 a la(s) 6 56 46 a  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/ef0df565-9722-44c3-9cc8-3a6b9de864db">
<img width="1512" alt="Captura de pantalla 2024-04-04 a la(s) 6 56 57 a  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/3c8c7bb2-cd2b-430b-98c5-a14848687cb4">
<img width="1512" alt="Captura de pantalla 2024-04-04 a la(s) 6 57 08 a  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/bdc243a1-e891-431c-b303-244aa6d2e5f1">
<img width="1512" alt="Captura de pantalla 2024-04-04 a la(s) 6 57 56 a  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/4ddcdbd7-2347-4718-94ac-8dadc58ae242">
<img width="1512" alt="Captura de pantalla 2024-04-04 a la(s) 6 59 56 a  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/3e1828b4-8fcc-42c5-bb95-c102a1a1822b">
<img width="1512" alt="Captura de pantalla 2024-04-04 a la(s) 7 00 50 a  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/1c08109d-203b-4008-8f72-f38d3c437042">
