### ISSUE TITLE
HU2 - 2 Edición de roles usuario PT2

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#956]
Se requiere continuar con el dedesarrollo de la [HU2 - 2](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/resanchezc_udistrital_edu_co/EYc_4k5TayBEgwWaq2wQt9UBOxFJ-y2a-Z_lj5bsjlDkUQ?wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1706125306937&web=1), relacionada con la edición de roles de usuarios.

Descripción: **Como** rol planeación **quiero** Quiero realizar la Asignación de Roles  Específicos a un usuario **para** para poder actualizar los roles de un usuario registrado en el sistema.

**Especificaciones técnicas**

- Actualmente el desarrollo del aplicativo se encuentra estabilizado en ambiente develop (Cliente, mid y crud).
- Se debe partir de la issue #873 y #874 .

**Sub Tareas**

- [x] Se debe desarrollar un endpoint en [autenticacion_mid](https://github.com/udistrital/autenticacion_mid/tree/develop) que permita quitar roles a un usuario con base en los servicios proveidos por el arquitecto (COLOCAR SERVICIOS).
- [x] Relacionar las acciones visuales de "vinculación" y "desvinculación" de roles con los respectivos endpoints (add, delete).

**Criterios de aceptación**

- [x] Dado que Un administrador realiza la búsqueda de usuarios por medio del campo de búsqueda, al encontrar el usuario especifico, cuando elige la opción "edición" gestiona los roles del usuario y le da clic en "Vincular" o "desvincular", entonces se atualiza la tabla de usuarios y en la columna roles se refleja el cambio. 

**Requerimientos**

- [x] Servicio de edición usuarios WSO2.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by ccmendezt** [comment]
## Evidencias - Avance Edición de roles usuario PT2
### 05/04/2024 - 15:56

- Se modificó el endpoint **addRol** debido a que los _servicios_ proporcionados por el _arquitecto_ tenían algunos cambios en la estructura haciendo que las peticiones se realizaran levemente distintas o incluso a otros endpoints, también de modificó el formato de respuesta utilizando el formato usado actualmente en la OATI. La adición de roles funciona perfectamente desde el _Swagger_ de la api **autenticacion_mid**:
![adicionRol](https://github.com/udistrital/planeacion_cliente/assets/82072560/b19b65b9-878a-47c9-884b-55d45d5e9a31)

- Se creó el servicio de **eliminación (desvinculación)** de _rol_ y está completamente funcional desde _Swagger_:
![eliminacionRol](https://github.com/udistrital/planeacion_cliente/assets/82072560/3bd9181e-47fb-4364-b95b-de082ec53525)

- Se crearon estructuras y se organizaron para manejar adecuadamente los campos de las respuestas realizadas a los endpoints proporcionados por el arquitecto:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/cae6b9cf-6744-4a56-aa1d-d12569a71e4d)
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/8650aa7d-bed1-4217-9cc0-9c0b49efdc10)
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/34006a01-5092-4f0b-a20c-a465327e45c7)
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/81f269c2-e050-4faf-a681-18b54e30ca24)
La gran mayoría de dichas estructuras de utilizan en los endpoints de adición y eliminación de roles.

## Notas importantes:
  **i.** Se debe refactorizar la api **auntenticacion_mid** ya que no cuenta con las prácticas actualizadas utilizadas por la OATI. Toda la lógica de las peticiones para adicion/eliminacion de roles se maneja en el **modelo** _Token.go_ llamado desde el controlador _Token.go_, pero debería hacerse desde un _helper_, en lugar del _modelo_. Así mismo para los otros endpoints **emailToken** y **userRol**.

**Comment by ccmendezt** [comment]
## Evidencias - Avance Edición de roles usuario PT2
### 08/07/2024 - 15:30

- Se realizó la implementación de _vinculación_ en **planeacion_cliente**:
![vincularRol](https://github.com/udistrital/planeacion_cliente/assets/82072560/4237bc91-590c-4b70-91ab-40bb07ff9c9e)


- Se realizó la implementación de _desvinculación_ en **planeacion_cliente**:
![desvincularRol](https://github.com/udistrital/planeacion_cliente/assets/82072560/92d61801-61f3-4295-a053-fe0f8fc7652a)


## Pull Request Asociados a Issue:

- **planeacion_cliente:** https://github.com/udistrital/planeacion_cliente/pull/979
- **autenticacion_mid**: Falta asignarme permisos para colaborar en el repositorio. 
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/ae390880-13cd-4971-ade1-18acc18846be)
