### ISSUE TITLE
2-7 Creación de microfrontend "pendientes_mf" PT2

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#957]
Se requiere terminar el microfrontend **planeacion_pendientes_mf** con base en el cliente **PLANEACION_CLIENTE**, de forma tal que los componentes asociados queden desacoplados del Cliente principal.

**Especificaciones técnicas**

1. El repositorio para **planeacion_pendientes_mf** es: 
**(https://github.com/udistrital/planeacion_pendientes_mf)**
3. Se requiere crear el cliente a partir de single-spa.
4. El API debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevos clientes definidos por la OATI.
5. Se debe adicionar el consumo de "planeacion_pendientes_mf" al microfrontend **planeacion_root_mf** desarrollado en #925 .
7. Se debe optimizar el código migrado, eliminando malas practicas de desarrollo.
8. Tomar como referencia el diagrama de componentes elaborado en #910 .

**Material de apoyo**

- Sesión de capacitación Microfrontends: https://udistritaleduco-my.sharepoint.com/:v:/g/personal/ndmunozc_udistrital_edu_co/EQ18oP3BMztCuGj4fRbI540BKawZvWw7muAnTX3jDINSAQ?referrer=Teams.TEAMS-WEB&referrerScenario=MeetingChicletGetLink.view.view 
- Sesión 2: [Revisión de MF Planeación-20240311_111601-Grabación de la reunión.mp4](https://udistritaleduco-my.sharepoint.com/personal/cerochac_udistrital_edu_co/Documents/Grabaciones/Revisi%C3%B3n%20de%20MF%20Planeaci%C3%B3n-20240311_111601-Grabaci%C3%B3n%20de%20la%20reuni%C3%B3n.mp4)
- Sesión 3: [https://udistritaleduco-my.sharepoint.com/:v:/g/personal/cerochac_udistrital_edu_co/ES41RgsHxCpKhdRlRiH-kgMB_jD0IfyQHvJkSjHNnb3ZYw?referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/cerochac_udistrital_edu_co/ES41RgsHxCpKhdRlRiH-kgMB_jD0IfyQHvJkSjHNnb3ZYw?referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view&isSPOFile=1)

**Sub Tareas**

- [x] Conexión con el cliente "planeacion_seguimiento_mf"
- [x] Cifrado de las coockies

**Criterios de aceptación**

- [x] El cliente se encuentra desarrollado.
- [x] Se interopera con a planeacion_seguimiento_mf y se evidencia su integración.
- [x] Pruebas funcionales del componente.

**Requerimientos**

- [x] Completar Issue #910  .

**Dependencias**

- planeacion_cliente
- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by C0C045** [comment]
# PR's
En formulacion-mf: https://github.com/udistrital/planeacion_formulacion_mf/pull/3
En seguimiento-mf: https://github.com/udistrital/planeacion_seguimiento_mf/pull/2
En pendientes-mf: https://github.com/udistrital/planeacion_pendientes_mf/pull/2

**Comment by milo19980525** [comment]
Queda pendiente revisar tiempo de eliminación de cookie relacionada con seguimiento.  Buen trabajo

**Comment by C0C045** [comment]
Tiempo de eliminación de la cookie. **SOLUCIONADO**

**Comment by milo19980525** [comment]
Perfecto.
