### ISSUE TITLE
HU2-3 Ajuste en tabla de seguimiento y descarga de excel

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#959]
Se requiere desarrollar la [HU2 - 3](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/Ee7zP4NGPeFMk8cY03G0D2EBz2FVBAlETLO8xPq6XIW2SA?e=9pUcjt), relacionada con el registro historico de seguimientos realizados sobre los planes de acción.

Descripción: 

- **Como** jefe de unidad y asistente de unidad **quiero** acceder a un registro histórico de todas las aprobaciones de seguimientos **para** tener trazabilidad sobre los diferentes seguimientos realizados a los planes de acción.
- **Como** jefe de planeación y asistente de planeación **quiero**  acceder a un registro histórico de todas las aprobaciones de seguimientos por unidad **para** tener trazabilidad sobre los diferentes seguimientos realizados a los plan de acción.

**Especificaciones técnicas**

- Actualmente el desarrollo del aplicativo se encuentra estabilizado en ambiente develop (Cliente, mid y crud).
- El desarrollo del componente se debe realizar en el menú "Plan de acción" -> "Consulta plan de acción".

**Sub Tareas**

- [x] Se deben crear dos submenus en el menú "Consulta plan de acción": **"Formulación"** y **"Seguimiento"**.
- [x] Actualmente en  "Plan de acción" -> "Consulta plan de acción" existe una tabla con la consulta de todos los planes de acción (formulación y seguimiento). Esta tabla debe colocarse en ambos menús diferenciando la información de planes de seguimiento y de formulación.
- FORMULACIÓN
- [x] Se debe dejar la misma tabla actual solo con los planes de formulación.

- SEGUIMIENTO
- [x] Para los usuarios con rol "PLANEACION" se debe habilitar un filtro que permita escoger la unidad sobre la cual se quiera mostrar el histórico.
- [x] Las variables de la tabla y condiciones de alerta se encuentran en [variables HU 2-3](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/Ee7zP4NGPeFMk8cY03G0D2EBz2FVBAlETLO8xPq6XIW2SA?e=rWIUgC)
- [x] En la tabla cada uno de los seguimientos debe tener un botón de "lupa" que rediriga al seguimiento de cada plan en particular.
- [x] Se debe habilitar un botón de "Descargar Seguimientos", el cual deberá generar la acción de descargar un archivo formato excel lo mostrado en la tabla.

**Criterios de aceptación**

- [x] Dado que un usuario con rol "JEFE_UNIDAD_PLANEACION", "ASISTENTE_DEPENDENCIA" o "JEFE_DEPENDENCIA" se encentra en el sistema cuando el asistente de unidad , da clic en el menú trazabilidad de seguimientos realizados, se genera una vista con  una tabla que describe los seguimientos realizados. En donde se describe cada uno de los seguimientos realizados al plan de acción. 
- [x] Dado que el asistente de unidad accede al sistema, en el menú trazabilidad de seguimientos realizados y este no cuenta con seguimientos realizados  cuando el asistente de unidad , da clic en el menú trazabilidad de seguimientos realizados, se visualiza un mensaje en una ventana emergente que indica que no se tienen seguimientos realizados y un botón aceptar para continuar en el menú principal del sistema
- [x] Dado que el asistente de unidad accede al sistema, en el menú trazabilidad de seguimientos realizados. y desea descargar los seguimientos realizados, listados en la tabla cuando el asistente de unidad Accede al menú trazabilidad de seguimientos realizados. realiza clic en el botón "Descargar Seguimientos", se genere y descargue un archivo Excel el cual contenga toda la información listada en la tabla de seguimientos realizados.
- [x] Dado que el asistente de unidad Accede  al sistema, en el menú  de trazabilidad de seguimientos realizados, donde observa una tabla con los seguimientos realizados y desea revisar un seguimiento en particular, cuando el asistente de unidad accede al menú seguimientos realizados. En la tabla de seguimientos realizados elige un seguimiento particular y hace clic en el ícono de lupa, el sistema se redireccione a la ventana del seguimiento del plan de acción en particular escogido y pueda observar en la ventana del seguimeinto escogid.

**Requerimientos**

- [x] Servicio de edición usuarios WSO2.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by C0C045** [comment]
# Tabla de seguimientos realizados y Descarga

1. Existe una tabla de procesos realizados tanto para 'Formulación' como para 'Seguimiento'.
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/38e16f45-e49a-41b3-bcff-f31ae4d5c346)
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/d51940b9-095b-48a6-9a4b-1e718d02d2a0)

2. Se aplicó el filtro por unidad en la tabla de 'Seguimiento' para usuarios con rol 'PLANEACION'.
![filtro](https://github.com/udistrital/planeacion_cliente/assets/55455142/d318477c-df64-4d6e-bda7-26c876e6184c)

3. Se implementó otra alternativa para visualizar los trimestres de un plan de acción en especifico, ya que de esta forma se contribuye a una mejor estética y optimización. Por ende, se tiene un nuevo componente flotante que nos permite visualizar un promedio de las brechas por trimestre (si existe), el estado del trimestre y la acción (lupa) para ir al detalle específico de cada trimestre.
![trimestre](https://github.com/udistrital/planeacion_cliente/assets/55455142/a2130a55-3246-4ede-9701-fd5eb26680a4)

4. Se agregó el 'popup' encargado de avisarnos que la unidad o dependencia seleccionada no tiene planes en fase de seguimiento.
![noUnidad](https://github.com/udistrital/planeacion_cliente/assets/55455142/0237e49a-c8c2-412b-9ba3-a2ac74e640f5)

5. Se agregó un nuevo 'popup' que nos indica que no es posible ver los trimestres de un plan de acción; debido a que su vigencia no tiene unos trimestres definidos aún.
![noVigencia](https://github.com/udistrital/planeacion_cliente/assets/55455142/d01d2858-e742-444e-b769-67c859c7d8e8)

6. Se implementó el botón de 'Descargar Seguimientos'; el cuál nos permite descargar un archivo .xlsx que contiene toda la 'Tabla de seguimientos realizados' con detalle de cada trimestre.
![descargar](https://github.com/udistrital/planeacion_cliente/assets/55455142/d73ab896-1198-468a-92bc-20b251969aa3)


## NOTA IMPORTANTE
El desarrollo de la _'Tabla de seguimientos y Descarga'_ se vio afectado con validaciones de más, debido a que en el aplicativo existen varias vigencias que no tienen periodos asignados, además, de planes antiguos y dañados que no cumplen con la funcionalidad actual del sistema, por ende, para evitar errores se hicieron varias validaciones que en un aplicativo ideal se hubieran podido evitar para tener un código más óptimo.

**Planes Dañados:**
- 'Plan de acción 2023 Prod Seguimiento' en VICERRECTORIA ACADEMICA
- Todos los planes de FACULTAD DE CIENCIAS Y EDUCACION
- Todos los planes de FACULTAD DE CIENCIAS MATEMATICAS Y NATURALES

**Ejemplos:**
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/0b031113-9bcc-4fda-b92b-8c7dbead1ab4)
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/9b72e776-1676-43ce-a4d2-32ba07866eb3)

**Comment by C0C045** [comment]
# PR
rama cliente: https://github.com/udistrital/planeacion_cliente/pull/976
