### ISSUE TITLE
1-1 Refactorización API planeacion_arbol_mid

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#960]
Se requiere refactorizar el API **PLANEACION_ARBOL_MID** con base en el API **PLANEACION_MID**, de forma tal que los controladores asociados queden desacoplados del API principal.

**Especificaciones técnicas**

1. El repositorio para **PLANEACION_ARBOL_MID** es: https://github.com/udistrital/planeacion_arbol_mid
2. Se requiere migrar los **nuevos controladores** (en dado caso de darse el caso) asociado a Arbol, del API **PLANEACION_MID** al API **PLANEACION_ARBOL_MID**.
3. El API debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevas APIs GO definidos por la OATI.
4. De igual manera se deben implementar los respectivos controles de errores con base en lo evidenciado en:  [Tercero-mid](https://github.com/udistrital/sga_tercero_mid).
5. Se deben renombrar los endpoints con base en las directrices establecidas en los [lineamientos](https://github.com/udistrital/lineamientos_oas) y en las [buenas prácticas de desarrollo API REST](https://vicente-aguilera-perez.medium.com/las-10-mejores-pr%C3%A1cticas-para-nombrar-api-rest-endpoints-48b8bcbd1397) y con base en: #948 
6. Los métodos de utilidades que son globales a todas las APIs deben ser migrados a la librería **utils_oas**.
7. Se debe optimizar el código migrado, eliminando malas practicas de desarrollo.
8. Actualizar readme.

**Sub Tareas**

- [x] Refactorización de API **PLANEACION_ARBOL_MID**
- [x] Migración de nuevos endpoints.
- [x] Manejo correcto de errores.
- [x] Nombrameniento adecuado.

**Criterios de aceptación**

- [x] El API se encuentra refactorizada y con manejo de errores.
- [x] Los nuevos endpoints son migrados.

**Requerimientos**

- [x] Completar Issue #803 y #822 .

**Dependencias**

- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
- Router
- Controllers (punto de entrada - HTTP)
- Services (Son llamados por Controllers - lógica pesada)
- Helpers (Son utilizados services - transversal o funcionalidad en general)

Revisión de requestresponse de utils_oas
Revisión de handlePanic de utils_oas

**Comment by norbeydanilo** [comment]
Ejemplo de uso en SGA:

- [Tercero-mid](https://github.com/udistrital/sga_tercero_mid)

**Comment by norbeydanilo** [comment]
Ajuste de nombre de endpoints en controllers según REST:

- [Issue](https://github.com/udistrital/planeacion_cliente/issues/948)

**Comment by ccmendezt** [comment]
## Evidencias - Avance Refactorización API planeacion_arbol_mid
### 10/04/2024 - 12:30 pm

- Se ajustó el nombre de endpoints en controllers según ![REST](https://github.com/udistrital/planeacion_cliente/issues/948):
    - Nombres propuestos para endpoints:
    - 

- Se agregó la funcionalidad al botón **_Seleccionar todos_** que permite seleccionar todos los planes/proyectos para asignarlos al proceso y la vigencia seleccionada:

- Se ajustó el ancho de las columnas en la tabla _**listar-plan**_ para mejorar su visualización.
    **Antes:**
![AnchoCol_Antes](https://github.com/udistrital/planeacion_cliente/assets/82072560/d13725b5-1feb-4404-889b-1dc0cc502442)

   **Después:**
![AnchoCol_Despues](https://github.com/udistrital/planeacion_cliente/assets/82072560/99dd6cd0-4161-4bbc-b13e-4b5fa07b4bfd)

## Notas importantes:
  **i.** Se están evaluando las validaciones que se deben hacer al momento de elegir o no unidades y/o planes/proyectos.
  **ii.** Se está revisando cómo realizar la petición al endpoint para almacenar los datos de las unidades y/o proyectos de interés asociados a una vigencia y proceso establecido.
  **iii.** Falta ajustar algunos aspectos estéticos de la tabla de planes/proyectos.

**Comment by ccmendezt** [comment]
## Evidencias - Avance Refactorización API planeacion_arbol_mid
### 10/04/2024 - 17:33

- Se ajustó el nombre de endpoints en controllers según [REST](https://github.com/udistrital/planeacion_cliente/issues/948):
    - Nombres propuestos para endpoints:
    ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/46a14582-9177-4712-a7bc-8ace9b9ff90d)

    - Nombres de endpoints **antes**:
    ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/5acd1fdf-e1f8-4eb5-9b73-c9e1aac83009)

    - Nombres de endpoints **después**:
    ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/f27b609a-af62-41ff-a3db-21d5e7a0776f)

- Se implementó el **handlePanic** para el manejo de errores y **requestresponse** para el manejo de las respuestas en cada uno de los recursos del controlador como se especificó y se migró toda la lógica de negocio a los servicios:
    - _ConsultarArbol_:
    ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/4b483b67-6ffc-403d-a61c-2d5156cb760c)
    
    - _DesactivarPlan_:
    ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/d8101518-7d81-40bc-b546-47f776d89d29)

    - _DesactivarNodo_:
    ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/f7815789-3e49-4e90-9584-30617fbba9f9)

    - _ActivarPlan_:
    ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/79a400d7-99d7-457d-9e94-bc27e676a992)

    - _ActivarNodo_:
    ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/d8ff6cfd-4a89-43b0-8608-4d6ab87d4efa)

- Se creó el _servicio_ **arbol_service.go** dentro de la carpeta _services_ para que sean llamados desde los controllers migrando toda la lógica que había en el _controlador_ y _helper_.

- En el _helper_ **arbol_helper.go** no se tiene código, el archivo está vacío.

- Las funciones manejan dos parámetros de salida (data, error), para el retorno de la respuesta y el error (en caso de haber) respectivamente.

- Se actualizó el **README.md**

## Pull Request Asociados a Issue

- **planeacion_arbol_mid:** https://github.com/udistrital/planeacion_arbol_mid/pull/4

## Notas importantes:
  **i.** El build de la API MID falló debido a que ya existe el go.mod, añadir el go.mod y go.sum al .gitignore pero se deben eliminar los archivos del repo.
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/6bd5e819-07a0-462f-be19-85e4d05724e0)

**Comment by ccmendezt** [comment]
## Evidencias - Avance Refactorización API planeacion_arbol_mid
### 14/04/2024 - 20:40

- Los smoke_test fueron realizados con un resultado exitoso:

#### ArbolController

- **TestConsultarArbol:** <span style="color: #4cc61e;"><b>Test OK</b></span>
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/c6879aa0-b4df-443d-9d29-2291ab677bdd)

- **TestDesactivarPlan:** <span style="color: #4cc61e;"><b>Test OK</b></span>
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/ac9c6df0-7698-4b86-8013-8b17ef30633b)

- **TestDesactivarNodo:** <span style="color: #4cc61e;"><b>Test OK</b></span>
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/5b7621ee-e320-4b70-91a4-4679598f43a2)

- **TestActivarPlan:** <span style="color: #4cc61e;"><b>Test OK</b></span>
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/e45f7fc8-9039-4284-aacb-dd8f2ce676e9)

- **TestActivarNodo:** <span style="color: #4cc61e;"><b>Test OK</b></span>
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/b911eda4-1853-478c-bad1-a581cb0ec2c1)

- Se modificó el **README.md** añadiendo la estructura que maneja actualmente la OATI y también las imágenes de las pruebas unitarias realizadas.

**Comment by ccmendezt** [comment]
## Evidencias - Avance Refactorización API planeacion_arbol_mid
### 16/04/2024 - 5:30 pm

- Se revisó el comportamiento de los endpoints en ambiente de pruebas usando la siguiente dirección: http://pruebasapi.intranetoas.udistrital.edu.co:8550/v1
- **Todos los cinco endpoints funcionaron correctamente tanto para los casos de prueba como para los casos de error** (Solo se mostrará el resultado de _Activar/Desactivar plan_, pero se afirma nuevamente que todos los endpoints funcionan correctamente).

#### ActivarPlan
- **Resultado correcto:** 
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/7efb1ef6-17d0-4c38-8c31-c67510e11d5c)

- **Resultado fallido:**
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/ced0ddc1-9229-40ff-9da5-e384f8012667)

#### DesactivarPlan
- **Resultado correcto:**
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/7ee75bb3-e1b4-4862-80b6-ef82cb7d278c)

- **Resultado fallido:**
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/5a0ee6ee-7064-40f2-bfce-5c311eb1da9c)
