### ISSUE TITLE
1-3 Refactorización API planeacion_formulacion_mid PT1

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#961]
Se requiere refactorizar el API **PLANEACION_FORMULACION_MID** con base en el API **PLANEACION_MID**, de forma tal que los controladores asociados queden desacoplados del API principal.

**Especificaciones técnicas**

1. El repositorio para **PLANEACION_FORMULACION_MID** es: https://github.com/udistrital/planeacion_formulacion_e_inversion_mid/tree/feature/planeacion_formulacion
2. Se requiere migrar los **nuevos controladores** (en dado caso de darse el caso) asociado a Formulación, del API **PLANEACION_MID** al API **PLANEACION_FORMULACION_MID**.
3. El API debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevas APIs GO definidos por la OATI.
4. De igual manera se deben implementar los respectivos controles de errores con base en lo evidenciado en:  [Tercero-mid](https://github.com/udistrital/sga_tercero_mid).
5. Se deben renombrar los endpoints con base en las directrices establecidas en los [lineamientos](https://github.com/udistrital/lineamientos_oas) y en las [buenas prácticas de desarrollo API REST](https://vicente-aguilera-perez.medium.com/las-10-mejores-pr%C3%A1cticas-para-nombrar-api-rest-endpoints-48b8bcbd1397) y con base en: #948 
6. Los métodos de utilidades que son globales a todas las APIs deben ser migrados a la librería **utils_oas**.
7. Se debe optimizar el código migrado, eliminando malas practicas de desarrollo.
8. Actualizar readme.

**Sub Tareas**

- [x] Refactorización de API **PLANEACION_FORMULACION_MID**
- [x] Migración de nuevos endpoints.
- [x] Manejo correcto de errores.
- [x] Nombrameniento adecuado.

**Criterios de aceptación**

- [x] El API se encuentra refactorizada y con manejo de errores.
- [x] Los nuevos endpoints son migrados.

**Requerimientos**

- [x] Completar Issue #803 y #880 .

**Dependencias**

- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by C0C045** [comment]
# Avance en refactorización del API 'planeacion_formulacion_mid'

1. Se ajustaron cada una de las rutas de los controladores según lo planteado en 'https://github.com/udistrital/planeacion_cliente/issues/948#issuecomment-2028249802'
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/2789b7aa-252a-4ad8-8f18-a074801e1eaf)

2. Se modificó la estructura de los controladores según lo evidenciado en [Tercero-mid](https://github.com/udistrital/sga_tercero_mid/blob/develop/controllers/tercero_controller.go); dónde, podemos observar el uso de 'HandlePanic' y la separación de la lógica en 'services/formulacion.go'
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/3c180e5d-add5-423c-9d81-97fee0dca38b)

3. Se organizaron los 'helpers' para obtener un mejor orden y certeza a la hora de usarlos.
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/280d24b9-bc40-4a41-86c4-8d0e76d22a2d)

4. Se implementaron cada una de las pruebas unitarias tipo Smoke posibles para los controladores de 'formulacion.go', ya que algunas consultas requieren un objeto complejo que se construye a través de diferentes consultas anteriores.
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/efb5f3fa-3ba2-4af8-9b8c-602b9ebe36a4)
**RESULTADOS:**
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/535ffe7f-2449-47bc-80e0-d8fdc02c8ed9)
