### ISSUE TITLE
1-2 Refactorización API planeacion_formato_mid

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#962]
Se requiere refactorizar el API **PLANEACION_FORMATO_MID** con base en el API **PLANEACION_MID**, de forma tal que los controladores asociados queden desacoplados del API principal.

**Especificaciones técnicas**

1. El repositorio para **PLANEACION_FORMATO_MID** es: https://github.com/udistrital/planeacion_formato_mid
2. Se requiere migrar los **nuevos controladores** (en dado caso de darse el caso) asociado a Formato, del API **PLANEACION_MID** al API **PLANEACION_FORMATO_MID**.
3. El API debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevas APIs GO definidos por la OATI.
4. De igual manera se deben implementar los respectivos controles de errores con base en lo evidenciado en:  [Tercero-mid](https://github.com/udistrital/sga_tercero_mid).
5. Se deben renombrar los endpoints con base en las directrices establecidas en los [lineamientos](https://github.com/udistrital/lineamientos_oas) y en las [buenas prácticas de desarrollo API REST](https://vicente-aguilera-perez.medium.com/las-10-mejores-pr%C3%A1cticas-para-nombrar-api-rest-endpoints-48b8bcbd1397) y con base en: #948 
6. Los métodos de utilidades que son globales a todas las APIs deben ser migrados a la librería **utils_oas**.
7. Se debe optimizar el código migrado, eliminando malas practicas de desarrollo.
8. Actualizar readme.

**Sub Tareas**

- [x] Refactorización de API **PLANEACION_FORMATO_MID**
- [x] Migración de nuevos endpoints.
- [x] Manejo correcto de errores.
- [x] Nombrameniento adecuado.

**Criterios de aceptación**

- [x] El API se encuentra refactorizada y con manejo de errores.
- [x] Los nuevos endpoints son migrados.

**Requerimientos**

- [x] Completar Issue #803 y #844 .

**Dependencias**

- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
El Endpoint modificado responde de manera exitosa para un caso de éxito:

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/997d4348-c6bf-4c26-a068-226918af3d0d)

Responde también cuando se busca un dato el cual no existe:

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/c188af71-99e3-4970-a533-3be44acdc8da)

Y responde cuando un Endpoint falla en la consulta de los datos:

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/d162c970-a25d-42b6-a044-7e160b4140fe)

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/8512fca8-27ab-46e7-995c-2eaede0386ec)

**Comment by Mechaz123** [comment]
Buenas tardes, se acaba de solicitar el Pull hacia develop:

https://github.com/udistrital/planeacion_formato_mid/pull/7

**Comment by Mechaz123** [comment]
> Ya quedó desplegado todo en pruebas, por favor revisar las respuestas del endpoint y adjuntar evidencia en este issue

Se adjunta evidencia del funcionamiento del endpoint en ambiente de pruebas:

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/066344cf-e81a-494e-93a5-70c2ec1c7780)

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/10cf97f5-b22c-4c8c-8a09-d66a24aa2553)
