### ISSUE TITLE
Pruebas funcionales SISGPLAN en ambiente de pruebas - Sprints 4, 5, 6, 7 y 8.

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#963]
Tomando como referencia lo realizado en #903 , se requieren llevar a cabo pruebas funcionales en ambiente de pruebas, asociadas a los desarrollos realizados en SISGPLAN en los Sprints 4, 5, 6, 7 y 8.

**Especificaciones técnicas**

1. Las pruebas funcionales deben cubrir todos los desarrollos cargados en develop en los sprints 4, 5, 6, 7 y 8.
2. Se deben tomar como guía las pruebas realizadas por los desarrolladores en local en cada implementación.
3. El documento de pruebas debe especificar el estado en el que se encuentra el desarrollo, si se valida o no su funcionamiento y las observaciones correspondientes.
4. Los desarrollos a probar se encuentran en:
- [Sprint 4](https://github.com/udistrital/planeacion_cliente/milestone/82)
- [Sprint 5](https://github.com/udistrital/planeacion_cliente/milestone/83)
- [Sprint 6](https://github.com/udistrital/planeacion_cliente/milestone/84)
- [Sprint 7](https://github.com/udistrital/planeacion_cliente/milestone/85)
- [Sprint 8](https://github.com/udistrital/planeacion_cliente/milestone/86)
5. Se deben probar solamente los desarrollos, las tareas de análisis o documentación no se tienen en cuenta.
6. Se trata de hacer un compendio de todas las pruebas realizadas hasta la fecha en un documento y validar su funcionamiento.
7. Adicional al documento que se debe presentar con las pruebas, se requiere realizar una anotación y seguimiento en forma de comentarios en este issue, de tal forma que se evidencien las pruebas realizadas en cada desarrollo y si aprueban o no. Tomar como guía: https://github.com/udistrital/sga_documentacion/issues/42

**Sub Tareas**

- [x] Desarrollo de pruebas funcionales en ambiente de pruebas - SISGPLAN.
- [x] Seguimiento de pruebas funcionales en el issue.

**Criterios de aceptación**

- [x] Se presenta un documento con pruebas de los desarrollos implementados en el Sprint 4, 5, 6, 7 y 8, asociados a SISGPLAN.
- [x] Se presenta el seguimiento de las pruebas realizadas en el issue, asociadas a cada desarrollo.

**Requerimientos**

- No presenta.

**Dependencias**

- planeacion_cliente.
- planeacion_mid.
- planes_crud.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Pruebas locales (funcionales).
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
Carpeta para pruebas funcionales:

https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EvgM4KowvOBKjdXD3aFLGV0BGcATolW8LorkydQUQnYMuA?e=MZjaiw

**Comment by Oscarjaimes1710** [comment]
https://github.com/udistrital/planeacion_cliente/milestone/82
#904  Ok Revisada en perfecto funcionamiento.
#850 Ok Revisado: 2 detalles algunos tiempos de carga de la consulta y mal re direccionamiento de el botón consulta de planes de acción.

**Comment by a52290451** [comment]
#904 .

**Comment by Oscarjaimes1710** [comment]
#953

**Comment by a52290451** [comment]
@Oscarjaimes1710 Por favor subir evidencia de la revisión y realización de pruebas por sprint.
