### ISSUE TITLE
HU 1-2 - Filtrado en la interfaz de avance por período de tiempo - trimestral.

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#964]
Se requiere implementar una vista en **planeacion_cliente**, módulo de planes de acción, componente de **evaluación**, en el que se muestre el avance general de cada unidad asociada a un plan de acción, vigencia y trimestre en particular, a modo de grafico y tabla resumen.

Se debe tomar como referencia la [Historia de Usuario](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EcL1PrBXSR1AiQ7-2BIsxbsBSatRep0d56VRcH8D3CAOWA?e=5ppXvV) relacionada.

**Especificaciones técnicas**

1. Se debe agregar la opción "Todos los Trimestres" en el filtro "Trimestre". Esta opción debe estar habilitada solo cuando se selecciona  la opción "Todas las Unidades".
2. Si se selecciona la opción "Todas las Unidades", se debe mantener habilitado el filtro "Trimestre" y habilitar el botón "Consultar Evaluación". Adicionalmente, se debe tener seleccionada por defecto la opción "Todos los Trimestres".
3. Si se oprime el botón "Consultar Evaluación", cumpliéndose la condición de tener seleccionado en el filtro, "Todas las Unidades" y "Todos los Trimestres", se debe desplegar la vista implementada en #926 .
4. Si se oprime el botón "Consultar Evaluación", cumpliéndose la condición de tener seleccionado en el filtro, "Todas las Unidades" y un trimestre en particular, se deberán generar los siguientes elementos en la interfaz en una nueva vista:
- Grafico de barras en el que se muestren todas las unidades que tengan el plan seleccionado en fase de seguimiento, con su respectivo avance asociado al trimestre.
- Tabla resumen del plan de acción en el que se apilen todas las unidades por filas. Se debe manejar la misma estructura he información que se registra en la tabla resumen por unidad asociada al trimestre.
5. Aspectos a tener en cuenta:
- La tabla resumen debe poder desplegar y guardar la información del plan, por cada unidad registrada. Es decir que en principio, cada fila muestra la unidad y el avance de esa unidad con respecto al plan y al trimestre. Oprimiendo encima de una unidad en particular, se despliega toda la información del plan asociada a esa unidad.
- La grafica debe mostrar claramente la información asociada a cada unidad.

**Sub Tareas**

- [x] Adecuación y restricción de filtros y ajuste de opciones por filtro.
- [x] Creación de mockup para grafico del nivel de avance de todas las unidades por plan y trimestre.
- [x] Creación de mockup para tabla resumen del plan de acción en el que se incluyen todas las unidades.
- [x] Creación de grafico del nivel de avance de todas las unidades.
- [x] Creación de tabla resumen del plan de acción en el que se incluyen todas las unidades.

**Criterios de aceptación**

- [x] En el componente de evaluación del modulo de planes de acción, puedo seleccionar la información de todas las unidades asociadas a un plan de acción, vigencia y trimestre en particular.
- [x] Puedo ver en un grafico intuitivo, la información del nivel de avance general de cada unidad con respecto al plan de acción y trimestre seleccionados.
- [x] Puedo ver la información especifica de cada unidad, por trimestre y a nivel general, del plan de acción asociado, en una tabla resumen.

**Requerimientos**

- No presenta.

**Dependencias**

- planeacion_cliente.
- planeacion_mid.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by felimarod** [comment]
![image](https://github.com/udistrital/planeacion_cliente/assets/85894335/c58b63b5-11af-4884-8820-db824bbfc533)
Al seleccionar la opción de Trimestre especifico solo se muestra la gráfica con los avances de las diferentes unidades  en ese periodo seleccionado

**Comment by a52290451** [comment]
Se validan y aprueban pruebas funcionales realizadas.
