### ISSUE TITLE
1-4 Refactorización API autenticacion_mid

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#969]
Se requiere refactorizar el API **AUTENTICACION_MID**, de forma tal que su estructura y lógica queden acorde al modelo planteado en tercero_mid.

**Especificaciones técnicas**

1. El repositorio para **AUTENTICACION_MID** es: https://github.com/udistrital/planeacion_formulacion_e_inversion_mid/tree/feature/planeacion_formulacion
2. El API debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevas APIs GO definidos por la OATI.
3. De igual manera se deben implementar los respectivos controles de errores con base en lo evidenciado en:  [Tercero-mid](https://github.com/udistrital/sga_tercero_mid).
4. Se deben renombrar los endpoints con base en las directrices establecidas en los [lineamientos](https://github.com/udistrital/lineamientos_oas) y en las [buenas prácticas de desarrollo API REST](https://vicente-aguilera-perez.medium.com/las-10-mejores-pr%C3%A1cticas-para-nombrar-api-rest-endpoints-48b8bcbd1397)
5. Los métodos de utilidades que son globales a todas las APIs deben ser migrados a la librería **utils_oas**.
6. Se debe optimizar el código migrado, eliminando malas practicas de desarrollo.

**Sub Tareas**

- [x] Refactorización de API **AUTENTICACION_MID**
- [x] Manejo correcto de errores.
- [x] Nombrameniento adecuado.

**Criterios de aceptación**

- [x] El API se encuentra refactorizada y con manejo de errores.

**Requerimientos**

- [x] Completar Issue #956  .

**Dependencias**

- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by ccmendezt** [comment]
## Evidencias - Avance Refactorización API planeacion_arbol_mid
### 12/04/2024 - 17:18

- Se ajustó el nombre de endpoints en controllers según indicaciones dadas por el líder técnico:
    - Nombres de endpoints **después**:
    ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/8a6e4921-8697-443c-959c-fad4f2a0df96)

- Se implementó el **handlePanic** para el manejo de errores y **requestresponse** para el manejo de las respuestas en cada uno de los recursos del controlador como se especificó y se migró toda la lógica de negocio a los servicios:

**TokenController:**

- _GetEmail_:
    ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/6dd4b69e-c2d3-4b22-b4d5-fa40dea844aa)
    
- _GetRol_:
    ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/a5b84cc5-35fa-4434-b2f6-5697daf71216)

**RolController:**

- _AddRol_:
    ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/0b345f8b-accd-4863-9772-1568aca66f53)
    
- _RemoveRol_:
    ![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/bda67b8c-6996-446a-be9a-f8cf4777761a)


- Se crearon los _servicios_ **token_service.go**  y **rol_service.go** dentro de la carpeta _services_ para que sean llamados desde los controllers migrando toda la lógica que había en modelo **token_model.go** hacia sus respectivos servicios y helpers.

- En los _helpers_ **token_helper.go** y **rol_helper.go** se crearon funciones que se llaman en los servicios haciendo mucho más legible el código en los servicios.

- Las funciones manejan dos parámetros de salida (data, error), para el retorno de la respuesta y el error (en caso de haber) respectivamente.

- Se actualizó el **README.md**

## Notas importantes:
  **i.** Falta realizar los _smoke_test_ de los controladores para adjuntarlos en el readme.

**Comment by ccmendezt** [comment]
## Evidencias - Avance Refactorización API autenticacion_mid
### 14/04/2024 - 20:40

- Los smoke_test fueron realizados con un resultado exitoso:
#### TokenController

- **TestEmailToken:** <span style="color: #4cc61e;"><b>Test OK</b></span>
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/8b33568f-fccb-4fef-aa5f-a5dc299f7bfc)

- **TestUserRol:** <span style="color: #4cc61e;"><b>Test OK</b></span>
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/02b420e0-d023-478e-809a-14e38f643465)

#### RolController

- **TestAddRol:** <span style="color: #4cc61e;"><b>Test OK</b></span>
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/ec6e19fd-67ee-4fcd-921f-b7dcbd0b975e)

- **TestRemoveRol:** <span style="color: #4cc61e;"><b>Test OK</b></span>
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/465d23d9-e6ac-444b-9139-1a457bc60d1f)

- Se modificó el **README.md** añadiendo la estructura que maneja actualmente la OATI y también las imágenes de las pruebas unitarias realizadas.
- Se agregó una nueva variable de entorno **AUTENTICACION_MID_HTTP_PORT** para especificar el puerto de operación de la API MID.

## Notas importantes:
  **i.** Todos los cambios mencionados en esta issue están en el siguiente **Pull Request**: https://github.com/udistrital/autenticacion_mid/pull/90

**Comment by ccmendezt** [comment]
## Evidencias - Avance Refactorización API autenticacion_mid
### 16/04/2024 - 09:00

#### Endpoint - EmailToken
- Respuesta **correcta** usando _WSO2_:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/31b10b80-3c3a-42d5-a0e1-d5e16cca2c07)

- Respuesta **correcta** usando _API Refactorizada_:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/98c8a372-fbb2-4113-b640-9887267a3a1a)

- Respuesta **incorrecta** usando _WSO2_:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/90d5c0f3-e484-45fe-a3a6-adf7172783da)

- Respuesta **incorrecta** usando _API Refactorizada_:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/af16d1df-8e46-46a4-bae4-8779a3aafc63)

#### Endpoint - UserRol
- Respuesta **correcta** usando _WSO2_:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/4153330f-cd2c-4322-8d4c-9f9cde6f6660)

- Respuesta **correcta** usando _API Refactorizada_:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/4ae24b4e-c821-4872-97d7-be4a42b8c93e)

- Respuesta **incorrecta** usando _WSO2_:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/929c9b79-5c2d-4784-ad38-e615d5a7cf5f)

- Respuesta **incorrecta** usando _API Refactorizada_:
![image](https://github.com/udistrital/planeacion_cliente/assets/82072560/2214da58-f765-4acf-80c6-b1468d809d1a)

Como se puede apreciar en las imágenes, las respuestas proporcionadas tanto para respuestas correctas como fallidas están exactamente igual, no se cambió nada respecto a la respuesta de la API que se encuentra en producción. El cambio realizado fue para respuestas fallidas ya que para respuestas correctas ya se manejaba la petición con el mismo formato.
