### ISSUE TITLE
1-0 Investigación sobre alternativas de automatización para el desarrollo de APIs y Clientes

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#971]
Se requiere investigar herramientas y tendencias de desarrollo de software orientado a la automatización de generación de código para clientes y APIs.

**Especificaciones técnicas**

1. Actualmente la OATI desarrolla clientes y APIs con base en sus [lineamientos](https://github.com/udistrital/lineamientos_oas).
2. El desarrollo mediante el cual se efectuan nuevas funcionalidades se realiza bajo un marco de trabajo SCRUM orientando desarrollo bajo demanda.
3. Se desea transformar de manera parcial el desarrollo por demanda realizado desde cero por automatizaciones de desarrollo de código por plantillas (templates).

**Sub Tareas**

- [x] Investigar el estado del arte acerca de la automatización de código para la creación de módulos a nivel de back.
- [x] Investigar el estado del arte acerca de la automatización de código para la creación de módulos a nivel de front.
- [x] Documentación de las opciones encontradas en el estado del arte.
- [x] Cuadro comparativo de las opciones encontradas.

**Criterios de aceptación**

- [x] Documento completo, estructurado, con buena presentación, desgolce de las herramientas encontradas y cuadro comparativo.

**Requerimientos**

- [X] X.

**Dependencias**

-[X] ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Documentación
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Tener en cuenta el MDA

**Comment by Mechaz123** [comment]
Se adjunta el link del documento trabajado, con las referencias y demás información:

https://udistritaleduco-my.sharepoint.com/:w:/g/personal/daarojasg_udistrital_edu_co/Ec8hb7OgBVdGmk9Rflk5NbUB4LmSpQhj-vH4vxGnJ_qsOw?e=tPRbZg

**Comment by norbeydanilo** [comment]
Ubucar documento en [carpeta ](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EnZT_ejF2eZFpxBUMKudD_wBa7p-rEc5ukzycC39V6suqQ?e=5excRf)

**Comment by Mechaz123** [comment]
Se sube el documento con una mejor visualización del contenido y en la carpeta especificada en esta Issue

**Comment by Mechaz123** [comment]
> Por favor relacionar pantallazos de la herramienta con la que se realizó la prueba de concepto.

Este es un ejemplo usando angular Schematics, cabe recalcar que la pregunta que aparece al momento de ejecutar el comando:
` ng g ../../../seed/src/collection.json:seed --dry-run=false`
Son modificables según la necesidad así mismo como el contenido que se agregue a lo generado:

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/102715e3-9a9b-489b-9250-e131bc16f73c)

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/fab806fa-b66c-45b8-b8d2-16b67f55382c)

![image](https://github.com/udistrital/planeacion_cliente/assets/73924638/7a760916-82c0-4167-be68-45edb93580b7)
