### ISSUE TITLE
1-5 Refactorización API planeacion_seguimiento_mid

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#972]
Se requiere refactorizar el API **PLANEACION_SEGUIMIENTO_MID** con base en el API **PLANEACION_MID**, de forma tal que los controladores asociados queden desacoplados del API principal.

**Especificaciones técnicas**

1. El repositorio para **PLANEACION_SEGUIMIENTO_MID** es: https://github.com/udistrital/planeacion_seguimiento_mid
2. Se requiere migrar los **nuevos controladores** (en caso de ser requerido) asociados a Seguimiento, del API **PLANEACION_MID** al API **PLANEACION_SEGUIMIENTO_MID**.
3. El API debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevas APIs GO definidos por la OATI.
4. De igual manera se deben implementar los respectivos controles de errores con base en lo evidenciado en:  [Tercero-mid](https://github.com/udistrital/sga_tercero_mid).
5. Se deben renombrar los endpoints con base en las directrices establecidas en los [lineamientos](https://github.com/udistrital/lineamientos_oas) y en las [buenas prácticas de desarrollo API REST](https://vicente-aguilera-perez.medium.com/las-10-mejores-pr%C3%A1cticas-para-nombrar-api-rest-endpoints-48b8bcbd1397) y con base en: #948 
6. Los métodos de utilidades que son globales a todas las APIs deben ser migrados a la librería **utils_oas**.
7. Se debe optimizar el código migrado, eliminando malas practicas de desarrollo.

**Sub Tareas**

- [x] Refactorización del API **PLANEACION_SEGUIMIENTO_MID**
- [x] Migración de nuevos endpoints.
- [x] Manejo correcto de errores.
- [x] Nombramiento adecuado.

**Criterios de aceptación**

- [x] El API se encuentra refactorizada y con manejo de errores.
- [x] Los nuevos endpoints son migrados.

**Requerimientos**

- [x] #803 
- [x] #863 

**Dependencias**

- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by felimarod** [comment]
![image](https://github.com/udistrital/planeacion_cliente/assets/85894335/cd40d867-7233-4fc4-9497-b34db6fb88e6)
No se tiene permiso al repositorio. Hasta el momento:
- Se han agregado los últimos cambios realizados en planeacion_mid respectivos a seguimiento
- Se han migrado 13 endpoints de 20, para que queden con los respectivos controles de errores y con la estructura definida de _services_

**Comment by felimarod** [comment]
Se migraron los endpoints faltantes con la estructura definida.

Se estan renombrando los endpoints para cumplir con las buenas practicas de nombramientos

**Comment by felimarod** [comment]
Reasignacion de las rutas
![seguimiento rutas](https://github.com/udistrital/planeacion_cliente/assets/85894335/7691fef2-03cd-47f8-b43b-32e3455b1953)

**Comment by a52290451** [comment]
Para finalizar la tarea se requiere completar los siguientes items:

1. Resumen de los cambios y optimizaciones realizados.
2. Confirmar si los métodos de utilidades se encuentran en utils_oas o no y realizar el respectivo ajuste.
3. Completar pruebas unitarias y funcionales.
4. Enviar PR a Develop.

**Comment by a52290451** [comment]
Correcciones requeridas en reasignación de rutas:

1. Cambiar "_" por "-" en las URIs

**Comment by a52290451** [comment]
@felimarod por favor realizar corrección y subir evidencia en la actividad

**Comment by felimarod** [comment]
Pruebas unitarias:
![image](https://github.com/udistrital/planeacion_cliente/assets/85894335/c7b289f7-4b1e-4c27-822f-bd4b811b2556)

**Comment by felimarod** [comment]
Necesito los permisos para poder subir la función nueva en utils_oas
![image](https://github.com/udistrital/planeacion_cliente/assets/85894335/498ddf1f-289d-4f10-9745-8a488d23d8b1)

**Comment by felimarod** [comment]
Resumen de cambios y optimizaciones: 
- Migración de nuevos endpoints.
    - Actualización de CrearReportes
    - Se agrega EstadoTrimestres
    - Se agrega VerificarSeguimiento
- Estructura y flujo tomando como ejemplo terceros_mid
    - Manejo correcto de errores según el ejemplo de terceros_mid.
      -  Creación de función StringAJson en utils_oas
    - Paso de lógica a services
- Cambio de nombres en endpoints
  - Separación en diferentes contextos
- Eliminación de códigos quemados
- Se separan las pruebas unitarias en diferentes documentos
- Se complementan las pruebas unitarias(parcialmente)
  > Los casos que faltan por pruebas requieren datos específicos que no se pueden sacar fácilmente del cliente

**Comment by a52290451** [comment]
@felimarod se concede acceso a utils_oas para subir los cambios realizados

**Comment by a52290451** [comment]
por favor realizar PR a Develop

**Comment by a52290451** [comment]
Se requiere realizar correcciones de acuerdo a lo señalado:

https://github.com/udistrital/planeacion_seguimiento_mid/pull/2#pullrequestreview-2007058907

**Comment by felimarod** [comment]
> @felimarod se concede acceso a utils_oas para subir los cambios realizados

Cambios subidos en https://github.com/udistrital/utils_oas/pull/44
Note que hay un problema con 2 paquetes en el archivo 
![image](https://github.com/udistrital/planeacion_cliente/assets/85894335/c756fb77-9925-4723-8a45-5973c1c0a983)
![image](https://github.com/udistrital/planeacion_cliente/assets/85894335/bafda78f-3fc0-4d7d-a085-2957528cbbdb)
Sin embargo preferí no solucionarlo ya que tal vez lohicieron en otra PR

**Comment by felimarod** [comment]
> Sin embargo preferí no solucionarlo ya que tal vez lohicieron en otra PR

Se actualizó el go.mod y go.sum después de hablarlo en reunión y llegar a la conclusión de solucionarlo.
Cambios listos en la PR https://github.com/udistrital/utils_oas/pull/44

**Comment by felimarod** [comment]
> Se requiere realizar correcciones de acuerdo a lo señalado:
> 
> [udistrital/planeacion_seguimiento_mid#2 (review)](https://github.com/udistrital/planeacion_seguimiento_mid/pull/2#pullrequestreview-2007058907)

Correcciones realizadas

**Comment by a52290451** [comment]
Se aprueba PR asociado a utils_oas: https://github.com/udistrital/utils_oas/pull/44

**Comment by a52290451** [comment]
Se realiza despliegue en ambiente de pruebas: https://github.com/udistrital/planeacion_seguimiento_mid/pull/3

**Comment by a52290451** [comment]
1. Ajuste de endpoints en APIs - De acuerdo a nueva revisión

Router:

/seguimiento/.../estado

/detalles

/actividades

/reportes

/indicadores

/periodos

- Desaparece /estado-trimestre ... pasan a /seguimiento

consultar: https://github.com/udistrital/planeacion_cliente/issues/948

**Comment by a52290451** [comment]
Router:

/seguimiento/.../estado

/detalles

/actividades

/reportes

/indicadores

/periodos

- Desaparece /estado-trimestre ... pasan a /seguimiento

consultar: https://github.com/udistrital/planeacion_cliente/issues/948

**Comment by felimarod** [comment]
## planeacion_seguimiento_mid

- [x] /habilitar_reportes [put] > /reportes/habilitar
- [x] /crear_reportes/:plan/:tipo [post] > /reportes/:plan/:tipo
- [x] /consultar_periodos/:vigencia [get] > /periodos/:vigencia
- [x] /consultar_actividades/:seguimiento_id [get] > /actividades/:seguimiento_id
- [x] /guardar_seguimiento/:plan_id/:index/:trimestre [put] > /:plan_id/:indiceActividad/:trimestreId
- [x] /consultar_seguimiento/:plan_id/:index/:trimestre [get] > /:planId/:indiceActividad/:trimestreId
- [x] /consultar_indicadores/:plan_id [get] > /:plan_id/indicadores
- [x] /consultar_avance [post] > /avance
- [x] /consultar_estado_trimestre/:plan_id/:trimestre [get] > /:plan_id/:trimestre/estado
- [x] /guardar_documentos/:plan_id/:index/:trimestre [put] > /detalles/documento/:plan_id/:index/:trimestre
- [x] /guardar_cualitativo/:plan_id/:index/:trimestre [put] > /detalles/detalles/cualitativo/:plan_id/:index/:trimestre
- [x] /guardar_cuantitativo/:plan_id/:index/:trimestre [put] > /detalles/cuantitativo/:plan_id/:index/:trimestre
- [x] /reportar_actividad/:index [put] > /reportes/actividad/:index
- [x] /reportar_seguimiento/:id [put] > /reportes/seguimiento/:id
- [x] /revision_actividad/:plan_id/:index/:trimestre [put] > /actividades/revision/:plan_id/:index/:trimestre
- [x] /revision_seguimiento/:id [put] > /:id/revision
- [x] /retornar_actividad/:plan_id/:index/:trimestre [put] > /actividades/retornar/:plan_id/:index/:trimestre
- [x] /migrar_seguimiento/:plan_id/:trimestre [post] > /:plan_id/:trimestre_id/migracion

**Comment by a52290451** [comment]
Se despliegan cambios realizados en ambiente de pruebas.

**Comment by a52290451** [comment]
Queda pendiente actualización de swagger.

**Comment by a52290451** [comment]
Se realiza corrección de bugs, según las pruebas realizadas por  @Oscarjaimes1710 y actualización de swagger.
