### ISSUE TITLE
1-6 Refactorización API planeacion_reportes_mid

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#973]
Se requiere refactorizar el API **PLANEACION_REPORTES_MID** con base en el API **PLANEACION_MID**, de forma tal que los controladores asociados queden desacoplados del API principal.

**Especificaciones técnicas**

1. El repositorio para **PLANEACION_REPORTES_MID** es: https://github.com/udistrital/planeacion_reportes_mid
2. Se requiere migrar los **nuevos controladores** (en caso de ser requerido) asociados a Reportes, del API **PLANEACION_MID** al API **PLANEACION_REPORTES_MID**.
3. El API debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevas APIs GO definidos por la OATI.
4. De igual manera se deben implementar los respectivos controles de errores con base en lo evidenciado en:  [Tercero-mid](https://github.com/udistrital/sga_tercero_mid).
5. Se deben renombrar los endpoints con base en las directrices establecidas en los [lineamientos](https://github.com/udistrital/lineamientos_oas) y en las [buenas prácticas de desarrollo API REST](https://vicente-aguilera-perez.medium.com/las-10-mejores-pr%C3%A1cticas-para-nombrar-api-rest-endpoints-48b8bcbd1397) y con base en: #948 
6. Los métodos de utilidades que son globales a todas las APIs deben ser migrados a la librería **utils_oas**.
7. Se debe optimizar el código migrado, eliminando malas practicas de desarrollo.

**Sub Tareas**

- [x] Refactorización del API **PLANEACION_REPORTES_MID**
- [x] Migración de nuevos endpoints.
- [x] Manejo correcto de errores.
- [x] Nombramiento adecuado.

**Criterios de aceptación**

- [x] El API se encuentra refactorizada y con manejo de errores.
- [x] Los nuevos endpoints son migrados.

**Requerimientos**

- [x] #803 .
- [x] #917 .
- [x] #928 .

**Dependencias**

- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Oscarjaimes1710** [comment]
Recordar hacer pruebas unitarias y pruebas funcionales.

**Comment by norbeydanilo** [comment]
Documentar issue @Oscarjaimes1710

**Comment by a52290451** [comment]
@Oscarjaimes1710 Por favor subir reporte de la actividad para finalización.

**Comment by Oscarjaimes1710** [comment]
Pruebas Funcionales : https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7Bb0b7ff47-932e-4e9f-ab88-aa2cef95afba%7D&action=editnew

**Comment by Oscarjaimes1710** [comment]
Link del repo : https://github.com/udistrital/planeacion_reportes_mid/tree/feature/refactor_reportes
Link de el pull : https://github.com/udistrital/planeacion_reportes_mid/pull/2

**Comment by a52290451** [comment]
Se validan y aprueban pruebas funcionales realizadas.

**Comment by a52290451** [comment]
Para la estructura y contenido del API, se requieren realizar los siguientes ajustes en la PARTE 2:

1. Migración de métodos de Helpers  a Services. Se deben migrar los siguientes métodos de los helpers a sus respectivos servicios:

- Validar -> ValidarReporte
- ProcesarDesagregado -> Desagregado
- ProcesarPlanAccionAnual -> PlanAccionAnual
- ProcesarPlanAccionAnualGeneral -> PlanAccionAnualGeneral
- ProcesarNecesidades -> Necesidades
- ProcesarPlanAccionEvaluacion -> PlanAccionEvaluacion

Con esto se busca eliminar una capa de abstracción he incluir la lógica de estos métodos al interior de los servicios correspondientes.

2. Adecuación de helpers para manejo de error a través de ErrorHandler en controllers.

- Se debe eliminar el manejo de error mediante panics y conducir estos de forma que logren ser retornados a sus respectivos controladores.

**Comment by a52290451** [comment]
El desarrollo se encuentra en ambiente de pruebas

**Comment by Oscarjaimes1710** [comment]
Desarrollo parte 2 Refactor planeacion_reportes_mid 
https://github.com/udistrital/planeacion_cliente/issues/973#issuecomment-2068270837

Se corren pruebas unitarias todo ok con la migración de métodos de Helpers a Services--->

<img width="613" alt="Captura de pantalla 2024-04-24 a la(s) 11 26 34 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/e26bb01d-a10c-4206-b48e-6dbc6b816361">
