### ISSUE TITLE
1-7 Refactorización API planeacion_evaluacion_mid

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#974]
Se requiere refactorizar el API **PLANEACION_EVALUACION_MID** con base en el API **PLANEACION_MID**, de forma tal que los controladores asociados queden desacoplados del API principal.

**Especificaciones técnicas**

1. El repositorio para **PLANEACION_EVALUACION_MID** es: https://github.com/udistrital/planeacion_evaluacion_mid
2. Se requiere migrar los **nuevos controladores** (en caso de ser requerido) asociados a Evaluación, del API **PLANEACION_MID** al API **PLANEACION_EVALUACION_MID**.
3. El API debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevas APIs GO definidos por la OATI.
4. De igual manera se deben implementar los respectivos controles de errores con base en lo evidenciado en:  [Tercero-mid](https://github.com/udistrital/sga_tercero_mid).
5. Se deben renombrar los endpoints con base en las directrices establecidas en los [lineamientos](https://github.com/udistrital/lineamientos_oas) y en las [buenas prácticas de desarrollo API REST](https://vicente-aguilera-perez.medium.com/las-10-mejores-pr%C3%A1cticas-para-nombrar-api-rest-endpoints-48b8bcbd1397) y con base en: #948 
6. Los métodos de utilidades que son globales a todas las APIs deben ser migrados a la librería **utils_oas**.
7. Se debe optimizar el código migrado, eliminando malas practicas de desarrollo.

**Sub Tareas**

- [x] Refactorización del API **PLANEACION_EVALUACION_MID**
- [x] Migración de nuevos endpoints.
- [x] Manejo correcto de errores.
- [x] Nombramiento adecuado.

**Criterios de aceptación**

- [x] El API se encuentra refactorizada y con manejo de errores.
- [x] Los nuevos endpoints son migrados.

**Requerimientos**

- [x] #803 .
- [x] #924 .

**Dependencias**

- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar issue @Oscarjaimes1710

**Comment by a52290451** [comment]
@Oscarjaimes1710 Por favor subir reporte de la actividad para finalización.

**Comment by norbeydanilo** [comment]
@Oscarjaimes1710 Por favor documentar, subir evidencias y reportar estado del desarrollo con @a52290451

**Comment by Oscarjaimes1710** [comment]
Estructura controlladores --->

<img width="843" alt="Captura de pantalla 2024-04-17 a la(s) 3 13 03 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/0a2b8782-f59a-4d68-9fd4-58e4d432edfc">


Estructura services --->

<img width="1169" alt="Captura de pantalla 2024-04-17 a la(s) 3 14 58 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/e779b19d-cbcd-4261-bdae-66ead2f3ee32">


Estructura carpetas --->
<img width="226" alt="Captura de pantalla 2024-04-17 a la(s) 3 15 40 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/233846dc-dfab-4ae9-97f3-1754debd57b3">


Ruta modificada --->
<img width="569" alt="Captura de pantalla 2024-04-17 a la(s) 3 16 29 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/301ec720-b5e9-492e-9689-35a1d1fbf259">

swagger actualizado con la nueva ruta --->

<img width="811" alt="Captura de pantalla 2024-04-17 a la(s) 3 17 13 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/e07d0b4c-c84c-48b8-bd14-98b5a7b2fd3d">

**Comment by Oscarjaimes1710** [comment]
Pruebas funcionales planeacion_evaluacion_mid : https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7BFE51C628-91DB-4A51-AA95-017C19680A3D%7D&file=Formato%20de%20registro%20de%20pruebas%20en%20el%20sistema.xlsx&action=default&mobileredirect=true

**Comment by Oscarjaimes1710** [comment]
Nuevas pruebas unitarias en con conformidad con los nuevos cambios En perfecto funcionamiento --->
<img width="557" alt="Captura de pantalla 2024-04-20 a la(s) 1 02 44 a  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/51cfa6d2-e6f5-46b1-811e-ff9af11518db">

**Comment by Oscarjaimes1710** [comment]
Autorizar permisos para hacer el push 

<img width="935" alt="Captura de pantalla 2024-04-20 a la(s) 1 19 19 a  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/b9b2dcb5-8fc5-4e3a-a1c2-3149439ca482">

**Comment by a52290451** [comment]
@Oscarjaimes1710 ya tienes permisos, por favor subir commit para validación final.

**Comment by Oscarjaimes1710** [comment]
Link del PR : https://github.com/udistrital/planeacion_evaluacion_mid/pull/3/commits/aa7ba5d13983db6bc6e7f7710c76cab8ab7d6e8c 

Link de el Repositorio:   https://github.com/udistrital/planeacion_evaluacion_mid/tree/feature/refactor_evaluacion :

**Comment by Oscarjaimes1710** [comment]
Se corren de nuevo pruebas unitarias de acuerdo a los ajustes solicitados : 

<img width="603" alt="Captura de pantalla 2024-04-24 a la(s) 6 40 28 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/e94824d0-881e-4278-be33-0a0f0df43e0f">

**Comment by a52290451** [comment]
Se despliega en ambiente de pruebas.

Queda pendiente registro en WSO2 y actualización de variables de entorno
