### ISSUE TITLE
Mantenimiento API notificaciones_mid

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#978]
Se requiere realizar el mantenimiento del API notificaciones_mid de tal forma que se puedan registrar notificaciones a múltiples usuarios en una misma cola.

**Especificaciones técnicas**

1. El Api de notificaciones se encuentra ubicado en: https://github.com/udistrital/notificacion_mid.
2. Se requiere ajustar la petición de registro de mensajes para que el mensaje permita registrar múltiples usuarios como destinatarios.
3. Se requiere revisar y ajustar tiempo de espera y cantidad de mensajes para que no sean una limitante a la hora de realizar peticiones.

**Sub Tareas**

- [x] Ajuste de petición de registro de mensajes para múltiples usuarios.
- [x] Ajuste de tiempo de espera y cantidad de mensajes. 

**Criterios de aceptación**

- [x] El API de notificaciones_mid permite registrar un mensaje para múltiples usuarios.
- [x] El API de notificaciones_mid es flexible en cuanto al manejo de tiempo de espera y cantidad de mensajes a consultar.

**Requerimientos**

- [x] Completar issue #862  .

**Dependencias**

- planeacion_cliente.
- notificacion_mid.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Se realiza el mantenimiento en notificacion_mid de tal manera que varios usuarios puedan recibir un mismo mensaje.

Se realiza la petición para el envio de mensajes donde contiene un Atributo llamado "IdUusarios", el cual contiene una lista de los usuarios a los cuales se les va a remitir el mesnaje (en donde se asocia el documento del usuario) para este caso se utilizan nombres de prueba: 
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/e3bb42c4-e9e7-43d7-9ad4-b6f975ce7b5f)

Al consultar los mensajes rgistrados en la cola, se obtienen dos mensajes registrados de manera independiente con la misma información enviada en la petición anterior (asunto y mensaje), y con un nuevo Atributo llamado "IdUsuario". Todo esto para poder asociar un único usuario con el mensaje de notificación (ya que si se tienen varios usuarios por mensaje en el momento de eliminar la notificación por que ya se dio el visto, la notificacaión se borraria para los diferentes usuarios asociados a ese mensaje):
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/ada288ec-e3bc-40b3-b744-b892cda727e2)
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/a5baaaaa-5fce-400d-9948-f9a8b62697dd)

**Comment by a52290451** [comment]
Queda pendiente PR a Develop.

No se requiere actualización de Swagger o variables de entorno.

**Comment by a52290451** [comment]
Se realiza despliegue en ambiente de pruebas. No se requieren correcciones:

https://github.com/udistrital/notificacion_mid/pull/48
