### ISSUE TITLE
Bug - Corrección de peticiones en la edición de plantillas.

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#987]
Se requiere realizar la corrección del bug asociado a la actualización de plantillas de planes de acción en el módulo de contrucción. Actualmente, cuando se requiere realizar una actualización de plantillas, esta no se actualiza.

**Especificaciones técnicas**

- Cuando se intenta actualizar campos en una plantilla, esta no se actualiza y tampoco se actualizan los planes de acción relacionados.
- Existe un problema al momento de consumir el endpoint relacionado en planeacion_mid.
- Para mayor información consultar las pruebas realizadas en #903 y #963 .

**Sub Tareas**

- [x] Corrección de Bug.

**Criterios de aceptación**

- [x] SISGPLAN permite la actualización de plantillas de planes de acción de forma correcta.

**Dependencias**

- No presenta

**Requerimientos**

- planeacion_mid
- planeacion_cliente

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegobauto** [comment]
Se corrige bug en rama: [feature/bugActPlantilla](https://github.com/udistrital/planeacion_mid/tree/feature/bugActPlantilla)

Dado que el error no requirio de grandes cambios (El codigo de abreviación para un plan en estado en formulación estaba como EF cuando debería ser EF_SP), se hace directamente el pull request: [Pull](https://github.com/udistrital/planeacion_mid/pull/504)

**Comment by diegobauto** [comment]
Evidencias de solución: 

Estado inicial de la plantilla:
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/76cadefa-3bee-49f1-9839-418199b0c3c3)

Se modifica el nombre del primer valor del primer nivel: 
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/93ae3326-434b-41bd-9ba7-09071c9fe1d9)

Aparece la ventana emergente que nos indica si queremos actualizar los planes asociados a la plantilla (confirmamos):
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/94593888-2e91-4584-8867-b55c1d8f4eb1)

Posteriormente se realiza el proceso para la actualización:
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/e531cca2-60cf-4893-8c0e-b9d8fe4a63f9)

El valor se modifica en la plantilla:
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/cb2bd8ec-2df0-4db5-8c5e-b620d746b18d)

Se hace una busqueda de cuales son los planes asociados:
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/d62498d6-f609-4e7f-af6c-67c23311a91b)
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/42eff12a-a8ad-43ed-ad9e-c347d48bfc52)

Y se comprueba que los planes asociados (id's), se hayan actualizado correctamente:
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/6c06bd66-00ea-4b23-971c-6dc8736a2e37)
![image](https://github.com/udistrital/planeacion_cliente/assets/64450601/11218251-f7a2-4d9e-bdc4-4d02b42ba9a8)

**Comment by a52290451** [comment]
Muchas gracias Diego, se realiza despliegue en ambiente de pruebas:

https://github.com/udistrital/planeacion_mid/pull/505

**Comment by a52290451** [comment]
Se requieren realizar pruebas adicionales ya que el bug aún sigue en ambiente de pruebas.

**Comment by a52290451** [comment]
El bug se soluciona en su totalidad. Queda desplegado en ambiente de pruebas.
