### ISSUE TITLE
Ajustar bugs cliente componte Identificación de contratistas y recurso 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#99]
Se debe ajustar los bugs encontrados  en el componente de identificación de contratistas y recursos, estos bugs son: 

- [x] Cambiar el flujo de guardado en el componente de identificación de contratistas  
- [x] Implementar el flujo de validación para los campos de la tabla de identificación de contratistas y recursos

**Comment by ndmc98** [comment]
Se da inicio a la issue el 02/11/2021

**Comment by ndmc98** [comment]
- Se cambia el flujo en el componente de identificación de contratistas.
- Se crea la validación de los campos de la tabla antes de realizar el proceso de guardado/envío. La validación se realiza a través de la revisión de los registros del datasource de la tabla.

**Comment by ndmc98** [comment]
Se genera el Pull Request para dar cierre a la issue. 03/11/2021

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
