### ISSUE TITLE
1-3 Refactorización API planeacion_formulacion_mid PT2

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#991]
Se requiere continuar con la refactorización del API **PLANEACION_FORMULACION_MID** con base en el API **PLANEACION_MID**, de forma tal que los controladores asociados queden desacoplados del API principal, en específico los de inversión.

**Especificaciones técnicas**

1. El repositorio para **PLANEACION_FORMULACION_MID** es: https://github.com/udistrital/planeacion_formulacion_e_inversion_mid/tree/feature/planeacion_formulacion
2. Se requiere migrar los **nuevos controladores** (en dado caso de darse el caso) asociado a Formulación, del API **PLANEACION_MID** al API **PLANEACION_FORMULACION_MID**, relacionados con inversion.
3. El API debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/logica_orientada_a_funciones.md) establecidos para la creación de nuevas APIs GO definidos por la OATI .
4. De igual manera se deben implementar los respectivos controles de errores con base en lo evidenciado en:  [Tercero-mid](https://github.com/udistrital/sga_tercero_mid).
5. Se deben renombrar los endpoints con base en las directrices establecidas en los [lineamientos](https://github.com/udistrital/lineamientos_oas) y en las [buenas prácticas de desarrollo API REST](https://vicente-aguilera-perez.medium.com/las-10-mejores-pr%C3%A1cticas-para-nombrar-api-rest-endpoints-48b8bcbd1397) y con base en: #948 
6. Los métodos de utilidades que son globales a todas las APIs deben ser migrados a la librería **utils_oas**.
7. Se debe optimizar el código migrado, eliminando malas practicas de desarrollo.
8. Actualizar readme.

**Sub Tareas**

- [x] Refactorización de API **PLANEACION_FORMULACION_MID** para el controlador inversion.
- [x] Migración de nuevos endpoints.
- [x] Manejo correcto de errores.
- [x] Nombrameniento adecuado.
- [x] Realización de pruebas unitarias para ambos controladores (inversion, formulacion)
- [x] Realización de pruebas funcionales.

**Criterios de aceptación**

- [x] El API se encuentra refactorizada y con manejo de errores.
- [x] Los nuevos endpoints son migrados.
- [x] Se realizan las respectivas pruebas requeridas.
- [x] Se actualiza el readme.

**Requerimientos**

- [x] Completar Issue #803 y #880 .

**Dependencias**

- planeacion_mid
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by C0C045** [comment]
# Avance en refactorización del API 'planeacion_formulacion_mid'
Los siguientes cambios ya se encuentran presentes en el commit: [12afc45](https://github.com/udistrital/planeacion_formulacion_mid/commit/12afc450295531c85d51f36dbe83bbcae2e7883f)

1. Se ajustaron cada una de las rutas de los controladores según lo planteado en 'https://github.com/udistrital/planeacion_cliente/issues/948#issuecomment-2028249802'
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/9d2d6915-f521-490b-a508-0fd52e2767d3)

2. Se modificó la estructura de los controladores según lo evidenciado en [Tercero-mid](https://github.com/udistrital/sga_tercero_mid/blob/develop/controllers/tercero_controller.go); dónde, podemos observar el uso de 'HandlePanic' y la separación de la lógica en 'services/inversion.go'
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/e20ab232-eb0f-4727-bfd1-b9cd48641580)

**Nota:** Para dar culminado el desarrollo e iniciar con cada una de las pruebas planteadas en el issue; faltaría realizar las pruebas unitarias para el controlador 'inversion.go'.

**Comment by C0C045** [comment]
# Refactorización del API 'planeacion_formulacion_mid'

Se implementaron cada una de las pruebas unitarias tipo Smoke posibles para los controladores de 'inversion.go', ya que algunas consultas requieren un objeto complejo que se construye a través de diferentes consultas anteriores.
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/b0e34689-ac5e-4ced-96a0-24a1fbd6e759)

**RESULTADOS:**
![image](https://github.com/udistrital/planeacion_cliente/assets/55455142/2ff89a14-4c3f-4ce3-aa8f-6f1751f13e52)

**Comment by C0C045** [comment]
# Pruebas Funcionales
Enlace de acceso: https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EcUy-b26qDtGrsfNFqflIGkBcp79nEfCIFV8BJ7NyGmErQ?e=GdRtnb

**Comment by C0C045** [comment]
# Pruebas Funcionales del Despliegue a Pruebas
Una vez realizadas las pruebas de todos los 'endpoints' posibles tanto en Formulación como en Inversión, se llegó a la conclusión que la migración fue exitosa, sin embargo, existen algunos 'endpoints' que reciben objetos complejos para realizar su función y por ende no pudieron ser probados a profundidad. Por último, los nuevos cambios de las rutas funcionan perfectamente también.

Enlace de acceso: https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EQ4P6NTtA7xNrI_uyHgVgAYBKa4Wn4CoQUv5nP_2Q_jQEg?e=HdRsod
