### ISSUE TITLE
2 - 3 Refactorización cliente planeacion_evaluacion_mf

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#992]
Se requiere refactorizar el MF **PLANEACION_EVALUACION_MF** con base en el API **PLANEACION_CLIENTE**, de forma tal que se culmine con la migración de componentes y se presente el cliente en su forma final.

**Especificaciones técnicas**

1. El repositorio para **PLANEACION_EVALUACION_MF** es: https://github.com/udistrital/planeacion_evaluacion_mf
2. Se requiere migrar los **nuevos desarrollos** (en caso de ser requerido) asociados a Evaluación, del cliente **PLANEACION_CLIENTE** al MF **PLANEACION_EVALUACION_MF**.
3. El Cliente debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevos Clientes definidos por la OATI.
4. Los componentes y servicios que son globales a todos los MF deben ser migrados al cliente **CORE** o de **UTILIDADES**.
5. Se debe optimizar el código migrado, eliminando malas practicas de desarrollo.
6. El MF debe quedar optimizado en estilos y con pruebas funcionales en su totalidad.
7. El MF debe consumir los endpoints asociados a los MicroMids desarrollados para SISGPLAN, en lugar de planeacion_mid.

**Sub Tareas**

- [x] Refactorización del cliente **PLANEACION_EVALUACION_MF**
- [x] Migración de nuevas funcionalidades.
- [x] Optimización de código.
- [ ] Ajuste de estilos.

**Criterios de aceptación**

- [x] El MF se encuentra refactorizado.
- [x] El MF cuenta con todas sus componentes y funcionalidades migrados.
- [x] El código del MF se encuentra optimizado.
- [ ] Los estilos del MF son los correspondientes a SISGPLAN.

**Requerimientos**

- [x] #974 .
- [x] #940 .

**Dependencias**

- planeacion_cliente
- planeacion_mid
- planeacion_evaluacion_mid
- planeacion_evaluacion_mf
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
@Oscarjaimes1710 se requiere cargar estado de la actividad.

**Comment by norbeydanilo** [comment]
@Oscarjaimes1710 Se solicita por favor actualizar el estado de la actividad. Documentar issue y dejar evidencia de commits.

**Comment by a52290451** [comment]
@Oscarjaimes1710 por favor subir actualización de la tarea.

**Comment by Oscarjaimes1710** [comment]
1. Se realiza la migracion de el nuevo desarrollo que se realizo hace 3 semanas donde se cambia el orden de las variables y también se agrega la funcionalidad de llamar todas las unidades y todos los periodos. 
Antes funcionaba así -->

<img width="681" alt="Captura de pantalla 2024-04-29 a la(s) 10 45 46 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/2fd117e4-0d4d-4632-9ec8-4838bfde3e1d">

 Ahora funciona asi : -->
<img width="1312" alt="Captura de pantalla 2024-04-29 a la(s) 10 46 37 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/04e7618c-0723-4e8b-b997-3f755a18817a">

2. Se actualizo el consumo de planeacion_evaluacion_mid antes lo consumida desde PLANES_MID ahora lo consume desde PLANEACION_EVALUACION_MID aqui esta el link del commit de actualización de los enviroments :https://github.com/udistrital/planeacion_evaluacion_mf/commit/34c2423a77f3576c9f748366cadbcb153d3596d8

3. Se esta trabajando actualmente en la actualización de las tablas para mostrar las gráficas con la nueva implementación de orden de variables, ya que actualmente no esta mostrando data los graficos.

**Comment by a52290451** [comment]
@Oscarjaimes1710 actualizar estado de la actividad, mencionando lo que hace falta para terminar.

**Comment by a52290451** [comment]
@Oscarjaimes1710 comentar estado actual de la issue y por qué no se han realizado pruebas funcionales.

**Comment by Oscarjaimes1710** [comment]
Actualmente se esta haciendo la revisión de el porque no pasan los planes de seguimiento a evaluación para poder realizar las pruebas funcionales del refactor del MF de evaluación. 

1. Se realiza la migración de el nuevo desarrollo que se realizo hace 3 semanas donde se cambia el orden de las variables y también se agrega la funcionalidad de llamar todas las unidades y todos los periodos. Link del commit : https://github.com/udistrital/planeacion_evaluacion_mf/commit/4dee57cfa95a92ad08f94888ce22f7df55f6bbb3 

2. Se actualizan los envioremnt añadiendo los micromids de consumo.

3.Se esta trabajando actualmente en la actualización de las tablas para mostrar las gráficas con la nueva implementación de orden de variables, ya que actualmente no esta mostrando data los gráficos.

4. Queda pendiente la carga de una optimización de código de estructuración de las carpetas en las validaciones del consumo de los micromids

**Comment by Oscarjaimes1710** [comment]
Se culmina el Refactor a falta de unas pruebas con planes que tengan valores , avance ( algun % ) y no todo en 0 para poder culminar las pruebas. 

1. Se migro todo lo que estaba en planeacion_cliente hacia planeacion_evaluacion_mf. 
<img width="524" alt="Captura de pantalla 2024-05-27 a la(s) 7 48 08 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/331f13c5-08e0-4b76-9e0c-17d42c6bf95b">

2.Se hace el refactor y migración de la tecnología google-charts a ngxcharts puesto que la versión del mf ya no permite el uso de google-charts 
<img width="461" alt="Captura de pantalla 2024-05-27 a la(s) 8 31 49 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/a9dac602-42fa-4602-a94b-1cf84a22ec2f">

3. Se optimiza el codigo y se eliminan funciones y variables que ya no se consumen. 

4. Se hace una actualización a planeacion_evaluacion_mid puesto que tenia el mismo error del bug del flujo de evaluacion ( Se actualiza el swagger).

Se modifica el consumo del controlador de getPlanesParaEvaluar a PlanesAEvaluar 
<img width="565" alt="Captura de pantalla 2024-05-27 a la(s) 8 33 32 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/a5f851b4-78f0-425a-b2ca-307e52927129">

5. en ese orden de ideas se actualizan los consumos de las consultas del mf hacia el micromid de evaluación
<img width="565" alt="Captura de pantalla 2024-05-27 a la(s) 8 34 54 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/d8e5533b-0a70-452b-9184-fa740445d7ea">

Se cargan pruebas del funcionamiento a falta de ajuste de basado en un plan que contenga datos de avance y no todo en 0 como se puede ver en las siguientes pruebas del flujo. 
<img width="1511" alt="Captura de pantalla 2024-05-27 a la(s) 8 15 17 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/7d409c99-ca38-4966-ac87-36373ce9a16e">
<img width="1511" alt="Captura de pantalla 2024-05-27 a la(s) 8 15 22 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/5f33297c-157a-45aa-aec1-b965deef096f">
<img width="1511" alt="Captura de pantalla 2024-05-27 a la(s) 8 15 29 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/12d5ab0a-64ca-4367-a0ba-71f60c74a7df">
<img width="750" alt="Captura de pantalla 2024-05-27 a la(s) 8 17 01 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/f590f92a-6fdc-42b1-8e69-87f1b31cb76a">
<img width="1114" alt="Captura de pantalla 2024-05-27 a la(s) 8 36 27 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/950660ed-92e5-4f81-a39e-66051d916a4c">

**Comment by Oscarjaimes1710** [comment]
Se proceden a cargar los correspondientes commits y PR's.

**Comment by a52290451** [comment]
Se requiere completar ajustes gráficos en el componente de evaluación antes de realizar el PR correspondiente. Adicionalmente, se requiere cargar un video con el funcionamiento final del MF.

**Comment by Oscarjaimes1710** [comment]
Para Dar fin a esta tarea se procede a cargar toda la evidencia del flujo 100% funcional y ajustado a lo previamente pactado.

<img width="1505" alt="Captura de pantalla 2024-06-03 a la(s) 4 13 47 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/26e6a8da-9f37-442d-a404-cbc4652708f8">
<img width="1505" alt="Captura de pantalla 2024-06-03 a la(s) 4 14 00 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/1c60baa6-4659-408a-9a2c-739c00bdf7a7">
<img width="1505" alt="Captura de pantalla 2024-06-03 a la(s) 4 14 22 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/2d2f6dc4-ed40-42c3-9690-eeffbaf024d8">
<img width="1512" alt="Captura de pantalla 2024-06-03 a la(s) 4 14 37 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/ec5182ce-9ab4-4ba2-bc94-a72f0de4dd78">
<img width="1505" alt="Captura de pantalla 2024-06-03 a la(s) 4 14 40 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/000f16fa-24dc-45a3-948d-5179fa572689">
<img width="1505" alt="Captura de pantalla 2024-06-03 a la(s) 4 14 46 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/aded308f-b556-4060-aaa5-e15410124bfd">
<img width="1505" alt="Captura de pantalla 2024-06-03 a la(s) 4 15 05 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/0d9f29b3-709c-424b-9dc9-5f44922f45ea">
<img width="1505" alt="Captura de pantalla 2024-06-03 a la(s) 4 15 57 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/d3261b5f-75a6-4f16-94df-cf8b4e4d10a5">
<img width="1505" alt="Captura de pantalla 2024-06-03 a la(s) 4 16 00 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/0799be59-7fbd-4e43-ad6c-e44a2c43a549">
<img width="1505" alt="Captura de pantalla 2024-06-03 a la(s) 4 16 03 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/37ff74a0-3096-4d9e-beda-0cbc3abcf03f">
<img width="1505" alt="Captura de pantalla 2024-06-03 a la(s) 4 16 11 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/3815715c-7757-4184-8f98-d128ebd8ba5a">

Resumen: 
1. Se Trae todo el desarrollo hecho en evaluación cliente para ajustarlo y re factorizar lo en el Mf 
2. Se hacen ajustes a las consultas que realizaba el planeacion_mid y el planeacion_evaluacion_mid para que los datos quedasen ajustados al formato de la lógica que ya estaba establecida.
3. Se eliminan algunas  funciones que no se estaban usando o consumiendo dentro del mf.
4. Se hacen ajustes a los estilos directamente en html previamente guiado por Steven Espejo.

A continuación se proceden a cargar los debidos Commits y pr con todos los cambios realizados.

**Comment by a52290451** [comment]
Queda pendiente revisr y aprobar PRs

**Comment by a52290451** [comment]
Se requiere revisar y mejorar PR:

https://github.com/udistrital/planeacion_evaluacion_mid/pull/9

**Comment by a52290451** [comment]
Se da cierre a la actividad con pruebas realizadas y Commits en Develop.
