### ISSUE TITLE
2 - 4 Refactorización cliente planeacion_reportes_mf

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#993]
Se requiere refactorizar el MF **PLANEACION_REPORTES_MF** con base en el API **PLANEACION_CLIENTE**, de forma tal que se culmine con la migración de componentes y se presente el cliente en su forma final.

**Especificaciones técnicas**

1. El repositorio para **PLANEACION_REPORTES_MF** es: https://github.com/udistrital/planeacion_reportes_mf
2. Se requiere migrar los **nuevos desarrollos** (en caso de ser requerido) asociados a Reportes, del cliente **PLANEACION_CLIENTE** al MF **PLANEACION_REPORTES_MF**.
3. El Cliente debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevos Clientes definidos por la OATI.
4. Los componentes y servicios que son globales a todos los MF deben ser migrados al cliente **CORE** o de **UTILIDADES**.
5. Se debe optimizar el código migrado, eliminando malas practicas de desarrollo.
6. El MF debe quedar optimizado en estilos y con pruebas funcionales en su totalidad.
7. El MF debe consumir los endpoints asociados a los MicroMids desarrollados para SISGPLAN, en lugar de planeacion_mid.

**Sub Tareas**

- [x] #1095
- [x] Migración de nuevas funcionalidades.
- [x] Optimización de código.
- [x] Ajuste de estilos.

**Criterios de aceptación**

- [x] El MF se encuentra refactorizado.
- [x] El MF cuenta con todas sus componentes y funcionalidades migrados.
- [x] El código del MF se encuentra optimizado.
- [x] Los estilos del MF son los correspondientes a SISGPLAN.

**Requerimientos**

- [x] #941 .
- [x] #973 .

**Dependencias**

- planeacion_cliente
- planeacion_mid
- planeacion_reportes_mid
- planeacion_reportes_mf
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Oscarjaimes1710** [comment]
Actualmente ya se trabaja en todo el refactor , se hacen commits para reportar la actualizacion en el core añadiendo el microfront al core y adicionalmente un commit para la actualizacion de los nuevos endpoint refactorizados en planeacion_reportes_mid 

Link de el commit 2: -https://github.com/udistrital/planeacion_reportes_mf/commit/f6b8bde5c7afdb087866817a2a7019cc5099fa3b

Link del commit 1: https://github.com/udistrital/planeacion_root_mf/commit/7917c78b8c9a7bf52ef0610c1637eed8bdce680f

**Comment by a52290451** [comment]
@Oscarjaimes1710 Incluir pruebas funcionales y cargar PR con los cambios realizados. Además, realizar un comentario indicando los cambios realizados en el MF.

**Comment by Oscarjaimes1710** [comment]
1. Se actualizan los consumos de los micromids. 
2. Se realiza optimización de código en la estructura de las carpetas y la validación de los consumos de los micromids
3. No hubo nuevos desarrollos por lo cual no se realizo migración de código. 
4. Queda pendiente la carga de pruebas funcionales en el Mf en local vs pruebas

**Comment by Oscarjaimes1710** [comment]
Se deja en stand-by el desarrollo y carga de pruebas de reportes_mf puesto que estamos analizando el flujo de un plan puesto que encontramos un error en la generación de reportes y presuntamente es debido a la estructura de las plantillas de los planes y parámetros en el flujo de cada plan.

**Comment by a52290451** [comment]
Se incluyen archivos guía para crear un plan con la estructura correcta:

[estructura de plan.docx](https://github.com/udistrital/planeacion_cliente/files/15383396/estructura.de.plan.docx)
[Construccion formato para la formulacion de planes de accion v2 1.pdf](https://github.com/udistrital/planeacion_cliente/files/15383397/Construccion.formato.para.la.formulacion.de.planes.de.accion.v2.1.pdf)

**Comment by norbeydanilo** [comment]
@a52290451 Dar cierre con actualización de estado y abordar faltantes en siguientes sprints. @Oscarjaimes1710

**Comment by Oscarjaimes1710** [comment]
La refactorización esta completa pero falla la data al imprimirla en el excel del reporte por una falla de la consulta con el id de armonización.
Se espera que salga asi y 
[Reporte(2).xlsx](https://github.com/udistrital/planeacion_cliente/files/15449187/Reporte.2.xlsx)
Sale asi: 
[Reporte(4).xlsx](https://github.com/udistrital/planeacion_cliente/files/15449188/Reporte.4.xlsx)

la consulta directa de reportes_mid sale asi : 
<img width="1464" alt="Captura de pantalla 2024-05-26 a la(s) 5 15 46 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/4857b510-666c-4b44-b504-ceafb88fa78b">
y es asi como deberia responder : 
<img width="1024" alt="Captura de pantalla 2024-05-26 a la(s) 5 16 41 p  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/18d9b57c-c4df-405d-9367-76660110822f">

**Comment by a52290451** [comment]
Se requiere realizar la corrección de los bugs encontrados y que el funcionamiento quede completamente igual al de planeacion_cliente.

**Comment by a52290451** [comment]
Se requiere realizar limpieza de archivo service, pasando funciones de utilidades a helpers

**Comment by a52290451** [comment]
Se requiere revisar y ajustar planeacion_reportes_mid de forma tal que no existan panics en los services:

https://github.com/udistrital/planeacion_reportes_mid/blob/develop/services/reportes_service.go

ademas, se deben migrar funciones de utilidades de services a helpers.

**Comment by a52290451** [comment]
Se requiere ajuste minimo en MF:

https://github.com/udistrital/planeacion_reportes_mf/pull/2#pullrequestreview-2110367768

**Comment by Oscarjaimes1710** [comment]
> Se requiere ajuste minimo en MF:
> 
> [udistrital/planeacion_reportes_mf#2 (review)](https://github.com/udistrital/planeacion_reportes_mf/pull/2#pullrequestreview-2110367768)

Ajuste realizado y commit cargado : https://github.com/udistrital/planeacion_reportes_mf/commit/a4ee957f1e408c5f8a9d63282497ecc2785056d1

**Comment by a52290451** [comment]
Queda pendiente evidencia de pruebas.

**Comment by Oscarjaimes1710** [comment]
[Reporte(11).xlsx](https://github.com/user-attachments/files/15830048/Reporte.11.xlsx)


<img width="1510" alt="Captura de pantalla 2024-05-23 a la(s) 9 08 21 a  m" src="https://github.com/udistrital/planeacion_cliente/assets/145817817/70b19dc4-22dd-4d40-811c-e2f2f3921b29">

Evidencia del funcionamiento del microfront

Queda pendientes cargar la ultima prueba con el microfront corriendo en pruebas.
