### ISSUE TITLE
2 - 6 Refactorización cliente planeacion_pendientes_mf

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#994]
Se requiere refactorizar el MF **PLANEACION_PENDIENTES_MF** con base en el API **PLANEACION_CLIENTE**, de forma tal que se culmine con la migración de componentes y se presente el cliente en su forma final.

**Especificaciones técnicas**

1. El repositorio para **PLANEACION_PENDIENTES_MF** es: https://github.com/udistrital/planeacion_pendientes_mf
2. Se requiere migrar los **nuevos desarrollos** (en caso de ser requerido) asociados a Pendientes, del cliente **PLANEACION_CLIENTE** al MF **PLANEACION_PENDIENTES_MF**.
3. El Cliente debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevos Clientes definidos por la OATI.
4. Los componentes y servicios que son globales a todos los MF deben ser migrados al cliente **CORE** o de **UTILIDADES**.
5. Se debe optimizar el código migrado, eliminando malas practicas de desarrollo.
6. El MF debe quedar optimizado en estilos y con pruebas funcionales en su totalidad.
7. El MF debe consumir los endpoints asociados a los MicroMids desarrollados para SISGPLAN, en lugar de planeacion_mid.

**Sub Tareas**

- [x] Refactorización del cliente **PLANEACION_PENDIENTES_MF**
- [x] Migración de nuevas funcionalidades.
- [x] Optimización de código.
- [x] Ajuste de estilos.

**Criterios de aceptación**

- [x] El MF se encuentra refactorizado.
- [x] El MF cuenta con todas sus componentes y funcionalidades migrados.
- [x] El código del MF se encuentra optimizado.
- [ ] Los estilos del MF son los correspondientes a SISGPLAN.

**Requerimientos**

- [x] #957 .

**Dependencias**

- planeacion_cliente
- planeacion_mid
- planeacion_pendientes_mf
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by felimarod** [comment]
## Migracion
No es requerida ya que PLANEACION_PENDIENTES_MF se encuentra al día y no se ha actualizado el modulo en PLANEACION_CLIENTE
## Optimización de código
Se renombran los componentes para quitar redundancias innecesarias
![image](https://github.com/udistrital/planeacion_cliente/assets/85894335/228e8247-ddb7-48c3-b72a-276a18b51867)

**Comment by a52290451** [comment]
@felimarod por favor enviar PR con correcciones finales

**Comment by felimarod** [comment]
Comparto error que se genera en ambos microfronted, considero que puede darse en el root_mf o en el core_mf
![image](https://github.com/udistrital/planeacion_cliente/assets/85894335/4ad7336b-4e13-493c-9705-b46ea606a5b0)

**Comment by felimarod** [comment]
Agrego el link a las [pruebas funcionales](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EW3XEHXSF_ZDvfIByWDMUzQBLFbEgWtsdkCg0gRu01GPvA?e=F1UJUe)

**Comment by a52290451** [comment]
Queda pendiente el ajuste del MF en cuanto a estilos y el despliegue en ambiente de pruebas.

**Comment by a52290451** [comment]
Se realiza solicitud para despliegue en ambiente de pruebas:

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=60673

**Comment by a52290451** [comment]
@felimarod se requiere actualizar README para este MF

**Comment by felimarod** [comment]
Se agrega evidencia de la actualización que se le hizo al README ¿algún detalle a cambiar?
![image](https://github.com/udistrital/planeacion_cliente/assets/85894335/89e44d46-f7cb-4308-8dc8-2283f1ac5ea5)

**Comment by a52290451** [comment]
@felimarod , hablo de planeacion_pendientes_mf no de planeacion_macroplanes_mf

![image](https://github.com/udistrital/planeacion_cliente/assets/36229498/5061caf3-daac-4de4-836e-a058cd45107f)
