### ISSUE TITLE
2 - 7 Refactorización cliente planeacion_macroplanes_mf

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#995]
Se requiere refactorizar el MF **PLANEACION_MACROPLANES_MF** con base en el API **PLANEACION_CLIENTE**, de forma tal que se culmine con la migración de componentes y se presente el cliente en su forma final.

**Especificaciones técnicas**

1. El repositorio para **PLANEACION_MACROPLANES_MF** es: https://github.com/udistrital/planeacion_macroplanes_mf
2. Se requiere migrar los **nuevos desarrollos** (en caso de ser requerido) asociados a Macroplanes, del cliente **PLANEACION_CLIENTE** al MF **PLANEACION_MACROPLANES_MF**.
3. El Cliente debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevos Clientes definidos por la OATI.
4. Los componentes y servicios que son globales a todos los MF deben ser migrados al cliente **CORE** o de **UTILIDADES**.
5. Se debe optimizar el código migrado, eliminando malas practicas de desarrollo.
6. El MF debe quedar optimizado en estilos y con pruebas funcionales en su totalidad.
7. El MF debe consumir los endpoints asociados a los MicroMids desarrollados para SISGPLAN, en lugar de planeacion_mid.

**Sub Tareas**

- [x] Refactorización del cliente **PLANEACION_MACROPLANES_MF**
- [x] Migración de nuevas funcionalidades.
- [x] Optimización de código.
- [ ] Ajuste de estilos.

**Criterios de aceptación**

- [x] El MF se encuentra refactorizado.
- [x] El MF cuenta con todas sus componentes y funcionalidades migrados.
- [x] El código del MF se encuentra optimizado.
- [ ] Los estilos del MF son los correspondientes a SISGPLAN.

**Requerimientos**

- [x] #951 .

**Dependencias**

- planeacion_cliente
- planeacion_mid
- planeacion_macroplanes_mf
- planes_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
@felimarod se requiere actualizar estado de la actividad.

**Comment by a52290451** [comment]
@felimarod Por favor actualizar la issue con los nuevos commits.

**Comment by felimarod** [comment]
No se tienen permisos para subir los cambios, hasta el momento se ha hecho el cambio para consumir los endpoints asociados a los MicroMids en todo el MF

**Comment by a52290451** [comment]
Se conceden permisos en planeacion_micromids_mf

**Comment by felimarod** [comment]
[Pruebas funcionales](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EbGw6OmV_kFPr_GoKh7B5tEBHria7YCYastF3vyzzi_wEQ?e=TkQqyM)

**Comment by felimarod** [comment]
- Se cambian las rutas
- Se cambia la estructura de carpetas por una más óptima
- Cambios en peticiones
    - Se hace el cambio por los endpoint de [PLANEACION_ARBOL_MID](https://github.com/udistrital/planeacion_arbol_mid)
    - Se cambia la estructura de las suscripciones para tener una estructura aprobada y no la antigua ya que sale que es 'deprecated'
- Se agregan e implementan tipos de datos
- Se elimina código muerto
- Se crea y utiliza un servicio para traer los códigos de los diferentes tipos de planes utilizados
- Se crea el componente de "En construcción"
    - Se arregla la traída de la imagen de fondo
- Se crea el componente consultar-planes el cual contiene la lógica para consultar pde y pi

**Comment by a52290451** [comment]
**QUEDA PENDIENTE**

1. Validar pruebas funcionales.
2. Desplegar en ambiente de pruebas.
3. Adecuación de estilos.

**Comment by a52290451** [comment]
Se validan y aprueban pruebas funcionales realizadas.

**Comment by a52290451** [comment]
Queda pendiente despliegue de infraestructura

**Comment by a52290451** [comment]
Se realiza solicitud para despliegue en ambiente de pruebas:

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=60674
