### ISSUE TITLE
Revisión y optimización de manejo de lógica en Mensajes de confirmación (Ventanas emergentes).

### ISSUE THREAD

**Issue by a52290451** [udistrital/planeacion_cliente#996]
Es necesario optimizar la lógica de los mensajes de alerta en el cliente de planeación_cliente para evitar que contengan algún tipo de lógica interna relacionada, a excepción de los mensajes de confirmación.

**Especificaciones Técnicas**

- Algunos mensajes de alerta tienen lógica interna vinculada al botón "OK", lo cual plantea un problema. Los mensajes de alerta no deben depender de esta lógica interna, ya que si un usuario decide cerrar la alerta o salir de la página sin presionar "OK", la lógica vinculada no se ejecutaría. Para solucionar esto, es necesario separar esta lógica del mensaje de alerta, colocándola fuera antes de que se muestre la alerta. Esto garantiza que la lógica se ejecute independientemente de la interacción con la alerta.
- En caso de tratarse de un mensaje de confirmación, estos si deben tener lógica interna que se ejecute dependiendo de la opción elegida por el usuario. En este caso, se debe asegurar que el usuario no pueda cerrar el mensaje de confirmación dando clic en un lugar diferente a las opciones definidas por el mensaje.

**Sub Tareas**

- [ ] Ajuste de mensajes de alerta en planeacion_cliente.
- [ ] Verificación y ajuste de mensajes de confirmación en planeacion_cliente.

**Criterios de aceptación**

- [ ] El sistema presenta un funcionamiento correcto cuando presenta mensajes de alerta y de confirmación.

**Requerimientos**

No aplica

**Dependencias**

- planeacion_cliente

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Oscarjaimes1710** [comment]
Se Carga el pr correspondiente con todos los cambios generados para esta optimización. 

- Se realiza la revisión de un aproximado de 724 Swal.fire buscando optimizar lo que se dicta en esta issue , adicionalmente se hace un análisis de los mensajes de alerta o de carga que necesitaban un ajuste (bloqueo de ventana hasta terminar la carga) para que el funcionamiento sea correcto, aunque los mensajes de carga se podían cerrar y el cargaba posteriormente a su cierre se bloquean hasta acabar su carga y ahí si liberar la ventana de swal para que el funcionamiento sea optimo, adicionalmente se analizan todos los swal de confirmación con botones como continuar, si , no y cancelar entre otros encontrándose con bastantes de estos con la opción de cerrarse sin ejecutar una acción aunque el swal estuviese esperando una respuesta, se procede a bloquearlos y así hacer que se cumpla la lógica implícita.
