### ISSUE TITLE
Capacitación de MF y Pólux

### ISSUE THREAD

**Issue by milo19980525** [udistrital/planeacion_cliente#999]
Se requiere preparar y desarrollar dos capacitaciones para desarrollarlas de manera sincrónica virtual para integrantes del equipo de inversión.

**Subtareas**

- [x] Realizar una presentación y ejemplo práctico acerca de los microfrontends.
- [x] Realizar un ejemplo sobre el sistema Pólux.

**Criterios de aceptación**

- [x] Documentar la issue con el material preparado.
- [x] Asistir y participar con base en lo establecido en las diferentes reuniones.

**Comment by Mechaz123** [comment]
Se desarrolló la siguiente diapositiva relacionada a la capacitación de acerca de Microfrontends:

[Capacitacion Microfrontends.pptx](https://github.com/udistrital/planeacion_cliente/files/15043799/Capacitacion.Microfrontends.pptx)

Se desarrolló un ejemplo practica para la explicación del funcionamiento del root, que función tiene el core y un microfrontend de ejemplo.

![Image](https://github.com/udistrital/planeacion_cliente/assets/73924638/292b39d8-2bcf-4c2e-ab9c-d7329a633ffe)

Por otra parte, se realizó la capacitación en polux en el ambiente de producción, cabe aclarar que al parecer el perfil de pruebasarte, fue eliminado o se hicieron cambios ya que se intenta acceder al perfil y no se encuentra, se revisó en WSO2 y al parecer no fue encontrado.
